bingoGenerator = require("./generators/generator_bases/simple_generator.js");
//Made By TK
var bingoList =
[{"name": "100% riverbed flight"},
{"name": "100% riverbed canyon"},
{"name": "100% tunnels"},
{"name": "100% anthill"},
{"name": "100% cliffside"},
{"name": "100% training"},
{"name": "60 combined grains in anthill and city entrance"},
{"name": "60 combined grains in tunnels and riverned flight"},
{"name": "60 combined grains in cliffside and riverbed canyon"},
{"name": "60 combined grains in city square and the tree"},
{"name": "60 combined grains in clover forest and anthill part2"},
{"name": "25 grains in both the tree and riverbed flight"},
{"name": "25 grains in both  city square and anthill part2"},
{"name": "25 grains in both cliffside and clover forest"},
{"name": "25 grains in both tunnels and city entrance"},
{"name": "25 grains in both anthill and riverbed canyon"},
{"name": "4+ tokens in anthill and riverbed canyon"},
{"name": "4+ tokens in tunnels and council chamber"},
{"name": "4+ tokens in cliffside and city entrance"},
{"name": "4+ tokens in city square and riverbed flight"},
{"name": "4+ tokens in clover forest and battle arena"},
{"name": "4+ tokens in anthill part2 and bugbar"},
{"name": "4+ tokens in the tree and bird nest"},
{"name": "2 grain tokens"},
{"name": "grain token in council chamber"},
{"name": "grain token in riverbed canyon"},
{"name": "grain token in city entrance"},
{"name": "grain token in tunnels"},
{"name": "grain token in bugbar"},
{"name": "2 flik tokens"},
{"name": "flik token in anthill part2"},
{"name": "flik token in the tree"},
{"name": "flik token in city square"},
{"name": "flik token in riverbed flight"},
{"name": "flik token in hopper"},
{"name": "2 enemies tokens"},
{"name": "enemy token in bird"},
{"name": "enemy token in battle arena"},
{"name": "enemy token in clover forest"},
{"name": "enemy token in cliffside"},
{"name": "enemy token in anthill"},
{"name": "collect all berries types(5 colours)"},
{"name": "collect 10 berries"},
{"name": "collect 2 gold berries and 2 green berries"},
{"name": "collect 2 blue berries and 2 purple berries"},
{"name": "collect 2 gold berries and 2 blue berries"},
{"name": "collect 2 green berries and 2 purple berries"},
{"name": "use a canon and super jump"},
{"name": "use all seeds colours(5)"},
{"name": "grow 20 seeds"},
{"name": "Kill a grasshopper in 4 levels"},
{"name": "kill a spider in 5 levels"},
{"name": "ELP anthill and anthill part2"},
{"name": "ELP tunnels and the tree"},
{"name": "ELP cliffside and riverbed flight"},
{"name": "ELP riverbed canyon and clover forest"},
{"name": "ELP city entrance and city square"},
{"name": "ELP anthill and riverbed flight"},
{"name": "ELP tunnels and anthill part2"},
{"name": "ELP cliffside and the tree"},
{"name": "ELP riverbed canyon and city square"},
{"name": "ELP city entrance and clover forest"},
{"name": "ELP anthill and the tree"},
{"name": "ELP tunnels and clover forest"},
{"name": "ELP cliffside and anthill part2"},
{"name": "ELP riverbed canyon and city entrance"},
{"name": "ELP riverbed flight and city square"},
{"name": "Defeat thumper and molt"},
{"name": "Defeat bird and thud"},
{"name": "Defeat hopper"},
{"name": "Finish a Bonus level"},
{"name": "150 grains"},
{"name": "7 tokens"},
{"name": "13 tokens"},
{"name": "ELP 5 levels"},
{"name": "Defeat 3 bosses"},
{"name": "use 5 telescopes"},
{"name": "use 3 harvesters"},
{"name": "ELP 2 levels without getting anything in them"}];
