bingoGenerator = require("./generators/generator_bases/simple_generator_alttp.js");

var bingoList = [
    "Defeat Armos",
    "Defeat Lanmolas",
    "Defeat Moldorm",
    "Defeat Agahnim",
    "Defeat Helmasaur King",
    "Defeat Arrghus",
    "Defeat Mothula",
    "Defeat Blind",
    "Defeat Kholdstare",
    "Defeat Vitreous",
    "Die to Trinexx",
    "Desert Palace Big Chest",
    "Tower of Hera Big Chest",
    "Palace of Darkness Big Chest",
    "Swamp Palace Big Chest",
    "Skull Woods Big Chest",
    "Thieves' Town Big Chest",
    "Ice Palace Big Chest",
    "Misery Mire Big Chest",
    "Turtle Rock Big Chest",
    "Desert Palace Compass",
    "Tower of Hera Compass",
    "Palace of Darkness Compass",
    "Swamp Palace Compass",
    "Skull Woods Compass",
    "Thieves' Town Compass",
    "Ice Palace Compass",
    "Misery Mire Compass",
    "Turtle Rock Compass",
    "Desert Map",
    "Hera Map",
    "Darkness Map",
    "Swamp Map",
    "Skull Map",
    "Thieves' Map",
    "Ice Map",
    "Mire Map",
    "TRock Map",
    "Open 5 Small Key Doors (Palace of Darkness)",
    "Open 4 Small Key Doors (Skull Woods)",
    "Open 6 Small Key Doors (Ice Palace)",
    "Open 6 Small Key Doors (Misery Mire)",
    "Open Purple Chest",
    "Break Ether Monolith",
    "Break Bombos Monolith",
    "Open Misery Mire",
    "Open Turtle Rock",
    "Death Mountain Lonely Island",
    "Lumberjack Tree",
    "Byrna Cave",
    "Mimic Cave",
    "Lake Hylia Island",
    "Bonk Grave",
    "Rescue the Dwarf",
    "Speak to Fat Faerie",
    "Perfect Archery Game",
    "3 Whirlpool Pairs",
    "Spend 1000 rupees",
    "Spend 1500 rupees",
    "40 Arrows",
    "50 Arrows",
    "20 Bombs",
    "30 Bombs",
    "40 Arrows and 20 Bombs",
    "8 Heart Pieces",
    "12 Heart Pieces",
    "4 Heart Containers",
    "6 Heart Containers",
    "10+ Total Hearts",
    "12+ Total Hearts",
    "Master Sword Pedestal",
    "2 Pendants",
    "2 Crystals",
    "3 Crystals",
    "2 Light World Dungeons",
    "3 Light World Dungeons",
    "2 Dark World Dungeons",
    "3 Dark World Dungeons",
    "Bomb open a cracked floor in any dungeon",
    "Bomb open a cracked door in any dungeon",
    "Move or destroy a wall in any dungeon",
    "Hit Crystal Switch with Frozen Enemy",
    "Read 3 Dark World Dungeon Telepathic Tiles",
    "2 Dungeon Blue Rupee Rooms",
    "Spawn a chest in 2 dungeons",
    "Collect Sahasrahla's Prize",
    "Pull a Tounge Statue",
    "Clear 2 Tile Rooms",
    "Finish in a Light World Dungeon Fairy Room",
    "Finish in a Dark Room",
    "Finish in a Rupee Floor Room",
    "Finish in a Trap Room",
    "Finish in a Prison Cell",
    "Finish in a Room with a Bumper",
    "Finish in a Room with an Orange Warp",
    "Finish as a Bunny",
    "Defeat all 6 Freezors",
    "Collect the Bow",
    "Collect the Lantern",
    "Collect the Hookshot",
    "Collect a Medallion",
    "Activate the Flute",
    "Bottled Bee",
    "Bottled Faerie",
    "Bottled Potion",
    "Lantern or Fire Rod",
    "Collect Rod + Cane of the same color",
    "Collect Rod + Cane of opposite colors",
    "3 A-Items",
    "Upgrade Shield",
    "Upgrade Sword",
    "Visit the Catfish with a Follower",
    "Pay the Hamburger Helper Hand",
    "Buy from 2 Shops in each World",
    "4 NPC/Object Followers",
    "Reveal a Hidden Cave under a rock in both Worlds",
    "Complete 1 Line of Y-Items"
];
