bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Assess 2 fossils",
    "Assess 3 fossils",
    "Assess 4 fossils",
    "Assess a fossil",
    "Build 5 DIYs",
    "Build a DIY including flowers",
    "Build a DIY including fruit",
    "Build a DIY including hard wood",
    "Build a DIY including iron",
    "Build a DIY including soft wood",
    "Build a DIY including sticks",
    "Build a DIY including stone",
    "Build a DIY including weeds",
    "Build a fishing pole",
    "Build a gold DIY",
    "Build a ladder",
    "Build a net",
    "Build a shovel",
    "Build a slingshot",
    "Buy 2 pairs of footwear",
    "Buy 3 Hats",
    "Buy 3 hats",
    "Buy 3 nook miles tickets",
    "Buy 3 pairs of glasses",
    "Buy 3 pairs of pants",
    "Buy 3 pairs of shorts",
    "Buy 3 pairs of tights/socks",
    "Buy 3 shirts",
    "Buy 3 sweaters",
    "Buy a rug from Sahara",
    "Buy a tank",
    "Buy any floor",
    "Buy any wallpaper",
    "Buy from Redd",
    "Buy something from ABD",
    "Catch 10 sea creatures (swimming)",
    "Catch 3 butterflies",
    "Catch 3 ocean fish",
    "Catch 3 pond fish",
    "Catch 3 river fish",
    "Catch 5 bugs",
    "Catch 5 fish",
    "Catch 5 sea creatures (swimming)",
    "Catch a large fish",
    "Catch a medium fish",
    "Catch a scorpion/tarantula",
    "Catch a sea bass",
    "Catch a small fish",
    "Catch a wasp",
    "Change your outfit",
    "Chop down 1 tree",
    "Complete 5 daily challenges",
    "Deposit bells in ABD",
    "Design an article of clothing",
    "Dig up 10 clams",
    "Dig up 2 fossils",
    "Dig up 3 fossils",
    "Dig up 4 fossils",
    "Dig up a fossil",
    "Display artwork",
    "Dive off the dock",
    "Do yoga with a villager",
    "Fix Gulliver's phone",
    "Get 10 sticks from shaking trees",
    "Get 5 sticks from shaking trees",
    "Get a star fragment",
    "Heal a wasp sting",
    "Hit 2 rocks",
    "Hit the money rock",
    "Learn a new DIY",
    "Learn about something from Blathers",
    "Mail a letter to a friend",
    "Mail a letter to a villager",
    "Make 10 fish bait",
    "Make 5 fish bait",
    "Make a bamboo DIY",
    "Make a clay DIY",
    "Make a new design",
    "Make a pumpkin DIY",
    "Move a building/house",
    "Pick up 10 shells",
    "Pick up 5 shells",
    "Pick up a conch",
    "Pick up a giant clam",
    "Pick up a message in a bottle",
    "Place 10 fence sections",
    "Place 20 fence section",
    "Place a path",
    "Plant 5 cosmos seeds",
    "Plant 5 flower seeds",
    "Plant 5 lily seeds",
    "Plant 5 rose seeds",
    "Plant 5 windflower seeds",
    "Plant a new money tree",
    "Plant orange flower seeds",
    "Plant red flower seeds",
    "Plant white flower seeds",
    "Plant yellow flower seeds",
    "Receive 8 items from a single rock",
    "Receive a DIY from a villager",
    "Receive clothing from a villager",
    "Sell 10 fruits",
    "Sell 10 weeds to Leif",
    "Sell 3 apples",
    "Sell 3 cherries",
    "Sell 3 oranges",
    "Sell 3 peaches",
    "Sell 3 pears",
    "Sell 4 coconuts",
    "Sell 5 foreign fruits",
    "Sell 5 native fruits",
    "Sell a hot item",
    "Sell the same bug 5 times",
    "Sell weeds to Leif",
    "Shake a tree 10 times",
    "Shoot down a present",
    "Spend 1000 Nook Miles",
    "Spend 2000 Nook Miles",
    "Take a photo with a villager",
    "Take a seated photo with a villager (both seated)",
    "Talk to 3 non-villager NPCs",
    "Talk to 5 non-villager NPCs",
    "Talk to 5 villagers",
    "Talk to a non-villager NPC",
    "Use a fruit to dig up a tree",
    "Use a wand",
    "Use vaulting pole 10 times",
    "Visit a Bamboo Island",
    "Visit any mystery Island",
    "Water 10 flowers",
    "Water 15 flowers",
    "Water 20 flowers",
    "Withdraw bells from ABD",
    "Work out with a villager"
];
