bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingolist = [
	"Ace a Spongebob level",
	"Ace a Patrick level",
	"Ace a Squidward level",
	"Ace a Mr.Krabs level",
	"Beat a boss twice",
	"Complete the Sand Maze without using the flashlight",
	"Complete the Glove World maze without using the flashlight",
	"Stop Left Glovey 10 times in the Glove World Maze",
	"Beat Patrick in the jellyfishing contest",
	"Collect the treasure from Big Lenny as Spongebob",
	"Interact with the gun in Squidward's Monument"
	"Beat any level twice",
	"Die to Big Lenny",
	"Complete the Toys This Way room without using the flashlight",
	"Complete the Prowler Punchout tutorial",
	"Enter Pearl's bedroom after she has started sleepwalking",
	"Place the Berry plush onto the shelf",
	"Find Mr.Krab's first dime",
	"Hit a squid guard with a rock",
	"Beat Berry in hide & seek as Squidward",
	"Defeat Iron Dogfish",
	"Give Berry his boxy",
	"Beat Barg'N-Mart after your cover is blown",
	"SQUARE",
	"Escape an Angler's sight after it has seen you",
	"Escape 3 different Belchers",
	"Enter a stall in the men's and women's bathroom",
	"Die to Mrs.Puff while you have a student with you",
	"Find Sans",
	"Beat Berry in a race",
	"Complete the middle hive last in Goofy Goobers",
	"Complete Mermalair without using the lanturn",
	"Place the berry statue on the pedestal in Mermalair",
	"Defeat Plankton",
	"Kick Me Here!",
	"Get the token from Industrial Park",
	"Beat Berry in hide & seek as Spongebob",
	"Have a Boxing Menace spot you in Larry's Gym and live",
	"Beat Larry's Gym"
	"Take the bottom path in Jellyfish Fields",
	"Take the top path in Jellyfish Fields",
	"Beat Ol' Bessy & the Jellybee",
	"Beat Weenie Hut Juniors without glitches",
	"Get Berry a sombrero",
	"Run inside Sandy's Treedome",
	"Beat ???-Krusty Krab with Patrick or Mr.Krabs at one heart",
	"Take a photo of all Parasitic Worms in ???-Rock Bottom",
	"Defeat Doodle Patrick",
	"Defeat the Overlord",
	"Get a B rating in any level"
];