bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "10 lair Mumbo tokens",
    "10 notes",
    "12 Mumbo tokens",
    "16 Mumbo tokens",
    "20 Mumbo tokens",
    "20 notes",
    "24 Mumbo tokens",
    "30 notes",
    "4 Mumbo tokens",
    "40 notes",
    "5 Mumbo tokens in Memory Meadow",
    "5 lair Mumbo tokens",
    "50 notes",
    "6 HP",
    "60 notes",
    "7 HP",
    "70 notes",
    "8 HP",
    "8 Mumbo tokens",
    "Alien zone notes in Highlight Heights",
    "All 1 Mumbo token in Lunar Landing",
    "All 4 Mumbo tokens in Glowing Gardens",
    "All 4 Mumbo tokens in Highlight Heights",
    "All 4 Mumbo tokens in Sparkling Springs",
    "All 4 Mumbo tokens in Twinkling Tunnels",
    "All 5 Mumbo tokens in zone 4 in Memory Meadow",
    "All 9 Mumbo tokens in Memory Meadow",
    "All honeycombs in Glowing Gardens",
    "All honeycombs in Highlight Heights",
    "All honeycombs in Lunar Landing",
    "All honeycombs in Memory Meadow",
    "All honeycombs in Sparkling Springs",
    "All honeycombs in Twinkling Tunnels",
    "All honeycombs in the lair",
    "All notes in Glowing Gardens",
    "All notes in Highlight Heights",
    "All notes in Lunar Landing",
    "All notes in Memory Meadow",
    "All notes in Sparkling Springs",
    "All notes in Twinkling Tunnels",
    "Asteroid zone notes in Lunar Landing",
    "Big tree zone notes in Glowing Gardens",
    "Blubber zone notes in Sparkling Springs",
    "Christmas zone notes in Highlight Heights",
    "Dupeable Mumbo token x3 in Sparkling Springs",
    "Gold mine zone notes in Twinkling Tunnels",
    "Main area notes in Glowing Gardens",
    "Main area notes in Highlight Heights",
    "Main area notes in Lunar Landing",
    "Main area notes in Sparkling Springs",
    "Main area notes in Twinkling Tunnels",
    "Maze zone notes in Glowing Gardens",
    "Mumbo token under the boat in Sparkling Springs",
    "Mushroom zone notes in Glowing Gardens",
    "Pink ice zone notes in Highlight Heights",
    "Station zone notes in Lunar Landing",
    "Sun zone notes in Lunar Landing",
    "Talk to 1 Bottles",
    "Talk to 3 Bottles",
    "Talk to 5 Bottles",
    "Talk to 7 Bottles",
    "Talk to 9 Bottles",
    "Underwater zone notes in Twinkling Tunnels",
    "Void zone notes in Twinkling Tunnels",
    "Volcano zone notes in Sparkling Springs",
    "Water zone notes in Sparkling Springs",
    "Zone 1 notes in Memory Meadow",
    "Zone 2 notes in Memory Meadow",
    "Zone 3 notes in Memory Meadow",
    "Zone 4 notes in Memory Meadow",
    "Zone 5 notes in Memory Meadow"
];
