bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "1 Spatula from Mr. Krabs",
    "1 Spatula from Patrick",
    "2 Spatulas from Mr. Krabs",
    "2 Spatulas from Patrick",
    "3 Spatulas from Patrick",
    "Across the Dreamscape",
    "Ambush at Tree-Dome",
    "Ambush in Lighthouse",
    "Annoy Squidward",
    "Ball Room Sock",
    "Bikini Bottom: All Socks (8)",
    "Bikini Bottom: All Spatulas (8)",
    "Clear Bumper Boats",
    "Computer Room Sock",
    "Connect the Towers",
    "Defeat Flying Dutchman",
    "Defeat Prawn",
    "Destroy the Robot Ship",
    "Down in the Swamp",
    "Downtown Copper Building Sock",
    "Downtown Copper Platform Sock",
    "Downtown Rock Bottom: All Socks (3)",
    "Downtown Rock Bottom: All Spatulas (4)",
    "Downtown Rooftops: All Socks (3)",
    "Downtown Rooftops: All Spatulas (2)",
    "Downtown Streets: All Socks (4)",
    "Downtown Streets: All Spatulas (3)",
    "Downtown: All Socks (9)",
    "Downtown: All Spatulas (8)",
    "Drain the Lake",
    "Dream: All Socks (5)",
    "Dream: All Spatulas (8)",
    "Dreamscape: All Spatulas (3)",
    "Dumpster Sock",
    "Duplicatotron Pier Sock",
    "End of the Road",
    "Extreme Bungee",
    "Find All Lost Campers",
    "Flounder Hill Sandman Sock",
    "Flounder Hill: All Socks (2)",
    "Flounder Hill: All Spatulas (2)",
    "Follow Bouncing Ball",
    "Frosty Bungee",
    "Funnel Machines",
    "Gated Jellyfish Caves Sock",
    "Get Aloft There, Matey",
    "Goo Lagoon Beach: All Socks (5)",
    "Goo Lagoon Beach: All Spatulas (3)",
    "Goo Lagoon Pier: All Socks (3)",
    "Goo Lagoon Pier: All Spatulas (3)",
    "Goo Lagoon: All Socks (11)",
    "Goo Lagoon: All Spatulas (8)",
    "Graveyard Lake Sock",
    "Graveyard Lake: All Spatulas (3)",
    "Graveyard: All Socks (3)",
    "Graveyard: All Spatulas (8)",
    "Grill Sock",
    "Guppy Mound: All Socks (3)",
    "Guppy Mound: All Spatulas (2)",
    "Here You Go",
    "How in Tarnation",
    "Ice Pillar Sock in Slide 3",
    "Infestation at Krusty Krab",
    "Inside Downtown Fallen Building Sock",
    "Jellyfish Barrel Island Sock",
    "Jellyfish Bowling Sock",
    "Jellyfish Caves: All Socks (4)",
    "Jellyfish Caves: All Spatulas (2)",
    "Jellyfish Fields: All Socks (14)",
    "Jellyfish Fields: All Spatulas (8)",
    "Jellyfish Fountain Sock",
    "Jellyfish Lake: All Socks (3)",
    "Jellyfish Rock: All Socks (6)",
    "Jellyfish Rock: All Spatulas (3)",
    "Kah - Rah - Tae",
    "Kelp Caves Sock",
    "Kelp Forest: All Socks (7)",
    "Kelp Forest: All Spatulas (8)",
    "Kelp Swamp: All Socks (2)",
    "Kelp Tiki Bowl Sock",
    "Kelp Vines Sock",
    "Kelp Woods: All Socks (3)",
    "Kelp Woods: All Spatulas (2)",
    "King of the Castle",
    "Krabby Patty Platforms",
    "Krusty Sock",
    "Lasers are Fun",
    "Learn Sandy's Moves",
    "Lodge Sandman Sock",
    "Mermaid Man Time Challenge",
    "Mermalair Lobby Sock",
    "Mermalair Main Chamber: All Spatulas (4)",
    "Mermalair: All Socks (4)",
    "Mermalair: All Spatulas (8)",
    "Music in the Ear of the Beholder",
    "Navigate Canyons and Mesas",
    "Patrick's Dilemma",
    "Patrick's Rock Sock",
    "Pineapple Sock",
    "Plundering Robots in Museum",
    "Power Crystal Crisis",
    "Return Museum's Art",
    "Robot Ship Sock",
    "Rock Bottom Museum: All Socks (3)",
    "Rock Bottom: All Socks (9)",
    "Rock Bottom: All Spatulas (8)",
    "Rolling Ball Room",
    "Sand Mountain Lodge: All Socks (2)",
    "Sand Mountain Lodge: All Spatulas (2)",
    "Sand Mountain Slide 3: All Socks (3)",
    "Sand Mountain Slide 3: All Spatulas (2)",
    "Sand Mountain: All Socks (10)",
    "Sand Mountain: All Spatulas (8)",
    "Sandy's Dream: All Socks (3)",
    "Sandy's Dream: All Spatulas (2)",
    "Save the Children",
    "Sea Caves: All Socks (3)",
    "Sea Needle Sock",
    "Security Tunnel Sock",
    "Shipwreck Sock",
    "Shut Down Security System",
    "Slide 3 Cave Sock",
    "Slide Leap",
    "Slidin' Texas Style",
    "Slip Sliding Away",
    "Small Shall Rule",
    "Sock Behind Lighthouse",
    "Sock Inside Lighthouse",
    "Spelunking",
    "SpongeBob's Closet",
    "Spork Mountain Sock",
    "Squid's Dream Sock",
    "Squidward's House Sock",
    "Super Bounce",
    "Swingalong Spatula",
    "Swingers Ahoy",
    "Swingin' Sandy",
    "TV Sock",
    "Texas Manor Sock",
    "Texas Oil Tower Sock",
    "Texas Slide Lasso Sock",
    "Through the Sea Caves",
    "Tikis Go Boom",
    "Top of Computer Area",
    "Top of Downtown Fallen Building Sock",
    "Top of Pineapple",
    "Top of Security Tunnel",
    "Top of Shady Shoals",
    "Top of Stack of Ships",
    "Top of the Chum Bucket",
    "Top of the Hill",
    "Top of the Lodge",
    "Tower Bungee",
    "Towers of Power",
    "Trench Clam Sock",
    "Trench of Darkness: All Socks (3)",
    "Trench of Darkness: All Spatulas (3)",
    "Wack-A-Tiki Sock",
    "Wall Jump in Chum Bucket"
];
