bingoGenerator = require("./generators/generator_bases/srl_generator_v5.js");

var bingoList = [];
bingoList[1] = [
  { name: "1-Secret", types: ["ch1"] },
  { name: "2-Secret", types: ["ch2"] },
  { name: "3-Secret", types: ["ch3"] },
  { name: "4-Secret", types: ["ch4"] },
  { name: "5-Secret", types: ["ch5"] },
  { name: "6-Secret", types: ["ch6"] },
  { name: "7-Secret", types: ["ch7"] },
  { name: "8-Secret", types: ["ch8"] },
  { name: "1-Secret Weaponless", types: ["ch1"] },
  { name: "2-Secret Weaponless", types: ["ch2"] },
  { name: "3-Secret Weaponless", types: ["ch3"] },
  { name: "4-Secret Weaponless", types: ["ch4"] },
  { name: "5-Secret Weaponless", types: ["ch5"] },
  { name: "6-Secret Weaponless", types: ["ch6"] },
  { name: "7-Secret Weaponless", types: ["ch7"] },
  { name: "8-Secret Weaponless", types: ["ch8"] },
];
bingoList[2] = [
  { name: "1-Secret 100%", types: ["ch1"] },
  { name: "2-Secret 100%", types: ["ch2"] },
  { name: "3-Secret 100%", types: ["ch3"] },
  { name: "4-Secret 100%", types: ["ch4"] },
  { name: "5-Secret 100%", types: ["ch5"] },
  { name: "6-Secret 100%", types: ["ch6"] },
  { name: "7-Secret 100%", types: ["ch7"] },
  { name: "8-Secret 100%", types: ["ch8"] },
  { name: "1-Secret Weaponless 100%", types: ["ch1"] },
  { name: "2-Secret Weaponless 100%", types: ["ch2"] },
  { name: "3-Secret Weaponless 100%", types: ["ch3"] },
  { name: "4-Secret Weaponless 100%", types: ["ch4"] },
  { name: "5-Secret Weaponless 100%", types: ["ch5"] },
  { name: "6-Secret Weaponless 100%", types: ["ch6"] },
  { name: "7-Secret Weaponless 100%", types: ["ch7"] },
  { name: "8-Secret Weaponless 100%", types: ["ch8"] },
];
bingoList[3] = [
  { name: "1-1", types: ["ch1"] },
  { name: "1-2", types: ["ch1"] },
  { name: "1-3", types: ["ch1"] },
  { name: "1-4", types: ["ch1"] },
  { name: "1-5", types: ["ch1"] },
  { name: "1-6", types: ["ch1"] },
  { name: "1-7", types: ["ch1"] },
  { name: "1-8", types: ["ch1"] },
  { name: "1-9", types: ["ch1"] },
  { name: "1-Fin", types: ["ch1"] },
  { name: "1-E1", types: ["ch1"] },
  { name: "1-E2", types: ["ch1"] },
  { name: "1-E3", types: ["ch1"] },
  { name: "2-1", types: ["ch2"] },
  { name: "2-2", types: ["ch2"] },
  { name: "2-3", types: ["ch2"] },
  { name: "2-4", types: ["ch2"] },
  { name: "2-5", types: ["ch2"] },
  { name: "2-6", types: ["ch2"] },
  { name: "2-7", types: ["ch2"] },
  { name: "2-8", types: ["ch2"] },
  { name: "2-9", types: ["ch2"] },
  { name: "2-Fin", types: ["ch2"] },
  { name: "2-E1", types: ["ch2"] },
  { name: "2-E2", types: ["ch2"] },
  { name: "2-E3", types: ["ch2"] },
  { name: "3-1", types: ["ch3"] },
  { name: "3-2", types: ["ch3"] },
  { name: "3-3", types: ["ch3"] },
  { name: "3-4", types: ["ch3"] },
  { name: "3-5", types: ["ch3"] },
  { name: "3-6", types: ["ch3"] },
  { name: "3-7", types: ["ch3"] },
  { name: "3-8", types: ["ch3"] },
  { name: "3-9", types: ["ch3"] },
  { name: "3-Fin", types: ["ch3"] },
  { name: "3-E1", types: ["ch3"] },
  { name: "3-E2", types: ["ch3"] },
  { name: "3-E3", types: ["ch3"] },
  { name: "4-1", types: ["ch4"] },
  { name: "4-2", types: ["ch4"] },
  { name: "4-3", types: ["ch4"] },
  { name: "4-4", types: ["ch4"] },
  { name: "4-5", types: ["ch4"] },
  { name: "4-6", types: ["ch4"] },
  { name: "4-7", types: ["ch4"] },
  { name: "4-8", types: ["ch4"] },
  { name: "4-9", types: ["ch4"] },
  { name: "4-Fin", types: ["ch4"] },
  { name: "4-E1", types: ["ch4"] },
  { name: "4-E2", types: ["ch4"] },
  { name: "4-E3", types: ["ch4"] },
  { name: "5-1", types: ["ch5"] },
  { name: "5-2", types: ["ch5"] },
  { name: "5-3", types: ["ch5"] },
  { name: "5-4", types: ["ch5"] },
  { name: "5-5", types: ["ch5"] },
  { name: "5-6", types: ["ch5"] },
  { name: "5-7", types: ["ch5"] },
  { name: "5-8", types: ["ch5"] },
  { name: "5-9", types: ["ch5"] },
  { name: "5-Fin", types: ["ch5"] },
  { name: "5-E1", types: ["ch5"] },
  { name: "5-E2", types: ["ch5"] },
  { name: "5-E3", types: ["ch5"] },
  { name: "6-1", types: ["ch6"] },
  { name: "6-2", types: ["ch6"] },
  { name: "6-3", types: ["ch6"] },
  { name: "6-4", types: ["ch6"] },
  { name: "6-5", types: ["ch6"] },
  { name: "6-6", types: ["ch6"] },
  { name: "6-7", types: ["ch6"] },
  { name: "6-8", types: ["ch6"] },
  { name: "6-9", types: ["ch6"] },
  { name: "6-Fin", types: ["ch6"] },
  { name: "6-E1", types: ["ch6"] },
  { name: "6-E2", types: ["ch6"] },
  { name: "6-E3", types: ["ch6"] },
  { name: "7-1", types: ["ch7"] },
  { name: "7-2", types: ["ch7"] },
  { name: "7-3", types: ["ch7"] },
  { name: "7-4", types: ["ch7"] },
  { name: "7-5", types: ["ch7"] },
  { name: "7-6", types: ["ch7"] },
  { name: "7-7", types: ["ch7"] },
  { name: "7-8", types: ["ch7"] },
  { name: "7-9", types: ["ch7"] },
  { name: "7-Fin", types: ["ch7"] },
  { name: "7-E1", types: ["ch7"] },
  { name: "7-E2", types: ["ch7"] },
  { name: "7-E3", types: ["ch7"] },
  { name: "8-1", types: ["ch8"] },
  { name: "8-2", types: ["ch8"] },
  { name: "8-3", types: ["ch8"] },
  { name: "8-4", types: ["ch8"] },
  { name: "8-5", types: ["ch8"] },
  { name: "8-6", types: ["ch8"] },
  { name: "8-7", types: ["ch8"] },
  { name: "8-8", types: ["ch8"] },
  { name: "8-9", types: ["ch8"] },
  { name: "8-Fin", types: ["ch8"] },
  { name: "8-E1", types: ["ch8"] },
  { name: "8-E2", types: ["ch8"] },
  { name: "8-E3", types: ["ch8"] },
];
bingoList[4] = [
  { name: "1-1 Weaponless", types: ["ch1"] },
  { name: "1-2 Weaponless", types: ["ch1"] },
  { name: "1-3 Weaponless", types: ["ch1"] },
  { name: "1-4 Weaponless", types: ["ch1"] },
  { name: "1-5 Weaponless", types: ["ch1"] },
  { name: "1-6 Weaponless", types: ["ch1"] },
  { name: "1-7 Weaponless", types: ["ch1"] },
  { name: "1-8 Weaponless", types: ["ch1"] },
  { name: "1-9 Weaponless", types: ["ch1"] },
  { name: "1-Fin Weaponless", types: ["ch1"] },
  { name: "1-E1 Weaponless", types: ["ch1"] },
  { name: "1-E2 Weaponless", types: ["ch1"] },
  { name: "1-E3 Weaponless", types: ["ch1"] },
  { name: "2-1 Weaponless", types: ["ch2"] },
  { name: "2-2 Weaponless", types: ["ch2"] },
  { name: "2-3 Weaponless", types: ["ch2"] },
  { name: "2-4 Weaponless", types: ["ch2"] },
  { name: "2-5 Weaponless", types: ["ch2"] },
  { name: "2-6 Weaponless", types: ["ch2"] },
  { name: "2-7 Weaponless", types: ["ch2"] },
  { name: "2-8 Weaponless", types: ["ch2"] },
  { name: "2-9 Weaponless", types: ["ch2"] },
  { name: "2-Fin Weaponless", types: ["ch2"] },
  { name: "2-E1 Weaponless", types: ["ch2"] },
  { name: "2-E2 Weaponless", types: ["ch2"] },
  { name: "2-E3 Weaponless", types: ["ch2"] },
  { name: "3-1 Weaponless", types: ["ch3"] },
  { name: "3-2 Weaponless", types: ["ch3"] },
  { name: "3-3 Weaponless", types: ["ch3"] },
  { name: "3-4 Weaponless", types: ["ch3"] },
  { name: "3-5 Weaponless", types: ["ch3"] },
  { name: "3-6 Weaponless", types: ["ch3"] },
  { name: "3-7 Weaponless", types: ["ch3"] },
  { name: "3-8 Weaponless", types: ["ch3"] },
  { name: "3-9 Weaponless", types: ["ch3"] },
  { name: "3-Fin Weaponless", types: ["ch3"] },
  { name: "3-E1 Weaponless", types: ["ch3"] },
  { name: "3-E2 Weaponless", types: ["ch3"] },
  { name: "3-E3 Weaponless", types: ["ch3"] },
  { name: "4-1 Weaponless", types: ["ch4"] },
  { name: "4-2 Weaponless", types: ["ch4"] },
  { name: "4-3 Weaponless", types: ["ch4"] },
  { name: "4-4 Weaponless", types: ["ch4"] },
  { name: "4-5 Weaponless", types: ["ch4"] },
  { name: "4-6 Weaponless", types: ["ch4"] },
  { name: "4-7 Weaponless", types: ["ch4"] },
  { name: "4-8 Weaponless", types: ["ch4"] },
  { name: "4-9 Weaponless", types: ["ch4"] },
  { name: "4-Fin Weaponless", types: ["ch4"] },
  { name: "4-E1 Weaponless", types: ["ch4"] },
  { name: "4-E2 Weaponless", types: ["ch4"] },
  { name: "4-E3 Weaponless", types: ["ch4"] },
  { name: "5-1 Weaponless", types: ["ch5"] },
  { name: "5-2 Weaponless", types: ["ch5"] },
  { name: "5-3 Weaponless", types: ["ch5"] },
  { name: "5-4 Weaponless", types: ["ch5"] },
  { name: "5-5 Weaponless", types: ["ch5"] },
  { name: "5-6 Weaponless", types: ["ch5"] },
  { name: "5-7 Weaponless", types: ["ch5"] },
  { name: "5-8 Weaponless", types: ["ch5"] },
  { name: "5-9 Weaponless", types: ["ch5"] },
  { name: "5-Fin Weaponless", types: ["ch5"] },
  { name: "5-E1 Weaponless", types: ["ch5"] },
  { name: "5-E2 Weaponless", types: ["ch5"] },
  { name: "5-E3 Weaponless", types: ["ch5"] },
  { name: "6-1 Weaponless", types: ["ch6"] },
  { name: "6-2 Weaponless", types: ["ch6"] },
  { name: "6-3 Weaponless", types: ["ch6"] },
  { name: "6-4 Weaponless", types: ["ch6"] },
  { name: "6-5 Weaponless", types: ["ch6"] },
  { name: "6-6 Weaponless", types: ["ch6"] },
  { name: "6-7 Weaponless", types: ["ch6"] },
  { name: "6-8 Weaponless", types: ["ch6"] },
  { name: "6-9 Weaponless", types: ["ch6"] },
  { name: "6-Fin Weaponless", types: ["ch6"] },
  { name: "6-E1 Weaponless", types: ["ch6"] },
  { name: "6-E2 Weaponless", types: ["ch6"] },
  { name: "6-E3 Weaponless", types: ["ch6"] },
  { name: "7-1 Weaponless", types: ["ch7"] },
  { name: "7-2 Weaponless", types: ["ch7"] },
  { name: "7-3 Weaponless", types: ["ch7"] },
  { name: "7-4 Weaponless", types: ["ch7"] },
  { name: "7-5 Weaponless", types: ["ch7"] },
  { name: "7-6 Weaponless", types: ["ch7"] },
  { name: "7-7 Weaponless", types: ["ch7"] },
  { name: "7-8 Weaponless", types: ["ch7"] },
  { name: "7-9 Weaponless", types: ["ch7"] },
  { name: "7-Fin Weaponless", types: ["ch7"] },
  { name: "7-E1 Weaponless", types: ["ch7"] },
  { name: "7-E2 Weaponless", types: ["ch7"] },
  { name: "7-E3 Weaponless", types: ["ch7"] },
  { name: "8-1 Weaponless", types: ["ch8"] },
  { name: "8-2 Weaponless", types: ["ch8"] },
  { name: "8-3 Weaponless", types: ["ch8"] },
  { name: "8-4 Weaponless", types: ["ch8"] },
  { name: "8-5 Weaponless", types: ["ch8"] },
  { name: "8-6 Weaponless", types: ["ch8"] },
  { name: "8-7 Weaponless", types: ["ch8"] },
  { name: "8-8 Weaponless", types: ["ch8"] },
  { name: "8-9 Weaponless", types: ["ch8"] },
  { name: "8-Fin Weaponless", types: ["ch8"] },
  { name: "8-E1 Weaponless", types: ["ch8"] },
  { name: "8-E2 Weaponless", types: ["ch8"] },
  { name: "8-E3 Weaponless", types: ["ch8"] },
];
bingoList[5] = [
  { name: "1-1 100%", types: ["ch1"] },
  { name: "1-2 100%", types: ["ch1"] },
  { name: "1-3 100%", types: ["ch1"] },
  { name: "1-4 100%", types: ["ch1"] },
  { name: "1-5 100%", types: ["ch1"] },
  { name: "1-6 100%", types: ["ch1"] },
  { name: "1-7 100%", types: ["ch1"] },
  { name: "1-8 100%", types: ["ch1"] },
  { name: "1-9 100%", types: ["ch1"] },
  { name: "1-Fin 100%", types: ["ch1"] },
  { name: "1-E1 100%", types: ["ch1"] },
  { name: "1-E2 100%", types: ["ch1"] },
  { name: "1-E3 100%", types: ["ch1"] },
  { name: "2-1 100%", types: ["ch2"] },
  { name: "2-2 100%", types: ["ch2"] },
  { name: "2-3 100%", types: ["ch2"] },
  { name: "2-4 100%", types: ["ch2"] },
  { name: "2-5 100%", types: ["ch2"] },
  { name: "2-6 100%", types: ["ch2"] },
  { name: "2-7 100%", types: ["ch2"] },
  { name: "2-8 100%", types: ["ch2"] },
  { name: "2-9 100%", types: ["ch2"] },
  { name: "2-Fin 100%", types: ["ch2"] },
  { name: "2-E1 100%", types: ["ch2"] },
  { name: "2-E2 100%", types: ["ch2"] },
  { name: "2-E3 100%", types: ["ch2"] },
  { name: "3-1 100%", types: ["ch3"] },
  { name: "3-2 100%", types: ["ch3"] },
  { name: "3-3 100%", types: ["ch3"] },
  { name: "3-4 100%", types: ["ch3"] },
  { name: "3-5 100%", types: ["ch3"] },
  { name: "3-6 100%", types: ["ch3"] },
  { name: "3-7 100%", types: ["ch3"] },
  { name: "3-8 100%", types: ["ch3"] },
  { name: "3-9 100%", types: ["ch3"] },
  { name: "3-Fin 100%", types: ["ch3"] },
  { name: "3-E1 100%", types: ["ch3"] },
  { name: "3-E2 100%", types: ["ch3"] },
  { name: "3-E3 100%", types: ["ch3"] },
  { name: "4-1 100%", types: ["ch4"] },
  { name: "4-2 100%", types: ["ch4"] },
  { name: "4-3 100%", types: ["ch4"] },
  { name: "4-4 100%", types: ["ch4"] },
  { name: "4-5 100%", types: ["ch4"] },
  { name: "4-6 100%", types: ["ch4"] },
  { name: "4-7 100%", types: ["ch4"] },
  { name: "4-8 100%", types: ["ch4"] },
  { name: "4-9 100%", types: ["ch4"] },
  { name: "4-Fin 100%", types: ["ch4"] },
  { name: "4-E1 100%", types: ["ch4"] },
  { name: "4-E2 100%", types: ["ch4"] },
  { name: "4-E3 100%", types: ["ch4"] },
  { name: "5-1 100%", types: ["ch5"] },
  { name: "5-2 100%", types: ["ch5"] },
  { name: "5-3 100%", types: ["ch5"] },
  { name: "5-4 100%", types: ["ch5"] },
  { name: "5-5 100%", types: ["ch5"] },
  { name: "5-6 100%", types: ["ch5"] },
  { name: "5-7 100%", types: ["ch5"] },
  { name: "5-8 100%", types: ["ch5"] },
  { name: "5-9 100%", types: ["ch5"] },
  { name: "5-Fin 100%", types: ["ch5"] },
  { name: "5-E1 100%", types: ["ch5"] },
  { name: "5-E2 100%", types: ["ch5"] },
  { name: "5-E3 100%", types: ["ch5"] },
  { name: "6-1 100%", types: ["ch6"] },
  { name: "6-2 100%", types: ["ch6"] },
  { name: "6-3 100%", types: ["ch6"] },
  { name: "6-4 100%", types: ["ch6"] },
  { name: "6-5 100%", types: ["ch6"] },
  { name: "6-6 100%", types: ["ch6"] },
  { name: "6-7 100%", types: ["ch6"] },
  { name: "6-8 100%", types: ["ch6"] },
  { name: "6-9 100%", types: ["ch6"] },
  { name: "6-Fin 100%", types: ["ch6"] },
  { name: "6-E1 100%", types: ["ch6"] },
  { name: "6-E2 100%", types: ["ch6"] },
  { name: "6-E3 100%", types: ["ch6"] },
  { name: "7-1 100%", types: ["ch7"] },
  { name: "7-2 100%", types: ["ch7"] },
  { name: "7-3 100%", types: ["ch7"] },
  { name: "7-4 100%", types: ["ch7"] },
  { name: "7-5 100%", types: ["ch7"] },
  { name: "7-6 100%", types: ["ch7"] },
  { name: "7-7 100%", types: ["ch7"] },
  { name: "7-8 100%", types: ["ch7"] },
  { name: "7-9 100%", types: ["ch7"] },
  { name: "7-Fin 100%", types: ["ch7"] },
  { name: "7-E1 100%", types: ["ch7"] },
  { name: "7-E2 100%", types: ["ch7"] },
  { name: "7-E3 100%", types: ["ch7"] },
  { name: "8-1 100%", types: ["ch8"] },
  { name: "8-2 100%", types: ["ch8"] },
  { name: "8-3 100%", types: ["ch8"] },
  { name: "8-4 100%", types: ["ch8"] },
  { name: "8-5 100%", types: ["ch8"] },
  { name: "8-6 100%", types: ["ch8"] },
  { name: "8-7 100%", types: ["ch8"] },
  { name: "8-8 100%", types: ["ch8"] },
  { name: "8-9 100%", types: ["ch8"] },
  { name: "8-Fin 100%", types: ["ch8"] },
  { name: "8-E1 100%", types: ["ch8"] },
  { name: "8-E2 100%", types: ["ch8"] },
  { name: "8-E3 100%", types: ["ch8"] },
];
bingoList[6] = [
  { name: "1-1 Weaponless 100%", types: ["ch1"] },
  { name: "1-2 Weaponless 100%", types: ["ch1"] },
  { name: "1-3 Weaponless 100%", types: ["ch1"] },
  { name: "1-4 Weaponless 100%", types: ["ch1"] },
  { name: "1-5 Weaponless 100%", types: ["ch1"] },
  { name: "1-6 Weaponless 100%", types: ["ch1"] },
  { name: "1-7 Weaponless 100%", types: ["ch1"] },
  { name: "1-8 Weaponless 100%", types: ["ch1"] },
  { name: "1-9 Weaponless 100%", types: ["ch1"] },
  { name: "1-Fin Weaponless 100%", types: ["ch1"] },
  { name: "1-E1 Weaponless 100%", types: ["ch1"] },
  { name: "1-E2 Weaponless 100%", types: ["ch1"] },
  { name: "1-E3 Weaponless 100%", types: ["ch1"] },
  { name: "2-1 Weaponless 100%", types: ["ch2"] },
  { name: "2-2 Weaponless 100%", types: ["ch2"] },
  { name: "2-3 Weaponless 100%", types: ["ch2"] },
  { name: "2-4 Weaponless 100%", types: ["ch2"] },
  { name: "2-5 Weaponless 100%", types: ["ch2"] },
  { name: "2-6 Weaponless 100%", types: ["ch2"] },
  { name: "2-7 Weaponless 100%", types: ["ch2"] },
  { name: "2-8 Weaponless 100%", types: ["ch2"] },
  { name: "2-9 Weaponless 100%", types: ["ch2"] },
  { name: "2-Fin Weaponless 100%", types: ["ch2"] },
  { name: "2-E1 Weaponless 100%", types: ["ch2"] },
  { name: "2-E2 Weaponless 100%", types: ["ch2"] },
  { name: "2-E3 Weaponless 100%", types: ["ch2"] },
  { name: "3-1 Weaponless 100%", types: ["ch3"] },
  { name: "3-2 Weaponless 100%", types: ["ch3"] },
  { name: "3-3 Weaponless 100%", types: ["ch3"] },
  { name: "3-4 Weaponless 100%", types: ["ch3"] },
  { name: "3-5 Weaponless 100%", types: ["ch3"] },
  { name: "3-6 Weaponless 100%", types: ["ch3"] },
  { name: "3-7 Weaponless 100%", types: ["ch3"] },
  { name: "3-8 Weaponless 100%", types: ["ch3"] },
  { name: "3-9 Weaponless 100%", types: ["ch3"] },
  { name: "3-Fin Weaponless 100%", types: ["ch3"] },
  { name: "3-E1 Weaponless 100%", types: ["ch3"] },
  { name: "3-E2 Weaponless 100%", types: ["ch3"] },
  { name: "3-E3 Weaponless 100%", types: ["ch3"] },
  { name: "4-1 Weaponless 100%", types: ["ch4"] },
  { name: "4-2 Weaponless 100%", types: ["ch4"] },
  { name: "4-3 Weaponless 100%", types: ["ch4"] },
  { name: "4-4 Weaponless 100%", types: ["ch4"] },
  { name: "4-5 Weaponless 100%", types: ["ch4"] },
  { name: "4-6 Weaponless 100%", types: ["ch4"] },
  { name: "4-7 Weaponless 100%", types: ["ch4"] },
  { name: "4-8 Weaponless 100%", types: ["ch4"] },
  { name: "4-9 Weaponless 100%", types: ["ch4"] },
  { name: "4-Fin Weaponless 100%", types: ["ch4"] },
  { name: "4-E1 Weaponless 100%", types: ["ch4"] },
  { name: "4-E2 Weaponless 100%", types: ["ch4"] },
  { name: "4-E3 Weaponless 100%", types: ["ch4"] },
  { name: "5-1 Weaponless 100%", types: ["ch5"] },
  { name: "5-2 Weaponless 100%", types: ["ch5"] },
  { name: "5-3 Weaponless 100%", types: ["ch5"] },
  { name: "5-4 Weaponless 100%", types: ["ch5"] },
  { name: "5-5 Weaponless 100%", types: ["ch5"] },
  { name: "5-6 Weaponless 100%", types: ["ch5"] },
  { name: "5-7 Weaponless 100%", types: ["ch5"] },
  { name: "5-8 Weaponless 100%", types: ["ch5"] },
  { name: "5-9 Weaponless 100%", types: ["ch5"] },
  { name: "5-Fin Weaponless 100%", types: ["ch5"] },
  { name: "5-E1 Weaponless 100%", types: ["ch5"] },
  { name: "5-E2 Weaponless 100%", types: ["ch5"] },
  { name: "5-E3 Weaponless 100%", types: ["ch5"] },
  { name: "6-1 Weaponless 100%", types: ["ch6"] },
  { name: "6-2 Weaponless 100%", types: ["ch6"] },
  { name: "6-3 Weaponless 100%", types: ["ch6"] },
  { name: "6-4 Weaponless 100%", types: ["ch6"] },
  { name: "6-5 Weaponless 100%", types: ["ch6"] },
  { name: "6-6 Weaponless 100%", types: ["ch6"] },
  { name: "6-7 Weaponless 100%", types: ["ch6"] },
  { name: "6-8 Weaponless 100%", types: ["ch6"] },
  { name: "6-9 Weaponless 100%", types: ["ch6"] },
  { name: "6-Fin Weaponless 100%", types: ["ch6"] },
  { name: "6-E1 Weaponless 100%", types: ["ch6"] },
  { name: "6-E2 Weaponless 100%", types: ["ch6"] },
  { name: "6-E3 Weaponless 100%", types: ["ch6"] },
  { name: "7-1 Weaponless 100%", types: ["ch7"] },
  { name: "7-2 Weaponless 100%", types: ["ch7"] },
  { name: "7-3 Weaponless 100%", types: ["ch7"] },
  { name: "7-4 Weaponless 100%", types: ["ch7"] },
  { name: "7-5 Weaponless 100%", types: ["ch7"] },
  { name: "7-6 Weaponless 100%", types: ["ch7"] },
  { name: "7-7 Weaponless 100%", types: ["ch7"] },
  { name: "7-8 Weaponless 100%", types: ["ch7"] },
  { name: "7-9 Weaponless 100%", types: ["ch7"] },
  { name: "7-Fin Weaponless 100%", types: ["ch7"] },
  { name: "7-E1 Weaponless 100%", types: ["ch7"] },
  { name: "7-E2 Weaponless 100%", types: ["ch7"] },
  { name: "7-E3 Weaponless 100%", types: ["ch7"] },
  { name: "8-1 Weaponless 100%", types: ["ch8"] },
  { name: "8-2 Weaponless 100%", types: ["ch8"] },
  { name: "8-3 Weaponless 100%", types: ["ch8"] },
  { name: "8-4 Weaponless 100%", types: ["ch8"] },
  { name: "8-5 Weaponless 100%", types: ["ch8"] },
  { name: "8-6 Weaponless 100%", types: ["ch8"] },
  { name: "8-7 Weaponless 100%", types: ["ch8"] },
  { name: "8-8 Weaponless 100%", types: ["ch8"] },
  { name: "8-9 Weaponless 100%", types: ["ch8"] },
  { name: "8-Fin Weaponless 100%", types: ["ch8"] },
  { name: "8-E1 Weaponless 100%", types: ["ch8"] },
  { name: "8-E2 Weaponless 100%", types: ["ch8"] },
  { name: "8-E3 Weaponless 100%", types: ["ch8"] },
];
bingoList[7] = [
  { name: "Kill 5 unique cats", types: [] },
  { name: "Kill 10 unique cats", types: [] },
  { name: "Kill 5 pieces of toast", types: ["killenemy","toast"] },
  { name: "Kill 1 raccalope", types: ["raccalope"] },
  { name: "Kill 2 raccalopes", types: ["raccalope"] },
  { name: "Kill 3 ducksharks", types: ["duckshark"] },
  { name: "Kill the same duckshark 5 times", types: ["duckshark"] },
];
bingoList[8] = [
  { name: "Kill 2 unique fire cats", types: ["fire"] },
  { name: "Kill 2 unique boomerang cats", types: ["boomerang"] },
  { name: "Kill 2 unique paperplane cats", types: ["paperplane"] },
  { name: "Kill 4 unique big bonking cats", types: ["pushers"] },
  { name: "Kill 4 unique small cats", types: ["small"] },
  { name: "Kill 2 unique sucking cats", types: ["suction"] },
  { name: "Kill 2 unique blowing cats", types: ["blow"] },
  { name: "Kill 2 unique grenade cats", types: ["grenade"] },
  { name: "Kill 2 unique bubble cats", types: ["bubble"] },
  { name: "Kill 2 unique forceball cats", types: ["forceball"] },
  { name: "Kill 2 unique ice cats", types: ["ice"] },
  { name: "Drown 4 cats", types: ["water"] },
  { name: "Lure 2 cats into spikes", types: ["forceball"] },
];
bingoList[9] = [
  { name: "1-6 doing frog boat skip", types: ["frog"] },
  { name: "5-1 WITHOUT the treadmill boost", types: ["casual"] },
  { name: "3-1 WITHOUT any omega boosts", types: ["noob"] },
  { name: "Collect 4 gems in any 5 stages", types: ["runover"] },
  { name: "3-2 WITHOUT any of the yolo boosts", types: ["frog"] },
  { name: "7-2, 7-3, 7-5 or 7-8 without any checkpoint skips", types: ["badatruns"] },
  { name: "2-F2 without the frog clip", types: ["xenemy"] },
];
bingoList[10] = [
  { name: "2-5 first ferdinand skip", types: ["skips"] },
  { name: "6-4 yolo boost through all these lasers", types: ["yolo"] },
  { name: "7-F1 journey through the boulder portals", types: ["boulders"] },
  { name: "8-9 with that boost", types: ["plsno","why"] },
  { name: "8-3 duckshark skip", types: ["ohgod"] },
];
bingoList[11] = [
  { name: "Have 5 paperplanes on screen at once", types: ["dupe","paperplane"] },
  { name: "Jam a rock between two blocks", types: ["boulders"] },
  { name: "Stand infront of a fire cat without getting hit by its fire", types: ["touch"] },
];
bingoList[12] = [
  { name: "Clear 3 Chapter 1 scenes", types: [] },
  { name: "Clear 3 Chapter 2 scenes", types: [] },
  { name: "Clear 3 Chapter 3 scenes", types: [] },
  { name: "Clear 3 Chapter 4 scenes", types: [] },
  { name: "Clear 3 Chapter 5 scenes", types: [] },
  { name: "Clear 3 Chapter 6 scenes", types: [] },
  { name: "Clear 3 Chapter 7 scenes", types: [] },
  { name: "Clear 3 Chapter 8 scenes", types: [] },
];
bingoList[13] = [
  { name: "100% Clear 3 Chapter 1 scenes", types: [] },
  { name: "100% Clear 3 Chapter 2 scenes", types: [] },
  { name: "100% Clear 3 Chapter 3 scenes", types: [] },
  { name: "100% Clear 3 Chapter 4 scenes", types: [] },
  { name: "100% Clear 3 Chapter 5 scenes", types: [] },
  { name: "100% Clear 3 Chapter 6 scenes", types: [] },
  { name: "100% Clear 3 Chapter 7 scenes", types: [] },
  { name: "100% Clear 3 Chapter 8 scenes", types: [] },
];
bingoList[14] = [
  { name: "Clear Encores in Ch1", types: [] },
  { name: "Clear Encores in Ch2", types: [] },
  { name: "Clear Encores in Ch3", types: [] },
  { name: "Clear Encores in Ch4", types: [] },
  { name: "Clear Encores in Ch5", types: [] },
  { name: "Clear Encores in Ch6", types: [] },
  { name: "Clear Encores in Ch7", types: [] },
  { name: "Clear Encores in Ch8", types: [] },
];
bingoList[15] = [
  { name: "100% Encores in Ch1", types: [] },
  { name: "100% Encores in Ch2", types: [] },
  { name: "100% Encores in Ch3", types: [] },
  { name: "100% Encores in Ch4", types: [] },
  { name: "100% Encores in Ch5", types: [] },
  { name: "100% Encores in Ch6", types: [] },
  { name: "100% Encores in Ch7", types: [] },
  { name: "100% Encores in Ch8", types: [] },
];
bingoList[16] = [
  { name: "3-2 Pacifict", types: [] },
  { name: "3-2 Genocide", types: [] },
  { name: "1-8 Pacifict", types: [] },
  { name: "1-8 Genocide", types: [] },
  { name: "3-5 Pacifict", types: [] },
  { name: "3-5 Genocide", types: [] },
  { name: "7-9 Pacifict", types: [] },
  { name: "7-9 Genocide", types: [] },
  { name: "6-3 Pacifict", types: [] },
  { name: "6-3 Genocide", types: [] },
  { name: "7-5 Pacifict", types: [] },
  { name: "7-5 Genocide", types: [] },
];
bingoList[17] = [
  { name: "Get all checkpoints in 7-5", types: ["cpget"] },
  { name: "Skip all checkpoints in 7-3", types: ["cpskip"] },
  { name: "Get all checkpoints in 1-7", types: ["cpget"] },
  { name: "Get all checkpoints in 5-5", types: ["cpget"] },
  { name: "Get all checkpoints in 6-8", types: ["cpget"] },
  { name: "Skip all checkpoints in 8-2", types: ["cpskip"] },
  { name: "Skip all checkpoints in 3-2", types: ["cpskip"] },
  { name: "Skip all checkpoints in 2-5", types: ["cpskip"] },
];
bingoList[18] = [
  { name: "1 golden hat", types: [] },
  { name: "2 golden hats", types: [] },
  { name: "3 golden hats", types: [] },
];
bingoList[19] = [
  { name: "50 unique gems", types: [] },
  { name: "100 unique gems", types: [] },
  { name: "150 unique gems", types: [] },
  { name: "200 unique gems", types: [] },
];
bingoList[20] = [
  { name: "10 unique yarns", types: [] },
  { name: "15 unique yarns", types: [] },
  { name: "20 unique yarns", types: [] },
  { name: "25 unique yarns", types: [] },
  { name: "30 unique yarns", types: [] },
];
bingoList[21] = [
  { name: "15 NPC kills", types: [] },
  { name: "20 NPC kills", types: [] },
  { name: "25 NPC kills", types: [] },
  { name: "30 NPC kills", types: [] },
];
bingoList[22] = [
  { name: "20 unique stage clears", types: [] },
  { name: "25 unique stage clears", types: [] },
  { name: "30 unique stage clears", types: [] },
  { name: "35 unique stage clears", types: [] },
  { name: "40 unique stage clears", types: [] },
];
bingoList[23] = [
  { name: "10 unique clock stamps", types: [] },
  { name: "15 unique clock stamps", types: [] },
  { name: "20 unique clock stamps", types: [] },
  { name: "25 unique clock stamps", types: [] },
  { name: "30 unique clock stamps", types: [] },
];
bingoList[24] = [
  { name: "Vacuum a cat's grenade and die from it", types: ["grenade"] },
  { name: "Kill 5 cats with their own grenades", types: ["grenade"] },
  { name: "Lure 5 cats into raccalopes", types: ["raccalope"] },
  { name: "Set yourself on fire, then extinguish yourself", types: ["fire"] },
  { name: "Bounce on 5 toxic bubbles without touching the ground", types: ["bubble"] },
  { name: "Kill that one paperplane cat with its own paperplanes", types: ["paperplane"] },
  { name: "Have a cat set another cat on fire", types: ["fire"] },
  { name: "Push a cat to it's demise using only forceballs", types: ["forceball"] },
];
bingoList[25] = [
  { name: "Duckshark's Big Adventure", types: ["duckshark"] },
  { name: "Bring a rock to the end of 6-4", types: ["boulders"] },
  { name: "Watch two full cutscenes", types: ["cutscene"] },
  { name: "8-Secret cleared without ever standing still", types: ["clear"] },
  { name: "Finish a stage with 0 jumps", types: ["jumpless"] },
];
