bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "25% map completion",
    "50% map completion",
    "75% map completion",
    "85% map completion",
    "Beat Alura Une",
    "Beat Balore",
    "Beat Big Golem",
    "Beat Chaos",
    "Beat Chronomage",
    "Beat Creaking Skull",
    "Beat Death",
    "Beat Final Guard",
    "Beat Flame Demon",
    "Beat Giant Skeleton",
    "Beat Graham",
    "Beat Great Armor",
    "Beat Headhunter",
    "Beat Julius",
    "Beat Legion",
    "Beat Manticore",
    "Beat Mimic",
    "Beat Red Minotaur",
    "Beat Tsuchinoko",
    "Get 10 Bullet Souls",
    "Get 10 Enchanted Souls",
    "Get 10 Guardian Souls",
    "Get 10 accessories",
    "Get 10 armors",
    "Get 10 weapons",
    "Get 3 Ability Souls",
    "Get 4 Ability Souls",
    "Get 6 Ability Souls",
    "Get 6 Bullet Souls",
    "Get 6 Enchanted Souls",
    "Get 6 Guardian Souls",
    "Get 6 accessories",
    "Get 6 armors",
    "Get 6 weapons",
    "Get 8 Bullet Souls",
    "Get 8 Enchanted Souls",
    "Get 8 Guardian Souls",
    "Get 8 accessories",
    "Get 8 armors",
    "Get 8 weapons",
    "Get Ancient Belt",
    "Get Ancient Book 1",
    "Get Ancient Book 2",
    "Get Ancient Book 3",
    "Get Armor of Water",
    "Get Balore soul",
    "Get Baselard",
    "Get Black Belt",
    "Get Black Panther soul",
    "Get Castle Map 1",
    "Get Castle Map 2",
    "Get Castle Map 3",
    "Get Chronomage soul",
    "Get Claimh Solais",
    "Get Creaking Skull soul",
    "Get Devil soul",
    "Get Dracula's Tunic",
    "Get Eversing",
    "Get Final Sword",
    "Get Flying Armor soul",
    "Get Galamoth soul (Time stop immunity)",
    "Get Giant Bat soul",
    "Get Grave keeper soul (Back Dash)",
    "Get Hippogryph soul (High jump)",
    "Get Iron Plate",
    "Get Kaladbolg",
    "Get Kicker skeletton soul (Comet Kick)",
    "Get Leather Plate",
    "Get Legion soul",
    "Get Lucky Charm",
    "Get Malphas soul (Double jump)",
    "Get Muramasa",
    "Get Mystletain",
    "Get Olrox's Suit",
    "Get Red Minotaur soul",
    "Get Red Scarf",
    "Get Satan's Ring",
    "Get Skeleton blade soul (Slide)",
    "Get Skula soul",
    "Get Soul Eater Ring",
    "Get Triton soul",
    "Get Tsuchinoko soul",
    "Get Undine soul",
    "Get all Ancient Books",
    "Get all Castle Maps",
    "Reach Level 15",
    "Reach Level 20",
    "Reach Level 25",
    "Reach Level 30",
    "Unlock 10 save point",
    "Unlock 4 teleporter",
    "Unlock 5 teleporter",
    "Unlock 6 teleporter",
    "Visit shop",
    "own 15000$",
    "own 25000$",
    "own 5000$",
    "own 50000$"
];
