bingoGenerator = require("./generators/generator_bases/srl_generator_v5.js");

// This is actually the new longo generator, but because bingosync requires a generator to be the default, 
// and for that default to be named  [game_name]_generator the file is called this. :/

var bingoList = [null,
  [
  { "name": "Talk to Theo in Crossing", "types": ["earlygame","cutscene"] },
  { "name": "Complete 1A Start without jumping", "types": ["earlygame","task"] },
  { "name": "All Berries in Start of 1A (6)", "types": ["checkpoint_berries"] },
  { "name": "All Berries in Chasm (5)", "types": ["checkpoint_berries"] },
  { "name": "Get a 1-Up in 1A", "types": ["1up","earlygame"] },
  { "name": "Complete 1A Start without dashing", "types": ["earlygame","task"] },
  { "name": "Forsaken City Cassette", "types": ["1b","earlygame"] },
  { "name": "Old Site Blue Heart", "types": ["hearts","earlygame"] },
  { "name": "Get two 1-Ups", "types": ["earlygame"] },
  { "name": "10 Berries in 1A", "types": ["amount_berries"] },
  { "name": "Talk to Theo in Awake", "types": ["earlygame","awake"] }, 
  { "name": "All Berries in Awake (1)", "types": ["checkpoint_berries"] },
  { "name": "Complete Awake without dashing", "types": ["earlygame","task"] }
  ], 
  
  [
  { "name": "5 Berries in 3 Chapters", "types": ["amount_berries"] }, 
  { "name": "Read the Poem in 2A", "types": ["earlygame","awake"] },
  { "name": "Talk to Theo in Elevator Shaft", "types": ["resort_cutscene","cutscene"] },
  { "name": "10 Berries in 2A", "types": ["amount_berries"] },
  { "name": "Find Letter and PICO-8 in Huge Mess", "types": ["resort_cutscene","cutscene"] },
  { "name": "Get a 1-Up in 2 Chapters", "types": ["1up","challenge"] },
  { "name": "Complete Crossing without dashing", "types": ["challenge","task"] },
  { "name": "2 Cassettes", "types": ["amount_cassettes"] },
  { "name": "Old Site Cassette", "types": ["2b","earlygame"] },
  { "name": "Complete Chasm without dashing", "types": ["earlygame","task"] },
  { "name": "All Berries in Start of 2A (9)", "types": ["checkpoint_berries"] },
  { "name": "Forsaken City Blue Heart", "types": ["hearts","earlygame"] },
  { "name": "All Berries in Intervention (8)", "types": ["checkpoint_berries"] }
  ],
  
  [
  { "name": "Grabless Start of 3A", "types": ["grabless"] },
  { "name": "All Berries in Crossing (9)", "types": ["checkpoint_berries"] },
  { "name": "Complete Intervention without jumping", "types": ["earlygame","task"] },
  { "name": "5 Berries in 4 Chapters", "types": ["amount_berries"] },
  { "name": "Grabless Start of 4A", "types": ["grabless"] },
  { "name": "Complete Shrine without dashing", "types": ["task"] },
  { "name": "Get a 1-Up in 4A", "types": ["1up","challenge"] },
  { "name": "25 Berries", "types": ["amount_berries"] },
  { "name": "Get a 1-Up in 2A", "types": ["1up"] },
  { "name": "Reach Old Site in PICO-8", "types": ["pico-8"] },
  { "name": "Old Site B-Side", "types": ["2b"] },
  { "name": "20 Berries", "types": ["amount_berries"] },
  { "name": "Get 5 Berries in PICO-8", "types": ["pico-8"] }
  ],
  
  [
  { "name": "Forsaken City B-Side", "types": ["1b"] },
  { "name": "Grabless 1A", "types": ["grabless"] },
  { "name": "Grabless 2A", "types": ["grabless"] },
  { "name": "3 Blue Hearts", "types": ["hearts"] },
  { "name": "Get three 1-Ups", "types": ["1up","challenge"] },
  { "name": "Get a 1-Up in 5A", "types": ["1up","challenge"] },
  { "name": "All Berries in Elevator Shaft (4)", "types": ["checkpoint_berries"] },
  { "name": "2 Winged Berries in 2 Chapters", "types": ["special_berries"] },
  { "name": "All Berries in Huge Mess (7)", "types": ["checkpoint_berries"] },
  { "name": "2 Seeded Berries", "types": ["special_berries"] },
  { "name": "Blue and Red Heart in Old Site", "types": ["2b"] },
  { "name": "All Collectibles in 2A", "types": ["amount_berries"] },
  { "name": "Celestial Resort Blue Heart", "types": ["hearts"] }
  ],
  
  [
  { "name": "Triple 1-Up", "types": ["1up","challenge"] },
  { "name": "Invisible 1A", "types": ["invisible"] },
  { "name": "Invisible 2A", "types": ["invisible"] },
  { "name": "4 Hearts and 4 Cassettes", "types": ["amount_hearts","amount_cassettes"] },
  { "name": "Springless Presidential Suite", "types": ["challenge"] },
  { "name": "Grabless Start of 2B", "types": ["2b","grabless","challenge"] },
  { "name": "All Binoculars in Singular (2)", "types": ["ch9","binoculars"] },
  { "name": "5 Keys", "types": ["keys"] },
  { "name": "Invisible Start of 3A", "types": ["invisible"] },
  { "name": "Invisible Cliff Face", "types": ["invisible"] },
  { "name": "Invisible Huge Mess", "types": ["invisible"] }
  ],
  
  [
  { "name": "All Berries in Presidential Suite (3)", "types": ["checkpoint_berries"] },
  { "name": "Mirror Temple Cassette", "types": ["5b"] },
  { "name": "Huge Mess: Chest -> Books -> Towel", "types": ["huge_mess_pathing"] },
  { "name": "Huge Mess: Chest -> Towel -> Books", "types": ["huge_mess_pathing"] },
  { "name": "Huge Mess: Towel -> Books -> Chest", "types": ["huge_mess_pathing"] },
  { "name": "Golden Ridge Cassette", "types": ["4b"] },
  { "name": "2 optional Theo Cutscenes", "types": ["cutscene"] },
  { "name": "Complete 3 A-Sides", "types": ["amount_chapters"] },
  { "name": "Read Diary in Elevator Shaft", "types": ["resort_cutscene","cutscene"] },
  { "name": "Grabless Elevator Shaft", "types": ["grabless"] },
  { "name": "All Berries in Start of 4A (8)", "types": ["checkpoint_berries"] },
  { "name": "Blue and Red Heart in Forsaken City", "types": ["1b"] },
  { "name": "All Collectibles in 1A", "types": ["amount_berries"] }
  ],
  
  [
  { "name": "All Berries in Old Trail (7)", "types": ["checkpoint_berries"] },
  { "name": "3 Winged Berries", "types": ["special_berries"] },
  { "name": "4 Winged Berries", "types": ["special_berries"] },
  { "name": "Use 5 Binoculars in B-Sides", "types": ["binoculars"] },
  { "name": "5 Berries in 5 Chapters", "types": ["amount_berries"] },
  { "name": "Grabless Huge Mess", "types": ["grabless"] },
  { "name": "Huge Mess: Books -> Towel -> Chest", "types": ["huge_mess_pathing"] },
  { "name": "Huge Mess: Books -> Chest -> Towel", "types": ["huge_mess_pathing"] },
  { "name": "Huge Mess: Towel -> Chest -> Books", "types": ["huge_mess_pathing"] },
  { "name": "Jump on 10 Snowballs", "types": ["snowballs"] },
  { "name": "Grabless Presidential Suite", "types": ["grabless"] },
  { "name": "Golden Ridge Blue Heart", "types": ["hearts"] },
  { "name": "Grabless Cliff Face", "types": ["grabless","challenge"] },
  { "name": "4 Blue Hearts", "types": ["hearts"] },
  { "name": "Get a 1-Up in 3 Chapters", "types": ["1up","challenge"] }
  ],
  
  [
  { "name": "Find Theo's Phone in 5A", "types": ["cutscene"] },
  { "name": "Celestial Resort Cassette", "types": ["3b"] },
  { "name": "Grabless Unravelling", "types": ["grabless"] },
  { "name": "Get 2 Keys in 5B", "types": ["5b","task","keys"] },
  { "name": "All Berries in Cliff Face (5)", "types": ["checkpoint_berries"] },
  { "name": "Grabless Search", "types": ["grabless"] },
  { "name": "5 Winged Berries", "types": ["special_berries"] },
  { "name": "Talk to Theo in Search", "types": ["cutscene","search"] },
  { "name": "4 Cassettes", "types": ["amount_cassettes"] },
  { "name": "15 Berries in 4A", "types": ["amount_berries"] },
  { "name": "Use 6 Binoculars in B-Sides", "types": ["binoculars"] },
  { "name": "Get 10 Berries in PICO-8", "types": ["pico-8"] },
  { "name": "Stun Oshiro 10 times", "types": ["oshiro_stun"] },
  { "name": "Golden Ridge B-Side", "types": ["4b"] },
  { "name": "Winged Golden Berry", "types": ["challenge"] }
  ],
  
  [
  { "name": "Reach the Mirror in 2A in 1 Dash", "types": ["challenge"] },
  { "name": "Quintuple 1-Up", "types": ["1up","challenge"] },
  { "name": "Invisible 1B", "types": ["1b","invisible"] },
  { "name": "Invisible Presidential Suite", "types": ["invisible"] },
  { "name": "Get a 1-Up in 3A", "types": ["1up","challenge"] },
  { "name": "2 Keys in 2 Chapters", "types": ["keys"] },
  { "name": "Invisible 2B", "types": ["2b","invisible"] },
  { "name": "Invisible 3B Start", "types": ["3b","invisible"] },
  { "name": "Invisible Staff Quarters", "types": ["3b","invisible"] },
  { "name": "Kill 5 different Seekers", "types": ["seeker","task","challenge"] }
  ],
  
  [
  { "name": "Mirror Temple A-Side", "types": ["task"] },
  { "name": "Grabless Depths", "types": ["grabless"] },
  { "name": "All Berries in Shrine (9)", "types": ["checkpoint_berries"] },
  { "name": "10 Berries in 3A", "types": ["amount_berries"] },
  { "name": "Complete 2 B-Sides", "types": ["amount_chapters"] },
  { "name": "Get the Key in Depths", "types": ["task"] },
  { "name": "All Berries in Rescue (1)", "types": ["checkpoint_berries"] },
  { "name": "Mirror Temple Blue Heart", "types": ["hearts"] },
  { "name": "All Berries in Start of 5A (12)", "types": ["checkpoint_berries"] },
  { "name": "Hit a Kevin block from all 4 sides", "types": ["task"] },
  { "name": "All Berries in Unravelling (1)", "types": ["checkpoint_berries"] },
  { "name": "2 Blue and 2 Red Hearts", "types": ["amount_hearts","amount_chapters"] },
  { "name": "Get the Orb in PICO-8", "types": ["pico-8"] },
  { "name": "All Berries in Start of 3A (11)", "types": ["checkpoint_berries"] },
  { "name": "Get 1 Key in Power Source", "types": ["ch9","binoculars","keys"] }
  ],
  
  [
  { "name": "Reach Library (3B Checkpoint)", "types": ["3b"] },
  { "name": "All Berries in Into the Core (1)", "types": ["checkpoint_berries","core"] },
  { "name": "Reflection Cutscene in Hollows", "types": ["cutscene"] },
  { "name": "Grabless Lake", "types": ["grabless"] },
  { "name": "35 Berries", "types": ["amount_berries"] },
  { "name": "40 Berries", "types": ["amount_berries"] },
  { "name": "Complete PICO-8", "types": ["pico-8"] },
  { "name": "3 optional Theo Cutscenes", "types": ["cutscene"] },
  { "name": "Kill a Seeker", "types": ["seeker","task"] },
  { "name": "Use 1 Binocular in 4 Chapters", "types": ["binoculars"] },
  { "name": "Only top route in Hollows", "types": ["task","reflection_pathing"] },
  { "name": "Get 1 Key in Search", "types": ["task","search","keys"] },
  { "name": "Reflection Cassette", "types": ["6b"] },
  { "name": "Reflection Blue Heart", "types": ["hearts"] },
  { "name": "3 Seeded Berries", "types": ["special_berries"] }
  ],
  
  [
  { "name": "Complete 2 A-Sides and 2 B-Sides", "types": ["amount_chapters"] },
  { "name": "5 Cassettes", "types": ["amount_cassettes"] },
  { "name": "Use 5 Binoculars in Farewell", "types": ["ch9","binoculars"] },
  { "name": "Stun Seekers 15 times", "types": ["seeker","task"] },
  { "name": "All Berries in Depths (11)", "types": ["checkpoint_berries"] },
  { "name": "Mirror Temple B-Side", "types": ["5b"] },
  { "name": "Use 8 Binoculars", "types": ["binoculars"] },
  { "name": "All Berries in Search (6)", "types": ["checkpoint_berries"] },
  { "name": "Get 2 Keys in Power Source", "types": ["ch9","binoculars"] },
  { "name": "5 Hearts", "types": ["amount_hearts"] },
  { "name": "20 Berries in 5A", "types": ["amount_berries"] },
  { "name": "Use 7 Binoculars", "types": ["binoculars"] },
  { "name": "Use 2 Binoculars in 3 Chapters", "types": ["binoculars"] },
  { "name": "Get 15 Berries in PICO-8", "types": ["pico-8","challenge"] },
  { "name": "Celestial Resort B-Side", "types": ["3b"] }
  ],
  
  [
  { "name": "Invisible 3A", "types": ["invisible"] },
  { "name": "Grabless Start of 3B", "types": ["3b","grabless","challenge"] },
  { "name": "Complete a B-Side Grabless", "types": ["grabless","challenge"] },
  { "name": "Invisible Library", "types": ["3b","invisible"] },
  { "name": "Get a 1-Up in 4 Chapters", "types": ["1up","challenge"] },
  { "name": "PICO-8 100%", "types": ["pico-8"] },
  { "name": "Invisible Rooftop", "types": ["3b","invisible"] },
  { "name": "Jumpless Reflection (6A Checkpoint)", "types": ["task"] },
  { "name": "Get a 1-Up at the end of a Chapter", "types": ["1up","challenge"] },
  { "name": "Invisible 4A", "types": ["invisible"] },
  { "name": "All Berries in Start and Depths of 5A (23)", "types": ["checkpoint_berries"] },
  { "name": "Invisible Unravelling", "types": ["invisible"] }
  ],
  
  [
   { "name": "Only bottom route in Hollows", "types": ["task","reflection_pathing"] },
    { "name": "Get 2 Keys in Search", "types": ["task","search"] },
      { "name": "Use 1 Binocular in 5 Chapters", "types": ["binoculars"] },
    { "name": "7 Winged Berries", "types": ["special_berries"] },
    { "name": "Kill 2 different Seekers", "types": ["seeker","task"] },
    { "name": "Get 3 Keys in Power Source", "types": ["ch9","binoculars"] },
    { "name": "10 Berries in 3 Chapters", "types": ["amount_berries"] },
        { "name": "6 Winged Berries", "types": ["special_berries"] },
    { "name": "Switch to Ice on the right of Into the Core", "types": ["core"] },
    { "name": "5 Blue Hearts", "types": ["hearts"] },
      { "name": "Get 3 Keys in Search", "types": ["task","search"] },
      { "name": "Get 4 Keys in Power Source", "types": ["ch9","binoculars"] },
      { "name": "Complete 3 B-Sides", "types": ["amount_chapters"] },
    { "name": "3 Blue and 3 Red Hearts", "types": ["amount_hearts","amount_chapters"] },
    { "name": "Complete 2 Chapters Grabless", "types": ["grabless","challenge"] }
  ],
  
  [
  { "name": "Grabless Into the Core", "types": ["grabless"] },
  { "name": "Invisible Stepping Stones", "types": ["invisible"] },
  { "name": "8 Keys", "types": ["keys"] },
  { "name": "All Binoculars in Power Source (7)", "types": ["ch9","binoculars"] },
  { "name": "Jumpless Rooftop", "types": ["3b","challenge"] },
  { "name": "Grabless Reprieve", "types": ["grabless"] },
  { "name": "6 Blue Hearts", "types": ["amount_hearts"] },
  { "name": "Invisible Eye of the Storm", "types": ["invisible"] },
  { "name": "Jumpless Resolution", "types": ["lategame","task"] },
  { "name": "4 Keys in 2 Chapters", "types": ["keys"] },
  { "name": "Complete both Feather Minigames", "types": ["cutscene"] },
  { "name": "Disintegrate 13 Unique Jellyfish in Power Source", "types": ["ch9","binoculars","task"] },
  { "name": "Invisible Rock Bottom", "types": ["invisible"] },
  { "name": "20 Berries in 3 Chapters", "types": ["amount_berries","big_berries"] }
  ],
  
  [
  { "name": "Stun Seekers 20 times", "types": ["seeker","task"] },
    { "name": "Blue and Red Heart in Golden Ridge", "types": ["4b"] },
    { "name": "Grabless Hollows", "types": ["grabless","challenge"] },
    { "name": "50 Berries", "types": ["amount_berries"] },
    { "name": "15 Berries in 2 Chapters", "types": ["amount_berries"] },
    { "name": "15 Berries in 3A", "types": ["amount_berries"] },
      { "name": "Kill 3 different Seekers", "types": ["seeker","task"] },
    { "name": "45 Berries", "types": ["amount_berries"] },
    { "name": "Reach Rock Bottom (6A/6B Checkpoint)", "types": ["6b","lategame"] },
    { "name": "Use 2 Binoculars in 4 Chapters", "types": ["binoculars"] },
    { "name": "Blue and Red Heart in Mirror Temple", "types": ["5b"] },
      { "name": "All Berries in 0M (4)", "types": ["lategame"] },
    { "name": "All Berries in Heart of the Mountain (1)", "types": ["checkpoint_berries","core"] },
    { "name": "Use all Binoculars in 500M (3)", "types": ["binoculars","lategame"] },
    { "name": "Reflection A-Side", "types": ["lategame","task"] }
  ],
  
  [
  { "name": "Invisible Power Source", "types": ["invisible"] },
  { "name": "Use 12 Binoculars in Farewell", "types": ["ch9","binoculars"] },
  { "name": "Invisible 5A", "types": ["invisible"] },
  { "name": "All Binoculars in Remembered (5)", "types": ["ch9","binoculars"] },
  { "name": "Invisible 0M", "types": ["invisible"] },
  { "name": "Stun Seekers 10 times in 2 Chapters", "types": ["seeker","task"] },
  { "name": "Invisible 500M", "types": ["invisible"] },
  { "name": "Stun Oshiro 10 times in 2 Chapters", "types": ["oshiro_stun"] },
  { "name": "Invisible 1000M", "types": ["invisible"] },
  { "name": "Kill 3 different Seekers in 2 Chapters", "types": ["seeker","task"] },
  { "name": "Invisible Reprieve", "types": ["invisible"] },
  { "name": "10 Keys", "types": ["keys"] },
  { "name": "30 Berries in 2 Chapters", "types": ["amount_berries","big_berries"] },
  { "name": "Kevin Easteregg Room in Event Horizon", "types": ["ch9"] }
  ],
  
  [
  { "name": "All Collectibles in 4A", "types": ["amount_berries"] },
  { "name": "8 Winged Berries", "types": ["special_berries"] },
  { "name": "Complete 3 A-Sides and 3 B-Sides", "types": ["amount_chapters"] },
  { "name": "3 Gems in The Summit", "types": ["lategame","gems"] },
  { "name": "Grabless 3A", "types": ["grabless"] },
  { "name": "7 Hearts", "types": ["amount_hearts"] },
  { "name": "10 Berries in 4 Chapters", "types": ["amount_berries"] },
  { "name": "Grabless Rock Bottom", "types": ["lategame","grabless"] },
  { "name": "0M and 500M Gems", "types": ["lategame","gems","task"] },
  { "name": "Easteregg room in Reflection", "types": ["task"] },
  { "name": "All Collectibles in 3A", "types": ["amount_berries"] },
  { "name": "9 Winged Berries", "types": ["special_berries"] },
  { "name": "4 Seeded Berries", "types": ["special_berries","lategame"] },
  { "name": "6 Hearts", "types": ["amount_hearts"] },
  { "name": "20 Berries in 7A", "types": ["lategame"] }
  ],
  
  [
  { "name": "All Collectibles in 3 Chapters", "types": ["amount_berries"] },
  { "name": "6 Hearts and 6 Cassettes", "types": ["amount_hearts","amount_cassettes"] },
  { "name": "Jump on 10 Snowballs in 2 Chapters", "types": ["snowballs"] },
  { "name": "Secret Room in Determination", "types": ["ch9","challenge"] },
  { "name": "Use 4 Binoculars in 3 Chapters", "types": ["binoculars"] },
  { "name": "4 Keys in 3 Chapters", "types": ["keys"] },
  { "name": "Invisible 2500M", "types": ["invisible"] },
  { "name": "Get a 1-Up in 7A", "types": ["1up","challenge"] },
  { "name": "Grabless 1500M", "types": ["grabless"] },
  { "name": "Use 20 Binoculars in Farewell", "types": ["ch9","binoculars"] },
  { "name": "Grabless Remembered", "types": ["grabless","challenge"] },
  { "name": "Invisible 1500M", "types": ["invisible"] },
  { "name": "Grabless 2000M", "types": ["grabless"] },
  { "name": "5 Berries in 7 Chapters", "types": ["amount_berries"] }
  ],
  
  [
   { "name": "Use 9 Binoculars", "types": ["binoculars"] },
    { "name": "Grabless 5A", "types": ["grabless"] },
    { "name": "All Berries in 500M (6)", "types": ["lategame"] },
    { "name": "All 4 optional Theo Cutscenes", "types": ["cutscene"] },
    { "name": "Complete 5 A-Sides", "types": ["amount_chapters"] },
      { "name": "4 Gems in The Summit", "types": ["lategame","gems"] },
     { "name": "The Summit Cassette", "types": ["7b"] },
       { "name": "Use 10 Binoculars", "types": ["binoculars"] },
    { "name": "65 Berries", "types": ["amount_berries","big_berries"] },
    { "name": "1000M and 1500M Gems", "types": ["lategame","gems","task"] },
      { "name": "All Berries in 1000M (6)", "types": ["lategame"] },
    { "name": "Blue and Red Heart in Celestial Resort", "types": ["3b"] },
      { "name": "75 Berries", "types": ["amount_berries","big_berries"] },
    { "name": "10 Berries in 5 Chapters", "types": ["amount_berries"] },
    { "name": "Use 5 Binoculars in The Summit", "types": ["binoculars","lategame"] }
  ],
  
  [
  { "name": "Use all Binoculars in 1000M (4)", "types": ["binoculars","lategame"] },
  { "name": "Complete 4 B-Sides", "types": ["amount_chapters"] },
    { "name": "Reflection B-Side", "types": ["6b"] },
    { "name": "Reach the Intro Car in Remembered", "types": ["ch9","task","challenge"] },
    { "name": "5 Gems in the Summit", "types": ["lategame","gems"] },
    { "name": "2000M and 2500M Gems", "types": ["lategame","gems","task"] },
    { "name": "15 Berries in 3 Chapters", "types": ["amount_berries","big_berries"] },
    { "name": "Grabless 6A", "types": ["lategame","grabless","challenge"] },
    { "name": "All Berries in 1500M (8)", "types": ["lategame"] },
    { "name": "All Berries in 2000M (8)", "types": ["lategame"] },
    { "name": "Get 5 Keys in Power Source", "types": ["ch9","binoculars"] },
    { "name": "35 Berries in 7A", "types": ["lategame"] },
    { "name": "Blue and Red Heart in Reflection", "types": ["6b"] },
    { "name": "All Flags in 3000M", "types": ["task","lategame"] },
    { "name": "All Collectibles in 5A", "types": ["amount_berries"] },
    { "name": "Grabless 3000M", "types": ["grabless"] },
    { "name": "Complete 3000M with no Badeline Orbs", "types": ["task","lategame","challenge"] },
    { "name": "1 Key in 5 Chapters", "types": ["keys"] },
    { "name": "wavedash.ppt", "types": ["ch9","cutscene"] }
  ],
  
  [
  { "name": "All Berries in 2500M (8)", "types": ["lategame"] },
    { "name": "All Berries in 3000M (7)", "types": ["lategame"] },
    { "name": "All Berries in Hot and Cold (3)", "types": ["checkpoint_berries","core"] },
    { "name": "Use 2 Binoculars in 5 Chapters", "types": ["binoculars"] },
    { "name": "Core Blue Heart", "types": ["core"] },
    { "name": "Visit the Bird's Nest in Epilogue", "types": ["task","lategame"] },
    { "name": "The Summit B-Side", "types": ["7b"] },
    { "name": "100 Berries", "types": ["amount_berries","big_berries"] },
    { "name": "Complete 5 B-Sides", "types": ["amount_chapters"] },
    { "name": "15 Berries in 4 Chapters", "types": ["amount_berries","big_berries"] },
    { "name": "Reach Event Horizon (9 Checkpoint)", "types": ["ch9"] },
    { "name": "All Collectibles in 8A", "types": ["checkpoint_berries","core"] },
    { "name": "The Summit Blue Heart", "types": ["gems","hearts"] },
    { "name": "11 Winged Berries", "types": ["special_berries"] },
    { "name": "15 Berries in 5 Chapters", "types": ["amount_berries","big_berries"] },
    { "name": "Invisible 3000M", "types": ["invisible"] },
    { "name": "Invisible 7A", "types": ["invisible"] },
    { "name": "20 Berries in 4 Chapters", "types": ["amount_berries","big_berries"] }
  ],
  
  [
  { "name": "Hit a Kevin Block from all 4 Sides in 3 Chapters", "types": ["ch9","task"] },
  { "name": "1-Up in 5 Chapters", "types": ["1up","challenge"] },
  { "name": "All Binoculars in Event Horizon", "types": ["ch9","binoculars"] },
  { "name": "Reach Reconciliation", "types": ["ch9"] },
  { "name": "Grabless Heart of the Mountain", "types": ["grabless"] },
  { "name": "All Binoculars in Determination", "types": ["ch9","binoculars"] },
  { "name": "All Collectibles in 7A", "types": ["amount_berries"] },
  { "name": "Complete 6 B-Sides", "types": ["amount_chapters"] },
  { "name": "10 Hearts", "types": ["amount_hearts"] },
  { "name": "8 Cassettes", "types": ["amount_cassettes"] },
  { "name": "Crush a Pufferfish", "types": ["ch9"] },
  { "name": "All Binoculars in Stubbornness", "types": ["ch9","binoculars"] },
  { "name": "Use 2 Binoculars in 8 Chapters", "types": ["binoculars"] },
  { "name": "2 Keys in 4 Chapters", "types": ["keys"] },
  { "name": "Blue and Red Heart in The Summit", "types": ["7b"] },
  { "name": "25 Berries in 4 Chapters", "types": ["amount_berries","big_berries"] }
  ],
  
  [
  { "name": "Complete Farewell", "types": ["ch9"] },
  { "name": "12 Hearts", "types": ["amount_hearts"] },
  { "name": "Complete 4 A-Sides and B-Sides", "types": ["amount_chapters"] },
  { "name": "Use all Binoculars in A-Sides (14)", "types": ["binoculars"] },
  { "name": "Use all Binoculars in B-Sides (15)", "types": ["binoculars"] },
  { "name": "Kill 10 Different Seekers", "types": ["seeker","task","challenge"] }
  ],
  
  [
  { "name": "Moon Berry", "types": ["ch9","special_berries"] },
  { "name": "Complete 10 Chapters", "types": ["amount_chapters"] },
  { "name": "8 Blue Hearts", "types": ["amount_hearts"] },
  { "name": "Complete 7 B-Sides", "types": ["amount_chapters"] },
  { "name": "125 Berries", "types": ["amount_berries","big_berries"] },
  { "name": "Complete All A-Sides", "types": ["amount_chapters"] }
  ]]
  