bingoGenerator = require("./generators/generator_bases/srl_generator_v5.js");

var bingoList = [];
bingoList[1] = [
  { name: "1A-2/十字路 Theo对话", types: ["earlygame","cutscene"] },
  { name: "1A-1/开始 无跳", types: ["earlygame","task"] },
  { name: "1A-1/开始 6草莓", types: ["checkpoint_berries"] },
  { name: "1A-3/峡谷 5草莓", types: ["checkpoint_berries"] },
  { name: "1A 1-Up", types: ["1up","earlygame"] },
  { name: "1A 蓝心", types: ["hearts","earlygame"] },
  { name: "1A-3/峡谷 无冲", types: ["earlygame","task"] },
  { name: "1A-1/开始 无冲", types: ["earlygame","task"] },
  { name: "1A 磁带", types: ["1b","earlygame"] },
  { name: "2A 蓝心", types: ["hearts","earlygame"] },
];
bingoList[2] = [
  { name: "两个 1-Up", types: ["1up"] },
  { name: "1A 10草莓", types: ["amount_berries"] },
  { name: "2A-3/唤醒 Theo对话", types: ["earlygame","awake"] },
  { name: "在 4A-3/古道 最后一面走隐藏路线", types: ["task"] },
  { name: "2A-3/唤醒 1草莓", types: ["checkpoint_berries"] },
  { name: "2A-2/干涉 8草莓", types: ["checkpoint_berries"] },
  { name: "2A-3/唤醒 无跳", types: ["earlygame","awake"] },
  { name: "2A-3/唤醒 无冲", types: ["earlygame","awake"] },
  { name: "2A-1/开始 9草莓", types: ["checkpoint_berries"] },
  { name: "2水晶之心", types: ["amount_hearts"] },

];
bingoList[3] = [
  { name: "三章节 各5草莓", types: ["amount_berries"] },
  { name: "1个B面", types: ["amount_chapters"] },
  { name: "2A-3/唤醒 读诗词", types: ["earlygame","awake"] },
  { name: "3A-3/电梯井 Theo对话", types: ["resort_cutscene","cutscene"] },
  { name: "2A-2/干涉 无跳", types: ["earlygame","task"] },
  { name: "1A-2/十字路口 9草莓", types: ["checkpoint_berries"] },
  { name: "2A 10草莓", types: ["amount_berries"] },
  { name: "3A-2/乱七八糟 信封pico8", types: ["resort_cutscene","cutscene"] },
  { name: "两个章节 各1-Up", types: ["1up","challenge"] },
  { name: "3A-1/开始 无抓", types: ["grabless"] },
];
bingoList[4] = [
  { name: "2A 1-Up", types: ["1up"] },
  { name: "PICO-8 跑到旧址", types: ["pico-8"] },
  { name: "通关1B", types: ["1b"] },
  { name: "1A 全部收集品", types: ["amount_berries"] },
  { name: "1A-2/十字路口 无冲", types: ["challenge","task"] },
  { name: "2A 磁带", types: ["2b","earlygame"] },
  { name: "4A-2/神迹 无冲", types: ["task"] },
  { name: "4A-1/开始 无抓", types: ["grabless"] },
  { name: "4A 1-Up", types: ["1up","challenge"] },
  { name: "2张磁带", types: ["amount_cassettes"] },
];
bingoList[5] = [
  { name: "20草莓", types: ["amount_berries"] },
  { name: "PICO-8 5草莓", types: ["pico-8"] },
  { name: "通关2B", types: ["2b"] },
  { name: "1A 无抓", types: ["grabless"] },
  { name: "2A 无抓", types: ["grabless"] },
  { name: "三个 1-Up", types: ["1up","challenge"] },
  { name: "5A 1-Up", types: ["1up","challenge"] },
  { name: "3A-3/电梯井 4草莓", types: ["checkpoint_berries"] },
  { name: "四个章节 各5草莓", types: ["amount_berries"] },
  { name: "1个 kevin4方向", types: ["task"] },
];
bingoList[6] = [
  { name: "3A-2/乱七八糟 7草莓", types: ["checkpoint_berries"] },
  { name: "B面 3望远镜", types: ["binoculars","earlygame"] },
  { name: "第1章 蓝心+红心", types: ["1b"] },
  { name: "第2章 蓝心+红心", types: ["2b"] },
  { name: "2A 全部收集品", types: ["amount_berries"] },
  { name: "3A 蓝心", types: ["hearts"] },
  { name: "3A-4/总统套房 3草莓", types: ["checkpoint_berries"] },
  { name: "5A 磁带", types: ["5b"] },
  { name: "3A 柜子-书-毛巾", types: ["huge_mess_pathing"] },
  { name: "3A 柜子-毛巾-书", types: ["huge_mess_pathing"] },
];
bingoList[7] = [
  { name: "2水晶之心+2磁带", types: ["amount_hearts","amount_cassettes"] },
  { name: "1枚蓝心+1枚红心", types: ["amount_hearts","amount_chapters"] },
  { name: "2个可不触发的Theo对话", types: ["cutscene"] },
  { name: "三个章节 各1-Up", types: ["1up","challenge"] },
  { name: "3A-2/乱七八糟 无抓", types: ["grabless"] },
  { name: "3A-3/电梯井 读日记", types: ["resort_cutscene","cutscene"] },
  { name: "3A-3/电梯井 无抓", types: ["grabless"] },
  { name: "4A-1/开始 8草莓", types: ["checkpoint_berries"] },
  { name: "4A 3望远镜", types: ["binoculars","task"] },
  { name: "4A-4/悬崖峭壁 无抓", types: ["grabless"] },
];
bingoList[8] = [
  { name: "4A-3/古道 7草莓", types: ["checkpoint_berries"] },
  { name: "3个A面", types: ["amount_chapters"] },
  { name: "3飞草莓", types: ["special_berries","earlygame"] },
  { name: "B面 4望远镜", types: ["binoculars"] },
  { name: "B面 5望远镜", types: ["binoculars"] },
  { name: "五个章节 各5草莓", types: ["amount_berries"] },
  { name: "3A 毛巾-书-柜子", types: ["huge_mess_pathing"] },
  { name: "3A 书-柜子-毛巾", types: ["huge_mess_pathing"] },
  { name: "踩10雪球", types: ["snowballs"] },
  { name: "踩15雪球", types: ["snowballs"] },
];
bingoList[9] = [
  { name: "3A-4/总统套房 无抓", types: ["grabless"] },
  { name: "2种子草莓", types: ["special_berries"] },
  { name: "3张磁带", types: ["amount_cassettes"] },
  { name: "25草莓", types: ["amount_berries"] },
  { name: "30草莓", types: ["amount_berries"] },
  { name: "两个章节 各2望远镜", types: ["binoculars"] },
  { name: "3A 磁带", types: ["3b"] },
  { name: "4A 蓝心", types: ["hearts"] },
  { name: "5望远镜", types: ["binoculars"] },
  { name: "6望远镜", types: ["binoculars"] },
];
bingoList[10] = [
  { name: "5B 2钥匙", types: ["5b","task"] },
  { name: "4A 磁带", types: ["4b"] },
  { name: "3A 书-毛巾-柜子", types: ["huge_mess_pathing"] },
  { name: "3A 毛巾-柜子-书", types: ["huge_mess_pathing"] },
  { name: "5A-4/搜寻 无抓", types: ["grabless"] },
  { name: "4飞草莓", types: ["special_berries"] },
  { name: "5飞草莓", types: ["special_berries"] },
  { name: "5A-1/开始 无跳", types: ["task"] },
  { name: "5A-4/搜寻 Theo对话", types: ["cutscene","search"] },
  { name: "4A-4/悬崖峭壁 5草莓", types: ["checkpoint_berries"] },
];
bingoList[11] = [
  { name: "3水晶之心", types: ["amount_hearts"] },
  { name: "4水晶之心", types: ["amount_hearts"] },
  { name: "B面 6望远镜", types: ["binoculars"] },
  { name: "PICO-8 10草莓", types: ["pico-8"] },
  { name: "踩10次Oshiro", types: ["oshiro_stun"] },
  { name: "踩15次Oshiro", types: ["oshiro_stun"] },
  { name: "三个章节 各1望远镜", types: ["binoculars"] },
  { name: "通关4B", types: ["4b"] },
  { name: "1A隐藏金", types: ["challenge"] },
  { name: "5A-5/营救 无抓", types: ["grabless"] },
];
bingoList[12] = [
  { name: "2个B面", types: ["amount_chapters"] },
  { name: "3水晶之心+3磁带", types: ["amount_hearts","amount_cassettes"] },
  { name: "5A-2/深渊 无抓", types: ["grabless"] },
  { name: "5A-3/豁然开朗 无抓", types: ["grabless"] },
  { name: "5A-2/深渊 拿到钥匙", types: ["task"] },
  { name: "5A-5/营救 1草莓", types: ["checkpoint_berries"] },
  { name: "5A 蓝心", types: ["hearts"] },
  { name: "5A-1/开始 12草莓", types: ["checkpoint_berries"] },
  { name: "3A-1/开始 11草莓", types: ["checkpoint_berries"] },
  { name: "4A-2/神迹 9草莓", types: ["checkpoint_berries"] },
];
bingoList[13] = [
  { name: "5A-3/豁然开朗 1草莓", types: ["checkpoint_berries"] },
  { name: "5A-4/搜寻 6草莓", types: ["checkpoint_berries"] },
  { name: "4张磁带", types: ["amount_cassettes"] },
  { name: "2枚蓝心+2枚红心", types: ["amount_hearts","amount_chapters"] },
  { name: "PICO-8 拿到双冲", types: ["pico-8"] },
  { name: "9-3/能源 1钥匙", types: ["ch9","binoculars"] },
  { name: "到达3B-3/图书馆", types: ["3b"] },
  { name: "8A-2/深入腹地 1草莓", types: ["checkpoint_berries","core"] },
  { name: "6-3/洞穴 支线对话", types: ["cutscene"] },
  { name: "6A-2/湖 无抓", types: ["grabless"] },
];
bingoList[14] = [
  { name: "35草莓", types: ["amount_berries"] },
  { name: "40草莓", types: ["amount_berries"] },
  { name: "PICO-8 Any%", types: ["pico-8"] },
  { name: "3个可不触发的Theo对话", types: ["cutscene"] },
  { name: "杀1新浪", types: ["seeker","task"] },
  { name: "四个章节 各1望远镜", types: ["binoculars"] },
  { name: "6-3/洞穴 全走上面", types: ["task","reflection_pathing"] },
  { name: "5A-4/搜寻 1钥匙", types: ["task","search"] },
  { name: "6A 磁带", types: ["6b"] },
  { name: "6A 蓝心", types: ["hearts"] },
];
bingoList[15] = [
  { name: "3种子草莓", types: ["special_berries"] },
  { name: "2个A面+2个B面", types: ["amount_chapters"] },
  { name: "4水晶之心+4磁带", types: ["amount_hearts","amount_cassettes"] },
  { name: "5张磁带", types: ["amount_cassettes"] },
  { name: "踩10新浪", types: ["seeker","task"] },
  { name: "踩15新浪", types: ["seeker","task"] },
  { name: "9-3/能源 2钥匙", types: ["ch9","binoculars"] },
  { name: "第九章 5望远镜", types: ["ch9","binoculars"] },
  { name: "5A-2/深渊 11草莓", types: ["checkpoint_berries"] },
  { name: "通关5B", types: ["5b"] },

];
bingoList[16] = [
  { name: "5水晶之心", types: ["amount_hearts"] },
  { name: "5A 15草莓", types: ["amount_berries"] },
  { name: "5A 20草莓", types: ["amount_berries"] },
  { name: "7望远镜", types: ["binoculars"] },
  { name: "8望远镜", types: ["binoculars"] },
  { name: "PICO-8 15草莓", types: ["pico-8","challenge"] },
  { name: "通关3B", types: ["3b"] },
  { name: "6-3/洞穴 全走下面", types: ["task","reflection_pathing"] },
  { name: "5A-4/搜寻 2钥匙", types: ["task","search"] },
  { name: "5A-4/搜寻 3钥匙", types: ["task","search"] }
];
bingoList[17] = [
  { name: "4A 不跳过结尾剧情", types: ["cutscene","task"] },
  { name: "6飞草莓", types: ["special_berries"] },
  { name: "7飞草莓", types: ["special_berries"] },
  { name: "4个可不触发的Theo对话", types: ["cutscene"] },
  { name: "杀2不同新浪", types: ["seeker","task"] },
  { name: "9-3/能源 3钥匙", types: ["ch9","binoculars"] },
  { name: "9-3/能源 4钥匙", types: ["ch9","binoculars"] },
  { name: "五个章节 各1望远镜", types: ["binoculars"] },
  { name: "三个章节 各10草莓", types: ["amount_berries"] },
  { name: "8A-2/深入腹地 去右边变冰", types: ["core"] },
];
bingoList[18] = [
  { name: "3个B面", types: ["amount_chapters"] },
  { name: "3枚蓝心+3枚红心", types: ["amount_hearts","amount_chapters"] },
  { name: "两个章节 无抓", types: ["grabless","challenge"] },
  { name: "踩20新浪", types: ["seeker","task"] },
  { name: "杀3不同新浪", types: ["seeker","task"] },
  { name: "两个章节 各3望远镜", types: ["binoculars"] },
  { name: "第4章 蓝心+红心", types: ["4b"] },
  { name: "6A-3/洞穴 无抓", types: ["grabless","challenge"] },
  { name: "两个章节 各15草莓", types: ["amount_berries"] },
  { name: "3A 15草莓", types: ["amount_berries"] },
];
bingoList[19] = [
  { name: "5个A面", types: ["amount_chapters"] },
  { name: "45草莓", types: ["amount_berries"] },
  { name: "50草莓", types: ["amount_berries"] },
  { name: "到达6B-3/谷底", types: ["6b","lategame"] },
  { name: "三个章节 各2望远镜", types: ["binoculars"] },
  { name: "第5章 蓝心+红心", types: ["5b"] },
  { name: "8A-4/山之心 1草莓", types: ["checkpoint_berries","core"] },
  { name: "7A-500m 3望远镜", types: ["binoculars","lategame"] },
  { name: "0米 4草莓", types: ["lategame"] },
  { name: "6A-6/决断 无跳", types: ["lategame","task"] },
];
bingoList[20] = [
  { name: "8飞草莓", types: ["special_berries"] },
  { name: "9飞草莓", types: ["special_berries"] },
  { name: "3个A面+3个B面", types: ["amount_chapters"] },
  { name: "第7章 3宝石", types: ["lategame","gems"] },
  { name: "0米+500米宝石", types: ["lategame","gems","task"] },
  { name: "3A 无抓", types: ["grabless"] },
  { name: "四个章节 各10草莓", types: ["amount_berries"] },
  { name: "3A 全部收集品", types: ["amount_berries"] },
  { name: "6A-5/谷底 无抓", types: ["lategame","grabless"] },
  { name: "6A 彩蛋房", types: ["task"] },
];
bingoList[21] = [
  { name: "6水晶之心", types: ["amount_hearts"] },
  { name: "7水晶之心", types: ["amount_hearts"] },
  { name: "7A 20草莓", types: ["lategame"] },
  { name: "9望远镜", types: ["binoculars"] },
  { name: "10望远镜", types: ["binoculars"] },
  { name: "4A 15草莓", types: ["amount_berries"] },
  { name: "4A 20草莓", types: ["amount_berries"] },
  { name: "5A 无抓", types: ["grabless"] },
  { name: "500米 6草莓", types: ["lategame"] },
  { name: "1000米 6草莓", types: ["lategame"] },
];
bingoList[22] = [
  { name: "7A 磁带", types: ["7b"] },
  { name: "65草莓", types: ["amount_berries","big_berries"] },
  { name: "75草莓", types: ["amount_berries","big_berries"] },
  { name: "尾声 鸟巢", types: ["task","lategame"] },
  { name: "第7章 4宝石", types: ["lategame","gems"] },
  { name: "1000米+1500米宝石", types: ["lategame","gems","task"] },
  { name: "第3章 蓝心+红心", types: ["3b"] },
  { name: "五个章节 各10草莓", types: ["amount_berries"] },
  { name: "第七章 5望远镜", types: ["binoculars","lategame"] },
  { name: "7A-1000m 4望远镜", types: ["binoculars","lategame"] },
];
bingoList[23] = [
  { name: "4个B面", types: ["amount_chapters"] },
  { name: "通关6B", types: ["6b"] },
  { name: "9-4/铭记 隐藏车", types: ["ch9","task","challenge"] },
  { name: "第7章 5宝石", types: ["lategame","gems"] },
  { name: "2000米+2500米宝石", types: ["lategame","gems","task"] },
  { name: "4A 全部收集品", types: ["amount_berries"] },
  { name: "三个章节 各15草莓", types: ["amount_berries","big_berries"] },
  { name: "6A 无抓", types: ["lategame","grabless","challenge"] },
  { name: "1500米 8草莓", types: ["lategame"] },
  { name: "2000米 8草莓", types: ["lategame"] },
];
bingoList[24] = [
  { name: "7A 35草莓", types: ["lategame"] },
  { name: "第6章 蓝心+红心", types: ["6b"] },
  { name: "7A 3000米碰所有旗子", types: ["task","lategame"] },
  { name: "5A 全部收集品", types: ["amount_berries"] },
  { name: "2500米 8草莓", types: ["lategame"] },
  { name: "3000米 7草莓", types: ["lategame"] },
  { name: "8A-3/冰火两重天 3草莓", types: ["checkpoint_berries","core"] },
  { name: "四个章节 各2望远镜", types: ["binoculars"] },
  { name: "8A 蓝心", types: ["core"] },
  { name: "9-3/能源 5钥匙", types: ["ch9","binoculars"] },
];
bingoList[25] = [
  { name: "通关7B", types: ["7b"] },
  { name: "第7章 蓝心+红心", types: ["7b"] },
  { name: "100草莓", types: ["amount_berries","big_berries"] },
  { name: "4种子草莓", types: ["special_berries","lategame"] },
  { name: "5个B面", types: ["amount_chapters"] },
  { name: "四个章节 各15草莓", types: ["amount_berries","big_berries"] },
  { name: "7A 全部收集品", types: ["lategame"] },
  { name: "到达9-5/视界线", types: ["ch9"] },
  { name: "8A 全部收集品", types: ["checkpoint_berries","core"] },
  { name: "7A 蓝心", types: ["gems","hearts"] },
];
