bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Block a Scholar's Mate",
    "Create a Fork on the King/Queen",
    "Create a Pin",
    "Decline 3 Gambits",
    "Do a Puzzle Rush",
    "Finish 5 Puzzles",
    "Finish The Daily Puzzle",
    "Get 10 Bullet Wins",
    "Get 3 3 Check Wins",
    "Get 3 Blitz Wins",
    "Get 3 Rapid Wins",
    "Get 5 Atomic Check Wins",
    "Get 5 Blitz Wins",
    "Get 5 Bullet Wins",
    "Get a Rapid Wins",
    "Initiate a Draw",
    "Initiate a Stalemate",
    "Make An En Passant",
    "Offer a Draw and Have It Accepted",
    "Play 1 Person With Premium",
    "Play 3 People Without Premium",
    "Play Someone -100+ or +100+",
    "Play Someone With A Default Icon",
    "Play The 4 Knights Opening 3 Times",
    "Play The BongCloud Opening",
    "Play The Caro-Kann 2 Times",
    "Play The Englund Gambit",
    "Play The Italian Game",
    "Play The King's Gambit",
    "Play The London System",
    "Play The Queen's Gambit",
    "Play The Ruy Lopez 2 Times",
    "Play The Scandinavian Defense",
    "Play The Sicilian Defense 3 Times",
    "Play The Vienna Game",
    "Play a Fianchetto Opening",
    "Play a New Account",
    "Promote To A Queen",
    "Win At 4 Player Chess",
    "Win At Puzzle Battle"
];
