bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "*All Suits (Minus Tao and Super Chibi Robo)",
    "*Frog Sticker",
    "*Jenny Block “Puzzle”",
    "*Spy Training",
    "*The Past",
    "14000 Moolah",
    "1500 Happy Points",
    "1500 Scrap",
    "2 Lego Bricks",
    "20000 Moolah",
    "2500 Scrap",
    "3 Frog Rings",
    "3 Lego Bricks",
    "3000 Happy Points",
    "3500 Scrap",
    "4000 Moolah",
    "5000 Happy Points",
    "6 Frog Rings",
    "7000 Happy Points",
    "8000 Moolah",
    "9 Frog Rings",
    "Alien Ear Chip",
    "All Chips/Upgrades",
    "All Doors Backyard",
    "All Doors Basement",
    "All Doors Foyer",
    "All Doors Jenny’s Room",
    "All Doors Living Room",
    "All Tools",
    "Assemble Pirate Crew (1-3 members only)",
    "Bandage Delivery",
    "Charge Giga Battery",
    "Cooking Sticker",
    "Deliver Pirate Ship",
    "Deliver the Red Shoe",
    "Divorce",
    "Engagement Ring",
    "Fill Crayon Box",
    "Frog Suit",
    "Ghost Suit",
    "Green Brick",
    "Grow certain seeds/flowers",
    "Gunpowder",
    "Mr Prongs Sticker",
    "Obtain Dog Bone",
    "Obtain Radar",
    "Obtain Spoon",
    "Obtain Squirter",
    "Pajamas",
    "Peekoe Sticker",
    "Rail Training",
    "Range Chip",
    "Red Brick",
    "Sophie Sticker",
    "Ticket Stub Delivery",
    "Utilibots Sticker",
    "White Brick"
];
