bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "*The Past",
    "14000 Moolah",
    "1500 Happy Points",
    "1500 Scrap",
    "20000 Moolah",
    "2500 Scrap",
    "3 Frog Rings",
    "3000 Happy Points",
    "3500 Scrap",
    "4000 Moolah",
    "5000 Happy Points",
    "6 Frog Rings",
    "700 Happy Points",
    "8000 Moolah",
    "9 Frog Rings",
    "Alien Ear Chip",
    "All Chips/Upgrades",
    "All Doors Backyard",
    "All Doors Basement",
    "All Doors Foyer",
    "All Doors Jenny’s Room",
    "All Doors Living Room",
    "All Suits (Minus Tao and Super Chibi Robo)",
    "All Tools",
    "Assemble 2 Pirate Crew Members",
    "Assemble Full Pirate Crew",
    "Bandage Delivery",
    "Blue Flower to Mom",
    "Charge Giga Battery",
    "Cooking Sticker",
    "Deliver Dog Tags",
    "Deliver First Sophie Letter",
    "Deliver Pirate Ship",
    "Deliver the Red Shoe",
    "Divorce",
    "Dog Bone",
    "Engagement Ring",
    "Fill Crayon Box",
    "Frog Sticker",
    "Frog Suit",
    "Green Brick",
    "Gunpowder",
    "Mr Prongs Sticker",
    "Obtain Radar",
    "Obtain Spoon",
    "Obtain Squirter",
    "Pajamas",
    "Patrol with Drake Redcrest",
    "Peekoe Sticker",
    "Pink Flower to Mom",
    "Rail Training",
    "Range Chip",
    "Red Brick",
    "Spy Training",
    "Ticket Stub Delivery",
    "Utilibots Sticker",
    "White Brick",
    "White flower to Mom"
];
