bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "1000 Scrap",
    "14000 Moolah",
    "1500 Happy Points",
    "20000 Moolah",
    "3 Frog Rings",
    "400 Happy Points",
    "4000 Moolah",
    "500 Scrap",
    "6 Frog Rings",
    "700 Happy Points",
    "8000 Moolah",
    "9 Frog Rings",
    "Alien Ear Chip",
    "All Chips/Upgrades",
    "All Doors Backyard",
    "All Doors Basement",
    "All Doors Foyer",
    "All Doors Jenny’s Room",
    "All Doors Living Room",
    "All Suits (Minus Tao and Super Chibi Robo)",
    "All Tools",
    "Bandage Delivery",
    "Blue Flower to Mom",
    "Charge Giga Battery",
    "Cooking Sticker",
    "Deliver First Sophie Letter",
    "Deliver Pirate Ship",
    "Deliver the Red Shoe",
    "Divorce",
    "Dog Bone",
    "Dog Tags",
    "Fill Crayon Box",
    "Free Funky Phil",
    "Frog Sticker",
    "Frog Suit",
    "Green Brick",
    "Gunpowder",
    "Mr Prongs Sticker",
    "Obtain Radar",
    "Obtain Spoon",
    "Obtain Squirter",
    "Pajamas",
    "Patrol with Drake Redcrest",
    "Peekoe Sticker",
    "Pink Flower to Mom",
    "Rail Training",
    "Range Chip",
    "Red Brick",
    "Spy Training",
    "Squirt Nectar on Sunshine",
    "Ticket Stub Delivery",
    "Utilibots Sticker",
    "Wake up the Bird",
    "White Brick",
    "White flower to Mom"
];
