bingoGenerator = require("./generators/generator_bases/simple_generator.js")

var bingoList = [
    "Take 3 cities",
    "Ally 3 city states",
    "Meet everyone",
    "Travel all the way around the world",
    "First Religion",
    "3 great person tiles",
    "Fully conquer a civ",
    "First to build a wonder",
    "First to build 5 wonders",
    "Own 10 wonders",
    "Industrial age",
    "Be so unhappy that a rebellion starts",
    "2000 gold",
    "Level 5 unit",
    "5 of one luxury",
    "Full social policy",
    "Build 3 cities",
    "Own 6 cities",
    "Find a natural wonder",
    "Lose 5 workers to barbs",
    "Complete religion dom over other civ",
    "Conquer a holy city and convert",
    "5 trade routes",
    "15 population",
    "Have a city more than 30 hexes from capital",
    "Take a city you founded back from another civ.",
    "Be at war for over 50 turns",
    "Be at war with all other civs in the game",
    "Another civ thinks your warmongering is global concern.",
    "Pillage 10 hexes",
    "Culture dom over another civ",
    "20 happiness",
    "City starvation",
    "City with >20 population",
    "Capture another religions unit",
    "Be elected host of WC",
    "Plunder 2 trade routes in one turn",
    "Steal a technology",
    "20 excess stratigic resource (total)"
];
