bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "1 Coin Bag (Puffle Rescue)",
    "1 Coin Bag (Thin Ice)",
    "1 Coin Bubble",
    "1-up Blast",
    "1-up Captain",
    "1-up Leader",
    "10 Coin Bags",
    "10 Sea Levels",
    "2 Coin Bags",
    "2 Coin Bubbles",
    "20 Sea Levels",
    "3 Coin Bags (Puffle Rescue)",
    "3 Coin Bubbles",
    "30 Sea Levels",
    "6 Coin Bags",
    "Ace Angler",
    "Ace Pilot",
    "Afishionado",
    "All Coin Bags",
    "Aqua Puffle",
    "Astro 1-up",
    "Astro Expert",
    "Astro Master",
    "Astro Secret",
    "Astro10 Max",
    "Astro20 Max",
    "Astro30 Max",
    "Astro40",
    "Astro5",
    "Astro5 Max",
    "Aunt Arctic Letter",
    "Blueprint",
    "Bubble Catch",
    "Candy Land",
    "Cart Expert",
    "Cart Master",
    "Cave Coins",
    "Cave Coins Max",
    "Cave Coins Plus",
    "Chef Hat",
    "Chocolate Box",
    "Clam Compress",
    "Clam Master",
    "Clam Pressure",
    "Clam Success",
    "Clam Timer",
    "Clam Treasure",
    "Clock Target",
    "Close Call",
    "Cocoa Beans",
    "Cool Gift",
    "Crab Cuts",
    "Crash!",
    "Easy Cannon",
    "Easy Flip",
    "Easy Grind",
    "Easy Jump",
    "Easy Spin",
    "Easy Tube",
    "Employee Award",
    "Expert Catch",
    "Express Rescue",
    "Extreme Cannon",
    "Extreme Rescue",
    "Fiery Squids",
    "First Place",
    "First Trick",
    "Fishtastic",
    "Flip Mania",
    "Flip Star",
    "Fly Fisher",
    "Food Fiasco",
    "Fuel Command",
    "Fuel Rank 1",
    "Fuel Rank 2",
    "Fuel Rank 3",
    "Fuel Rank 4",
    "Fuel Rank 5",
    "Fuel Wings",
    "G's Letter",
    "Going Places",
    "Graduate",
    "Gray Goodies",
    "Great Balance",
    "Handy Award",
    "High Jump",
    "Ice Bonus",
    "Ice Master",
    "Ice Trekker",
    "Iced Treasure",
    "Jet Pack 5",
    "Just Dessert",
    "Kerching!",
    "Lift Off",
    "Max Flips",
    "Max Grind",
    "Max Spin",
    "Max Tube",
    "Mine Grind",
    "Mine Marvel",
    "Mine Mission",
    "Mission 1 Medal",
    "Mission 10 Medal",
    "Mission 11 Medal",
    "Mission 2 Medal",
    "Mission 3 Medal",
    "Mission 4 Medal",
    "Mission 5 Medal",
    "Mission 6 Medal",
    "Mission 7 Medal",
    "Mission 8 Medal",
    "Mission 9 Medal",
    "Pearl Capture",
    "Pennant",
    "Pizza Box",
    "Pizza Chef",
    "Pizza Master",
    "Prize Mullet",
    "Puffle Bonus",
    "Puffle Boost",
    "Puffle Pilot",
    "Puffle Power",
    "Puffle Surfin'",
    "Quick Catch",
    "Rapid Rescue",
    "SOS 30",
    "SOS 60",
    "Shark!",
    "Ship Blast",
    "Shock King",
    "Snack Attack",
    "Snow Globe",
    "Snow Hero",
    "Snow Master",
    "Snow Student",
    "Spice Sea",
    "Squid Spotter",
    "Super Cannon",
    "Super Catch",
    "Super Grind",
    "Super Spin",
    "Super Tube",
    "Surf's Up",
    "Survivor",
    "Thank You Card",
    "Trick Master",
    "Trick Star",
    "Ultimate Duo",
    "Underground",
    "Worm Win"
];
