// 102 Dalmatians: Puppies to the rescue Bingo
// Version 6.0
// By DarkLizzard
bingoGenerator = require("./generators/generator_bases/srl_generator_v5.js");
var bingoList = [];
bingoList[1] = 
[{"name": "Collect all purple tokens"},
{"name": "Collect all red tokens"},
{"name": "Collect all blue tokens"},
{"name": "Collect all green tokens"},
{"name": "Collect all yellow tokens"},
{"name": "Collect all purple tokens"},
{"name": "Collect all red tokens"},
{"name": "Collect all blue tokens"},
{"name": "Collect all green tokens"},
{"name": "Collect all yellow tokens"},
{"name": "Collect all purple tokens"},
{"name": "Collect all red tokens"},
{"name": "Collect all blue tokens"},
{"name": "Collect all green tokens"},
{"name": "Collect all yellow tokens"},
{"name": "Get a gem"}],
bingoList[2] = 
[{"name": "Finish all red token maps"},
{"name": "Finish all blue token maps"},
{"name": "Finish all green token maps"},
{"name": "2 Platinum relics"},
{"name": "3 Platinum relics"},
{"name": "4 Platinum relics"},
{"name": "2 Platinum relics & 3 tokens"},
{"name": "2 Platinum relics & 4 tokens"},
{"name": "6 Collectables & Beat a boss in any WR"},
{"name": "1 token of each colour"},
{"name": "1 token of each WR"},
{"name": "Finish all yellow token maps"}],
bingoList[3] = 
[{"name": "2 Yellow tokens"},
{"name": "3 Yellow tokens"},
{"name": "3 Yellow tokens"},
{"name": "2 Red tokens"},
{"name": "3 Red tokens"},
{"name": "3 Red tokens"},
{"name": "2 Green tokens"},
{"name": "3 Green tokens"},
{"name": "3 Green tokens"},
{"name": "2 Blue tokens"},
{"name": "3 Blue tokens"},
{"name": "3 Blue tokens"},
{"name": "2 Purple tokens"},
{"name": "3 Purple tokens"},
{"name": "3 Purple tokens"}],
bingoList[4] = 
[{"name": "Crash cove 100%"},
{"name": "Oxide station 100%"},
{"name": "Dingo canyon 100%"},
{"name": "Polar pass 100%"},
{"name": "Crash cove 100%"},
{"name": "Oxide station 100%"},
{"name": "Dingo canyon 100%"},
{"name": "Polar pass 100%"},
{"name": "10 collectables"}],
bingoList[5] = 
[{"name": "N.Gin labs 100%"},
{"name": "Blizzard bluff 100%"},
{"name": "Papu's pyramid 100%"},
{"name": "5 collectables from WR4"},
{"name": "5 collectables from WR2"},
{"name": "Sewer Speedway 100%"}],
bingoList[6] = 
[{"name": "Cortex castle 100%"},
{"name": "Coco park 100%"},
{"name": "Mystery caves 100%"},
{"name": "Slide coliseum Platinum relic"},
{"name": "Turbo track Platinum relic"},
{"name": "5 collectables from WR3"},
{"name": "5 collectables from WR1"},
{"name": "Tiny arena 100%"}],
bingoList[7] = 
[{"name": "Roo's tubes 100%"},
{"name": "Tiger temple 100%"},
{"name": "Dragon mines 100%"},
{"name": "Roo's tubes under 1:30 & Sewer speedway Platinum relic"},
{"name": "Beat Ripper Roo & Dragon mines under 1:37"},
{"name": "N.gin labs platinum & Tiger temple under 1:50"},
{"name": "Papu's pyramid Platinum relic & Polar pass under 3:00"},
{"name": "Hot air skyways 100%"}],
bingoList[8] = 
[{"name": "3 Gold relics"},
{"name": "4 Gold Relics"},
{"name": "4 Gold Relics"},
{"name": "5 Gold Relics"},
{"name": "Blizzard bluff token & Hot air skyway relic"},
{"name": "Dingo canyon token & Turbo track relic"},
{"name": "Mystery caves token & Blizzard bluff relic"},
{"name": "Dingo canyon Gold relic & Turbo track relic"},
{"name": "Sewer speedway Platinum relic & Blizzard bluff token"},
{"name": "Sewer speedway Gold relic & Hot air skyway token"},
{"name": "Finish 6 different tracks"},
{"name": "Finish 5 different tracks"}],
bingoList[9] = 
[{"name": "1 relic from each WR"},
{"name": "2 Gold Relics from WR1"},
{"name": "2 Gold Relics from WR2"},
{"name": "2 Gold Relics from WR3"},
{"name": "2 Gold Relics from WR4"},
{"name": "3 Gold Relics from WR1"},
{"name": "3 Gold Relics from WR2"},
{"name": "3 Gold Relics from WR3"},
{"name": "3 Gold Relics from WR4"},
{"name": "Finish 2 tracks without any shortcuts"},
{"name": "Finish 3 tracks without any shortcuts"},
{"name": "Finish 4 tracks without any shortcuts"},
{"name": "2 Relics from WR5"}],
bingoList[10] = 
[{"name": "Crash cove gold & Slide coliseum platinum relic"},
{"name": "Crash cove gold relic & Cortex castle CTR token"},
{"name": "3 collectables N.gin Labs & Crash cove"},
{"name": "Crash cove platinum relic & Hot air skyways Platinum relic"},
{"name": "Oxide station token & Tiny arena relic"},
{"name": "Tiger temple token & Coco park relic"},
{"name": "Cortex castle token & Pinstripe"},
{"name": "Cortex castle token & Komodo Joe"},
{"name": "N.gin labs token & Ripper roo"},
{"name": "N.gin labs token & Papu pyramid token"},
{"name": "Crash cove token & Dingo canyon Gold relic"},
{"name": "Crash cove platinum relic & Hot air skyways token"}],
bingoList[11] = 
[{"name": "Crash cove gold relic & Dragon mines Platinum relic"},
{"name": "Sewer speedway token & N.gin labs Gold relic"},
{"name": "All Gold relics from WR1"},
{"name": "All Gold relics from WR2"},
{"name": "All Gold relics from WR3"},
{"name": "All Gold relics from WR4"},
{"name": "All relics from WR"},
{"name": "All tokens from WR"},
{"name": "Coco park token & Papu's pyramid token"},
{"name": "Coco park Platinum & Hot air skyway token"},
{"name": "Cortex castle token & N.gin labs token"},
{"name": "Blizzard bluff Platinum  relic & Hot air skyway Platinum relic"},
{"name": "2 tokens from WR2 and 2 Platinum relics from WR3"},
{"name": "2 Gold relics from WR2 and 2 Platinum relics from WR3"},
{"name": "2 Gold relics from WR2 and 2 tokens from WR3"},
{"name": "2 tokens from WR2 and 2 Platinum relics from WR1"},
{"name": "2 tokens from WR2 and 2 Platinum relics from WR4"},
{"name": "2 tokens from WR2 and 2 Gold relics from WR1"},
{"name": "2 tokens from WR2 and 2 Gold relics from WR4"},
{"name": "2 tokens from WR1 and 2 Platinum relics WR2"},
{"name": "2 tokens from WR4 and 2 Platinum relics WR3"},
{"name": "2 Platinum relics from WR1 and 2 tokens from WR3"},
{"name": "Beat any boss without getting hit"}],
bingoList[12] = 
[{"name": "Finish Crash cove, Polar Pass, Papu's Pyramid"},
{"name": "Finish Mystery caves, Tiny arena, Dingo canyon"},
{"name": "Finish Sewer speedway, Tiny arena, Dragon mines"},
{"name": "Finish Coco park, Mystery caves, Oxide station"},
{"name": "Finish Blizzard bluff, Polar pass, Hot air skyway"},
{"name": "Finish 1 track from each WR"},
{"name": "3 collectables N.gin Labs & Crash cove"},
{"name": "Any purple token with 20+ seconds remaining"},
{"name": "Finish Nitro court with 25 seconds remaining"},
{"name": "Mystery caves Gold relic & Oxide station token"},
{"name": "Finish 8 different tracks"},
{"name": "Finish 9 challenges"},
{"name": "Get 5 tokens in total"}],
bingoList[13] = 
[{"name": "Get a Platinum relic without missing any box"},
{"name": "Finish 2 Relic races without missing any box"},
{"name": "Finish 3 Relic races without missing any box"},
{"name": "Finish Crash cove, Coco park token & Blizzard bluff Gold relic"},
{"name": "Finish Roo's tubes, Tiger temple token & Dragon mines Gold relic"},
{"name": "Finish Mystery caves, Papu's pyramid token & Polar pass Gold relic"},
{"name": "Finish Sewer speedway, Dingo canyon token & Tiny arena Gold relic"},
{"name": "Finish N.gin labs, Crash cove token & Coco park Gold relic"},
{"name": "Finish Cortex castle, Roo's tubes token & Tiger temple Gold relic"},
{"name": "Finish Hot air skyway, Mystery caves token & Papu's pyramid Gold relic"},
{"name": "Finish Oxide station, Sewer speedway token & Dingo canyon Gold relic"},
{"name": "Finish Blizzard bluff, N.gin labs token & Crash cove Gold relic"},
{"name": "Finish Dragon mines, Cortex castle token & Roo's tubes Gold relic"},
{"name": "Finish Polar pass, Hot air skyway token & Mystery caves Gold relic"},
{"name": "Finish Tiny arena, Oxide station token & Sewer speedway Gold relic"},
{"name": "Finish Coco park, Blizzard bluff token & N.gin labs Gold relic"},
{"name": "Finish Tiger temple, Dragon mines token & Cortex castle Gold relic"},
{"name": "Finish Papu's pyramid, Polar pass token & Hot air skyway Gold relic"},
{"name": "Finish Dingo canyon, Tiny arena token & Oxide station Gold relic"},
{"name": "Get 8 tokens in total"}],
bingoList[14] = 
[{"name": "Oxide station Gold/Platinum relic & Papu's pyramid token"},
{"name": "Cortex castle Gold/Platinum relic & N.gin labs token"},
{"name": "Mystery caves Gold/Platinum relic & Blizzard bluff token"},
{"name": "Sewer speedway token & Mystery caves token"},
{"name": "Crash cove Platinum & Finish Cortex castle"},
{"name": "Hot air skyway Platinum relic & Finish Tiny arena"},
{"name": "Sewer speedway Gold/Platinum relic & Dingo canyon token"},
{"name": "Dragon mines Gold/Platinum relic & Papu's pyramid token"},
{"name": "Komodo Joe & finish Tiny arena"}],
bingoList[15] = 
[{"name": "Blizzard bluff token & Finish Crash cove"},
{"name": "Roo's tubes Gold/Platinum relic & Oxide station token"},
{"name": "Tiger temple Gold/Platinum relic & Draon mines token"},
{"name": "N.gin labs Gold/Platinum relic & Finish Hot air skyway"},
{"name": "N.gin labs Gold/Platinum relic & Finish Oxide station"},
{"name": "Papu's Pyramid Gold/Platinum relic & Finish Oxide station"},
{"name": "Tiger temple Gold/Platinum relic & Oxide station token"},
{"name": "Get a token in WR2 & Beat pinstripe"},
{"name": "Get a token in WR3 & Beat Pinstripe"},
{"name": "Get a token in WR4 & Finish Dingo canyon"},
{"name": "Get a token in WR1 & Finish Polar pass"},
{"name": "Beat Pinstripe & Blizzard bluff"}],
bingoList[16] = 
[{"name": "All tokens from WR1"},
{"name": "All tokens from WR4"},
{"name": "Finish all tracks in WR1"},
{"name": "Finish all tracks in WR4"},
{"name": "Touch super-turbo pads in 4 different levels"},
{"name": "Touch turbo pads in 5 different levels"},
{"name": "Hot air skyway under 3:30"},
{"name": "Sewer speedway under 2:10"},
{"name": "Coco park under 1:35"},
{"name": "Dingo canyon under 1:42"},
{"name": "Nitro court under 1:40"},
{"name": "Cortex castle under 3:00 & Rocky road token"},
{"name": "Beat N.Oxide & finish Hot air skyway"}],
bingoList[17] = 
[{"name": "All tokens from WR3"},
{"name": "All tokens from WR2"},
{"name": "Finish all tracks in WR2"},
{"name": "Finish all tracks in WR3"},
{"name": "Touch 7 different super-turbo pads"},
{"name": "Oxide station under 3:10"},
{"name": "Crash cove under 1:30"},
{"name": "Mystery caves under 2:20"},
{"name": "Open 3x doors in tiger temple & Drive through the railway in Dragon mines"}],
bingoList[18] = 
[{"name": "3 collectables Mystery caves & Roo's tubes"},
{"name": "3 collectables Tiger temple & Roo's tubes"},
{"name": "3 collectables Polar pass & Roo's tubes"},
{"name": "3 collectables Cortex castle & Roo's tubes"},
{"name": "Finish Roo's tubes, Tiny arena, Dragon mines"},
{"name": "Finish Oxide station, Blizzard bluff, N.gin labs"},
{"name": "Mystery caves token & Blizzard bluff Gold relic"},
{"name": "3 collectables Mystery caves & Roo's tubes"},
{"name": "3 collectables Tiger temple & Roo's tubes"},
{"name": "3 collectables Polar pass & Roo's tubes"},
{"name": "3 collectables Cortex castle & Roo's tubes"},
{"name": "Finish Roo's tubes, Tiny arena, Dragon mines"},
{"name": "Finish Oxide station, Blizzard bluff, N.gin labs"},
{"name": "Mystery caves token & Blizzard bluff Gold relic"},
{"name": "Beat Ripper Roo & Nitro court token"},
{"name": "Beat Ripper Roo & Polar pass token"},
{"name": "Beat Ripper Roo & N.gin labs token"},
{"name": "Beat Ripper Roo & Hot air skyway Platinum relic"},
{"name": "Beat Papu Papu & Rampage ruins token"},
{"name": "Beat Papu Papu & Crash cove Gold relic"},
{"name": "Beat Papu Papu & Mystery caves Platinum relic"},
{"name": "Beat Papu Papu & Papu's pyramid Gold relic"},
{"name": "Beat Komodo Joe & Slide coliseum Platinum relic"},
{"name": "Beat Komodo Joe & Hot air skyway Gold relic"},
{"name": "Beat Komodo Joe & Crash cove Platinum relic"},
{"name": "Beat Komodo Joe & Sewer speedway token"},
{"name": "Beat Komodo Joe & Tiny arena token"},
{"name": "Beat Pinstripe & Dragon mines ctr token"},
{"name": "Beat Pinstripe & Dingo canyon Gold relic"},
{"name": "Beat Pinstripe & Sewer speedway Gold relic"},
{"name": "Beat N.oxide & Slide coliseum relic"},
{"name": "Beat N.oxide & Crash cove Platinum relic"},
{"name": "Beat N.oxide & Oxide station Platinum relic"},
{"name": "Beat N.oxide & Oxide station token"},
{"name": "Beat N.oxide & Hot air skyway token"},
{"name": "Beat N.oxide & Roo's tubes Gold relic"},
{"name": "Finish all tracks in WR"},
{"name": "Finish all tracks in WR"},
{"name": "Finish all tracks in WR"},
{"name": "Finish all tracks in WR"},
{"name": "Finish all tracks in WR"},
{"name": "Get 5 relics in total"}],
bingoList[19] = 
[{"name": "Skull rock token & Slide coliseum Gold relic"},
{"name": "Get gold/platinum relics in Polar pass, Tiger temple & Blizzard bluff"},
{"name": "Get gold/platinum relics in Cortex castle, Tiger temple & Sewer speedway"},
{"name": "Get gold/platinum relics in Polar pass, Turbo track & Crash cove"},
{"name": "Get gold/platinum relics in Slide Coliseum, N.gin labs & Blizzard bluff token"},
{"name": "Get gold/platinum relics in Turbo track, Hot air skyway & Coco park"},
{"name": "Get gold/platinum relics in Papu's pyramid, Tiny arena & N.gin labs token"},
{"name": "Get gold/platinum relics in Tiny arena, Tiger temple & Coco park token"},
{"name": "Get gold/platinum relics in Turbo track, Hot air skyway & Rampage ruins token"},
{"name": "Get gold/platinum relics in Papu's pyramid, Tiny arena & Nitro court token"},
{"name": "Get gold/platinum relics in Tiny arena, Tiger temple & Skull rock token"},
{"name": "Get gold/platinum relics in Polar pass, Tiger temple & Rocky road token"}],
bingoList[20] = 
[{"name": "Get gold/platinum relics in Crash cove, Sewer speedway & Tiny arena"},
{"name": "Get gold/platinum relics in Sewer speedway, Papu's pyramid & Coco park"},
{"name": "Get gold/platinum relics in N.gin labs, Polar pass & Dragon mines"},
{"name": "Get gold/platinum relics in Coco park, Blizzard bluff & Mystery caves"},
{"name": "Get gold/platinum relics in Crash cove, Sewer speedway & Nitro court"},
{"name": "Get gold/platinum relics in Sewer speedway, Oxide station & Skull rock"},
{"name": "Get gold/platinum relics in N.gin labs, Crash cove & Rocky road"},
{"name": "Get gold/platinum relics in Coco park, Blizzard bluff & Rampage ruins"},
{"name": "Get gold/platinum relics in Crash cove, Roo's tubes & Tiny arena token"},
{"name": "Get gold/platinum relics in Dingo canyon, Tiger temple & Oxide station token"},
{"name": "Get gold/platinum relics in Papu's pyramid, Tiny arena & N.gin labs token"}],
bingoList[21] = 
[{"name": "1 token from WR1 & 2 Yellow tokens"},
{"name": "1 token from WR4 & 2 Red tokens"},
{"name": "2 tokens from WR4 & 1 Red token"},
{"name": "2 tokens from WR1 & 1 Yellow token"},
{"name": "2 tokens from WR3 & 2 Green tokens"},
{"name": "2 tokens from WR2 & 2 Green tokens"},
{"name": "2 tokens from WR3 & 2 Blue tokens"},
{"name": "2 tokens from WR2 & 2 Blue tokens"},
{"name": "2 tokens from WR4 & 2 Relics from WR5"},
{"name": "2 tokens from WR1 & 2 Relics from WR5"},
{"name": "2 tokens from WR3 & 2 Relics from WR5"},
{"name": "2 tokens from WR2 & 2 Relics from WR5"},
{"name": "2 tokens from WR4 & 2 Relics from WR4"},
{"name": "2 tokens from WR1 & 2 Relics from WR4"},
{"name": "2 tokens from WR3 & 2 Relics from WR4"},
{"name": "2 tokens from WR2 & 2 Relics from WR4"},
{"name": "2 tokens from WR4 & 2 Relics from WR3"},
{"name": "2 tokens from WR1 & 2 Relics from WR3"},
{"name": "2 tokens from WR3 & 2 Relics from WR3"},
{"name": "2 tokens from WR2 & 2 Relics from WR3"},
{"name": "2 tokens from WR4 & 2 Relics from WR2"},
{"name": "2 tokens from WR1 & 2 Relics from WR2"},
{"name": "2 tokens from WR3 & 2 Relics from WR2"},
{"name": "2 tokens from WR2 & 2 Relics from WR2"},
{"name": "2 tokens from WR4 & 2 Relics from WR1"},
{"name": "2 tokens from WR1 & 2 Relics from WR1"},
{"name": "2 tokens from WR3 & 2 Relics from WR1"},
{"name": "2 tokens from WR2 & 2 Relics from WR1"},
{"name": "Open 3x doors in Tiger temple without fail"}],
bingoList[22] = 
[{"name": "Crash cove Platinum relic"},
{"name": "Roo's tubes Platinum relic"},
{"name": "Mystery caves Platinum relic"},
{"name": "Sewer speedway Platinum relic"},
{"name": "Coco park Platinum relic"},
{"name": "Tiger temple Platinum relic"},
{"name": "Papu's pyramid Platinum relic"},
{"name": "Dingo canyon Platinum relic"},
{"name": "Blizzard bluff Platinum relic"},
{"name": "Dragon mines Platinum relic"},
{"name": "Polar pass Platinum relic"},
{"name": "Tiny arena Platinum relic"},
{"name": "N.gin labs Platinum relic"},
{"name": "Cortex castle Platinum relic"},
{"name": "Hot air skyway Platinum relic"},
{"name": "Oxide station Platinum relic"}],
bingoList[23] = 
[{"name": "Rocky road token & Cortex castle 100%"},
{"name": "Rocky road token & Tiny arena 100%"},
{"name": "Rocky road token & Sewer speedway 100%"},
{"name": "Rocky road token & Sewer speedway Platinum relic"},
{"name": "Rocky road token & Polar pass Gold relic"},
{"name": "Rocky road token & Papu's pyramid Token"},
{"name": "Nitro court token & Cortex castle Token"},
{"name": "Nitro court token & Crash cove Token"},
{"name": "Nitro court token & Dingo Canyon Platinum relic"},
{"name": "Rampage ruins token & Dragon mines 100%"},
{"name": "Rampage ruins token & Tiger temple 100%"},
{"name": "Rampage ruins token & Tiger temple Platinum relic"},
{"name": "Rampage ruins token & Mystery caves 100%"},
{"name": "Rampage ruins token & Hot air skyways Platinum relic"},
{"name": "Skull rock token & Papu's pyramid 100%"},
{"name": "Skull rock token & Roo's tubes Platinum relic"},
{"name": "Skull rock token & Blizzard bluff Platinum relic"},
{"name": "Beat Komodo Joe & Crash cove token"},
{"name": "Beat Komodo Joe & Sewer speedway ctr token"},
{"name": "Beat Pinstripe & N.gin labs platinum relic"},
{"name": "Skull rock token & Coco park Platinum relic"}],
bingoList[24] = 
[{"name": "2 yellow & 2 purple tokens"},
{"name": "2 green & 2 blue tokens"},
{"name": "2 purple & 2 red tokens"},
{"name": "2 red & 2 yellow tokens"},
{"name": "2 blue & 1 yellow tokens"},
{"name": "2 blue & 1 green tokens"},
{"name": "2 purple & 1 blue tokens"},
{"name": "2 green & 1 yellow tokens"},
{"name": "2 red & 1 green tokens"},
{"name": "2 red & 1 yellow tokens"},
{"name": "2 blue tokens & 3 gold relics"},
{"name": "3 green tokens & 1 Platinum relic"},
{"name": "2 purple tokens & 2 gold relics"},
{"name": "2 yellow tokens & 1 platinum relic"},
{"name": "3 red tokens & 1 platinum relic"}],
bingoList[25] = 
[{"name": "Beat 2 bosses"},
{"name": "Beat 3 bosses"},
{"name": "Beat 3 bosses"},
{"name": "Beat 1 boss & 2 red tokens"},
{"name": "Beat 1 boss & 2 blue tokens"},
{"name": "Beat 1 boss & 1 purple token"},
{"name": "Beat 1 boss & 2 yelow tokens"},
{"name": "Beat Oxide"}]