bingoGenerator = require("./generators/generator_bases/simple_generator.js");
var bingoList =
[{"name": "Desert Fox Gem"},
 {"name": "Pogo-a-Gogo Crystal"},
 {"name": "Melt Panic Gold Relic"},
 {"name": "Toxic Dash Crystal"},
 {"name": "Space Bash Trophy"},
 {"name": "Beach Ball Platinum Relic"},
 {"name": "Jungle Bash Gold Relic"},
 {"name": "Keg Kaboom Gem"},
 {"name": "Dragon Drop Crystal"},
 {"name": "N. Ballism Gold Relic"},
 {"name": "Metal Fox Gold Relic"},
 {"name": "El Pogo Loco Gem"},
 {"name": "Pogo-a-Gogo Gold Relic"},
 {"name": "Papu Pummel"},
 {"name": "Toxic Dash Gem"},
 {"name": "Swamp Fox Gem"},
 {"name": "Dante's Dash Platinum Relic"},
 {"name": "Melt Panic Crystal"},
 {"name": "Keg Kaboom Gold Relic"},
 {"name": "Pogo Padlock Crystal"},
 {"name": "Toxic Dash Gold Relic"},
 {"name": "Jungle Fox Platinum Relic"},
 {"name": "Keg Kaboom Crystal"},
 {"name": "Beach Ball Gem"},
 {"name": "Polar Panic Gold Relic"},
 {"name": "Splash Dash Platinum Relic"},
 {"name": "Space Bash Crystal"},
 {"name": "N. Ballism Platinum Relic"},
 {"name": "Manic Panic Trophy"},
 {"name": "Mallet Mash Trophy"},
 {"name": "Desert Fox Platinum Relic"},
 {"name": "N. Ballism Crystal"},
 {"name": "Tilt Panic Trophy"},
 {"name": "Snow Bash Gold Relic"},
 {"name": "Pogo Painter Trophy"},
 {"name": "Mallet Mash Gold Relic"},
 {"name": "Space Bash Gem"},
 {"name": "Crashball Gold Relic"},
 {"name": "Splash Dash Crystal"},
 {"name": "Tilt Panic Gold Relic"},
 {"name": "Metal Fox Platinum Relic"},
 {"name": "Tilt Panic Crystal"},
 {"name": "Sky Balls Gem"},
 {"name": "Dragon Drop Platinum Relic"},
 {"name": "Mallet Mash Gem"},
 {"name": "El Pogo Loco Gold Relic"},
 {"name": "Keg Kaboom Trophy"},
 {"name": "Oxide Ride"},
 {"name": "Tilt Panic Platinum Relic"},
 {"name": "Toxic Dash Platinum Relic"},
 {"name": "Snow Bash Trophy"},
 {"name": "Desert Fox Gold Relic"},
 {"name": "Ring Ding Crystal"},
 {"name": "Sky Balls Gold Relic"},
 {"name": "Dante's Dash Crystal"},
 {"name": "Polar Panic Trophy"},
 {"name": "Space Bash Gold Relic"},
 {"name": "Dot Dash Trophy"},
 {"name": "Pogo Padlock Platinum Relic"},
 {"name": "Dot Dash Platinum Relic"},
 {"name": "Pogo Padlock Trophy"},
 {"name": "Swamp Fox Gold Relic"},
 {"name": "Sky Balls Crystal"},
 {"name": "Manic Panic Gem"},
 {"name": "Drain Bash Gold Relic"},
 {"name": "Crashball Platinum Relic"},
 {"name": "Pogo Painter Crystal"},
 {"name": "Melt Panic Trophy"},
 {"name": "Jungle Bash Gem"},
 {"name": "Dante's Dash Gem"},
 {"name": "Jungle Fox Gold Relic"},
 {"name": "Dante's Dash Trophy"},
 {"name": "Polar Panic Gem"},
 {"name": "Sky Balls Trophy"},
 {"name": "Drain Bash Crystal"},
 {"name": "Jungle Fox Trophy"},
 {"name": "Swamp Fox Trophy"},
 {"name": "Crashball Trophy"},
 {"name": "Pogo Painter Gem"},
 {"name": "Manic Panic Crystal"},
 {"name": "Keg Kaboom Platinum Relic"},
 {"name": "Pogo Painter Gold Relic"},
 {"name": "Snow Bash Platinum Relic"},
 {"name": "Space Bash Platinum Relic"},
 {"name": "N. Ballism Gem"},
 {"name": "Ring Ding Gold Relic"},
 {"name": "Manic Panic Platinum Relic"},
 {"name": "Dante's Dash Gold Relic"},
 {"name": "Polar Panic Crystal"},
 {"name": "Dot Dash Gold Relic"},
 {"name": "Desert Fox Crystal"},
 {"name": "El Pogo Loco Trophy"},
 {"name": "Bearminator"},
 {"name": "Big Bad Fox"},
 {"name": "Drain Bash Platinum Relic"},
 {"name": "Toxic Dash Trophy"},
 {"name": "Ring Ding Gem"},
 {"name": "Snow Bash Gem"},
 {"name": "Beach Ball Trophy"},
 {"name": "Metal Fox Gem"},
 {"name": "El Pogo Loco Crystal"},
 {"name": "Pogo-a-Gogo Gem"},
 {"name": "Drain Bash Trophy"},
 {"name": "Dot Dash Crystal"},
 {"name": "Metal Fox Crystal"},
 {"name": "Swamp Fox Crystal"},
 {"name": "Crashball Gem"},
 {"name": "Sky Balls Platinum Relic"},
 {"name": "Mallet Mash Crystal"},
 {"name": "Jungle Bash Platinum Relic"},
 {"name": "Splash Dash Gold Relic"},
 {"name": "Crashball Crystal"},
 {"name": "Jungle Bash Crystal"},
 {"name": "Swamp Fox Platinum Relic"},
 {"name": "Metal Fox Trophy"},
 {"name": "Splash Dash Trophy"},
 {"name": "Jungle Fox Crystal"},
 {"name": "Pogo Padlock Gem"},
 {"name": "Desert Fox Trophy"},
 {"name": "El Pogo Loco Platinum Relic"},
 {"name": "Snow Bash Crystal"},
 {"name": "Pogo-a-Gogo Trophy"},
 {"name": "Dragon Drop Gem"},
 {"name": "Jungle Fox Gem"},
 {"name": "Beach Ball Gold Relic"},
 {"name": "Dragon Drop Trophy"},
 {"name": "Manic Panic Gold Relic"},
 {"name": "Pogo-a-Gogo Platinum Relic"},
 {"name": "Tilt Panic Gem"},
 {"name": "Drain Bash Gem"},
 {"name": "Ring Ding Trophy"},
 {"name": "Beach Ball Crystal"},
 {"name": "Mallet Mash Platinum Relic"},
 {"name": "Polar Panic Platinum Relic"},
 {"name": "Dot Dash Gem"},
 {"name": "Dragon Drop Gold Relic"},
 {"name": "Pogo Painter Platinum Relic"},
 {"name": "Pogo Padlock Gold Relic"},
 {"name": "Melt Panic Platinum Relic"},
 {"name": "Jungle Bash Trophy"},
 {"name": "Ring Ding Platinum Relic"},
 {"name": "Splash Dash Gem"},
 {"name": "N. Ballism Trophy"},
 {"name": "Melt Panic Gem"}]