bingoGenerator = require("./generators/generator_bases/simple_generator.js");
var bingoList =[{"name": "1 gem from 4 warp rooms"}, {"name": "3 coloured gems"}, {"name": "Red gem route gem in Bone Yard"}, {"name": "Box gem in Tomb Time"},
{"name": "Sphinxinator blue gem route gem"}, {"name": "Get 10 Gold/Platinum relics & the yellow gem"},
{"name": "Complete bonus rounds in Bone Yard, High Time & Tomb Wader"},
{"name": "ELP Toad Village, Gee Wiz & Double Header"}, {"name": "ELP Under Pressure & Deep Trouble"}, {"name": "Complete a bonus round in 4 warp rooms"},
{"name": "Defeat 3 bosses"}, {"name": "Eggipus Rex gem"}, {"name": "Green gem & 1 Gone Tomorrow gem"}, {"name": "Gold/platinum Relic in Area 51"},
{"name": "Blue gem & Platinum relic in Orient Express"}, {"name": "ELP Future Frenzy & Gone Tomorrow"}, {"name": "Gem path route gem in Bug Lite"},
{"name": "ELP Bone Yard & Dino Might"}, {"name": "Tomb Time purple gem route gem"}, {"name": "Gold/Platinum relics on Orient Express & Midnight Run"},
{"name": "ELP 5 Coco levels"}, {"name": "All gems from Toad Village & Flaming Passion"}, {"name": "All gems from Gone Tomorrow"}, {"name": "All gems from Deep Trouble"},
{"name": "ELP Makin’ Waves & Tell No Tales"}, {"name": "10 gems"}, {"name": "3 coloured gem path gems"}, {"name": "Tell No Tales box gem"},
{"name": "Orient Express & Bug Lite box gems"}, {"name": "6 gold/platinum relics"},{"name": "5 platinum relics"},
{"name": "Box gems from Makin’ Waves & High Time"}, {"name": "ELP Ski Crazed & Hot Coco"}, {"name": "2 gems from ‘Time’ levels"},
{"name": "ELP Bye Bye Blimps & Mad Bombers"}, {"name": "Ski Crazed gem"}, {"name": "20 Lives"}, {"name": "Box gems in Hog Ride & Dino Might"},
{"name": "Gold/Platinum Relics in Under Pressure & Orange Asphalt"}, {"name": "Gold/Platinum relics in High Time & Future Frenzy"},
{"name": "ELP Tomb Time, Sphinxinator, Tomb Wader & Bug Lite"}, {"name": "ELP 3 motorbike levels"}, {"name": "1 Area 51 gem"}, {"name": "1 Future Frenzy gem"},
{"name": "Complete all Hang ‘em High, Dino Might & Flaming Passion bonus rounds"}, {"name": "1 Platinum relic from 4 warp rooms"},
{"name": "Road Crash & Sphinxinator box gems"}, {"name": "Bye Bye Blimps & Deep Trouble box gems"}, {"name": "Get 2 platinum relics whilst playing as Coco"},
{"name": "7 gems"}, {"name": "14 gems"}, {"name": "ELP one level from each WR"}, {"name": "30 lives"}, {"name": "Double Header gem & Defeat N.Tropy"},
{"name": "Gold/Platinum relics in Tomb Time & Mad Bombers"},  {"name": "Midnight Run gem & defeat N.Gin"},
{"name": "Complete Toad Village, Gone Tomorrow & Bug Lite bonus rounds"}, {"name": "Hit a grey ! box in 5+ levels"},
{"name": "Hit a green ! box in 5+ levels"}, {"name": "Dino Might yellow gem route gem"}, {"name": "Under Pressure box gem & gold/platinum relic in Hot Coco"},
{"name": "Gee Wiz & Gone Tomorrow box gems"}, {"name": "5 gems from single gem levels"}, {"name": "ELP with 0 boxes broken in 3 levels"}, {"name": "4 WR1 gems"},
{"name": "4 WR2 gems"}, {"name": "4 WR3 gems"}, {"name": "3 WR4 gems"}, {"name": "3 WR5 gems"}, {"name": "Gold/Platinum relics in Toad Village & Ski Crazed"},
{"name": "Ride 5 different instances of colour gem platforms"}, {"name": "ELP all WR1 levels"}, {"name": "Bone Yard box gem & platinum relic in Midnight Run"},
{"name": "Gold/Platinum relics in Bone Yard, Hang ‘em high & Bug Lite"}, {"name": "Gold/platinum relics in Makin’ Waves, Hog Ride & Tomb Wader"},
{"name": "Red gem & Platinum relic in Gee wiz"}, {"name": "Blue gem & gold/platinum relic in Tell No Tales"}, {"name": "Purple gem & 1 WR5 platinum relic"},
{"name": "Hang Em’ High box gem & complete Sphinxinator bonus round"}, {"name": "Gold/platinum relic in Road Crash & defeat Tiny"},
{"name": "Gold/platinum relic on Bye Bye Blimps & defeat Dingodile"}, {"name": "Complete Future Frenzy bonus round & box gem in Mad Bombers"},
{"name": "Orange Asphalt & Hot Coco box gems"}, {"name": "Gold/platinum relics in Flaming Passion & Eggipus Rex"}, {"name": "Box gem in Area 51"},
{"name": "Break an Aku Aku box in 5+ different levels"}, {"name": "Both gems and Gold/platinum relic in Rings of Power"},
{"name": "ELP Hang ‘Em High, High Time & Flaming Passion"},{"name": "Get squashed,get destroyed by laser, get eaten, get electrocuted"}, {"name": "2 ‘High’ level gems"}, {"name": "1 gold/platinum relic from 6 warp rooms"}, {"name": "ELP 8 Crash levels"},
{"name": "Gold/platinum relic and gem in Orient Express "},{"name": "Gold/platinum relic and gem in hog ride and get the gold/platinum relic in orange asphalt"},
{"name": "Gold/platinum relic in Mad Bombers and the gem  Makin' Waves "}, {"name": "Gold/platinum relic and gem in Bye Bye Blimps"}, {"name": "Both Sphynxinator gems and Hog Ride gem"},
{"name": "Both Mad Bombers and Under Pressure gems"}, {"name": "Gee Wiz box gem and Road Crash Platinum/Gold relic"},
{"name": "Gold/platinum relic and gem in Orange Asphalt and Tell no Tales box gem"}, {"name": "Both Relics in Double Header and Ski Crazed"}, {"name": "ELP Road Crash and Area 51"},
{"name": "Gold/platinum relic and gem in Under Pressure and Gee Wiz gem"}, {"name": "Toad Village bonus round and gold relic and gem in Orange Asphalt"}, {"name":"ELP Orient Express and gold/platinum relic and 1 gem in Future Frenzy "},
{"name": "Gold/platinum relic and gem in Double Header and Platinum/Gold relic in Bye Bye Blimps"}, {"name": "ELP Hog Ride and Eggipus Rex"}, {"name": "Ride all the animal instances"},{"name": "All 'hidden level' gems"},{"name":"4+ gems in Egyptian levels"},{"name": "5+ gems in Arabic levels"},{"name": "3+ Gems in Prehistoric levels"},{"name": "3+ gems in Future levels"}];
