bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    {"name": "Adventure - Beat Ripper Roo"},
    {"name": "Adventure - Lose once to Papu Papu"},
    {"name": "Adventure - Get N. Gin Labs Trophy"},
    {"name": "Adventure - 100% 1 Hub"},
    {"name": "Adventure - Get 4 Tokens"},
    {"name": "Adventure - Collect 6 C's in CTR Tokens"},
    {"name": "Adventure - Get 3 Relics"},
    {"name": "Adventure - Get 2 Platinum Relics"},
    {"name": "Adventure - Get 2 Purple Tokens"},
    {"name": "Adventure - Get 1 Gem"},
    {"name": "Adventure - Collect 100 Total Wumpa in Adventure Mode"},
    {"name": "Adventure - Go through the secret door on all 3 laps of Tiger Temple"},
    {"name": "Adventure - Beat a boss without using a mini-turbo"},
    {"name": "Adventure - Win a Gold Relic without using a mini-turbo"},
    {"name": "Adventure - Drive through all 5 Hub areas"},
    {"name": "Adventure - Get OOB in Glacier Park"},
    {"name": "Adventure - Starting from the Save Screen, do 10 laps around The Lost Ruins"},
    {"name": "Adventure - Beat Ripper Roo with Polar/Pura"},
    {"name": "TT - Beat the Mystery Caves Oxide Ghost"},
    {"name": "TT - Beat the Sewer Speedway Oxide Ghost"},
    {"name": "TT - Beat the Papu's Pyramids Oxide Ghost"},
    {"name": "TT - Beat the Polar Pass Oxide Ghost"},
    {"name": "TT - Beat the Cortex Castle Oxide Ghost with Dingo/Tiny"},
    {"name": "TT - Beat the Hot Air Skyway Oxide Ghost"},
    {"name": "TT - Beat the Tiny Arena N. Tropy Ghost"},
    {"name": "TT - Beat 3 Oxide Ghosts with Polar/Pura"},
    {"name": "TT - Beat 1 N. Tropy Ghosts with Ripper Roo"},
    {"name": "TT - Beat 6 N. Tropy Ghosts"},
    {"name": "TT - Unlock 10 N. Tropy Ghosts"},
    {"name": "TT - Beat the Oxide Station Oxide Ghost without using any SC"},
    {"name": "Arcade - Finish Nitro Cup"},
    {"name": "Arcade - Finish Crash Cup"},
    {"name": "Arcade - Finish Crystal Cup"},
    {"name": "Arcade - Beat all 4 Cups on Easy"},
    {"name": "Arcade - Complete a Cup on Medium Difficulty"},
    {"name": "Arcade - Complete 2 7-Lap Races"},
    {"name": "Arcade - Do 20 combined laps in Arcade Single Mode"},
    {"name": "Arcade - Win a 3-Lap race from a lap behind in Arcade Single Mode"},
    {"name": "Arcade - Win in Dragon Mines with the Super Hard Mode cheat (Cheat Code | Must be deactivated before continuing)"},
    {"name": "Arcade - Activate the Icy Tracks cheat and beat an Arcade Cup (Cheat Code | Must be deactivated before continuing)"},
    {"name": "Misc. - Complete an Any% (Battle Mode Glitch) run"},
    {"name": "Misc. - Hit 3 unique CPU's with the '3 Missile' item consecutively"},
    {"name": "Misc. - Hit 3 unique CPU's with the 'Aku/Uka Mask' item before it runs out"},
    {"name": "Misc. - Watch the entire Scrapbook without skipping (Cheat Code)"},
    {"name": "Misc. - Reach the exit of Magma Cone in the Spyro 2 Demo (Cheat Code)"},
    {"name": "Misc. - Collect 200 Gems in Collosus in the Spyro 2 Demo (Cheat Code)"}
];
