bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "10 Berry Gems",
    "10 Death Gems",
    "10 Hidden Gems",
    "10 Wumpa Gems",
    "12 Box Gems",
    "12 Coco Skins",
    "12 Crash Skins",
    "12 Death Gems",
    "12 Flashback Tapes",
    "12 N-Sanely Perfect",
    "12 Skins",
    "120 Clear Gems",
    "15 Box Gems",
    "15 Death Gems",
    "15 Hidden Gems",
    "18 Skins",
    "2 Cortex Levels",
    "2 Dingo Levels",
    "2 Twana Levels",
    "20 Berry Gems",
    "20 Clear Gems",
    "20 N-verted Gems",
    "20 Skins",
    "20 Wumpa Gems",
    "3 Box Gems",
    "3 Coco Skins",
    "3 Cortex Levels",
    "3 Crash Skins",
    "3 Death Gems",
    "3 Dingo Levels",
    "3 Flashback Tapes",
    "3 Gold Relics",
    "3 Gold Tapes",
    "3 Hidden Gems",
    "3 N-Sanely Perfect",
    "3 Platinum Relics",
    "3 Platinum Tapes",
    "3 Purple Relics",
    "3 Sapphire Relics",
    "3 Sapphire Tapes",
    "3 Twana Levels",
    "30 Berry Gems",
    "30 Wumpa Gems",
    "40 Berry Gems",
    "40 Clear Gems",
    "40 N-verted Gems",
    "40 Wumpa Gems",
    "5 Death Gems",
    "5 Hidden Gems",
    "50 Berry Gems",
    "50 Wumpa Gems",
    "6 Box Gems",
    "6 Coco Skins",
    "6 Crash Skins",
    "6 Flashback Tapes",
    "6 Gold Relics",
    "6 Gold Tapes",
    "6 N-sanely Perfect",
    "6 Platinum Relics",
    "6 Platinum Tapes",
    "6 Purple Relics",
    "6 Sapphire Relics",
    "6 Sapphire Tapes",
    "6 Skins",
    "60 Clear Gems",
    "60 N-verted Gems",
    "80 Clear Gems",
    "9 Box Gems",
    "9 Coco Skins",
    "9 Crash Skins",
    "9 Flashback Tapes",
    "9 Gold Relics",
    "9 Gold Tapes",
    "9 N-Sanely Perfect",
    "9 Platinum Relics",
    "9 Platinum Tapes",
    "9 Purple Relics",
    "9 Sapphire Relics",
    "9 Sapphire Tapes",
    "Avoid All Boxes in a Level",
    "Avoid All Enemies in a Level",
    "Avoid All Gems in a Level",
    "Avoid All Wumpa in a Level",
    "Avoid Damage in a Level",
    "Beat N-gin/No N-Gin Skip",
    "Blue Gem",
    "Blue Gem Route",
    "Blue Gem/No Blue Gem Skip",
    "Cat's Meow Skin",
    "Classic Coco Skin",
    "Complete 12 Bonus Levels",
    "Complete 15 Bonus Levels",
    "Complete 3 Bonus Levels",
    "Complete 6 Bonus Levels",
    "Complete 9 Bonus Levels",
    "Complete a Bonus Level Without breaking any boxes",
    "Crash Chicken Skin",
    "Do Hit The Road Skip",
    "Do Louise Skip",
    "Fake Coco Skin",
    "Fake Crash Skin",
    "Get 20 Lives",
    "Get 40 Lives",
    "Get 60 Lives",
    "Get 80 Lives",
    "Get 99 Lives",
    "Get Aku´s invincibility",
    "Green Gem",
    "Green Gem Route",
    "No 3+Death Gem in a Level",
    "No Box Gem in a Level",
    "No Hidden Gem in a Level",
    "Red Gem",
    "Red Gem Route",
    "Yellow Gem",
    "Yellow Gem Route"
];
