bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "All Non Airplane Bosses in Isle 2 with Peashooter only",
    "At least 3 Parries on Isle 1 Bosses",
    "Beat 3 Bosses with Chaser (regular)",
    "Beat Cala Maria without getting petrified",
    "Beat Hilda without killing any minions",
    "Beat The Bee without Pressing Down",
    "Beat The Devil without taking a hit",
    "Beat Train without parrying the wheels on the cart",
    "Beat a Boss with Revert Directional Controls",
    "Beat a Boss with Uncharged Charge Shot",
    "Beat a boss with Mini Airplane",
    "Beat a plane boss with just whetstone",
    "Beat all 5 Bon Bon minions",
    "Beat an Isle 3 Boss with Chaser (Expert)",
    "Beat any Boss on Expert using whetstone only",
    "Buy all the charms",
    "Clear All Run n' Guns",
    "Clear Mausoleums",
    "Collect 30 Coins",
    "Collect at least 1 S on each of 3 Isles",
    "Defeat 3 Bosses on Simple",
    "Defeat King Dice without any hearts",
    "Defeat all King Dice's minions in a single gauntlet",
    "Dodge Werner Werman charge attack with no springs",
    "Don't pick the Bomb Upgrade",
    "Don't take a hit for 3 fights in a row",
    "Don't use Airplane Nukes",
    "Don't use Exs in Isle 2",
    "Don't use either Lobber or Roundabout",
    "Get Wally's knockout, when his heart is out",
    "Get a rank of at least A+ on all Isle 1 bosses",
    "Get all 3 Slot combinations in Ribby n Croaks",
    "Grab the juggler's Secret Coin",
    "Grim with Spread in Regular",
    "Have less than 10 Deaths before Isle 3",
    "Hit the Start Over at King Dice",
    "Kill a minion in Cala Maria",
    "Knockout with Super 3",
    "Listen to the Quartet's song",
    "Never use shortcuts",
    "Obtain at least 3 P ranks",
    "Octopus Skip",
    "Pop 5 Balloons in Funfair Fever",
    "Reach Isle 3 without any upgrades",
    "Ride the beam in Briney fight",
    "Run N Gun Pacifist, no damage",
    "S rank any plane level with Machine gun Only",
    "Swing roundabout Ex 5 times",
    "Unlock the 2-Strip video filter",
    "Use at least one of each weapon's Ex"
];
