bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "$$$$",
    "101 north",
    "5 assaults",
    "5 psyco",
    "Brendan?",
    "COOOOOOOOOB!",
    "Cheese!",
    "Craftsman",
    "Cyberpunk glitched (FREE)",
    "Dakota",
    "Dexter",
    "Dino",
    "EXP",
    "El Capitan",
    "Fist of the North Star",
    "Get on your glad rags",
    "Grub?",
    "Gun for hire",
    "Heres johnny",
    "Hows biz",
    "Hugs for everyone",
    "Joytoy",
    "Maxtek",
    "Org Crime",
    "Padre",
    "Pet the cat",
    "Pizza?",
    "Psycho",
    "Pub?",
    "Refrigerator man",
    "Regina",
    "Rep Crime",
    "Ride the roller coaster",
    "Roach!",
    "S&R",
    "S.O.S",
    "Stone cold killer",
    "Theif",
    "Upgrades",
    "Wakako",
    "Way of the samurai",
    "assault",
    "ball game",
    "boarder wall",
    "judy",
    "no fast travel",
    "no scope",
    "no time for missions",
    "oil for nothing",
    "pimp it up",
    "puppy loving pacifist",
    "rouge",
    "saboteur",
    "somebody to loot",
    "stabby stabby",
    "the clap!",
    "the tower",
    "vroom",
    "when pandas fly",
    "you can swim?"
];
