bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Activate 2 Crit tablets",
    "Activate 3 Damage tablets",
    "Activate 4 Stamina tablets",
    "Activate 5 Faith tablets",
    "Barehanded upgrade",
    "Complete Quest 9",
    "Create 7 chickens",
    "Don't destroy Statues",
    "Don't use Needles",
    "Fair fight (Templar)",
    "Get Both Aureus' Bow and Elinor's Spear",
    "Kill 2 \"Scavengers\"",
    "Kill 2 bosses with their own weapons",
    "Kill 2 chained bosses",
    "Kill 4 Elites",
    "Kill Asriel with the help of Amaris",
    "Kill Elemiah - Crow lady",
    "Kill Jezebel",
    "Kill Martyr",
    "Kill Sariandel - Void prisoner",
    "Kill The First one",
    "Kill The Virgin",
    "Kill a Crow assassin",
    "Kill a boss without rolling",
    "Kill the Chimera while having the meow buff",
    "Kill the Guardian",
    "Obtain a second row alter buff",
    "Reach 5 copies of a consumable",
    "Reach 8 buffs",
    "Reach 8 diseases",
    "Read Curious man series (3)",
    "Read Initiation (4)",
    "Read Lost squad (2)",
    "Reuniting Ariuk and Gabrielle",
    "Save Banlamb and Clotide",
    "Unlock 26 forge items",
    "Unlock forest shortcut",
    "Visit a Princess tomb",
    "Visit the glade",
    "Visit the hearth",
    "Visit the rotten houses"
];
