bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "10 Afflicted characters in roster",
    "22 Total Kills",
    "5 Crimson curse heroes in roster",
    "7 heroes died",
    "A extra effect from Abbey or Tavern",
    "All 15 original heroes in roster",
    "All zones level 1",
    "Any Tier 1 Apprentice boss",
    "Any zone to level 3",
    "Beat a camping ambush!",
    "Burn three items",
    "CM first farmstead",
    "CM using only 3 heroes",
    "CM while only using AoE attacks",
    "CM with 1 virtuous",
    "CM with 3 heroes on deaths door",
    "CM with 3 of same hero in a party",
    "CM with 4 Lepers in party",
    "CM with a Jester 4 times",
    "CM with a Plague doctor 5 times",
    "CM with a Vestal 4 times",
    "CM with an Abomination 4 times",
    "CM with an Antiquarian 3 times",
    "CM with an Arbalist 3 times",
    "CM with three afflicted",
    "CM without bringing any provisions",
    "CM without melee attacks",
    "CM without ranged attacks",
    "Collect 4 journals",
    "Complete a medium mission",
    "Crit heal two different abilities(same battle)",
    "Crocodilian",
    "Cure 4 diseases",
    "Destroy 6 corpses",
    "Die from the crimson curse",
    "Do not use Tavern nor Abbey",
    "Enter a hidden room",
    "Heal 0 with an occultist",
    "Hold 55 crests",
    "Hold Exactly 0 Gold",
    "Hold over 55,555 gold",
    "Kill Wilbur before Swine",
    "Kill a Cultist Priest",
    "Lose a Hero to a maggot/Spider",
    "Lose someone while they're on the enemy side",
    "Lose the old road",
    "No heroes died",
    "No retreats from battle",
    "Over 20 damage from one DOT",
    "Over 30 damage from Crit attack",
    "Reach 8 active Buffs (one hero)",
    "Receive this goal while camping",
    "Resist 4 deathblows, single battle, same character",
    "Save two people from the cauldron",
    "Sell 10 trinkets",
    "Shambler/ Collector/ Shreiker",
    "Two deaths via heart attack",
    "Upgrade a single building stat 4 times",
    "Use all unique camping abilties (one hero)",
    "Use no torches",
    "Vestal and Abomination in Bar",
    "Veteran level hero"
];
