bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "10 Trinkets",
    "3 Crimson cursed character",
    "5 heroes died",
    "70,000 Gold",
    "90 Crests",
    "Abomination and a vestal walk in to a bar",
    "All Heros in roster",
    "Any Tier 2 apprenitce boss",
    "Camping ambushed!",
    "Complete a district",
    "Complete a long mission",
    "Complete a medium mission",
    "Crocodlie",
    "Die of a heart attack",
    "Find a hidden room",
    "Finish at camp",
    "First farmstead mission.",
    "Hag",
    "Heal 0 with an occultist",
    "Kill a Cultist Priest",
    "Kill a madman",
    "Level 4 building upgrade",
    "Necromancer",
    "No heroes died",
    "No retreats from battle",
    "No stress buildings used",
    "No torches",
    "One hero virtuous",
    "Resist 4 deathblows",
    "Shambler or Collector",
    "Siren",
    "Swine prince",
    "Two hero afflicted at the same time",
    "Veteran level hero"
];
