bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Buy a ladder from Gilligan",
    "Collect a +0, +1 and +2 variation of the same ring",
    "Defeat Darklurker",
    "Defeat all 11 crystal lizards in Dragon Aerie",
    "Defeat all Pursuers",
    "Defeat all three Heide Knights",
    "Defeat four roaming souls in four different areas",
    "Defeat the Corrosive Ant Queen",
    "Defeat three different NPC invaders",
    "Despawn both red crsytal lizards",
    "Discover all 9 covenants",
    "Don't defeat Last Giant",
    "Don't defeat Mirror Knight",
    "Don't defeat Ruin Sentinels",
    "Don't defeat Skeleton Lords",
    "Don't defeat Velstadt",
    "Don't kill any Dragonrider",
    "Don't obtain Silver Cat Ring",
    "Extinguis the fire in the Flame Salamander pit",
    "Free all four Milfanitos",
    "Gather five additional residents in Majula",
    "Get 7 estus flask uses",
    "Get all 3 bite rings",
    "Get all 4 quartz rings",
    "Get all gestures",
    "Get estus flask to +5",
    "Get the BKUGS",
    "Get the Dragon Tooth",
    "Get the ladder miniature",
    "Get the moonlight greatsword",
    "Get the undead lockaway key",
    "Infuse a weapon",
    "Inherit Felkins Gear",
    "Kill Vendrick",
    "Kill all Giants in all memories",
    "Kill the Ancient Dragon",
    "Light all bonfires in four areas",
    "Light bonfires in 15 areas",
    "Never enter the Rotunda room",
    "Never use a Fragrant Branch of Yore",
    "Obtain Black Knight Sword",
    "Obtain Chaos Set",
    "Obtain Chloranthy Ring +2",
    "Obtain Defender/Watcher Greatsword",
    "Obtain Dragon Soul",
    "Obtain Havel's Set",
    "Obtain Hawk Ring",
    "Obtain Immolation",
    "Obtain King's Ring",
    "Obtain Mastodon Greatsword",
    "Obtain Royal Dirk",
    "Obtain Santier's Spear",
    "Obtain Soul of Vendrick",
    "Obtain Vengarl's Set",
    "Obtain a weapon of each class",
    "Obtain all weapon buff spells (no hidden weapon)",
    "Obtain an Old Soul",
    "Obtain both Pyromancy Flames",
    "Obtain both Serpent Rings +2",
    "Obtain the Avelyn",
    "Obtain the Dark Set",
    "Obtain the Engraved Gauntlets",
    "Obtain the Pickaxe",
    "Receive \"Warmup\" from Tark",
    "Receive at least four different items from trading with Dyna and Tillo",
    "Reinforce your Pyromancy Flame five times",
    "Reveal five illusory walls",
    "Talk to Benhart in the Memory of Orro",
    "Talk to Lucatiel in Aldia's Keep",
    "Talk to the rat king at both locations",
    "Transpose three boss weapons",
    "Use 5 Pharros Lockstones"
];
