bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "3 Crimson Curse characters in roster",
    "6 heroes died",
    "A negitive effect from either the abby or Tavern",
    "All 15 original heroes",
    "Any Tier 2 apprenitce boss",
    "Beat a camping ambush!",
    "CM first farmstead",
    "CM with 1 virtuous",
    "CM with 3 Heroes on deaths door",
    "CM with 4 of same hero in a party",
    "CM with a Abomination 4 times",
    "CM with a Arbalist 4 times",
    "CM with a Jester 4 times",
    "CM with a Plague doctor 5 times",
    "CM with a Vestal 5 times",
    "CM with three afflicted",
    "CM without melee attacks",
    "CM without ranged attacks",
    "Collect 4 journals",
    "Complete a long mission",
    "Complete a medium mission",
    "Crocodilian",
    "Cure 5 diseases",
    "Die of a heart attack",
    "Do not use Tavern nor Abby",
    "Enter a hidden room",
    "Hag",
    "Heal 0 with an occultist",
    "Hold 60 crests",
    "Hold 67,500 gold",
    "Kill a Cultist Priest",
    "Necromancer",
    "No heroes died",
    "No retreats from battle",
    "Receive this goal while camping",
    "Resist 4 deathblows in single battle by same character",
    "Sell 10 trinkets",
    "Shambler or Collector",
    "Siren",
    "Swine prince",
    "Upgrade a single building stat 4 times",
    "Use no torches",
    "Vestal and Abomination in Bar",
    "Veteran level hero"
];
