bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "[{“name”: “Man in a Bind”},",
    "{“name”: “A Mother's Lament”},",
    "{“name”: “A Sick Man”},",
    "{“name”: “A Strange Group”},",
    "{“name”: “Above the Law”},",
    "{“name”: “Activate 5 Unique Mixed Drinks at once”},",
    "{“name”: “Antique Lover”},",
    "{“name”: “Barricade Pair”},",
    "{“name”: “Beat Any Boss Unarmed”},",
    "{“name”: “Beat Isabela only using Melee Attacks”},",
    "{“name”: “Break All the Sandbags”},",
    "{“name”: “Break the Plates in the Food Court”},",
    "{“name”: “Bring 4 Female Survivors to Jo”},",
    "{“name”: “Bring 5 Survivors into Seans Fight”},",
    "{“name”: “Bring Jeff to Cliff”},",
    "{“name”: “Bring Ronald to the Food Court and Feed him 3 items”},",
    "{“name”: “Carry Isabela into any Optional Psychopath Fight”},",
    "{“name”: “Complete Kent 1's Photo Tutorial Without Killing Kent 3”},",
    "{“name”: “Cover 10 Zombies in Pies”},",
    "{“name”: “Do Bomb Collector Without a Vehicle”},",
    "{“name”: “Dressed For Action”},",
    "{“name”: “Eat 5 unique Food Items Before Killing Steven”},",
    "{“name”: “Equip 4 Survivors with Shotguns at Once”},",
    "{“name”: “Escort 2 Entrance Plaza Survivors out of the area WITHOUT Harming the Snipers”},",
    "{“name”: “Frank the Pimp (8 Female Survivors)”},",
    "{“name”: “Fry 10 Zombie Faces with a Pan”},",
    "{“name”: “Fry a pan on every Grill”},",
    "{“name”: “Get 3 Sexy Zombies in one photo”},",
    "{“name”: “Get Kidnapped by the Cult and Escape”},",
    "{“name”: “Get the Maintenance Tunnel Key”},",
    "{“name”: “Give Ross a Gun”},",
    "{“name”: “Give both Shinji and Yuu a Katana”},",
    "{“name”: “Grill 5 Steaks”},",
    "{“name”: “Grind 30 Zombies with a Lawn Mower”},",
    "{“name”: “Gun Shop Standoff”},",
    "{“name”: “Hanging By a Thread”},",
    "{“name”: “Have 10 Survivors in the Party at Once”},",
    "{“name”: “Have 10 Survivors in your Party at once”},",
    "{“name”: “Have 3 Injured/Old survivors in the party at the same time”},",
    "{“name”: “Have Adam Blow up 3 Balloons Before Killing Him”},",
    "{“name”: “Have Carlito 2 Hit Himself with a Grenade Before Killing Him”},",
    "{“name”: “Have Susan and Floyd in your Survivor Party”},",
    "{“name”: “Hold 5 Hunks of Meat at once”},",
    "{“name”: “Hold Adam's Chainsaw and all 3 Buff Magazines for it at once”},",
    "{“name”: “Japanese Tourists”},",
    "{“name”: “Kill 10 Zombies at Once with a Propane Tank Explosion”},",
    "{“name”: “Kill 10 Zombies with CDs”},",
    "{“name”: “Kill 1000 Zombies”},",
    "{“name”: “Kill 20 Zombies only using Soccer Balls”},",
    "{“name”: “Kill 20 Zombies with 2 Handed Weapons”},",
    "{“name”: “Kill 3 Survivors Only using Hedge Trimmers”},",
    "{“name”: “Kill 5 Survivors”},",
    "{“name”: “Kill 50 Zombies with the Regular Chainsaw”},",
    "{“name”: “Kill Any 5 Psychopaths”},",
    "{“name”: “Kill Any Boss with Spitfire”},",
    "{“name”: “Kill Any Boss with a Mannequin Torso”},",
    "{“name”: “Kill Any Psychopath using only King Salmon”},",
    "{“name”: “Kill Any Psychopath using only The Rat Stick”},",
    "{“name”: “Kill Carlito 1 only using Brad/Jessie's Pistols”},",
    "{“name”: “Kill Carlito 2 Only Using Sniper Rifles”},",
    "{“name”: “Kill Carlito 3”},",
    "{“name”: “Kill Cletus Only Using Guns From his Store”},",
    "{“name”: “Kill Cliff Both Without Leaving the Store and Only using Store Items”},",
    "{“name”: “Kill Convicts Melee Only”},",
    "{“name”: “Kill Jo After Letting her Kill All Her Survivors”},",
    "{“name”: “Kill Larry(DREX Required)”}]",
    "{“name”: “Kill Natalie in Front of Jeff”},",
    "{“name”: “Kill Paul While Adam is Active”},",
    "{“name”: “Knock over 10 Zombies with one Bowling Ball throw”},",
    "{“name”: “Listen to 5 Full Otis Calls”},",
    "{“name”: “Long Haired Punk”},",
    "{“name”: “Lovers”},",
    "{“name”: “Make 10 Zombies Slip”},",
    "{“name”: “Make Adam Trip Once Before Killing Him”},",
    "{“name”: “Mark of the Sniper”},",
    "{“name”: “Open the Wonderland Shortcut”},",
    "{“name”: “Out of Control”},",
    "{“name”: “Photograph 20 PP Stickers”},",
    "{“name”: “Photograph 20 Survivors”},",
    "{“name”: “Photograph 3 Boss PP Moments”},",
    "{“name”: “Photograph 3 Survivor PP Moments”},",
    "{“name”: “Photograph Both Kents Together”},",
    "{“name”: “Prisoners”},",
    "{“name”: “Put 4 unique Novelty Masks on Zombies and grab a photo”},",
    "{“name”: “Reach Level 20”},",
    "{“name”: “Recruit At Least 1 Gun Shop Survivor”},",
    "{“name”: “Recruit At least 2 of Jo's Survivors”},",
    "{“name”: “Restaurant Man”},",
    "{“name”: “Ride the Space Rider”},",
    "{“name”: “Run on all the Treadmills”},",
    "{“name”: “Save Paul”},",
    "{“name”: “Shadow of the North Plaza”},",
    "{“name”: “Spin All the Racks in Entrance Plaza”},",
    "{“name”: “Spray a Water Gun on Kent's Corpse”},",
    "{“name”: “Take 1 Photo featuring 3 Unique Genres”},",
    "{“name”: “Take Pictures of both Hanging Survivors”},",
    "{“name”: “The Coward”},",
    "{“name”: “The Cult”},",
    "{“name”: “The Drunkard”},",
    "{“name”: “The Gun Shop”},",
    "{“name”: “The Hatchet Man”},",
    "{“name”: “The Woman Who Didn't Make It”},",
    "{“name”: “Turn the Servbot Head Statue”},",
    "{“name”: “Twin Sisters”},",
    "{“name”: “Use Any Boss Weapon to Kill Another Boss”},",
    "{“name”: “Wear Each Novelty Mask Once”},"
];
