bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "BUY THE BELL",
    "Buy Out a Whole Shop (ANY)",
    "Collect 100 Concept Arts",
    "Collect 30 of Any Pin (NO SPECIAL)",
    "Collect 50 Concept Arts",
    "Collect 60 Power Sparks",
    "Collect The Purple E-Ticket",
    "Complete all Detective Mickey Quests",
    "Complete all Gilda Races",
    "Complete all of Jim’s Puzzles",
    "Complete an IL With Gamma at 0",
    "Do an Area Jumpless (No Hub Worlds)",
    "Drop an Anvil on Abner",
    "Free 10 Gremlins",
    "Free 5 Gremlins",
    "Get 1 Costume (NO DLC)",
    "Get 10 Pins (NO SPECIAL)",
    "Get 2 Costumes (NO DLC)",
    "Get 36 Film Reels",
    "Get 5 Pins (NO SPECIAL)",
    "Get 5 Special Pins",
    "Get 5K E-Tickets",
    "Get 72 Film Reels",
    "Get Demo Green E-Ticket",
    "Get Gremlin Guardian Pin",
    "Get Out of Bounds",
    "Get Softlocked",
    "Get a Golden E-Ticket",
    "Gremlin Jump in Courtyard",
    "Hit Roarless on Both Towers",
    "Ignite an Explosive",
    "Kill Mickey in Every Way (Thinner, Void, Enemy, Crushed, Electricity, Fall Damage)",
    "Kill One of Each Blotling",
    "Kill a Gremlin",
    "Make Something Fall (Boulder, Pillar, Rocks, ETC.)",
    "Repair Daisy",
    "Repair Donald",
    "Repair Goofy",
    "Sell Small Pete’s Ship Log",
    "Take a Selfie with Every NPC in Bog Easy",
    "Take a Selfie with Every NPC in Mean Street",
    "Take a Selfie with Every NPC in Ostown",
    "Take a Selfie with Every NPC in Ventureland",
    "Unlock Walt’s Apartment",
    "Upset an NPC"
];
