bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "10 Mirror Shards",
    "4 Mirror Shards",
    "8 Mirror Shards",
    "Bell Tower Mirror Shard",
    "Bring the Blue Fish to the Fish Bowl",
    "Cabinet Mirror Shard",
    "Cave Mirror Shard",
    "Choose to stay with the Ghost",
    "Clock Tower Mirror Shard",
    "Collect 4 Star Containers",
    "Collect 8 Star Containers",
    "Collect Clock Tower Star Container (use tricks on clock until it reaches 7:00)",
    "Collect Train Star Container",
    "Donald Duck Plush",
    "Fix the Clock Tower",
    "Give the flower to the Painting",
    "Grand Hall Urn",
    "Group Painting of Mickey and Friends",
    "Heart Picture",
    "Holey Stairway Star Container",
    "Kitchen Mirror Shard",
    "Library Key",
    "Magnifying Glass",
    "Minnie’s Bow",
    "Model Mirror Mansion",
    "Model Windmill",
    "Nunchuk Shoe Chase",
    "Obtain the Gear",
    "Painting Hall Mirror Shard (The Painting with eyes that move and such)",
    "Perfect Barrel Minigame",
    "Perform 12 unique tricks",
    "Perform 4 unique tricks",
    "Perform 8 unique tricks",
    "Plant Pot",
    "Plug in the T.V.",
    "Pluto’s Collar",
    "Pull the Chair from under Mickey",
    "Put 1 Coin in the Piggy Bank",
    "Rubber Duck",
    "Shrinking Toy Witch",
    "Sword (complete Sword Chase without being hit)",
    "Tea Time",
    "Toy Room Mirror Shard",
    "Wardrobe Magic Trick"
];
