bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Buy 10 Costumes",
    "Buy 5 Costumes",
    "Buy All Costumes",
    "Buy an item from each shop in the park",
    "Collect 10,000 coins",
    "Collect 100,000 coins",
    "Collect 14 Different Collection Items",
    "Collect 14 different collectibles",
    "Collect 21 different collectibles",
    "Collect 500,000 coins",
    "Collect 7 Different Collection Items",
    "Collect 7 different collectibles",
    "Collect all of 1 collectible set",
    "Collect all of 2 collectible sets",
    "Collect all of 3 collectible sets",
    "Complete 1 Target Minigame",
    "Complete 10 Adventures",
    "Complete 20 Adventures",
    "Complete 3 Target Minigames",
    "Complete 30 Adventures",
    "Complete 5 Target Minigames",
    "Complete Alice in Wonderland Autograph Book",
    "Complete Big and Small Autograph Book",
    "Complete Black Barty’s Autograph",
    "Complete Enchanted Tiki Room Conducting Minigame",
    "Complete Grim Grinning Ghosts Conducting Minigame",
    "Complete Heroes Autograph Book",
    "Complete Hide ‘n Seek”",
    "Complete Jambalaya Jazz Band Conducting Minigame",
    "Complete Princesses Autograph Book",
    "Complete Royal Street Bachelors Conducting Minigame",
    "Complete The Sensational Six Autograph Book",
    "Complete Toy Story Autograph Book",
    "Complete Tricksters Autograph Book",
    "Complete Villains Autograph Book",
    "Complete Winnie the Pooh Autograph Book",
    "Complete the Discovery Photo Album for Adventureland",
    "Complete the Discovery Photo Album for Critter Country",
    "Complete the Discovery Photo Album for Fantasyland",
    "Complete the Discovery Photo Album for Frontierland",
    "Complete the Discovery Photo Album for Main Street U.S.A",
    "Complete the Discovery Photo Album for Mickey’s Toontown",
    "Complete the Discovery Photo Album for New Orleans Square",
    "Complete the Discovery Photo Album for Tomorrowland",
    "Complete the Photo Pass Album for Adventureland",
    "Complete the Photo Pass Album for Critter Country",
    "Complete the Photo Pass Album for Disneyland Landmarks",
    "Complete the Photo Pass Album for Fantasyland",
    "Complete the Photo Pass Album for Frontierland",
    "Complete the Photo Pass Album for Main Street U.S.A",
    "Complete the Photo Pass Album for Mickey’s Toontown",
    "Complete the Photo Pass Album for New Orleans Square",
    "Complete the Photo Pass Album for Tomorrowland",
    "Complete “A Costume for Jasmine”",
    "Complete “A Fishing Rod for Mowgli”",
    "Complete “A Grand Design”",
    "Complete “A Message for Jumba Jookiba”",
    "Complete “A Message in a Bottle”",
    "Complete “A New Ship”",
    "Complete “Baloo and the Monkeys”",
    "Complete “Beast’s Gift”",
    "Complete “Birthday Lights”",
    "Complete “Black Barty’s Fortune”",
    "Complete “Books for Belle”",
    "Complete “Cheer Up, Stitch”",
    "Complete “Competition”",
    "Complete “Defeat Zurg”",
    "Complete “Diamond Hunt”",
    "Complete “Dinglehoppers”",
    "Complete “Dressed for the Ball”",
    "Complete “Eeyore’s Tail”",
    "Complete “Election Photos”",
    "Complete “Election Preparations”",
    "Complete “Feed Stitch”",
    "Complete “Fishing for Pearls”",
    "Complete “Fixing Beast’s Book”",
    "Complete “Further Election Preparations”",
    "Complete “Goofy’s Fireworks”",
    "Complete “Gooseberry Pie”",
    "Complete “Help Jumba”",
    "Complete “Help Tiana”",
    "Complete “Hidden Treasure”",
    "Complete “Homework”",
    "Complete “Honey, Honey, Honey”",
    "Complete “Hook’s New Look”",
    "Complete “In a Man’s World”",
    "Complete “Inspiration for the Parade”",
    "Complete “Join the Lost Boys”",
    "Complete “Joining the Jolly Roger”",
    "Complete “Meet Sheriff Woody”",
    "Complete “Merryweather’s Gift”",
    "Complete “Mickey’s Photo Album”",
    "Complete “Missing Books”",
    "Complete “Pete’s Gold”",
    "Complete “Pete’s a-Missin’”",
    "Complete “Pooh’s Birthday Party”",
    "Complete “Preparations for the Ball”",
    "Complete “Royal Service”",
    "Complete “Royal Tea Party”",
    "Complete “Scuttle Strikes Again”",
    "Complete “Space Ranger Cadets”",
    "Complete “Surprise”",
    "Complete “The Election!”",
    "Complete “The Lost Ribbon”",
    "Complete “The Lost Watch”",
    "Complete “The Monster”",
    "Complete “The Return of Genie”",
    "Complete “The Royal Celebration”",
    "Complete “The Sting”",
    "Complete “The Stress of Success”",
    "Complete “The Trouble With Woozles”",
    "Complete “Treasure Hunt”",
    "Complete “Water the Flowers”",
    "Complete “What Did We Catch”",
    "Complete “Where Am I?”",
    "Complete “X Marks the Spot”",
    "Complete “You Shall Go to the Ball”",
    "Complete” Ariel’s Parade”",
    "Dance with Aladdin",
    "Dance with Alice",
    "Dance with Ariel",
    "Dance with Aurora",
    "Dance with Baloo",
    "Dance with Beast",
    "Dance with Belle",
    "Dance with Black Barty",
    "Dance with Br’er Bear",
    "Dance with Br’er Fox",
    "Dance with Br’er Rabbit",
    "Dance with Buzz",
    "Dance with Captain Hook",
    "Dance with Chip and Dale",
    "Dance with Cinderella",
    "Dance with Daisy",
    "Dance with Donald Duck",
    "Dance with Duffy Bear",
    "Dance with Eeyore",
    "Dance with Genie",
    "Dance with Goofy",
    "Dance with Jasmine",
    "Dance with Jessie",
    "Dance with Mickey",
    "Dance with Minnie",
    "Dance with Mowgli",
    "Dance with Naveen",
    "Dance with Peter Pan",
    "Dance with Piglet",
    "Dance with Pinocchio",
    "Dance with Pluto",
    "Dance with Pooh",
    "Dance with Snow White",
    "Dance with Stinky Pete",
    "Dance with Stitch",
    "Dance with The Mad Hatter",
    "Dance with The Martians",
    "Dance with The Queen of Hearts",
    "Dance with The White Rabbit",
    "Dance with Tiana",
    "Dance with Tigger",
    "Dance with Woody",
    "Dance with all of the Princesses",
    "Finish 25% of Adventureland",
    "Finish 25% of Critter Country",
    "Finish 25% of Fantasyland",
    "Finish 25% of Frontierland",
    "Finish 25% of Main Street U.S.A",
    "Finish 25% of Mickey’s Toontown",
    "Finish 25% of New Orleans Square",
    "Finish 25% of Tomorrowland",
    "Finish 50% of Adventureland",
    "Finish 50% of Critter Country",
    "Finish 50% of Fantasyland",
    "Finish 50% of Frontierland",
    "Finish 50% of Main Street U.S.A",
    "Finish 50% of Mickey’s Toontown",
    "Finish 50% of New Orleans Square",
    "Finish 50% of Tomorrowland",
    "Finish 75% of Adventureland",
    "Finish 75% of Critter Country",
    "Finish 75% of Fantasyland",
    "Finish 75% of Frontierland",
    "Finish 75% of Main Street U.S.A",
    "Finish 75% of Mickey’s Toontown",
    "Finish 75% of New Orleans Square",
    "Finish 75% of Tomorrowland",
    "Get Aladdin’s Autograph",
    "Get Alice’s Autograph",
    "Get Ariel’s Autograph",
    "Get Aurora’s Autograph",
    "Get Baloo’s Autograph",
    "Get Beast’s Autograph",
    "Get Belle’s Autograph",
    "Get Br’er Bear’s Autograph",
    "Get Br’er Fox’s Autograph",
    "Get Br’er Rabbit’s Autograph",
    "Get Buzz’s Autograph",
    "Get Captain Hook’s Autograph",
    "Get Chip and Dale’s Autograph",
    "Get Cinderella’s Autograph",
    "Get Daisy’s Autograph",
    "Get Donald Duck’s Autograph",
    "Get Duffy Bear’s Autograph",
    "Get Eeyore’s Autograph",
    "Get Genie’s Autograph",
    "Get Goofy’s Autograph",
    "Get Jasmine’s Autograph",
    "Get Jessie’s Autograph",
    "Get Mad Hatter’s Autograph",
    "Get Mickey’s Autograph",
    "Get Minnie’s Autograph",
    "Get Mowgli’s Autograph",
    "Get Naveen’s Autograph",
    "Get Peter Pan’s Autograph",
    "Get Piglet’s Autograph",
    "Get Pinocchio’s Autograph",
    "Get Pluto’s Autograph",
    "Get Pooh’s Autograph",
    "Get Snow White’s Autograph",
    "Get Stinky Pete’s Autograph",
    "Get Stitch’s Autograph",
    "Get The Martian’s Autograph",
    "Get The Queen of Hearts’ Autograph",
    "Get Tiana’s Autograph",
    "Get Tigger’s Autograph",
    "Get White Rabbit’s Autograph",
    "Get Woody’s Autograph",
    "High Fived all of the Fab Five",
    "Hug Aladdin",
    "Hug Alice",
    "Hug Ariel",
    "Hug Aurora",
    "Hug Baloo",
    "Hug Beast",
    "Hug Belle",
    "Hug Black Barty",
    "Hug Br’er Bear",
    "Hug Br’er Fox",
    "Hug Br’er Rabbit",
    "Hug Buzz",
    "Hug Captain Hook",
    "Hug Chip and Dale",
    "Hug Cinderella",
    "Hug Daisy",
    "Hug Donald Duck",
    "Hug Duffy Bear",
    "Hug Eeyore",
    "Hug Genie",
    "Hug Goofy",
    "Hug Jasmine",
    "Hug Jessie",
    "Hug Mickey",
    "Hug Minnie",
    "Hug Mowgli",
    "Hug Naveen",
    "Hug Peter Pan",
    "Hug Piglet",
    "Hug Pinocchio",
    "Hug Pluto",
    "Hug Pooh",
    "Hug Snow White",
    "Hug Stinky Pete",
    "Hug Stitch",
    "Hug The Mad Hatter",
    "Hug The Martians",
    "Hug The Queen of Hearts",
    "Hug The White Rabbit",
    "Hug Tiana",
    "Hug Tigger",
    "Hug Woody",
    "Hug all of the Villains",
    "Make Monstro the Whale Sneeze",
    "Obtain all 10 secrets on Alice in Wonderland",
    "Obtain all 10 secrets on Big Thunder Mountain Railroad",
    "Obtain all 10 secrets on Buzz Lightyear’s Astro Blasters",
    "Obtain all 10 secrets on Disney Princess Fantasy Faire",
    "Obtain all 10 secrets on Finding Nemo Submarine Voyage",
    "Obtain all 10 secrets on Fireworks Spectacular",
    "Obtain all 10 secrets on Haunted Mansion",
    "Obtain all 10 secrets on Jungle Cruise",
    "Obtain all 10 secrets on Matterhorn Bobsleds",
    "Obtain all 10 secrets on Mickey’s Soundsational Parade",
    "Obtain all 10 secrets on Peter Pan’s Flight",
    "Obtain all 10 secrets on Pirates of the Caribbean",
    "Obtain all 10 secrets on Pixie Hollow",
    "Obtain all 10 secrets on Space Mountain",
    "Obtain all 10 secrets on Splash Mountain",
    "Obtain all 10 secrets on The Many Adventures of Winnie the Pooh",
    "Obtain all 10 secrets on “It’s a Small World”",
    "Obtain all 7 of the Magic Items",
    "Obtain the Blaster Magic Item",
    "Obtain the Camera Magic Item",
    "Obtain the Fishing Rod Magic Item",
    "Obtain the Megaphone Magic Item",
    "Obtain the Spyglass Magic Item",
    "Obtain the Squirtgun Magic Item",
    "Obtain the Wand Magic Item",
    "Photograph 10 Hidden Mickeys",
    "Photograph 20 Hidden Mickeys",
    "Photograph 30 Hidden Mickeys",
    "Photograph Aladdin",
    "Photograph Alice",
    "Photograph Ariel",
    "Photograph Aurora",
    "Photograph Baloo",
    "Photograph Beast",
    "Photograph Belle",
    "Photograph Black Barty",
    "Photograph Br’er Bear",
    "Photograph Br’er Fox",
    "Photograph Br’er Rabbit",
    "Photograph Buzz",
    "Photograph Captain Hook",
    "Photograph Chip and Dale",
    "Photograph Cinderella",
    "Photograph Daisy",
    "Photograph Donald Duck",
    "Photograph Duffy Bear",
    "Photograph Eeyore",
    "Photograph Genie",
    "Photograph Goofy",
    "Photograph Jasmine",
    "Photograph Jessie",
    "Photograph Mickey",
    "Photograph Minnie",
    "Photograph Mowgli",
    "Photograph Naveen",
    "Photograph Peter Pan",
    "Photograph Piglet",
    "Photograph Pinocchio",
    "Photograph Pluto",
    "Photograph Pooh",
    "Photograph Snow White",
    "Photograph Stinky Pete",
    "Photograph Stitch",
    "Photograph The Mad Hatter",
    "Photograph The Martians",
    "Photograph The Queen of Hearts",
    "Photograph The White Rabbit",
    "Photograph Tiana",
    "Photograph Tigger",
    "Photograph Woody",
    "Play Disney Princess Fantasy Faire",
    "Play Fireworks Spectacular",
    "Play Mickey’s Soundsational Parade",
    "Play Pixie Hollow",
    "Play all 2 chapters of Big Thunder Mountain Railroad",
    "Play all 2 chapters of Haunted Mansion",
    "Play all 2 chapters of Space Mountain",
    "Play all 2 chapters of Splash Mountain",
    "Play all 3 chapters of Alice in Wonderland",
    "Play all 3 chapters of Finding Nemo Submarine Voyage",
    "Play all 3 chapters of Jungle Cruise",
    "Play all 3 chapters of Matterhorn Bobsleds",
    "Play all 3 chapters of The Many Adventures of Winnie the Pooh",
    "Play all 4 chapters of Buzz Lightyear’s Astro Blasters",
    "Play all 4 chapters of Peter Pan’s Flight",
    "Play all 4 chapters of Pirates of the Caribbean",
    "Play “It’s a Small World”",
    "Reach Level 10",
    "Reach Level 11",
    "Reach Level 12",
    "Reach Level 13",
    "Reach Level 14",
    "Reach Level 2",
    "Reach Level 3",
    "Reach Level 4",
    "Reach Level 5",
    "Reach Level 6",
    "Reach Level 7",
    "Reach Level 8",
    "Reach Level 9",
    "Reach Max Level",
    "Ride Alice in Wonderland Teacups",
    "Ride All Non-Playable Rides",
    "Ride Astro Orbiter",
    "Ride Dumbo the Flying Elephant",
    "Ride Gadget Go Coaster",
    "Ride King Arthur Carrousel",
    "Talk to 1 Park Guide",
    "Talk to 3 Park Guides",
    "Talk to 5 Park Guides",
    "Won 5 bronze pin badges for attractions",
    "Won 5 gold pin badges for attractions",
    "Won 5 platinum pin badges for attractions",
    "Won 5 silver pin badges for attractions",
    "Won the bronze pin badge on Alice in Wonderland",
    "Won the bronze pin badge on Big Thunder Mountain Railroad",
    "Won the bronze pin badge on Buzz Lightyear’s Astro Blasters",
    "Won the bronze pin badge on Disney Princess Fantasy Faire",
    "Won the bronze pin badge on Finding Nemo Submarine Voyage",
    "Won the bronze pin badge on Fireworks Spectacular",
    "Won the bronze pin badge on Haunted Mansion",
    "Won the bronze pin badge on Jungle Cruise",
    "Won the bronze pin badge on Matterhorn Bobsleds",
    "Won the bronze pin badge on Mickey’s Soundsational Parade",
    "Won the bronze pin badge on Peter Pan’s Flight",
    "Won the bronze pin badge on Pirates of the Caribbean",
    "Won the bronze pin badge on Pixie Hollow",
    "Won the bronze pin badge on Space Mountain",
    "Won the bronze pin badge on Splash Mountain",
    "Won the bronze pin badge on The Many Adventures of Winnie the Pooh",
    "Won the bronze pin badge on “It’s a Small World”",
    "Won the gold pin badge on Alice in Wonderland",
    "Won the gold pin badge on Big Thunder Mountain Railroad",
    "Won the gold pin badge on Buzz Lightyear’s Astro Blasters",
    "Won the gold pin badge on Disney Princess Fantasy Faire",
    "Won the gold pin badge on Finding Nemo Submarine Voyage",
    "Won the gold pin badge on Fireworks Spectacular",
    "Won the gold pin badge on Haunted Mansion",
    "Won the gold pin badge on Jungle Cruise",
    "Won the gold pin badge on Matterhorn Bobsleds",
    "Won the gold pin badge on Mickey’s Soundsational Parade",
    "Won the gold pin badge on Peter Pan’s Flight",
    "Won the gold pin badge on Pirates of the Caribbean",
    "Won the gold pin badge on Pixie Hollow",
    "Won the gold pin badge on Space Mountain",
    "Won the gold pin badge on Splash Mountain",
    "Won the gold pin badge on The Many Adventures of Winnie the Pooh",
    "Won the gold pin badge on “It’s a Small World”",
    "Won the platinum pin badge on Alice in Wonderland",
    "Won the platinum pin badge on Big Thunder Mountain Railroad",
    "Won the platinum pin badge on Buzz Lightyear’s Astro Blasters",
    "Won the platinum pin badge on Disney Princess Fantasy Faire",
    "Won the platinum pin badge on Finding Nemo Submarine Voyage",
    "Won the platinum pin badge on Fireworks Spectacular",
    "Won the platinum pin badge on Haunted Mansion",
    "Won the platinum pin badge on Jungle Cruise",
    "Won the platinum pin badge on Matterhorn Bobsleds",
    "Won the platinum pin badge on Mickey’s Soundsational Parade",
    "Won the platinum pin badge on Peter Pan’s Flight",
    "Won the platinum pin badge on Pirates of the Caribbean",
    "Won the platinum pin badge on Pixie Hollow",
    "Won the platinum pin badge on Space Mountain",
    "Won the platinum pin badge on Splash Mountain",
    "Won the platinum pin badge on The Many Adventures of Winnie the Pooh",
    "Won the platinum pin badge on “It’s a Small World”",
    "Won the silver pin badge on Alice in Wonderland",
    "Won the silver pin badge on Big Thunder Mountain Railroad",
    "Won the silver pin badge on Buzz Lightyear’s Astro Blasters",
    "Won the silver pin badge on Disney Princess Fantasy Faire",
    "Won the silver pin badge on Finding Nemo Submarine Voyage",
    "Won the silver pin badge on Fireworks Spectacular",
    "Won the silver pin badge on Haunted Mansion",
    "Won the silver pin badge on Jungle Cruise",
    "Won the silver pin badge on Matterhorn Bobsleds",
    "Won the silver pin badge on Mickey’s Soundsational Parade",
    "Won the silver pin badge on Peter Pan’s Flight",
    "Won the silver pin badge on Pirates of the Caribbean",
    "Won the silver pin badge on Pixie Hollow",
    "Won the silver pin badge on Space Mountain",
    "Won the silver pin badge on Splash Mountain",
    "Won the silver pin badge on The Many Adventures of Winnie the Pooh",
    "Won the silver pin badge on “It’s a Small World”"
];
