bingoGenerator = require("./generators/generator_bases/simple_generator.js");
//Made By TK
var bingoList = [
{"name": "all toys in 1 level in each WR"},
{"name": "a time challenge from each WR"},
{"name": "ELP one level from each WR"},
{"name": "time challenge in the nephew's murky way and huey's track"},
{"name": "time challenge in urban high-rises and ghostly path"},
{"name": "time challenge in Earie Alley and artifact way"},
{"name": "time challenge in dangerous cliff and dewey's rooftops"},
{"name": "time challenge in the roofs and the gorge"},
{"name": "time challenge in louie's creepy corridor and ancient fate"},
{"name": "time challenge in forest edge and haunted hall"},
{"name": "time challenge in first avenue and temple's entrance"},
{"name": "ELP Earie Alley and dangerous cliff"},
{"name": "ELP artifact way and dewey's rooftops"},
{"name": "ELP  the nephew's murky way and urban high-rises"},
{"name": "ELP huey's track and ghostly path"},
{"name": "ELP the roofs and ancient fate"},
{"name": "ELP the gorge and louie's creepy corridor"},
{"name": "ELP forest edge and temple's entrance"},
{"name": "ELP first avenue and haunted hall"},
{"name": "ELP Earie Alley and ancient fate"},
{"name": "ELP artifact way and louie's creepy corridor"},
{"name": "ELP  the nephew's murky way and temple's entrance"},
{"name": "ELP huey's track and haunted hall"},
{"name": "ELP the roofs and dangerous cliff"},
{"name": "ELP the gorge and dewey's rooftops"},
{"name": "ELP forest edge and urban high-rises"},
{"name": "ELP first avenue and ghostly path"},
{"name": "ELP Earie Alley and louie's creepy corridor"},
{"name": "ELP artifact way and ancient fate"},
{"name": "ELP  the nephew's murky way and haunted hall"},
{"name": "ELP huey's track and temple's entrance"},
{"name": "ELP the roofs and dewey's rooftops"},
{"name": "ELP the gorge and dangerous cliff"},
{"name": "ELP forest edge and ghostly path"},
{"name": "ELP first avenue and urban high-rises"},
{"name": "all toys in the roofs and louie's creepy corridor"},
{"name": "all toys in ancient fate and the gorge"},
{"name": "all toys  the nephew's murky way and  ghostly path"},
{"name": "all toys huey's track and urban high-rises"},
{"name": "all toys Earie Alley and dewey's rooftops"},
{"name": "all toys dangerous cliff and artifact way"},
{"name": "all toys forest edge and first avenue"},
{"name": "all toys  haunted hall and temple's entrance"},
{"name": "time challenge in the nephew's murky way and all toys in artifact way"},
{"name": "time challenge in urban high-rises and all toys in dewey's rooftops"},
{"name": "time challenge in huey's track and all toys in dangerous cliff"},
{"name": "time challenge in ghostly path and all toys in Earie Alley"},
{"name": "time challenge in the roofs and all toys in first avenue"},
{"name": "time challenge in the gorge and all toys in forest edge"},
{"name": "time challenge in louie's creepy corridor and all toys in temple's entrance"},
{"name": "time challenge in haunted hall and all toys in ancient fate"},
{"name": "all toys in wR1"},
{"name": "all toys in WR2"},
{"name": "all toys in WR3"},
{"name": "all toys in wR4"},
{"name": "all time trials in a WR and change outfit"},
{"name": "20 lives"},
{"name": "10 toys"},
{"name": "15 toys"},
{"name": "5 time trials"},
{"name": "8 time trials"},
{"name": "100% forest edge"},
{"name": "100% the gorge"},
{"name": "100% huey's track"},
{"name": "100% dangerous cliff"},
{"name": "100% first avenue"},
{"name": "100% the roofs"},
{"name": "100% dewey's rooftops"},
{"name": "100% urban high-rises"},
{"name": "100% haunted hall"},
{"name": "100% earie alley"},
{"name": "100% louie's creepy corridor"},
{"name": "100% ghostly path"},
{"name": "100% temple's entrance"},
{"name": "100% artifact way"},
{"name": "100% the nephew's murky way"},
{"name": "100% ancient fate"},
{"name": "defeat merlock"},
{"name": "defeat magica de spell"},
{"name": "defeat beagle boys"},
{"name": "defeat bernadette the chicken"},
{"name": "finish bears path"},
{"name": "finish main street"},
{"name": "finish under handed"},
{"name": "finish head alley"},
{"name": "100% a WR including the bonus level"},
{"name": "explode 10 dynamites"},
{"name": "finish a level without getting any star(not time trial)"},
{"name": "finish a level without dying in it"},
{"name": "Defeat 2 bosses"},
{"name": "1 toy from each WR"},
{"name": " 7 toys in WR1"},
{"name": "7 toys in WR2"},
{"name": "7 toys in WR3"},
{"name": "7 toys in WR4"},
{"name": "5 toys in WR1 and 5 in WR3"},
{"name": "5 toys in WR4 and 5 in WR2"},
{"name": "5 toys in WR1 and 5 in WR4"},
{"name": " 5 toys in WR3 and 5 in WR2"}
];
