bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "artist´s apprentice",
    "bakery real eastete agent",
    "book enthusiast",
    "cat nap enabler",
    "complete 2 minigames in at least 2 of their levels each one",
    "complete 3 minigames",
    "complete 4 minigames",
    "complete a minigame in at least 2 of his levels",
    "complete archery",
    "complete archery advanced",
    "complete at least 2 minigames without pressing spacebar (synchronized swimming doesn't count)",
    "complete at least 3 minigames without pressing spacebar (synchronized swimming doesn't count)",
    "complete climbing",
    "complete climbing advanced",
    "complete marathon",
    "complete marathon advanced",
    "complete rugby",
    "complete rugby advanced",
    "complete rugby with at least 120/100 meters",
    "complete skateboarding",
    "complete skateboarding advanced",
    "complete synchronized swimming",
    "complete synchronized swimming advanced",
    "complete synchronized swimming master",
    "complete table tennis",
    "complete table tennis advanced",
    "complete table tennis master",
    "construction employee of the year",
    "crabby realtor",
    "get 10 total trophies",
    "get 15 total trophies",
    "get 2 trophies in archery zone",
    "get 2 trophies in bamboo forest (table tennis)",
    "get 2 trophies in beach (marathon)",
    "get 2 trophies in city (skateboarding)",
    "get 2 trophies in lake (swimming)",
    "get 2 trophies in lava lake (rugby)",
    "get 2 trophies in mountain (climbing)",
    "get 3 scrolls",
    "get 3 trophies in archery zone",
    "get 3 trophies in bamboo forest (table tennis)",
    "get 3 trophies in beach (marathon)",
    "get 3 trophies in city (skateboarding)",
    "get 3 trophies in lake (swimming)",
    "get 3 trophies in lava lake (rugby)",
    "get 3 trophies in mountain (climbing)",
    "get 4 scrolls",
    "get 5 total trophies",
    "get at least 1 trophie in every area",
    "ghostly delivery",
    "gym motivator",
    "help the trophies turtle",
    "hermit enabler",
    "hot spring savior",
    "lighter of laterns",
    "little motivator",
    "lucky arrow retriever",
    "marathon babysitter",
    "paddle fetcher",
    "peach hunter",
    "race tie breaker",
    "rain stopper",
    "read every signal",
    "royal arrow collector intern",
    "secret skatepark membership",
    "sister reunion organizer",
    "super mountain rescue",
    "talk to every Inari (not headquarter needed)",
    "talk to every Kappa (not headquarter needed)",
    "talk to every Karasu (not headquarter needed)",
    "talk to every Ushi (not headquarter needed)",
    "talk with a champion in 3 different dojos",
    "talk with a champion in 4 different dojos",
    "wind stopper"
];
