bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "100% 5 levels",
    "Beat the game in < 5hrs",
    "Cause en enemy to self-immolate",
    "Chainsaw 20 demons in 1 level",
    "Chainsaw kill 2 Barons of Hell in 1 level",
    "Climb the Argent Energy Tower in < 15min",
    "Collect all DOOM figures",
    "Collect all Praetor Suit tokens",
    "Complete all rune trials",
    "Crouch for an entire boss battle",
    "Destroy all VEGA cores within 30sec",
    // multiple copies of Difficulty + so that it can occur multiple times
    "Difficulty +",
    "Difficulty +",
    "Difficulty +",
    "Dodge all of a boss's attacks for 30sec",
    "Find all Classic level rooms",
    "Finish a level in <10 min",
    "Fully upgrade 5 weapon mods",
    "Get 15 consecutive headshots",
    "Glory kill all enemies in a level",
    "Ignore non-mandatory argent energy",
    "Kill 5 demons w/ 1 shot",
    "Kill Baron of Hell w/ only pistol",
    "Kill a Pinky using only melee",
    "Kill a boss using only 1 weapon",
    "Melee 5 Sucide Skulls",
    "Melee only 1st level",
    "Never upgrade the Praetor Suit",
    "No \"aiming\" for an entire encounter",
    "No BFG use (full run)",
    "No deaths (full run)",
    "No frag grenades (full run)",
    "No movement for an entire encounter",
    "Only use non-upgraded weapons",
    "Passively cross the Argent Enery Tower bridge",
    "Perform 25 glory kills in a row",
    "Play with inverted aim for a level",
    "Play with no HUD (full run)",
    "Punch 10 Turkeys",
    "Score 50k in Demon Destruction",
    "Skip all secrets in 1 level",
    "Stun 6 enemies simultaniously w/ a stun bomb",
    "Upgrade all runes",
    "Use a different weapons for each section of Argent D'Nur",
    "Use no power-ups (full run)",
    "Use no runes (full run)",
    "Use only energy-based weapons (full run)",
    "Use only physical weapons (full run)"
];
