bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Acquire all the rings",
    "Acquire all the staves",
    "Baptize by Kemco",
    "Beat 3 different monsters in the desert before entering Drawbridge Castle",
    "Beat Hazhulkhen with your fists",
    "Beat a boss with no magic at all (not even strength!)",
    "Beat a boss with solo scout",
    "Beat any boss with a solo character under level 10",
    "Beat any boss with no magic and no armor or shield",
    "Beat any boss without any character being above level 6",
    "Beat the Tombstone Cerberus head before anyone reaches level 2",
    "Die from the Rats monster",
    "Encounter the wandering merchant in the world 3 different times",
    "Equip a character with the full dragon set",
    "Feed the shark a full party",
    "Fill 1 characters item bag with only keys",
    "Find Wolf's Wallet (cross the river into Marsh)",
    "Get 100k jade",
    "Get a Kill with Fighter wielding a Bow",
    "Get a Kill with Mage wielding a Long Sword",
    "Get a Kill with Priest wielding Rod",
    "Get a Kill with Scout wielding a Shield",
    "Get every character to at least level 4 before entering Drawbridge castle",
    "Get the Fighter to level 14",
    "Go from one castle to another backwards",
    "Have 3 different NPCs say HAK HAK",
    "Have a collective X (stat) across all 4 party members",
    "Kill 8 different monsters before entering drawbridge castle",
    "Kill Hordkhen with a full living party",
    "Kill a constellation monster in each zone",
    "Kill a hidden dungeon boss",
    "Kill all non-constellation monsters in the desert",
    "Kill all non-constellation monsters in the grassland",
    "Kill all non-constellation monsters in the marsh",
    "Kill all non-constellation monsters in the tundra",
    "Kill an enemy while submerged in water",
    "Kill the I love you robot",
    "Learn every magic spell across all characters",
    "Melee Naak with Mage",
    "No Saves",
    "One File",
    "Reach 50 Fortune stat on 1 character and show that on screen",
    "Read all 8 Lore Coffins in any order",
    "Sell Thiefi Staff to wandering merchant",
    "Spider gauntlet (reach level 6 on any character before leaving the first castle)",
    "Talk to 3 different non-story NPC’s other than the wise old man",
    "Use all the warp points at least once",
    "Visit all Anaks",
    "You may not Drown",
    "You may not cast anti-matter",
    "You may not cast ressurection",
    "You may not revive at shrines"
];
