bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Collect 10 Tushonkas",
    "Collect a Graphics card",
    "Collect a Ledx",
    "Collect a Tetriz",
    "Consume Sugar, Mayo, and Condensed Milk in a single raid and then escape",
    "Extract while fully dehydrated",
    "Extract with a Car Battery",
    "Extract within 10 minutes of the start of a raid",
    "Find a Salewa, bandage, and esmarch in one raid.",
    "Find a golden star in raid",
    "Find a stimulant in raid and use it, then extract",
    "Find paracord in raid",
    "Get a melee kill",
    "Get a three win streak",
    "Get less than 1000xp in raid, extract and survive.",
    "Kill 10 scavs in a single Raid",
    "Kill A Cultist",
    "Kill A PMC with a Toz-106",
    "Kill A PMC with no armor and ps ammo.",
    "Kill Gluhar",
    "Kill Killa",
    "Kill Reshala",
    "Kill Schturman",
    "Kill a PMC with a Grenade",
    "Kill a PMC with a mounted gun",
    "Loot a Level 4 or Higher Helmet",
    "Loot a level 4 or higher Armor",
    "Obtain a key that is worth more than 100k roubles",
    "One enters with nothing and must extract(no run through)",
    "PMC Pistol Kill",
    "Unlock and loot a marked room"
];
