bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Beat a Moonschorced hitless",
    "Bring 4 characters to the Prehevil Bop",
    "Buy a skin bible from the Poketcat at your first encounter with him",
    "Buy an item from the Radiating One",
    "Collect 3 constant heads",
    "Complete a skill tree not of your character",
    "Complete the Prehevil map",
    "Craft 6 different items",
    "Create the full “Makeshift Armor”",
    "Die from infection",
    "Do an Ending without entering the “Equipment” tab",
    "Eat 6 different type of Foods",
    "Fail 3 coin flips in a row",
    "Fight Rancid the Sergal without making using the Hexen once and win",
    "Find Levi’s stash",
    "Finish a combat using only the Talk skill",
    "Gain Panophobia",
    "Get tied up in the train and then override all your save files with this one.",
    "Give 3 carrots to Black Kalev",
    "Guard 3 coin flips attacks from 3 different enemies",
    "Have 1 skill from every contestant skill tree",
    "Have 3 different Engravings on party members",
    "Have 4 Lucky coins",
    "Have 4 Moonschorced contestant alive on the map at the same time",
    "Have a Full Party",
    "Have a Moonschorced contestant kill 3 party members and win",
    "Have a character with 5 different buffs active at the same time",
    "Have a character with 5 different debuffs active at the same time",
    "Have a “good time” with Needle",
    "Have an enemy with 5 different debuffs active at the same time",
    "Have at least affinity 1 with all the gods",
    "Kill 2 Decrepit Priests",
    "Kill 2 Doppelgangers",
    "Kill 3 Moonschorced contestant",
    "Kill 3 enemy with head attacks",
    "Kill 4 contestant (human)",
    "Kill 9 Prehevil villagers",
    "Kill Caligura before he becomes Moonschorched",
    "Kill Father Hugo",
    "Kill Levi’s Doppelganger",
    "Kill Marina’s Doppelganger",
    "Kill Moonless without hitting the Miasma",
    "Kill Needles",
    "Kill Olivia’s Doppelganger",
    "Kill Stitches",
    "Kill Tanaka’s Doppelganger",
    "Kill a Beekeeper",
    "Kill a Deathmask",
    "Kill a Moonschorced contestant with only consumables",
    "Kill a Moonschorced contestant without using any skill",
    "Kill the Centaur",
    "Kill the Heartless One",
    "Kill the Janitor",
    "Kill the Mob",
    "Kill the Platoon while the Sylvian Trooper is still alive",
    "Kill the Ratkin Gang",
    "Kill the Tormented One",
    "Kill the Vile",
    "Kill the Woodsman",
    "Meet august 3 times after he leaves the train",
    "Obtain the Fellatio Effigy",
    "Obtain the Hunger Effigy",
    "Obtain the Leechmonger Ring",
    "Obtain the Martyr Effigy",
    "Obtain the Pinecone Pig",
    "Obtain the Sewer winch",
    "Obtain the guaranteed Betel Stone",
    "Obtain the guaranteed Soul-devouring Necklace",
    "Obtain the guaranteed Vinushka Skin-Bible",
    "Obtain the heads of 8 different enemies",
    "Obtain the “Shield of the four”",
    "Reach 99 Shillings",
    "Reach Ending A",
    "Reach Ending B",
    "Reach Ending C",
    "Reach Max Affinity with All-mer",
    "Reach Max Affinity with Gro-Goroth",
    "Reach Max Affinity with Rher",
    "Reach Max Affinity with Sylvian",
    "Reach Max Affinity with Vinushka",
    "Reach Max Affinity with the God of Fear and Hunger",
    "Reach the Prehevil Bop",
    "Reach the first Pub in Prehevil without opening the main gate",
    "Rematch Rancid the Sergal",
    "Rescue Pav after Kaiser attacks him",
    "See 2 unique defeat cutscene",
    "See Samarie kill Marina’s dad",
    "See a contestant kill another contestant",
    "Sleep in 3 different locations",
    "Squish a Crimson Father",
    "Take Heroin",
    "Take an effigy without having recruited any character",
    "Talk to Iki Turso",
    "Talk to Pocketcat in the Museum",
    "Talk to all three Museum Special Guest",
    "Talk to the Masked Person in the Woods",
    "Turn on all the Telectroscope",
    "Use a skills from 3 different gods in a single fight",
    "Use the suicide or “Inverted crown of thorns” skill",
    "Win a fight without arms"
];
