bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "All 5 Characters at 50+",
    "Collect 13 key items",
    "Collect 3 pieces of Crystal Set",
    "Collect 3 pieces of Dragoon Set",
    "Collect 3 pieces of Paladin Set",
    "Collect 3 pieces of Samurai Set",
    "Collect Adamant Ore",
    "Collect Adamant from Grotto",
    "Collect Ancient Sword",
    "Collect Avenger Sword",
    "Collect Bahamut Summon",
    "Collect Baron Key",
    "Collect Crystal",
    "Collect Cursed Ring",
    "Collect Darkness Crystal",
    "Collect Dragon Whip",
    "Collect Earth Crystal",
    "Collect Excalibur from Kokkol",
    "Collect Glass Helmet",
    "Collect Hook",
    "Collect Leviathan Summon",
    "Collect Lilith Rod",
    "Collect Luca Key",
    "Collect Magma Key",
    "Collect Masamune",
    "Collect Odin Summon",
    "Collect Package",
    "Collect Pan",
    "Collect Pass",
    "Collect Pink Tail",
    "Collect Rat Tail",
    "Collect Ribbon",
    "Collect Rune Axe",
    "Collect Sandyruby",
    "Collect Spoon",
    "Collect Stardust Rod",
    "Collect Sylph Summon",
    "Collect Tower Key",
    "Collect Twinharp",
    "Collect White Lance",
    "Collect Zeus Gauntlet",
    "Collect only Edge or Cecil",
    "Collect only Rydia or Rosa",
    "Complete Giant of Babil",
    "Defeat Asura & Leviathan",
    "Defeat Bahamut",
    "Defeat Boss in Bahamut's Spot",
    "Defeat Boss in Mist Dragon's Spot",
    "Defeat Boss in Octomamm's Spot",
    "Defeat Boss in Odin's Spot",
    "Defeat Boss in Wyvern's Spot",
    "Defeat Bosses in Asura & Leviathan's Spot",
    "Defeat CPU",
    "Defeat Elements",
    "Defeat Evil Wall",
    "Defeat Golbez",
    "Defeat K Eblan & Q Eblan",
    "Defeat Odin",
    "Defeat Ogopogo",
    "Defeat Pale Dim",
    "Defeat Wyvern",
    "Finish with Cid or Kain",
    "Finish with Palom or Porom",
    "Finish with Tellah or Edward",
    "Have Edward Defeat a Boss",
    "Have Rydia or Palom learn Meteo",
    "Skip Edge",
    "Skip FuSoYa"
];
