bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
 'Artemis Arrows',
 'Charm Arrows',
 'Darkness Arrows',
 'Fire Arrows',
 'Ice Arrows',
 'Lit Arrows',
 'Medusa Arrows',
 'Mute Arrows',
 'Poison Arrows',
 'Samurai Arrows',
 'White Arrows',
 'Dwarf Axe',
 'Ogre Axe',
 'Poison Axe',
 'Rune Axe',
 'Boomerang',
 'FullMoon',
 'Archer Bow',
 'Artemis Bow',
 'CrossBow',
 'ElvenBow',
 'GreatBow',
 'Samurai Bow',
 'CatClaw',
 'Charm Claw',
 'Poison Claw',
 'Darkness Sword',
 'Black Sword',
 'Earth Hammer',
 'Silver Hammer',
 'Charm Harp',
 'Crystal Sword',
 'Excalibur',
 'Legend Sword',
 'Light Sword',
 'Long Katana',
 'Middle Katana',
 'Masamune',
 'Murasame',
 'Ninja Katana',
 'Dancing Dagger',
 'Mute Dagger',
 'Spoon',
 'Change Rod',
 'Charm Rod',
 'FlameRod',
 'IceRod',
 'Lilith Rod',
 'Stardust Rod',
 'Thunder Rod',
 'Blizzard Spear',
 'Dragoon Spear',
 'Drain Spear',
 'Flame Spear',
 'Gungnir Spear',
 'White Spear',
 'Wind Spear',
 'Life Staff',
 'Lunar Staff',
 'Power Staff',
 'Silence Staff',
 'Silver Staff',
 'Ancient Sword',
 'Avenger Sword',
 'Defense Sword',
 'Drain Sword',
 'Fire Sword',
 'IceBrand Sword',
 'Medusa Sword',
 'Silver Sword',
 'Slumber Sword',
 'Blitz Whip',
 'Chain Whip',
 'Dragon Whip',
 'Flame Whip',
 'Whip',
 'Black Armor',
 'Crystal Armor',
 'Darkness Armor',
 'Diamond Armor',
 'Dragoon Armor',
 'Fire Armor',
 'Ice Armor',
 'Paladin Armor',
 'Samurai Armor',
 'Silver Armor',
 'Bl. Belt',
 'Black Robe',
 'Gaea Robe',
 'Heroine Robe',
 'Karate Gi',
 'Ninja Gi',
 'Power Robe',
 'Sorcerer Robe',
 'White Robe',
 'Wizard Robe',
 'Bandana',
 'Black Helmet',
 'Crystal Helm',
 'Darkness Helm',
 'Diamond Helm',
 'Dragoon Helm',
 'Gaea Hat',
 'Leather Hat',
 'Glass Helmet',
 'Headband',
 'Ninja Hat',
 'Paladin Helm',
 'Ribbon',
 'Samurai Helm',
 'Silver Helmet',
 'Tiara',
 'Wizard Cap',
 'Aegis Shield',
 'Black Shield',
 'Crystal Shield',
 'Diamond Shield',
 'Dragoon Shield',
 'Fire Shield',
 'Ice Shield',
 'Paladin Shield',
 'Samurai Shield',
 'Silver Shield',
 'Black Gauntlets',
 'Crystal Gauntlets',
 'Darkness Gauntlets',
 'Diamond Gauntlets',
 'Dragoon Gauntlets',
 'Paladin Gauntlets',
 'Samurai Gauntlets',
 'Silver Gauntlets',
 'Zeus Gauntlets',
 'Crystal Ring',
 'Cursed Ring',
 'Diamond Ring',
 'Protect Ring',
 'Rune Ring',
 'Silver Ring',
 'Strength Ring',
 'Bomb Summon',
 'Cockatrice Summon',
 'Mage Summon',
 'Imp Summon',
 'Elixir',
 'Cabin',
 'Whistle',
 'Rat Tail'
];
