bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Bane the Dragon",
    "Braken the Kraken",
    "Buy 100,000G worth of items in one stop",
    "Collect 1 of each shop bracelet",
    "Collect 1 of each wood/iron/steel armor",
    "Confused Kary",
    "Defeat Kary 1",
    "Defeat Kraken 1",
    "Defeat Lich 1",
    "Defeat Tiamat 1",
    "Do Not Use CUR4",
    "Do Not Use FADE",
    "Do Not Use FAST",
    "Do Not Use NUKE",
    "Do Not Use TMPR",
    "Do not WARP in Ice Cave",
    "Garland Boxing",
    "Get Lupa'd",
    "Kill 2 different Worms",
    "Kill 3 different Dragons",
    "Kill 3 different Ghosts",
    "Kill 3 different Giants",
    "Kill 3 different Lizards",
    "Kill 3 different Sahags",
    "Kill 3 different Wolves",
    "Melee the Pirates",
    "Purchase at least 1 spell of levels 1-7",
    "Quake the Dead",
    "See BRAK or BANE",
    "See GLANCE or GLARE",
    "See HEAT or CREMATE",
    "See TOXIC or POISON",
    "Sell 40,000G worth of items in one stop",
    "Take 1 None",
    "Take 2 Black Mages",
    "Take 2 Thieves",
    "Take 2 White Mages",
    "Take 4 Red Mages",
    "Take No Black Belts",
    "Take No Fighters",
    "Talk to 10 Bats in Earth Cave",
    "Talk to 5 Dragons in Cardia Isles",
    "Talk to 5 Mermaids in Sea Shrine",
    "Talk to Hurray Dwarf",
    "Throw Masmune into Space (3F)",
    "Visit Bahamut",
    "Visit every empty room on Earth 5",
    "Visit the Bat Party Room",
    "Walk the Hall of Giants"
];
