bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
	"max out a magic materia",
	"max out a summon materia",
	"max out a skill materia",	
	"max out a passive materia",		
	"steal right arm from a bomb",		
	"win a chocobo race",		
	"defeat one of the weapons",		
	"get a level 4 limit break",		
	"recruit Yuffie",		
	"recruit Vincent",		
	"take Barret on a date at the gold saucer",		
	"obtain Knights of the Round",		
	"get the aqualung enemy skill",		
	"get the matra magic enemy skill",		
	"get the big guard enemy skill",		
	"get the death sentence enemy skill",		
	"reach level 50",		
	"reach level 25",		
	"obtain 5 summons",		
	"obtain murasame",		
	"obtain tiger fang",		
	"obtain umbrella",		
	"obtain crystal comb",		
	"obtain hawkeye",		
	"obtain gold megaphone",		
	"obtain buntline",		
	"obtain flayer",		
	"reach level 15",		
	"obtain 10 summons",		
	"obtain phoenix",		
	"obtain ifrit",		
	"take tifa on a date at the gold saucer",		
	"take aerith on a date at the gold saucer",		
	"obtain shiva",		
	"obtain ramuh",		
	"get 5 baskets in a row on Super Dunk",
	"get all three of the best dress options for cloud",
	"obtain kujata",		
	"obtain alexander",		
	"obtain barrier materia",		
	"obtain revive materia",		
	"obtain time materia",		
	"obtain poison materia",		
	"obtain heal materia",		
	"obtain counter attack materia",		
	"obtain experience plus materia",		
	"obtain HP plus materia",		
	"obtain double cut materia",
	"obtain steal materia",
	"obtain w-summon materia",	
]