bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Beat 1 easy demon",
    "Beat 2 8/9 star levels",
    "Beat 2 gauntlets",
    "Beat 3 6/7 star levels",
    "Beat 4 4/5 star levels",
    "Beat 5 3 star levels",
    "Beat 5 main levels",
    "Beat 7 main levels",
    "Beat 9 main levels",
    "Beat Geometrical Dominator and Cycles in Normal Mode",
    "Beat Hexagon Force and Fingerdash in normal mode",
    "Beat Jumper and xStep in Normal Mode",
    "Beat Theory of Everything in normal mode and Electrodynamix in normal mode",
    "Beat Time Machine and Blast Processing in Normal Mode",
    "Beat a gauntlet",
    "Beat any 2 map packs",
    "Beat any 4 map packs",
    "Beat any 5 map packs",
    "Buy 10 shop items",
    "Buy 12 shop items",
    "Buy 8 shop items",
    "Collect 10 shards total",
    "Collect 15 diamonds",
    "Collect 15 shards total",
    "Collect 20 diamonds",
    "Collect 25 diamonds",
    "Collect 5 fire shards",
    "Collect 5 ice shards",
    "Collect 5 lava shards",
    "Collect 5 poison shards",
    "Collect 5 shadow shards",
    "Complete 20 rated levels",
    "Complete 25 rated levels",
    "Complete 30 rated levels",
    "Complete 4 quests",
    "Complete Dry Out and Base after Base and Can't Let Go",
    "Complete all the questions in a vault",
    "Complete the “I can count!” achievement",
    "Complete the “Uber Hacker” achievement",
    "Do 250 attempts",
    "Do 350 attempts",
    "Do 500 attempts",
    "Get 15% on an insane demon",
    "Get 25% on a medium demon",
    "Get both the vault secret coins",
    "Get the “master detective” achievement",
    "Get the “so close” achievement",
    "Grind 15 user coins",
    "Grind 18 user coins",
    "Grind 21 user coins",
    "Grind 35 stars",
    "Grind 40 stars",
    "Grind 45 stars",
    "Have 3000 mana orbs at any given time",
    "Have 3500 mana orbs at any given time",
    "Have 4000 mana orbs at any given time",
    "Have all 3 coins in any 2 main levels",
    "Have all 3 coins in any 3 main levels",
    "Have all 3 coins in any 4 main levels",
    "Jump 1000 times",
    "Jump 2000 times",
    "Jump 3000 times",
    "Kill 100 icons",
    "Kill 75 icons",
    "Make a 7-second layout (Go for decent gameplay)",
    "Make and release a new level with 500+ objects",
    "Obtain 10 new colours",
    "Obtain 10 new icons",
    "Obtain 10 secret coins",
    "Obtain 12 new colours",
    "Obtain 12 new icons",
    "Obtain 14 new colours",
    "Obtain 15 secret coins",
    "Obtain 2 new balls",
    "Obtain 2 new death effects",
    "Obtain 2 new robots",
    "Obtain 2 new ships",
    "Obtain 2 new spiders",
    "Obtain 2 new trails",
    "Obtain 2 new waves",
    "Obtain 3 new balls",
    "Obtain 3 new robots",
    "Obtain 3 new ships",
    "Obtain 3 new spiders",
    "Obtain 3 new waves",
    "Obtain 4 new balls",
    "Obtain 4 new robots",
    "Obtain 4 new ships",
    "Obtain 4 new spiders",
    "Obtain 4 new waves",
    "Obtain 8 new icons",
    "Obtain a new death effect",
    "Obtain a new trail",
    "Open 2 chests (Any chest works)",
    "Open 4 chests (Any chest works)",
    "Open 6 chests (Any chest works)",
    "Unlock Potbor",
    "Unlock any 2 vaults",
    "Unlock any vault"
];
