bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "100% all collectables in any level",
    "20 bounces on octopus",
    "30 bounces on bounce house",
    "Beat Gluttony boss",
    "Beat Pie boss",
    "Beat pie without getting hit",
    "Break the eggs in the cave by rave",
    "Buy Drug lord outfit (Jungle)",
    "Buy Kitchen apron outfit (flavor peaks)",
    "Buy Miss nate outfit from (sashimi bay)",
    "Buy Toilet paper (Flavor peaks)",
    "Buy any outfit from outfit lady",
    "Climb the mountain the intended way",
    "Collect 10 lucky cats",
    "Collect 18 ing",
    "Collect 3 horns",
    "Collect 3 outlits (IT)",
    "Collect 300 gems",
    "Collect 5 hearts",
    "Collect 5 outfits",
    "Collect beer outfit (Flavor peaks)",
    "Collect one ing each world",
    "Complete 5 challenges",
    "Complete DR jelly",
    "Complete Joyfruit",
    "Complete Pearly gate with one swing",
    "Complete Pearly gate without getting hit",
    "Complete Puzzle",
    "Complete Rave",
    "Complete Ritual site",
    "Complete Sewers",
    "Complete Whale",
    "Complete a light gate",
    "EF to maze",
    "EF to whale",
    "Get Light horns",
    "Get Ram horns",
    "Get Wing horns",
    "Get ground slam skill",
    "Get hand horns",
    "Get swing refill",
    "Get to floating island in hub",
    "Get to the carpark in market",
    "Get vertical nugget throw",
    "Get yogurt with light horns",
    "Grab the ing at the top of the platform in jungle",
    "Hit 2 different bong",
    "Kill all crabs by joyfruit",
    "Kill all enemies in DR jelly",
    "Kill all enemies in Peary gates",
    "Kill all enemies in Sewers",
    "Kill all human in slaughter house",
    "Kill all lizard at joyfruit",
    "Kill all prison guards",
    "Make the bomb in restaurant",
    "Play 2 wack a moles",
    "Play slot machine",
    "Ride 5 Ziplines",
    "Save the munchers in sewers",
    "Space nasa outfit into greed door",
    "Swim from god boss fight to maze",
    "Take out all flying candy meat at flavor peaks",
    "Take out the 3 cross in pearly gates",
    "Talk to npc on Hot air balloon",
    "Unlock a additional heart",
    "Unlock all checkpoints at Flavor peaks",
    "Unlock all checkpoints at Jungle",
    "Unlock all checkpoints at Market",
    "Unlock all checkpoints at Peary gates",
    "Unlock all checkpoints at Sashimi bay",
    "Use the cannon to take out all the goo in whale",
    "Use the cannon to take out the pirate",
    "Vist each outfit lady once",
    "Walk into IT room with Role reverse outfit",
    "Witness the ritual"
];
