//Hitman 3: Miami Finish Line
//Version 1.0
//By Providence Community
bingoGenerator = require("./generators/generator_bases/simple_generator.js");
var bingoList = [
    {"name": "Become a Food Vendor"},
    {"name": "Become a Journalist"},
    {"name": "Become a Kowoon Mechanic"},
    {"name": "Become a Kronstadt Engineer"},
    {"name": "Become a Kronstadt Mechanic"},
    {"name": "Become a Kronstadt Researcher"},
    {"name": "Become a Kronstadt Security"},
    {"name": "Become a Mascot"},
    {"name": "Become a Medic"},
    {"name": "Become a Race Coordinator"},
    {"name": "Become a Race Marshal"},
    {"name": "Become a Sotteraneo Mechanic"},
    {"name": "Become a Thwack Mechanic"},
    {"name": "Become a Waiter"},
    {"name": "Become an Aeon Mechanic"},
    {"name": "Become an Event Crew"},
    {"name": "Become an Event Security"},
    {"name": "Become Florida Man"},
    {"name": "Become Ted Mendez"},
    {"name": "Become the Blue Seed Driver"},
    {"name": "Become the Crashed Kronstadt Driver"},
    {"name": "Become the Kitchen Staff"},
    {"name": "Become the Kowoon Driver"},
    {"name": "Become the Pale Rider"},
    {"name": "Collect 2 Hammers"},
    {"name": "Collect 2 Kitchen Knives"},
    {"name": "Collect 2 Octane Boosters"},
    {"name": "Collect 2 Scissors"},
    {"name": "Collect 3 Crowbars"},
    {"name": "Collect 3 Rat Poisons"},
    {"name": "Collect 3 Screwdrivers"},
    {"name": "Collect a Cleaver"},
    {"name": "Collect a Fish"},
    {"name": "Collect a Medical Cabinet Key"},
    {"name": "Collect a Photo of Robert Knox"},
    {"name": "Collect Maxwell Rutter's Dongle"},
    {"name": "Collect the Amputation Knife"},
    {"name": "Collect the Car Bomb"},
    {"name": "Collect the Electronic Car Key"},
    {"name": "Collect the Incriminating Evidence"},
    {"name": "Collect the Speedboat Key"},
    {"name": "Collect the Starfish"},
    {"name": "Buy a Can of Soda"},
    {"name": "Drop a Racecar with the Car Lift"},
    {"name": "End the race as a Race Marshal"},
    {"name": "Hide someone in the Garden Shredder"},
    {"name": "Interact with a TV"},
    {"name": "Interact with two Fuseboxes"},
    {"name": "Interact with two Generators"},
    {"name": "Make PALLAS shoot a dummy"},
    {"name": "Open Florida Man's Food Stall"},
    {"name": "Peep through the Peep Hole"},
    {"name": "Sabotage the Expo Car's Engine"},
    {"name": "Set the Air Conditioner to dry mode"},
    {"name": "Start a Pit Stop"},
    {"name": "Turn on 2 Faucets"},
    {"name": "Turn on 3 Sinks"},
    {"name": "Turn on both Forklift Alarms"},
    {"name": "Drop a Loudspeaker"},
    {"name": "Make the Fish Trophy swing"},
    {"name": "Shoot 3 Fish Tanks"},
    {"name": "Blend in as Kronstadt Mechanic"},
    {"name": "Blend in as Race Marshal"},
    {"name": "Blend in as Waiter"},
    {"name": "Pacify someone with a Baseball Bat"},
    {"name": "Pacify someone with a Golf Club"},
    {"name": "Pacify someone with a Shovel"},
    {"name": "Pacify someone with an Android Arm"},
    {"name": "Pacify someone with the Frying Pan"},
    {"name": "Pacify someone with the Police Baton"},
    {"name": "Poison the Chili Sauce"},
    {"name": "Poison the Cup of Milk"},
    {"name": "Poison the IV Drip"},
    {"name": "Poison the Trophy"},
    {"name": "Throw a Fish into the Ocean"},
    {"name": "Throw an Octane Booster"},
    {"name": "Toss a Coin into the Aquarium"}
];
