//Hitman 3: Dartmoor Death in the Family
//Version 1.0
//By Providence Community
bingoGenerator = require("./generators/generator_bases/simple_generator.js");
var bingoList = [{"name": "Become a Bodyguard"},
{"name": "Become a Gardener"},
{"name": "Become a Mansion Guard"},
{"name": "Become a Mansion Staff"},
{"name": "Become the Lawyer"},
{"name": "Become the Photographer"},
{"name": "Become the Private Investigator"},
{"name": "Become the Undertaker"},
{"name": "Collect 2 Apples"},
{"name": "Collect 2 Apricots"},
{"name": "Collect 2 Baseballs"},
{"name": "Collect 2 Bricks"},
{"name": "Collect 2 Feather Dusters"},
{"name": "Collect 2 Fuse Cells"},
{"name": "Collect 2 Garden Forks"},
{"name": "Collect 2 Hammers"},
{"name": "Collect 2 Lead Pipes"},
{"name": "Collect 2 Letter Openers"},
{"name": "Collect 2 Newspapers"},
{"name": "Collect 2 Rat Poisons"},
{"name": "Collect 2 Scissors"},
{"name": "Collect 2 Shears "},
{"name": "Collect 2 Unicorn Horns"},
{"name": "Collect a Bag of Sugar"},
{"name": "Collect a Cigar Box"},
{"name": "Collect a Crowbar"},
{"name": "Collect a Hearse Key"},
{"name": "Collect a Poisonous Emetic Flower"},
{"name": "Collect a Screwdriver"},
{"name": "Collect both Irons"},
{"name": "Collect both Wrenches"},
{"name": "Collect Montgomery's Lost Letter"},
{"name": "Collect Mr. Fernsby's List"},
{"name": "Collect the Banana"},
{"name": "Collect the Barber Razor"},
{"name": "Collect the Boat Key"},
{"name": "Collect the Cleaver"},
{"name": "Collect the Folding Knife"},
{"name": "Collect the Greenhouse Key Chain"},
{"name": "Collect the Imperial Filigree Egg"},
{"name": "Collect the Key to Mr. Fernsby's Office"},
{"name": "Collect the Kitchen Knife"},
{"name": "Collect the Lethal Poison Pill Jar"},
{"name": "Collect the Letter from Emma's Mother"},
{"name": "Collect the Letter to Rebecca Carlisle"},
{"name": "Collect the Mansion Floor Plan"},
{"name": "Collect the Mansion Master Key"},
{"name": "Collect the Pool Ball"},
{"name": "Collect the Receipt for Safe Repairs"},
{"name": "Collect the Soda Can"},
{"name": "Collect the Staff Locker Key"},
{"name": "Collect Zachary's Half-Burnt Diary"},
{"name": "Collect Zachary's Suicide Note"},
{"name": "Create a Leak in the Garden Fountain"},
{"name": "Fill the Grave"},
{"name": "Hide someone in the Garden Shredder"},
{"name": "Interact with a Fusebox"},
{"name": "Investigate Rebecca's Laptop"},
{"name": "Investigate the Lawyer's Laptop"},
{"name": "Investigate Zachary's Laptop"},
{"name": "Peep through 2 Peep Holes"},
{"name": "Ring the Dinner Bell"},
{"name": "Turn off the Generator"},
{"name": "Turn on 2 Faucets"},
{"name": "Turn on 2 Gramophones"},
{"name": "Turn on 2 Radios"},
{"name": "Turn on 3 Sinks"},
{"name": "Turn on both Vacuum Cleaners"},
{"name": "Turn on the Answering Machine"},
{"name": "Use the Distillation Kit to make Poison"},
{"name": "Use the Walking Cane on a Switch"},
{"name": "Drop both Hanging Plants"},
{"name": "Shoot all 3 Bird's Nests"},
{"name": "Blend in as a Bodyguard"},
{"name": "Blend in as Mansion Staff"},
{"name": "Pacify someone with a Driftwood Log"},
{"name": "Pacify someone with a Fire Poker"},
{"name": "Pacify someone with a Maori Paddle"},
{"name": "Pacify someone with the Car Battery"},
{"name": "Pacify someone with the Golf Club"},
{"name": "Blow up a Garden Tractor"},
{"name": "Blow up a Propane Flask"},
{"name": "Fire a Bartoli Hunting Shotgun"},
{"name": "Have someone step on a Rake"},
{"name": "Knock someone down with Soap"},
{"name": "Make someone slip on a Banana"},
{"name": "Put the Saber on Alexa's desk"},
{"name": "Throw the Fish into the Lake"},
{"name": "Throw the Hatchet in the Fountain"},
{"name": "Trigger the Bird Cage"}]
