//Hitman 3: Mumbai Chasing a ghost
//Version 1.0
//By Providence Community
bingoGenerator = require("./generators/generator_bases/simple_generator.js");
var bingoList = [{"name": "Become a Bollywood Bodyguard"},
{"name": "Become a Bollywood Crew"},
{"name": "Become a Dancer"},
{"name": "Become a Food Vendor"},
{"name": "Become a Laundry Worker"},
{"name": "Become a Local Security"},
{"name": "Become a Metal Worker"},
{"name": "Become a Queen's Bodyguard"},
{"name": "Become a Queen's Guard"},
{"name": "Become a Thug"},
{"name": "Become a Vanya's Servant"},
{"name": "Become an Elite Thug"},
{"name": "Become the Barber"},
{"name": "Become the Kashmirian"},
{"name": "Become the Laundry Foreman"},
{"name": "Become the Lead Actor"},
{"name": "Become the Painter"},
{"name": "Become the Tailor"},
{"name": "Collect 2 Barber Razors"},
{"name": "Collect 2 Cans of Soda"},
{"name": "Collect 2 Cans of Spaghetti Sauce"},
{"name": "Collect 2 Chennai Cricket Balls"},
{"name": "Collect 2 Crowbars"},
{"name": "Collect 2 Hammers"},
{"name": "Collect 2 Irons"},
{"name": "Collect 2 Lead Pipes"},
{"name": "Collect 2 Rat Poisons"},
{"name": "Collect 2 Wrenches"},
{"name": "Collect 3 Bricks"},
{"name": "Collect 3 Screwdrivers"},
{"name": "Collect a Barbershop Key"},
{"name": "Collect a Hideout Key"},
{"name": "Collect a Kitchen Knife"},
{"name": "Collect a Lethal Poison Pill Jar"},
{"name": "Collect a Letter Opener"},
{"name": "Collect a Luxury Apartment Keycard"},
{"name": "Collect a Maelstrom Manifesto"},
{"name": "Collect a Scissors"},
{"name": "Collect a Train Yard Key"},
{"name": "Collect both Folding Knives"},
{"name": "Collect both Khatvangas"},
{"name": "Collect Neha's Letter on the Hill"},
{"name": "Collect the 'Mumbai Hero' Script"},
{"name": "Collect the Amputation Knife"},
{"name": "Collect the Beach House Key"},
{"name": "Collect the Industrial Fan Instructions"},
{"name": "Collect the Laundry Business Documents"},
{"name": "Collect the Note to Sagar"},
{"name": "Collect the Purple Colored Smoke"},
{"name": "Collect the Request Note to the Tailor"},
{"name": "Collect the Tube of Paint"},
{"name": "Adjust the Kashmirian's Sniper Scope"},
{"name": "Hide someone in the Garden Shredder"},
{"name": "Interact with a Generator"},
{"name": "Override the Steam Pool Pressure Lock"},
{"name": "Peep through the Peep Hole"},
{"name": "Release the Concrete Pipe manually"},
{"name": "Start the Forklift Alarm"},
{"name": "Tamper with the Fan Security System"},
{"name": "Turn off 2 Fuseboxes"},
{"name": "Turn on 2 Industrial Tumble Dryers"},
{"name": "Turn on 2 Sinks"},
{"name": "Turn on a Faucet"},
{"name": "Turn on the Vacuum Cleaner"},
{"name": "Turn on the Water Pump"},
{"name": "Drop a Shop Sign"},
{"name": "Drop the Beach House Rowboat"},
{"name": "Puncture a Water Cooler"},
{"name": "Ignite a Gasoline Drum"},
{"name": "Blend in as a Servant"},
{"name": "Blend in as Bollywood Crew"},
{"name": "Blend in as Metal Worker"},
{"name": "Pacify someone with a Baseball Bat"},
{"name": "Pacify someone with a Frying Pan"},
{"name": "Pacify someone with a Lever"},
{"name": "Pacify someone with a Shovel"},
{"name": "Blow up a Fire Extinguisher"},
{"name": "Blow up a Gas Canister"},
{"name": "Blow up a Pile of Propane Canisters"},
{"name": "Blow up a Propane Flask"},
{"name": "Blow up a Scooter"},
{"name": "Poison a Glass of Wine on the Hill"},
{"name": "Serve someone poisoned Food or Tea"},
{"name": "Have someone step on the Rake"},
{"name": "Throw a Brick into a Forge"}]
