//Hitman 3: New York Golden Handshake
//Version 1.0
//By Providence Community
bingoGenerator = require("./generators/generator_bases/simple_generator.js");
var bingoList = [{"name": "Investigate the Director's Laptop"},
{"name": "Open the Vault"},
{"name": "Peep through the Peep Hole"},
{"name": "Tamper with the ATM"},
{"name": "Tamper with the Clock Panel"},
{"name": "Turn off 2 Fuseboxes"},
{"name": "Turn off Athena's Wi-Fi"},
{"name": "Turn on 3 Sinks"},
{"name": "Turn on a Photocopier"},
{"name": "Turn on the Air Conditioner"},
{"name": "Turn on the Gramophone"},
{"name": "Turn on the Money Counter"},
{"name": "Turn on the TV"},
{"name": "Drop 3 Chandeliers"},
{"name": "Puncture 2 Water Coolers"},
{"name": "Blend in as an Investment Banker"},
{"name": "Pacify someone with a Car Battery"},
{"name": "Pacify someone with a Police Baton"},
{"name": "Pacify someone with a Violin"},
{"name": "Pacify someone with a Wet Floor Sign"},
{"name": "Pacify someone with the Golf Club"},
{"name": "Blow up a Propane Flask"},
{"name": "Poison Athena's Vodka Glass"},
{"name": "Poison Fabian Mann's Coffee"},
{"name": "Poison the Cocaine"},
{"name": "Poison the Fired Banker's Water"},
{"name": "Dump a Fire Axe in a Vent"},
{"name": "Dump a Fire Extinguisher in a Vent"},
{"name": "Sedate someone with Chloroform"},
{"name": "Sedate someone with the Kalmer"}]
