//Hitman 3: Sapienza World of Tomorrow
//Version 1.0
//By Providence Community
bingoGenerator = require("./generators/generator_bases/simple_generator.js");
var bingoList = [
{"name": "Become a Biolab Security"},
{"name": "Become a Bodyguard"},
{"name": "Become a Chef"},
{"name": "Become a Church Staff"},
{"name": "Become a Delivery Man"},
{"name": "Become a Gardener"},
{"name": "Become a Housekeeper"},
{"name": "Become a Kitchen Assistant"},
{"name": "Become a Lab Technician"},
{"name": "Become a Mansion Security"},
{"name": "Become a Mansion Staff"},
{"name": "Become a Priest"},
{"name": "Become a Store Clerk"},
{"name": "Become a Waiter"},
{"name": "Become Roberto Vargas"},
{"name": "Become the Bohemian"},
{"name": "Become the Butler"},
{"name": "Become the Cyclist"},
{"name": "Become the Green Plumber"},
{"name": "Become the Plague Doctor"},
{"name": "Become the Red Plumber"},
{"name": "Equip a Hazmat Suit"},
{"name": "Collect 2 Bricks"},
{"name": "Collect 2 Busts"},
{"name": "Collect 2 Crowbars"},
{"name": "Collect 2 Hammers"},
{"name": "Collect 2 Kitchen Knives"},
{"name": "Collect 2 Scissors"},
{"name": "Collect 2 Wrenches"},
{"name": "Collect 3 Rat Poisons"},
{"name": "Collect 3 Screwdrivers"},
{"name": "Collect 4 Cans of Spaghetti Sauce"},
{"name": "Collect a Cannabis Joint"},
{"name": "Collect a Church Key"},
{"name": "Collect a Combat Knife"},
{"name": "Collect a Folding Knife"},
{"name": "Collect a Mansion Master Key"},
{"name": "Collect a Sewer Key"},
{"name": "Collect the Amputation Knife"},
{"name": "Collect the Cleaver"},
{"name": "Collect the Letter Opener"},
{"name": "Collect the Medical Journal"},
{"name": "Collect the Remote Explosive"},
{"name": "Collect the Romantic Note"},
{"name": "Collect the Toy Tank"},
{"name": "Buy a Can of Soda"},
{"name": "Cook the Sauce as a Kitchen Assistant"},
{"name": "Interact with any 2 Radios"},
{"name": "Interact with 2 TVs"},
{"name": "Interact with both Generators"},
{"name": "Open Silvio's Safe"},
{"name": "Open the Observatory Dome manually"},
{"name": "Place the Golfball in the Bucket"},
{"name": "Play the VHS Tape"},
{"name": "Release a Winch manually"},
{"name": "Ring the Dinner Bell manually"},
{"name": "Turn on 2 Faucets"},
{"name": "Turn on 3 Sinks"},
{"name": "Turn on the Chair Lift"},
{"name": "Turn on the Gramophone"},
{"name": "Wake up the Detective with the Radio"},
{"name": "Drop 3 Chandeliers"},
{"name": "Drop a Stalactite"},
{"name": "Drop the Solar System"},
{"name": "Drop the Church Bell"},
{"name": "Blend in as Gardener"},
{"name": "Blend in as Lab Technician"},
{"name": "Pacify someone with a Baseball Bat"},
{"name": "Pacify someone with a Golf Club"},
{"name": "Pacify someone with the Piano"},
{"name": "Pacify someone with the Police Baton"},
{"name": "Examine the Biolab Safety Protocol"},
{"name": "Blow up a Scooter"},
{"name": "Blow up the Biolab Brick Wall"},
{"name": "Poison Francesca's Champagne"}
];
