//Hitman 3: Dubai On top of the world
//Version 1.0
//By Providence Community
bingoGenerator = require("./generators/generator_bases/simple_generator.js");
var bingoList = [{"name": "Become a Maintenance Staff"},
{"name": "Become a Penthouse Guard"},
{"name": "Become a Penthouse Staff"},
{"name": "Become an Art Crew"},
{"name": "Become an Event Security"},
{"name": "Become an Event Staff"},
{"name": "Become an Ingram's Bodyguard"},
{"name": "Become The Assassin"},
{"name": "Become the Famous Chef"},
{"name": "Become the Helicopter Pilot"},
{"name": "Become the Kitchen Staff"},
{"name": "Collect 2 Crowbars"},
{"name": "Collect 2 Hammers"},
{"name": "Collect 2 Kitchen Knives"},
{"name": "Collect 2 Letter Openers"},
{"name": "Collect 2 Rat Poisons"},
{"name": "Collect 3 Screwdrivers"},
{"name": "Collect a Cannabis Joint"},
{"name": "Collect a Fuse Cell"},
{"name": "Collect a Janitorial Key"},
{"name": "Collect a Staff Keycard"},
{"name": "Collect a Wrench"},
{"name": "Collect an Evacuation Keycard"},
{"name": "Collect both Imperial Filigree Eggs"},
{"name": "Collect the Blueberry Muffin"},
{"name": "Collect the Cleaver"},
{"name": "Collect the Emetic Pills"},
{"name": "Collect the Helicopter Key"},
{"name": "Collect the Iron"},
{"name": "Collect the Meaty Bone"},
{"name": "Collect the Model of the Sceptre"},
{"name": "Collect the Scissors"},
{"name": "Collect the Server Room Keycard"},
{"name": "Buy a Can of Soda"},
{"name": "Place the Golf Ball in the Bucket"},
{"name": "Sabotage a Server Rack"},
{"name": "Speed up the Cooking Timer"},
{"name": "Tamper with 2 Toilet Control Panels"},
{"name": "Tamper with Ingram's Balcony Railing"},
{"name": "Turn off 2 Fuseboxes"},
{"name": "Turn off 2 Generators"},
{"name": "Turn on 2 Sinks"},
{"name": "Turn on 2 Vacuum Cleaners"},
{"name": "Turn on an Ice Machine"},
{"name": "Turn on both Sound Systems"},
{"name": "Turn on the Fumigation Unit"},
{"name": "Turn on the Radio in Ingram's Study"},
{"name": "View the Floor Plans on a Terminal"},
{"name": "Drop 2 Clouds"},
{"name": "Drop 2 Loudspeakers"},
{"name": "Drop a Hanging Lamp"},
{"name": "Drop the Chandelier"},
{"name": "Drop the Hanging Plant"},
{"name": "Puncture 2 Water Coolers"},
{"name": "Ignite a Gasoline Drum"},
{"name": "Blend in as Event Staff"},
{"name": "Blend in as Maintenance Staff"},
{"name": "Blend in as Penthouse Staff"},
{"name": "Pacify someone with a Frying Pan"},
{"name": "Pacify someone with the Golf Club"},
{"name": "Blow up a Fire Extinguisher"},
{"name": "Blow up a Gas Canister"},
{"name": "Blow up a Propane Flask"},
{"name": "Poison Ingram's Plate of Food"},
{"name": "Serve someone a poisoned drink"},
{"name": "Fire a loud weapon"},
{"name": "Knock someone down with a Soap"},
{"name": "Knock someone down with an Apple"},
{"name": "Make someone slip on a Banana"}]
