//Hitman 3: Ambrose Island Shadows in the water
//Version 1.0
//By Providence Community
bingoGenerator = require("./generators/generator_bases/simple_generator.js");
var bingoList = [{"name": "Become a Cook"},
{"name": "Become an Engineer"},
{"name": "Become the Hippie"},
{"name": "Become a Metal Worker"},
{"name": "Become a Militia Soldier"},
{"name": "Become a Pirate"},
{"name": "Equip the free Buccaneer suit"},
{"name": "Collect 2 Apricots"},
{"name": "Collect 2 Bags of Gunpowder"},
{"name": "Collect 2 Bricks"},
{"name": "Collect 2 Cannonballs"},
{"name": "Collect 2 Crowbars"},
{"name": "Collect 2 Fish"},
{"name": "Collect 2 Hammers"},
{"name": "Collect 2 Scissors"},
{"name": "Collect 2 Screwdrivers"},
{"name": "Collect 2 Seashells"},
{"name": "Collect 2 Starfish"},
{"name": "Collect 2 Vodka Bottles"},
{"name": "Collect 2 Whiskey Bottles"},
{"name": "Collect 3 Soda Cans"},
{"name": "Collect 3 Wrenches"},
{"name": "Collect a Bone Lockpick"},
{"name": "Collect a Diary Entry"},
{"name": "Collect a Folding Knife"},
{"name": "Collect a Fuse Cell"},
{"name": "Collect a Garden Fork"},
{"name": "Collect a Kukri Machete"},
{"name": "Collect a Lethal Poisonous Frog"},
{"name": "Collect an Emetic Poisonous Flower"},
{"name": "Collect an Ether Pamphlet"},
{"name": "Collect both Emetic Rat Poisons"},
{"name": "Collect both Newspapers"},
{"name": "Collect both Soaps"},
{"name": "Collect both Spray Cans"},
{"name": "Collect Orson's Access Card"},
{"name": "Collect the Apology Letter"},
{"name": "Collect the Bag of Sugar"},
{"name": "Collect the Barber Razor"},
{"name": "Collect the Cage Key"},
{"name": "Collect the Cleaver"},
{"name": "Collect the Cook's Key"},
{"name": "Collect the Gold Idol"},
{"name": "Collect the Hook"},
{"name": "Collect the Iron"},
{"name": "Collect the Letter Opener"},
{"name": "Collect the Longtail Boat Key"},
{"name": "Collect the Message in a Bottle"},
{"name": "Collect the Nitroglycerin"},
{"name": "Collect the Old Axe"},
{"name": "Collect the Scrap Sword"},
{"name": "Collect the Shears"},
{"name": "Collect the Submarine Key"},
{"name": "Collect the Tactical Boat Key"},
{"name": "Collect the Village Master Key"},
{"name": "Break a Wooden Board"},
{"name": "Conceal an item in a Crab Hole"},
{"name": "Craft a Makeshift Explosive"},
{"name": "Dump something down the Vent"},
{"name": "Ignite a Brazier"},
{"name": "Interact with 2 Generators"},
{"name": "Peep through the Peep Hole"},
{"name": "Read Crest's Plan on the Cave Laptop"},
{"name": "Repair the Boat Engine"},
{"name": "Talk to Agent Smith"},
{"name": "Turn off the Projector"},
{"name": "Turn on 2 Radios"},
{"name": "Turn on the Car Battery Charger"},
{"name": "Turn on the Meeting Signal Light"},
{"name": "Turn on the Motor"},
{"name": "Turn on the Vacuum Cleaner"},
{"name": "Turn on the Water Pump"},
{"name": "Drop both Lamps"},
{"name": "Drop the Bag of Bricks"},
{"name": "Drop the Boat"},
{"name": "Drop the Stalactite in the Militia Cave"},
{"name": "Ignite two Gasoline Drums"},
{"name": "Puncture a Water Barrel"},
{"name": "Blend in as Metal Worker"},
{"name": "Blend in as Militia Member"},
{"name": "Blend in as Pirate"},
{"name": "Pacify someone with a Driftwood Log"},
{"name": "Pacify someone with a Frying Pan"},
{"name": "Pacify someone with a Paddle"},
{"name": "Pacify someone with a Shovel"},
{"name": "Pacify someone with a Wooden Torch"},
{"name": "Pacify someone with the Khatvanga"},
{"name": "Pacify someone with the Umbrella"},
{"name": "Blow up 2 Gas Canisters"},
{"name": "Blow up a Fire Extinguisher"},
{"name": "Blow up a Molotov Cocktail"},
{"name": "Blow up a Propane Flask"},
{"name": "Poison both Glasses in the Meeting Area"},
{"name": "Poison Noel's Plate of Food"},
{"name": "Poison Orson's Dish"},
{"name": "Serve someone poisoned Beer"},
{"name": "Fire the Shashka A33 Gold"},
{"name": "Knock someone down with an Apple"},
{"name": "Make someone slip on a Banana"},
{"name": "Take a Photo of Lance Hsu"}]
