//Hitman 3: Hokkaido Situs Inversus
//Version 1.0
//By Providence Community
bingoGenerator = require("./generators/generator_bases/simple_generator.js");
var bingoList = [
    {"name": "Become a Bodyguard"},
    {"name": "Become a Chef"},
    {"name": "Become a Doctor"},
    {"name": "Become a Handyman"},
    {"name": "Become a Morgue Doctor"},
    {"name": "Become a Patient"},
    {"name": "Become a Resort Security"},
    {"name": "Become a Resort Staff"},
    {"name": "Become Amos Dexter"},
    {"name": "Become Jason Portman"},
    {"name": "Become the Helicopter Pilot"},
    {"name": "Become the Hospital Director"},
    {"name": "Become the Motorcyclist"},
    {"name": "Become the Yoga Instructor"},
    {"name": "Collect 2 Rat Poisons"},
    {"name": "Collect 2 Wrenches"},
    {"name": "Collect 3 Soda Cans"},
    {"name": "Collect a Crowbar"},
    {"name": "Collect a vial of Botulinum Toxin"},
    {"name": "Collect both Cleavers"},
    {"name": "Collect both Hammers"},
    {"name": "Collect both Kitchen Knives"},
    {"name": "Collect both Scalpels"},
    {"name": "Collect both Screwdrivers"},
    {"name": "Collect Erich Soders' Kill List"},
    {"name": "Collect the Bust in Portman's Suite"},
    {"name": "Collect the Cowboy Bust"},
    {"name": "Activate Expert Mode on the Console"},
    {"name": "Better the Curator's mood with the remote"},
    {"name": "Buy a Can of Soda"},
    {"name": "Call for Assistance with Dexter's IV Stand"},
    {"name": "Conceal an item in the Briefcase"},
    {"name": "Cut the Fugu Fish"},
    {"name": "Decrease the Organ Room Temperature"},
    {"name": "Drain the Stem Cell Pump"},
    {"name": "Hide someone in the Incinerator"},
    {"name": "Increase the Sauna Temperature"},
    {"name": "Interact with 2 TVs"},
    {"name": "Interact with the Operation Controls panel"},
    {"name": "Open the Roller Door in the Kitchen"},
    {"name": "Place a Pack of Cigarettes for Yuki"},
    {"name": "Tamper with 2 Toilet Control Panels"},
    {"name": "Turn off the Bridge Lights"},
    {"name": "Turn off the Examination Room Spotlight"},
    {"name": "Turn off the Generator"},
    {"name": "Turn off the Radio in the Changing Room"},
    {"name": "Turn off the Spa's Cold Water"},
    {"name": "Turn on the Vacuum Cleaner"},
    {"name": "Damage the Aquarium"},
    {"name": "Drop 3 Icicles"},
    {"name": "Start a Fire"},
    {"name": "Blend in as Handyman"},
    {"name": " Blend in as Resort Staff"},
    {"name": "Pacify someone with a Fire Poker"},
    {"name": "Pacify someone with the Frying Pan"},
    {"name": "Pacify someone with the Police Baton"},
    {"name": "Examine 2 Confidential Patient Journals"},
    {"name": "Examine Dexter's Public Patient Journal"},
    {"name": "Examine Portman's Public Patient Journal"},
    {"name": "Examine the KAI Surgical System Manual"},
    {"name": "Examine the Research Assistant's Notes"},
    {"name": "Blow up the Fire Extinguisher"},
    {"name": "Blow up the Gas Canister"},
    {"name": "Blow up the Propane Flask"},
    {"name": "Blow up Yuki's Gas Heater Lamp"},
    {"name": "Poison the Heli Pilot's Pill Stash"},
    {"name": "Serve someone poisoned Sushi"},
    {"name": "Place the Katana on the Yoga Platform"}
];
