//Hitman 3: Bangkok Club 27
//Version 1.0
//By Providence Community
bingoGenerator = require("./generators/generator_bases/simple_generator.js");
var bingoList = [   
    {"name": "Become a Cross' Bodyguard"},
    {"name": "Become a Groundskeeper"},
    {"name": "Become a Hotel Security"},
    {"name": "Become a Hotel Staff"},
    {"name": "Become a Kitchen Staff"},
    {"name": "Become a Recording Crew"},
    {"name": "Become a Waiter"},
    {"name": "Become Abel de Silva"},
    {"name": "Become an Exterminator"},
    {"name": "Become Morgan's Bodyguard"},
    {"name": "Become the Stalker"},
    {"name": "Collect 2 Crowbars"},
    {"name": "Collect 2 Hammers"},
    {"name": "Collect 2 Kitchen Knives"},
    {"name": "Collect 2 Rat Poisons"},
    {"name": "Collect 2 Screwdrivers"},
    {"name": "Collect 2 Wrenches"},
    {"name": "Collect 4 Coconuts"},
    {"name": "Collect a Letter Opener"},
    {"name": "Collect a Master Keycard"},
    {"name": "Collect both Pool Balls"},
    {"name": "Collect the Cake Topper"},
    {"name": "Collect the Cleaver"},
    {"name": "Collect the Insecticide"},
    {"name": "Collect the Lead Pipe"},
    {"name": "Collect the Letter for Ken"},
    {"name": "Buy a Can of Soda"},
    {"name": "Conceal an item in the Briefcase"},
    {"name": "Increase Voltage on the Regulator"},
    {"name": "Interact with a Sound System"},
    {"name": "Play the Guitar"},
    {"name": "Repair the Tuk-Tuk Engine"},
    {"name": "Sit down in Jordan's Room"},
    {"name": "Talk to the Hotel Director"},
    {"name": "Turn off a Fumigation Unit"},
    {"name": "Turn off the Fusebox"},
    {"name": "Turn on 2 Sinks"},
    {"name": "Turn on a Radio"},
    {"name": "Turn on both Faucets"},
    {"name": "Turn on the Fountain"},
    {"name": "Turn on the Guitar Amp"},
    {"name": "Turn on the Vacuum Cleaner"},
    {"name": "Ignite a Gasoline Drum"},
    {"name": "Blend in as Groundskeeper"},
    {"name": "Blend in as Hotel Staff"},
    {"name": "Blend in as Recording Crew"},
    {"name": "Pacify someone with a Piano"},
    {"name": "Pacify someone with a the Baseball Bat"},
    {"name": "Pacify someone with the Police Baton"},
    {"name": "Pacify someone with the Shovel"},
    {"name": "Examine a Manager Note"},
    {"name": "Examine the Exterminator's Schedule"},
    {"name": "Examine the Guest List"},
    {"name": "Blow up a Propane Flask"},
    {"name": "Poison a Sample Dish"},
    {"name": "Poison Jordan's Bottle of Beer"},
    {"name": "Poison the Birthday Cake"},
    {"name": "Put the Katana in the Recording Booth"},
    {"name": "Throw the Sapper's Axe into the River"}
]
