//Hitman 3: Colorado Freedom Fighters
//Version 1.0
//By Providence Community
bingoGenerator = require("./generators/generator_bases/simple_generator.js");
var bingoList = [{"name": "Become an Explosive Specialist"},
{"name": "Become a Hacker"},
{"name": "Become the Militia Cook"},
{"name": "Become a Militia Elite"},
{"name": "Become a Militia Soldier"},
{"name": "Become a Militia Spec Ops"},
{"name": "Become a Militia Technician"},
{"name": "Become the Point Man"},
{"name": "Become the Scarecrow"},
{"name": "Collect 2 Bricks"},
{"name": "Collect 2 Crowbars"},
{"name": "Collect 2 Hammers"},
{"name": "Collect 2 Kitchen Knives"},
{"name": "Collect 2 Wrenches"},
{"name": "Collect 3 Screwdrivers"},
{"name": "Collect 4 Nitroglycerins"},
{"name": "Collect 4 Soda Cans"},
{"name": "Collect 5 Apricots"},
{"name": "Collect a Pistol"},
{"name": "Collect Rose's Room Key"},
{"name": "Collect the Baseball"},
{"name": "Collect the Branding Iron"},
{"name": "Collect the Cowboy Bust"},
{"name": "Collect the Explosive Watch Battery"},
{"name": "Collect the Garage Key"},
{"name": "Collect the Hacker's Phone"},
{"name": "Collect the Hallucinogenic Drugs"},
{"name": "Collect the Interpol Badge"},
{"name": "Collect the Quad Bike Keys"},
{"name": "Conceal an item in the Briefcase"},
{"name": "Drop the Car Lift"},
{"name": "Fire the Battering Ram"},
{"name": "Hide someone in a Hay Baler"},
{"name": "Overdose the Prisoner"},
{"name": "Peep through the Peep Hole"},
{"name": "Scan Rose's Face"},
{"name": "Start 2 Forklift Alarms"},
{"name": "Turn off 2 Fuseboxes"},
{"name": "Turn on 2 Faucets"},
{"name": "Turn on 2 Generators"},
{"name": "Turn on 2 Sinks"},
{"name": "Turn on the TV"},
{"name": "Drop the Chandelier"},
{"name": "Release the Haybale Winch manually"},
{"name": "Ignite a Gasoline Drum"},
{"name": "Blend in as Explosive Specialist"},
{"name": "Blend in as Militia Technician"},
{"name": "Pacify someone with the Baseball Bat"},
{"name": "Pacify someone with the Lead Pipe"},
{"name": "Pacify someone with the Mannequin Arm"},
{"name": "Blow up 2 Gas Canisters"},
{"name": "Blow up a Fire Extinguisher"},
{"name": "Blow up a Super Spicy Taco Van"},
{"name": "Blow up both Gas Heater Lamps"},
{"name": "Poison a Plate of Food"},
{"name": "Poison Maya's Water Bottle"},
{"name": "Poison Penelope's Water Bottle"},
{"name": "Poison the Point Man's Water Bottle"},
{"name": "Put the Old Axe in the Greenhouse"},
{"name": "Throw a Coin in the Well"},
{"name": "Throw a Shovel in the Tar Pit"},
{"name": "Throw the Baseball Bat into the River"},
{"name": "Throw the Cleaver in the River"}]
