//Hitman 3: Haven Island Last Resort
//Version 1.0
//By Providence Community
bingoGenerator = require("./generators/generator_bases/simple_generator.js");
var bingoList = [{"name": "Become the Boat Captain"},
{"name": "Become a Bodyguard"},
{"name": "Become the Butler"},
{"name": "Become a Chef"},
{"name": "Become the Doctor"},
{"name": "Become a Life Guard"},
{"name": "Become the Masseur"},
{"name": "Become a Resort Guard"},
{"name": "Become a Restort Staff"},
{"name": "Become the Snorkel Instructor"},
{"name": "Become a Tech Crew"},
{"name": "Become a Villa Guard"},
{"name": "Become a Villa Staff"},
{"name": "Become a Waiter"},
{"name": "Equip the Gas Suit"},
{"name": "Collect 2 Apples"},
{"name": "Collect 2 Bananas"},
{"name": "Collect 2 Doubloons"},
{"name": "Collect 2 Emetic Poisonous Flowers"},
{"name": "Collect 2 Fish"},
{"name": "Collect 2 Hammers"},
{"name": "Collect 2 Screwdrivers"},
{"name": "Collect 2 Seashells"},
{"name": "Collect 2 Starfish"},
{"name": "Collect 2 Wrenches"},
{"name": "Collect 3 Blueberry Muffins"},
{"name": "Collect 7 Coconuts"},
{"name": "Collect a Cheeseburger"},
{"name": "Collect a Gold Idol"},
{"name": "Collect a Haven Villa Key"},
{"name": "Collect a pair of Scissors"},
{"name": "Collect a Remote Explosive"},
{"name": "Collect a Speedboat Key"},
{"name": "Collect a Staff Area Key"},
{"name": "Collect a Stethoscope"},
{"name": "Collect a Water Scooter Key"},
{"name": "Collect an Iron"},
{"name": "Collect an Underground Facility Keycard"},
{"name": "Collect both Lead Pipes"},
{"name": "Collect both Lethal Poisonous Frogs"},
{"name": "Collect both Pearls"},
{"name": "Collect Partial Treasure Map - Island"},
{"name": "Collect Partial Treasure Map - Palm Tree"},
{"name": "Collect Partial Treasure Map - Skull"},
{"name": "Collect the Baseball"},
{"name": "Collect the Cleaver"},
{"name": "Collect the Feather Duster"},
{"name": "Collect the Folding Knife"},
{"name": "Collect the Imperial Filigree Egg"},
{"name": "Collect the Internal Haven Report"},
{"name": "Collect the Kitchen Knife"},
{"name": "Collect the Lethal Poison Pill Jar"},
{"name": "Collect the Letter Opener"},
{"name": "Collect the Lion Fish Hut Key"},
{"name": "Collect the Manta Ray Hut Key"},
{"name": "Collect the Meaty Bone"},
{"name": "Collect the Medical Cabinet Key"},
{"name": "Collect the Newspaper"},
{"name": "Collect the Rat Poison"},
{"name": "Collect the Scalpel"},
{"name": "Collect the USB Flash Drive"},
{"name": "Buy a Can of Soda"},
{"name": "Conceal an item in the Briefcase"},
{"name": "Conceal the Hatchet in a Crab Hole"},
{"name": "Interact with a Radio"},
{"name": "Interact with a Surveillance Footage"},
{"name": "Open an Escape Hatch from either side"},
{"name": "Pull the Book to open the Secret Door"},
{"name": "Remove the Safety Pin on 2 Trapdoors"},
{"name": "Repair the Jacuzzi Power Supply"},
{"name": "Turn off the Generator"},
{"name": "Turn off the Projector"},
{"name": "Turn off the Sound System"},
{"name": "Turn off the Ventilation"},
{"name": "Turn off two Fuseboxes"},
{"name": "Turn on 2 TVs"},
{"name": "Turn on 3 Sinks"},
{"name": "Turn on a Motor"},
{"name": "Turn on the Gramophone"},
{"name": "Turn on the Vacuum Cleaner"},
{"name": "Turn on two Faucets"},
{"name": "Turn on two Ice Machines"},
{"name": "Unplug all 4 Server Racks"},
{"name": "Drop 2 Flower Pots"},
{"name": "Drop a Chandelier"},
{"name": "Drop 2 Loudspeakers"},
{"name": "Overflow the Fish Tank manually"},
{"name": "Puncture a Water Cooler"},
{"name": "Blend in as a Waiter"},
{"name": "Pacify someone with a Frying Pan"},
{"name": "Pacify someone with a Golf Club"},
{"name": "Pacify someone with a Kettlebell"},
{"name": "Pacify someone with a Shovel"},
{"name": "Pacify someone with a Wet Floor Sign"},
{"name": "Pacify someone with the Baseball Bat"},
{"name": "Pacify someone with the Police Baton"},
{"name": "Blow up 2 Scooters"},
{"name": "Blow up a Propane Flask"},
{"name": "Poison Jason Portman's Beer"},
{"name": "Poison Ljudmila Vetrova's Dish"},
{"name": "Poison someone with the Emetic Syringe"},
{"name": "Poison the Breathing Apparatus"},
{"name": "Poison Tyson Williams' Medicine"},
{"name": "Knock someone down with a Muffin"},
{"name": "Knock someone down with an Apple"},
{"name": "Make someone slip on a Banana"},
{"name": "Throw a Fish into a Swimming Pool"},
{"name": "Throw the Fire Axe into the Ocean"},
{"name": "Trigger the Bird Cage"}]
