//Hitman 3: Berlin Apex Predator
//Version 1.0
//By Providence Community
bingoGenerator = require("./generators/generator_bases/simple_generator.js");
var bingoList = [
    {"name": "Become a Bartender"},
    {"name": "Become a Biker"},
    {"name": "Become a Club Crew"},
    {"name": "Become a Club Security"},
    {"name": "Become a DJ"},
    {"name": "Become a Technician"},
    {"name": "Become Rolf Hirschmüller"},
    {"name": "Become the Dealer"},
    {"name": "Become the Delivery Guy"},
    {"name": "Become the Florida Man"},
    {"name": "Collect 2 Bird's Eggs"},
    {"name": "Collect 2 Coconuts"},
    {"name": "Collect 2 Crowbars"},
    {"name": "Collect 2 Hobby Knives"},
    {"name": "Collect 2 Kitchen Knives"},
    {"name": "Collect 2 Lead Pipes"},
    {"name": "Collect 2 Soda Cans"},
    {"name": "Collect 2 Spray Cans"},
    {"name": "Collect 2 Wrenches"},
    {"name": "Collect 3 Rat Poisons"},
    {"name": "Collect 3 Screwdrivers"},
    {"name": "Collect a Bag of 'Medicine' Pills"},
    {"name": "Collect a Club Keycard"},
    {"name": "Collect a Juice Bar Ticket"},
    {"name": "Collect a Technician's Note"},
    {"name": "Collect both Bags of Sugar"},
    {"name": "Collect both Bananas"},
    {"name": "Collect both Garden Forks"},
    {"name": "Collect both Hammers"},
    {"name": "Collect the Baseball"},
    {"name": "Collect the Food Delivery flyer"},
    {"name": "Collect the Insecticide"},
    {"name": "Collect the Modern Sedative Syringe"},
    {"name": "Collect the Motorcycle Key"},
    {"name": "Collect the Poisonous Mushroom"},
    {"name": "Collect the Pool Ball"},
    {"name": "Break open both Boxes with a Crowbar"},
    {"name": "Break the Board behind the Red Toilet"},
    {"name": "Call Montgomery to schedule a Meeting"},
    {"name": "Create an Oil Leak with a Wrench"},
    {"name": "Drop the Concrete Pipe manually"},
    {"name": "Fire Tremaine's sniper"},
    {"name": "Hide someone in the Incinerator"},
    {"name": "Open the Biker Garage Door manually"},
    {"name": "Photograph the Astral Graffiti"},
    {"name": "Ring the Doorbell as a Biker"},
    {"name": "Show a Juice Bar Ticket to the Bikers"},
    {"name": "Trigger the Climax"},
    {"name": "Turn off 2 Fuseboxes"},
    {"name": "Turn off both Generators"},
    {"name": "Turn on 3 Sinks"},
    {"name": "Turn on a Faucet"},
    {"name": "Turn on the Forklift Alarm"},
    {"name": "Turn on the Gramophone"},
    {"name": "Turn on the Rack Case"},
    {"name": "Turn on the Sprinkler Unit"},
    {"name": "Turn on the TV"},
    {"name": "Turn on the Wind-Up Toy"},
    {"name": "Drop 2 Bags of Bricks"},
    {"name": "Drop 3 Hanging Cubes"},
    {"name": "Start a Fire"},
    {"name": "Blend in as Biker"},
    {"name": "Blend in as Club Crew"},
    {"name": "Blend in as Technician"},
    {"name": "Pacify Agent Montgomery's Partner"},
    {"name": "Pacify someone with the Police Baton"},
    {"name": "Blow up the Delivery Guy's Scooter"},
    {"name": "Blow up the Gas Canister"},
    {"name": "Poison Lowenthal's Fast Food"},
    {"name": "Serve someone a poisoned drink"},
    {"name": "Knock someone down with the Muffin"},
    {"name": "Throw a Cocaine Brick into a Fan"}
];
