//Hitman 3: Mendoza Farewell
//Version 1.0
//By Providence Community
bingoGenerator = require("./generators/generator_bases/simple_generator.js");
var bingoList = [
    {"name": "Become a Bodyguard"},
    {"name": "Become a Gaucho"},
    {"name": "Become a Mercenary"},
    {"name": "Become a Providence Herald"},
    {"name": "Become a Waiter"},
    {"name": "Become a Winery Worker"},
    {"name": "Become the Lawyer"},
    {"name": "Become the Sommelier"},
    {"name": "Equip the free Wetsuit"},
    {"name": "Collect 2 Grape Knives"},
    {"name": "Collect 2 Rat Poisons"},
    {"name": "Collect 2 Screwdrivers"},
    {"name": "Collect 2 Shears"},
    {"name": "Collect 2 Wrenches"},
    {"name": "Collect 3 Crowbars"},
    {"name": "Collect 3 Soda Cans"},
    {"name": "Collect 5 Bottles of the same Wine"},
    {"name": "Collect 5 Grapevines"},
    {"name": "Collect a Garden Fork"},
    {"name": "Collect a Security Keycard"},
    {"name": "Collect both Fuse Cells"},
    {"name": "Collect both Hobby Knives"},
    {"name": "Collect the 1945 Grand Paladin"},
    {"name": "Collect the Basement Key"},
    {"name": "Collect the Branson MD-2 Microphone"},
    {"name": "Collect the Calendar"},
    {"name": "Collect the Cocaine Brick"},
    {"name": "Collect the Combat Knife"},
    {"name": "Collect the Fish"},
    {"name": "Collect the Icicle"},
    {"name": "Collect the Imperial Filigree Egg"},
    {"name": "Collect the Kitchen Knife"},
    {"name": "Collect the Lethal Poison Pill Jar"},
    {"name": "Collect the Meaty Bone"},
    {"name": "Collect the Tier 1 Access Dongle"},
    {"name": "Collect the Violin"},
    {"name": "Collect Yates' Boat Key"},
    {"name": "Collect Yates' Car Key"},
    {"name": "Break the Wine Pump"},
    {"name": "Buy a Can of Soda"},
    {"name": "Close the Freezer Door"},
    {"name": "Conceal an item in the Toolbox"},
    {"name": "Detonate the Remote CX Demo Block MkIII"},
    {"name": "Dump a Propane Flask down the Shaft"},
    {"name": "Fire an Antique Cannon"},
    {"name": "Fire the Bartoli Woodsman sniper"},
    {"name": "Fire the Sieger 300 Tactical sniper"},
    {"name": "Hide someone in a Garden Shredder"},
    {"name": "Ignite the Asado Pit with a Torch"},
    {"name": "Increase the Voltage on the Regulator"},
    {"name": "Interact with 2 Radios"},
    {"name": "Open both Asado Grounds Windows"},
    {"name": "Open the Basement Safe"},
    {"name": "Produce Poison with the Distillation Kit"},
    {"name": "Scan 2 QR Codes"},
    {"name": "Start the Grape Presser"},
    {"name": "Trigger something on the Terminal"},
    {"name": "Turn on 2 Faucets"},
    {"name": "Turn on 2 Forklift Alarms"},
    {"name": "Turn on 3 Sinks"},
    {"name": "Turn on a Water Pump"},
    {"name": "Turn on the Frosted Glass"},
    {"name": "Turn on the Ice Machine"},
    {"name": "Turn on the Photocopier"},
    {"name": "Turn on the Vacuum Cleaner"},
    {"name": "Turn the Tap to open the Secret Door"},
    {"name": "Drop 2 Chandeliers"},
    {"name": "Drop 2 Hanging Plants"},
    {"name": "Puncture a Water Cooler"},
    {"name": "Puncture two Water Barrels"},
    {"name": "Start a Fire"},
    {"name": "Blend in as Waiter"},
    {"name": "Pacify someone with a Frying Pan"},
    {"name": "Pacify someone with the Fire Poker"},
    {"name": "Pacify someone with the Rake"},
    {"name": "Pacify someone with the Umbrella"},
    {"name": "Blow up a Gas Heater Lamp"},
    {"name": "Blow up the Gas Canister"},
    {"name": "Serve someone poisoned Wine"},
    {"name": "Knock someone down with an Apple"},
    {"name": "Make someone slip on a Banana"}
]
