//Hitman 3: Whittleton Creek Another Life
//Version 1.0
//By Providence Community
bingoGenerator = require("./generators/generator_bases/simple_generator.js");
var bingoList = [
    {"name": "Become a Cassidy Bodyguard"},
    {"name": "Become a Construction Worker"},
    {"name": "Become a Garbage Man"},
    {"name": "Become a Gardener"},
    {"name": "Become a Police Deputy"},
    {"name": "Become a Server"},
    {"name": "Become Gunther Mueller"},
    {"name": "Become James Batty"},
    {"name": "Become Janus' Bodyguard"},
    {"name": "Become Sheriff Masterson"},
    {"name": "Become Spencer Green"},
    {"name": "Become the Exterminator"},
    {"name": "Become the Mailman"},
    {"name": "Become the Nurse"},
    {"name": "Become the Plumber"},
    {"name": "Become the Real Estate Broker"},
    {"name": "Equip the Arkian Robes"},
    {"name": "Collect 10 Blueberry Muffins"},
    {"name": "Collect 2 Crowbars"},
    {"name": "Collect 2 Kitchen Knives"},
    {"name": "Collect 2 Rat Poisons"},
    {"name": "Collect 2 Screwdrivers"},
    {"name": "Collect 2 Wrenches"},
    {"name": "Collect 3 Baseballs"},
    {"name": "Collect a Pack of Cigarettes"},
    {"name": "Collect all 3 Apples"},
    {"name": "Collect Janus' Old Photograph"},
    {"name": "Collect the Battle Axe"},
    {"name": "Collect the Cigar Box"},
    {"name": "Collect the Hidden Microfilm"},
    {"name": "Collect the Lawsuit Documents"},
    {"name": "Collect the Lethal Poisonous Frog"},
    {"name": "Collect the Letter Opener"},
    {"name": "Collect the Rude Ruby pistol"},
    {"name": "Collect the Surveillance Tape"},
    {"name": "Collect the Vault Keycard"},
    {"name": "Collect the Wilsons' House Key"},
    {"name": "Block 2 Mole Holes"},
    {"name": "Break a Fire Hydrant with a Wrench"},
    {"name": "Detonate an Explosive Device"},
    {"name": "Hide someone in the Incinerator"},
    {"name": "Install the missing Propane for the Grill"},
    {"name": "Open a Manhole"},
    {"name": "Place a Muffin on Janus' Food Plate"},
    {"name": "Place the Cannabis Joint for Batty"},
    {"name": "Pour tea for Janus with the Samovar"},
    {"name": "Pull the Book to open the Secret Door"},
    {"name": "Retreive the Hatchet"},
    {"name": "Ring the Bell next to the Nurse"},
    {"name": "Turn on 3 Sinks"},
    {"name": "Turn on Janus' Gramophone"},
    {"name": "Turn on the Basement Sound System"},
    {"name": "Break Cassidy's Display Case"},
    {"name": "Drop all 3 Chandeliers"},
    {"name": "Blend in as Garbage Man"},
    {"name": "Blend in as Gardener"},
    {"name": "Pacify someone with a Golf Club"},
    {"name": "Pacify someone with the Lead Pipe"},
    {"name": "Pacify someone with the Paddle"},
    {"name": "Pacify someone with the Rake"},
    {"name": "Blow up a Fire Extinguisher"},
    {"name": "Blow up a Propane Flask"},
    {"name": "Blow up the Scooter"},
    {"name": "Knock someone down with a Muffin"},
    {"name": "Knock someone down with an Apple"},
    {"name": "Trigger the Singing Fish"}
];
