//Hitman 3: Isle of Sgail Ark Society
//Version 1.0
//By Providence Community
bingoGenerator = require("./generators/generator_bases/simple_generator.js");
var bingoList = [{"name": "Become a Castle Staff"},
{"name": "Become a Chef"},
{"name": "Become a Custodian"},
{"name": "Become a Guard"},
{"name": "Become a Raider"},
{"name": "Become an Architect"},
{"name": "Become an Ark Member"},
{"name": "Become an Elite Guard"},
{"name": "Become an Entertainer"},
{"name": "Become an Event Staff"},
{"name": "Become an Initiate"},
{"name": "Become the Butler"},
{"name": "Become the Master of Ceremonies"},
{"name": "Collect 2 Bricks"},
{"name": "Collect 2 Crowbars"},
{"name": "Collect 2 Rat Poisons"},
{"name": "Collect 2 Screwdrivers"},
{"name": "Collect 2 Soda Cans"},
{"name": "Collect 2 Wrenches"},
{"name": "Collect 3 Coconuts"},
{"name": "Collect a Basement Key"},
{"name": "Collect a Cannonball"},
{"name": "Collect a Chapel Key"},
{"name": "Collect a Cigar Box"},
{"name": "Collect a Hammer"},
{"name": "Collect a Kitchen Knife"},
{"name": "Collect a Membership Booklet"},
{"name": "Collect a Scissors"},
{"name": "Collect a Tower Key"},
{"name": "Collect both Apricots"},
{"name": "Collect Janus' Journal"},
{"name": "Collect Sophia's Newspaper Clipping"},
{"name": "Collect the Can of Spaghetti"},
{"name": "Collect the Cheeseburger"},
{"name": "Collect the Circumcision Knife"},
{"name": "Collect the Cleaver"},
{"name": "Collect the Cowboy Bust"},
{"name": "Collect the Dagger Acquisition Note"},
{"name": "Collect the ECT Device Safety Report"},
{"name": "Collect the Effigy Design Drawings"},
{"name": "Collect the Fish"},
{"name": "Collect the Hand Flare"},
{"name": "Collect the Hydraulic Door Safety Report"},
{"name": "Collect the Letter Opener"},
{"name": "Collect the List of Donations"},
{"name": "Collect the MoC's Schedule"},
{"name": "Collect the Newspaper"},
{"name": "Collect the Photo of Sophia and Blake"},
{"name": "Collect the Safe Combination Code"},
{"name": "Collect the Scalpel"},
{"name": "Collect the Wake Schedule"},
{"name": "Conceal an item in a Briefcase"},
{"name": "Knock the Door on the Courtyard Gate"},
{"name": "Overflow the Fish Tank manually"},
{"name": "Peep through a Peep Hole"},
{"name": "Push a Button to open a Secret Door"},
{"name": "Read the Files on the Constant's Laptop"},
{"name": "Signal the Harpist to Cue the Music"},
{"name": "Start the Forklift Alarm"},
{"name": "Tamper with a Toilet Control Panel"},
{"name": "Turn off 2 Fuseboxes"},
{"name": "Turn off a Rack Case"},
{"name": "Turn off the Alarm System"},
{"name": "Turn off the Hyperborean Model Lights"},
{"name": "Turn off the Server in the Ark Control Room"},
{"name": "Turn off the TV"},
{"name": "Turn on 2 Sinks"},
{"name": "Turn on a Boiler"},
{"name": "Turn on a Gramophone"},
{"name": "Turn on a Radio"},
{"name": "Turn on a Vacuum Cleaner"},
{"name": "Turn on the Faucet"},
{"name": "Turn on the Ice Machine"},
{"name": "Turn on the Music Box"},
{"name": "Break open 2 Ark Society Crates"},
{"name": "Drop 3 Chandeliers"},
{"name": "Drop down a Porticulis manually"},
{"name": "Puncture 2 Wine Barrels"},
{"name": "Puncture a Water Cooler"},
{"name": "Release a Winch manually"},
{"name": "Ignite a Gasoline Drum"},
{"name": "Blend in as Ark Member"},
{"name": "Blend in as Custodian"},
{"name": "Pacify someone with a Fire Poker"},
{"name": "Pacify someone with a Mace"},
{"name": "Pacify someone with the Frying Pan"},
{"name": "Pacify someone with the Torch"},
{"name": "Blow up a Bag of Gunpowder"},
{"name": "Blow up a Fire Extinguisher"},
{"name": "Blow up a Gas Canister"},
{"name": "Blow up a Gas Heater Lamp"},
{"name": "Blow up a Propane Flask"},
{"name": "Serve someone poisoned food"},
{"name": "Sedate someone with Chloroform"},
{"name": "Knock someone down with an Apple"},
{"name": "Knock someone down with the Muffin"}]
