//Hitman 3: Marrakech Gilded Cage
//Version 1.0
//By Providence Community
bingoGenerator = require("./generators/generator_bases/simple_generator.js");
var bingoList = [
{"name": "Become a Consulate Janitor"},
{"name": "Become a Consulate Security"},
{"name": "Become a Food Vendor"},
{"name": "Become a Handyman"},
{"name": "Become a Local Printing Crew"},
{"name": "Become a Military Officer"},
{"name": "Become a Military Soldier"},
{"name": "Become a Shopkeeper"},
{"name": "Become a Waiter"},
{"name": "Become an Elite Soldier"},
{"name": "Become the Headmaster"},
{"name": "Become the Masseur"},
{"name": "Become the Prisoner"},
{"name": "Collect 2 Cleavers"},
{"name": "Collect 2 Crowbars"},
{"name": "Collect 2 Hammers"},
{"name": "Collect 2 Pool Balls"},
{"name": "Collect 2 Rat Poisons"},
{"name": "Collect 2 Scissors"},
{"name": "Collect 2 Screwdrivers"},
{"name": "Collect 2 Wrenches"},
{"name": "Collect 3 Bricks"},
{"name": "Collect 3 Kitchen Knives"},
{"name": "Collect 3 Remote Explosives"},
{"name": "Collect 3 Toy Tanks"},
{"name": "Collect a Consulate Keycard"},
{"name": "Collect a Lethal Poison Pill Jar"},
{"name": "Collect an Army Truck Key"},
{"name": "Collect the Consulate Staff Car Key"},
{"name": "Collect the Headmaster Key"},
{"name": "Collect the Letter Opener"},
{"name": "Buy a Can of Soda"},
{"name": "Call Reza with 'Cherry Blossom'"},
{"name": "Call the Consul with 'Honeycomb'"},
{"name": "Conceal an item in the Briefcase"},
{"name": "Dismiss 3 Elite Soldiers"},
{"name": "Kick down the Toilet"},
{"name": "Peep through 2 Peep Holes"},
{"name": "Place an Explosive in the Camera"},
{"name": "Sabotage a Phonebooth"},
{"name": "Sabotage the Stage Lamp manually"},
{"name": "Show an Invitation to the Bodyguard"},
{"name": "Turn off both Generators"},
{"name": "Turn off the Fusebox in the School"},
{"name": "Turn off the Oil Lamp"},
{"name": "Turn off the Sound System"},
{"name": "Turn on 2 Sinks"},
{"name": "Turn on both Photocopiers"},
{"name": "Turn on both Vacuum Cleaners"},
{"name": "Turn on the Faucet"},
{"name": "Turn on the Ice Machine"},
{"name": "Turn on the School Intercom"},
{"name": "Turn on the Stage Lamp"},
{"name": "Turn on the TV"},
{"name": "Wake up the Waiter with the Radio"},
{"name": "Release the Moose manually"},
{"name": "Shoot down the Cafe Sign"},
{"name": "Ignite a Gasoline Drum"},
{"name": "Blend in as Consulate Janitor"},
{"name": "Blend in as Elite Soldier"},
{"name": "Blend in as Food Vendor"},
{"name": "Examine the Evacuation Plan"},
{"name": "Examine the Printing Schedule"},
{"name": "Examine the Tablet Computer"},
{"name": "Blow up 2 Gas Canisters"},
{"name": "Blow up a Fire Extinguisher"},
{"name": "Blow up a Propane Flask"},
{"name": "Poison a Shisha Pipe"},
{"name": "Poison Reza's Plate of Food"},
{"name": "Poison the Glass in Strandberg's Office"},
{"name": "Fire a Tactical Bartoli shotgun"}
]
