//Hitman 3: Paris Showstopper
//Version 1.0
//By Providence Community
bingoGenerator = require("./generators/generator_bases/simple_generator.js");
var bingoList = [
    {"name": "Become a Chef"},
    {"name": "Become a CICADA Bodyguard"},
    {"name": "Become a Palace Staff"},
    {"name": "Become a Security Guard"},
    {"name": "Become a Stylist"},
    {"name": "Become a Tech Crew"},
    {"name": "Become an Auction Staff"},
    {"name": "Become Helmut Kruger"},
    {"name": "Become the Sheikh"},
    {"name": "Become the Vampire Magician"},
    {"name": "Collect 2 Busts"},
    {"name": "Collect 2 Crowbars"},
    {"name": "Collect 2 Hammers"},
    {"name": "Collect 2 Kitchen Knives"},
    {"name": "Collect 2 Lead Pipes"},
    {"name": "Collect 2 Letter Openers"},
    {"name": "Collect 2 Scissors"},
    {"name": "Collect 3 Rat Poisons"},
    {"name": "Collect 3 Screwdrivers"},
    {"name": "Collect 3 Wrenches"},
    {"name": "Collect Dalia's Laptop Dongle"},
    {"name": "Collect the Brick under the Barge"},
    {"name": "Collect the Cleaver"},
    {"name": "Collect the Palace Master Key"},
    {"name": "Collect the Remote Explosive"},
    {"name": "Collect the Sheikh's Bartoli pistol"},
    {"name": "Collect the Speedboat Key"},
    {"name": "Conceal an item in the Briefcase"},
    {"name": "Get frisked"},
    {"name": "Give the Lens to the Blogger"},
    {"name": "Release 2 Winches manually"},
    {"name": "Show an IAGO invitation to a Bodyguard"},
    {"name": "Trigger Code 17"},
    {"name": "Trigger the Fireworks"},
    {"name": "Turn off 2 Generators"},
    {"name": "Turn off a Fusebox"},
    {"name": "Turn on any 2 Radios"},
    {"name": "Turn on 2 Vacuum Cleaners"},
    {"name": "Turn on 3 Sinks"},
    {"name": "Turn on the Diorama"},
    {"name": "Turn on the Faucet"},
    {"name": "Break 3 Display Cases"},
    {"name": "Break the Vase"},
    {"name": "Start a Fire"},
    {"name": "Blend in as Auction Staff"},
    {"name": "Blend in as Bodyguard under the Pagoda"},
    {"name": "Blend in as Palace Staff"},
    {"name": "Blend in at the Auction as the Sheikh"},
    {"name": "Pacify someone with the Golf Club"},
    {"name": "Pacify someone with the Piano"},
    {"name": "Pacify someone with the Police Baton"},
    {"name": "Pacify the guard in the Voltaire Suite"},
    {"name": "Examine the Cocktail Recipe"},
    {"name": "Examine the Fireworks Schedule"},
    {"name": "Examine the Room Assignment Document"},
    {"name": "Examine the Stage Schedule"},
    {"name": "Blow up 2 Gas Heater Lamps"},
    {"name": "Blow up a Car"},
    {"name": "Blow up a Fire Extinguisher"},
    {"name": "Blow up a Gas Canister"},
    {"name": "Blow up a Propane Flask"},
    {"name": "Poison a Sushi Plate"},
    {"name": "Poison Dalia's drink on the Balcony"},
    {"name": "Poison Sebastian Sato's glass"},
    {"name": "Put a Hatchet on the Catwalk"},
    {"name": "Put a Saber on the Sheikh's Bed"}
];
