bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
{"name": "Bell Beast"},
{"name": "Broodmother"},
{"name": "Cogwork Dancers"},
{"name": "Crawfather"},
{"name": "Disgraced Chef Lugoli"},
{"name": "Father of the Flame"},
{"name": "First Sinner"},
{"name": "Forebrothers Signis & Gron"},
{"name": "Fourth Chorus"},
{"name": "Garmond & Zaza"},
{"name": "Grand Mother Silk"},
{"name": "Great Conchflies"},
{"name": "Groal the Great"},
{"name": "Lace 1"},
{"name": "Lace 2"},
{"name": "Last Judge"},
{"name": "Moorwing"},
{"name": "Moss Mother Refight"},
{"name": "Phantom"},
{"name": "Savage Beastfly 1"},
{"name": "Savage Beastfly 2"},
{ "name": "Skull Tyrant 1"},
{"name": "Skull Tyrant 2"},
{"name": "The Unravelled"},
{"name": "Trobbio"},
{"name": "Widow"},
{"name": "Move Flea Caravan to Greymoor"},
{"name": "Move Flea Caravan to Blasted Steps"},
{"name": "Obtain Reaper Crest"},
{"name": "Obtain Beast Crest"},
{"name": "Obtain Wanderer Crest"},
{"name": "Obtain Witch Crest"},
{"name": "Obtain Architect Crest"},
{"name": "Upgrade Hunter Crest"},
{"name": "Unlock Half the Bellway Stations (6)"},
{"name": "Unlock all Bellway Stations (12)"},
{"name": "Unlock Half the Ventrica Stations (4)"},
{"name": "Unlock all Ventrica Stations (7)"},
{"name": "Obtain 2 Extra Spools"},
{"name": "Obtain 3 Extra Spools"},
{"name": "Obtain 1 Extra Mask"},
{"name": "Obtain 2 Extra Mask"},
{"name": "Obtain Clawline"},
{"name": "Obtain Swift Step"},
{"name": "Obtain Cling Grip"},
{"name": "Obtain Needolin"},
{"name": "Obtain Drifter's Cloak"},
{"name": "Obtain Feydown Cloak"},
{"name": "Obtain Silkspear"},
{"name": "Obtain Thread Storm"},
{"name": "Obtain a Cross Stitch"},
{"name": "Obtain Sharpdart"},
{"name": "Obtain Rune Rage"},
{"name": "Obtain 1 Crafting Kit"},
{"name": "Obtain 2 Crafting Kit"},
{"name": "Obtain 1 Tool Pouch"},
{"name": "Obtain 2 Tool Pouch"},
{"name": "Obtain Architech's Melody"},
{"name": "Obtain Conductor's Melody"},
{"name": "Obtain Vaultkeeper's Melody"},
{"name": "Obtain 2nd Needle Upgrade"},
{"name": "Obtain 3rd Needle Upgrade"},
{"name": "Obtain Flea Brew + Phasmium Vial"},
{"name": "Obtain Straight Pin, Threefold Pin and Longpin"},
{"name": "Obtain Warding Bell and Magma Bell"},
{"name": "Obtain Multibinder and Injector Band"},
{"name": "Obtain Longclaw"},
{"name": "Obtain Tacks"},
{"name": "Obtain Silkspeed Anklets and Scuttlebrace"},
{"name": "Obtain Hornet Statuette"},
{"name": "Obtain a Bellhome"},
{"name": "Deliver Pilgrim's Rest Supplies"},
{"name": "Save Sherma in Whiteward"}
];