bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Collect 5 Metal Flowers",
    "Collect 10 Metal Flowers",
    "Collect 3 Banuk Figures",
    "Collect 3 Vantage Points",
    "Collect 5 Vantage Points",
    "Get 10 Bluegleam",
    "Get 20 Bluegleam",
    "Collect 2 Ancient Vessels",
    "Collect 6 Ancient Vessels",
    "Clear 3 Corruption Zones",
    "Clear 6 Corruption Zones",
    "Clear a Bandit Camp",
    "Clear 3 Bandit Camps",
    "Clear SIGMA Cauldron",
    "Clear RHO Cauldron",
    "Clear XI Cauldron",
    "Clear ZETA Cauldron",
    "Override 1 Tallneck",
    "Override 3 Tallnecks",
    "Collect 3 Pigments",
    "Collect 6 Pigments",
    "Don't Fast Travel",
    "Don't Override Machines",
    "Kill 4 Bellowbacks",
    "Kill a Rockbreaker",
    "Override 2 Stormbirds",
    "Kill 2 Stormbirds",
    "Kill 6 snapmaws",
    "Override 2 Thunderjaws",
    "Kill 2 Thunderjaws",
    "Collect 2 Powercells",
	"Collect All Rising Suns from a Hunting Ground",
	"Finish 'In Her Mother's Footsteps' Sidequest",
    "Finish 'Acquired Taste' Sidequest",
    "Finish 'Fatal Inheritance' Sidequest",
	"Finish 'Insult to Injury' Sidequest"
];
