bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
  { name: "Kill vek with self-pull" },
  { name: "Shoot cryo 4 times 1 region" },
  { name: "Gain no reputation 1 island" },
  { name: "No mech/bldg dmg 1 region" },
  { name: "Death Skip 1 island" },
  { name: "Beat game no weapon cores" },
  { name: "Drown 3 vek in 1 region" },
  { name: "Fully charge Prime weapon" },
  { name: "Use 3 ice mech 1 island" },
  { name: "Kill 6 vek w/land mines" },
  { name: "Kill all goos" },
  { name: "Freeze all bldg 1 region" },
  { name: "Burn all bldg 1 region" },
  { name: "Beat game destroy timepods" },
  { name: "Pilot to max level" },
  { name: "Block 4 vek in 1 turn" },
  { name: "Kill 2 vek w/island tanks" },
  { name: "1 island primes only" },
  { name: "1 island brutes only" },
  { name: "1 island ranged only" },
  { name: "1 island science only" },
  { name: "Beat game keep grid over 3" },
  { name: "Teleport vek 4 tiles" },
  { name: "Survive region with 1 grid" },
  { name: "No direct dmg/fire 1 region" },
  { name: "Kill vek with train" },
  { name: "Kill vek with satellite" },
  { name: "Kill all vek w/mtn disposal" },
  { name: "Complete a perfect island" },
  { name: "Complete island no mech dmg" },
  { name: "Earn or buy 10 grid 1 island" },
  { name: "Earn 9 reputation 1 island" },
  { name: "Grid resist to 30%" },
  { name: "Beat the game on Hard" },
  { name: "Fill all 6 weapon slots" },
  { name: "Kill 6 vek 1 turn" },
  { name: "Beat game no pilots/secret sq" },
  { name: "Resist grid 3x 1 region" },
  { name: "Beat game destroy bomb" },
  { name: "Collect 4 timepods" },
];
