bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Break all Cracked Walls in Art Exhibit (1)",
    "Break all Cracked Walls in Boiling Grave (2)",
    "Break all Cracked Walls in Flooded Basement (2)",
    "Break all Cracked Walls in Grand Library (4)",
    "Break all Cracked Walls in Pillow Fort (1)",
    "Break all Cracked Walls in Potassium Mine (2)",
    "Break all Cracked Walls in Sand Castle (2)",
    "Break all Cracked Walls in Trash Cave (2)",
    "Change an Outfit in Changing Tent",
    "Clear Art Exhibit of all pre-boss Chests (2)",
    "Clear Boiling Grave of all pre-boss Chests (2)",
    "Clear Dark Hypostyle of all pre-boss Chests (2)",
    "Clear Flooded Basement of all pre-boss Chests (2)",
    "Clear Grand Library of all pre-boss Chests (3)",
    "Clear Machine Fortress of all pre-boss Chests (3)",
    "Clear Pillow Fort of all pre-boss Chests (2)",
    "Clear Potassium Mine of all pre-boss Chests (2)",
    "Clear Sand Castle of all pre-boss Chests (2)",
    "Clear Sunken Labyrinth of all pre-boss Chests (2)",
    "Clear Tomb of Simulacrum of all pre-boss Chests (2)",
    "Clear Trash Cave of all pre-boss Chests (2)",
    "Complete Art Exhibit",
    "Complete Boiling Grave",
    "Complete Dark Hypostyle",
    "Complete Flooded Basement",
    "Complete Grand Library",
    "Complete Machine Fortress",
    "Complete Pillow Fort",
    "Complete Potassium Mine",
    "Complete Sand Castle",
    "Complete Sunken Labyrinth",
    "Complete Tomb of Simulacrum",
    "Complete Trash Cave",
    "Die in Snowboarding Minigame",
    "Die to Lava",
    "Die to Spikebun (any)",
    "Die to Spikes",
    "Die to a Bee (any)",
    "Die to a Boss (any)",
    "Die to a Construct (any)",
    "Die to a Feral Gate (any)",
    "Die to a Hexrot (any)",
    "Die to a Jelly (any)",
    "Die to a Jenny (any)",
    "Die to a Roger (any)",
    "Die to a Snake (any)",
    "Die to a Turnip (any)",
    "Die to a Void",
    "Die to a Whirlpool",
    "Die to an Enemy (any)",
    "Get 3 Portal World Scrolls",
    "Get 3 Secret Cave Scrolls",
    "Get Amulet I",
    "Get Amulet II",
    "Get Amulet III",
    "Get Art Gallery",
    "Get Coast Crayon",
    "Get Coast Outfit",
    "Get Dynamite I",
    "Get Dynamite II",
    "Get Dynamite III",
    "Get EFCS",
    "Get Fancy Crayon",
    "Get Fancy Outfit",
    "Get Fire Mace",
    "Get Fire Sword",
    "Get Fluffy Crayon",
    "Get Fluffy Outfit",
    "Get Force Wand I",
    "Get Force Wand II",
    "Get Force Wand III",
    "Get Frozen Crayon",
    "Get Frozen Outfit",
    "Get Headband I",
    "Get Headband II",
    "Get Headband III",
    "Get Ice Ring I",
    "Get Ice Ring II",
    "Get Ice Ring III",
    "Get Lonely Crayon",
    "Get Lonely Outfit",
    "Get Pepperpain Crayon",
    "Get Pepperpain Outfit",
    "Get Secret Art Gallery",
    "Get Slope Crayon",
    "Get Slope Outfit",
    "Get Star Crayon",
    "Get Star Outfit",
    "Get Tippsie's Hint in the Abandoned House",
    "Get Tome I",
    "Get Tome II",
    "Get Tome III",
    "Get Tracker I",
    "Get Tracker II",
    "Get Tracker III",
    "Get a Blue Heart Pickup",
    "Get a Cold Debuff",
    "Get a Dire Hit Buff",
    "Get a Forbidden Key",
    "Get a Fragile Debuff",
    "Get a Lightning Pickup",
    "Get a Mighty Buff",
    "Get a Red Heart Pickup",
    "Get a Stunned Debuff",
    "Get a Tough Buff",
    "Get a Weak Debuff",
    "Get a Yellow Heart Pickup",
    "Get all Coast Lock Picks",
    "Get all Coast Shards",
    "Get all Fancy Lock Picks",
    "Get all Fancy Shards",
    "Get all Fluffy Lock Picks",
    "Get all Fluffy Shards",
    "Get all Frozen Lock Picks",
    "Get all Frozen Shards",
    "Get all Keys in Art Exhibit (4)",
    "Get all Keys in Boiling Grave (5)",
    "Get all Keys in Dark Hypostyle (6)",
    "Get all Keys in Flooded Basement (5)",
    "Get all Keys in Grand Library (8)",
    "Get all Keys in Machine Fortress (5)",
    "Get all Keys in Pillow Fort (2)",
    "Get all Keys in Potassium Mine (5)",
    "Get all Keys in Sand Castle (2)",
    "Get all Keys in Sunken Labyrinth (3)",
    "Get all Keys in Tomb of Simulacrum (10)",
    "Get all Keys in Trash Cave (4)",
    "Get all Lonely Lock Picks",
    "Get all Lonely Shards",
    "Get all Pepperpain Lock Picks",
    "Get all Pepperpain Shards",
    "Get all Slope Lock Picks",
    "Get all Slope Shards",
    "Get all Star Lock Picks",
    "Get all Star Shards",
    "Hit the Apathetic Frog 100 times",
    "Kill 10 Cowbun",
    "Kill 10 Feral Gates (gray)",
    "Kill 10 Feral Gates (red)",
    "Kill 10 Hyperdusa",
    "Kill 10 Oglers",
    "Kill 10 Shellbun",
    "Kill 10 Skullnips",
    "Kill 15 Turnips (any kind)",
    "Kill 2 Flower Jennies",
    "Kill 2 Metal Turnips",
    "Kill 2 Oglers (large)",
    "Kill 2 Snakes (Lonely Road)",
    "Kill 3 Hermit Legs (Trash Cave)",
    "Kill 3 Jellies (red)",
    "Kill 3 Oglers (dark)",
    "Kill 3 Rotnips",
    "Kill 3 Spikebun (gold)",
    "Kill 5 Angry Bees",
    "Kill 5 Bunboys",
    "Kill 5 Candy Snakes",
    "Kill 5 Jenny Sharks (in water)",
    "Kill 5 Octacles",
    "Kill 5 Spikebun",
    "Kill 5 Swimmy Rogers",
    "Kill 5 Titans",
    "Kill 5 Volcanos",
    "Kill 7 Jellies (green)",
    "Kill 7 Stupid Bees",
    "Kill a 10 Fishbun",
    "Kill a Brutus",
    "Kill a Chilly Roger",
    "Kill a Construct Boris",
    "Kill a Construct Marina",
    "Kill a Construct Sam",
    "Kill a Hermit Legs",
    "Kill a Hermit Legs (Tomb of Simulacrum)",
    "Kill a Hexrot (fire)",
    "Kill a Hexrot (ice)",
    "Kill a Jenny Shark (out of water)",
    "Kill a Slayer Jenny",
    "Kill a Volcano (Potassium Mine)",
    "Kill a boss",
    "Kill a boss with only Force Wand",
    "Kill a boss with only Ice Ring",
    "Kill an Evil Easel",
    "Kill an Ice Turnip",
    "Kill the Yellow Turnip (Moon Garden)",
    "Open all Doors in Art Exhibit (14)",
    "Open all Doors in Boiling Grave (20)",
    "Open all Doors in Dark Hypostyle (14)",
    "Open all Doors in Flooded Basement (15)",
    "Open all Doors in Grand Library (23)",
    "Open all Doors in Machine Fortress (18)",
    "Open all Doors in Pillow Fort (5)",
    "Open all Doors in Potassium Mine (22)",
    "Open all Doors in Sand Castle (7)",
    "Open all Doors in Sunken Labyrinth (15)",
    "Open all Doors in Tomb of Simulacrum (41)",
    "Open all Doors in Trash Cave (15)",
    "Read Secret Sign in Frozen's Outfit Cave",
    "Read Secret Sign in Ludo City",
    "Read Secret Sign in Maze of Steel",
    "Read Secret Sign in Nowhere",
    "Read Secret Sign in Place From Younger Days"
];
