bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Art Exhibit's Dynamite Puzzle w/o Using Dynamite",
    "Autumn Climb Skip",
    "Boiling Grave Faster Key 1",
    "Boiling Grave Faster Key 2",
    "Boiling Grave Faster Key 3",
    "Break All Breakable Arts in Art Exhibit",
    "Break all Cracked Walls in Grand Library (4)",
    "Brutal Oasis Skip",
    "Clear 10 Houses (not caves)",
    "Clear 50 Caves (any)",
    "Clear all Caves",
    "Clear all Houses (not caves)",
    "Complete Dark Hypostyle",
    "Complete Grand Library",
    "Complete Machine Fortress",
    "Complete Sunken Labyrinth",
    "Complete Tomb of Simulacrum",
    "Destroy 10 Art Exhibits",
    "Destroy 100 Wooden Barrels",
    "Destroy 25 Different Ice Blocks",
    "Destroy 25 Different Metal Blocks",
    "Destroy 5 Different 1 Counter Blocks",
    "Destroy 5 Different 2 Counter Blocks",
    "Destroy 5 Different 3 Counter Blocks",
    "Destroy 5 Different 4 Counter Blocks",
    "Die to Stationary Spike Ball",
    "Die to Stationary Spikes",
    "Die to That Guy",
    "Die to a Construct Boris",
    "Die to a Construct Marina",
    "Die to a Construct Sam",
    "Die to a Dark Ogler",
    "Die to a Hexrot (fire)",
    "Die to a Hexrot (ice)",
    "Die to a Metal Hyperdusa",
    "Die to the Metal Jelly",
    "Do Fly Glitch At Least Once",
    "Early Tomb of Simulacrum",
    "Enter Every Room in Dark Hypostyle (23)",
    "Enter Every Room in Grand Library (31)",
    "Enter Every Room in Machine Fortress (18)",
    "Enter Every Room in Sunken Labyrinth (21)",
    "Enter Every Room in The Promised Remedy (19)",
    "Enter Every Room in Tomb of Simulacrum (43)",
    "Enter Lost City of Avlopp w/o Using Tunnel",
    "Enter all Transport Caves",
    "Escape a Boss Fight and Leave Dungeon During the Fight",
    "Farthest Shore Skip",
    "Find 25 Different Remarkables",
    "Find Find 10 Different Remarkables",
    "Flooded Basement Force+Ice Shortcut w/o Using any Items",
    "Get 2 Forbidden Keys",
    "Get 2 Raft Pieces",
    "Get 4 Forbidden Keys",
    "Get 4 Raft Pieces",
    "Get 6 Raft Pieces",
    "Get 8 Raft Pieces",
    "Get Dark Hypostyle Crayon",
    "Get Dynamite III",
    "Get EFCS",
    "Get Every Form of Ice Storage",
    "Get Fire Mace",
    "Get Force Wand III",
    "Get Grand Library Crayon",
    "Get Ice Cream Cone in Tomb of Simulacrum (yum!)",
    "Get Ice Ring III",
    "Get Loot",
    "Get Machine Fortress Crayon",
    "Get Pillow Fort Tracker w/o Moving Any Blocks",
    "Get Sand Castle Force Wand w/o Using a Key or Dynamite/Ice Ring",
    "Get Sunken Labyrinth Crayon",
    "Get Tomb of Simulacrum Crayon",
    "Get a Stun Debuff",
    "Get all Keys in Dark Hypostyle (6)",
    "Get all Keys in Grand Library (8)",
    "Get all Keys in Machine Fortress (5)",
    "Get all Keys in Sunken Labyrinth (3)",
    "Get all Keys in Tomb of Simulacrum (10)",
    "Get to Tomb of Simulacrum Map w/o Using Any Tunnels",
    "Grand Library Get Fire Mace w/o Using Chain",
    "Grand Library Open all Doors in the Main Hall w/o Fire Mace",
    "Kill 100 of One Type of Enemy",
    "Kill 25 Angry Bees",
    "Kill 25 Brutus",
    "Kill 25 Bunboys",
    "Kill 25 Candy Snakes",
    "Kill 25 Chilly Rogers",
    "Kill 25 Cowbun",
    "Kill 25 Dark Oglers",
    "Kill 25 Enemies by Reflecting Projectiles",
    "Kill 25 Enemies with Dynamite Only",
    "Kill 25 Enemies with Force Wand Only",
    "Kill 25 Enemies with Ice Ring Only",
    "Kill 25 Evil Easels",
    "Kill 25 Feral Gates (gray)",
    "Kill 25 Feral Gates (red)",
    "Kill 25 Fishbun",
    "Kill 25 Flower Jennies",
    "Kill 25 Hermit Legs (TC)",
    "Kill 25 Hermit Legs (ToS)",
    "Kill 25 Hyperdusas",
    "Kill 25 Ice Turnips",
    "Kill 25 Jellies (green)",
    "Kill 25 Jellies (red)",
    "Kill 25 Jenny Sharks (in water)",
    "Kill 25 Jenny Sharks (out of water)",
    "Kill 25 Metal Skullnips",
    "Kill 25 Octacles",
    "Kill 25 Oglers (large)",
    "Kill 25 Oglers (small)",
    "Kill 25 Rotnips",
    "Kill 25 Safety Jennies",
    "Kill 25 Shellbuns",
    "Kill 25 Skullnips (in lava)",
    "Kill 25 Skullnips (normal)",
    "Kill 25 Slayer Jennies",
    "Kill 25 Snakes",
    "Kill 25 Spikebuns (gold)",
    "Kill 25 Spikebuns (normal)",
    "Kill 25 Stupid Bees",
    "Kill 25 Swimmy Rogers",
    "Kill 25 Titans (any)",
    "Kill 25 Volcano Mining Carts",
    "Kill 25 Volcanoes",
    "Kill 4 Metal Skullnips",
    "Kill 5 Dark Oglers",
    "Kill 5 Titans (yellow)",
    "Kill Biadlo I",
    "Kill Biadlo II",
    "Kill Construct Boris 10 Times",
    "Kill Construct Marina 10 Times",
    "Kill Construct Sam 10 Times",
    "Kill Jenny I",
    "Kill Jenny II",
    "Kill Jenny III",
    "Kill Lenny I",
    "Kill Lenny II",
    "Kill Mechabun I",
    "Kill Mechabun II",
    "Kill Mechabun III",
    "Kill Passel",
    "Kill Simulacrum",
    "Kill That Guy",
    "Kill a Boss w/ Only Dynamite",
    "Kill a Boss w/ Only EFCS",
    "Kill a Boss w/ Only Force Wand",
    "Kill a Boss w/ Only Ice Ring",
    "Kill a Boss w/ Only Reflecting Projectiles",
    "Kill a Brutus with Dynamite Only",
    "Kill a Brutus with Force Wand Only",
    "Kill a Brutus with Ice Ring Only",
    "Kill a Bunboy with Only Dynamite",
    "Kill a Bunboy with Only Force Wand",
    "Kill a Bunboy with Only Ice Ring",
    "Kill a Construct Boris",
    "Kill a Construct Boris with Only Dynamite",
    "Kill a Construct Boris with Only Force Wand",
    "Kill a Construct Boris with Only Ice Ring",
    "Kill a Construct Marina",
    "Kill a Construct Marina with Only Dynamite",
    "Kill a Construct Marina with Only Force Wand",
    "Kill a Construct Marina with Only Ice Ring",
    "Kill a Construct Sam",
    "Kill a Construct Sam with Only Dynamite",
    "Kill a Construct Sam with Only Force Wand",
    "Kill a Construct Sam with Only Ice Ring",
    "Kill a Flower Jenny with Only Dynamite",
    "Kill a Flower Jenny with Only Force Wand",
    "Kill a Flower Jenny with Only Ice Ring",
    "Kill a Hermit Legs (ToS) with Only Dynamite",
    "Kill a Hermit Legs (ToS) with Only Force Wand",
    "Kill a Hermit Legs (ToS) with Only Ice Ring",
    "Kill a Hexrot (fire)",
    "Kill a Hexrot (fire) with Only Dynamite",
    "Kill a Hexrot (fire) with Only Force Wand",
    "Kill a Hexrot (fire) with Only Ice Ring",
    "Kill a Hexrot (ice)",
    "Kill a Hexrot (ice) with Only Dynamite",
    "Kill a Hexrot (ice) with Only Force Wand",
    "Kill a Hexrot (ice) with Only Ice Ring",
    "Kill a Rotnip with Only Dynamite",
    "Kill a Rotnip with Only Force Wand",
    "Kill a Rotnip with Only Ice Ring",
    "Kill a Slayer Jenny with Only Dynamite",
    "Kill a Slayer Jenny with Only Force Wand",
    "Kill a Slayer Jenny with Only Ice Ring",
    "Kill a Snake with Only Dynamite",
    "Kill a Snake with Only Force Wand",
    "Kill a Snake with Only Ice Ring",
    "Kill a Spikebun (gold) with Only Dynamite",
    "Kill a Spikebun (gold) with Only Force Wand",
    "Kill a Spikebun (gold) with Only Ice Ring",
    "Kill a Swimmy Roger with Only Dynamite",
    "Kill a Swimmy Roger with Only Force Wand",
    "Kill a Swimmy Roger with Only Ice Ring",
    "Kill all Enemies in Moon Garden 5 Times",
    "Kill all Enemies in Northern End 5 Times",
    "Kill all Enemies in Scrap Yard 5 Times",
    "Kill an Ice Turnip with Only Dynamite",
    "Kill an Ice Turnip with Only Force Wand",
    "Kill an Ice Turnip with Only Ice Ring",
    "Kill an Ogler (dark) with Only Dynamite",
    "Kill an Ogler (dark) with Only Force Wand",
    "Kill an Ogler (dark) with Only Ice Ring",
    "Kill an Ogler (large) with Only Dynamite",
    "Kill an Ogler (large) with Only Force Wand",
    "Kill an Ogler (large) with Only Ice Ring",
    "Lonely Road Skip",
    "Lost City of Avlopp Skip",
    "Maze of Steel Skip",
    "Moon Garden Skip",
    "Ocean Castle Skip",
    "Open 25 Gates",
    "Open Bee Chest (Machine Fortress)",
    "Open Empty Boss Key Chest (Grand Library)",
    "Open all Doors in Dark Hypostyle (14)",
    "Open all Doors in Grand Library (23)",
    "Open all Doors in Machine Fortress (18)",
    "Open all Doors in Sunken Labyrinth (15)",
    "Open all Doors in Tomb of Simulacrum (41)",
    "Open all Gates in Dark Hypostyle",
    "Open all Gates in Grand Library",
    "Open all Gates in Machine Fortress",
    "Open all Gates in Sunken Labryinth",
    "Open all Gates in Tomb of Simulacrum",
    "Painful Plain Skip",
    "Passel Puzzle/Combat Skips",
    "Pause in a Void",
    "Perform a Void Walk",
    "Perform an Ice Clip",
    "Potassium Mine Chain Skip",
    "Potassium Mine Faster Main Room Key",
    "Promenade Path Skip",
    "Push a Counter Block into a Void",
    "Read all Secret Signs in The Promised Remedy (7)",
    "Roll Down 2 Different Slopes Continuously for 5 Seconds",
    "Roll Down 25 Different Slopes",
    "Roll Past all 3 Octacles in South Star Woods",
    "Sand Castle's Force Puzzle w/o Using Force Wand",
    "Scrap Yard Skip",
    "Shoot a Fireball Through a Portal",
    "Solve an 8 Switch Puzzle (number)",
    "Talk to Jenny Berry in Fancy Ruins",
    "Talk to Jenny Berry in Fluffy Fields",
    "Talk to Jenny Berry in Frozen Court",
    "Talk to Jenny Berry in Pepperpain Prairie",
    "Talk to Jenny Berry in Slippery Slope",
    "Talk to Jenny Berry in Star Woods (North)",
    "Talk to Jenny Berry in Star Woods (South)",
    "Talk to Jenny Berry in Sweetwater Coast",
    "The Vault Skip",
    "Trash Cave Faster Key 1",
    "Trash Cave Faster Key 2",
    "Trash Cave Faster Key 3",
    "Trash Cave Room 2 Puzzle w/o Items",
    "Unlock 25 Combat/Puzzle Doors",
    "Unlock 25 Key Doors",
    "Use Blue Warp in Dark Hypostyle",
    "Use Blue Warp in Grand Library",
    "Use Blue Warp in Machine Fortress",
    "Use Blue Warp in Sunken Labyrinth",
    "Use Blue Warp in Tomb of Simulacrum",
    "Use Green Warp in Grand Library",
    "Use Green Warp in Tomb of Simulacrum",
    "Use Red Warp in Dark Hypostyle",
    "Use Red Warp in Grand Library",
    "Use Red Warp in Sunken Labyrinth",
    "Use Red Warp in Tomb of Simulacrum",
    "Use Yellow Warp in Dark Hypostyle",
    "Use Yellow Warp in Grand Library",
    "Use Yellow Warp in Sunken Labyrinth",
    "Use Yellow Warp in Tomb of Simulacrum",
    "Visit That Guy in Fancy Ruins",
    "Visit That Guy in Fluffy Fields Tunnel",
    "Visit That Guy in Frozen Court Tunnel",
    "Visit That Guy in Trash Cave",
    "Walk Through a Room with Disappearing Floors",
    "Wall of Text Skip"
];
