bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Activate all Overworld Portals",
    "Bet a Blue Heart Pickup",
    "Bounce Over Spikes with Force Wand",
    "Bounce Over Void with Force Wand",
    "Break 10 Bushes",
    "Break 10 Movable Blocks",
    "Break all Barrels in Staff Area Secret Room in Fluffy Fields",
    "Break all Cracked Walls in Art Exhibit (1)",
    "Break all Cracked Walls in Boiling Grave (2)",
    "Break all Cracked Walls in Flooded Basement (2)",
    "Break all Cracked Walls in Pillow Fort (1)",
    "Break all Cracked Walls in Potassium Mine (2)",
    "Break all Cracked Walls in Sand Castle (2)",
    "Break all Cracked Walls in Trash Cave (2)",
    "Change an Outfit in Changing Tent",
    "Clear 25 Caves (any)",
    "Clear 5 Houses (not caves)",
    "Clear all Scroll of Empty aves in Fancy Ruins (2)",
    "Clear all Scroll or Empty Caves in Fluffy Fields (12)",
    "Clear all Scroll or Empty Caves in Frozen Court (2)",
    "Clear all Scroll or Empty Caves in Lonely Road (6)",
    "Clear all Scroll or Empty Caves in Pepperpain Prairie (7)",
    "Clear all Scroll or Empty Caves in Slippery Slope (2)",
    "Clear all Scroll or Empty Caves in Star Woods (4)",
    "Clear all Scroll or Empty Caves in Sweetwater Coast (5)",
    "Complete Art Exhibit",
    "Complete Autumn Climb",
    "Complete Boiling Grave",
    "Complete Brutal Oasis",
    "Complete Farthest Shore",
    "Complete Flooded Basement",
    "Complete Former Colossus",
    "Complete Lost City of Avlopp",
    "Complete Maze of Steel",
    "Complete Moon Garden",
    "Complete Northern End",
    "Complete Ocean Castle",
    "Complete Painful Plain",
    "Complete Pillow Fort",
    "Complete Potassium Mine",
    "Complete Promenade Path",
    "Complete Sand Castle",
    "Complete Sand Crucible",
    "Complete Scrap Yard",
    "Complete The Vault",
    "Complete Trash Cave",
    "Complete Wall of Text",
    "Destroy 10 Ice Blocks",
    "Destroy 10 Metal Blocks",
    "Destroy 25 Wooden Barrels",
    "Destroy 5 Art Exhibits",
    "Destroy 5 Different Trash Cans",
    "Destroy Furniture in Cave in Pepperpain Prairie with Banana Loving Flower Jenny",
    "Destroy Furniture in House Just South of House on the Hill",
    "Destroy Furniture in House in East Sweetwater Coast",
    "Destroy Furniture in House in Fancy Ruins",
    "Destroy a 1 Counter Block",
    "Destroy a 2 Counter Block",
    "Destroy a 3 Counter Block",
    "Destroy a 4 Counter Block",
    "Destroy the Health Potion Bar in Staff Area of Fluffy Fields",
    "Die in Snowboarding Minigame",
    "Die to 10 Skullnips (in lava)",
    "Die to Floor Spikes",
    "Die to Jenny Flower in Lonely Road House",
    "Die to Lava",
    "Die to Spike Ball",
    "Die to a Bee Swarm",
    "Die to a Boss",
    "Die to a Bunboy",
    "Die to a Cactus (Environmental)",
    "Die to a Cannon",
    "Die to a Chilly Roger",
    "Die to a Feral Gate (gray)",
    "Die to a Feral Gate (red)",
    "Die to a Jelly (green)",
    "Die to a Jelly (red)",
    "Die to a Jenny Shark",
    "Die to a Laser",
    "Die to a Machine Gun",
    "Die to a Monochrome",
    "Die to a Snake",
    "Die to a Spectre",
    "Die to a Spikebun (gold)",
    "Die to a Spikebun (normal)",
    "Die to a Stupid Bee",
    "Die to a Swimmy Roger",
    "Die to a Turnip (gun)",
    "Die to a Turnip (lance)",
    "Die to a Turnip (normal)",
    "Die to a Void",
    "Die to a Whirlpool",
    "Die to an Angry Bee",
    "Die to an Enemy",
    "Die to the Yellow Roger (Moon Garden)",
    "Drop Dynamite into a Void",
    "Dynamite an Ice Block",
    "Enter Every Room in Art Exhibit (19)",
    "Enter Every Room in Boiling Grave (26)",
    "Enter Every Room in Flooded Basement (21)",
    "Enter Every Room in Pillow Fort (11)",
    "Enter Every Room in Potassium Mine (21)",
    "Enter Every Room in Sand Castle (11)",
    "Enter Every Room in Trash Cave (20)",
    "Enter Jenny Berry's House",
    "Explode a Force Wand Bubble",
    "Extinguish 3 Fires",
    "Fill all Overworld Map Sections",
    "Find 10 Different Remarkables",
    "Fire a Cannon",
    "Freeze 10 Enemies to Death",
    "Freeze a Dynamite",
    "Get 10 Shards",
    "Get 3 Outfits",
    "Get 5 Crayons",
    "Get 5 Scrolls",
    "Get Amulet I",
    "Get Amulet II",
    "Get Amulet III",
    "Get Art Exhibit Crayon",
    "Get Art Gallery",
    "Get Boiling Grave Crayon",
    "Get Chain I",
    "Get Chain II",
    "Get Chain III",
    "Get Dynamite I",
    "Get Dynamite II",
    "Get Fancy Ruins Crayon",
    "Get Fancy Ruins Outfit",
    "Get Fire Sword",
    "Get Flooded Basement Crayon",
    "Get Fluffy Fields Crayon",
    "Get Fluffy Fields Lock Pick",
    "Get Fluffy Fields Outfit",
    "Get Force Wand I",
    "Get Force Wand II",
    "Get Frozen Court Crayon",
    "Get Frozen Court Lock Pick",
    "Get Frozen Court Outfit",
    "Get Headband I",
    "Get Headband II",
    "Get Headband III",
    "Get Ice Ring I",
    "Get Ice Ring II",
    "Get Lonely Road Crayon",
    "Get Lonely Road Lock Pick",
    "Get Lonely Road Outfit",
    "Get Pepperpain Prairie Crayon",
    "Get Pillow Fort Crayon",
    "Get Potassium Mine Crayon",
    "Get Pushed Into Lava",
    "Get Pushed Into a Spike Pit",
    "Get Pushed Into a Void",
    "Get Sand Castle Crayon",
    "Get Secret Art Gallery",
    "Get Slipepry Slope Crayon",
    "Get Slippery Slope Outfit",
    "Get Smacked by a Chest",
    "Get Sound Test",
    "Get Star Woods Crayon",
    "Get Star Woods Outfit",
    "Get Sweetwater Coast Crayon",
    "Get Sweetwater Coast Lock Pick",
    "Get Sweetwater Coast Outfit",
    "Get Tippsie's Hint in the Abandoned House",
    "Get Tome I",
    "Get Tome II",
    "Get Tome III",
    "Get Tracker I",
    "Get Tracker II",
    "Get Tracker III",
    "Get Trash Cave Crayon",
    "Get a Cold Debuff",
    "Get a Dire Hit Buff",
    "Get a Fragile Debuff",
    "Get a Lightning Pickup",
    "Get a Mighty Buff",
    "Get a Red Heart Pickup",
    "Get a Tough Buff",
    "Get a Weak Debuff",
    "Get a Yellow Heart (Pickup or Chest)",
    "Get all Fancy Ruins Lock Picks (2)",
    "Get all Fancy Ruins Shards (5)",
    "Get all Fluffy Fields Shards (5)",
    "Get all Frozen Court Shards (4)",
    "Get all Ittle Remarkables in Art Exhibit (3)",
    "Get all Ittle Remarkables in Boiling Grave (2)",
    "Get all Ittle Remarkables in Flooded Basement (3)",
    "Get all Ittle Remarkables in Pillow Fort (3)",
    "Get all Ittle Remarkables in Potassium Mine (3)",
    "Get all Ittle Remarkables in Sand Castle (3)",
    "Get all Ittle Remarkables in Trash Cave (3)",
    "Get all Keys in Art Exhibit (4)",
    "Get all Keys in Boiling Grave (5)",
    "Get all Keys in Flooded Basement (5)",
    "Get all Keys in Pillow Fort (2)",
    "Get all Keys in Potassium Mine (5)",
    "Get all Keys in Sand Castle (2)",
    "Get all Keys in Trash Cave (4)",
    "Get all Lonely Road Shards (4)",
    "Get all Pepperpain Prairie Lock Picks (2)",
    "Get all Pepperpain Prairie Shards (5)",
    "Get all Slippery Slope Lock Picks (2)",
    "Get all Slippery Slope Shards (4)",
    "Get all Star Woods Lock Picks (2)",
    "Get all Star Woods Shards (5)",
    "Get all Sweetwater Coast Shards (4)",
    "Get an Ittle Remarkable in Fancy Ruins",
    "Get an Ittle Remarkable in Fluffy Fields",
    "Get an Ittle Remarkable in Frozen Court",
    "Get an Ittle Remarkable in Lonely Road",
    "Get an Ittle Remarkable in Pepperpain Prairie",
    "Get an Ittle Remarkable in Slippery Slope",
    "Get an Ittle Remarkable in Star Woods",
    "Get an Ittle Remarkable in Sweetwater Coast",
    "Help Lenny Clean",
    "Hit the Apathetic Frog 100 Times",
    "Kill 10 Cowbun",
    "Kill 10 Enemies with Dynamite Only",
    "Kill 10 Enemies with Force Wand Only",
    "Kill 10 Enemies with Ice Ring Only",
    "Kill 10 Feral Gates (gray)",
    "Kill 10 Feral Gates (red)",
    "Kill 10 Fishbun",
    "Kill 10 Hyperdusa",
    "Kill 10 Oglers (small)",
    "Kill 10 Safety Jennies",
    "Kill 10 Shellbun",
    "Kill 10 Skullnips",
    "Kill 10 Skullnips (in lava)",
    "Kill 10 Stupid Bees",
    "Kill 10 Turnips (gun)",
    "Kill 10 Turnips (lance)",
    "Kill 10 Turnips (normal)",
    "Kill 2 Flower Jennies",
    "Kill 2 Oglers (big)",
    "Kill 2 Snakes",
    "Kill 3 Hermit Legs (TC)",
    "Kill 3 Ice Turnips",
    "Kill 3 Jellies (red)",
    "Kill 3 Rotnips",
    "Kill 3 Spikebun (gold)",
    "Kill 5 Angry Bees",
    "Kill 5 Bunboys",
    "Kill 5 Candy Snakes",
    "Kill 5 Enemies by Reflecting Projectiles",
    "Kill 5 Jenny Sharks (in water)",
    "Kill 5 Jenny Sharks (out of water)",
    "Kill 5 Octacles",
    "Kill 5 Spikebun",
    "Kill 5 Swimmy Rogers",
    "Kill 5 Titans (gray)",
    "Kill 5 Titans (red)",
    "Kill 5 Volcano Mining Carts",
    "Kill 5 Volcanoes",
    "Kill 50 of One Type of Enemy",
    "Kill 7 Jellies (green)",
    "Kill a Boss in Art Exhibit",
    "Kill a Boss in Boiling Grave",
    "Kill a Boss in Flooded Basement",
    "Kill a Boss in Pillow Fort",
    "Kill a Boss in Potassium Mine",
    "Kill a Boss in Sand Castle",
    "Kill a Boss in Trash Cave",
    "Kill a Brutus",
    "Kill a Chilly Roger",
    "Kill a Slayer Jenny",
    "Kill an Evil Easel",
    "Kill any Boss",
    "Kill the Yellow Roger (Moon Garden)",
    "Light 5 Torches",
    "Light the Torch in Jenny Flower House in Lonely Road",
    "Open 10 Gates",
    "Open all Doors in Art Exhibit (14)",
    "Open all Doors in Boiling Grave (20)",
    "Open all Doors in Flooded Basement (15)",
    "Open all Doors in Pillow Fort (5)",
    "Open all Doors in Potassium Mine (22)",
    "Open all Doors in Sand Castle (7)",
    "Open all Doors in Trash Cave (15)",
    "Open all Gates in Art Exhibit",
    "Open all Gates in Boiling Grave",
    "Open all Gates in Flooded Basement",
    "Open all Gates in Pillow Fort",
    "Open all Gates in Potassium Mine",
    "Open all Gates in Sand Castle",
    "Open all Gates in Trash Cave",
    "Push 10 Different Movable Blocks",
    "Push a Movable Block into a Void",
    "Push an Ice Block into a Void",
    "Read Each Placard in Art Exhibit",
    "Read Secret Sign in Frozen Court Outfit Cave",
    "Read Secret Sign in Jenny Berry's House",
    "Read Secret Sign in Ludo City",
    "Read Secret Sign in Maze of Steel",
    "Read Secret Sign in Nowhere",
    "Read Secret Sign in Place From Younger Days",
    "Roll Continuously for 5 Seconds with a Single Roll",
    "Roll Down 10 Different Slopes",
    "Shoot Force Through a Portal",
    "Slice an Ice Block Through a Portal",
    "Slide a Dynamite Through a Portal",
    "Solve \"Rich\" Turnip's Bed Problem in House in Star Woods",
    "Solve a 1 Switch Puzzle (non-number)",
    "Solve a 2 Switch Puzzle (non-number)",
    "Solve a 2 Switch Puzzle (number)",
    "Solve a 3 Switch Puzzle (non-number)",
    "Solve a 3 Switch Puzzle (number)",
    "Solve a 4 Switch Puzzle (non-number)",
    "Solve a 4 Switch Puzzle (number)",
    "Solve a 5 Switch Puzzle (non-number)",
    "Stand in Art Exhibit Standee",
    "Stand in Fluffy Fields Standee",
    "Stand in Frozen Court Standee",
    "Stand in Lonely Road Standee",
    "Stand in Pepperpain Prairie Standee",
    "Stand in Slippery Slope Standee",
    "Stand in Sweetwater Coast Standee",
    "Start a File as Apathetic Frog",
    "Start a File as Jenny Berry",
    "Talk to Biadlo in Overworld",
    "Talk to Business Casual Man",
    "Talk to Jenny Berry in Lonely Road",
    "Talk to Jenny in Overworld",
    "Talk to Mapman in Fluffy Fields",
    "Talk to Mapman in Frozen Court",
    "Talk to Mapman in Lonely Road",
    "Talk to Mapman in Pepperpain Prairie",
    "Talk to Mapman in Slippery Slope",
    "Talk to Mapman in Star Woods",
    "Talk to Mapman in Sweetwater Coast",
    "Talk to Pizza Jenny in Trash Cave",
    "Talk to the 2 Hexrots in a Lonely Road Cave",
    "Talk to the 3 Jenny Cats in a Lonely Road Cave",
    "Talk to the 3 Rats in Staff Area of Fluffy Fields",
    "Talk to the 3 Relaxing Turnips in Pepperpain Prairie",
    "Touch all Checkpoints in the Overworld",
    "Unlock 10 Combat/Puzzle Doors",
    "Unlock 10 Green Doors or Crystals (or Gray Gates)",
    "Unlock 10 Key Doors",
    "Unlock 10 Red Doors, Gates, or Crystals",
    "Use Blue Warp in Art Exhibit",
    "Use Blue Warp in Boiling Grave",
    "Use Blue Warp in Flooded Basement",
    "Use Blue Warp in Potassium Mine",
    "Use Blue Warp in Trash Cave",
    "Use a Green Cube Portal",
    "Use a Green Portal Warp",
    "Watch the Cow Get Abducted",
    "Watch the Cowbun Explode",
    "Watch the Fishbun Explode",
    "Watch the Ogler Explode"
];
