bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "12 Dalmatians Collected",
    "12 Enemy Gummi Ship Blueprints",
    "16 Enemy Gummi Ship Blueprints",
    "2 Postcards",
    "2 Torn Pages",
    "20 Enemy Gummi Ship Blueprints",
    "21 Dalmatians Collected",
    "24 Enemy Gummi Ship Blueprints",
    "30 Dalmatians Collected",
    "4 Enemy Gummi Ship Blueprints",
    "4 Postcards",
    "4 Torn Pages",
    "42 Dalmatians Collected",
    "51 Dalmatians Collected",
    "6 Postcards",
    "60 Dalmatians Collected",
    "72 Dalmatians Collected",
    "8 Enemy Gummi Ship Blueprints",
    "8 Postcards",
    "81 Dalmatians Collected",
    "90 Dalmatians Collected",
    "All Blue Trinity Points",
    "All Chests Agrabah",
    "All Chests Atlantica",
    "All Chests Deep Jungle",
    "All Chests Destiny Island",
    "All Chests End of the World",
    "All Chests Halloween Town",
    "All Chests Hollow Bastion",
    "All Chests Monstro",
    "All Chests Never Land",
    "All Chests Olympus Coliseum",
    "All Chests Traverse Town",
    "All Chests Wonderland",
    "All Dalmatians Collected",
    "All Dalmatians from Agrabah",
    "All Dalmatians from Atlantica",
    "All Dalmatians from Deep Jungle",
    "All Dalmatians from Halloweentown",
    "All Dalmatians from Hollow Bastion",
    "All Dalmatians from Monstro",
    "All Dalmatians from Neverland",
    "All Dalmatians from Olympus Coliseum",
    "All Dalmatians from Traverse Town",
    "All Dalmatians from Wonderland",
    "All Enemy Gummi Ship Blueprints",
    "All Green Trinity Points",
    "All Keyholes",
    "All Postcards",
    "All Red Trinity Points",
    "All Torn Pages",
    "All Trinity Points in Agrabah",
    "All Trinity Points in Atlantica",
    "All Trinity Points in Deep Jungle",
    "All Trinity Points in Halloween Town",
    "All Trinity Points in Hollow Bastion",
    "All Trinity Points in Monstro",
    "All Trinity Points in Never Land",
    "All Trinity Points in Olympus Coliseum",
    "All Trinity Points in Traverse Town",
    "All Trinity Points in Wonderland",
    "All White Trinity Points",
    "All Yellow Trinity Points",
    "Beat 10 Gummi Missions",
    "Beat 15 Gummi Missions",
    "Beat 20 Gummi Missions",
    "Beat 25 Gummi Missions",
    "Beat 5 Gummi Missions",
    "Beat 50 Air Pirate",
    "Beat 50 Air Soldier",
    "Beat 50 Angel Star",
    "Beat 50 Aqua Tank",
    "Beat 50 Bandit",
    "Beat 50 Barrel Spider",
    "Beat 50 Battleship",
    "Beat 50 Bit Sniper",
    "Beat 50 Blue Rhapsody",
    "Beat 50 Bouncywild",
    "Beat 50 Darkball",
    "Beat 50 Defender",
    "Beat 50 Fat Bandit",
    "Beat 50 Gargoyle",
    "Beat 50 Green Requiem",
    "Beat 50 Invisible",
    "Beat 50 Large Body",
    "Beat 50 Pirate",
    "Beat 50 Pot Spider",
    "Beat 50 Powerwild",
    "Beat 50 Red Nocturne",
    "Beat 50 Screwdiver",
    "Beat 50 Sea Neon",
    "Beat 50 Search Ghost",
    "Beat 50 Shadow",
    "Beat 50 Sheltering Zone",
    "Beat 50 Soldier",
    "Beat 50 Wight Knight",
    "Beat 50 Wizard",
    "Beat 50 Wyvern",
    "Beat 50 Yellow Opera",
    "Beat Ansem I w/Kingdom Key",
    "Beat Ansem II w/Kingdom Key",
    "Beat Anti-Sora w/Kingdom Key",
    "Beat Captain Hook w/Kingdom Key",
    "Beat Cave of Wonders w/Kingdom Key",
    "Beat Chernabog w/Kingdom Key",
    "Beat Cloud Preliminary Cup",
    "Beat Final Ansem w/Kingdom Key",
    "Beat Glut (Shark) Twice",
    "Beat Hades Cup 10th Seed",
    "Beat Hades Cup 10th Seed Solo",
    "Beat Hades Cup 1st Seed",
    "Beat Hades Cup 1st Seed Solo",
    "Beat Hades Cup 20th Seed",
    "Beat Hades Cup 20th Seed Solo",
    "Beat Hades Cup 25th Seed",
    "Beat Hades Cup 25th Seed Solo",
    "Beat Hades Cup 30th Seed",
    "Beat Hades Cup 30th Seed Solo",
    "Beat Hades Cup 40th Seed",
    "Beat Hades Cup 40th Seed Solo",
    "Beat Hades Cup 44th Seed",
    "Beat Hades Cup 44th Seed Solo",
    "Beat Hades Cup Time Trial",
    "Beat Hercules Cup",
    "Beat Hercules Cup Solo",
    "Beat Hercules Cup Solo w/Kingdom Key",
    "Beat Hercules Cup Time Trial",
    "Beat Ice Titan",
    "Beat Ice Titan w/Kingdom Key",
    "Beat Kurt Zisa",
    "Beat Kurt Zisa w/Kingdom Key",
    "Beat Leon First District",
    "Beat Maleficent I w/Kingdom Key",
    "Beat Maleficent II w/Kingdom Key",
    "Beat Pegasus Cup",
    "Beat Pegasus Cup Solo",
    "Beat Pegasus Cup Solo w/Kingdom Key",
    "Beat Pegasus Cup Time Trial",
    "Beat Phantom",
    "Beat Phantom w/Kingdom Key",
    "Beat Phil Cup",
    "Beat Phil Cup Solo",
    "Beat Phil Cup Time Trial",
    "Beat Phil Cup solo w/Kingdom Key",
    "Beat Riku Destiny Islands",
    "Beat Riku-Ansem w/Kingdom Key",
    "Beat Rock Titan w/Kingdom Key",
    "Beat Sabor Three Times",
    "Beat Sabor Twice",
    "Beat Selphie",
    "Beat Sephiroth",
    "Beat Sephiroth w/Kingdom Key",
    "Beat Tidus",
    "Beat Tidus, Selphie, and Wakka",
    "Beat Unknown",
    "Beat Unknown w/Kingdom Key",
    "Beat Ursula 2 W/Kingdom Key",
    "Beat Wakka",
    "Beat all Gummi Missions",
    "Beat all World Terminus Points",
    "Bounce Rare Truffle 100 times",
    "Bounce Rare Truffle 50 times",
    "Collect 10 Treasure Chests",
    "Collect 100 Treasure Chests",
    "Collect 10000 Munny",
    "Collect 105 Treasure Chests",
    "Collect 110 Treasure Chests",
    "Collect 115 Treasure Chests",
    "Collect 120 Treasure Chests",
    "Collect 125 Treasure Chests",
    "Collect 130 Treasure Chests",
    "Collect 135 Treasure Chests",
    "Collect 140 Treasure Chests",
    "Collect 145 Treasure Chests",
    "Collect 15 Blazing Stones",
    "Collect 15 Dazzling Stone",
    "Collect 15 Energy Stones",
    "Collect 15 Frost Stones",
    "Collect 15 Fury Stones",
    "Collect 15 Lightning Stones",
    "Collect 15 Mythril Stones",
    "Collect 15 Power Stones",
    "Collect 15 Serenity Power",
    "Collect 15 Stormy Stones",
    "Collect 15 Treasure Chests",
    "Collect 150 Treasure Chests",
    "Collect 155 Treasure Chests",
    "Collect 160 Treasure Chests",
    "Collect 165 Treasure Chests",
    "Collect 170 Treasure Chests",
    "Collect 175 Treasure Chests",
    "Collect 180 Treasure Chests",
    "Collect 185 Treasure Chests",
    "Collect 190 Treasure Chests",
    "Collect 195 Treasure Chests",
    "Collect 2 pieces of evidence",
    "Collect 20 Treasure Chests",
    "Collect 200 Treasure Chests",
    "Collect 25 Treasure Chests",
    "Collect 3 pieces of evidence",
    "Collect 30 Treasure Chests",
    "Collect 35 Treasure Chests",
    "Collect 4 pieces of evidence",
    "Collect 40 Treasure Chests",
    "Collect 45 Treasure Chests",
    "Collect 50 Treasure Chests",
    "Collect 5000 Munny",
    "Collect 55 Treasure Chests",
    "Collect 60 Treasure Chests",
    "Collect 65 Treasure Chests",
    "Collect 70 Treasure Chests",
    "Collect 75 Treasure Chests",
    "Collect 80 Treasure Chests",
    "Collect 85 Treasure Chests",
    "Collect 90 Treasure Chests",
    "Collect 95 Treasure Chests",
    "Collect Claw Marks as one of your evidence",
    "Complete all Agrabah Gummi Missions",
    "Complete all Atlantica Gummi Missions",
    "Complete all Deep Jungle Gummi Missions",
    "Complete all End of the World Gummi Missions",
    "Complete all Halloween Town Gummi Missions",
    "Complete all Hollow Bastion Gummi Missions",
    "Complete all Monstro Gummi Missions",
    "Complete all NeverLand Gummi Missions",
    "Complete all Olympus Coliseum Gummi Missions",
    "Complete all Traverse Town Gummi Missions",
    "Complete all Wonderland Gummi Missions",
    "Complete charades with White Mushroom",
    "Get All Keyblades",
    "Get All Shields",
    "Get All Staves",
    "Get All Summons",
    "Get Bambi",
    "Get Dumbo",
    "Get Mushu",
    "Get the Mega Potion from Aeris",
    "Max Level Aero",
    "Max Level Blizzard",
    "Max Level Cure",
    "Max Level Fire",
    "Max Level Gravity",
    "Max Level Stop",
    "Max Level Tuinder",
    "Obtain Aerith Model",
    "Obtain Cactuar Model",
    "Obtain Chocobo Model",
    "Obtain Cid Model",
    "Obtain Geppetto Model",
    "Obtain Hyperion Model",
    "Obtain Leon Model",
    "Obtain Pinocchio Model",
    "Obtain Yuffie Model",
    "Reach Level 100",
    "Reach Level 25",
    "Reach Level 50",
    "Reach Level 75",
    "Synthesize AP Up",
    "Synthesize Angel Bangle",
    "Synthesize Atlas Armlet",
    "Synthesize Cosmic Arts",
    "Synthesize Cottage",
    "Synthesize Crystal Crown",
    "Synthesize Dark Matter",
    "Synthesize Dark Ring",
    "Synthesize Defense Up",
    "Synthesize EXP Bracelet",
    "Synthesize EXP Earring",
    "Synthesize Elixir",
    "Synthesize Energy Bangle",
    "Synthesize Fantasista",
    "Synthesize Gaia Bangle",
    "Synthesize Golem Chain",
    "Synthesize Guard Earring",
    "Synthesize Heartguard",
    "Synthesize Magic Armlet",
    "Synthesize Master Earring",
    "Synthesize Mega Ether",
    "Synthesize Mega Potion",
    "Synthesize Megalixir",
    "Synthesize Moogle Badge",
    "Synthesize Mythril",
    "Synthesize Power Chain",
    "Synthesize Power Up",
    "Synthesize Ribbon",
    "Synthesize Rune Armlet",
    "Synthesize Seven Elements",
    "Synthesize Three Stars",
    "Synthesize Titan Chain",
    "Synthesize Ultima Weapon",
    "Win Riku Race"
];
