bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "1 Ga-Spell",
    "1 Super Boss",
    "10 Chests in Neverland",
    "10 Postcards",
    "100 Hits on a Rare Truffle",
    "13 Unique Keyblades",
    "15 Chests in Agrabah",
    "15 Chests in Halloween Town",
    "15 Chests in Traverse Town",
    "15 Chests in Wonderland",
    "15000 Munny at One Time",
    "2+ Air Combo Plus",
    "2+ Combo Plus",
    "20 Chests in End of the World",
    "25 Chests in Hollow Bastion",
    "3 Different Mushroom Arts",
    "3 Ga-Spells",
    "3 Ra-Spells",
    "3 Unique EXP Items",
    "33 Puppies",
    "4 Post Cards",
    "5 Chests in World Terminus",
    "5 Different Mushroom Arts",
    "5 Ga-Spells",
    "5 Ra-Spells",
    "50 Hits on a Rare Truffle",
    "66 Puppies",
    "7 Post Cards",
    "7 Unique Keyblades",
    "99 Puppies",
    "Acquire Bambi",
    "Acquire Dumbo",
    "Acquire Genie",
    "Acquire Loggers",
    "Acquire Mushu",
    "Acquire Simba",
    "Acquire Tinker Bell",
    "Aeroga",
    "All 13 Ansem Reports",
    "All 3 Dream Weapons",
    "All Blue Trinities",
    "All Chests in Deep Jungle",
    "All Chests in Final Dimension",
    "All Chests in Giant Crevasse",
    "All Chests in Olympus",
    "All Chests in Traverse Town",
    "All Chests in Wonderland",
    "All Evidence Pieces",
    "All Ga-Spells",
    "All Green Trinities",
    "All Lift Stop Chests",
    "All Ra-Spells",
    "All Red Trinities",
    "All Summons",
    "All Trinities in Agrabah",
    "All Trinities in Deep Jungle",
    "All Trinities in Halloween Town",
    "All Trinities in Hollow Bastion",
    "All Trinities in Monstro",
    "All Trinities in Neverland",
    "All Trinities in Olympus Coliseum",
    "All Trinities in Traverse Town",
    "All Trinities in Wonderland",
    "All Trinity Checks",
    "All White Trinities",
    "All Yellow Trinities",
    "Any Ra-Spell",
    "Ars or Ragnarok",
    "Ars or Strike Raid",
    "At Least 50 Hits on Pink Agaricus",
    "Avoid Damage in Cave Escape",
    "Beat Riku in a Race",
    "Beat Riku with Wooden Sword",
    "Become a Heartless",
    "Bizzaga",
    "Blizzaga Chest in Olympus Coliseum",
    "Blizzara Chest in Olympus Coliseum",
    "Blow up an Urchin in Atlantica",
    "Break all Pots without Waking Pot Scorpion",
    "Break the Floor of the Treehouse",
    "Brew a Potion in Camp",
    "Buy 3 Unique Items From the Peddler",
    "Buy all of the Peddler's Unique Items",
    "Buy an Item From the Peddler",
    "Clear 100 Acre Woods",
    "Clear Atlantica",
    "Coconut Check",
    "Collect 2 Clock Tower Door Rewards",
    "Collect 3 Clock Tower Door Rewards",
    "Combo-Master or Counter Attack",
    "Compete against Riku 10 Times",
    "Complete a Section of Jiminy's Journal",
    "Curaga",
    "Defeat 4 Behemoths",
    "Defeat 5 Unique Behemoths",
    "Defeat Anti-Sora",
    "Defeat Chernabog",
    "Defeat Dragon Maleficent",
    "Defeat Hades",
    "Defeat Ice Titan",
    "Defeat Kurt Zisa",
    "Defeat Phantom",
    "Defeat Sephiroth",
    "Defeat Unknown",
    "Defeat a Boss with their World's Keyblade",
    "Destiny Island Day 2 Chest",
    "Diamond Dust or One-Winged Angel",
    "Divine Rose Check",
    "Divine Rose or Lady Luck",
    "Do all 4 Emblem Piece Checks",
    "Don't Let Bees Pop Pooh's Balloon",
    "Don't Let Tigger Stomp a Single Carrot",
    "Don't Use Aero",
    "Don't Use EXP Zero",
    "Don't Use Summons",
    "Donald 13+ MP",
    "Dream Shield Check",
    "Fairy Harp or Crabclaw",
    "Fight the 3v1 on Destiny Islands",
    "Fill up the Empty Bottle for Kairi",
    "Final Rest Chest",
    "Firaga",
    "Get Aerith Check",
    "Get Hit with the Butt of a Shotgun",
    "Get Poisoned",
    "Give Owl 5 Rare Nuts",
    "Goofy 9+ MP",
    "Graviga",
    "Gravity Break or Blitz",
    "Guard or Dodgeroll",
    "Hades Cup",
    "Hades Cup 20th Seed",
    "Hades Cup 30th Seed",
    "Hades Cup 40th Seed",
    "Hades Cup Solo",
    "Hades Cup Time-Trial",
    "Have all Day 2 Destiny Islands Items",
    "High Jump-Ga",
    "Jungle King or Pumpkinhead",
    "Kill 5 Unique Pureblood Heartless",
    "Kill a Chimera",
    "Kill a Gigas Shadow",
    "Kill a Grand Ghost",
    "Kill a Jet Balloon",
    "Kill a Neoshadow",
    "Kill a Pot Scorpion",
    "Kill a Stealth Soldier",
    "Lead Pooh to 5 Jars of Honey",
    "Leaf Bracer and Second Chance",
    "Leaf Bracer or Second Chance",
    "Lucky Strike or Critical Plus",
    "MP Rage or MP Haste",
    "Metal Chocobo or Lionheart",
    "Navi-Gummi Check",
    "Oathkeeper or Oblivion",
    "Obtain Aero Arts",
    "Obtain Blizzard Arts",
    "Obtain Cure Arts",
    "Obtain Fire Arts",
    "Obtain Gravity Arts",
    "Obtain Matsutake Rank (Master's Proof)",
    "Obtain Shiitake Rank (Expert's Proof)",
    "Obtain Stop Arts",
    "Obtain Thunder Arts",
    "Obtain an EXP Item",
    "Obtain the Chocobo Model Blueprint",
    "Obtain the Cid Model Blueprint",
    "Obtain the Elixir from Jack's House",
    "Olympia Check",
    "Olympia or Spellbinder",
    "Open 7 Clams in Atlantica",
    "Pegasus Cup",
    "Pegasus Cup Time-Trial",
    "Phil Cup",
    "Phil Cup Time-Trial",
    "Preform an Experiment in Camp",
    "Pull out Rabbit's Crops",
    "Reach Level 30",
    "Reach Level 40",
    "Reach Level 50",
    "Reach Level 60",
    "Reach Level 70",
    "Replace All of the Books in the Library",
    "Scan-Ra",
    "Seagull Egg Check",
    "Seal 3 Keyholes",
    "Seal 5 Keyholes",
    "Seal 8 Keyholes",
    "Send Pooh At Least 30m Off the Swing",
    "Set Hook on Fire",
    "Slapshot or Sliding Dash",
    "Sonic Blade or Ripple Drive",
    "Sora 10+ MP",
    "Sora 50+ STR",
    "Spellbinder Check",
    "Stopga",
    "Superglide",
    "Synth 12 Unique Items",
    "Synth 18 Unique Items",
    "Synth 24 Unique Items",
    "Synth 30 Unique Items",
    "Synth 6 Unique Items",
    "Synth All Unique Items",
    "Tech Boost or Treasure Magnet",
    "Three Wishes or Wishing Star",
    "Thundaga",
    "Trinity Limit",
    "Ultima Weapon",
    "Use all 4 Emblem Pieces on the Door",
    "Visit Geppetto's House",
    "Vortex or Hurricane Blast",
    "Win the Black Ballade Game",
    "Wooden Sword",
    "Zantetsuken or Stun Impact"
];
