bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "1 Ga-Spell",
    "1 Super Boss",
    "10 Chests in Neverland",
    "10 Postcards",
    "100 Hits on a Rare Truffle",
    "13 Unique Keyblades",
    "15 Chests in Agrabah",
    "15 Chests in Halloween Town",
    "15 Chests in Traverse Town",
    "15 Chests in Wonderland",
    "2+ Air Combo Plus",
    "2+ Combo Plus",
    "20 Chests in End of the World",
    "25 Chests in Hollow Bastion",
    "3 Different \"Arts\" Items",
    "3 Ga-Spells",
    "3 Unique EXP Items",
    "33 Puppies",
    "5 Different \"Arts\" Items",
    "50 Hits on a Rare Truffle",
    "66 Puppies",
    "7 Post Cards",
    "7 Unique Keyblades",
    "99 Puppies",
    "Acquire Bambi",
    "Acquire Dumbo",
    "Acquire Genie",
    "Acquire Mushu",
    "Acquire Tinkerbell",
    "Aeroga",
    "All 13 Ansem Reports",
    "All 3 Dream Weapons",
    "All Blue Trinities",
    "All Chests in Deep Jungle",
    "All Chests in Olympus",
    "All Chests in Traverse Town",
    "All Chests in Wonderland",
    "All Ga-Spells",
    "All Green Trinities",
    "All Lift Stop Chests",
    "All Red Trinities",
    "All Summons",
    "All Trinities in Agrabah",
    "All Trinities in Deep Jungle",
    "All Trinities in Halloween Town",
    "All Trinities in Hollow Bastion",
    "All Trinities in Monstro",
    "All Trinities in Neverland",
    "All Trinities in Olympus Coliseum",
    "All Trinities in Traverse Town",
    "All Trinities in Wonderland",
    "All Trinity Checks",
    "All White Trinities",
    "All World Terminus Chests",
    "All Yellow Trinities",
    "Ars or Strike Raid",
    "Beat Riku in a Race",
    "Bizzaga",
    "Blizzaga Chest in Olympus Coliseum",
    "Blow up an Urchin in Atlantica",
    "Buy 3 Unique Items From the Peddler",
    "Buy all of the Peddler's Unique Items",
    "Buy an Item From the Peddler",
    "Clear 100 Acre Woods",
    "Clear Atlantica",
    "Coconut Check",
    "Collect Logs",
    "Combo-Master or Counter Attack",
    "Curaga",
    "Defeat 4 Unique Behemoths",
    "Defeat Anti-Sora",
    "Defeat Chernabog",
    "Defeat Dragon Maleficent",
    "Defeat Hades",
    "Defeat Ice Titan",
    "Defeat Kurt Zisa",
    "Defeat Leon & Cloud",
    "Defeat Phantom",
    "Defeat Sephiroth",
    "Defeat Unknown",
    "Diamond Dust or One-Winged Angel",
    "Don't Let Tigger Stomp a Single Carrot",
    "Don't Use Aero",
    "Don't Use EXP Zero",
    "Don't Use Summons",
    "Donald 13+ MP",
    "Dream Shield Check",
    "Fight the 3v1 on Destiny Islands",
    "Fill up the Empty Bottle for Kairi",
    "Final Rest Chest",
    "Firaga",
    "Get Hit with the Butt of a Shotgun",
    "Get Poisoned",
    "Give Owl 5 Rare Nuts",
    "Goofy 9+ MP",
    "Graviga",
    "Gravity Break or Blitz",
    "Guard or Dodgeroll",
    "Hades Cup",
    "Hades Cup Solo",
    "Hades Cup Time-Trial",
    "High Jump-Ga",
    "Kill a Chimaera",
    "Kill a Grand Ghost",
    "Kill a Pot Scorpion",
    "Kill a Stealth Soldier",
    "Leaf Bracer and Second Chance",
    "Leaf Bracer or Second Chance",
    "Logs Check",
    "Lucky Strike or Critical Plus",
    "MP Rage or MP Haste",
    "Metal Chocobo",
    "Navi-Gummi Check",
    "Oathkeeper or Oblivion",
    "Obtain Matsutake Rank (Master's Proof)",
    "Obtain Shiitake Rank (Expert's Proof)",
    "Olympia Check",
    "Open 7 Clams in Atlantica",
    "Pegasus Cup",
    "Phil Cup",
    "Pumpkin Head",
    "Reach Level 100",
    "Reach Level 25",
    "Reach Level 50",
    "Reach Level 75",
    "Reach Level 90",
    "Replace all of the books in the Library",
    "Scan-Ra",
    "Seagull Egg Check",
    "Seal 3 Keyholes",
    "Seal 5 Keyholes",
    "Seal 8 Keyholes",
    "Set Hook on Fire",
    "Slapshot or Sliding Dash",
    "Sonic Blade or Ripple Drive",
    "Sora 10+ MP",
    "Sora 50+ STR",
    "Spellbinder Check",
    "Stopga",
    "Superglide",
    "Synth 18 Unique Items",
    "Synth 28 Unique Items",
    "Synth 8 Unique Items",
    "Synth All Unique Items",
    "Tech Boost or Treasure Magnet",
    "Thundaga",
    "Ultima Weapon",
    "Vortex or Hurricane Blast",
    "Wooden Sword",
    "Zantetsuken or Stun Impact"
];
