bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Clash with Xemnas",
    "Collect 30 Puzzle Pieces",
    "Collect Every Puzzle Piece In A World",
    "Complete Duality/Two Sides Puzzle",
    "Complete Heart Puzzle",
    "Complete Shang's Mission",
    "Complete the Heart Puzzle",
    "Defeat Barbossa",
    "Defeat Cerberus",
    "Defeat Dark Thorn",
    "Defeat Demyx in Hollow Bastion",
    "Defeat Final Xemnas",
    "Defeat Future Pete in Timeless River",
    "Defeat Groundshaker",
    "Defeat Hades",
    "Defeat Jafar",
    "Defeat Old Pete",
    "Defeat Oogie Boogie",
    "Defeat Prison Keeper",
    "Defeat Roxas",
    "Defeat Scar",
    "Defeat Shan Yu",
    "Defeat Storm Rider",
    "Defeat Thresholder",
    "Defeat Xaldin",
    "Defeat an Absent Silhouette",
    "Defeat the Cursed Grim Reaper",
    "Defeat the Elemental Lords",
    "Defeat the Experiment",
    "Defeat the Hostile Program",
    "Defeat the MCP",
    "Destroy Shang's Camp",
    "Don't Give Up",
    "Dual Wield Oathkeeper and Oblivion",
    "Enter the Laser Dome",
    "Enter the Throne Room",
    "Equip Donald and Goofy with the Nobody Weapons",
    "Fight Alongside Axel and Win",
    "Fight Alongside Cloud and Win",
    "Find 10 Maps",
    "Find 5 Recipes",
    "Find Auron's Statue or the Hades Cup Trophy",
    "Find Pooh in the Spooky Cave",
    "Find a Gift of the Mushroom XIII",
    "Find one of the Struggle Trophies",
    "Find the Ice Cream or the Picture",
    "Gain 10 HP",
    "Get 250 points in a Skateboard minigame",
    "Get Curaga or Reflega",
    "Get Firaga or Blizzaga",
    "Get Level 3 Aerial Dodge",
    "Get Level 3 Dodge Roll",
    "Get Level 3 Glide",
    "Get Level 3 High Jump",
    "Get Level 3 Quick Run",
    "Get Thundaga or Magnega",
    "Get a score of 10 in the grandstander minigame",
    "Get an A rank on a Mushroom XIII minigame",
    "Get up on the Hydra's Back",
    "Go into Anti Form",
    "Have 10000 Munny",
    "Have 2 Drive Recoveries",
    "Have 2 Proofs",
    "Have 20 AP Boosts in your inventory",
    "Have 3 Even Numbered Ansem Reports",
    "Have 3 Odd Numbered Ansem Reports",
    "Have 30 Potions In Your Inventory",
    "Have 4-in-a-row Ansem Reports",
    "Have 7 Drive Gagues",
    "Have 7 Unique Accessories",
    "Have 7 Unique Armors",
    "Have 7 Unique Donald Shields",
    "Have 7 Unique Goofy Shields",
    "Have 7 Unique Keyblades",
    "Have A Draw Equipped",
    "Have some Finny Fun",
    "Kill or Be Killed by Sephiroth",
    "Kill or Be Killed by a Data Org Member",
    "Lose a Struggle",
    "Obtain Magic 9 times",
    "Obtain a Max Level Growth Ability",
    "Play a game with Luxord",
    "Reach Final Form Level 5",
    "Reach Level 20",
    "Reach Level 33",
    "Reach Level 45",
    "Reach Master Form Level 7",
    "Reach Moogle Level 2",
    "Reach Summon Level 4",
    "Reach Valor Form Level 4",
    "Reach Wisdom Form Level 6",
    "Reach the Bottom of Honey Pot Hill",
    "Reach the Nobodies in the Cavern of Rememebrance",
    "Reach the top of Sunset Hill as Sora",
    "Replay Phil's Minigame",
    "Speak with the Fairies in Yen Sid's Tower",
    "Spin the Carousel in Halloween Town",
    "Touch the Beam in Twilight Town",
    "Turn the Valves in the Cavern of Remembrance",
    "Use One Of Any Mega Item",
    "Use a Summon Limit",
    "Use a Tent",
    "Use any Donald or Goofy Limit",
    "Use every non main party Limit",
    "Win the Cerberus Cup",
    "Win the Pain and Panic Cup",
    "Win the Struggle against Setzer",
    "Win the Titan Cup"
];
