var bingoGenerator = require("./generators/generator_bases/srl_generator_v5.js");

var bingoList = 
[[
{ "name": "Become Dome-Mouth Kirby in 3 different levels", "types": ["MM"] },
{ "name": "Save all Waddle Dees in Downtown Grassland", "types": ["1"] },
{ "name": "Save all Waddle Dees in Through the Tunnel", "types": ["2"] },
],[
{ "name": "Enter a HAL room", "types": ["HAL"] },
{ "name": "Save all Waddle Dees in Rocky Rollin’ Road", "types": ["3"] },
{ "name": "Save all Waddle Dees in A Trip to Alivel Mall", "types": ["4"] },
],[
{ "name": "Save 25 Waddle Dees in Natural Plains", "types": ["NP"] },
{ "name": "Save all Waddle Dees in Abandoned Beach", "types": ["5"] },
{ "name": "Save all Waddle Dees in Concrete Isles", "types": ["6"] },
],[
{ "name": "Save 35 Waddle Dees in Natural Plains", "types": ["NP"] },
{ "name": "Complete any Cutter Treasure Road", "types": ["7"] },
{ "name": "Complete any Bomb Treasure Road", "types": ["8"] },
{ "name": "Save all Waddle Dees in Scale the Cement Summit", "types": ["9"] },
{ "name": "Complete any Fire Treasure Road", "types": ["10"] },
],[
{ "name": "Collect 10 unique volume 1 figurine capsules", "types": ["capsule"] },
{ "name": "Finish 3 unique levels in a mouthful mode", "types": ["MMM"] },
{ "name": "Save 40 Waddle Dees in Natural Plains", "types": ["NP"] },
{ "name": "Save 10 solitary caged Waddle Dees in Natural Plains", "types": ["NP"] },
{ "name": "Crack open 3 Knock-Knock Nuts mission", "types": ["11"] },
{ "name": "Die to fire or lava", "types": ["12"] },
{ "name": "Activate 10 unique shiny spots", "types": ["shiny"] },
],[
{ "name": "Collect 5 total rare stones", "types": ["rare"] },
{ "name": "Save all Waddle Dees in Fast-Flowing Waterworks", "types": ["13"] },
{ "name": "Defeat Wild Edge with Needle", "types": ["14"] },
{ "name": "Mix for Sleep", "types": ["15"] },
],[
{ "name": "Collect 5 unique Waddle Dees from treasure chests", "types": ["chest"] },
{ "name": "Destroy 5 unique bomb blocks", "types": ["bomb"] },
{ "name": "Save all Waddle Dees in Natural Plains", "types": ["NP"] },
{ "name": "Complete any Ice Treasure Road", "types": ["16"] },
{ "name": "Save all Waddle Dees in Welcome to Wondaria", "types": ["17"] },
{ "name": "Save all Waddle Dees in Circuit Speedway", "types": ["18"] },
{ "name": "Complete any Ranger Treasure Road", "types": ["19"] },
{ "name": "Sleep in Kirby’s house", "types": ["20"] },
],[
{ "name": "Collect 5 unique blue coins", "types": ["blue"] },
{ "name": "Beat 2 unique bosses without taking damage", "types": ["damage"] },
{ "name": "Save 10 solitary caged Waddle Dees in Everbay Coast", "types": ["EC"] },
{ "name": "Become Car-Mouth Kirby in 3 different levels", "types": ["MM"] },
{ "name": "Activate 5 unique blue switches", "types": ["switch"] },
{ "name": "Make 10 unique Waddle Dees wave to Kirby", "types": ["wave"] },
{ "name": "Save all Waddle Dees in Invasion at the House of Horrors", "types": ["21"] },
{ "name": "Save all Waddle Dees in The Wondaria Dream Parade", "types": ["22"] },
{ "name": "Unlock every base ability", "types": ["23"] },
{ "name": "Defeat Wild Bonkers with Hammer", "types": ["24"] },
{ "name": "Eat a Kirby Burger", "types": ["25"] },
],[
{ "name": "Complete any Hammer Treasure Road", "types": ["26"] },
{ "name": "Save all Waddle Dees in Northeast Frost Street", "types": ["27"] },
{ "name": "Complete any Drill Treasure Road", "types": ["28"] },
{ "name": "Complete any Sword Treasure Road", "types": ["29"] },
{ "name": "Finish third in a Carby race", "types": ["30"] },
{ "name": "Rescue 3 unique timer challenge Waddle Dees", "types": ["timer"] },
{ "name": "Make all the wilted flowers bloom mission", "types": ["31"] },
],[
{ "name": "Beat 10 unique enemy/miniboss arenas", "types": ["arena"] },
{ "name": "Collect 5 unique blueprints", "types": ["blueprint"] },
{ "name": "Collect 20 unique volume 1 figurine capsules", "types": ["capsule"] },
{ "name": "Save 25 Waddle Dees in Everbay Coast", "types": ["EC"] },
{ "name": "Eat 3 unique Maxim Tomatoes", "types": ["maxim"] },
{ "name": "Defeat Tropic Woods with Clutter Needle", "types": ["32"] },
{ "name": "Destroy 13 aliens by using Vending Mouth mission", "types": ["33"] },
{ "name": "Activate 20 unique shiny spots", "types": ["shiny"] },
],[
{ "name": "Use 3 different blueprints to evolve abilities", "types": ["blueprint"] },
{ "name": "Enter 2 unique HAL rooms", "types": ["HAL"] },
{ "name": "Finish 5 unique levels in a mouthful mode", "types": ["MMM"] },
{ "name": "Collect 10 total rare stones", "types": ["rare"] },
{ "name": "Activate 10 unique blue switches", "types": ["switch"] },
{ "name": "Save 10 solitary caged Waddle Dees in Wondaria Remains", "types": ["WR"] },
{ "name": "Complete any Tornado Treasure Road", "types": ["34"] },
{ "name": "Save all Waddle Dees in Metro on Ice", "types": ["35"] },
{ "name": "Save all Waddle Dees in Windy, Freezing Seas", "types": ["36"] },
{ "name": "Complete any Needle Treasure Road", "types": ["37"] },
],[
{ "name": "Have at least 1,000 coins", "types": ["coins"] },
{ "name": "Beat 3 unique bosses without taking damage", "types": ["damage"] },
{ "name": "Save 35 Waddle Dees in Everbay Coast", "types": ["EC"] },
{ "name": "Beat 3 unique bosses without using abilities", "types": ["NCA"] },
{ "name": "Defeat Gorimondo with Gigant Sword", "types": ["38"] },
{ "name": "Defeat Tropic Woods with Toy Hammer", "types": ["39"] },
{ "name": "Collect 10 unique Waddle Dees from treasure chests", "types": ["chest"] },
{ "name": "Open 10 unique treasure chests", "types": ["chest"] },
],[
{ "name": "Eat 5 unique Maxim Tomatoes", "types": ["maxim"] },
{ "name": "Become Ring-Mouth Kirby in 3 different levels", "types": ["MM"] },
{ "name": "Become Vending-Mouth Kirby in 3 different levels", "types": ["MM"] },
{ "name": "Become Stairs-Mouth Kirby in 3 different levels", "types": ["MM"] },
{ "name": "Become Cone-Mouth Kirby in 3 different levels", "types": ["MM"] },
{ "name": "Save 30 Waddle Dees in Wondaria Remains", "types": ["WR"] },
{ "name": "Save all Waddle Dees in The Battle of Blizzard Bridge", "types": ["40"] },
{ "name": "Save all Waddle Dees in The Wastes Where Life Began", "types": ["41"] },
],[
{ "name": "Eat 3 unique invincible candies", "types": ["42"] },
{ "name": "Save all Waddle Dees in Everbay Coast", "types": ["EC"] },
{ "name": "Save all Waddle Dees in Searching the Oasis", "types": ["43"] },
{ "name": "Defeat Clawroline with Fleur Tornado", "types": ["44"] },
],[
{ "name": "Beat 15 unique enemy/miniboss arenas", "types": ["arena"] },
{ "name": "Make 20 unique Waddle Dees wave to Kirby", "types": ["wave"] },
{ "name": "Save 10 solitary caged Waddle Dees in Winter Horns", "types": ["WH"] },
{ "name": "Save all Waddle Dees in Moonlight Canyon", "types": ["45"] },
{ "name": "Die in freezing water", "types": ["46"] },
{ "name": "Activate 30 unique shiny spots", "types": ["shiny"] },
],[
{ "name": "Collect 10 unique blue coins", "types": ["blue"] },
{ "name": "Become Car-Mouth Kirby in 5 different levels", "types": ["MM"] },
{ "name": "Become Pipe-Mouth Kirby in 3 different levels", "types": ["MM"] },
{ "name": "Become Dome-Mouth Kirby in 5 different levels", "types": ["MM"] },
{ "name": "Become Water-Balloon-Mouth Kirby in 3 different levels", "types": ["MM"] },
{ "name": "Beat 4 unique bosses without using abilities", "types": ["NCA"] },
{ "name": "Save 30 Waddle Dees in Winter Horns", "types": ["WH"] },
{ "name": "Save all Waddle Dees in Alivel Mall (Staff Side)", "types": ["47"] },
{ "name": "Defeat 4 unique Wild Edges", "types": ["48"] },
{ "name": "Collect 5 unique volume 2 figurine capsules", "types": ["49"] },
{ "name": "Defeat 4 unique Fleurinas", "types": ["50"] },
{ "name": "Rescue 5 unique timer challenge Waddle Dees", "types": ["timer"] },
],[
{ "name": "Have at least 2,000 coins", "types": ["coins"] },
{ "name": "Save all Waddle Dees in Enter the Fiery Forbidden Lands", "types": ["51"] },
{ "name": "Save all Waddle Dees in Conquer the Inferno Road", "types": ["52"] },
{ "name": "Defeat King Dedede with Noble Ranger", "types": ["53"] },
{ "name": "Defeat King Dedede with Dragon Fire", "types": ["54"] },
{ "name": "Defeat Fleurina using Ring Mouth mission", "types": ["55"] },
],[
{ "name": "Collect 15 unique blueprints", "types": ["blueprint"] },
{ "name": "Destroy 10 unique bomb blocks", "types": ["bomb"] },
{ "name": "Beat 4 unique bosses without taking damage", "types": ["damage"] },
{ "name": "Become Ring-Mouth Kirby in 5 different levels", "types": ["MM"] },
{ "name": "Become Vending-Mouth Kirby in 5 different levels", "types": ["MM"] },
{ "name": "Become Cone-Mouth Kirby in 5 different levels", "types": ["MM"] },
{ "name": "Activate 20 unique blue switches", "types": ["switch"] },
{ "name": "Save 40 Waddle Dees in Wondaria Remains", "types": ["WR"] },
{ "name": "Save all Waddle Dees in Burning, Churning Power Plant", "types": ["56"] },
{ "name": "Catch Bling Blipper", "types": ["57"] },
{ "name": "Defeat 4 unique Wild Frostys", "types": ["58"] },
{ "name": "Defeat Clawroline with Homing Bomb", "types": ["59"] },
{ "name": "Beat Twin Wild Frosty without getting hit mission", "types": ["60"] },
{ "name": "Die to poison", "types": ["61"] },
{ "name": "Defeat 4 unique Wild Bonkers", "types": ["62"] },
{ "name": "Open 20 unique treasure chests", "types": ["chest"] },
],[
{ "name": "Save 10 solitary caged Waddle Dees in Originull Wasteland", "types": ["OW"] },
{ "name": "Save 40 Waddle Dees in Winter Horns", "types": ["WH"] },
{ "name": "Save all Waddle Dees in Wondaria Remains", "types": ["WR"] },
{ "name": "Save all Waddle Dees in Gathering of the Beast Council", "types": ["63"] },
{ "name": "Defeat Wild Bonkers with the Cutter ability mission", "types": ["64"] },
],[
{ "name": "Collect 15 unique blue coins", "types": ["blue"] },
{ "name": "Use 5 different blueprints to evolve abilities", "types": ["blueprint"] },
{ "name": "Finish 7 unique levels in a mouthful mode", "types": ["MMM"] },
{ "name": "Beat 5 unique bosses without using abilities", "types": ["NCA"] },
{ "name": "Save 30 Waddle Dees in Originull Wasteland", "types": ["OW"] },
{ "name": "Collect 20 total rare stones", "types": ["rare"] },
{ "name": "Save all Waddle Dees in Winter Horns", "types": ["WH"] },
{ "name": "Beat all 3 difficulties of Tilt-and-Roll", "types": ["65"] },
{ "name": "Defeat Sillydillo with Pencil Drill", "types": ["66"] },
{ "name": "Activate 40 unique shiny spots", "types": ["shiny"] },
],[
{ "name": "Enter 3 unique HAL rooms", "types": ["HAL"] },
{ "name": "Become Scissor-Lift-Mouth Kirby in 3 different levels", "types": ["MM"] },
{ "name": "Become Ring-Mouth Kirby in 7 different levels", "types": ["MM"] },
{ "name": "Save all Waddle Dees in The Beast Pack’s Final Stand", "types": ["67"] },
],[
{ "name": "Save 40 Waddle Dees in Originull Wasteland", "types": ["OW"] },
{ "name": "Save 40 Waddle Dees in Redgar Forbidden Lands", "types": ["RFL"] },
{ "name": "Save 15 solitary caged Waddle Dees in Redgar Forbidden Lands", "types": ["RFL"] },
{ "name": "Make all the Windmill Switches spin mission", "types": ["68"] },
],[
{ "name": "Save 50 Waddle Dees in Redgar Forbidden Lands", "types": ["RFL"] },
{ "name": "Defeat Sillydillo with Space Ranger", "types": ["69"] },
{ "name": "Become Cone-Mouth Kirby in 7 different levels", "types": ["MM"] },
],[
{ "name": "Save all Waddle Dees in Originull Wasteland", "types": ["OW"] },
{ "name": "Use a cannon in 3 different levels", "types": ["70"] },
{ "name": "Collect 3 unique volume 3 figurine capsules", "types": ["71"] },
],[
{ "name": "Have at least 5,000 coins", "types": ["coins"] },
{ "name": "Beat 6 unique bosses without using abilities", "types": ["NCA"] },
{ "name": "Save all Waddle Dees in Redgar Forbidden Lands", "types": ["RFL"] },
{ "name": "Make 30 unique Waddle Dees wave to Kirby", "types": ["wave"] },
]];
