bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "1 Story Level using 1P2C",
    "1 Story Level with Ice Rink",
    "1 Story Level with Silhouettes/ Disguises",
    "1 Story Level with Zero Studs",
    "2 Super Statuses",
    "3 Hostages",
    "3 Story Levels with 1P2C",
    "3 Story Levels with Ice Rink",
    "3 Story Levels with Silhouettes/ Disguises",
    "3 Story Levels with Zero Studs",
    "3 Vehicle Levels Free Play",
    "4 Super Statuses",
    "6 Hostages",
    "6 Super Statuses",
    "9 Hostages",
    "A Daring Rescue - 30k Studs",
    "A Daring Rescue - 4+ Story Minikits",
    "A Daring Rescue - 6+ Minikits",
    "A Daring Rescue - 8+ Minikits",
    "A Daring Rescue - Hostage",
    "A Daring Rescue - No Room 1 Skip",
    "A Daring Rescue - Red Brick",
    "A Poisonous Appointment - 40k Studs",
    "A Poisonous Appointment - 5+ Minikits",
    "A Poisonous Appointment - 9+ Minikits",
    "A Poisonous Appointment - Hostage",
    "A Poisonous Appointment - Red Brick",
    "A Surprise for the Commissioner - 30k Studs",
    "A Surprise for the Commissioner - 4+ Story Minikits",
    "A Surprise for the Commissioner - 6+ Minikits",
    "A Surprise for the Commissioner - 9+ Minikits",
    "A Surprise for the Commissioner - Hostage",
    "A Surprise for the Commissioner - No Boss Skip",
    "A Surprise for the Commissioner - Red Brick",
    "An Enterprising Theft - 10 Minikits",
    "An Enterprising Theft - 25k Studs",
    "An Enterprising Theft - 3+ Minikits",
    "An Enterprising Theft - Hostage",
    "An Enterprising Theft - Red Brick",
    "An Icy Reception - 3+ Minikits",
    "An Icy Reception - 40k Studs",
    "An Icy Reception - 8+ Minikits",
    "An Icy Reception - Hostage",
    "An Icy Reception - Red Brick",
    "An Icy Reception - Robin Only",
    "Arctic World - 20k Studs",
    "Arctic World - 3+ Minikits",
    "Arctic World - 9+ Minikits",
    "Arctic World - Hostage",
    "Arctic World - No Drop In Warps",
    "Arctic World - Red Brick",
    "Batboat Battle - 10 Minikits",
    "Batboat Battle - 15k Studs",
    "Batboat Battle - 5+ Minikits",
    "Batboat Battle - Red Brick",
    "Biplane Blast - 10 Minikits",
    "Biplane Blast - 15k Studs",
    "Biplane Blast - 4+ Minikits",
    "Biplane Blast - Red Brick",
    "Breaking Blocks - 2+ Minikits",
    "Breaking Blocks - 30k Studs",
    "Breaking Blocks - 9+ Minikits",
    "Breaking Blocks - Hostage",
    "Breaking Blocks - Red Brick",
    "Buy 10 Data",
    "Buy 2 Suit Upgrades",
    "Buy 2 Villain Red Bricks",
    "Buy 2 Villains",
    "Buy 3 Goons",
    "Buy 3 Law Enforcement Characters",
    "Buy 3 Villain Red Bricks",
    "Buy 4 Suit Upgrades",
    "Buy 5 Goons/Henchmen",
    "Buy All Police Road Vehicles",
    "Buy Batgirl and Nightwing",
    "Buy Bruce Wayne and Private Jet",
    "Buy Commissioner Gordon and Alfred",
    "Buy Robin's Submarine",
    "Buy Slam and Fast Build",
    "Collect 1 Million Studs",
    "Collect 10 Minikits",
    "Collect 15 Minikits",
    "Collect 20 Minikits",
    "Collect 25 Minikits",
    "Collect 3 Red Bricks",
    "Collect 5 Red Bricks",
    "Collect 500k Studs",
    "Collect 7 Red Bricks",
    "Collect All Suits",
    "Custom Character Free Play",
    "Double Vacuum Deposit",
    "Dying of Laughter - 4+ Minikits",
    "Dying of Laughter - 40k Studs",
    "Dying of Laughter - 9+ Minikits",
    "Dying of Laughter - Hostage",
    "Dying of Laughter - Red Brick",
    "Flight of the Bat - 10 Minikits",
    "Flight of the Bat - 15k Studs",
    "Flight of the Bat - 7+ Minikits",
    "Flight of the Bat - Red Brick",
    "Green Fingers - 4+ Minikits",
    "Green Fingers - 40k Studs",
    "Green Fingers - 9+ Minikits",
    "Green Fingers - Hostage",
    "Green Fingers - Red Brick",
    "Grow 3 Poison Ivy Plants",
    "Harboring a Grudge - 10 Minikits",
    "Harboring a Grudge - 15k Studs",
    "Harboring a Grudge - 7+ Minikits",
    "Harboring a Grudge - Red Brick",
    "Hero Episode - Story",
    "In the Dark Night - 2+ Minikits",
    "In the Dark Night - 35k Studs",
    "In the Dark Night - 8+ Minikits",
    "In the Dark Night - Hostage",
    "In the Dark Night - No Disco Skip",
    "In the Dark Night - No Wall Jumping",
    "In the Dark Night - Red Brick",
    "Joker's Home Turf - 30k Studs",
    "Joker's Home Turf - 4+ Story Minikits",
    "Joker's Home Turf - 6+ Minikits",
    "Joker's Home Turf - 9+ Minikits",
    "Joker's Home Turf - Hostage",
    "Joker's Home Turf - No Room 2/3 Gliding",
    "Joker's Home Turf - No Vacuum Skip",
    "Joker's Home Turf - Red Brick",
    "Joker's Home Turf - Toxic Goo Minikit",
    "Little Fun at the Big Top - 30k Studs",
    "Little Fun at the Big Top - 4+ Minikits",
    "Little Fun at the Big Top - 9+ Minikits",
    "Little Fun at the Big Top - Hostage",
    "Little Fun at the Big Top - No Candy Cane Jump",
    "Little Fun at the Big Top - Red Brick",
    "On the Rocks - 10 Minikits",
    "On the Rocks - 30k Studs",
    "On the Rocks - 4+ Story Minikits",
    "On the Rocks - 6+ Minikits",
    "On the Rocks - Hostage",
    "On the Rocks - Red Brick",
    "Penguin's Lair - 15k Studs",
    "Penguin's Lair - 4+ Story Minikits",
    "Penguin's Lair - 6+ Minikits",
    "Penguin's Lair - 9+ Minikits",
    "Penguin's Lair - Hostage",
    "Penguin's Lair - No Glide Suit",
    "Penguin's Lair - Red Brick",
    "Power Crazed Penguin - Hero Story",
    "Power Crazed Penguin - Villain Story",
    "Riddler's Revenge - Hero Story",
    "Riddler's Revenge - Villain Story",
    "Ride 3 Stud Rides",
    "Rockin' the Docks - 4+ Story Minikits",
    "Rockin' the Docks - 6+ Minikits",
    "Rockin' the Docks - 9+ Minikits",
    "Rockin' the Docks - Hostage",
    "Rockin' the Docks - No Birthday Skip",
    "Rockin' the Docks - Red Brick",
    "Rockin' the Docks - Super Villain",
    "Stealing the Show - 1 Character",
    "Stealing the Show - 10 Minikits",
    "Stealing the Show - 5+ Story Minikits",
    "Stealing the Show - 7+ Minikits",
    "Stealing the Show - Hostage",
    "Stealing the Show - Red Brick",
    "Stealing the Show - Super Villain",
    "The Face-Off - 10 Minikits",
    "The Face-Off - 40k Studs",
    "The Face-Off - 5+ Story Minikits",
    "The Face-Off - 7+ Minikits",
    "The Face-Off - Hostage",
    "The Face-Off - No Drop In Warps",
    "The Face-Off - Red Brick",
    "The Joker's Masterpiece - 4+ Minikits",
    "The Joker's Masterpiece - 40k Studs",
    "The Joker's Masterpiece - 9+ Minikits",
    "The Joker's Masterpiece - Hostage",
    "The Joker's Masterpiece - Red Brick",
    "The Joker's Return - Hero Story",
    "The Joker's Return - Villain Story",
    "The Lure of the Night - 40k Studs",
    "The Lure of the Night - 5+ Minikits",
    "The Lure of the Night - 9+ Minikits",
    "The Lure of the Night - Hostage",
    "The Lure of the Night - Red Brick",
    "The Riddler Makes a Withdrawal - 10 Minikits",
    "The Riddler Makes a Withdrawal - 30k Studs",
    "The Riddler Makes a Withdrawal - 5+ Story Minikits",
    "The Riddler Makes a Withdrawal - 7+ Minikits",
    "The Riddler Makes a Withdrawal - Hostage",
    "The Riddler Makes a Withdrawal - No Wall Jumping",
    "The Riddler Makes a Withdrawal - Red Brick",
    "There She Goes Again - 10 Minikits",
    "There She Goes Again - 3+ Minikits",
    "There She Goes Again - 40k Studs",
    "There She Goes Again - Hostage",
    "There She Goes Again - No Gliding",
    "There She Goes Again - Red Brick",
    "To the Top of the Tower - 10 Minikits",
    "To the Top of the Tower - 40k Studs",
    "To the Top of the Tower - 5+ Story Minikits",
    "To the Top of the Tower - 7+ Minikits",
    "To the Top of the Tower - Hostage",
    "To the Top of the Tower - No Magnet Suit",
    "To the Top of the Tower - No Wall Jumping",
    "To the Top of the Tower - Red Brick",
    "Two-Face Chase - 10 Minikits",
    "Two-Face Chase - 30k Studs",
    "Two-Face Chase - 7+ Minikits",
    "Two-Face Chase - No Drop In Warps",
    "Two-Face Chase - Red Brick",
    "Under the City - 5+ Minikits",
    "Under the City - 8+ Minikits",
    "Under the City - Hostage",
    "Under the City - No Room 1 Out of Bounds",
    "Under the City - No Room 3 Gliding",
    "Under the City - Out of Bounds Minikit",
    "Under the City - Red Brick",
    "Under the City - Super Hero",
    "Villain Episode - Story",
    "Watch 3 Cutscenes",
    "You Can Bank on Batman - 20k Studs",
    "You Can Bank on Batman - 3+ Minikits",
    "You Can Bank on Batman - 9+ Minikits",
    "You Can Bank on Batman - Hostage",
    "You Can Bank on Batman - Red Brick",
    "Zoo's Company - 10 Minikits",
    "Zoo's Company - 30k Studs",
    "Zoo's Company - 5+ Minikits",
    "Zoo's Company - Hostage",
    "Zoo's Company - No Bench Jump",
    "Zoo's Company - No Turtle Skip",
    "Zoo's Company - Red Brick"
];
