bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "1 Story Level with Disguises",
    "1 Story Level with Zero Studs",
    "2 Story Episodes",
    "2 Super Statuses",
    "4 Super Statuses",
    "6 Super Statuses",
    "A Spanish Legacy - 3+ Story Bottles",
    "A Spanish Legacy - 40k Studs",
    "A Spanish Legacy - 9+ Bottles",
    "A Spanish Legacy - All Compass Items",
    "A Touch Of Destiny - 25k Studs",
    "A Touch Of Destiny - 4+ Story Bottles",
    "A Touch Of Destiny - 9+ Bottles",
    "A Touch Of Destiny - All Compass Items",
    "A Touch Of Destiny - No Room 1 Skip",
    "At World's End - Story",
    "Colleck 1 Million Studs",
    "Collect 10 Minikits",
    "Collect 15 Minikits",
    "Collect 2 Million Studs",
    "Collect 20 Minikits",
    "Collect 25 Minikits",
    "Collect 3 Red Hats",
    "Collect 5 Red Hats",
    "Collect 500k Studs",
    "Collect 7 Red Hats",
    "Complete 3 Levels in Free Play",
    "Davy Jones' Locker - 5+ Story Bottles",
    "Davy Jones' Locker - 9+ Bottles",
    "Davy Jones' Locker - All Compass Items",
    "Davy Jones' Locker - True Pirate",
    "Dead Man's Chest - Story",
    "Isla Cruces - 35k Studs",
    "Isla Cruces - 4+ Story Bottles",
    "Isla Cruces - 9+ Bottles",
    "Isla Cruces - All Compass Items",
    "Isla De Muerta - 2+ Story Bottles",
    "Isla De Muerta - 30k Studs",
    "Isla De Muerta - 8+ Bottles",
    "Isla De Muerta - All Compass Items",
    "London Town - 30k Studs",
    "London Town - 9+ Bottles",
    "London Town - All Compass Items",
    "Norrington's Choice - 5+ Story Bottles",
    "Norrington's Choice - 50k Studs",
    "Norrington's Choice - 8+ Bottles",
    "Norrington's Choice - All Compass Items",
    "On Stranger Tides - Story",
    "Pelegosto - 35k Studs",
    "Pelegosto - 7+ Bottles",
    "Pelegosto - All Compass Items",
    "Pelegosto - No Dog Skip",
    "Port Royal - 5+ Story Bottles",
    "Port Royal - 70k Studs",
    "Port Royal - 9+ Bottles",
    "Port Royal - All Compass Items",
    "Purchase 5 Crew Members of the Flying Dutchman",
    "Purchase 5 Cursed Crew Members of the Black Pearl",
    "Purchase 5 of the Pirate Lords",
    "Purchase Fast Build, Fast Dig and Fast Forge",
    "Queen Anne's Revenge - 25k Studs",
    "Queen Anne's Revenge - 3+ Story Bottles",
    "Queen Anne's Revenge - 8+ Bottles",
    "Queen Anne's Revenge - All Compass Items",
    "Singapore - 25k Studs",
    "Singapore - 9+ Bottles",
    "Singapore - All Compass Items",
    "Singapore - No Barrel Jump / Pixel Jump",
    "Smuggler's Den - 25k Studs",
    "Smuggler's Den - 3+ Story Bottles",
    "Smuggler's Den - 8+ Bottles",
    "Smuggler's Den - All Compass Items",
    "The Black Pearl Attacks - 25k Studs",
    "The Black Pearl Attacks - 4+ Story Bottles",
    "The Black Pearl Attacks - 7+ Bottles",
    "The Black Pearl Attacks - All Compass Items",
    "The Black Pearl Attacks - No Room 3 Skip",
    "The Brethren Court - 2+ Story Bottles",
    "The Brethren Court - 7+ Bottles",
    "The Brethren Court - All Compass Items",
    "The Brethren Court - True Pirate",
    "The Curse of the Black Pearl - Story",
    "The Dutchman's Secret - 3+ Story Bottles",
    "The Dutchman's Secret - 50k Studs",
    "The Dutchman's Secret - 9+ Bottles",
    "The Dutchman's Secret - All Compass Items",
    "The Fountain of Youth - 8+ Bottles",
    "The Fountain of Youth - All Compass Items",
    "The Fountain of Youth - True Pirate",
    "The Kraken - 5+ Story Bottles",
    "The Kraken - 8+ Bottles",
    "The Kraken - All Compass Items",
    "The Kraken - True Pirate",
    "The Maelstrom - 25k Studs",
    "The Maelstrom - 8+ Bottles",
    "The Maelstrom - All Compass Items",
    "Tortuga - 3+ Story Bottles",
    "Tortuga - 7+ Bottles",
    "Tortuga - 70k Studs",
    "Tortuga - All Compass Items",
    "Unlock 1 Ship",
    "Unlock 2 Ships",
    "Unlock 3 Ships",
    "White Cap Bay - 10 Bottles",
    "White Cap Bay - 25k Studs",
    "White Cap Bay - 5+ Story Bottles",
    "White Cap Bay - All Compass Items"
];
