bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "All Minikits & Red Power Bricks for 5 levels",
    "All gold bricks for Battle Over Coruscant (3-1)",
    "All gold bricks for Cloud City Trap (5-5)",
    "All gold bricks for Count Dooku (2-5)",
    "All gold bricks for Dagobah (5-4)",
    "All gold bricks for Darth Maul (1-5)",
    "All gold bricks for Darth Vader (3-5)",
    "All gold bricks for Death Star Escape (4-4)",
    "All gold bricks for Defense of Kashyyyk (3-3)",
    "All gold bricks for Discovery on Kamino (2-1)",
    "All gold bricks for Droid Factory (2-2)",
    "All gold bricks for Escape From Echo Base (5-2)",
    "All gold bricks for Escape From Naboo (1-2)",
    "All gold bricks for Falcon Flight (5-3)",
    "All gold bricks for General Grievous (3-2)",
    "All gold bricks for Gunship Cavalry (2-4)",
    "All gold bricks for Hoth Battle (5-1)",
    "All gold bricks for Into the Death Star (6-5)",
    "All gold bricks for Jabba's Palace (6-1)",
    "All gold bricks for Jedi Battle (2-3)",
    "All gold bricks for Jedi Destiny (6-4)",
    "All gold bricks for Mos Eisley Spaceport (4-3)",
    "All gold bricks for Mos Espa Podrace (1-3)",
    "All gold bricks for Negotiations (1-1)",
    "All gold bricks for Rebel Attack (4-5)",
    "All gold bricks for Retake Theed Palace (1-4)",
    "All gold bricks for Ruin of the Jedi (3-4)",
    "All gold bricks for Secret Plans (4-1)",
    "All gold bricks for Speeder Showdown (6-2)",
    "All gold bricks for The Battle of Endor (6-3)",
    "All gold bricks for Through the Jundland Wastes (4-2)",
    "Buy 10 characters",
    "Buy 12 characters",
    "Buy 15 characters",
    "Buy 2 extras worth at least 200,000 studs",
    "Buy 3 bounty hunters",
    "Buy 5 extras",
    "Buy 6 extras",
    "Buy 7 extras",
    "Buy 8 characters",
    "Buy 8 extras",
    "Buy all hints",
    "Collect 1 gold brick from minigames",
    "Collect 10 red power bricks",
    "Collect 100 minikits",
    "Collect 11 red power bricks",
    "Collect 12 red power bricks",
    "Collect 2 gold bricks from minigames",
    "Collect 60 minikits",
    "Collect 70 minikits",
    "Collect 8 red power bricks",
    "Collect 80 minikits",
    "Collect 9 red power bricks",
    "Collect 90 minikits",
    "Defeat 4 bosses without glitches",
    "Defeat 5 bosses without glitches",
    "Defeat 6 bosses without glitches",
    "Defeat 7 bosses without glitches",
    "Die as Jar Jar Binks in 3 different levels",
    "Finish 3 ship levels",
    "Finish 4 ship levels",
    "Finish 5 ship levels",
    "Finish 6 ship levels",
    "Finish Cloud City Trap (5-5) without using Yoda (Free Play)",
    "Finish Death Star Escape (4-4) without glitches (Free Play)",
    "Finish Death Star Escape (4-4) without glitches (Story Mode)",
    "Finish Jabba's Palace (6-1) as 'Princess Leia (Slave)' (Story Mode)",
    "Finish all 8 ship levels",
    "Finish all levels in Episode I (Story Mode)",
    "Finish all levels in Episode II (Story Mode)",
    "Finish all levels in Episode III (Story Mode)",
    "Finish all levels in Episode IV (Story Mode)",
    "Finish all levels in Episode V (Story Mode)",
    "Finish all levels in Episode VI (Story Mode)",
    "Finish any 10 levels (Free Play)",
    "Finish any 15 levels (Free Play)",
    "Finish any 15 levels (Story Mode)",
    "Finish any 20 levels (Story Mode)",
    "Finish the last level of every episode (Story Mode)",
    "Get killed by The Emperor's Sith lightning",
    "Glitched Anakin fight in Darth Vader (3-5)",
    "Perform two successful It's Raining Men skips (2-1)",
    "True Jedi Story and Free Play for 5 levels",
    "Unlock all variants of Han Solo",
    "Unlock all variants of Luke Skywalker",
    "Unlock all variants of Obi-Wan Kenobi",
    "Unlock all variants of Princess Leia",
    "Use any variant of Yoda to clip through at least 10 different doors",
    "Wear both a stormtrooper and bounty hunter helmet as Chewbacca"
];
