var bingoGenerator = require("./generators/generator_bases/srl_generator_v5.js");

var bingoList = [];
bingoList[1] = [
  { name: "You Can Bank on Batman - Red Brick", types: [] },
  { name: "There She Goes Again - Hostage", types: [] },
  { name: "Joker's Home Turf - Red Brick", types: [] },
  { name: "1 Story Level with Zero Studs", types: [] },
  { name: "Buy 10 Data", types: [] },
  { name: "An Icy Reception - Hostage", types: [] },
  { name: "Little Fun at the Big Top - 30k Studs", types: [] },
  { name: "Collect 10 Minikits", types: [] },
  { name: "Batboat Battle - 5+ Minikits", types: [] },
];
bingoList[2] = [
  { name: "Little Fun at the Big Top - Hostage", types: [] },
  { name: "You Can Bank on Batman - 20k Studs", types: [] },
  { name: "There She Goes Again - 3+ Minikits", types: [] },
  { name: "1 Story Level using 1P2C", types: [] },
  { name: "3 Hostages", types: [] },
  { name: "An Icy Reception - 3+ Minikits", types: [] },
  { name: "Batboat Battle - 15k Studs", types: [] },
  { name: "Buy 2 Suit Upgrades", types: [] },
  { name: "Buy Robin's Submarine and Penguin Goon Submarine", types: [] },
];
bingoList[3] = [
  { name: "1 Story Level with Ice Rink", types: [] },
  { name: "2 Super Hero/Villains", types: [] },
  { name: "Joker's Home Turf - 6+ Minikits", types: [] },
  { name: "Collect 15 Minikits", types: [] },
  { name: "Two-Face Chase - 30k Studs", types: [] },
  { name: "Under the City - 5+ Minikits", types: [] },
  { name: "You Can Bank on Batman - Hostage", types: [] },
  { name: "There She Goes Again - 40k Studs", types: [] },
  { name: "Little Fun at the Big Top - No Candy Cane Jump", types: [] },
];
bingoList[4] = [
  { name: "1 Story Level with Silhouettes/ Disguises", types: [] },
  { name: "An Icy Reception - 30k Studs", types: [] },
  { name: "Collect 3 Red Bricks", types: [] },
  { name: "Flight of the Bat - 15k Studs", types: [] },
  { name: "Joker's Home Turf - 30k Studs", types: [] },
  { name: "Little Fun at the Big Top - 4+ Minikits", types: [] },
  { name: "There She Goes Again - No Gliding", types: [] },
  { name: "Two-Face Chase - No Drop In Warps", types: [] },
  { name: "You Can Bank on Batman - 3+ Minikits", types: [] },
];
bingoList[5] = [
  { name: "3 Story Levels with Ice Rink", types: [] },
  { name: "An Icy Reception - Red Brick", types: [] },
  { name: "Buy 3 Goons", types: [] },
  { name: "Buy All Police Road Vehicles", types: [] },
  { name: "A Poisonous Appointment - 40k Studs", types: [] },
  { name: "Joker's Home Turf - Hostage", types: [] },
  { name: "Ride 3 Stud Rides", types: [] },
  { name: "There She Goes Again - Red Brick", types: [] },
  { name: "Two-Face Chase - 7+ Minikits", types: [] },
];
bingoList[6] = [
  { name: "3 Story Levels with 1P2C", types: [] },
  { name: "A Poisonous Appointment - 5+ Minikits", types: [] },
  { name: "An Icy Reception - Robin Only", types: [] },
  { name: "Flight of the Bat - 7+ Minikits", types: [] },
  { name: "Joker's Home Turf - No Room 2/3 Gliding", types: [] },
  { name: "The Face Off - 7+ Minikits", types: [] },
  { name: "There She Goes Again - 10 Minikits", types: [] },
  { name: "Two-Face Chase - Red Brick", types: [] },
  { name: "Zoo's Company - 7+ Minikits", types: [] },
];
bingoList[7] = [
  { name: "Collect 20 Minikits", types: [] },
  { name: "Hero Episode - Story", types: [] },
  { name: "Zoo's Company - 30k Studs", types: [] },
  { name: "The Face Off - Hostage", types: [] },
  { name: "Little Fun at the Big Top - Red Brick", types: [] },
  { name: "Joker's Home Turf - No Vacuum Skip", types: [] },
  { name: "Buy Batgirl and Nightwing", types: [] },
  { name: "An Icy Reception - 10 Minikits", types: [] },
  { name: "Under the City - Hostage", types: [] },
];
bingoList[8] = [
  { name: "3 Story Levels with Silhouettes/ Disguises", types: [] },
  { name: "A Poisonous Appointment - Hostage", types: [] },
  { name: "Buy 4 Suit Upgrades", types: [] },
  { name: "In the Dark Night - 2+ Minikits", types: [] },
  { name: "Joker's Home Turf - 10 Minikits", types: [] },
  { name: "The Face Off - 30k Studs", types: [] },
  { name: "Under the City - No Room 3 Gliding", types: [] },
  { name: "You Can Bank on Batman - 10 Minikits", types: [] },
  { name: "Zoo's Company - Hostage", types: [] },
];
bingoList[9] = [
  { name: "6 Hostages", types: [] },
  { name: "Buy 2 Villains", types: [] },
  { name: "In the Dark Night - 35k Studs", types: [] },
  { name: "The Face Off - No Drop In Warps", types: [] },
  { name: "To the Top of the Tower - 40k Studs", types: [] },
  { name: "Under the City - Super Hero", types: [] },
  { name: "Zoo's Company - No Bench Jump", types: [] },
  { name: "The Riddler Makes a Withdrawal - 30k Studs", types: [] },
  { name: "A Surprise for the Commissioner - Red Brick", types: [] },
];
bingoList[10] = [
  { name: "3 Story Levels with Zero Studs", types: [] },
  { name: "Buy Bruce Wayne and Private Jet", types: [] },
  { name: "Collect All Suits", types: [] },
  { name: "Riddler's Revenge - Hero Story", types: [] },
  { name: "Rockin' the Docks - 6+ Minikits", types: [] },
  { name: "The Face Off - 10 Minikits", types: [] },
  { name: "The Joker's Return - Hero Story", types: [] },
  { name: "Power Crazed Penguin - Hero Story", types: [] },
  { name: "The Riddler Makes a Withdrawal - Hostage", types: [] },
];
bingoList[11] = [
  { name: "3 Vehicle Levels Free Play", types: [] },
  { name: "Zoo's Company - No Turtle Skip", types: [] },
  { name: "The Riddler Makes a Withdrawal - 7+ Minikits", types: [] },
  { name: "The Face Off - Red Brick", types: [] },
  { name: "Stealing the Show - Hostage", types: [] },
  { name: "On the Rocks - 30k Studs", types: [] },
  { name: "Bi-Plane Blast - 4+ Minikits", types: [] },
  { name: "A Surprise for the Commissioner - 30k Studs", types: [] },
  { name: "4 Super Hero/Villains", types: [] },
];
bingoList[12] = [
  { name: "6 Super Hero/Villains", types: [] },
  { name: "Collect 5 Red Bricks", types: [] },
  { name: "Collect 500k Studs", types: [] },
  { name: "Custom Character Free Play", types: [] },
  { name: "Bi-Plane Blast - 15k Studs", types: [] },
  { name: "A Surprise for the Commissioner - 6+ Minikits", types: [] },
  { name: "Harboring a Grudge - 15k Studs", types: [] },
  { name: "On the Rocks - Hostage", types: [] },
  { name: "Rockin' the Docks - Hostage", types: [] },
];
bingoList[13] = [
  { name: "The Joker's Masterpiece - 4+ Minikits", types: [] },
  { name: "9 Hostages", types: [] },
  { name: "A Daring Rescue - 30k Studs", types: [] },
  { name: "A Poisonous Appointment - 10 Minikits", types: [] },
  { name: "A Surprise for the Commissioner - Hostage", types: [] },
  { name: "Green Fingers - 3+ Minikits", types: [] },
  { name: "Harboring a Grudge - Red Brick", types: [] },
  { name: "Hero Episode - Free Play", types: [] },
  { name: "In the Dark Night - Hostage", types: [] },
];
bingoList[14] = [
  { name: "On the Rocks - 5+ Minikits", types: [] },
  { name: "Penguin's Lair - Hostage", types: [] },
  { name: "Rockin' the Docks - Super Villain", types: [] },
  { name: "Stealing the Show - 1 Character", types: [] },
  { name: "Green Fingers - 40k Studs", types: [] },
  { name: "In the Dark Night - No Disco Skip", types: [] },
  { name: "Penguin's Lair - 6+ Minikits", types: [] },
  { name: "The Riddler Makes a Withdrawal - No Wall Jumping", types: [] },
  { name: "Under the City - Red Brick", types: [] },
];
bingoList[15] = [
  { name: "Zoo's Company - Red Brick", types: [] },
  { name: "A Daring Rescue - 5+ Minikits", types: [] },
  { name: "A Poisonous Appointment - Red Brick", types: [] },
  { name: "A Surprise for the Commissioner - 10 Minikits", types: [] },
  { name: "An Enterprising Theft - 25k Studs", types: [] },
  { name: "Batboat Battle - Red Brick", types: [] },
  { name: "Bi-Plane Blast - 10 Minikits", types: [] },
  { name: "Buy 2 Villain Red Bricks", types: [] },
  { name: "Penguin's Lair - 15k Studs", types: [] },
];
bingoList[16] = [
  { name: "Zoo's Company - 10 Minikits", types: [] },
  { name: "Two-Face Chase - 10 Minikits", types: [] },
  { name: "To the Top of the Tower - 7+ Minikits", types: [] },
  { name: "The Riddler Makes a Withdrawal - Red Brick", types: [] },
  { name: "In the Dark Night - No Wall Jumping", types: [] },
  { name: "Penguin's Lair - No Glide Suit", types: [] },
  { name: "Stealing the Show - 7+ Minikits", types: [] },
  { name: "The Joker's Masterpiece - Hostage", types: [] },
  { name: "Flight of the Bat - 10 Minikits", types: [] },
];
bingoList[17] = [
  { name: "Batboat Battle - 10 Minikits", types: [] },
  { name: "Buy Commissioner Gordon and Alfred", types: [] },
  { name: "Flight of the Bat - Red Brick", types: [] },
  { name: "In the Dark Night - 10 Minikits", types: [] },
  { name: "Little Fun at the Big Top - 10 Minikits", types: [] },
  { name: "Penguin's Lair - Red Brick", types: [] },
  { name: "To the Top of the Tower - Hostage", types: [] },
  { name: "Under the City - 10 Minikits", types: [] },
  { name: "Buy 3 Law Enforcement Characters", types: [] },
];
bingoList[18] = [
  { name: "Buy 5 Goons/Henchmen", types: [] },
  { name: "Double Vacuum Deposit", types: [] },
  { name: "In the Dark Night - Red Brick", types: [] },
  { name: "On the Rocks - 10 Minikits", types: [] },
  { name: "Rockin' the Docks - 10 Minikits", types: [] },
  { name: "The Joker's Masterpiece - 40k Studs", types: [] },
  { name: "Under the City - Out of Bounds Minikit", types: [] },
  { name: "The Lure of the Night - Hostage", types: [] },
  { name: "Harboring a Grudge - 7+ Minikits", types: [] },
];
bingoList[19] = [
  { name: "A Daring Rescue - 10 Minikits", types: [] },
  { name: "An Enterprising Theft - 3+ Minikits", types: [] },
  { name: "Bi-Plane Blast - Red Brick", types: [] },
  { name: "Breaking Blocks - 2+ Minikits", types: [] },
  { name: "Buy 3 Villain Red Bricks", types: [] },
  { name: "Dying of Laughter - 10 Minikits", types: [] },
  { name: "Grow 3 Poison Ivy Plants", types: [] },
  { name: "The Lure of the Night - 40k Studs", types: [] },
  { name: "To the Top of the Tower - No Wall Jumping", types: [] },
];
bingoList[20] = [
  { name: "To the Top of the Tower - No Magnet Suit", types: [] },
  { name: "The Lure of the Night - 3+ Minikits", types: [] },
  { name: "Stealing the Show - Red Brick", types: [] },
  { name: "Penguin's Lair - 10 Minikits", types: [] },
  { name: "Green Fingers - Hostage", types: [] },
  { name: "Collect 25 Minikits", types: [] },
  { name: "Arctic World - 2+ Minikits", types: [] },
  { name: "A Daring Rescue - No Room 1 Skip", types: [] },
];
bingoList[21] = [
  { name: "An Enterprising Theft - Hostage", types: [] },
  { name: "Arctic World - Hostage", types: [] },
  { name: "Breaking Blocks - Red Brick", types: [] },
  { name: "Buy Slam and Fast Build", types: [] },
  { name: "Dying of Laughter - 40k Studs", types: [] },
  { name: "Harboring a Grudge - 10 Minikits", types: [] },
  { name: "On the Rocks - Red Brick", types: [] },
  { name: "To the Top of the Tower - 10 Minikits", types: [] },
];
bingoList[22] = [
  { name: "An Enterprising Theft - 10 Minikits", types: [] },
  { name: "A Daring Rescue - Red Brick", types: [] },
  { name: "Arctic World - No Drop In Warps", types: [] },
  { name: "Breaking Blocks - 30k Studs", types: [] },
  { name: "Dying of Laughter - Hostage", types: [] },
  { name: "Stealing the Show - Super Villain", types: [] },
  { name: "The Lure of the Night - Red Brick", types: [] },
  { name: "The Riddler Makes a Withdrawal - 10 Minikits", types: [] },
];
bingoList[23] = [
  { name: "An Enterprising Theft - Red Brick", types: [] },
  { name: "Arctic World - 10 Minikits", types: [] },
  { name: "Breaking Blocks - Hostage", types: [] },
  { name: "Collect 1 Million Studs", types: [] },
  { name: "Dying of Laughter - 5+ Minikits", types: [] },
  { name: "Green Fingers - Red Brick", types: [] },
  { name: "Rockin' the Docks - Red Brick", types: [] },
  { name: "Stealing the Show - 10 Minikits", types: [] },
];
bingoList[24] = [
  { name: "Arctic World - 20k Studs", types: [] },
  { name: "Breaking Blocks - 10 Minikits", types: [] },
  { name: "Collect 7 Red Bricks", types: [] },
  { name: "The Joker's Masterpiece - Red Brick", types: [] },
  { name: "A Daring Rescue - Hostage", types: [] },
  { name: "Power Crazed Penguin - Villain Story", types: [] },
  { name: "Riddler's Revenge - Villain Story", types: [] },
  { name: "The Joker's Return - Villain Story", types: [] },
];
bingoList[25] = [
  { name: "Arctic World - Red Brick", types: [] },
  { name: "The Joker's Masterpiece - 10 Minikits", types: [] },
  { name: "The Lure of the Night - 10 Minikits", types: [] },
  { name: "Dying of Laughter - Red Brick", types: [] },
  { name: "To the Top of the Tower - Red Brick", types: [] },
  { name: "Green Fingers - 10 Minikits", types: [] },
  { name: "Villain Episode - Story", types: [] },
  { name: "Villain Episode - Free Play", types: [] },
  { name: "Bonus Level", types: [] },
];
