bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "1 Story Level using 1P2C",
    "1 Story Level with Ice Rink",
    "1 Story Level with Silhouettes/ Disguises",
    "1 Story Level with Zero Studs",
    "1-1 - 20k Studs",
    "1-1 - 3+ Minikits",
    "1-1 - 9+ Minikits",
    "1-1 - Hostage",
    "1-1 - Red Brick",
    "1-2 - 3+ Minikits",
    "1-2 - 40k Studs",
    "1-2 - 8+ Minikits",
    "1-2 - Hostage",
    "1-2 - Red Brick",
    "1-2 - Robin Only",
    "1-3 - 10 Minikits",
    "1-3 - 30k Studs",
    "1-3 - 7+ Minikits",
    "1-3 - No Drop In Warps",
    "1-3 - Red Brick",
    "1-4 - 40k Studs",
    "1-4 - 5+ Minikits",
    "1-4 - 9+ Minikits",
    "1-4 - Hostage",
    "1-4 - Red Brick",
    "1-5 - 10 Minikits",
    "1-5 - 40k Studs",
    "1-5 - 5+ Story Minikits",
    "1-5 - 7+ Minikits",
    "1-5 - Hostage",
    "1-5 - No Drop In Warps",
    "1-5 - Red Brick",
    "2 Super Statuses",
    "2-1 - 10 Minikits",
    "2-1 - 3+ Minikits",
    "2-1 - 40k Studs",
    "2-1 - Hostage",
    "2-1 - No Gliding",
    "2-1 - Red Brick",
    "2-2 - 10 Minikits",
    "2-2 - 15k Studs",
    "2-2 - 5+ Minikits",
    "2-2 - Red Brick",
    "2-3 - 5+ Minikits",
    "2-3 - 8+ Minikits",
    "2-3 - Hostage",
    "2-3 - No Room 1 Out of Bounds",
    "2-3 - No Room 3 Gliding",
    "2-3 - Out of Bounds Minikit",
    "2-3 - Red Brick",
    "2-3 - Super Hero",
    "2-4 - 10 Minikits",
    "2-4 - 30k Studs",
    "2-4 - 5+ Minikits",
    "2-4 - Hostage",
    "2-4 - No Bench Jump",
    "2-4 - No Turtle Skip",
    "2-4 - Red Brick",
    "2-5 - 15k Studs",
    "2-5 - 4+ Story Minikits",
    "2-5 - 6+ Minikits",
    "2-5 - 9+ Minikits",
    "2-5 - Hostage",
    "2-5 - No Glide Suit",
    "2-5 - Red Brick",
    "3 Hostages",
    "3 Story Levels with 1P2C",
    "3 Story Levels with Ice Rink",
    "3 Story Levels with Silhouettes/ Disguises",
    "3 Story Levels with Zero Studs",
    "3 Vehicle Levels Free Play",
    "3-1 - 30k Studs",
    "3-1 - 4+ Story Minikits",
    "3-1 - 6+ Minikits",
    "3-1 - 9+ Minikits",
    "3-1 - Hostage",
    "3-1 - No Room 2/3 Gliding",
    "3-1 - No Vacuum Skip",
    "3-1 - Red Brick",
    "3-1 - Toxic Goo Minikit",
    "3-2 - 30k Studs",
    "3-2 - 4+ Minikits",
    "3-2 - 9+ Minikits",
    "3-2 - Hostage",
    "3-2 - No Candy Cane Jump",
    "3-2 - Red Brick",
    "3-3 - 10 Minikits",
    "3-3 - 15k Studs",
    "3-3 - 7+ Minikits",
    "3-3 - Red Brick",
    "3-4 - 2+ Minikits",
    "3-4 - 35k Studs",
    "3-4 - 8+ Minikits",
    "3-4 - Hostage",
    "3-4 - No Disco Skip",
    "3-4 - No Wall Jumping",
    "3-4 - Red Brick",
    "3-5 - 10 Minikits",
    "3-5 - 40k Studs",
    "3-5 - 5+ Story Minikits",
    "3-5 - 7+ Minikits",
    "3-5 - Hostage",
    "3-5 - No Magnet Suit",
    "3-5 - No Wall Jumping",
    "3-5 - Red Brick",
    "4 Super Statuses",
    "4-1 - 10 Minikits",
    "4-1 - 30k Studs",
    "4-1 - 4+ Story Minikits",
    "4-1 - 7+ Minikits",
    "4-1 - Hostage",
    "4-1 - No Wall Jumping",
    "4-1 - Red Brick",
    "4-2 - 10 Minikits",
    "4-2 - 30k Studs",
    "4-2 - 4+ Story Minikits",
    "4-2 - 6+ Minikits",
    "4-2 - Hostage",
    "4-2 - Red Brick",
    "4-3 - 4+ Minikits",
    "4-3 - 40k Studs",
    "4-3 - 9+ Minikits",
    "4-3 - Hostage",
    "4-3 - Red Brick",
    "4-4 - 10 Minikits",
    "4-4 - 25k Studs",
    "4-4 - 3+ Minikits",
    "4-4 - Hostage",
    "4-4 - Red Brick",
    "4-5 - 2+ Minikits",
    "4-5 - 30k Studs",
    "4-5 - 9+ Minikits",
    "4-5 - Hostage",
    "4-5 - Red Brick",
    "5-1 - 4+ Story Minikits",
    "5-1 - 6+ Minikits",
    "5-1 - 9+ Minikits",
    "5-1 - Hostage",
    "5-1 - No Birthday Skip",
    "5-1 - Red Brick",
    "5-1 - Super Villain",
    "5-2 - 1 Character",
    "5-2 - 10 Minikits",
    "5-2 - 5+ Story Minikits",
    "5-2 - 7+ Minikits",
    "5-2 - Hostage",
    "5-2 - Red Brick",
    "5-2 - Super Villain",
    "5-3 - 10 Minikits",
    "5-3 - 20k Studs",
    "5-3 - 7+ Minikits",
    "5-3 - Red Brick",
    "5-4 - 30k Studs",
    "5-4 - 4+ Story Minikits",
    "5-4 - 6+ Minikits",
    "5-4 - 8+ Minikits",
    "5-4 - Hostage",
    "5-4 - No Room 1 Skip",
    "5-4 - Red Brick",
    "5-5 - 20k Studs",
    "5-5 - 3+ Minikits",
    "5-5 - 9+ Minikits",
    "5-5 - Hostage",
    "5-5 - No Drop In Warps",
    "5-5 - Red Brick",
    "6 Hostages",
    "6 Super Statuses",
    "6-1 - 30k Studs",
    "6-1 - 4+ Story Minikits",
    "6-1 - 6+ Minikits",
    "6-1 - 9+ Minikits",
    "6-1 - Hostage",
    "6-1 - No Boss Skip",
    "6-1 - Red Brick",
    "6-2 - 10 Minikits",
    "6-2 - 15k Studs",
    "6-2 - 4+ Minikits",
    "6-2 - Red Brick",
    "6-3 - 40k Studs",
    "6-3 - 5+ Minikits",
    "6-3 - 9+ Minikits",
    "6-3 - Hostage",
    "6-3 - Red Brick",
    "6-4 - 40k Studs",
    "6-4 - 5+ Minikits",
    "6-4 - 9+ Minikits",
    "6-4 - Hostage",
    "6-4 - Red Brick",
    "6-5 - 4+ Minikits",
    "6-5 - 40k Studs",
    "6-5 - 9+ Minikits",
    "6-5 - Hostage",
    "6-5 - Red Brick",
    "9 Hostages",
    "Buy 10 Data",
    "Buy 2 Suit Upgrades",
    "Buy 2 Villain Red Bricks",
    "Buy 2 Villains",
    "Buy 3 Goons",
    "Buy 3 Law Enforcement Characters",
    "Buy 3 Villain Red Bricks",
    "Buy 4 Suit Upgrades",
    "Buy 5 Goons/Henchmen",
    "Buy All Police Road Vehicles",
    "Buy Batgirl and Nightwing",
    "Buy Bruce Wayne and Private Jet",
    "Buy Commissioner Gordon and Alfred",
    "Buy Robin's Submarine",
    "Buy Slam and Fast Build",
    "Collect 1 Million Studs",
    "Collect 10 Minikits",
    "Collect 15 Minikits",
    "Collect 20 Minikits",
    "Collect 25 Minikits",
    "Collect 3 Red Bricks",
    "Collect 5 Red Bricks",
    "Collect 500k Studs",
    "Collect 7 Red Bricks",
    "Collect All Suits",
    "Custom Character Free Play",
    "Double Vacuum Deposit",
    "Episode 1 Story",
    "Episode 2 Story",
    "Episode 3 Story",
    "Episode 4 Story",
    "Episode 5 Story",
    "Episode 6 Story",
    "Grow 3 Poison Ivy Plants",
    "Hero Episode - Story",
    "Ride 3 Stud Rides",
    "Villain Episode - Story",
    "Watch 3 Cutscenes"
];
