bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "1 star rank 2 missions",
    "1000 gold 2 missions",
    "11 gold greenies",
    "12 gems Clockworks",
    "12 gems Haunted",
    "12 gems Mines",
    "12 gems Treacherous",
    "1500 gold one mission",
    "2 Toad escort missions",
    "2 gems 5 mansions",
    "2 missions 25 seconds off WR",
    "20 total gems",
    "3 bonus missions",
    "3 boss missions",
    "3 floor hunter",
    "3 floor polterpup",
    "3 missions 25 seconds off WR",
    "3 missions Clockworks",
    "3 missions Gloomy",
    "3 missions Haunted",
    "3 missions Mines",
    "3 missions Treacherous",
    "4 bonus rooms",
    "4 floor rush",
    "4 gems 3 mansions",
    "5 gold bloonberries",
    "6 Greenie Types",
    "6 total missions completed",
    "7 gems Clockworks",
    "7 gems Haunted",
    "7 gems Mines",
    "7 gems Treacherous",
    "A-1 and A-3 Any% route",
    "A-4 Boo and Booper Trooper",
    "All Polterpup missions",
    "All gems Gloomy",
    "All gold greenies Clockworks",
    "All gold greenies Gloomy",
    "All gold greenies Haunted",
    "All gold greenies Mines",
    "All gold greenies Treacherous",
    "Die 2 times different mansions",
    "Every Poltergeist variety",
    "Every non-special normal ghost variety",
    "Every strong ghost variety",
    "Inspect 4 unique fake doors",
    "Kill 5 gold critter types",
    "King Boo and Boolossus",
    "Low% 2 levels or bonus missions",
    "Low% 3 levels or bonus missions",
    "One mission from each mansion",
    "Take 200 damage one mission",
    "Trifecta two different sets"
];
