bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "11 gold greenies",
    "1500 gold 3 missions",
    "2 Toad escort missions",
    "2 missions 20 seconds off WR",
    "20 total gems",
    "2000 gold one mission",
    "3 bonus missions",
    "3 boss missions",
    "3 floor normal hunter",
    "3 floor normal polterpup",
    "3 missions 20 seconds off WR",
    "3 missions Clockworks",
    "3 missions Mines",
    "4 bonus missions",
    "4 boss missions",
    "4 floor normal rush",
    "4 missions Gloomy",
    "4 missions Haunted",
    "4 missions Treacherous",
    "5 bonus rooms",
    "5 gold bloonberries",
    "6 Greenie Types",
    "8 gems Clockworks",
    "8 gems Gloomy",
    "8 gems Haunted",
    "8 gems Mines",
    "8 gems Treacherous",
    "8 total missions completed",
    "A-1 and A-3 Any% route",
    "A-4 Boo and Booper Trooper",
    "All Polterpup levels",
    "All bonus missions",
    "All gems Clockworks",
    "All gems Gloomy",
    "All gems Haunted",
    "All gems Mines",
    "All gems Treacherous",
    "All gold greenies Clockworks",
    "All gold greenies Gloomy",
    "All gold greenies Haunted",
    "All gold greenies Mines",
    "All gold greenies Treacherous",
    "Die 3 times different missions",
    "Every Poltergeist variety",
    "Every non-special normal ghost variety",
    "Every strong ghost variety",
    "Kill one of each gold critter type",
    "King Boo and Boolossus",
    "Low% 2 levels or bonus missions",
    "Low% a level or bonus mission",
    "One mission from each mansion",
    "Take 150 health 3 missions",
    "Trifecta"
];
