bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Catch 3 Golden Mice",
    "Catch 3 Optional Portrait Ghosts",
    "Catch 3 Speedy Spirits",
    "Catch All Optional Portrait Ghosts",
    "Catch RNG Gold Mouse in Sealed Room",
    "Clear Courtyard",
    "Clear Hidden and Sealed Room",
    "Collect 10 Boos",
    "Collect 10 Gold Bars",
    "Collect 2 Silver Diamonds",
    "Collect 5 Blue Gems",
    "Collect 5 Boos",
    "Collect 5 Green Gems",
    "Collect 5 Large Pearls",
    "Collect 5 Red Gems",
    "Collect 500 Bills",
    "Collect 500 Coins",
    "Collect All Area 2 Boos",
    "Collect All Big Hearts",
    "Collect All Blackout Speedy Spirits",
    "Collect All Blue Gems",
    "Collect All Green Gems",
    "Collect All Mario Items",
    "Collect All Red Gems",
    "Collect All Silver Diamonds",
    "Collect Sealed Room Speedy Spirit",
    "Collect the Fire Element",
    "Collect the Ice Element",
    "Collect the Plant Gold Diamond",
    "Collect the Water Element",
    "Defeat Biff Atlas",
    "Defeat Bogmire",
    "Defeat Boolossus",
    "Defeat Floating Whirlindas",
    "Defeat Fortune Teller",
    "Defeat Sir Weston",
    "Defeat Sue Pea",
    "Defeat Uncle Grimmly",
    "Defeat Van Gore",
    "Talk to all Toads"
];
