bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "\"Clear\" 5 Rooms in the Blackout",
    "30 Gold Bars",
    "750 Bills",
    "750 Coins",
    "All Area 1 Boos",
    "All Area 3 Boos",
    "All Basement Boos",
    "All Unique Chests",
    "Capture Breaker Room Speedy Spirit",
    "Capture Jarvis",
    "Capture Petunia",
    "Capture Shivers",
    "Catch 5 Speedy Spirits",
    "Catch all Cheese Gold Mice",
    "Cheer Up all Toads (Excluding Blackout)",
    "Clear 5 Rooms in Normal Mansion (Not Training Room)",
    "Clear all Attic Rooms",
    "Clear all Outside Areas",
    "Clear all Washrooms and Bathrooms",
    "Clockworks Boo",
    "Collect 5 Rubies",
    "Collect 50 Small Pearls",
    "Collect 6 Emeralds",
    "Collect 6 Sapphires",
    "Collect Grimmly’s Key",
    "Collect Sealed Room Key",
    "Collect all Basement Keys",
    "Collect all Large Hearts (Restores 50 HP)",
    "Defeat 3 Fire Ghosts",
    "Defeat 3 Ice Ghosts",
    "Defeat all Blackout Speedy Spirits",
    "Destroy all Unique Fake Doors (Excluding Blackout)",
    "Get 2 Silver Diamonds",
    "Get 20 Gold Bars",
    "Get 4 Mario Items",
    "Get 650 Bills",
    "Get 650 Coins",
    "Get Chauncey’s Key",
    "Get Mario’s Shoe",
    "Get Plant Gold Diamond",
    "Get Secret Altar Sapphire",
    "Get Van Gore’s Key",
    "Get all Element Pickups",
    "Mirror warp at 5 different mirrors",
    "Spin all the Fans",
    "Take down All Posters",
    "Talk to Blackout Toad",
    "Unlock all Doors Guarded by Area Keys",
    "Water a Plant in 5 Different Rooms",
    "Water all Plants on the 2 Balconies"
];
