bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "4 Standards Below PR on BC 3lap",
    "4 Standards Below PR on BC flap",
    "4 Standards Below PR on BP 7lap",
    "4 Standards Below PR on BP flap",
    "4 Standards Below PR on DC 3lap",
    "4 Standards Below PR on DC flap",
    "4 Standards Below PR on DDD 3lap",
    "4 Standards Below PR on DDD flap",
    "4 Standards Below PR on DDJ 3lap",
    "4 Standards Below PR on DDJ flap",
    "4 Standards Below PR on DKM 3lap",
    "4 Standards Below PR on DKM flap",
    "4 Standards Below PR on LC 3lap",
    "4 Standards Below PR on LC flap",
    "4 Standards Below PR on MB 3lap",
    "4 Standards Below PR on MB flap",
    "4 Standards Below PR on MCT 3lap",
    "4 Standards Below PR on MCT flap",
    "4 Standards Below PR on MaC 3lap",
    "4 Standards Below PR on MaC flap",
    "4 Standards Below PR on PB 3lap",
    "4 Standards Below PR on PB flap",
    "4 Standards Below PR on RR 3lap",
    "4 Standards Below PR on RR flap",
    "4 Standards Below PR on SL 3lap",
    "4 Standards Below PR on SL flap",
    "4 Standards Below PR on WC 2lap",
    "4 Standards Below PR on WC flap",
    "4 Standards Below PR on WS 3lap",
    "4 Standards Below PR on WS flap",
    "4 Standards Below PR on YC 3lap",
    "4 Standards Below PR on YC flap",
    "BC Driftless",
    "BC Shortcut (Either One)",
    "BP Driftless",
    "Blow Up",
    "Blue Shell Dodge",
    "Blue Shell Yourself",
    "Complete 1 Lap of a Track Backwards (No BP)",
    "Complete All Cup Tour in 1st Place",
    "Cross the DDD Finish Line in Yellow Sand",
    "DC Driftless",
    "DDD Driftless",
    "DDJ Driftless",
    "DDJ Invisible Bridge Post Hitbox",
    "DDJ Shortcut Jump (w/ shroom)",
    "DDJ Shroomless",
    "DDJ Small Bridge",
    "DK Shortcut (x3)",
    "DKM Driftless",
    "Dodge 3 Red Shells",
    "Drown in DC",
    "Drown in PB",
    "Flower Cup 150cc with Randomized Character/Kart",
    "Flower Cup Mirror with Randomized Character/Kart",
    "Get Combo'd by a Car",
    "Get Eaten by The DDD Cactus Monster",
    "Get a Top 5 in Time Trials",
    "Go Backwards into the DKM Cannon",
    "Go through YC Secret Tunnel",
    "Goomba Mushroom",
    "Grab a Falling Rainbow Road Star",
    "Hit 3 Cataquacks",
    "Hit Both Chainchomps (Item doesn't count)",
    "Hit Leg and Head of Blue Dino",
    "Hit a Freezie on SL (x3)",
    "LC Driftless",
    "Lose in Balloon Battle",
    "Lose in Bomb-omb Blast",
    "Lose in Shine Thief",
    "MB Boost Panel Strat (x3)",
    "MB Driftless",
    "MB Pipe Strat",
    "MB Shortcut",
    "MCT Driftless",
    "MCT Purple Path (x3)",
    "MaC Driftless",
    "Mushroom Cup 150cc with Randomized Character/Kart",
    "Mushroom Cup Mirror with Randomized Character/Kart",
    "PB Driftless",
    "PB Pipe (x3)",
    "PB Ramp (x3)",
    "Play RR (and finish)",
    "RR Driftless",
    "SL Driftless",
    "Special Cup 150cc with Randomized Character/Kart",
    "Special Cup Mirror with Randomized Character/Kart",
    "Star Cup 150cc with Randomized Character/Kart",
    "Star Cup Mirror with Randomized Character/Kart",
    "Steal a Special Item",
    "Steal an Item with a Mushroom",
    "Successful Pool Skip (x3)",
    "Take Either DDD Shroom Cut Shroomless",
    "Take the Daisy Cruiser Cannon",
    "WC 9lap in VS. Mode",
    "WC Driftless",
    "WS Driftless",
    "WS Shortcut",
    "YC Driftless",
    "Yoshi's Circuit Yolo (x3)",
    "Z-Tech an Entire Lap"
];
