bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Bob-omb Avenue",
    "Bob-omba",
    "Boo Cemetary",
    "Chain Chomp",
    "Dance Stage",
    "Duel Tower Floor 1",
    "Duel Tower Floor 2",
    "Duel Tower Floor 3",
    "Goomba House",
    "Goombob Manor",
    "Horror Condo 1st Floor",
    "Horror Condo 2nd Floor",
    "Horror Condo Basement",
    "Ice Game Room",
    "Ice Stadium",
    "Jungle Game Hut",
    "Klepto Ruins",
    "Lakitu House",
    "Loch Dorrie",
    "Mario Vaudeville",
    "Mr. I",
    "Mushroom Beacon",
    "Mushroom Condo 2nd Floor",
    "Mushroom Condo 3rd Floor",
    "Mushroom Condo Basement",
    "Mushroom Condo Rooftop",
    "Mushroom Field",
    "Mushroom Library",
    "Mushroom Pool",
    "Mushroom Stadium",
    "Petal House",
    "Pokey Desert",
    "Spear Thicket",
    "Sushi Cliff",
    "The Hammer",
    "Thwomp House",
    "Town Game Room A",
    "Town Game Room B",
    "Town Koopa Bank",
    "Train Station",
    "Ukiki House"
];
