bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "100 coins",
    "3+ stacked enemies",
    "A regular mario level",
    "Airship",
    "Auto/music level",
    "Autoscroller",
    "Beat 10+ stages",
    "Block Snake",
    "Bob-omb excavation",
    "Boo block",
    "Boom Boom",
    "Boos out of a block",
    "Boss fight",
    "Cat Bowser",
    "Cat/Superball Mario",
    "Claw",
    "Clown car",
    "Death trap",
    "Dev door/item",
    "Die to a blooper",
    "Die to a dry bones",
    "Die to an angry wiggler",
    "Die to fire",
    "German level",
    "Get a WR",
    "Get crushed",
    "Grab 3 red coins",
    "Grab the axe in castle",
    "Kaizo block",
    "Lakitu cloud",
    "Naked pipe",
    "New Super Mario Bros U level",
    "Pick a door",
    "Pipe hat",
    "Puzzle level",
    "Ride a thwomp",
    "Rising lava/poison",
    "See-saw",
    "Star power genocide",
    "Sun/Moon",
    "Super Mario 1 level",
    "Super Mario 3 level",
    "Super Mario 3d world level",
    "Switch/rhythm blocks",
    "Too many spikes",
    "Twister",
    "Under 60 seconds",
    "Vertical sublevel",
    "Water level",
    "Yoshi murder"
];
