bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "1st 4 races in a row",
    "2 or more Daisys in the race",
    "2 or more players uses Daisy",
    "3 blues in one race",
    "3 or more bloopers in a single race",
    "3 shocks in one race",
    "4 or more luck tracks",
    "A track gets repicked and played",
    "Avoid a bomb",
    "Beat someone by less than 200 milliseconds",
    "Blooper in 9th",
    "Bomb Snipe someone",
    "Bring a POW down to last",
    "Bring a dodge up to 3rd place",
    "Bring shock up to 7th place",
    "Bumped off by a light weight",
    "Canon Dodge",
    "Cheater combo (Star Mega)",
    "Dodge a blue with a shroom",
    "Dodge a shock or blue by falling off",
    "Dodge blue shell with a ground shroom",
    "Dodge red without any items",
    "Dodge shock 5 times",
    "Dodge the shock and get 1st",
    "Dodging a shock with a bullet bill",
    "Don’t pull/get passed a TC in 4 races in a row",
    "Fail and recovery (12th to 1st)",
    "Falling into lava",
    "Falling off 3 times in a single race",
    "Finding a star on the ground",
    "Finished at the same spot twice in a row",
    "Frontrun all race long",
    "Frontrun for 2 laps and die last lap",
    "Get 1 snipe",
    "Get 1st place 3 times",
    "Get Blue shelled off",
    "Get blue shelled when not in 1st",
    "Get lag bumped off",
    "Get mario karted (1st to 12th)",
    "Get sniped spammed",
    "Get stared 3 times in a single race",
    "Get target shocked",
    "Get three snipes in one race",
    "Getting a single shroom in last place",
    "Getting bombed",
    "Getting focused by someone with 3 greens",
    "Getting hit and stared right after",
    "Getting killed on the last turn / straight",
    "Getting stop trolled",
    "Getting your item box stealed",
    "Got your own track picked",
    "Greening a goomba intentionally and using his shroom",
    "Hit 3 people with triple greens",
    "Hit a European player (green line)",
    "Hit a Japanese player (red line)",
    "Hit a trick snipe",
    "Hit an American player (blue line)",
    "Hit an Oceanian player (yellow line)",
    "Hit by laggy thundercloud",
    "Hit by shell from behind while trailing",
    "Hit someone midair without a red",
    "Hit your own back a later in the track",
    "Instant karma",
    "Lap 1 shock",
    "Lose item to Chain Chomp, Cataquack, etc.",
    "More than half of room is Funky Flame Runner",
    "Mupbed off by Funky Kong",
    "No items in the whole race",
    "No shock 2 races in a row",
    "No shock in one race",
    "POW in 8th",
    "Passing a thundercloud first try",
    "Play 6 luck tracks",
    "Play a 100cc race",
    "Play a whole cup",
    "Repicked Track gets played",
    "Shock happens after 40 seconds or less",
    "Single green or red in 6th or lower",
    "Sniping yourself",
    "Somebody is using a kart",
    "Someone disconnects",
    "Someone has a \"player\" mii",
    "Squished by Thwomp",
    "Start and Finish a race in 1st",
    "Use every type of shrooms in a single race",
    "Use every yellow item in a single race7",
    "Wii wheel user",
    "Win 1 mirror race",
    "You end up no passing the line",
    "You failed a respawn boost",
    "You failed a standstill mini turbo",
    "You failed your startup boost",
    "You get disconnected",
    "Your own shock dodges no one"
];
