bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Beat a player with at least 5k more VR than you",
    "Bump another player off the road",
    "Collide with at least 4 different enemies on a single race",
    "Do any clock hands shortcut on Tick-Tock Clock",
    "Do the Big Blue anti-gravity shortcut",
    "Do the Dk Mountain gap shortcut",
    "Do the Dk Summit double shortcut",
    "Do the Dragon Driftway gap shortcut",
    "Do the Mushroom gorge gap jump",
    "Do the Snow Land big shortcut",
    "Do the Wii Rainbow Road Gap Jump",
    "Do the double path switch shortcut in MK8 Rainbow Road",
    "Do the main Piranha Plant Cove shortcut",
    "Dodge Blue Shell with a Mushroom",
    "Dodge a red shell with a Bob-omb",
    "Finish all 3 laps while in 1st place",
    "Finish any track with moving trafic without bumping into a car",
    "Finish in 5th place while spaming every item",
    "Get 1st on a City course while playing with a WiiU/Switch DLC character",
    "Get 1st place 3 times in a row",
    "Get 1st place only using Mushrooms or Coins",
    "Get 1st place while on a kart",
    "Get 1st place while using an inside drift bike",
    "Get 1st place without tricking",
    "Get 1st place without using any type of Mushrooms",
    "Get Last place on Baby Park",
    "Get a Boo while in last place",
    "Get a Rupee or Bell",
    "Get a coin item while having 10 coins",
    "Get a shock while in 9th place",
    "Get a triple item while in 8th place or lower",
    "Get a weird Lakitu respawn animation",
    "Get either a Star or Golden Mushroom on 2nd place",
    "Get hit by 4 items within 1 minute",
    "Get hit by a Boomerang Flower thrown behind",
    "Get hit by a Bullet Bill",
    "Get hit by a Green Shell while in the cannon sequence",
    "Get hit by a Lighting while in last place",
    "Get hit by a Super Horn while in 1st place",
    "Get hit by any item while holding Triple Banana",
    "Get more than 3 mushroom in your 2 item slots",
    "Get the Blooper while playing with any color customizable character",
    "Get the Crazy 8 while playing with a character added in MK8/MK8D",
    "Get the Piranha plant while playing with any color of Yoshi",
    "Get the Zelda/Yoshi's Island shortcut route",
    "Get top 2 with the lowest speed combo",
    "Get top 2 without drifting",
    "Get top 3 in 4 City tracks",
    "Get top 3 on Baby Park while playing with any baby character",
    "Get your stage be picked and be the only player who pick that option",
    "Get your stage picked 3 times in a row",
    "Hit 2 players using the same bullet bill",
    "Hit 2 players with the same fire flower",
    "Hit a player directly with a Bob-omb snipe",
    "Hit a player directly with a banana snipe",
    "Hit yourself with your own Blue Shell",
    "Hit yourself with your own item",
    "Lobby full of same country players excluding",
    "Lose to a player with at least 5k less Vr than you",
    "Play Mario with the standart kart combo on Mario Kart Stadium",
    "Play a Wii track while playing with the Mii characterr",
    "Play a collaboration track while using a character or kart from it",
    "Shock Dodge",
    "Trick on a Half-pipe from a track not present in Mario Kart Wii",
    "Use a blueshell while playing with a koopa-like species character",
    "Use another player's mushroom",
    "With a Boo steal a Coin from a player"
];
