bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList =
[
    "Beat Acid Man With Only Mega Buster",
    "Beat Acid Man With Only Power Gear",
    "Beat Acid Man Without Using Gears",
    "Beat Blast Man With Only Mega Buster",
    "Beat Blast Man With Only Speed Gear",
    "Beat Blast Man Without Using Gears",
    "Beat Block Man With Only Mega Buster",
    "Beat Block Man With Only Speed Gear",
    "Beat Block Man Without Using Gears",
    "Beat Bounce Man With Only Mega Buster",
    "Beat Bounce Man With Only Power Gear",
    "Beat Bounce Man Without Using Gears",
    "Beat Fuse Man With Only Mega Buster",
    "Beat Fuse Man With Only Power Gear",
    "Beat Fuse Man Without Using Gears",
    "Beat Impact Man With Only Mega Buster",
    "Beat Impact Man With Only Speed Gear",
    "Beat Impact Man Without Using Gears",
    "Beat Torch Man With Only Mega Buster",
    "Beat Torch Man With Only Speed Gear",
    "Beat Torch Man Without Using Gears",
    "Beat Tundra Man Man Without Using Gears",
    "Beat Tundra Man With Only Mega Buster",
    "Beat Tundra Man With Only Power Gear",
    "Beat Wily Machine 11 With Only Mega Buster",
    "Beat Wily Machine 11 Without Using Gears",
    "Beat Yellow Devil With Only Mega Buster",
    "Beat Yellow Devil Without Using Gears",
    "Beat the Game on Casual or Higher",
    "Beat the Game on Newcomer or Higher",
    "Beat the Game on Normal or Higher",
    "Beat the Game on Superhero or Higher",
    "Complete Acid Man's Stage Without Dying",
    "Complete Blast Man's Stage Without Dying",
    "Complete Block Man's Stage Without Dying",
    "Complete Bounce Man's Stage Without Dying",
    "Complete Fuse Man's Stage Without Dying",
    "Complete Impact Man's Stage Without Dying",
    "Complete Torch Man's Stage Without Dying",
    "Complete Tundra Man's Stage Without Dying",
    "Complete Wily Stage 1 Without Dying",
    "Complete Wily Stage 2 Without Dying",
    "Complete Wily Stage 3 Without Dying",
    "Complete Wily Stage 4 Without Dying",
    "Finish Off Acid Man With Block Dropper",
    "Finish Off Acid Man With Double Gear Active",
    "Finish Off Blast Man With Blazing Torch",
    "Finish Off Blast Man With Double Gear Active",
    "Finish Off Block Man With Chain Blast",
    "Finish Off Block Man With Double Gear Active",
    "Finish Off Bounce Man With Double Gear Active",
    "Finish Off Bounce Man With Pile Driver",
    "Finish Off Fuse Man With Bounce Ball",
    "Finish Off Fuse Man With Double Gear Active",
    "Finish Off Impact Man With Acid Barrier",
    "Finish Off Impact Man With Double Gear Active",
    "Finish Off Torch Man With Double Gear Active",
    "Finish Off Torch Man With Tundra Storm",
    "Finish Off Tundra Man With Double Gear Active",
    "Finish Off Tundra Man With Scramble Thunder",
    "Finish Off Wily Machine 11 With Double Gear Active",
    "Finish Off Yellow Devil With Double Gear Active",
    "Get 3 Beat Calls From the Shop",
    "Get 3 Eddie Calls From the Shop",
    "Get 3 Pierce Protectors",
    "Get 9 Energy Tanks",
    "Get 9 Weapon Tanks",
    "Get Every Part From the Shop",
    "Get a Mystery Tank",
    "Get a Super Guard",
    "Get the Auto Charge Chip From the Shop",
    "Get the Awakener Chip From the Shop",
    "Get the Bolt Catcher From the Shop",
    "Get the Buddy Call Plus From the Shop",
    "Get the Buster Plus Chip From the Shop",
    "Get the Capsule Catcher From the Shop",
    "Get the Cooling System From the Shop",
    "Get the Cooling System Infinite From the Shop",
    "Get the Energy Balancer From the Shop",
    "Get the Energy Balancer Neo From the Shop",
    "Get the Energy Catcher From the Shop",
    "Get the Energy Dispenser From the Shop",
    "Get the Max Amount of All Items",
    "Get the Mystery Chip From the Shop",
    "Get the Power Shield From the Shop",
    "Get the Shock Absorber From the Shop",
    "Get the Speed Gear Booster From the Shop",
    "Get the Spike Boots From the Shop",
    "Get the Tank Container From the Shop",
    "Max Out Your Lives"
];
