bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "1 Adult Sheegoth",
    "1 Chozo Save Station",
    "1 Elite Pirate",
    "1 Large Enemy using Flamethrower (Magmoor+)",
    "1 Magmoor Save Station",
    "1 Major Boss",
    "1 Map Station",
    "1 Mines Save Station",
    "1 Missile Station",
    "1 Phendrana Save Station",
    "1 Plated Beetle",
    "1 Tallon Save Station",
    "1 lap around the Geothermal Core Spider Track",
    "2 Adult Sheegoth",
    "2 Chozo Save Stations",
    "2 Elite Pirates",
    "2 Magmoor Save Stations",
    "2 Major Bosses",
    "2 Map Stations",
    "2 Mines Save Stations",
    "2 Minor Bosses",
    "2 Missile Stations",
    "2 Phendrana Save Stations",
    "2 Plated Beetles",
    "3 Adult Sheegoth",
    "3 Elite Pirates",
    "3 Major Bosses",
    "3 Map Stations",
    "3 Minor Bosses",
    "3 Phendrana Save Stations",
    "4 Adult Sheegoth",
    "4 Major Bosses",
    "4 Minor Bosses",
    "4 Phendrana Save Stations",
    "5 Minor Bosses",
    "Activate the Observatory",
    "All 3 Vanilla Beam Location Items",
    "All Hall of the Elders Bomb Slots",
    "Arbor Chamber Item",
    "Biohazard Containment Item",
    "Boost Ball",
    "Boost in 10 Spinners",
    "Boost in 5 Spinners",
    "Boost in 7 Spinners",
    "Break 2 Bendenzium Objects",
    "Break 2 Cordite Objects",
    "Break 4 Bendenzium Objects",
    "Break 4 Cordite Objects",
    "Break 8 Bendenzium Objects",
    "Clear Flying Pirates in 3 Rooms",
    "Clear Flying Pirates in 6 Rooms",
    "Clear Flying Pirates in 9 Rooms",
    "Clear Ghosts in 2 Rooms",
    "Clear Ghosts in 4 Rooms",
    "Clear Ghosts in 6 Rooms",
    "Clear Hunter Metroids in Fungal Hall A",
    "Clear Normal Metroids in 1 Room",
    "Clear Normal Metroids in 3 Rooms",
    "Clear Normal Metroids in 5 Rooms",
    "Clear Shadow Pirates in 2 Rooms",
    "Clear Shadow Pirates in 4 Rooms",
    "Clear Shadow Pirates in 6 Rooms",
    "Cloaked Drone",
    "Defeat 3 Ice Pirates using Ice Spreader",
    "Defeat 3 Plasma Pirates using Flamethrower",
    "Defeat 3 Power Pirates using Super Missiles",
    "Defeat 3 Wave Pirates using Wavebuster",
    "Duplicate/Nothing Item",
    "Dynamo (Upper) Item",
    "Elder Chamber Item",
    "Flaahgra",
    "Flamethrower",
    "Furnace (Upper) Item",
    "Grapple Beam",
    "Gravity Chamber (Lower) Item",
    "Gravity Chamber (Upper) Item",
    "Gravity Suit",
    "Have 1 Beam Combo",
    "Have 1 Power Bomb Expansion",
    "Have 1 Suit",
    "Have 100 Missiles (Capacity)",
    "Have 12 E-Tanks",
    "Have 130 Missiles (Capacity)",
    "Have 2 Beam Combos",
    "Have 2 Power Bomb Expansions",
    "Have 2 Suits",
    "Have 3 Beam Combos",
    "Have 3 E-Tanks",
    "Have 3 Power Bomb Expansions",
    "Have 3 Suits",
    "Have 4 Beam Combos",
    "Have 4 Beams",
    "Have 4 Power Bomb Expansions",
    "Have 4 Visors",
    "Have 40 Missiles (Capacity)",
    "Have 6 E-Tanks",
    "Have 70 Missiles (Capacity)",
    "Have 9 E-Tanks",
    "Have Morph Ball + 4 Ball Upgrades",
    "Hive Mecha",
    "Ice Beam",
    "Ice Spreader",
    "Incinerator Drone",
    "Life Grove Ghosts",
    "Life Grove Tunnel Item",
    "Magmoor Workstation Item",
    "Main Plaza (Tree) Item",
    "Main Power Bombs",
    "Meta Ridley",
    "Metroid Quarantine B Item",
    "Morph Ball Bombs",
    "Omega Pirate",
    "Phazon Elite",
    "Phazon Mining Tunnel Item",
    "Phazon Suit",
    "Phendrana Shorelines (Spider Track) Item",
    "Plasma Beam",
    "Plasma Processing Item",
    "Processing Center Access Item",
    "Quarantine Monitor Item",
    "Research Core Item",
    "Research Lab Hydra Item",
    "Ruined Courtyard Item",
    "Ruined Gallery (Tunnel) Item",
    "Space Jump Boots",
    "Spider Ball",
    "Storage Cave Item",
    "Storage Depot A Item",
    "Sunchamber (Ghosts) Item",
    "Super Missiles",
    "Thardus",
    "Thermal Visor",
    "Tower of Light Item",
    "Training Chamber Item",
    "Use a Save Station in 3 Regions",
    "Use a Save Station in 4 Regions",
    "Varia Suit",
    "Wave Beam",
    "Wavebuster",
    "X-Ray Visor"
];
