bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "1 Agon Save Stations",
    "1 Sanctuary Save Stations",
    "1 Torvus Save Stations",
    "2 Agon Save Stations",
    "2 Sanctuary Save Stations",
    "2 Torvus Save Stations",
    "3 Agon Save Stations",
    "3 Sanctuary Save Stations",
    "3 Torvus Save Stations",
    "4 Agon Save Stations",
    "4 Sanctuary Save Stations",
    "4 Torvus Save Stations",
    "5 Agon Save Stations",
    "5 Torvus Save Stations",
    "Aerie Item",
    "Amber Translator",
    "Annihilator Beam",
    "Boost Ball",
    "Cobalt Translator",
    "Collect 1 Dark Agon Keys",
    "Collect 1 Dark Torvus Keys",
    "Collect 1 Ing Hive Keys",
    "Collect 2 Dark Agon Keys",
    "Collect 2 Dark Torvus Keys",
    "Collect 2 Ing Hive Keys",
    "Collect 3 Dark Agon Keys",
    "Collect 3 Dark Torvus Keys",
    "Collect 3 Ing Hive Keys",
    "Collect all Dark upgrades (Beam, Suit, Visor)",
    "Collect all Light upgrades (Beam, Suit)",
    "Complete the Grand Windchamber Puzzle",
    "Culling Chamber Item",
    "Dark Beam",
    "Dark Oasis Item",
    "Dark Suit",
    "Dark Visor",
    "Darkburst",
    "Deactivate the Crypt Force Field",
    "Defeat 1 Guardian",
    "Defeat 2 Guardians",
    "Defeat 2 Minor Bosses",
    "Defeat 2 Sub-Guardians",
    "Defeat 3 Guardians",
    "Defeat 3 Minor Bosses",
    "Defeat 3 Sub-Guardians",
    "Defeat 4 Minor Bosses",
    "Defeat 4 Sub-Guardians",
    "Defeat 5 Minor Bosses",
    "Defeat 5 Sub-Guardians",
    "Defeat 6 Minor Bosses",
    "Defeat 6 Sub-Guardians",
    "Defeat all 5 Sporbs",
    "Defeat all Dark Metroids in Phazon Site",
    "Defeat both Ingsmashers in Reactor Access",
    "Defeat both Krocusses",
    "Defeat both Mechlops in Dynamo Works Access",
    "Defeat both Mekenobites in Sanctuary Temple",
    "Defeat both Sandiggers in Mining Plaza",
    "Defeat the Dark Ingsmasher in Hive Portal Chamber",
    "Defeat the Flying Pirates in Mining Station B",
    "Defeat the Warrior Ing in Duelling Range",
    "Destroy 1 Flying Ing Cache in 1 areas",
    "Destroy 1 Flying Ing Cache in 2 areas",
    "Destroy 1 Flying Ing Cache in 3 areas",
    "Destroy 1 Flying Ing Cache in 4 areas",
    "Destroy a Lightbringer",
    "Dungeon Item",
    "Echo Visor",
    "Emerald Translator",
    "Encounter Dark Samus 1 time",
    "Encounter Dark Samus 2 times",
    "Encounter Dark Samus 3 times",
    "Encounter Dark Samus 4 times",
    "Encounter Dark Samus 5 times",
    "Encounter Dark Samus 6 times",
    "Energy Transfer Module",
    "Enter 1 Generator Portals",
    "Enter 2 Generator Portals",
    "Enter 3 Generator Portals",
    "Enter 4 Generator Portals",
    "Feeding Pit Item",
    "Flip Over a Dark Phlogus",
    "GFMC Compound (Ship) Item",
    "Gathering Hall Item",
    "Grand Windchamber Item",
    "Grapple Beam",
    "Gravity Boost",
    "Hall of Honored Dead Item",
    "Have 1 Beam Combo",
    "Have 1 Translator",
    "Have 100 Dark Ammo",
    "Have 100 Light Ammo",
    "Have 12 Energy Tanks",
    "Have 120 Missiles",
    "Have 150 Dark Ammo",
    "Have 150 Light Ammo",
    "Have 2 Beam Combos",
    "Have 2 Power Bombs",
    "Have 2 Translators",
    "Have 200 Dark Ammo",
    "Have 200 Light Ammo",
    "Have 3 Beam Combos",
    "Have 3 Energy Tanks",
    "Have 3 Translators",
    "Have 30 Missiles",
    "Have 4 Beam Combos",
    "Have 4 Power Bombs",
    "Have 4 Translators",
    "Have 6 Energy Tanks",
    "Have 6 Power Bombs",
    "Have 60 Missiles",
    "Have 8 Power Bombs",
    "Have 9 Energy Tanks",
    "Have 90 Missiles",
    "Hive Chamber A Item",
    "Hive Entrance Item",
    "Hive Gyro Chamber Item",
    "Ing Cache 2 Item",
    "Ing Reliquary Item",
    "Junction Site Item",
    "Light Beam",
    "Light Suit",
    "Lower the bridge in Vault",
    "Main Energy Controller (Light Suit) Item",
    "Main Gyro Chamber Item",
    "Main Power Bomb",
    "Main Reactor Item",
    "Meditation Vista Item",
    "Mining Plaza Item",
    "Missile Launcher",
    "Morph Ball Bomb",
    "Move 2 Light Blocks",
    "Move 3 Light Blocks",
    "Move 8 Light Blocks",
    "Move the Forgotten Bridge",
    "Poisoned Bog Item",
    "Profane Path Item",
    "Reboot the Power Suit",
    "Return Agon Energy",
    "Return Sanctuary Energy",
    "Return Torvus Energy",
    "Ride the Gondola in Abandoned Base",
    "Sanctuary Entrance Item",
    "Sanctuary Map Station Item",
    "Scan all Amber hints",
    "Scan all Cobalt hints",
    "Scan all Emerald hints",
    "Scan all Violet hints",
    "Screw Attack",
    "Seeker Launcher",
    "Sonic Boom",
    "Space Jump Boots",
    "Spider Ball",
    "Storage A Item",
    "Storage C Item",
    "Sunburst",
    "Super Missile",
    "Torvus Plaza Item",
    "Transit Tunnel East Item",
    "Transit Tunnel South Item",
    "Undertemple (SA Wall) Item",
    "Unlock 1 Echo Key Beam Gate",
    "Unlock 1 Sonic System Echo Gate",
    "Unlock 12 Missile Doors",
    "Unlock 16 Missile Doors",
    "Unlock 2 Echo Key Beam Gates",
    "Unlock 2 Seeker Missile Doors",
    "Unlock 2 Sonic System Echo Gates",
    "Unlock 3 Echo Key Beam Gates",
    "Unlock 3 Power Bomb Doors",
    "Unlock 3 Sonic System Echo Gates",
    "Unlock 3 Super Missile Doors",
    "Unlock 4 Missile Doors",
    "Unlock 5 Seeker Missile Doors",
    "Unlock 6 Power Bomb Doors",
    "Unlock 6 Super Missile Doors",
    "Unlock 8 Missile Doors",
    "Unlock 8 Seeker Missile Doors",
    "Unlock 9 Power Bomb Doors",
    "Unlock 9 Super Missile Doors",
    "Unlock a Translator Gate in 1 Region",
    "Unlock a Translator Gate in 2 Regions",
    "Unlock a Translator Gate in 3 Regions",
    "Unlock a Translator Gate in 4 Regions",
    "Unlock a Translator Gate in 5 Regions",
    "Use 10 Kinetic Orb Cannons",
    "Use 12 Grapple Points",
    "Use 15 Grapple Points",
    "Use 20 Kinetic Orb Cannons",
    "Use 3 Grapple Points",
    "Use 30 Kinetic Orb Cannons",
    "Use 6 Grapple Points",
    "Use 9 Grapple Points",
    "Use a Save Station in 3 Regions",
    "Use a Save Station in 4 Regions",
    "Use a Save Station in 5 Regions",
    "Vault Item",
    "Violet Translator",
    "Visit Sky Temple Gateway",
    "War Ritual Grounds Item",
    "Watch Station Item"
];
