bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "1 Aeion Ability",
    "1 Duplicate Item",
    "1 Nothing Item",
    "10 E-Tanks",
    "12 Power Bombs",
    "120 Missiles",
    "160 Missiles",
    "2 Aeion Abilities",
    "3 Aeion Abilities",
    "3 E-Tanks",
    "4 Power Bombs",
    "50 Missiles",
    "6 E-Tanks",
    "8 E-Tanks",
    "8 Power Bombs",
    "80 Missiles",
    "Charge Beam",
    "Check 10 Adam Hints",
    "Check 2 Adam Hints",
    "Check 5 Adam Hints",
    "Check 8 Adam Hints",
    "Corpius",
    "Cross Bombs",
    "Defeat 1 Major Bosses",
    "Defeat 2 Chozo Soldiers",
    "Defeat 2 E.M.M.I.",
    "Defeat 2 Gobblers",
    "Defeat 2 Major Bosses",
    "Defeat 2 Robot Chozo",
    "Defeat 2 Shakernaut",
    "Defeat 3 Chozo Soldiers",
    "Defeat 3 E.M.M.I.",
    "Defeat 3 Gobblers",
    "Defeat 3 Major Bosses",
    "Defeat 4 Chozo Soldiers",
    "Defeat 4 E.M.M.I.",
    "Defeat 4 Gobblers",
    "Defeat 4 Major Bosses",
    "Defeat 4 Robot Chozo",
    "Defeat 4 Shakernaut",
    "Defeat 5 E.M.M.I.",
    "Defeat 5 Major Bosses",
    "Defeat 6 E.M.M.I.",
    "Defeat 6 Major Bosses",
    "Defeat 6 Robot Chozo",
    "Defeat a Chozo Soldier",
    "Defeat an E.M.M.I.",
    "Defeat an Omnithon",
    "Destroy 14 Breakable Walls",
    "Destroy 2 Enky",
    "Destroy 4 Enky",
    "Destroy 5 Breakable Walls",
    "Destroy 6 Enky",
    "Destroy 8 Enky",
    "Destroy 9 Breakable Walls",
    "Diffusion Beam",
    "Drogyga",
    "Elite Chozo Soldier",
    "Elun Chozo Soldier",
    "Escue",
    "Experiment No. Z-57",
    "Flash Shift",
    "Golzuna",
    "Grapple Beam",
    "Gravity Suit",
    "Ice E.M.M.I.",
    "Ice Missile",
    "Kraid",
    "Main Power Bomb",
    "Morph Ball",
    "Morph Ball Bombs",
    "Open 2 Grapple Blocks",
    "Open 2 Storm Missile Gates",
    "Open 2 Super Missile Covers",
    "Open 2 Wide Beam Covers",
    "Open 3 Missile Covers",
    "Open 3 Storm Missile Gates",
    "Open 3 Wide Beam Covers",
    "Open 4 Grapple Blocks",
    "Open 4 Storm Missile Gates",
    "Open 4 Super Missile Covers",
    "Open 4 Wide Beam Covers",
    "Open 5 Missile Covers",
    "Open 8 Missile Covers",
    "Parry a Muzby",
    "Phantom Cloak",
    "Plasma Beam",
    "Post Speed E.M.M.I. Shinespark Item",
    "Power Bomb E.M.M.I.",
    "Pull 2 Grapple Boxes",
    "Pull 3 Grapple Boxes",
    "Pulse Radar",
    "Push 1 Wide Beam Box",
    "Push 3 Wide Beam Boxes",
    "Push 5 Wide Beam Boxes",
    "Quiet Robe Chozo Soldier",
    "Release the X",
    "Screw Attack",
    "Space Jump",
    "Speed Booster",
    "Speed E.M.M.I.",
    "Spider Magnet",
    "Spin Boost",
    "Storm Missile",
    "Super Missile",
    "Use 1 Map Station",
    "Use 1 Save Station in 2 Regions",
    "Use 1 Save Station in 3 Regions",
    "Use 1 Save Station in 4 Regions",
    "Use 1 Save Station in 5 Regions",
    "Use 1 Save Station in 6 Regions",
    "Use 1 Save Station in 7 Regions",
    "Use 1 Save Station in 8 Regions",
    "Use 12 Save Stations",
    "Use 2 Artaria Save Stations",
    "Use 2 Burenia Save Stations",
    "Use 2 Cataris Save Stations",
    "Use 2 Dairon Save Stations",
    "Use 2 Ferenia Save Stations",
    "Use 2 Ghavoran Save Stations",
    "Use 2 Map Stations",
    "Use 2 Morph Ball Launchers",
    "Use 3 Artaria Save Stations",
    "Use 3 Burenia Save Stations",
    "Use 3 Map Stations",
    "Use 4 Map Stations",
    "Use 4 Morph Ball Launchers",
    "Use 4 Save Stations",
    "Use 5 Map Stations",
    "Use 6 Map Stations",
    "Use 6 Morph Ball Launchers",
    "Use 8 Save Stations",
    "Use the Elun Save Station",
    "Use the Itorash Save Station",
    "Vanilla Screw Attack Item",
    "Vanilla Space Jump Item",
    "Varia Suit",
    "Wave Beam",
    "Wave E.M.M.I.",
    "Wide Beam"
];
