var bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    {"name": "Mk22 Easy Supply Depot"},
    {"name": "Mk22 Normal Supply Depot"},
    {"name": "Mk22 Hard Supply Depot"},
    {"name": "Mk22 Extreme Supply Depot"},
    {"name": "M1911A1 Easy Supply Depot"},
    {"name": "M1911A1 Normal Supply Depot"},
    {"name": "M1911A1 Hard Supply Depot"},
    {"name": "M1911A1 Extreme Supply Depot"},
    {"name": "SAA Easy Supply Depot"},
    {"name": "SAA Normal Supply Depot"},
    {"name": "SAA Hard Supply Depot"},
    {"name": "SAA Extreme Supply Depot"},
    {"name": "Mk23 Easy Supply Depot"},
    {"name": "Mk23 Normal Supply Depot"},
    {"name": "Mk23 Hard Supply Depot"},
    {"name": "Mk23 Extreme Supply Depot"},
    {"name": "Scorpion Easy Supply Depot"},
    {"name": "Scorpion Normal Supply Depot"},
    {"name": "Scorpion Hard Supply Depot"},
    {"name": "Scorpion Extreme Supply Depot"},
    {"name": "Uzi Easy Supply Depot"},
    {"name": "Uzi Normal Supply Depot"},
    {"name": "Uzi Hard Supply Depot"},
    {"name": "Uzi Extreme Supply Depot"},
    {"name": "M10 Easy Supply Depot"},
    {"name": "M10 Normal Supply Depot"},
    {"name": "M10 Hard Supply Depot"},
    {"name": "M10 Extreme Supply Depot"},
    {"name": "P90 Easy Supply Depot"},
    {"name": "P90 Normal Supply Depot"},
    {"name": "P90 Hard Supply Depot"},
    {"name": "P90 Extreme Supply Depot"},
    {"name": "M16A1 Easy Supply Depot"},
    {"name": "M16A1 Normal Supply Depot"},
    {"name": "M16A1 Hard Supply Depot"},
    {"name": "M16A1 Extreme Supply Depot"},
    {"name": "XM177E2 Easy Supply Depot"},
    {"name": "XM177E2 Normal Supply Depot"},
    {"name": "XM177E2 Hard Supply Depot"},
    {"name": "XM177E2 Extreme Supply Depot"},
    {"name": "AK-47 Easy Supply Depot"},
    {"name": "AK-47 Normal Supply Depot"},
    {"name": "AK-47 Hard Supply Depot"},
    {"name": "AK-47 Extreme Supply Depot"},
    {"name": "FAMAS Easy Supply Depot"},
    {"name": "FAMAS Normal Supply Depot"},
    {"name": "FAMAS Hard Supply Depot"},
    {"name": "FAMAS Extreme Supply Depot"},
    {"name": "M4A1 Easy Supply Depot"},
    {"name": "M4A1 Normal Supply Depot"},
    {"name": "M4A1 Hard Supply Depot"},
    {"name": "M4A1 Extreme Supply Depot"},
    {"name": "M4 (SOPMOD) Easy Supply Depot"},
    {"name": "M4 (SOPMOD) Normal Supply Depot"},
    {"name": "M4 (SOPMOD) Hard Supply Depot"},
    {"name": "M4 (SOPMOD) Extreme Supply Depot"},
    {"name": "AKS74-U Easy Supply Depot"},
    {"name": "AKS74-U Normal Supply Depot"},
    {"name": "AKS74-U Hard Supply Depot"},
    {"name": "AKS74-U Extreme Supply Depot"},
    {"name": "M37 Easy Supply Depot"},
    {"name": "M37 Normal Supply Depot"},
    {"name": "M37 Hard Supply Depot"},
    {"name": "M37 Extreme Supply Depot"},
    {"name": "M870 Easy Supply Depot"},
    {"name": "M870 Normal Supply Depot"},
    {"name": "M870 Hard Supply Depot"},
    {"name": "M870 Extreme Supply Depot"},
    {"name": "SVD Easy Supply Depot"},
    {"name": "SVD Normal Supply Depot"},
    {"name": "SVD Hard Supply Depot"},
    {"name": "SVD Extreme Supply Depot"},
    {"name": "Mosin N Easy Supply Depot"},
    {"name": "Mosin N Normal Supply Depot"},
    {"name": "Mosin N Hard Supply Depot"},
    {"name": "Mosin N Extreme Supply Depot"},
    {"name": "RPG-7 Easy Supply Depot"},
    {"name": "RPG-7 Normal Supply Depot"},
    {"name": "RPG-7 Hard Supply Depot"},
    {"name": "RPG-7 Extreme Supply Depot"},
    {"name": "M63 Easy Supply Depot"},
    {"name": "M63 Normal Supply Depot"},
    {"name": "M63 Hard Supply Depot"},
    {"name": "M63 Extreme Supply Depot"},
    {"name": "Knife Easy Supply Depot"},
    {"name": "Knife Normal Supply Depot"},
    {"name": "Knife Hard Supply Depot"},
    {"name": "Knife Extreme Supply Depot"},
    {"name": "SP Knife Easy Supply Depot"},
    {"name": "SP Knife Normal Supply Depot"},
    {"name": "SP Knife Hard Supply Depot"},
    {"name": "SP Knife Extreme Supply Depot"},
    {"name": "Grenade Easy Supply Depot"},
    {"name": "Grenade Normal Supply Depot"},
    {"name": "Grenade Hard Supply Depot"},
    {"name": "Grenade Extreme Supply Depot"},
    {"name": "Stun G Easy Supply Depot"},
    {"name": "Stun G Normal Supply Depot"},
    {"name": "Stun G Hard Supply Depot"},
    {"name": "Stun G Extreme Supply Depot"},
    {"name": "TNT Easy Supply Depot"},
    {"name": "TNT Normal Supply Depot"},
    {"name": "TNT Hard Supply Depot"},
    {"name": "TNT Extreme Supply Depot"},
    {"name": "Claymore Easy Supply Depot"},
    {"name": "Claymore Normal Supply Depot"},
    {"name": "Claymore Hard Supply Depot"},
    {"name": "Claymore Extreme Supply Depot"},
    {"name": "CQC Easy Supply Depot"},
    {"name": "CQC Normal Supply Depot"},
    {"name": "CQC Hard Supply Depot"},
    {"name": "CQC Extreme Supply Depot"},
    {"name": "Mk22 Easy Town"},
    {"name": "Mk22 Normal Town"},
    {"name": "Mk22 Hard Town"},
    {"name": "Mk22 Extreme Town"},
    {"name": "M1911A1 Easy Town"},
    {"name": "M1911A1 Normal Town"},
    {"name": "M1911A1 Hard Town"},
    {"name": "M1911A1 Extreme Town"},
    {"name": "SAA Easy Town"},
    {"name": "SAA Normal Town"},
    {"name": "SAA Hard Town"},
    {"name": "SAA Extreme Town"},
    {"name": "Mk23 Easy Town"},
    {"name": "Mk23 Normal Town"},
    {"name": "Mk23 Hard Town"},
    {"name": "Mk23 Extreme Town"},
    {"name": "Scorpion Easy Town"},
    {"name": "Scorpion Normal Town"},
    {"name": "Scorpion Hard Town"},
    {"name": "Scorpion Extreme Town"},
    {"name": "Uzi Easy Town"},
    {"name": "Uzi Normal Town"},
    {"name": "Uzi Hard Town"},
    {"name": "Uzi Extreme Town"},
    {"name": "M10 Easy Town"},
    {"name": "M10 Normal Town"},
    {"name": "M10 Hard Town"},
    {"name": "M10 Extreme Town"},
    {"name": "P90 Easy Town"},
    {"name": "P90 Normal Town"},
    {"name": "P90 Hard Town"},
    {"name": "P90 Extreme Town"},
    {"name": "M16A1 Easy Town"},
    {"name": "M16A1 Normal Town"},
    {"name": "M16A1 Hard Town"},
    {"name": "M16A1 Extreme Town"},
    {"name": "XM177E2 Easy Town"},
    {"name": "XM177E2 Normal Town"},
    {"name": "XM177E2 Hard Town"},
    {"name": "XM177E2 Extreme Town"},
    {"name": "AK-47 Easy Town"},
    {"name": "AK-47 Normal Town"},
    {"name": "AK-47 Hard Town"},
    {"name": "AK-47 Extreme Town"},
    {"name": "FAMAS Easy Town"},
    {"name": "FAMAS Normal Town"},
    {"name": "FAMAS Hard Town"},
    {"name": "FAMAS Extreme Town"},
    {"name": "M4A1 Easy Town"},
    {"name": "M4A1 Normal Town"},
    {"name": "M4A1 Hard Town"},
    {"name": "M4A1 Extreme Town"},
    {"name": "M4 (SOPMOD) Easy Town"},
    {"name": "M4 (SOPMOD) Normal Town"},
    {"name": "M4 (SOPMOD) Hard Town"},
    {"name": "M4 (SOPMOD) Extreme Town"},
    {"name": "AKS74-U Easy Town"},
    {"name": "AKS74-U Normal Town"},
    {"name": "AKS74-U Hard Town"},
    {"name": "AKS74-U Extreme Town"},
    {"name": "M37 Easy Town"},
    {"name": "M37 Normal Town"},
    {"name": "M37 Hard Town"},
    {"name": "M37 Extreme Town"},
    {"name": "M870 Easy Town"},
    {"name": "M870 Normal Town"},
    {"name": "M870 Hard Town"},
    {"name": "M870 Extreme Town"},
    {"name": "SVD Easy Town"},
    {"name": "SVD Normal Town"},
    {"name": "SVD Hard Town"},
    {"name": "SVD Extreme Town"},
    {"name": "Mosin N Easy Town"},
    {"name": "Mosin N Normal Town"},
    {"name": "Mosin N Hard Town"},
    {"name": "Mosin N Extreme Town"},
    {"name": "RPG-7 Easy Town"},
    {"name": "RPG-7 Normal Town"},
    {"name": "RPG-7 Hard Town"},
    {"name": "RPG-7 Extreme Town"},
    {"name": "M63 Easy Town"},
    {"name": "M63 Normal Town"},
    {"name": "M63 Hard Town"},
    {"name": "M63 Extreme Town"},
    {"name": "Knife Easy Town"},
    {"name": "Knife Normal Town"},
    {"name": "Knife Hard Town"},
    {"name": "Knife Extreme Town"},
    {"name": "SP Knife Easy Town"},
    {"name": "SP Knife Normal Town"},
    {"name": "SP Knife Hard Town"},
    {"name": "SP Knife Extreme Town"},
    {"name": "Grenade Easy Town"},
    {"name": "Grenade Normal Town"},
    {"name": "Grenade Hard Town"},
    {"name": "Grenade Extreme Town"},
    {"name": "Stun G Easy Town"},
    {"name": "Stun G Normal Town"},
    {"name": "Stun G Hard Town"},
    {"name": "Stun G Extreme Town"},
    {"name": "TNT Easy Town"},
    {"name": "TNT Normal Town"},
    {"name": "TNT Hard Town"},
    {"name": "TNT Extreme Town"},
    {"name": "Claymore Easy Town"},
    {"name": "Claymore Normal Town"},
    {"name": "Claymore Hard Town"},
    {"name": "Claymore Extreme Town"},
    {"name": "CQC Easy Town"},
    {"name": "CQC Normal Town"},
    {"name": "CQC Hard Town"},
    {"name": "CQC Extreme Town"},
    {"name": "Mk22 Easy Silo Entrance"},
    {"name": "Mk22 Normal Silo Entrance"},
    {"name": "Mk22 Hard Silo Entrance"},
    {"name": "Mk22 Extreme Silo Entrance"},
    {"name": "M1911A1 Easy Silo Entrance"},
    {"name": "M1911A1 Normal Silo Entrance"},
    {"name": "M1911A1 Hard Silo Entrance"},
    {"name": "M1911A1 Extreme Silo Entrance"},
    {"name": "SAA Easy Silo Entrance"},
    {"name": "SAA Normal Silo Entrance"},
    {"name": "SAA Hard Silo Entrance"},
    {"name": "SAA Extreme Silo Entrance"},
    {"name": "Mk23 Easy Silo Entrance"},
    {"name": "Mk23 Normal Silo Entrance"},
    {"name": "Mk23 Hard Silo Entrance"},
    {"name": "Mk23 Extreme Silo Entrance"},
    {"name": "Scorpion Easy Silo Entrance"},
    {"name": "Scorpion Normal Silo Entrance"},
    {"name": "Scorpion Hard Silo Entrance"},
    {"name": "Scorpion Extreme Silo Entrance"},
    {"name": "Uzi Easy Silo Entrance"},
    {"name": "Uzi Normal Silo Entrance"},
    {"name": "Uzi Hard Silo Entrance"},
    {"name": "Uzi Extreme Silo Entrance"},
    {"name": "M10 Easy Silo Entrance"},
    {"name": "M10 Normal Silo Entrance"},
    {"name": "M10 Hard Silo Entrance"},
    {"name": "M10 Extreme Silo Entrance"},
    {"name": "P90 Easy Silo Entrance"},
    {"name": "P90 Normal Silo Entrance"},
    {"name": "P90 Hard Silo Entrance"},
    {"name": "P90 Extreme Silo Entrance"},
    {"name": "M16A1 Easy Silo Entrance"},
    {"name": "M16A1 Normal Silo Entrance"},
    {"name": "M16A1 Hard Silo Entrance"},
    {"name": "M16A1 Extreme Silo Entrance"},
    {"name": "XM177E2 Easy Silo Entrance"},
    {"name": "XM177E2 Normal Silo Entrance"},
    {"name": "XM177E2 Hard Silo Entrance"},
    {"name": "XM177E2 Extreme Silo Entrance"},
    {"name": "AK-47 Easy Silo Entrance"},
    {"name": "AK-47 Normal Silo Entrance"},
    {"name": "AK-47 Hard Silo Entrance"},
    {"name": "AK-47 Extreme Silo Entrance"},
    {"name": "FAMAS Easy Silo Entrance"},
    {"name": "FAMAS Normal Silo Entrance"},
    {"name": "FAMAS Hard Silo Entrance"},
    {"name": "FAMAS Extreme Silo Entrance"},
    {"name": "M4A1 Easy Silo Entrance"},
    {"name": "M4A1 Normal Silo Entrance"},
    {"name": "M4A1 Hard Silo Entrance"},
    {"name": "M4A1 Extreme Silo Entrance"},
    {"name": "M4 (SOPMOD) Easy Silo Entrance"},
    {"name": "M4 (SOPMOD) Normal Silo Entrance"},
    {"name": "M4 (SOPMOD) Hard Silo Entrance"},
    {"name": "M4 (SOPMOD) Extreme Silo Entrance"},
    {"name": "AKS74-U Easy Silo Entrance"},
    {"name": "AKS74-U Normal Silo Entrance"},
    {"name": "AKS74-U Hard Silo Entrance"},
    {"name": "AKS74-U Extreme Silo Entrance"},
    {"name": "M37 Easy Silo Entrance"},
    {"name": "M37 Normal Silo Entrance"},
    {"name": "M37 Hard Silo Entrance"},
    {"name": "M37 Extreme Silo Entrance"},
    {"name": "M870 Easy Silo Entrance"},
    {"name": "M870 Normal Silo Entrance"},
    {"name": "M870 Hard Silo Entrance"},
    {"name": "M870 Extreme Silo Entrance"},
    {"name": "SVD Easy Silo Entrance"},
    {"name": "SVD Normal Silo Entrance"},
    {"name": "SVD Hard Silo Entrance"},
    {"name": "SVD Extreme Silo Entrance"},
    {"name": "Mosin N Easy Silo Entrance"},
    {"name": "Mosin N Normal Silo Entrance"},
    {"name": "Mosin N Hard Silo Entrance"},
    {"name": "Mosin N Extreme Silo Entrance"},
    {"name": "RPG-7 Easy Silo Entrance"},
    {"name": "RPG-7 Normal Silo Entrance"},
    {"name": "RPG-7 Hard Silo Entrance"},
    {"name": "RPG-7 Extreme Silo Entrance"},
    {"name": "M63 Easy Silo Entrance"},
    {"name": "M63 Normal Silo Entrance"},
    {"name": "M63 Hard Silo Entrance"},
    {"name": "M63 Extreme Silo Entrance"},
    {"name": "Knife Easy Silo Entrance"},
    {"name": "Knife Normal Silo Entrance"},
    {"name": "Knife Hard Silo Entrance"},
    {"name": "Knife Extreme Silo Entrance"},
    {"name": "SP Knife Easy Silo Entrance"},
    {"name": "SP Knife Normal Silo Entrance"},
    {"name": "SP Knife Hard Silo Entrance"},
    {"name": "SP Knife Extreme Silo Entrance"},
    {"name": "Grenade Easy Silo Entrance"},
    {"name": "Grenade Normal Silo Entrance"},
    {"name": "Grenade Hard Silo Entrance"},
    {"name": "Grenade Extreme Silo Entrance"},
    {"name": "Stun G Easy Silo Entrance"},
    {"name": "Stun G Normal Silo Entrance"},
    {"name": "Stun G Hard Silo Entrance"},
    {"name": "Stun G Extreme Silo Entrance"},
    {"name": "TNT Easy Silo Entrance"},
    {"name": "TNT Normal Silo Entrance"},
    {"name": "TNT Hard Silo Entrance"},
    {"name": "TNT Extreme Silo Entrance"},
    {"name": "Claymore Easy Silo Entrance"},
    {"name": "Claymore Normal Silo Entrance"},
    {"name": "Claymore Hard Silo Entrance"},
    {"name": "Claymore Extreme Silo Entrance"},
    {"name": "CQC Easy Silo Entrance"},
    {"name": "CQC Normal Silo Entrance"},
    {"name": "CQC Hard Silo Entrance"},
    {"name": "CQC Extreme Silo Entrance"}
];
