bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "5 Uniques in the same unit",
    "A Hero’s Way",
    "Banger Alert",
    "Beat LAV Type G in one shot",
    "Beat best Zeke, no resupplies",
    "Blow up an obstacle with C4",
    "Boss QTE",
    "Box Boosting... UP?!",
    "Break a helicopter’s cockpit",
    "Cocoon Shellshocked",
    "Cocoon: Leave me the Shell Alone",
    "Complete EO128 after using a missile platform",
    "Complete Extra Op One Shot",
    "Contact a Ghost",
    "Create a divine wind",
    "Defeat Gear Rex using only the Mk.22",
    "Defeat Pupa using only the Patriot",
    "Defeat any Custom AI",
    "Destroy all extremities of an AI",
    "Dodge 4 or more trees",
    "Don’t Loop the Butterfly",
    "Drop a box on an enemy's head",
    "Entice a Monster with food",
    "Find Sunlight",
    "Gamer Fuel",
    "Go on a 4 star date",
    "Going Bananas",
    "Head Shot Master",
    "I LOVE THE BEACH",
    "Kill every human enemy in a story mission",
    "Listen to Heavens Divide",
    "Overflow mother base",
    "Perfectly cook a ration",
    "Perform a CQC chain of at least 6 enemies",
    "Perform a leap of faith",
    "Pull an AI board of each type",
    "Read Huey’s letter to Strangelove",
    "Rear Entry",
    "Recruit a 5-star chef",
    "Rescue 5 POWs total",
    "S Rank any Monster",
    "S Rank any Pooyan Mission",
    "S Rank any Tank",
    "S Rank any non AI Vehicle",
    "Strangelove QTE",
    "Stun rod Zadornov into submission",
    "Take a photo of someone special",
    "This Story’s Bananas",
    "Throw a Chaff at Metal Gear Zeke",
    "Unique calls for the Love Box and Box Tank",
    "Use a turret to kill an enemy"
];
