bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Activate a conduit",
    "Bake a cake",
    "Breed a chicken",
    "Breed a cow",
    "Breed a horse",
    "Breed a pig",
    "Breed a sheep",
    "Brew a potion",
    "Build a trans pride flag",
    "Catch a fish",
    "Compost some food",
    "Cook food on a campfire",
    "Detonate TNT",
    "Eat a suspicious stew",
    "Eat an enchanted golden apple",
    "Enchant an item",
    "Enter the end",
    "Enter the nether",
    "Fill a map",
    "Find Elytra",
    "Find a desert temple",
    "Find a desert well",
    "Find a dungeon",
    "Find a forest mansion",
    "Find a fossil",
    "Find a jungle temple",
    "Find a mushroom island",
    "Find a nether fortress",
    "Find a pillager outpost",
    "Find a shipwreck",
    "Find a stronghold",
    "Find a swamp hut",
    "Find a village",
    "Find an abandoned mineshaft",
    "Find an end city",
    "Find an ice spike biome",
    "Find an ocean temple",
    "Find buried treasure",
    "Find diamond ore",
    "Full set of Iron tools",
    "Full set of chain armour",
    "Full set of diamond armour",
    "Full set of diamond tools.",
    "Full set of gold armour",
    "Full set of gold tools",
    "Full set of iron armour",
    "Full set of leather armour",
    "Full set of stone tools",
    "Full set of wooden tools",
    "Get a full stack of an edible item",
    "Get withered",
    "Grow a melon",
    "Grow a pumpkin",
    "Grow wheat",
    "Kill a ghast",
    "Kill a slime",
    "Kill a witch",
    "Kill all 3 guardians in an ocean temple",
    "Kill an evoker",
    "Kill the wither",
    "Levitate",
    "Light a firework",
    "Make a cookie",
    "Make a dispenser",
    "Make a full enchanting setup",
    "Make a functional mob farm",
    "Make a potion of healing",
    "Make a redstone clock",
    "Make a snow golem",
    "Make a trade",
    "Make an enchanting table",
    "Make an ender chest",
    "Make an iron golem",
    "Place a beacon",
    "Play a music disc",
    "Put a banner on a shield",
    "Reach bedrock",
    "Reach the height limit",
    "Repair a tool/armour",
    "Ride a llama",
    "Shear a sheep",
    "Spawn a chicken with an egg",
    "Spawn the wither",
    "Tame a cat",
    "Tame a donkey",
    "Tame a horse",
    "Tame a mule",
    "Tame a parrot",
    "Tame a wolf",
    "Use a grindstone",
    "Use a minecart",
    "Use a nametag",
    "Wear a turtle shell",
    "Write a book"
];
