bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "A Balanced Diet",
    "A Complete Catalogue",
    "A Furious Cocktail",
    "A Seedy Place",
    "A Terrible Fortress",
    "A Throwaway Joke",
    "Acquire Hardware",
    "Adventure",
    "Adventuring Time",
    "Arbalistic",
    "Beaconator",
    "Bee Our Guest",
    "Best Friends Forever",
    "Bring Home the Beacon",
    "Bullseye",
    "Country Lode, Take Me Home",
    "Cover Me With Diamonds",
    "Cover Me in Debris",
    "Diamonds!",
    "Enchanter",
    "Eye Spy",
    "Fishy Business",
    "Free the End",
    "Getting an Upgrade",
    "Great View From Up Here",
    "Hero of the Village",
    "Hidden in the Depths",
    "Hired Help",
    "Hot Stuff",
    "Hot Tourist Destinations",
    "How Did We Get Here?",
    "Husbandry",
    "Ice Bucket Challenge",
    "Into Fire",
    "Isn't It Iron Pick",
    "Local Brewery",
    "Minecraft",
    "Monster Hunter",
    "Monsters Hunted",
    "Nether",
    "Not Quite \"Nine\" Lives",
    "Not Today, Thank You",
    "Oh Shiny",
    "Ol' Betsy",
    "Postmortal",
    "Remote Getaway",
    "Return to Sender",
    "Serious Dedication",
    "Sky's the Limit",
    "Sniper Duel",
    "Spooky Scary Skeleton",
    "Sticky Situation",
    "Stone Age",
    "Subspace Bubble",
    "Suit Up",
    "Sweet Dreams",
    "Tactical Fishing",
    "Take Aim",
    "The City at the End of the Game",
    "The End",
    "The End... Again...",
    "The End?",
    "The Next Generation",
    "The Parrots and the Bats",
    "This Boat Has Legs",
    "Those were the Days",
    "Total Beelocation",
    "Two Birds, One Arrow",
    "Two by Two",
    "Uneasy Alliance",
    "Very Very Fightening",
    "Voluntary Exile",
    "War Pigs",
    "We Need to Go Deeper",
    "What a Deal!",
    "Who is Cutting Onions?",
    "Who's the Pillager Now?",
    "Withering Heights",
    "You Need a Mint",
    "Zombie Doctor"
];
