bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
 {name: "Feed Monster Potatoes For 1 Year"},
 {name: "Unlock FIMBA Monsters"},
 {name: "Monster Dies At > 1 Year Old"},
 {name: "Go Bankrupt"},
 {name: "Move Misses At 95% Or More"},
 {name: "Move Hits At 5% Or Less"},
 {name: "Win A Tournament With AI Control Only"},
 {name: "Cocoon A Worm"},
 {name: "Discard Pure Platina"},
 {name: "Win 8 Tournaments"},
 {name: "Unlock Durahan"},
 {name: "Rewarded 3000G On 1 Errantry"},
 {name: "Unlock 10 Monster Cards"},
 {name: "Use Every Drug On 1 Monster"},
 {name: "Finish 1 Tech Chain"},
 {name: "Spend Over 10000G At The Shop In 1 Trip"},
 {name: "Basic Tech Forte In HoF"},
 {name: "Find Kato Disc Chips On Expedition"},
 {name: "Lose A Week Of Life With A Banana"},
 {name: "Unlock Dragon"},
 {name: "Find Two Pure Gold On 1 Expedition"},
 {name: "KO Oakleyman"},
 {name: "2 Greats In A Row"},
 {name: "Beat Your Monster In Play"},
 {name: "Activate Fury Battle Special"},
 {name: "Run Away"},
 {name: "Use Both Peaches On 1 Monster"},
 {name: "Unlock Ghost"},
 {name: "I Wonder It Buds The Flower"},
 {name: "Monster Flattened In Battle"},
 {name: "Grit And Win"},
 {name: "Refuse 1 Ranch Upgrade"},
 {name: "Wins/Losses Mirrored On Grid"},
 {name: "Use A Move That Costs 50 Guts Or More"},
 {name: "Commit Foolery 3 Times In One Battle"},
 {name: "Unlock One Move From Each Errantry"},
 {name: "5+ Funeral Attendees"},
 {name: "Roll Credits"},
 {name: "Unlock Joker"},
 {name: "50000G"},
 {name: "Wither For 60+ Guts"},
 {name: "Tidal Wave hits"},
 {name: "Activate Fight Battle Special"},
 {name: "Spartan"},
 {name: "REVERSE: Don't Visit Aunt Verde"},
 {name: "Unlock Centaur"},
 {name: "Find Phoenix Feather On First Expedition"},
 {name: "Unlock 3 Enemy Cards"},
 {name: "Breeder Rank 8"},
 {name: "Refuse Praise For Monster Giving Item"},
 {name: "Win A Fight Using Only Recovery Moves"},
 {name: "Use Clay Doll As Combining Item"},
 {name: "Unlock Zilla"},
 {name: "Fight King Ape"},
 {name: "REVERSE: Never See Kavaro"}
];
