bingoGenerator = require("./generators/generator_bases/simple_generator.js");
//Made By TK
var bingoList =
[{"name": "Gold in orientation"},
{"name": "Gold in the docks"},
{"name": "Gold in city park"},
{"name": "Gold in downtown"},
{"name": "Gold in the marketplace"},
{"name": "Silver in the docks"},
{"name": "Silver in city park"},
{"name": "Silver in downtown"},
{"name": "Silver in the marketplace"},
{"name": "Silver in the shpinx"},
{"name": "Silver in the oasis"},
{"name": "Silver in the tomb"},
{"name": "Silver in the pyramid"},
{"name": "Bronze in city park"},
{"name": "Bronze in downtown"},
{"name": "Bronze in the docks"},
{"name": "Bronze in the marketplace"},
{"name": "Bronze in the shpinx"},
{"name": "Bronze in the oasis"},
{"name": "Bronze in the tomb"},
{"name": "Bronze in the pyramid"},
{"name": "Bronze in sugar shack"},
{"name": "Bronze in the ski lift"},
{"name": "Bronze in the iceberg"},
{"name": "Bronze in hot springs"},
{"name": "more than 100 tokens in urban chase"},
{"name": "more than 125 tokens in desert chase"},
{"name": "more than 150 tokens in arctic chase"},
{"name": "scare 15 nerves"},
{"name": "scare 30 nerves"},
{"name": "scare 3 red nerves"},
{"name": "scare 3 blue nerves"},
{"name": "scare 3 green nerves"},
{"name": "scare 3 yellow nerves"},
{"name": "scare 3 orange nerves"},
{"name": "scare a nerve from every colour in the same level (not orientation)"},
{"name": "eat randall twice"},
{"name": "collect 40 tokens from normal levels"},
{"name": "collect 20 tokens from normal levels"},
{"name": "unlock and use a trampoline"},
{"name": "unlock and use the speed ability"},
{"name": "unlock and use the bouncing ability"},
{"name": "use every trampoline"},
{"name": "use every speed powerup"},
{"name": "use every bouncing powerup"},
{"name": "use every powerup"},
{"name": "use every type of abilities"},
{"name": "leave a level with ooze bar full"},
{"name": "leave a level from each area with ooze bar full"},
{"name": "leave 7 levels with ooze bar full"},
{"name": "exit through 5 portals"},
{"name": "10 medals"},
{"name": "25 lives"},
{"name": "combined 9 nerves in hot springs and the marketplace"},
{"name": "combined 9 nerves in the iceberg and the docks"},
{"name": "combined 9 nerves in the ski lift and the oasis"},
{"name": "combined 9 nerves in sugar shack and the shpinx"},
{"name": "combined 9 nerves in the pyramid and downtown"},
{"name": "combined 9 nerves in the tomb and city park"},
{"name": "combined 15 tokens in hot springs and the oasis"},
{"name": "combined 15 tokens in the iceberg and the shpinx"},
{"name": "combined 15 tokens in the ski lift and city park"},
{"name": "combined 15 tokens in sugar shack and downtown"},
{"name": "combined 15 tokens in the pyramid and the marketplace"},
{"name": "combined 15 tokens in the tomb and the docks"}
]
