bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "+500 Life",
    "+600 In 2 Different Stats",
    "0 Funeral Attendees",
    "0 Guts To 99",
    "1 Damage",
    "1 Hit KO An Opponent",
    "100 Fame",
    "2 Crab’s Claws In Inventory",
    "3 \"I Regret…\"s At Shrine",
    "3 Different Drugs On 1 Monster",
    "5 Different Disc Chips In Inventory",
    "50000G",
    "800+ Intelligence",
    "800+ Power",
    "800+ Speed",
    "999 Damage",
    "Bad To Good Nature",
    "Beat Your Monster In Mudball Fight",
    "Beat Your Monster In Snowball Fight",
    "Beat Your Monster In Sparring",
    "Beat Your Monster In Sumo",
    "Boots And Big Footprint In Inventory",
    "Commit Foolery 3 Times In One Battle",
    "Defeat 2 Different Apes",
    "Defeat 2 Different Phoenix",
    "Defeat 3 Different Mocchis",
    "Defeat 3 Different Suezos",
    "Defeat 4 Different Zuums",
    "Defeat A Jill",
    "Dig Up Hot Springs",
    "Discard Pure Platina",
    "Don’t Visit Aunt Verde For 1 Year",
    "Every Stat Ends With 1",
    "Failure 3 Times In A Row",
    "Feed Monster 12 Milk",
    "Feed Monster 12 Potatoes",
    "Feed Monster 12 Tablets",
    "Fill Freezer With Different Monsters",
    "Fill Inventory With Smoked Snakes",
    "Find Phoenix Feather On First Expedition",
    "Finish 1 Tech Chain",
    "Foolery 6 Times In One Battle",
    "Get 5 Diamond Marks",
    "Get KO'd By Tiravail",
    "Go Bankrupt",
    "Have One Tech In Each Slot",
    "KO Oakleyman",
    "KO Waranmo",
    "Kitty’s Bang Doesn’t KO",
    "Lose A Week Of Life With A Banana",
    "Monster Dies At < 1 Year Old",
    "Monster Flattened In Battle",
    "Monster Gets +1 On Errantry",
    "Monster Gets +1 On Two Drills",
    "Monster(s) Give 3 Different Items",
    "Opponent KO'd In 4 Seconds Or Less",
    "Plant Chips And Flower In Inventory",
    "Refuse 1 Ranch Upgrade",
    "Run Away",
    "Scold Monster For Cheating",
    "Search Elephant In Parepare",
    "Search Jill Statue In Papas",
    "Sell Monster For 1000G Or More",
    "Spartan",
    "Spend Over 10000G In 1 Shop Trip",
    "Truancy",
    "Try To Use Clay Doll As Combining Item",
    "Two Gemini Pots In Inventory",
    "Two Statues In Inventory",
    "Unlock 10 Monster Cards",
    "Unlock 15 Monster Cards",
    "Unlock 3 Enemy Cards",
    "Unlock A Monster Card With Number Ending In 1",
    "Unlock Durahan",
    "Unlock FIMBA Monsters",
    "Unlock Joker",
    "Unlock One Move From Each Errantry",
    "Unlock Phoenix",
    "Use A Move That Costs 50 Guts Or More",
    "Win 3 F-Rank Tournaments",
    "Win 8 Tournaments",
    "Win A Tournament With AI Control Only",
    "Win More Than 2000G At IMa/FIMBA",
    "Wins/Losses Mirrored On Grid",
    "Wither For 60+ Guts",
    "Zuum Chips And Dino Tail In Inventory"
];
