bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "+282 Life",
    "1 Damage",
    "1 Hit KO An Opponent",
    "10% Or Less Hit",
    "100 Fame",
    "2 Cheats In A Row",
    "2 Crits Back To Back",
    "2 Greats In A Row",
    "450+ Skill",
    "800+ Intelligence",
    "800+ Speed",
    "95% Miss",
    "99 Guts",
    "Activate Ease",
    "Activate Fight",
    "Activate Grit",
    "Activate Guard",
    "Activate Unity",
    "All Moves Miss",
    "Breeder Rank 7",
    "Commit Foolery 3 Times In One Battle",
    "Enemy Monster Withdraws",
    "Every Stat Ends With 1",
    "Failure 3 Times In A Row",
    "Foolery 6 Times In One Battle",
    "KO 2 Galis",
    "KO 2 Hengers",
    "KO 2 Tigers",
    "KO 3 Plants",
    "Monster Asks For 3 Different Items",
    "Monster Flattened In Battle",
    "Never See Kavaro",
    "Power And Win",
    "Run Away For At Least 4wk",
    "Win By Less Than 1%",
    "Wins/Losses Mirrored On Grid"
];
