bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "1000 coins in 1 level",
    "12 star coins in world flower",
    "12 star coins in world mushroom",
    "15 star coins in world 1",
    "18 star coins in world 2",
    "18 star coins in world 3",
    "18 star coins in world 4",
    "18 star coins in world 5",
    "18 star coins in world 6",
    "20 total star coins",
    "200 coins in 1 level",
    "25 total star coins",
    "30 total star coins",
    "35 total star coins",
    "40 total star coins",
    "45 total star coins",
    "50 lives",
    "50 total star coins",
    "500 coins in 1 level",
    "55 total star coins",
    "All exits in 1 world",
    "All secret exits in World 3",
    "All secret exits in World 4",
    "All secret exits in World Mushroom and World Flower",
    "Clear 1 level in every world (minus star)",
    "Clear 1-5",
    "Clear 2 castle",
    "Clear 2 water themed levels",
    "Clear 2-5",
    "Clear 3 Cannons",
    "Clear 3 Castle",
    "Clear 3 ghost houses",
    "Clear 3 levels in world 5 and world mushroom",
    "Clear 3-3",
    "Clear 3-B",
    "Clear 3-Castle",
    "Clear 4 Levels while collecting every star coin",
    "Clear 4 ghost houses",
    "Clear 4-2",
    "Clear 4-C",
    "Clear 4-Castle",
    "Clear 4-Tower",
    "Clear 5 Levels while collecting every star coin",
    "Clear 5 levels in world 2",
    "Clear 5 levels in world 3",
    "Clear 5 levels in world 4",
    "Clear 5 levels in world flower",
    "Clear 5 levels in world mushroom",
    "Clear 5 levels unlocked by star coins",
    "Clear 5-6",
    "Clear 5-Castle",
    "Clear 5-Tower",
    "Clear 6 Levels while collecting every star coin",
    "Clear 6-3",
    "Clear 7 Levels while collecting every star coin",
    "Clear 8 Levels while collecting every star coin",
    "Clear 9 Levels while collecting every star coin",
    "Clear F-3",
    "Clear M-3",
    "Clear a level as star mario",
    "Clear a level while a gold ring is active",
    "Clear a water themed level",
    "Clear all cannons",
    "Clear any rainbow bonus level",
    "Clear one level with each powerup",
    "Collect 10 sets of red coins",
    "Collect 5 sets of red coins",
    "Collect 8 sets of red coins",
    "Collect a 50 coin",
    "Defeat 3 sets of Reznor",
    "Defeat 4 sets of Reznor",
    "Get 25 total exits",
    "Get 30 total exits",
    "Get 35 total exits",
    "Get 5 secret exits",
    "Get 8 secret exits",
    "Get both exits in 1-Tower",
    "Get both exits in 2-GH",
    "Get both exits in 3-4",
    "Get both exits in 3-GH",
    "Get both exits in 3-Tower",
    "Get both exits in 4-GH",
    "Get both exits in 4-Tower",
    "Get both exits in 5-1",
    "Get both exits in 5-A",
    "Get both exits in 5-GH",
    "Get both exits in 6-GH",
    "Get both exits in F-1",
    "Get both exits in F-GH",
    "Get both exits in M-1",
    "Get both exits in M-GH",
    "Get fireworks 3 times",
    "Get fireworks in world 2",
    "Obtain star in inventory"
];
