bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Beat 2 Airship levels",
    "Beat 2-1 Damageless",
    "Beat 3-2 Damageless",
    "Beat 4-4 Damageless",
    "Beat 5-3 Damageless",
    "Beat 6-1 Damageless",
    "Beat 6-Castle Damageless",
    "Beat 7-3 Damageless",
    "Beat 8-Fortress Damageless",
    "Beat 6-4 with Yoshi",
    "Beat 4 different levels where you have to go underwater",
    "Beat 6 different levels where you have to go underground",
    "Beat 4-Airship",
    "Beat 6-Airship",
    "Beat an Airship with all Star Coins",
    "Defeat 5 different Koopalings a least once",
    "Beat 5-5",
    "Beat 7-4",
    "Beat 3-3",
    "Beat 3-5 (Secret Exit)",
    "Beat 7-6 and collect 5 lives minimum",
    "Beat 8-1 with no run button",
    "Beat 8-Castle",
    "Collect all Star Coins in 2-2",
    "Collect all Star Coins in 3-4",
    "Collect all Star Coins in 4-5",
    "Collect all Star Coins in 5-2",
    "Collect all Star Coins in 8-6",
    "Collect all star Coins in 7-5",
    "Beat All Ice Bros on W3 World Map once (using a star doesn't count)",
    "Beat All Piranha Plants on W5 World Map once (using a star doesn't count)",
    "Beat every stage in W1",
    "Beat every stage in W2",
    "Beat every stage in W3",
    "Beat every stage in W4",
    "Beat every stage in W5",
    "Beat every stage in W6",
    "Beat every stage in W7",
    "Beat every stage in W8",
    "Collect 15 Star coins in W6",
    "Collect 12 Star coins in W3",
    "Collect 15 Star coins in W4",
    "Collect 15 Star coins in W2",
    "Collect 16 Star coins in W8",
    "Collect 18 Star coins in W1",
    "Collect 30 total Star Coins",
    "Collect 40 total Star Coins",
    "Collect 50 total Star Coins",
    "Collect 60 total Star Coins",
    "Collect 70 total Star Coins",
    "Collect a Star coin in W7",
    "Collect all red coins for 5 different red coin rings",
    "Complete 10 castle or fortress stages (final bowser counts)",
    "Complete 8 levels while collecting all star coins",
    "Complete 9 levels while collecting all star coins",
    "Complete 10 levels while collecting all star coins",
    "Complete 4 Castles levels with all star coins (final Bowser counts)",
    "Complete 4 Fortress levels with all star coins",
    "Complete 2 Ghost Houses with all star coins",
    "Complete 3 Ghost Houses with all star coins",
    "Complete 11 Castle or Fortress levels (final Bowser counts)",
    "Complete 8 Castle or Fortress levels (final Bowser counts)",
    "Defeat 5 Different World Map Minibosses",
    "Defeat Lemmy Twice",
    "Defeat Ludwig",
    "Defeat Roy",
    "Defeat Morton",
    "Defeat Iggy",
    "Defeat Wendy",
    "Enter 3 separate cannons",
    "Enter every world 1-8",
    "Get a perfect Red Toad House (collect maximum amount of items)",
    "Clear 7 different Toadhouses",
    "Clear 10 different Toadhouses",
    "Clear 3 different Yellow Toadhouses",
    "Clear 3 different Green Toadhouses",
    "Get both exits in 3-Ghost",
    "Get both exits in 6-6",
    "Get both exits in 7-Ghost",
    "Get both exits in world 6-5",
    "Go without collecting the 8-2 secret exit (can be marked anytime so long as it is never used)",
    "Hit the red switch (W3)",
    "Obtain 5 different secret exits",
    "Obtain 6 different secret exits",
    "All Secret Exits in W2",
    "All Secret Exits in W3",
    "All Secret Exits in W4",
    "All Secret Exits in W6",
    "All Secret Exits in W7",
    "Beat Bowser Jr. a least once as Mini-Mario (from any Airship)",
    "Beat 2 different Koopalings as Mini-Mario",
    "Clear 3 different levels with Yoshi",
    "20 Lives from flagpoles",
    "Save 3 Toads",
    "Save 4 Toads",
    "Save 5 Toads",
    "Reach 99 lives",
    "Enter W2 Warp Cannon",
    "Enter W6 Warp Cannon",
    "Reach W5 with no cannon",
    "Use no more than one cannon (can be marked anytime so long as it is never violated)"
];
