bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList =
[
    "Beat 2 airship levels",
    "Beat 2-1 Damageless",
    "Beat 4 levels where you have to go underwater",
    "Beat 4-airship",
    "Beat 5 of the Koopalings at least once",
    "Beat 7-6 and collect 5 lives minimum",
    "Beat 7-Fortress with all 3 star coins",
    "Beat 8-1 with no run button",
    "Beat 8-Fortress (final Bowser)",
    "Beat 8-Fortress damageless",
    "Beat every stage in W2",
    "Beat every stage in W5",
    "Collect 15 Star coins in W6",
    "Collect 16 Star coins in W8",
    "Collect 18 Star coins in W1",
    "Collect 40 total Star Coins",
    "Collect 50 total Star Coins",
    "Collect 60 total Star Coins",
    "Collect 70 total Star Coins",
    "Collect a Star coin in W7",
    "Collect all Star coins in 2-2",
    "Collect all red coins for 5 different red coin rings",
    "Collect all star coins in 8-6",
    "Complete 10 castle or fortress stages (final bowser counts)",
    "Complete 10 levels while collecting all star coins",
    "Complete 11 castle or fortress stages (final bowser counts)",
    "Complete 8 castle or fortress stages (final bowser counts)",
    "Defeat 5 Different World Map Minibosses",
    "Defeat Lemmy Twice",
    "Defeat Ludwig",
    "Defeat Wendy",
    "Enter 3 separate cannons",
    "Enter every world 1-8",
    "Get a perfect Red Toad House (collect maximum amount of items)",
    "Get both exits in 3-Ghost",
    "Go without collecting the 8-2 secret exit (can be marked anytime so long as it is never used)",
    "Hit the red switch (W3)",
    "Obtain 5 different secret exits",
    "Obtain 6 different secret exits",
    "Reach 99 lives",
    "Reach W5 with no cannon",
    "Use no more than one cannon (can be marked anytime so long as it is never violated)"
];
