bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "All Exits in 1-2",
    "All Exits in 2-4",
    "All Exits in 3-GH",
    "All Exits in 4-GH",
    "All Exits in 5-2",
    "All Exits in 5-4",
    "All Exits in 5-5",
    "All Exits in 5-GH",
    "All Exits in 6-5",
    "All Exits in 6-T1",
    "All Exits in 7-GH",
    "All Exits in 8-1",
    "All Secret Exits in W1",
    "All Secret Exits in W2",
    "All Secret Exits in W3",
    "All Secret Exits in W4",
    "All Secret Exits in W5",
    "All Secret Exits in W6",
    "All Secret Exits in W7",
    "All Secret Exits in W8",
    "Beat 1-3",
    "Beat 1-T Damageless",
    "Beat 2-2",
    "Beat 2-5",
    "Beat 2-6",
    "Beat 2-6 Damageless",
    "Beat 3-3",
    "Beat 3-4",
    "Beat 3-5",
    "Beat 3-C Damageless",
    "Beat 3-GH",
    "Beat 4-2 Damageless",
    "Beat 4-3 Damageless",
    "Beat 4-4 Damageless",
    "Beat 4-5",
    "Beat 4-5 Damageless",
    "Beat 4-C Damageless",
    "Beat 5-1 Damageless",
    "Beat 5-2",
    "Beat 5-3 Damageless",
    "Beat 5-6 Damageless",
    "Beat 5-7",
    "Beat 5-7 Damageless",
    "Beat 5-C Damageless",
    "Beat 6-5",
    "Beat 6-7 Damageless",
    "Beat 6-T2 Damageless",
    "Beat 7-2",
    "Beat 7-6",
    "Beat 7-6 Damageless",
    "Beat 7-T Damageless",
    "Beat 8-4",
    "Beat Bowser with Fireballs",
    "Beat Every Stage in W1",
    "Beat Every Stage in W2",
    "Beat Every Stage in W3",
    "Beat Every Stage in W4",
    "Beat Every Stage in W5",
    "Beat Every Stage in W6",
    "Beat Every Stage in W7",
    "Beat Every Stage in W8",
    "Catch Nabbit 1 time",
    "Catch Nabbit 2 times",
    "Catch Nabbit 3 times",
    "Clear 10 Tower/Castle/Airship Levels",
    "Clear 2 Levels in W8 While Collecting Every Star Coin",
    "Clear 3 Levels in W1 While Collecting Every Star Coin",
    "Clear 3 Levels in W2 While Collecting Every Star Coin",
    "Clear 3 Levels in W3 While Collecting Every Star Coin",
    "Clear 3 Levels in W4 While Collecting Every Star Coin",
    "Clear 3 Levels in W7 While Collecting Every Star Coin",
    "Clear 4 Levels in W2 While Collecting Every Star Coin",
    "Clear 4 Levels in W3 While Collecting Every Star Coin",
    "Clear 4 Levels in W4 While Collecting Every Star Coin",
    "Clear 4 Levels in W5 While Collecting Every Star Coin",
    "Clear 4 Levels in W6 While Collecting Every Star Coin",
    "Clear 4 Levels in W7 While Collecting Every Star Coin",
    "Clear 5 Levels in W5 While Collecting Every Star Coin",
    "Clear 5 Levels in W6 While Collecting Every Star Coin",
    "Clear 5 Tower/Castle/Airship Levels",
    "Clear 6 Tower/Castle/Airship Levels",
    "Clear 7 Tower/Castle/Airship Levels",
    "Clear 8 Tower/Castle/Airship Levels",
    "Clear 9 Tower/Castle/Airship Levels",
    "Collect 10 Star Coins in W1",
    "Collect 12 Star Coins in W2",
    "Collect 12 Star Coins in W3",
    "Collect 12 Star Coins in W4",
    "Collect 15 Star Coins in W6",
    "Collect 15 Star Coins in W7",
    "Collect 18 Star Coins in W5",
    "Collect 2 Powerups on the World Map",
    "Collect 3 Powerups on the World Map",
    "Collect 35 Total Star Coins",
    "Collect 4 Powerups on the World Map",
    "Collect 40 Total Star Coins",
    "Collect 45 Total Star Coins",
    "Collect 50 Total Star Coins",
    "Collect 55 Total Star Coins",
    "Collect 6 Star Coins in W8",
    "Collect 60 Total Star Coins",
    "Collect 65 Total Star Coins",
    "Complete 1 Secret Level",
    "Complete 10 Levels While Collecting All Star Coins",
    "Complete 11 Levels While Collecting All Star Coins",
    "Complete 12 Levels While Collecting All Star Coins",
    "Complete 13 Levels While Collecting All Star Coins",
    "Complete 2 Secret Levels",
    "Complete 3 Secret Levels",
    "Complete 7 Levels While Collecting All Star Coins",
    "Complete 8 Levels While Collecting All Star Coins",
    "Complete 9 Levels While Collecting All Star Coins",
    "Complete the Kamek bossfight Without the Acorn or Super Crown Powerups",
    "Defeat 3 World Map Minibosses",
    "Defeat 4 World Map Minibosses",
    "Defeat 5 World Map Minibosses",
    "Defeat Bowser Jr.",
    "Defeat Iggy",
    "Defeat Larry",
    "Defeat Lemmy",
    "Defeat Ludwig",
    "Defeat Morton",
    "Defeat Roy",
    "Die From Lava",
    "Die From a Bottomless Pit",
    "Kill Two Baby Yoshis",
    "Kill a Baby Yoshi",
    "Touch 1 Goal Pole While Riding Yoshi",
    "Touch 2 Goal Poles While Riding Yoshi",
    "Touch 3 Goal Poles While Riding Yoshi"
];
