bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList =
[
    "Activate 6 transporters",
    "Activate 7 transporters",
    "Activate City Ruins: Center Transporter",
    "Activate City Ruins: Near Factory Transporter",
    "Activate City Ruins: Near the Tower Transporter",
    "Activate Desert: Camp Transporter",
    "Activate Desert: Center Transporter",
    "Activate Desert: Housing Complex Transporter",
    "Activate Desert: Oil Field Transporter",
    "Activate Factory: Entrance Transporter",
    "Activate Flooded City: Coast Transporter",
    "Activate Forest Castle: Front Transporter",
    "Activate Forest Castle: Royal Chamber Transporter",
    "Activate Forest Zone: Center Transporter",
    "Activate Park Ruins: Attraction Sq. Transporter",
    "Buy a chip/material from Emil on Desert route",
    "Buy an item from 6 different shops",
    "Buy an item from 7 different shops",
    "Catch 3 different fish",
    "Collect all stamps",
    "Collect the Amusement Park Photograph",
    "Collect the Forest Photograph",
    "Collect the Oasis Photograph",
    "Collect ⅔ Photographs for Photographs quest",
    "Complete 11B’s Memento",
    "Complete 3 sidequests",
    "Complete 4 sidequests",
    "Complete 5 sidequests",
    "Complete Anemone’s Past",
    "Complete Animal Care",
    "Complete Camp Development",
    "Complete Culinary Researcher",
    "Complete Family Squabble",
    "Complete Improving Communications",
    "Complete Investigating Communications",
    "Complete Machine Examination 1",
    "Complete Machine Examination 2",
    "Complete Resistance Disappearance",
    "Complete Retrieve the Confidential Intel",
    "Complete Robo Dojo -- Black Belt",
    "Complete Robo Dojo -- Brown Belt",
    "Complete Robo Dojo -- White Belt",
    "Complete Sartre’s (Jean-Paul’s) Melancholy",
    "Complete Sorting Trouble",
    "Complete Terminal Repair",
    "Complete The Manager’s Request",
    "Complete The Wandering Couple",
    "Complete YoRHa Betrayers",
    "Complete fights for Jackass’s Research",
    "Complete negotiations but never transport",
    "Complete negotiations dealing and taking no damage or leaving bounds",
    "Complete three Speed Star races",
    "Consume 20x large recovery",
    "Defeat 5 Enemies while mounted on an animal",
    "Defeat A2",
    "Defeat Goliath Tank in the Amusement Park",
    "Defeat both City Engels",
    "Defeat the Animal-loving Machine",
    "Die while at full health (Get one shot)",
    "Don’t upgrade Virtuous Contract to level 2",
    "Equip 3 +3 chips",
    "Equip Blue Ribbon",
    "Equip Pink Ribbon",
    "Fish in Amusement Park Sewer Pipe once",
    "Fish in Amusement Park once",
    "Fish in City Ruins once",
    "Fish in Flooded City Access Point once",
    "Fish in Flooded City Coast once",
    "Fish in Flooded City Sewer Pipe once",
    "Fish in Forest Castle River once",
    "Fish in Oasis once",
    "Fish in Oil Field once",
    "Fish in the cavern near Emil's home",
    "Get 1 Jukebox Sound Data",
    "Get 15 non-system chips with different names or levels",
    "Get 3 endings",
    "Get 4 endings",
    "Get Ending H (Ignore the City Engels encounter)",
    "Get Ending K (Obtain & eat a Mackerel)",
    "Get Ending N (Destroy the machines in Pascal’s Village)",
    "Get Ending T (Remove your OS chip)",
    "Get Ending U (Self-Destruct in bunker)",
    "Have 0 money",
    "Have 6 read mail",
    "Have masamune upgrade a weapon",
    "Have the P and M shields active at the same time",
    "Interact with the Lunar Tear in the Amusement Park",
    "Interact with the Lunar Tear in the Commercial Center",
    "Interact with the Lunar Tear in the Desert",
    "Interact with the Lunar Tear in the Forest",
    "Kill 3 enemies trapped in 1 gravity program",
    "Kill 3 machines in the city underground with mirage",
    "Kill 3 machines with 1 hammer program",
    "Kill 3 worm machines without pod fire/pod programs",
    "Kill 5 machines in 1 spear program",
    "Kill 5 machines with the blade program underground in the desert",
    "Kill Beauvoir with no small swords equipped",
    "Kill a Desert Goliath machine in Adam Pit",
    "Kill a Special Unit Machine Weaponless",
    "Kill a special unit machine with no melee attacks",
    "Kill eve twice during negotiations",
    "Kill the amusement park tank with only self destruct damage",
    "Obtain 2 small gears after Supply Trader Quest",
    "Obtain 5 weapons",
    "Obtain 6 weapons",
    "Obtain Ancient Overlord",
    "Obtain Beastbane",
    "Obtain Beastlord",
    "Obtain Beautiful Glass",
    "Obtain Choice Sachet",
    "Obtain Cypress Stick",
    "Obtain Dragoon Lance",
    "Obtain Fang of the Twins",
    "Obtain Letter for Sartre",
    "Obtain Lunar Tear (accessory)",
    "Obtain Machine Axe",
    "Obtain Machine Fossil",
    "Obtain Machine Spear",
    "Obtain Machine Sword",
    "Obtain Phoenix Dagger",
    "Obtain Sartre’s Letter",
    "Obtain Type-3 Lance",
    "Obtain Type-4O Lance",
    "Obtain Type-4O Sword",
    "Obtain Virtuous Dignity",
    "Obtain Virtuous Grief",
    "Obtain Virtuous Treaty",
    "Obtain YoRHa-issue Blade",
    "Obtain a +5 or +6 Chip",
    "Obtain a Desert Flower",
    "Obtain a Mackerel",
    "Obtain a Memory Alloy",
    "Obtain a Meteorite",
    "Obtain a Silver Ore",
    "Obtain a Small Gear after Supply Trader Quest",
    "Obtain a titanium alloy",
    "Obtain gold ore",
    "Perform “interaction finishers” on 4 different enemies",
    "Reach level 13",
    "Retrieve 2B’s Body next to Virtuous Treaty",
    "Ride an animal to the desert center transporter",
    "Single DG run (No Small Sword on Weapon Set 1’s heavy slot)",
    "Take a nap (in resistance camp or bunker)",
    "Take an E drug while fighting a special unit machine",
    "Talk to the YoRHa member in the Oasis",
    "Talk to the YoRHa member in the Oil Field",
    "Unequip all chips except OS before leaving the bunker and do not re-equip",
    "Upgrade Ancient Overlord to level 2",
    "Upgrade Beastbane to level 2",
    "Upgrade Beastlord to level 2",
    "Upgrade Cypress Stick to level 2",
    "Upgrade Dragoon Lance to level 2",
    "Upgrade Fang of the Twins to level 2",
    "Upgrade Machine Axe to level 2",
    "Upgrade Machine Spear to level 2",
    "Upgrade Machine Sword to level 2",
    "Upgrade Phoenix Dagger to level 2",
    "Upgrade Type-3 Lance to level 2",
    "Upgrade Type-4O Lance to level 2",
    "Upgrade Virtuous Dignity to level 2",
    "Upgrade Virtuous Grief to level 2",
    "Upgrade Virtuous Treaty to level 2",
    "Upgrade YoRHa-issue Blade to level 2",
    "Upgrade any weapon to level 3",
    "Visit 2 DLC Elevators",
    "Visit Emil's Home",
    "Visit Emil’s giant heads in the desert",
    "Visit the Commercial Facility",
    "Visit the DLC elevator in the Desert",
    "Visit the DLC elevator in the Flooded City",
    "Visit the DLC elevator in the forest",
    "Visit the Forest King’s Cradle",
    "Visit the Place of Memories",
    "Visit the basement of the amusement park",
    "Visit the old Forest King’s grave",
    "Watch Romeo & Juliet’s play",
    “Obtain the Bomb Program”,
    “Buy all chip capacity upgrades”,
    “Self destruct, then die to kamikaze bots”,
    “Complete a speed star race without jumping“,
    “Complete a speed star race without dashing or spear”,
    “Ride the roller coaster back into the station”,
    “Lower the bridge shortcut in the factory”,
    “Die in a factory silo, retrieve your body”,
    “Ride an animal from the forest castle to the commercial facility”,
    “Kill Jean Paul”,
    “Obtain a spear, a short sword, a long sword and gauntlets (no fists)”,
    “Have 5 active buffs”,
    “Completely fill your chip capacity”,
    “Die in flooded city while dialogue is playing”,
    “Buy 1 of every item sold in the bunker”,
    “Obtain 4 key items”,
    “Die in the factory at level 7 8 9 or 10”,
    “Die in city ruins and respawn in the Forest or the flooded city”,
    “Die the desert, respawn in pascal’s village”,
    “Push 2 boxes off edges”,
    “Kill four different type enemies using pod counter attack”,
    “Sell HUD: Sound waves to the amusement park robot 3 times”,
    “Obtain all virtuous weapons”,
    “Obtain a machine weapon from two different shops”,
    “Collect 1x Copper, Silver, and Gold Ore”,
    “Die on the Amusement park coaster at level 5 or 10”,
    “Kill all enemies in the amusement park”,
    “Buy 100 animal bait”, 
    “Drop the crane shortcut in the factory”,
];
