bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Beat a Powerhouse CPU or higher (Chambara)",
    "Beat the Badminton Mii Legend",
    "Beat the Football (One-on-One) Mii Legend",
    "Beat the Tennis Mii Legends in a ‘Best of 5’ Match",
    "Beat the Volleyball Mii Legends",
    "Come back from 0-4 behind to win 7-6 against a strong CPU or higher (Badminton)",
    "Complete 3 Hole Special with +1 or better (Golf)",
    "Complete a 3 Hole Random Game (Golf)",
    "Complete a 3 Hole game, scoring a birdie or better on every hole (Golf)",
    "Complete a 9 Hole Game (Golf)",
    "Complete a hole using the wedge and putter only, without reaching the stroke limit (Golf)",
    "Complete a hole with a double bogey or better, landing in every bunker (Golf)",
    "Complete a hole with a par or better, redlining every shot (excludes putting, Golf)",
    "Complete any Par 5 hole, only landing on the fairway or green (Golf)",
    "Complete any tutorial",
    "Draw in Sudden Death (Chambara)",
    "Get an assist in a goal (Four-on-Four Football)",
    "Get exactly 2 pins on every throw (Except 12th Throw, Bowling)",
    "Hit a 'Rocket Serve' in Volleyball and Tennis",
    "Hit a shot ‘Out’ (Badminton)",
    "Hit the Flag (Golf)",
    "Hit the larger fountain on Hole 11 [unique sfx plays], then complete the hole without reaching the stroke limit (Golf)",
    "Hit three 'X3' spikes in a single point (Volleyball)",
    "Return a ‘Smash’ successfully (Tennis)",
    "Return a ‘Super Smash’ successfully (Badminton)",
    "Score 150 or higher without moving or angling (Bowling)",
    "Score 200 or higher (Bowling)",
    "Score 50 in the Staff Credits minigame",
    "Score a point against a strong CPU or higher, back player only (Tennis)",
    "Score a point against a strong CPU or higher, front player only (Tennis, serving doesn’t count)",
    "Score a point in 2 shots or less (Serve counts as 1 shot, Tennis)",
    "Score an Eagle or better (Golf)",
    "Score with a curved kick (Football)",
    "Score with a diving header (Football)",
    "Score with a sideways kick (Football)",
    "Shoot and score from your own half of the pitch against a strong CPU or higher (Football)",
    "Sink a putt from outside the green (Golf)",
    "Strike (Advanced Special Bowling)",
    "Strikes or Spares Only (Except 12th Throw, Intermediate Special Bowling or higher)",
    "Trigger the ‘Extra Time Goals’ Easter Egg [Hit crossbar and score] (Football Free Practice)",
    "Trigger the ‘Golden Ball’ Easter Egg [10 kick-ups in a row] (Football Free Practice)",
    "Trigger the ‘Nice Block!’ Text (Football)",
    "Turkey (Beginner Special Bowling or higher)",
    "Win 5-0 (Volleyball)",
    "Win a match without conceding a goal (Four-on-Four Football)",
    "Win a match without conceding any points (Tennis)",
    "Win a point by 'Block Out' (Volleyball)",
    "Win a point with a ‘Quick Spike’ (Volleyball)",
    "Win a point with a ‘Slide Attack’ (Volleyball)",
    "Win a point without using a drop shot (Badminton)",
    "Win a point without using a ‘Super Smash’ (Badminton)",
    "Win a point, only using drop shots (Badminton)",
    "Win a round with only thrust attacks (Chambara)",
    "Win a round, attacking less than three times (No Sudden Death, Chambara)",
    "Win against a powerhouse CPU or higher, controlling two characters individually (Tennis)",
    "Win against strong CPUs or higher, controlling both characters (Volleyball)",
    "Win by KO in under 30 seconds (One-on-One Football)",
    "Win with the (Regular) Sword without blocking (Chambara)",
    "Win with the Charge Sword without using a Charge Strike (Chambara)",
    "Win with the Twin Swords without using a Spinning Strike (Chambara)"
];
