bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
	"Sucessfully Scrutinize for a Money Item twice",
	"Successfully Scrutinize for a Soulstone (L) twice",
	"Purchase 99 of a single item",
	"Get a Game Over",
	"Complete two non-Kit Side Stories",
	"Obtain two Olive (M)s",
	"Obtain two Essence of Pomegranate",
	"Talk to two Dogs",
	"Collect from two non-Ch-1 bosses",
	"Finish an encounter with a Guide or Allure NPC",
	"Open two Purple Chests",
	"Beat an optinal NPC Challenge or Provoke",
	"Steal from two non-Ch-1 bosses",
	"Capture four beasts with 3+ strength",
	"Capture three beasts with 4+ strength",
	"Use two Nut (L)s",
	"Defeat the Buffalo encounter at Stonegard",
	"Use four unique Concoctions on a single boss",
	"Obtain a Forbidden weapon",
	"Succeed on a 3% Steal",
	"Restore reputation in two towns",
	"Recruit all male travellers",
	"Obtain four subjobs",
	"Deal 9999 damage in a single hit",
	"Finish a boss with a Guide or Allure NPC",
	"Capture three beasts with 5+ strength",
	"Acquire an Alluring Ribbon",
	"Recruit all female travellers",
	"Defeat an optional boss",
	"Teach BewilderingGrace to four travellers",
	"Have two equipment with +300",
	"Have 8 accessories equipped",
	"Reach 200k leaves",
	"Steal 3 candy from children",
	"Finish a foe with poison damage",
	"Use five soulstone(L) of a single element",
	"Kill a Cait",
	"Obtain eight subjobs",
	"Win a fight with a JP or XP boost",
	"Defeat an indoors Ch 2 boss",
	"Capture three beasts with 6+ strength",
	"Obtain every unique Concoct material",
	"Defeat a beast Ch 2 boss",
	"Reach 600 EAtk on a single traveller (incl. weapon)",
	"Steal 5 candy from children",
	"Equip passives from four different jobs on a single traveller",
	"Purchase two 40k+ items",
	"Recruit every traveller",
	"Capture three unique beasts with 7+ strength",
	"Restore reputation in Grandport",
	"Visit every town",
	"Have 3000+ max hp on one traveller",
	"Reach 500k leaves",
	"Use ten Soulstone (L)s on a single encounter",
	"Obtain a weapon with an elemental boost",
	"Obtain a battle tested weapon",
	"Defeat a boss with mid-fight dialogue",
	"Have three Adamantine items on a single traveller",
	"Finish a Ch 2+ boss with Bewildering Grace",
	"Defeat a boss with 100k+ hp",
	"Obtain a secret job",

	"Unlock a divine skill",
	"Collect 30k+ leaves in one encounter and win",
	"Defeat the Devourer of Men",
	"Defeat the Snake Charmer / Giant Python",
	"Successfully inflict Blind, Poison, Sleep, and Confusion in one fight",
	"Have 1 of each 'Bottle of _ Dust' item",
];
