bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Take a canoe ride to Lumbridge from south of the champions guild",
    "Steal three unique pieces of the HAM robes",
    "Pray at three different altars",
    "Receive payment for filling a box of bananas",
    "Kill a pirate",
    "Obtain an imp bead",
    "Kill a cow in three different pens",
    "Teleport to the essence mine from the Wizards Tower",
    "Drink a wizard mind bomb in the Rimmington tool shop",
    "Buy and Drink a beer in 3 different pubs",
    "Steal a wine and tea from their respective stalls",
    "Complete a lap of rooftop agility in Falador and Al-Kahrid",
    "Complete a lap of rooftop agility in Draynor and Varrock",
    "Take a cadava berry to Krystilia",
    "Pick up a red spider egg",
    "Kill a unicorn on Entrana",
    "Talk to a goblin general",
    "Kill a chaos druid",
    "Have the Sawmill operator make you an oak plank",
    "Buy a shanty pass",
    "Burn 4 different types of logs",
    "Buy a candle in the Lumbridge swamp",
    "Smith an iron bar at two separate furnaces",
    "Equip a chef’s hat",
    "Wave on three free to play bridges",
    "Kill a ghost in Draynor Manor",
    "Play two church organs",
    "Complete the first step of a beginner clue",
    "Cook something on 4 out of 5 ranges inside of Falador",
    "Bring some soft clay to the Oracle",
    "Kill the White Knight with the blue helmet plume",
    "Trade the two F2P gem traders",
    "Bring a steel sword to the guard captain in Varrock castle",
    "Enter the Falador and south Ice Mountain Dwarven Mine entrance",
    "Pick up the Forlorn boot on mudskipper point",
    "Click on all 6 cooking ranges in Varrock",
    "Buy a rake from three different tree patch farmer",
    "Pick up the coins in the bears cage behind Varrock",
    "Sell a fur to the trader in Varrock",
    "Craft leather gloves",
    "Create a blue dye",
    "Get sent to the Port Sarim Jail",
    "Mine some iron in four unique mine locations",
    "Get pricked by a needle from a haystack/bale",
    "Make a pizza dough",
    "Buy a Tyras Helm from the charter ships",
    "Enter the Black Knights Fortress",
    "Have Zandar Horfyre teleport you away from the Dark Wizards Tower",
    "Find a cabbage seed in the Rimmington cabbage patch",
    "Read the book Magicks Most Destructive in the Chemists house",
    "Fire a maple longbow bought from Rimmington",
    "Pick up three unique bronze pickaxe spawns ",
    "Enter the back room of Wydins Food Store",
    "Sell some garlic to the Musa Point general store",
    "Bring a hops seed to Vasquen, the farmer at the hops patch south of Varrock",
    "Purchase a stew in the Port Sarim Rat Pits",
    "Drink an Asgarnian ale by the Dwarven Mines Dragon Slayer chest",
    "Purchase some steel limbs from the Dwarven Mine crossbow shop",
    "Obtain a gem in the Varrock Museum",
    "Fill a bucket from two different wells",
    "Read three signposts west of the River Lum",
    "Talk to Hunding atop the Barbarian Village watchtower wearing any wizard hat",
    "Kill a Fleshcrawler",
    "Talk to Ruantun in the Draynor Sewers while wearing an Event RPG",
    "Pick up 5 unique item spawns on the island of Entrana ",
    "Deliver a redberry on Thurgo south of Port Sarim",
    "Replace the cooked chicken spawn in Falador with a raw one",
    "Buy a steel chainbody from Horvik in Varrock",
    "Fletch any willow bow (u) on the second floor of both Varrock banks",
    "Steal from the guards on top of the southern Falador wall",
    "Sell a full sack of potatoes to the Lumbridge general store",
    "Obtain a brass key",
    "Light a bug lantern while standing next to Vannaka",
    "Mine some silver in the Edgeville dungeon",
    "Obtain 3 types of elemental runes from the dark wizards south of Varrock",
    "Mine some gold ore in the Al Kharid mine",
    "Pick up 3 unique elemental rune spawns",
    "Deliver a snapegrass to Redbeard Frank in Port Sarim",
    "Craft a ball of wool on two unique spinning wheels",
    "Make some sinew on the Edgeville cooking range",
    "Catch a fish while fly fishing next to the goblin house in Lumbridge",
    "Buy a fresh Avas Accumulator",
    "Deliver some poison from Draynor Manor to the Apothecary in Varrock",
    "Obtain an ensouled goblin head",
    "Obtain a rune or arrow drop from a barbarian",
    "Obtain a talisman from an elemental wizard south of Falador",
    "Pull the lever in the party room with two of the following: Newspaper, Kebab, Swamp paste",
    "Cast crumble undead on the skeleton across the wilderness border",
    "Deliver an iron battleaxe from Bobs Axes in Lumbridge to Brians Battleaxes in Port Sarim",
    "Deliver a jug of wine to Osman in Al-Kharid",
    "Kill a hill giant",
    "Pickpocket three potato seeds from a regular farmer",
    "Milk three dairy cows",
    "Cast each elemental bolt spell on the lesser demon in the wizards tower",
    "Smith a bronze dagger on Doric’s anvil",
    "Bury a big bone in the moss giants lair in Edgeville Dungeon",
    "Clean any herb in the standing stone garden north of Falador",
    "Smelt a steel bar in the Edgeville furnace",
    "Buy an elemental staff from Zaff",
    "Catch an impling",
    "Offer (bring) a holy amulet mold to the statue of Saradomin north of Falador"
];