var bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [ {"name": "Squid Cap"},
{"name": "Chef's Hat"},
{"name": "Carnival"},
{"name": "Franken's Nail"},
{"name": "Samurai"},
{"name": "Indian's Feather"},
{"name": "Afro"},
{"name": "Smart Glasses"},
{"name": "Siren Hat"},
{"name": "Quiz Hat"},
{"name": "Magic Hat"},
{"name": "Weathercock"},
{"name": "Light Helmet"},
{"name": "Exclamation"},
{"name": "Musashi's Katana"},
{"name": "Genie Shoes"},
{"name": "Cool Shoes"},
{"name": "Slippers"},
{"name": "Mogutan's Hat"},
{"name": "Hanamizu's ? "},
{"name": "Sunglasses"},
{"name": "Machine Gun"},
{"name": "Ribbon"},
{"name": "Glass Shoes"},
{"name": "Bunny Ears"},
{"name": "Bunny Tail"},
{"name": "Cute High Heels"},
{"name": "Working Helmet"},
{"name": "Pick Axe"},
{"name": "Working Shoes"},
{"name": "Snorkel"},
{"name": "Oxygen Cylinder"},
{"name": "Fins"},
{"name": "Climbing Hat"},
{"name": "Backpack"},
{"name": "Climbing Shoes"},
{"name": "Santa's Cap"},
{"name": "Santa's Sack"},
{"name": "Red Shoes"},
{"name": "Angel Halo"},
{"name": "Angel Wings"},
{"name": "Winged Shoes"},
{"name": "Gangster Kit"},
{"name": "Heroine Kit"},
{"name": "Bunny Kit"},
{"name": "Workman Kit"},
{"name": "Diving Kit"},
{"name": "Climber Kit"},
{"name": "Santa Kit"},
{"name": "Angel Kit"}
]
