bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "13 friends in 4 zones",
    "14 Friends in Cavern Zone",
    "14 friends in lava zone",
    "15 Friends in Iceberg Zone",
    "17 Friends in Beach Zone",
    "2 Bonuses in Tangrowth's Vine Swing",
    "20 Meadow Zone Friends",
    "5 Friends in Haunted Zone",
    "9 Bonuses in Venusaur's Vine Swing",
    "Beat 2 Obstacle Hops",
    "Befriend 2 pokemon hiding in crates",
    "Befriend 4 eeveelutions",
    "Befriend Hitmonlee",
    "Befriend Hitmontop",
    "Befriend Honchkrow",
    "Befriend Infernape",
    "Befriend Kirlia",
    "Befriend Sudowoodo",
    "Befriend Wailord",
    "Best Friend 2 Eeveelutions",
    "Best friend Torterra",
    "Bring 1 Gold Bar to Golem",
    "Clear the goals of 5 different attractions without getting the character's bonus",
    "Friend 5 Pokemon through Hide 'n Seek",
    "Friend Empoleon and Venusaur",
    "Friend Magnezone",
    "Get 15 Bonuses in Bulbasaur's Daring Dash",
    "Get 2 Treehouse Friends in the Meeting Place",
    "Get 3 Bonuses in 6 Attractions",
    "Get 5 friends through quizzes",
    "Get 8 Bonuses with Pikachu",
    "Get HP up by 2 levels",
    "Get T-bolt up by 2 levels",
    "Reach 1000 Berries",
    "Reach 1500 Berries",
    "Reach 2000 Berries"
];
