(function(j, i, g, m, k, n, o) {
    function q(b) {
        var e, f, a = this,
            c = b.length,
            d = 0,
            h = a.i = a.j = a.m = 0;
        a.S = [];
        a.c = [];
        for (c || (b = [c++]); d < g;) a.S[d] = d++;
        for (d = 0; d < g; d++) e = a.S[d], h = h + e + b[d % c] & g - 1, f = a.S[h], a.S[d] = f, a.S[h] = e;
        a.g = function(b) {
            var c = a.S,
                d = a.i + 1 & g - 1,
                e = c[d],
                f = a.j + e & g - 1,
                h = c[f];
            c[d] = h;
            c[f] = e;
            for (var i = c[e + h & g - 1]; --b;) d = d + 1 & g - 1, e = c[d], f = f + e & g - 1, h = c[f], c[d] = h, c[f] = e, i = i * g + c[e + h & g - 1];
            a.i = d;
            a.j = f;
            return i
        };
        a.g(g)
    }

    function p(b, e, f, a, c) {
        f = [];
        c = typeof b;
        if (e && c == "object")
            for (a in b)
                if (a.indexOf("S") < 5) try {
                    f.push(p(b[a], e - 1))
                } catch (d) {}
                return f.length ? f : b + (c != "string" ? "\0" : "")
    }

    function l(b, e, f, a) {
        b += "";
        for (a = f = 0; a < b.length; a++) {
            var c = e,
                d = a & g - 1,
                h = (f ^= e[a & g - 1] * 19) + b.charCodeAt(a);
            c[d] = h & g - 1
        }
        b = "";
        for (a in e) b += String.fromCharCode(e[a]);
        return b
    }
    i.seedrandom = function(b, e) {
        var f = [],
            a;
        b = l(p(e ? [b, j] : arguments.length ? b : [(new Date).getTime(), j, window], 3), f);
        a = new q(f);
        l(a.S, j);
        i.random = function() {
            for (var c = a.g(m), d = o, b = 0; c < k;) c = (c + b) * g, d *= g, b = a.g(1);
            for (; c >= n;) c /= 2, d /= 2, b >>>= 1;
            return (c + b) / d
        };
        return b
    };
    o = i.pow(g, m);
    k = i.pow(2, k);
    n = k * 2;
    l(i.random(), j)
})([], Math, 256, 6, 52);

bingoGenerator = function(bingoList, opts) {
    var LANG = opts.lang || 'name';
    var MODE = opts.mode || "normal";
    var cardType = "Normal";
    var SEED = opts.seed || Math.ceil(999999 * Math.random()).toString();
    var size = 5;

    // simpler generator that just does a random choice without duplicates
    Math.seedrandom(SEED);
    if (true) {
        var usedGoals = {};
        var bingoBoard = [];

        for (var i = 1; i <= 25; i++) {
            var randIndex = Math.floor(Math.random() * bingoList.length);
            while (usedGoals[randIndex]) {
                randIndex = Math.floor(Math.random() * bingoList.length);
            }
            usedGoals[randIndex] = true;

            var goal = bingoList[randIndex];
            bingoBoard[i] = {"name": goal};
        }

        return bingoBoard;
    }
};

var bingoList = [
    "Use no X items",
    "No potions of any kind in battle",
    "Use no TMs",
    "Only Poke balls or Great balls",
    "Use no Repels",
    "Do not white out",
    "Master ball",
    "Lucky egg",
    "Any pokemon with the ability Speed Boost",
    "Any pokemon with the ability Drought",
    "Any pokemon with the ability Trace",
    "Any pokemon with the ability Pressure",
    "Any pokemon with the ability Drizzle",
    "Any pokemon with the ability Rough Skin",
    "Any pokemon with Careful Nature",
    "Any pokemon with Quiet Nature",
    "Any pokemon with Lonely Nature",
    "Any pokemon with Impish Nature",
    "Any pokemon with Serious Nature",
    "Any pokemon with Hasty Nature",
    "Any pokemon with Timid Nature",
    "Any pokemon with Quirky Nature",
    "Any pokemon with Brave Nature",
    "Any pokemon with Docile Nature",
    "Pokemon with a multi-hit move",
    "Hit a OHKO move",
    "Pokemon with 4 water moves",
    "Pokemon with 4 grass moves",
    "Pokemon with 4 fire moves",
    "Pokemon with 4 poison moves",
    "Pokemon with 4 electric moves",
    "Pokemon with 4 psychic moves",
    "Pokemon with 4 steel moves",
    "Pokemon with 1 fire, 1 water, 1 grass, and 1 electric move",
    "Pokemon with a recharge move",
    "Pokemon with a turn charging move",
    "Pokemon with a weather move",
    "Pokemon with a consecutively executed move",
    "Pokemon with a multi hit move",
    "Pokemon with a self healing move",
    "Pokemon with 4 non-damage dealing moves",
    "Pokemon with 4 non-normal moves",
    "Pokemon with 4 damage dealing moves",
    "Pokemon with 4 normal moves",
    "Pokemon with 4 STAB moves",
    "Pokemon with Tackle",
    "Pokemon with Sacred Fire",
    "Pokemon with Doom Desire",
    "3 Pokemon over 200 lbs (90.75 kg)",
    "3 Pokemon under 5 lbs (2.25 kg)",
    "Pokemon with a 5 pp move",
    "Obtain the Pokenav",
    "Deliver the letter to Steven",
    "Win 6 soda pops",
    "TM 46",
    "Leave 2 pokemon at the daycare",
    "3 Badges",
    "Obtain a Macho Brace",
    "Buy a lava cookie",
    "Watch your interview on TV",
    "TM 05",
    "Hoenn dex 10 owned",
    "National dex 20 owned",
    "Battle 50 trainers",
    "View a replica SS Anne",
    "Complete level 1 of Trick Master",
    "Evolve a pokemon at level 30 or higher",
    "Defeat a trainer in a Pokenav rematch",
    "Defeat Wally",
    "Finish inside your house",
    "Defeat all 10 trainers on Route 116",
    "Defeat all 7 trainers in Dewford Gym",
    "Defeat all 9 trainers on route 117",
    "Defeat all 4 trainers on route 112",
    "Change wallpaper of a PC box",
    "Defeat 4 bug catchers",
    "Restore your party's health outside of a Pokemon Center",
    "Catch a pokemon in very tall grass",
    "Get a berry from the Berry Master's wife",
    "$50,000 or more",
    "Wailmer Pail",
    "Itemfinder",
    "Soot Sack",
    "Go-Goggles",
    "Escape from battle with a Fluffy Tail",
    "Release starter before level 10",
    "Register MOM in the Pokenav",
    "Register Profesor Birch in the Pokenav",
    "Amulet Coin",
    "Plant 5 berries",
    "Defeat 7 youngsters",
    "Defeat 2 Ladys",
    "Defeat 2 Rich Boys",
    "Defeat 3 Twins",
    "Defeat 8 Hikers",
    "Defeat 3 Pokefans",
    "Defeat 6 Guitarists",
    "Defeat 3 Aroma Ladys",
    "Stop a Pokemon from evolving",
    "Pokemon with 4 HM moves",
    "Defeat every trainer in each gym you enter",
    "Teach 3 gym leader TMs",
    "Register 10 people in the Pokenav",
    "5 double battles",
    "50 berries in bag",
    "3 match win streak at battle tent",
    "Complete level 2 of Trick Master",
    "Defeat Rival 3 times",
    "Use itemfinder to find a hidden item",
    "HM06 Rock Smash",
    "3 HMs",
    "Defeat all 6 Cycling Road trainers",
    "Coin case",
    "Win on the slot machines",
    "Win a spin of roulette",
    "Collect an egg from the daycare",
    "Talk to 6 overworld pokemon",
    "4 HMs",
    "Have Lanette name the PC storage system",
    "Perform a trick on a Mach Bike",
    "Perform a trick on a Acro Bike",
    "Craft any item at the Glass Workshop",
    "Defeat 4 trainers at the Winstrate house",
    "Defeat Maxie",
    "4 Badges",
    "Catch a Pokemon while surfing",
    "Hoenn dex 100 seen",
    "National dex 200 seen",
    "Hoenn dex 15 owned",
    "National dex 25 owned",
    "3 pokemon at or above Lv 40",
    "5 pokemon at or above Lv 35",
    "6 pokemon at or above Lv 30",
    "Battle 75 trainers",
    "Complete level 3 of Trick Master",
    "10 different berries",
    "8 key items",
    "5 types of Poke balls",
    "15 TMs",
    "Catch a Pokemon while surfing",
    "Catch a Pokemon by fishing",
    "Defeat all 9 trainers on route 103",
    "Defeat all 10 non-desert trainers on route 111",
    "Defeat all 8 desert trainers on route 111",
    "Defeat all 10 trainers on route 113",
    "Defeat all 10 trainers on route 115",
    "Defeat all 9 trainers (including Magma) on Mt. Chimney",
    "Defeat all 6 trainers (including Magma) on Jagged Pass",
    "Catch a Pokemon in Mirage Tower",
    "Revive a fossil",
    "Fill a PC box",
    "Have the Move Reminder/Maniac reteach a move",
    "Defeat all 12 trainers on route 114",
    "Defeat all 8 trainers in the Petalburg Gym",
    "HM 02",
    "Catch 5 pokemon in the Safari Zone",
    "Delete a move",
    "$75,000 or more",
    "2 fishing rods",
    "Use HP Up, Protein, Iron, Calcium, Zinc, and Carbos",
    "Own 10 different Poison type Pokemon",
    "Own 10 different Flying type Pokemon",
    "Own 10 different Normal type Pokemon",
    "Own 10 different Grass type Pokemon",
    "Own 10 different Water type Pokemon",
    "Own 8 different Bug type Pokemon",
    "Own 6 different Ground type Pokemon",
    "Own 6 different Fire type Pokemon",
    "Own 6 different Psychic type Pokemon",
    "Own 6 different Pokemon with no shared type",
    "Own 6 different dual typed Pokemon",
    "Own 6 different single typed pokemon",
    "Own 6 different Rock type Pokemon",
    "Own 5 different Fighting type Pokemon",
    "Own 5 different Electric type Pokemon",
    "Own 5 different 4x weakness Pokemon",
    "Own 5 different starters/starter evolutions",
    "Own 5 Legendary or Mythical Pokemon",
    "Own 3 different Dark type Pokemon",
    "Own 3 different Dragon type Pokemon",
    "Own 3 different Steel type Pokemon",
    "Own 3 different Ghost type Pokemon",
    "Own 3 different Ice type Pokemon",
    "Own 3 baby Pokemon",
    "Own 3 Eevee family Pokemon",
    "Defeat 4 Lasses",
    "Defeat 5 Fisherman",
    "Defeat 5 Ruin Maniacs",
    "Defeat 7 Battle Girls",
    "Teach 10 TMs",
    "3 pokemon with status conditions",
    "Faint 2 pokemon with 1 move",
    "Evolve a pokemon twice",
    "Evolve 3 different pokemon",
    "Evolve 3 pokemon with different stones",
    "Starter Pokemon never faints",
    "Teach TM 49",
    "TM 32",
    "TM 01",
    "A pokemon with a move that causes the user to faint",
    "Register 20 people in the Pokenav",
    "10 double battles",
    "Hatch an egg",
    "TM 32",
    "Win Verdanturf Town battle tent",
    "Any Lv 50 Pokemon",
    "Make a secret base",
    "Win Fallarbor Town battle tent",
    "5 Badges",
    "6 Badges",
    "5 HMs",
    "TM 24",
    "TM 10",
    "Hoenn dex 125 seen",
    "National dex 250 seen",
    "Hoenn dex 20 owned",
    "National dex 35 owned",
    "75 berries in bag",
    "Defeat Team Aqua at the Weather Institute",
    "Defeat Rival 4 times",
    "6 HMs",
    "Devon Scope",
    "Kill or catch 2 Kecleons",
    "Battle 125 trainers",
    "Make a Pokeblock",
    "Come in 4th place in a Pokemon Contest",
    "View a very old painting",
    "TM 44",
    "Defeat a non-rival trainer a 3rd time",
    "Complete level 4 of Trick Master",
    "Complete level 5 of Trick Master",
    "Defeat all 8 trainers on route 118",
    "Defeat all 17 trainers on route 119",
    "Defeat all 14 trainers on route 120",
    "Defeat all 10 trainers on route 121",
    "Catch a pokemon underwater",
    "$100,000 or more",
    "$150,000 or more",
    "Magma Emblem",
    "All 3 fishing rods",
    "Defeat any gym leader without losing any HP",
    "Defeat 5 Swimmers",
    "Defeat 10 Bird Keepers",
    "Smach 10 rocks",
    "Defeat 3 Psychics (trainers)",
    "Defeat 4 Pokemon Breeders",
    "Move a boulder",
    "Exactly $0",
    "Complete one in-game trade",
    "Leave Skitty and Wailord at the daycare",
    "Lugia or Ho-Oh",
    "Raikou, Entei, or Suicune",
    "Zapdos and Raikou",
    "Moltres and Entei",
    "Articuno and Regice",
    "Regirock, Regice, or Registeel",
    "Articuno, Zapdos, or Moltres",
    "Rayquaza",
    "Kyogre and Groudon",
    "Treecko and Deoxys",
    "Jirachi",
    "Latios and Latias",
    "2 of Metagross, Tyranitar, Salamance, or Dragonite",
    "Huntail or Gorebyss",
    "Walerin or Poliwrath",
    "Banette or Dusclops",
    "Castform",
    "Milotic or Gyarados",
    "Magikarp and Feebas",
    "Any 2 fossil Pokemon",
    "Corphish",
    "Lunatone or Solrock",
    "Chikorita and Celebi",
    "Zangoose or Seviper",
    "Cacnea",
    "Torkoal",
    "Wailord and Skitty",
    "Sharpedo",
    "Bulbasaur and Mew",
    "Plusle and Minun",
    "Manectric or Raichu",
    "Medicham or Hariyama",
    "Shedinja",
    "Slaking or Exploud",
    "Breloom",
    "Masquerain or Butterfree",
    "Gardevoir",
    "Female Wingull nicknamed Peeko",
    "Swellow, Fearow, or Noctowl",
    "Linoone, Sentret, or Raticate",
    "Celebi",
    "Blissey",
    "Miltank",
    "Sudowoodo",
    "Smoochum, Elekid or Magby",
    "Hitmonlee, Hitmonchan, or Hitmontop",
    "Skarmory",
    "Delibird",
    "Smeargle or Ditto",
    "Spinda",
    "Dustox or Beautifly",
    "Ledian or Ariados",
    "2 of Pichu, Cleffa, Igglybuff, or Togepi",
    "Venusaur, Meganium, or Sceptile",
    "Charizard, Typlosion, or Blaziken",
    "Blastoise, Feraligatr, or Swampert",
    "Exeggutor, Xatu, or Grumpig",
    "Ampharos",
    "Scizor, Heracross, or Pinsir",
    "Shuckle",
    "Granbull, Wigglytuff, or Clefable",
    "Unown",
    "Wobbuffet",
    "Slowking or Slowbro",
    "Politioed or Poliwrath",
    "Miltank nicknamed Moo",
    "Sunflora nicknamed Sunny",
    "Bellossom or Vileplume",
    "Mewtwo or Mew",
    "Mr. Mime nicknamed Mimey",
    "Farfetch'd nicknamed Dux",
    "Rhydon or Donphan",
    "Porygon or Porygon2",
    "Kangaskhan nicknamed Jumpy",
    "Kingler or Octillery",
    "Seviper or Arbok",
    "Swalot or Muk",
    "Roselia or Victreebel",
    "Tebtacruel or Qwilfish",
    "Ursaring or Tauros",
    "Rapidash, Arcanine, or Ninetails",
    "Chimecho",
    "Whiscash or Quagsire",
    "Camerupt or Houndoom",
    "Kingdra or Flygon",
    "Absol",
    "Male & Female Luvdisc nicknamed Caserin & Luverin",
    "Sharpedo or Starmie",
    "Male Pikachu nicknamed Sparky",
    "Charmeleon nicknamed Zippo",
    "Female Meowth nicknamed Meowzie",
    "Growlithe nicknamed Growlie",
    "Feraligatr nicknamed Wani-Wani",
    "Female Misdreavus nicknamed Little Miss",
    "Jigglypuff nicknamed Pink",
    "Male Delcatty nicknamed Johnny",
    "Pupitar nicknamed Cruise",
    "Butterfree nicknamed Happy",
    "Taillow nicknamed Rose",
    "Female Pikachu nicknamed Volty",
    "Beldum nickname Iron",
    "Female Rhyhorn nicknamed Hornlette",
    "Mr. Mime nicknamed Marcel",
    "Nidoran F nicknamed Spot",
    "Nidorina nicknamed Terry",
    "Lickitung nicknamed Marc",
    "Jynx nicknamed Lola",
    "Electrode nicknamed Doris",
    "Tangela nicknamed Crinkles",
    "Seel nicknamed Sailor",
    "Mr. Mime nicknamed Miles",
    "Machamp nicknamed Ricky",
    "Dugtrio nicknamed Gurio",
    "Parasect nicknamed Spike",
    "Rhydon nicknamed Buffy",
    "Dewgong nicknamed Cezanne",
    "Muk nicknamed Sticky",
    "Beedrill nicknamed Chikuchiku",
    "Mew nicknamed Bart",
    "Pidgeot nicknamed Marty",
    "Beedrill nicknamed Stinger",
    "Male Onix nicknamed Rocky",
    "Female Machop nicknamed Muscle",
    "Voltorb nicknamed Volty",
    "Female Rhydon nicknamed Don",
    "Male Aerodactyl nicknamed Aeroy",
    "Male Rapidash nicknamed Runny",
    "Female Dodrio nicknamed Doris",
    "Male Xatu nicknamed Paul",
    "Magneton nicknamed Maggie.",
    "Male makuhita nicknamed Makit",
    "Female Skitty nicknamed Skitit",
    "Female Corsola nicknamed Coroso",
    "Male Seedot nicknamed Dots",
    "Female Plusle nicknamed Pluses",
    "Male Horsea nicknamed Seasor",
    "Male Meowth nicknamed Meowow",
    "Male Elekid nicknamed Zaprong",
    "Male Steelix nicknamed Rusty",
    "Chansey nicknamed Pinky",
    "Female Charizard nicknamed Charla",
    "Nidorina and Nidorino nicknamed Maria and Tony",
    "Mareep nicknamed Fluffy",
    "Male Pikachu nicknamed Puka",
    "2 Bellossom nickanmed Bella and Belle",
    "Scizor nicknamed Masamune",
    "Pidgey nicknamed Ken",
    "Zubat nicknamed Mimi",
    "3 Swinub nicknamed Su, Ein, and Ub",
    "Natu nicknamed Naughty",
    "Flaaffy nicknamed Hannah",
    "Linoone nicknamed Tokin",
    "Dunsparce, Tauros, or Stantler",
    "Any pokemon exactly 1' tall",
    "Any pokemon exactly 2' tall",
    "Scyther or Yanma",
    "Ludicolo or Shiftry",
    "Volbeat and Illumise",
    "Claydol or Piloswine",
    "Relicanth or Mantine",
    "Forretress or Mawile",
    "Sableye or Gengar",
    "Ursaring or Donphan",
    "Primeape or Persian",
    "Kecleon",
    "Glalie or Lapras",
    "Bulbasaur and Deoxys"
];

