bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList =
[
    "$50.000 on hand",
    "20 TMs",
    "3 Pokémon that start with the same letter",
    "3 baby Pokémon",
    "4x super effective move",
    "7 different Pokéballs",
    "7 different apricorns",
    "A Lake Guardian",
    "A Pikachu clone",
    "A Pokémon of each type",
    "A Pokémon that changes form in weather",
    "A Pokémon that’s 15 lbs or less",
    "A Pokémon that’s 2'00” or less",
    "A Pokémon that’s 300 lbs. or more",
    "A Pokémon that’s 7'00” or more",
    "A Pokémon too big to walk in buildings",
    "A Pokémon with 4 STAB moves",
    "A Pokémon with 4 non-TM status moves",
    "A legendary beast",
    "A legendary bird",
    "A mythical Pokémon",
    "A pseudo-legendary",
    "A shiny Pokémon",
    "Ability from a legendary",
    "Ability that affects Attack",
    "Ability that affects Speed",
    "Ability that gives an immunity",
    "An Eeveelution",
    "Battle Eusine",
    "Battle a legendary",
    "Black Belt, Expert Belt or Focus Sash",
    "BlackGlasses, Wise Glasses or Choice Specs",
    "Call Youngster Joey",
    "Catch a Pokémon from Super Smash Bros Brawl",
    "Catch a Pokémon in the Safari Zone",
    "Catch a Pokémon with a Rod",
    "Catch a cat Pokémon",
    "Catch a dog Pokémon",
    "Catch a roamer",
    "Catch a starter",
    "Charcoal",
    "Defeat 5 Youngsters",
    "Defeat 7 Hikers",
    "Defeat a Gym Leader with a Pokémon 8 levels lower",
    "Defeat a Gym Leader with animations on",
    "Defeat a Pokémon with either Burn, Poison or confusion",
    "Defeat a doubles partner",
    "Defeat all Rocket HQ wild Pokémon",
    "Defeat all trainers at Lake of Rage",
    "Defeat all trainers in Goldenrod Tunnel",
    "Defeat all trainers in National Park",
    "Defeat all trainers in the Lighthouse",
    "Defeat all trainers on Route 47",
    "Ditto, Stantler, Kecleon or Chatot",
    "Do an in-game trade",
    "Don’t use Repels",
    "Don’t use X items",
    "Don’t use any TMs",
    "Dunsparce, Wobbuffet, Yanma or Qwilfish",
    "Electrizer, Magmarizer, Protector or Reaper Cloth",
    "Encounter a Pokémon with a unique theme",
    "Everstone",
    "Evolve a Pokémon with a stone",
    "Evolve the same Pokémon twice",
    "Exp. Share",
    "Finish a battle in red bar",
    "Freeze a Pokémon",
    "Get 2 Pokémon with the same nature",
    "Get Kenya",
    "Get Shuckie",
    "Get a Headbutt encounter",
    "Get a PokéBall from Kurt using Apricorns",
    "Get a Silver Wind/Ancientpower/Ominous Wind boost",
    "Get a haircut",
    "Get an item from your companion",
    "Get dressed as a Rocket Grunt",
    "Get gift Dratini",
    "Get gift Eevee",
    "Get gift Tyrogue",
    "Get through Dark Cave without Flash",
    "Glacier Badge",
    "Groudon, Kyogre or Rayquaza",
    "Heracross, Aipom or Pineco",
    "Hit 5 times with a multi-hit move",
    "Itemfinder",
    "Land a move with 70% accuracy",
    "Lugia or Ho-Oh",
    "Luvdisc, Corsola or Finneon",
    "Magmotar, Electevire, Togekiss or Yanmega",
    "Mew or Mewtwo",
    "Miltank, Tauros, Farfetch'd or Snubbull",
    "Mineral Badge",
    "Mystic Water",
    "No money on hand or mom",
    "Numel, Carvanha, Baltoy or Gulpin",
    "Obtain a fossil Pokémon",
    "One of the Regis",
    "Own 10 Normal types",
    "Palkia, Dialga or Giratina",
    "Participate in Pokéathlon",
    "Play Voltorb Flip",
    "Push all boulders in the holes in Ice Path",
    "Release a legendary",
    "Release starter before level 11",
    "Rematch with Youngster Joey",
    "Slowpoketail",
    "Solve a puzzle in Ruins of Alph",
    "Stop starter from evolving 3 times",
    "TM05 Roar",
    "TM09 Bullet Seed",
    "TM10 Hidden Power",
    "TM18 Rain Dance",
    "TM21 (Frustration) or TM27 (Return)",
    "TM36 Sludge Bomb",
    "TM43 Secret Power",
    "Teddiursa, Phanpy, Ledyba or Spinarak",
    "Trigger Suicune-cutscene on Route 42",
    "Use Struggle",
    "Weather-related move",
    "Win Bug Catching Contest",
    "Zangoose, Seviper, Scyther or Pinsir",
    "€10.000 on mom"
];
