bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
{"name": "Crit Leon or Hop"},
{"name": "Spin around for 1 Minute"},
{"name": "Die in the Wild Area"},
{"name": "Defeat a strong-looking wild Pokemon"},
{"name": "Bike into a Gurdurr on Route 8"},
{"name": "Defeat a breeder in the Wild Area"},
{"name": "Buy a TR from a Watt Trade and teach it (Min 2,000 Watts)"},
{"name": "Catch a 1* Raid Battle Pokemon"},
{"name": "Catch a 2* Raid Battle Pokemon"},
{"name": "Catch a 3* Raid Battle Pokemon"},
{"name": "Dynamax in every gym you enter"},
{"name": "Trade for Cheekers"},
{"name": "Trade for Cash"},
{"name": "Trade for Candyfloss"},
{"name": "Trade for Masky"},
{"name": "Trade for Reddos/Blubop"},
{"name": "Trade for Mymo"},
{"name": "Trade for Linear"},
{"name": "Talk to all the Ball Guys"},
{"name": "Obtain TMs Rest and Snore"},
{"name": "15 TMs"},
{"name": "Trigger Yamper's ability"},
{"name": "Cook a Sweet Potato Curry"},
{"name": "Cook a Spicy Mushroom Curry"},
{"name": "Cook a Sour Apple Curry"},
{"name": "Cook a Bitter Sausage Curry"},
{"name": "Cook 3 different curries (Different taste doesn’t count)"},
{"name": "Cook 2 curries of at least Milcery Class"},
{"name": "5 Curry Dex Recipes"},
{"name": "Obtain 5 Fancy Apples"},
{"name": "Get 100,000 Pokedollars"},
{"name": "Get 5,000 Watts"},
{"name": "1 hour Poké Job"},
{"name": "Old Letter quest"},
{"name": "Fossil Pokémon"},
{"name": "Dynamax Rookidee"},
{"name": "Dynamax Wooloo"},
{"name": "Buy 69 Pokeballs"},
{"name": "Buy 420 Pokeballs"},
{"name": "Obtain 10 revives"},
{"name": "1 of each battle item"},
{"name": "Release starter before reaching Motostoke"},
{"name": "4 Badges Owned"},
{"name": "Catch all 3 pokemon in Kabu’s Gym Mission"},
{"name": "Defeat all trainers on Route 3"},
{"name": "Sirfetch’d"},
{"name": "Get a Flapple/Appletun"},
{"name": "Use a Cracked Pot on a Sinistea"},
{"name": "Evolve Milcery"},
{"name": "Shake 5 different Berry Trees"},
{"name": "Make Sonia do the Wobbuffet Face"},
{"name": "Flex on Mum"},
{"name": "TM69 Psycho Cut"},
{"name": "Play with your pokemon in Pokemon Camp"},
{"name": "TM99 Breaking Swipe"},
{"name": "TM00 Mega Punch"},
{"name": "Morpeko"},
{"name": "Evolve a Pokemon via Evolution Stone"},
{"name": "Escape from Battle without Running, Fainting, or Winning"},
{"name": "Amulet Coin"},
{"name": "Lucky Egg"},
{"name": "4 Type Boosting Items"},
{"name": "Beat up Hop 4 times"},
{"name": "Rotom Rally: Meetup Spot"},
{"name": "Rotom Rally: East Lake Axewell"},
{"name": "Rotom Rally: Dappled Grove"},
{"name": "Rotom Rally: Giant’s Seat"},
{"name": "Rotom Rally: Giant’s Cap"},
{"name": "Rotom Rally: Hammerlocke Hills"},
{"name": "Rotom Rally: Bridge Field"},
{"name": "Overworld Butterfree"},
{"name": "Elgyem"},
{"name": "Buy 10,000 Pokedollars of Clothes"},
{"name": "Buy 20,000 Pokedollars of Clothes"},
{"name": "Buy 30,000 Pokedollars of Clothes"},
{"name": "Raboot"},
{"name": "Thwackey"},
{"name": "Drizzile"},
{"name": "Get a 5 streak on the Digging Duo"},
{"name": "A Pokemon Taller than 7 feet"},
{"name": "An Eeveelution"},
{"name": "Choice Specs"},
{"name": "Choice Scarf"},
{"name": "Choice Band"},
{"name": "Get a Haircut"},
{"name": "Hi-Tech Earbuds"},
{"name": "Buy 5 Curry Ingredients"},
{"name": "Say Yes to Opal Travel"},
{"name": "Catch 5 different Bug Type Pokemon"},
{"name": "Catch 3 different Grass Type Pokemon"},
{"name": "Catch 4 different Normal Type Pokemon"},
{"name": "Catch an evolved Pokemon"},
{"name": "Evolve a Gen 1 Pokemon"},
{"name": "Evolve a Gen 2 Pokemon"},
{"name": "Evolve a Gen 3 Pokemon"},
{"name": "Evolve a Gen 4 Pokemon"},
{"name": "Evolve a Gen 5 Pokemon"},
{"name": "Evolve a Gen 6 Pokemon"},
{"name": "Evolve a Gen 7 Pokemon"},
{"name": "Evolve a Gen 8 Pokemon"},
{"name": "Release One Pokemon"},
{"name": "Defeat a Gym Leader with Battle Animations on"},
{"name": "Win a battle in the Battle Cafe"},
{"name": "Use Struggle"},
{"name": "Defeat 8 Team Yell Grunts"},
{"name": "60 Pokemon Seen"},
{"name": "80 Pokemon Seen"},
{"name": "100 Pokemon Seen"},
{"name": "10 Pokemon Owned"},
{"name": "15 Pokemon Owned"},
{"name": "20 Pokemon Owned"},
{"name": "Watch The Opening Ceremony Cutscene"},
{"name": "Buy and Wear the Poison Uniform"},
{"name": "Buy and Wear the Steel Uniform"},
{"name": "Buy and Wear the Electric Uniform"},
{"name": "Change your Hairstyle before the 4th gym"},
{"name": "Change your Hairstyle after the 5th gym"},
{"name": "Do not use EXP Candies or Rare Candies"},
{"name": "No Pokecenters"},
{"name": "Collect 5 different Evolutionary Stones"},
{"name": "Own 1 pokemon from each generation"},
{"name": "Don’t evolve your starter 3 times"},
{"name": "Don’t evolve your starter 5 times"},
{"name": "Have a pokemon with a weather-related ability"},
{"name": "Upgrade your Rotom Bike to the max"},
{"name": "Upgrade your Rotom Bike once"},
{"name": "Get TM81 Bulldoze"},
{"name": "Get TM73 Cross Poison"},
{"name": "Defeat a Pokemon from a 5* Raid Battle"},
{"name": "Defeat a Pokemon from a 4* Raid Battle"},
{"name": "6 Pokemon that share the same type"},
{"name": "3 pokemon starting with the same letter"},
{"name": "Catch enough pokemon to complete the Alphabet"},
{"name": "A pokemon weighing less than 1 LB"},
{"name": "A pokemon weighing at least 150 LBs"}
];
