bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Acquire ASCENDANT LIGHT",
    "Acquire CLING GEM",
    "Acquire INDIGNATION",
    "Acquire SOLAR WIND",
    "Acquire SOUL CUTTER",
    "Acquire STRIKEBREAK",
    "Acquire SUN GREAVES",
    "Acquire SUNSETTER",
    "BOUNCE off of 4 DIFFERENT ENEMIES in a row",
    "Collect 1 GOOD GRACE",
    "Collect 2 CLEAR MINDS",
    "Collect 2 GOOD GRACES",
    "Collect AERIAL FINESSE",
    "Collect EMPATHY",
    "Collect HELIACAL POWER",
    "Collect MARTIAL PROWESS",
    "Collect PILGRIMAGE",
    "Collect all 3 CLEAR MINDS",
    "Defeat 10 FLYING SWORDS",
    "Defeat 15 SPIKED WHEELS",
    "Defeat 4 ARMOR KNIGHTS",
    "Defeat 4 MAIDS",
    "Defeat 5 HAND STATUES",
    "Defeat 7 TUBAISTS",
    "Defeat STRONG EYES",
    "Defeat the TINY KNIGHT",
    "Destroy 3 STRIKEBREAK WALLS",
    "Destroy 7 BREAKABLE WALLS (including strikebreak walls)",
    "Find and equip the PROFESSIONAL outfit",
    "Flip 10 UNIQUE LEVERS",
    "Flip 5 UNIQUE LEVERS",
    "Get KNOCKED INTO A DEATH PLANE by an enemy",
    "Get the MAJOR KEY in SANSA KEEP",
    "Get the MAJOR KEY in the EMPTY BAILY",
    "Get the MAJOR KEY in the TOWER REMAINS",
    "Get the MAJOR KEY in the TWILIGHT THEATRE",
    "Get the MAJOR KEY in the UNDERBELLY",
    "Lead a FLYING SWORD into a DEATH PLANE",
    "Obtain 2 SMALL KEYS",
    "Obtain 3 HEALTH UPGRADE FRAGMENTS",
    "Obtain 3 SMALL KEYS",
    "Obtain 5 HEALTH UPGRADE FRAGMENTS",
    "Obtain 7 HEALTH UPGRADE FRAGMENTS",
    "Obtain 9 HEALTH UPGRADE FRAGMENTS",
    "REST on 3 different STOOLS",
    "Read every BOOK in the LIBRARY",
    "Save at 3 SAVE CRYSTALS in DILAPIDATED DUNGEON",
    "Save at 3 SAVE CRYSTALS in SANSA CASTLE",
    "Save at 3 SAVE CRYSTALS in SANSA KEEP",
    "Save at 3 SAVE CRYSTALS in the LIBRARY",
    "Save at 3 SAVE CRYSTALS in the TWILIGHT THEATER",
    "Save at 3 SAVE CRYSTALS in the UNDERBELLY",
    "Speak to 5 DIFFERENT NPCs",
    "Speak to the \"KILL AGAIN\" GOAT"
];
