bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Level 10",
    "Level 20",
    "Level 30",
    "Level 40",
    "Level 50",
    "Level 60",
    "Level 70",
    "Level 80",
    "Level 90",
    "Level 100",
    "Defeat The Mega Censor",
    "Defeat The Phantom",
    "Defeat The Den Mother",
    "Defeat Linda",
    "Aquire Confusion Grenade",
    "Aquire Telekenisys",
    "Aquire Pyrokenisys",
    "Aquire Invisibility",
    "Aquire Clairevoyance",
    "Collect all of Baggage (Oleander)",
    "Collect all of Baggage (Tumbler)",
    "Collect all of Baggage (Sasha)",
    "Collect all of Baggage (Milla)",
    "Collect all of Baggage (Linda)",
    "Collect all of Baggage (Boyd)",
    "Collect all of Baggage (Gloria)",
    "Collect all of Baggage (Fred)",
    "Collect all of Baggage (Edgar)",
    "Collect a Mental Layer Upgrade",
    "Collect an Ammo Upgrade",
    "Aquire the Dowsing Rod",
    "Aquire the Cobweb Duster",
    "By a Psi Core",
    "Create a psi Card for cobwebs",
    "Change your Psi ball color",
    "Aquire Mental Magnet",
    "Collect 50 Arrowheads",
    "Collect 100 Arrowheads",
    "Collect 150 Arrowheads",
    "Collect 200 Arrowheads",
    "Eat Dinner (Cook a critter)",
    "Defeat 1 Wrestler",
    "Defeat 2 Wrestlers",
    "Defeat 3 Wrestlers",
    "Defeat 4 Wrestlers",
    "Defeat 1 Nightmare",
    "Defeat 2 Nightmares",
    "Buy a painting (over 0 cost)",
    "Collect 4 scavenger hunt items",
    "Collect 8 scavenger hunt items",
    "Collect 12 scavenger hunt items",
    "Collect 16 scavenger hunt items",
    "Enter Milla's toybox",
    "Defeat Kochamara",
    "Collect Rolling Pin",
    "Take a bird's eye view (Clairvoyance a bird)",
    "Collect 2 Brains",
    "Collect 4 Brains",
    "Collect 6 Brains",
    "Collect 8 Brains",
    "Collect 10 Brains",
    "Collect Crow's Feather",
    "Collect Lilli's Bracelet",
    "Defeat Coach punching game Level 1",
    "Defeat Coach punching game Level 2",
    "Defeat Coach punching game Level 3",
    "Free the Blimp Pilot",
    "Collect 2 Psi Challenge markers",
    "Collect 4 Psi Challenge markers",
    "Collect 6 Psi Challenge markers",
    "Open a safe in Oleander's mind",
    "Open a safe in the Brain Tumbler",
    "Open a safe in Sasha's Mind",
    "Open a safe in Milla's Mind",
    "Open a safe in Linda's Mind",
    "Open a safe in Boyd's Mind",
    "Open a safe in Gloria's Mind",
    "Open a safe in Edgar's Mind",
    "Open a safe in Fred's Mind",
    "Open a safe in Meat Circus",
    "Open a safe in Every Mind",
    "Defeat Oly's Dad (Battle 1)",
    "Defeat Oly's and Raz's Dads (Battle 2)",
    "Defeat Dad Monster (Final Battle)",
    "Defeat a Brain Tank",
    "Visit Every part of camp",
    "Talk to Every Version of Cruller",
    "Shoot Hoops with Raz as ball",
    "Climb to the top of the GCP (above the trees)",
    "Visit Edgar's Secret Garden",
    "Help Dogen through minefield",
    "Have Raz repeat Oleander's Speech",
    "Change a TV channel",
    "Teleport via Worm",
    "Back to HQ using Bacon",
    "Read a message",
    "Kill a Psychic Bear",
    "Set off a car Alarm",
    "Get Sniped",
    "Get confused by rat",
    "Show Pokeylope to 5 Campers",
    "Telekenysis 5 Campers",
    "Psi blast 5 Campers",
    "Heat up 5 Campers",
    "Kill a psychic cougar",
    "Steal a Squirrel's Nuts",
    "Visit Oleander's Secret Tunnel",
    "Camp History Lesson",
    "Light the Main Campfire",
    "Waterfall Secret Psi Card",
    "Offer Someone cake",
    "Haybale Target Practice",
    "Buy some Candy",
    "Fire behind the Firestarters",
    "Ride a canoe",
    "Use a bathroom",
    "Recruit a soldier",
    "Recruit a builder",
    "Storm the Castle",
    "Grab a bunny",
    "Make your own Psi challenge marker",
    "Clear 5 cobwebs",
    "Clear 10 cobwebs",
    "Clear 15 cobwebs",
    "Collect 20 figments in a level",
    "Collect 40 figments in a level"
];
