bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Beat Bongo hills without dying and without taking damage while getting all cages",
    "Beat Gong heights screen 2 without letting go of right",
    "Beat Hard Rocks while having exactly 20 cages",
    "Beat Pencil Pentathlon without running nor helicoptering in screens 1 and 3",
    "Beat SMC1 while only being able to touch 1 pink eraser",
    "Beat Space Mama while having exactly 19 cages",
    "Beat Space mama after beating sax",
    "Beat allegro presto without having the ring grab powerup",
    "Beat allegro screen 1 while only collecting 6 tings or less",
    "Beat eat at joe’s without dying and without taking damage",
    "Beat first screen of mr. sax as small rayman",
    "Beat moskito after beating sax",
    "Beat moskito’s nest with 1 punch",
    "Beat mr sax with only 12 punches and without getting hit",
    "Beat mr skops without using punch",
    "Beat skops 1 without standing on a surface apart from the start and 3 red platforms",
    "Beat the 2nd screen of Twilight Gulch without taking a hit",
    "Beat the BH4 Magician under 23 seconds without using run and helicopter",
    "Beat the EP 3 Magician under 27 seconds",
    "Beat the PPW2 Magician under 8 seconds.",
    "Beat the final screen of PP without walking off of slippery platforms",
    "Beat viking mama while having exactly 20 lives",
    "Clip 5 times in Mr Sax's Hullaballoo without pressing down",
    "Collect 5 cages in twilight gulch without getting hit",
    "Collect all 51 tings in MSP1 and reach the endsign without taking a hit",
    "Die in every screen of blue mountains",
    "Do a superjump in picture city",
    "Do allegro clip twice within 5 tries",
    "Enter Anguish Lagoon for the first time with 13 lives and 5 cages",
    "Enter Mr Sax fight while having exactly 99 tings",
    "Get 1 cage in every level except for CP/EAJ/MSS",
    "Get 2 lives from 1 Magician",
    "Get Both MN1 cages without using speed storage",
    "Get all 6 1ups in Bongo Hills",
    "Get all 6 1ups in Eat at Joe's",
    "Get all 7 1ups in Eraser Plains",
    "Get all 7 1ups in Hard rocks",
    "Get all 8 1ups in SMC",
    "Get all TSoF cages in reverse order",
    "Get all cages in EAJ in reverse order",
    "Get all cages in anguish lagoon in 1 go without leaving the level",
    "Get all tings and powerups in allegro screen 1 without taking a hit and without dying",
    "Get all tings in Allegro 1",
    "Get all tings, P orbs and 1 ups in CP without taking a hit",
    "Get the bongo hills dark screen cage without using helicopter, tethering and speedlocking",
    "Get the helicopter powerup while having exactly 4 cages in total",
    "Get the running powerup without having any caged collected",
    "Grimace 69 times",
    "Hit Mr. Stone 6 times while having atleast 3 dogs alive all the time.",
    "Hit all 6 cages in 3 different levels",
    "In MSS get from the photographer to the end sign while only using 1 punch",
    "Kill 50 living stones (small or tall) in 1 screen without getting hit",
    "Kill 6 different tall living stones in PPW without using punch and without taking damage in between",
    "Kill viking mama twice in a row with only taking 1 damage boost to do so",
    "Reach 30 Lives",
    "Reach the top SMC1 end sign without touching any sharpeners and without taking damage",
    "Spawn 30 enemies from the lips guy in MN without getting hit",
    "Successfully finish 6 magicians",
    "Take the skops photographer, then get all cages in reverse order without leaving the screen",
    "Touch the Extra end signs of HR1 and SMC1",
    "Zip 4 times",
    "Zip anywhere but the 3rd screen of Bongo Hills",
    "beat EP while only pressing run and helicopter once",
    "in PP, Get 7 Unique fist powerups without picking up P orbs or 1ups",
    "in PP2, Collect all 60 tings & reach the endsign without taking a hit",
    "in TSoF final screen, go from bottom to top without taking damage and without using helicopter"
];
