bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Beat Bongo hills without dying and without taking damage while getting all cages",
    "Beat Pencil Pentathlon without running nor helicoptering in screens 1 and 3",
    "Beat SMC1 while only being able to touch 1 pink sharpener",
    "Beat Space Mama while having exactly 23 cages",
    "Beat TSoF without punching any plum",
    "Beat allegro presto without having the ring grab powerup",
    "Beat allegro screen 1 while only collecting 6 tings or less",
    "Beat eat at joe’s without dying and without taking damage",
    "Beat moskito’s nest with 1 punch",
    "Beat mr sax with only 12 punches and without getting hit",
    "Beat the EP 3 Magician under 27 seconds",
    "Beat the PPW2 Magician under 8 seconds.",
    "Beat the final screen of PP without walking off of slippery platforms",
    "Clip 5 times in Mr Sax's Hullaballoo without pressing down",
    "Do a superjump",
    "Do a zip anywhere but the 3rd screen of bongo hills",
    "Do allegro clip twice within 5 tries",
    "Enter Anguish Lagoon for the first time with 13 lives and 5 cages",
    "Fall for 6 seconds without dying",
    "Finish first screen of mr. sax as small rayman",
    "Fully game over",
    "Get all cages in EAJ in reverse order",
    "Get all cages in anguish lagoon in 1 go without leaving the level.",
    "Get the bongo hills dark screen cage without using helicopter, tethering and speedlocking",
    "Get the helicopter powerup while having exactly 4 cages in total",
    "Grimace 150 times",
    "Hit Mr. Stone 6 times while having atleast 3 dogs alive all the time.",
    "In MSS get from the photographer to the end sign while only using 1 punch",
    "Kill 10 tall living stones without using punch",
    "Kill 50 living stones (small or tall) in 1 screen without getting hit",
    "Kill viking mama twice in a row with only taking 1 damage boost to do so",
    "Reach the top SMC1 end sign without touching any sharpeners",
    "Softlock the game",
    "Successfully finish 10 magicians",
    "Take the skops photographer, then get all cages in reverse order",
    "in TSoF final screen, go from bottom to top without taking damage and without using helicopter",
    "zip somewhere other than bongo 3"
];
