bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "AFK (#59)",
    "AFK in Water (#95)",
    "Alien Parasite (#89)",
    "Balance Animal Population",
    "Blue Orb (Water)",
    "Bomb Castle (#60)",
    "Bully Minion (#25)",
    "Chicken Altar (#80)",
    "Dark Stone Altar (#66)",
    "Dark Stone Lord (#93)",
    "Death to 99 End Door (#67)",
    "Destroy Pods (#31)",
    "Die to Anvil (#22)",
    "Die to Bomb (#28)",
    "Die to Canon (#17)",
    "Die to Dark Lord (#50)",
    "Die to Diagonal Spikes (#70)",
    "Die to Dragon (#14)",
    "Die to Mimic (#23)",
    "Die to Minon (#03)",
    "Die to Pit Minions (#15)",
    "Die to Spike (#21)",
    "Drop Kill Princess (#42)",
    "Drop down Fortress (#58)",
    "Drop down Fortress with Princess (#55)",
    "Drop down Waterfall (#08)",
    "Drop left of Mountain (#46)",
    "End of Desert (#88)",
    "End of Water (#97)",
    "Endless Drop (#10)",
    "Feed King (#99)",
    "Feed Mimic (#98)",
    "Feed Minion",
    "Flute Ending (#83)",
    "Fortnite (#77)",
    "Genocide Route?",
    "Go Fishing (#12)",
    "Green Orb (Earth)",
    "Harakiri (#47)",
    "Hide in Tressure (#39)",
    "Hug Cat (#11)",
    "Hug Chicken (#79)",
    "Hug Dark Lord (#73)",
    "Hug Dragon (#43)",
    "Hug Elder (#40)",
    "Hug Guard (#19)",
    "Hug King (#18)",
    "Hug Mimic",
    "Hug Minion (#13)",
    "Hug Princess (#57)",
    "Hug Rock (#54)",
    "Hug Shopkeeper (#37)",
    "Jump in Desert (#91)",
    "Kill 15 unique Minions",
    "Kill Chicken (#63)",
    "Kill Dark Lord (#69)",
    "Kill Devs + Crunch Hell (#87)",
    "Kill Dragon (#16)",
    "Kill Elder (#01)",
    "Kill Fairys (#85)",
    "Kill Guard (#04)",
    "Kill King (#05)",
    "Kill Mimic (#74)",
    "Kill Pit Minions (#49)",
    "Kill Princess (#64)",
    "Kill Rock (#32)",
    "Kill Shopkeeper (#09)",
    "Leap of Faith (#33)",
    "Left Lever (#38)",
    "Legendary Gardener",
    "Manga Tressure (#68)",
    "Mix Chicken DNA with Yours",
    "Mountain Tressure (#62)",
    "Origin of the Princess",
    "Overheal (#65)",
    "Pacifist (#61)",
    "Pirates (#96)",
    "Princess to Altar (#76)",
    "Princess to Anvil (#53)",
    "Princess to Barn (#86)",
    "Princess to Canon (#52)",
    "Princess to Castle (#51)",
    "Princess to Desert (#81)",
    "Princess to Dragon (#92)",
    "Princess to Home (#94)",
    "Princess to Shop (#78)",
    "Princess to Waterfall (#82)",
    "Red Button (#48)",
    "Red Orb (Fire)",
    "Right Lever (#44)",
    "Sacrifice 6 Items (#71)",
    "Sacrifice Princess (#72)",
    "Shield Dark Lord (#90)",
    "Shield Dragon (#29)",
    "Shopkeepers Real Product",
    "Sleep (#20)",
    "Sleep with Princess (#45)",
    "Stone trip (#02)",
    "Strawberry (#24)",
    "Swim in Lava (#06)",
    "Swim with Piranhas (#07)",
    "To much Weight (#26)",
    "Treassure Mimic (#75)",
    "Trinket + Shield Dragon (#41)",
    "Trinket Dragon (#36)",
    "True Piece of Art",
    "Under Elevator (#34)",
    "WMD Castle Canon (#56)",
    "WMD Fortress Canon (#84)",
    "WMD Shop Canon (#27)",
    "Waste Pipe (#35)",
    "X-Mas (#30)",
    "Yellow Orb (Air)"
];
