bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Buy 3x Cobra Bracelet",
    "Buy Kung Fu Dress",
    "Buy Walnut",
    "Talk to Elder after Chest",
    "Talk to Elman",
    "Talk to Cannon Wife",
    "Rescue Primm twice",
    "Get Magic Rope",
    "Get Minor Mallet",
    "Level Sword to 3 (at least on 1 char)",
    "Level Spear to 2 (at least on 1 char)",
    "Level Gloves to 2 (at least on 1 char)",
    "Level Javelin to 2 (at least on 1 char)",
    "Level Boomerang to 2 (at least on 1 char)",
    "Level Bow to 2 (at least on 1 char)",
    "Level Whip to 2 (at least on 1 char)",
    "Level Axe to 2 (at least on 1 char)",
    "Level Undine to 2 (at least on 1 char)",
    "Level Gnome to 2 (at least on 1 char)",
    "Kill Mantis Ant without dying",
    "Kill Tropikallo without killing the Vine",
    "Kill Spikey Tiger without using range Weapons",
    "Kill Fire Gigas without Magic",
    "Kill Middle Eye of Wall Face last",
    "Kill Kilroy while at least two Chars are Moogle",
    "Kill Jabberwocky without Magic",
    "Never Kill Rabite, Lullabud, Mushboom and Buzz Bee",
    "Never Kill Blat, Kid Goblin and Green Drop",
    "Never Kill ChobinHood, Eye Spy, Polter Chair and Werewolf",
    "Never Kill Iffish and Water Bandit",
    "Never Kill Ma Goblin, Goblin and Chess Knight",
    "Never Kill Zombie, Tomato Man, Evil Sword and Chess Knight"
];
