bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Get Magic Rope, Minor Mallet and Moogle Belt",
    "Get Griffin Helm",
    "Get Faerie Crown",
    "Get Faerie's Ring",
    "Get Faerie Cloak",
    "Get Power Suit",
    "Get Cockatrice Cap",
    "Get Amulet Helm",
    "Get Guardain Ring",
    "Get Ninja Gloves",
    "Get Dragon Ring",
    "Get Watcher Ring",
    "Get Imp's Ring",
    "Get Amulet Ring",
    "Get Vampire Cape",
    "Level Sword to 8 (at least on 1 char)",
    "Level Spear to 8 (at least on 1 char)",
    "Level Gloves to 7 (at least on 1 char)",
    "Level Javelin to 8 (at least on 1 char)",
    "Level Boomerang to 8 (at least on 1 char)",
    "Level Bow to 8 (at least on 1 char)",
    "Level Whip to 8 (at least on 1 char)",
    "Level Axe to 7 (at least on 1 char)",
    "Level Undine to 7 (at least on 1 char)",
    "Level Gnome to 7 (at least on 1 char)",
    "Level Sylphid to 7 (at least on 1 char)",
    "Level Salamando to 7 (at least on 1 char)",
    "Level Lumina to 7",
    "Level Shade to 7",
    "Level Luna to 7 (at least on 1 char)",
    "Level Dryad to 7 (at least on 1 char)",
    "Kill 15 Bossenemies without Magic",
    "Kill 25 Bossenemies without Magic",
    "Kill 10 Bossenemies without Weapons",
    "Never Kill Normal Enemies until you reach the Upper Lands",
    "Never Kill Normal Enemies in the Upper Lands until you reach Desert/Ice Country (except the 3 Pebblers)",
    "Never Kill Normal Enemies in the Desert and the Fire Palace",
    "Never Kill Normal Enemies in the Ice Country and the Ice Palast",
    "Never Kill Normal Enemies in the whole Empire (South-, North- and Goldcity)",
    "Never Kill Normal Enemies in the Lofty Mountains, the Palace of Darkness and the true Courage",
    "Never Kill Normal Enemies in Great Palace and Undercity"
];
