bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Erhalte Magisches Seil, Schrumpfhammer und Moogle Gürtel",
    "Erhalte Greifenhelm",
    "Erhalte Elfenkrone",
    "Erhalte Elfenarmband",
    "Erhalte Elfenweste",
    "Erhalte Götterrobe",
    "Erhalte Echsenkappe",
    "Erhalte Platinhelm",
    "Erhalte Saturnring",
    "Erhalte Federhandschuh",
    "Erhalte Drachenring",
    "Erhalte Zyklopenring",
    "Erhalte Zauberring",
    "Erhalte Fetischring",
    "Erhalte Drachenmantel",
    "Level Schwert auf 8 (mindestens auf einem Char)",
    "Level Lanze auf 8 (mindestens auf einem Char)",
    "Level Klaue auf 7 (mindestens auf einem Char)",
    "Level Speer auf 8 (mindestens auf einem Char)",
    "Level Bumerang auf 8 (mindestens auf einem Char)",
    "Level Bogen auf 8 (mindestens auf einem Char)",
    "Level Peitsche auf 8 (mindestens auf einem Char)",
    "Level Axt auf 7 (mindestens auf einem Char)",
    "Level Frosta auf 7 (mindestens auf einem Char)",
    "Level Rocky auf 7 (mindestens auf einem Char)",
    "Level Elektra auf 7 (mindestens auf einem Char)",
    "Level Vesuvio auf 7 (mindestens auf einem Char)",
    "Level Laterna auf 7",
    "Level Nacturn auf 7",
    "Level Lunatic auf 7 (mindestens auf einem Char)",
    "Level Harzinger auf 7 (mindestens auf einem Char)",
    "Töte 15 Bosse ohne Magie",
    "Töte 25 Bosse ohne Magie",
    "Töte 10 Bosse ohne Waffen",
    "Töte keine Normale Gegner bis du die Hochlande erreicht hast",
    "Töte keine Normale Gegner in den Hochlanden bis du die Wüste oder die Weihnachts- inssel erreicht hast",
    "Töte keine Normale Gegner in der Wüste und im Feuertempel",
    "Töte keine Normale Gegner in auf der Weihnachts- insel und im Eistempel",
    "Töte keine Normale Gegner im Imperium (Süd-, Nord-, und Goldstadt)",
    "Töte keine Normale Gegner auf dem Schicksals- berg, dem Tempel der Dunkelheit und der Mutprobe",
    "Töte keine Normale Gegner auf der kompletten Dracheninsel"
];
