bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Kaufe 3x Schlangen- armreif",
    "Kaufe Ninja Qipao",
    "Kaufe Walnuss",
    "Sprich mit dem Ältesten nachdem du die Kiste geöffnet hast",
    "Sprich mit Ronald",
    "Sprich mit der Frau der Canonis",
    "Rette Prim zweimal",
    "Erhalte Wundertau",
    "Erhalte Schrumpf- hammer",
    "Level Schwert auf 3 (mindestens auf einem Char)",
    "Level Lanze auf 2 (mindestens auf einem Char)",
    "Level Kalue auf 2 (mindestens auf einem Char)",
    "Level Speer auf 2 (mindestens auf einem Char)",
    "Level Bumerang auf 2 (mindestens auf einem Char)",
    "Level Bogen auf 2 (mindestens auf einem Char)",
    "Level Peitsche auf 2 (mindestens auf einem Char)",
    "Level Axt auf 2 (mindestens auf einem Char)",
    "Level Frosta auf 2 (mindestens auf einem Char)",
    "Level Rocky auf 2 (mindestens auf einem Char)",
    "Töte Sichelanbeter ohne zu sterben",
    "Töte Tropikallo ohne die Ranke zu zerstören",
    "Töte Schmusekater ohne Fernkampf- waffen",
    "Töte Feuermutant ohne Magie",
    "Töte Das mittlere Auge der Fratzenwand zuletzt",
    "Töte Thrillboy während mindestens 2 Chars gezappelt sind",
    "Töte Jabberwocky ohne Magie",
    "Töte keine Pogopuschel, Traumtulpe, Pilzkopf und Dornenwespe",
    "Töte keine Floddermaus, Murmelgoblin und Bioschleim",
    "Töte keine Bogenratte, Höllenspion, Zappelhocker und Wolfbestie",
    "Töte keine Rotzpiranha und Poseidonkröte",
    "Töte keine Ratzgoblin, Dösergoblin und Schachmeister",
    "Töte keine Fleischfetzer, Tomatenmann, Teufelsklinge und Schachmeister"
];
