// use ladx generator to keep endings separate
bingoGenerator = require("./generators/generator_bases/ladx_generator.js");

var bingoList = [
    {"name": "10 Memories"},
    {"name": "10 Prayer Beads"},
    {"name": "10 Sculptor's Idols"},
    {"name": "10 Skill Points at Once"},
    {"name": "10 Treasure Carp Scales"},
    {"name": "10000 Sen"},
    {"name": "15 Prayer Beads"},
    {"name": "15 Sculptor's Idols"},
    {"name": "15 Skill Points at Once"},
    {"name": "15 Treasure Carp Scales"},
    {"name": "20 Prayer Beads"},
    {"name": "20 Sculptor's Idols"},
    {"name": "20 Skill Points at Once"},
    {"name": "25 Prayer Beads"},
    {"name": "25 Sculptor's Idols"},
    {"name": "3 Gourd Seeds"},
    {"name": "30 Prayer Beads"},
    {"name": "5 Gourd Seeds"},
    {"name": "5 Memories"},
    {"name": "5 Treasure Carp Scales"},
    {"name": "5000 Sen"},
    {"name": "7 Gourd Seeds"},
    {"name": "7 Memories"},
    {"name": "8000 Sen"},
    {"name": "Defeat 1 Ashina Elite"},
    {"name": "Defeat 1 Centipede"},
    {"name": "Defeat 1 Chained Ogre"},
    {"name": "Defeat 1 Drunkard"},
    {"name": "Defeat 1 General"},
    {"name": "Defeat 1 Headless"},
    {"name": "Defeat 1 Lone Shadow"},
    {"name": "Defeat 1 Seven Spears"},
    {"name": "Defeat 1 Shichimen Warrior"},
    {"name": "Defeat 1 Snake Eyes"},
    {"name": "Defeat 2 Ashina Elites"},
    {"name": "Defeat 2 Bulls"},
    {"name": "Defeat 2 Centipedes"},
    {"name": "Defeat 2 Chained Ogres"},
    {"name": "Defeat 2 Drunkards"},
    {"name": "Defeat 2 Generals"},
    {"name": "Defeat 2 Headless"},
    {"name": "Defeat 2 Lone Shadows"},
    {"name": "Defeat 2 Seven Spears"},
    {"name": "Defeat 2 Shichimen Warriors"},
    {"name": "Defeat 2 Snake Eyes"},
    {"name": "Defeat 3 Drunkards"},
    {"name": "Defeat 3 Generals"},
    {"name": "Defeat 3 Lone Shadows"},
    {"name": "Defeat 4 Drunkards"},
    {"name": "Defeat Armored Warrior"},
    {"name": "Defeat Blazing Bull"},
    {"name": "Defeat Corrupted Monk (Fake)"},
    {"name": "Defeat Demon of Hatred"},
    {"name": "Defeat Divine Dragon"},
    {"name": "Defeat Genichiro (Ashina Castle)"},
    {"name": "Defeat Genichiro (Tutorial)"},
    {"name": "Defeat Great Shinobi Owl"},
    {"name": "Defeat Guardian Ape"},
    {"name": "Defeat Gyoubu"},
    {"name": "Defeat Headless Ape"},
    {"name": "Defeat Isshin (Ashina or Saint)"},
    {"name": "Defeat Lady Butterfly"},
    {"name": "Defeat Mist Noble"},
    {"name": "Defeat O'Rin"},
    {"name": "Defeat Okami Leader"},
    {"name": "Defeat Owl (Father)"},
    {"name": "Defeat Sakura Bull"},
    {"name": "Defeat Screen Monkeys"},
    {"name": "Defeat Shinobi Hunter"},
    {"name": "Defeat True Corrupted Monk"},
    {"name": "End with no Active Dragonrot"},
    {"name": "End with no Health Upgrades"},
    {"name": "Immortal Severance Ending", "group": "ending"},
    {"name": "Kill the Great Colored Carp"},
    {"name": "Kill the Great Serpent"},
    {"name": "Obtain 3 Prosthetic Tools"},
    {"name": "Obtain 5 Prosthetic Tools"},
    {"name": "Obtain 7 Prosthetic Tools"},
    {"name": "Obtain Ashina Skill Book"},
    {"name": "Obtain Divine Abduction"},
    {"name": "Obtain Dried Serpent Viscera"},
    {"name": "Obtain Finger Whistle"},
    {"name": "Obtain Flame Vent"},
    {"name": "Obtain Loaded Axe"},
    {"name": "Obtain Loaded Shuriken"},
    {"name": "Obtain Loaded Spear"},
    {"name": "Obtain Loaded Umbrella"},
    {"name": "Obtain Mist Raven"},
    {"name": "Obtain Mushin Skill Book"},
    {"name": "Obtain Prosthetic Skill Book"},
    {"name": "Obtain Sabimaru"},
    {"name": "Obtain Senpou Skill Book"},
    {"name": "Obtain Shinobi Firecracker"},
    {"name": "Obtain Shinobi Skill Book"},
    {"name": "Purification Ending", "group": "ending"},
    {"name": "Shura Ending", "group": "ending"},
    {"name": "Unlock Ashina Cross (Ashina Combat Art)"},
    {"name": "Unlock High Monk (Senpou Combat Art)"},
    {"name": "Unlock Living Force (Prosthetic Combat Art)"},
    {"name": "Unlock Shadowrush (Shinobi Combat Art)"}
];
