bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Admire a krill",
    "Behold Prairie Peaks' largest crystal",
    "Break through the Valley ice rink",
    "Build a bridge",
    "Catch a butterfly",
    "Change your back item in Aviary",
    "Change your cape at Prairie social space",
    "Change your hair in Valley Coliseum",
    "Change your mask at Wasteland social space",
    "Change your pants at Eden social space",
    "Collect wax from a clam",
    "Complete a Prophecy Trial",
    "Complete a Valley race",
    "Confetti emote beside a candle cake",
    "Create a shared space at a shrine",
    "Dance emote in the rain",
    "Drop a crab in the polluted geyser",
    "Faint emote in polluted water",
    "Fly through a Wind Path island tunnel",
    "Fly through an Assembly hoop",
    "Get launched by an updraft",
    "Get spotted by a krill",
    "Go fishing in the Village of Dreams",
    "Go for a swim in the Wind Paths",
    "Go swimming at Forgotten Ark",
    "Go to jail in the Repository of Refuge",
    "Handstand emote on granny's table",
    "Have a seat in the Aviary cafe",
    "Have your light go out",
    "Hide and Seek emote in Forest Brook",
    "High-five a seasonal guide",
    "Hop down the hole in Bird's Nest",
    "Hug a seasonal guide",
    "Jump on a bed",
    "Land on a jellyfish",
    "Leave a message at any Trial's shrine",
    "Leave a message candle at a shrine",
    "Light a constellation barrier",
    "Light a white candle",
    "Light the Hermit's lamp",
    "Listen to a bell ring",
    "Look Around emote in Starlight Desert",
    "Make flowers bloom",
    "Meditate at a temple",
    "Meditate in the collab hub",
    "Pass through an area without using wing flaps",
    "Pass through the Crescent Lake Tunnel",
    "Pass under a bridge",
    "Perform a fancy dive",
    "Perform a seasonal spirit's emote beside them",
    "Pick up a crab",
    "Play on the swings at the Treehouse",
    "Recharge on a cloud",
    "Record a shared memory at a shrine",
    "Relax on beach chairs in Sanctuary Islands",
    "Relive Confident Sightseer",
    "Relive Fainting Warrior",
    "Relive Pointing Candlemaker",
    "Relive Polite Scholar",
    "Relive Shivering Trailblazer",
    "Relive Waving Bellmaker",
    "Relive a 'Call' spirit",
    "Relive a 'Stance' spirit",
    "Relive a Belonging spirit",
    "Relive a Enchantment spirit",
    "Relive a Passage spirit",
    "Relive a Rhythm spirit",
    "Relive a Sanctuary spirit",
    "Relive a spirit with a blue cape",
    "Relive a spirit with a placeable prop",
    "Relive a spirit with an animal mask",
    "Relive a spirit with an instrument",
    "Relive an Abyss spirit",
    "Roast a crab over a fire",
    "Set a scene at the Performance stage",
    "Sit at a bonfire",
    "Sit on a throne",
    "Skip an elder cutscene",
    "Slide on some ice",
    "Spot a nightbird in Prairie Peaks",
    "Spot a sky whale",
    "Stand on the Prophecy totem",
    "Stand on top of a ladder",
    "Take a boat ride into another area",
    "Take a lap of the Valley temple maze",
    "Take a picture of a manatee",
    "Take a picture of a manta",
    "Take a ride on a manta",
    "Take an elevator ride",
    "Talk to an Aviary shopkeeper",
    "Tiptoe with the Teabrewer",
    "Touch Aviary's tallest peak",
    "Touch grass in Vault",
    "Try out an instrument in Harmony Hall",
    "Two map shrines in Forest",
    "Two map shrines in Isle",
    "Two map shrines in Prairie",
    "Two map shrines in Valley",
    "Two map shrines in Vault",
    "Two map shrines in Wasteland",
    "Un-pot butterflies",
    "Use the return shrine twice",
    "Visit any two winged light locations",
    "Visit the Ascetic Monk's secret pool",
    "Visit the smiling candles in Prairie Temple",
    "Wave emote in Valley Coliseum",
    "Witness an eclipse in Isle"
];
