bingoGenerator = require("./generators/generator_bases/srl_generator_v8.js");

var bingoList = [];
bingoList[1] = [
    {name: "City Escape M2", types: ["1"]},
    {name: "Speedshoes twice in any level and finish", types: ["1"]},
    {name: "Magnetic Shield twice in any level and finish", types: ["1"]},
    {name: "2 Chao Boxes in City Escape and finish", types: ["1"]},
    {name: "5 hidden animals in City Escape and finish", types: ["1"]},
    {name: "Rename a Chao after a person you're racing", types: ["1"]},
    {name: "Complete City Escape M1 with a Magnetic Shield", types: ["1"]},
    {name: "Iron Gate M2", types: ["1"]},
    {name: "Complete Iron Gate M1 with 100+ Rings", types: ["1"]},
    {name: "2 Chao Boxes in Iron Gate and finish", types: ["1"]},
    {name: "5 hidden animals in Iron Gate and finish", types: ["1"]},
    {name: "Wild Canyon M1 Hintless", types: ["1"]}
];
bingoList[2] = [
    {name: "Dry Lagoon M1 Hintless", types: ["2"]},
    {name: "5 Emblems (Team Combined)", types: ["2"]},
    {name: "City Escape M3", types: ["2"]},
    {name: "Wild Canyon M2", types: ["2"]},
    {name: "Complete Wild Canyon M1 with 100+ Rings", types: ["2"]},
    {name: "2 Chao Boxes in Wild Canyon and finish", types: ["2"]},
    {name: "Unlock Chao Garden for all Hero Story characters", types: ["2"]},
    {name: "5 hidden animals in Wild Canyon and finish", types: ["2"]}
];
bingoList[3] = [
    {name: "3 Mech Missions A-Rank (Team Combined)", types: ["3"]},
    {name: "Wild Canyon M3", types: ["3"]},
    {name: "Wild Canyon M3 B-Rank", types: ["3"]},
    {name: "Dry Lagoon M2", types: ["3"]},
    {name: "Complete Dry Lagoon M1 with 100+ Rings", types: ["3"]},
    {name: "2 Chao Boxes in Dry Lagoon and finish", types: ["3"]},
    {name: "5 hidden animals in Dry Lagoon and finish", types: ["3"]},
    {name: "Wild Canyon M4", types: ["3"]},
    {name: "Dry Lagoon M3", types: ["3"]},
    {name: "Dry Lagoon M3 B-Rank", types: ["3"]},
    {name: "City Escape M4", types: ["3"]},
    {name: "Wild Canyon M5", types: ["3"]},
    {name: "Defeat both Big Foot and Hot Shot", types: ["3"]},
    {name: "Dry Lagoon M4", types: ["3"]}
];
bingoList[4] = [
    {name: "Wild Canyon M4 A-Rank", types: ["4"]},
    {name: "City Escape M4 A-Rank", types: ["4"]},
    {name: "Wild Canyon M5 A-Rank", types: ["4"]},
    {name: "Dry Lagoon M4 A-Rank", types: ["4"]},
    {name: "Prison Lane M2", types: ["4"]},
    {name: "Complete Prison Lane M1 with 100+ Rings", types: ["4"]},
    {name: "2 Chao Boxes in Prison Lane and finish", types: ["4"]},
    {name: "5 hidden animals in Prison Lane and finish", types: ["4"]},
    {name: "Destroy the Gold Beetle in 3 Hero Story stages", types: ["4"]},
    {name: "Complete Prison Lane M1 with a Green Shield", types: ["4"]},
    {name: "Sand Ocean M2", types: ["4"]},
    {name: "Complete Sand Ocean M1 with 100+ Rings", types: ["4"]},
    {name: "2 Chao Boxes in Sand Ocean and finish", types: ["4"]},
    {name: "5 hidden animals in Sand Ocean and finish", types: ["4"]},
    {name: "Beginner Chao Karate Emblem (with a new Chao)", types: ["4"]},
    {name: "City Escape M5", types: ["4"]},
    {name: "Dry Lagoon M5", types: ["4"]},
    {name: "Shadow's Flame Ring", types: ["4"]},
    {name: "Metal Harbor M2", types: ["4"]},
    {name: "2 Chao Boxes in Metal Harbor and finish", types: ["4"]},
    {name: "5 hidden animals in Metal Harbor and finish", types: ["4"]},
    {name: "Pacifist Metal Harbor M1", types: ["4"]},
    {name: "Unlock Chao Garden for all Dark Story characters", types: ["4"]},
    {name: "Metal Harbor M3", types: ["4"]},
    {name: "Metal Harbor M3 B-Rank", types: ["4"]}
];
bingoList[5] = [
    {name: "Wild Canyon All Missions A-Rank", types: ["5"]},
    {name: "City Escape M5 A-Rank", types: ["5"]},
    {name: "Dry Lagoon M5 A-Rank", types: ["5"]},
    {name: "Radical Highway M2", types: ["5"]},
    {name: "Complete Radical Highway M1 with 100+ Rings", types: ["5"]},
    {name: "2 Chao Boxes in Radical Highway and finish", types: ["5"]},
    {name: "5 hidden animals in Radical Highway and finish", types: ["5"]},
    {name: "Destroy the Gold Beetle in 3 Dark Story stages", types: ["5"]},
    {name: "Pacifist Radical Highway M1", types: ["5"]},
    {name: "Egg Quarters M1 Hintless", types: ["5"]},
    {name: "Metal Harbor M4", types: ["5"]},
    {name: "Radical Highway M3", types: ["5"]},
    {name: "Sonic's Ancient Light", types: ["5"]},
    {name: "Egg Quarters M2", types: ["5"]},
    {name: "Complete Egg Quarters M1 with 100+ Rings", types: ["5"]},
    {name: "2 Chao Boxes in Egg Quarters and finish", types: ["5"]},
    {name: "5 hidden animals in Egg Quarters and finish", types: ["5"]},
    {name: "Complete Egg Quarters M1 with a Magnetic Shield", types: ["5"]}
];
bingoList[6] = [
    {name: "City Escape All Missions A-Rank", types: ["6"]},
    {name: "Dry Lagoon All Missions A-Rank", types: ["6"]},
    {name: "Metal Harbor M4 A-Rank", types: ["6"]},
    {name: "Green Forest M2", types: ["6"]},
    {name: "Complete Green Forest M1 with 100+ Rings", types: ["6"]},
    {name: "2 Chao Boxes in Green Forest and finish", types: ["6"]},
    {name: "5 hidden animals in Green Forest and finish", types: ["6"]},
    {name: "Pacifist Green Forest M1", types: ["6"]},
    {name: "Complete Green Forest M1 with a Magnetic Shield", types: ["6"]},
    {name: "Metal Harbor M5", types: ["6"]},
    {name: "Egg Quarters M3", types: ["6"]},
    {name: "Pumpkin Hill M1 Hintless", types: ["6"]},
    {name: "Green Forest M3", types: ["6"]},
    {name: "Radical Highway M4", types: ["6"]},
    {name: "Pumpkin Hill M2", types: ["6"]},
    {name: "Complete Pumpkin Hill M1 with 100+ Rings", types: ["6"]},
    {name: "2 Chao Boxes in Pumpkin Hill and finish", types: ["6"]},
    {name: "5 hidden animals in Pumpkin Hill and finish", types: ["6"]},
    {name: "Pumpkin Hill M3", types: ["6"]},
    {name: "Egg Quarters M4", types: ["6"]},
    {name: "Destroy the Gold Beetle in 5 different stages", types: ["6"]}
];
bingoList[7] = [
    {name: "Metal Harbor M5 A-Rank", types: ["7"]},
    {name: "Radical Highway M4 A-Rank", types: ["7"]},
    {name: "Egg Quarters M4 A-Rank", types: ["7"]},
    {name: "Lost Colony M2", types: ["7"]},
    {name: "Sand Ocean M3", types: ["7"]},
    {name: "Complete Lost Colony M1 with 100+ Rings", types: ["7"]},
    {name: "2 Chao Boxes in Lost Colony and finish", types: ["7"]},
    {name: "5 hidden animals in Lost Colony and finish", types: ["7"]},
    {name: "Radical Highway M5", types: ["7"]},
    {name: "Pumpkin Hill M4", types: ["7"]},
    {name: "Green Forest M4", types: ["7"]},
    {name: "Game Over during Mission Street M1", types: ["7"]},
    {name: "Iron Gate M3", types: ["7"]},
    {name: "Egg Quarters M5", types: ["7"]},
    {name: "Unlock Chao Garden for every character", types: ["7"]},
    {name: "Pumpkin Hill M5", types: ["7"]},
    {name: "Game Over during Tails 1", types: ["7"]},
    {name: "Weapons Bed M2", types: ["7"]},
    {name: "Complete Weapons Bed M1 with 100+ Rings", types: ["7"]},
    {name: "2 Chao Boxes in Weapons Bed and finish", types: ["7"]},
    {name: "5 hidden animals in Weapons Bed and finish", types: ["7"]},
    {name: "Pacifist Weapons Bed M1", types: ["7"]},
    {name: "Sand Ocean M4", types: ["7"]}
];
bingoList[8] = [
    {name: "Metal Harbor All Missions A-Rank", types: ["8"]},
    {name: "Radical Highway M5 A-Rank", types: ["8"]},
    {name: "Pumpkin Hill M4 A-Rank", types: ["8"]},
    {name: "Green Forest M4 A-Rank", types: ["8"]},
    {name: "Egg Quarters M5 A-Rank", types: ["8"]},
    {name: "Pumpkin Hill M5 A-Rank", types: ["8"]},
    {name: "Sand Ocean M4 A-Rank", types: ["8"]},
    {name: "Knuckles' Air Necklace", types: ["8"]},
    {name: "Aquatic Mine M1 Hintless", types: ["8"]},
    {name: "Rouge's Treasure Scope", types: ["8"]},
    {name: "Security Hall M1 Hintless", types: ["8"]},
    {name: "Mission Street M2", types: ["8"]},
    {name: "Iron Gate M4", types: ["8"]},
    {name: "Complete Mission Street M1 with 100+ Rings", types: ["8"]},
    {name: "2 Chao Boxes in Mission Street and finish", types: ["8"]},
    {name: "5 hidden animals in Mission Street and finish", types: ["8"]},
    {name: "Destroy the Gold Beetle in 6 Hero Story stages", types: ["8"]},
    {name: "Pacifist Mission Street M1", types: ["8"]},
    {name: "Lost Colony M3", types: ["8"]},
    {name: "Aquatic Mine M2", types: ["8"]},
    {name: "Weapons Bed M3", types: ["8"]},
    {name: "Dr Eggman's Laser Blaster", types: ["8"]},
    {name: "Complete Aquatic Mine M1 with 100+ Rings", types: ["8"]},
    {name: "2 Chao Boxes in Aquatic Mine and finish", types: ["8"]},
    {name: "5 hidden animals in Aquatic Mine and finish", types: ["8"]},
    {name: "Green Forest M5", types: ["8"]},
    {name: "Aquatic Mine M3", types: ["8"]},
    {name: "Game Over during Flying Dog", types: ["8"]},
    {name: "Security Hall M2", types: ["8"]},
    {name: "Complete Security Hall M1 with 100+ Rings", types: ["8"]},
    {name: "2 Chao Boxes in Security Hall and finish", types: ["8"]},
    {name: "5 hidden animals in Security Hall and finish", types: ["8"]},
    {name: "Destroy the Gold Beetle in 6 Dark Story stages", types: ["8"]},
    {name: "Complete Security Hall M1 with a Magnetic Shield", types: ["8"]}
];
bingoList[9] = [
    {name: "Radical Highway All Missions A-Rank", types: ["9"]},
    {name: "Egg Quarters All Missions A-Rank", types: ["9"]},
    {name: "Pumpkin Hill All Missions A-Rank", types: ["9"]},
    {name: "Iron Gate M4 A-Rank", types: ["9"]},
    {name: "Green Forest M5 A-Rank", types: ["9"]},
    {name: "Iron Gate M5", types: ["9"]},
    {name: "Sand Ocean M5", types: ["9"]},
    {name: "Game Over during Route 101 M1", types: ["9"]},
    {name: "Aquatic Mine M4", types: ["9"]},
    {name: "Security Hall M3", types: ["9"]},
    {name: "Security Hall M3 B-Rank", types: ["9"]},
    {name: "Weapons Bed M4", types: ["9"]},
    {name: "Route 101 M2", types: ["9"]},
    {name: "Defeat both Tails 1 and Dr Eggman 1", types: ["9"]},
    {name: "Security Hall M4", types: ["9"]},
    {name: "Lost Colony M4", types: ["9"]},
    {name: "White Jungle M2", types: ["9"]},
    {name: "Weapons Bed M5", types: ["9"]},
    {name: "Complete White Jungle M1 with 100+ Rings", types: ["9"]},
    {name: "2 Chao Boxes in White Jungle and finish", types: ["9"]},
    {name: "5 hidden animals in White Jungle and finish", types: ["9"]},
    {name: "Game Over during Sonic 1", types: ["9"]},
    {name: "Pacifist White Jungle M1", types: ["9"]}
];
bingoList[10] = [
    {name: "Green Forest All Missions A-Rank", types: ["10"]},
    {name: "Iron Gate M5 A-Rank", types: ["10"]},
    {name: "Sand Ocean M5 A-Rank", types: ["10"]},
    {name: "Aquatic Mine M4 A-Rank", types: ["10"]},
    {name: "Weapons Bed M4 A-Rank", types: ["10"]},
    {name: "Security Hall M4 A-Rank", types: ["10"]},
    {name: "Lost Colony M4 A-Rank", types: ["10"]},
    {name: "Weapons Bed M5 A-Rank", types: ["10"]},
    {name: "Beginner Kart Racing Emblem", types: ["10"]},
    {name: "Destroy the Gold Beetle in 3 Hero Story stages (M5 only)", types: ["10"]},
    {name: "Security Hall M5", types: ["10"]},
    {name: "Route 101 M3", types: ["10"]},
    {name: "Hidden Base M2", types: ["10"]},
    {name: "Complete Hidden Base M1 with 100+ Rings", types: ["10"]},
    {name: "2 Chao Boxes in Hidden Base and finish", types: ["10"]},
    {name: "5 hidden animals in Hidden Base and finish", types: ["10"]},
    {name: "White Jungle M3", types: ["10"]},
    {name: "Game Over during Pyramid Cave M1", types: ["10"]}
];
bingoList[11] = [
    {name: "Iron Gate All Missions A-Rank", types: ["11"]},
    {name: "Sand Ocean All Missions A-Rank", types: ["11"]},
    {name: "Weapons Bed All Missions A-Rank", types: ["11"]},
    {name: "Security Hall M5 A-Rank", types: ["11"]},
    {name: "Pyramid Cave M2", types: ["11"]},
    {name: "Lost Colony M5", types: ["11"]},
    {name: "Complete Pyramid Cave M1 with 100+ Rings", types: ["11"]},
    {name: "2 Chao Boxes in Pyramid Cave and finish", types: ["11"]},
    {name: "5 hidden animals in Pyramid Cave and finish", types: ["11"]},
    {name: "Game Over during Route 280 M1", types: ["11"]},
    {name: "Route 101 M4", types: ["11"]},
    {name: "Hidden Base M3", types: ["11"]},
    {name: "Death Chamber M1 Hintless", types: ["11"]},
    {name: "Route 280 M2", types: ["11"]},
    {name: "Pyramid Cave M3", types: ["11"]},
    {name: "White Jungle M4", types: ["11"]},
    {name: "Shadow's Ancient Light", types: ["11"]}
];
bingoList[12] = [
    {name: "Security Hall All Missions A-Rank", types: ["12"]},
    {name: "Lost Colony M5 A-Rank", types: ["12"]},
    {name: "Route 101 M4 A-Rank", types: ["12"]},
    {name: "White Jungle M4 A-Rank", types: ["12"]},
    {name: "Game Over during King Boom Boo", types: ["12"]},
    {name: "Death Chamber M2", types: ["12"]},
    {name: "Complete Death Chamber M1 with 100+ Rings", types: ["12"]},
    {name: "2 Chao Boxes in Death Chamber and finish", types: ["12"]},
    {name: "5 hidden animals in Death Chamber and finish", types: ["12"]},
    {name: "Hidden Base M4", types: ["12"]},
    {name: "Route 101 M5", types: ["12"]},
    {name: "Sky Rail M2", types: ["12"]},
    {name: "Complete Sky Rail M1 with 100+ Rings", types: ["12"]},
    {name: "2 Chao Boxes in Sky Rail and finish", types: ["12"]},
    {name: "5 hidden animals in Sky Rail and finish", types: ["12"]},
    {name: "Death Chamber M3", types: ["12"]},
    {name: "Pyramid Cave M4", types: ["12"]},
    {name: "Sky Rail M3", types: ["12"]},
    {name: "White Jungle M5", types: ["12"]},
    {name: "All Kart Racing Emblems", types: ["12"]},
    {name: "Mad Space M1 Hintless", types: ["12"]},
    {name: "Death Chamber M4", types: ["12"]},
    {name: "Route 280 M3", types: ["12"]}
];
bingoList[13] = [
    {name: "Lost Colony All Missions A-Rank", types: ["13"]},
    {name: "Hidden Base M4 A-Rank", types: ["13"]},
    {name: "Route 101 M5 A-Rank", types: ["13"]},
    {name: "Pyramid Cave M4 A-Rank", types: ["13"]},
    {name: "White Jungle M5 A-Rank", types: ["13"]},
    {name: "Death Chamber M4 A-Rank", types: ["13"]},
    {name: "Finish any mission with 25+ Lives (No Underflow)", types: ["13"]},
    {name: "Hidden Base M5", types: ["13"]},
    {name: "Mad Space M2", types: ["13"]},
    {name: "Complete Mad Space M1 with 100+ Rings", types: ["13"]},
    {name: "2 Chao Boxes in Mad Space and finish", types: ["13"]},
    {name: "5 hidden animals in Mad Space and finish", types: ["13"]},
    {name: "Sky Rail M4", types: ["13"]},
    {name: "Pyramid Cave M5", types: ["13"]},
    {name: "Death Chamber M5", types: ["13"]},
    {name: "Defeat both Shadow 1 and Sonic 1", types: ["13"]},
    {name: "Sky Rail M5", types: ["13"]},
    {name: "Destroy the Gold Beetle in 3 Dark Story stages (M5 only)", types: ["13"]},
    {name: "Mad Space M3", types: ["13"]},
    {name: "Route 280 M4", types: ["13"]}
];
bingoList[14] = [
    {name: "Route 101 All Missions A-Rank", types: ["14"]},
    {name: "White Jungle All Missions A-Rank", types: ["14"]},
    {name: "Hidden Base M5 A-Rank", types: ["14"]},
    {name: "Sky Rail M4 A-Rank", types: ["14"]},
    {name: "Pyramid Cave M5 A-Rank", types: ["14"]},
    {name: "Death Chamber M5 A-Rank", types: ["14"]},
    {name: "Sky Rail M5 A-Rank", types: ["14"]},
    {name: "Route 280 M4 A-Rank", types: ["14"]},
    {name: "Eternal Engine M2", types: ["14"]},
    {name: "Mad Space M4", types: ["14"]},
    {name: "Dr Eggman's Protective Armor", types: ["14"]},
    {name: "Complete Eternal Engine M1 with 100+ Rings", types: ["14"]},
    {name: "2 Chao Boxes in Eternal Engine and finish", types: ["14"]},
    {name: "5 hidden animals in Eternal Engine and finish", types: ["14"]},
    {name: "Meteor Herd M1 Hintless", types: ["14"]},
    {name: "Complete Eternal Engine M1 with a Green Shield", types: ["14"]},
    {name: "Knuckles' Sunglasses", types: ["14"]},
    {name: "Meteor Herd M2", types: ["14"]},
    {name: "Tails' Laser Blaster", types: ["14"]},
    {name: "Complete Meteor Herd M1 with 100+ Rings", types: ["14"]},
    {name: "2 Chao Boxes in Meteor Herd and finish", types: ["14"]},
    {name: "5 hidden animals in Meteor Herd and finish", types: ["14"]},
    {name: "Destroy the Gold Beetle in 10 different stages", types: ["14"]}
];
bingoList[15] = [
    {name: "Hidden Base All Missions A-Rank", types: ["15"]},
    {name: "Pyramid Cave All Missions A-Rank", types: ["15"]},
    {name: "Death Chamber All Missions A-Rank", types: ["15"]},
    {name: "Sky Rail All Missions A-Rank", types: ["15"]},
    {name: "Mad Space M4 A-Rank", types: ["15"]},
    {name: "Prison Lane M3", types: ["15"]},
    {name: "Mad Space M5", types: ["15"]},
    {name: "Meteor Herd M3", types: ["15"]},
    {name: "Route 280 M5", types: ["15"]},
    {name: "Mission Street M3", types: ["15"]},
    {name: "Eternal Engine M3", types: ["15"]},
    {name: "Aquatic Mine M5", types: ["15"]},
    {name: "Meteor Herd M4", types: ["15"]},
    {name: "Sonic's Flame Ring", types: ["15"]},
    {name: "Prison Lane M4", types: ["15"]},
    {name: "Meteor Herd M5", types: ["15"]}
];
bingoList[16] = [
    {name: "Mad Space M5 A-Rank", types: ["16"]},
    {name: "Route 280 M5 A-Rank", types: ["16"]},
    {name: "Aquatic Mine M5 A-Rank", types: ["16"]},
    {name: "Meteor Herd M4 A-Rank", types: ["16"]},
    {name: "Prison Lane M4 A-Rank", types: ["16"]},
    {name: "Meteor Herd M5 A-Rank", types: ["16"]},
    {name: "Cosmic Wall M2", types: ["16"]},
    {name: "Complete Cosmic Wall M1 with 100+ Rings", types: ["16"]},
    {name: "5 hidden animals in Cosmic Wall and finish", types: ["16"]},
    {name: "Crazy Gadget M2", types: ["16"]},
    {name: "Complete Crazy Gadget M1 with 100+ Rings", types: ["16"]},
    {name: "2 Chao Boxes in Crazy Gadget and finish", types: ["16"]},
    {name: "5 hidden animals in Crazy Gadget and finish", types: ["16"]},
    {name: "Complete Crazy Gadget M1 with a Green Shield", types: ["16"]},
    {name: "Mission Street M4", types: ["16"]},
    {name: "Cosmic Wall M3", types: ["16"]},
    {name: "Eternal Engine M4", types: ["16"]},
    {name: "Prison Lane M5", types: ["16"]},
    {name: "Sonic's Magic Gloves", types: ["16"]},
    {name: "Crazy Gadget M3", types: ["16"]},
    {name: "2500 Total Rings", types: ["16"]}
];
bingoList[17] = [
    {name: "Mad Space All Missions A-Rank", types: ["17"]},
    {name: "Route 280 All Missions A-Rank", types: ["17"]},
    {name: "Aquatic Mine All Missions A-Rank", types: ["17"]},
    {name: "Meteor Herd All Missions A-Rank", types: ["17"]},
    {name: "Mission Street M4 A-Rank", types: ["17"]},
    {name: "Eternal Engine M4 A-Rank", types: ["17"]},
    {name: "Prison Lane M5 A-Rank", types: ["17"]},
    {name: "Final Rush M2", types: ["17"]},
    {name: "Complete Final Rush M1 with 100+ Rings", types: ["17"]},
    {name: "2 Chao Boxes in Final Rush and finish", types: ["17"]},
    {name: "5 hidden animals in Final Rush and finish", types: ["17"]},
    {name: "All Hero Story Character's Upgrades", types: ["17"]},
    {name: "Complete Final Rush M1 with a Magnetic Shield", types: ["17"]},
    {name: "All Hero Story Character's Mystic Melody", types: ["14"]},
    {name: "All Dark Story Character's Mystic Melody", types: ["17"]},
    {name: "Mission Street M5", types: ["17"]},
    {name: "Crazy Gadget M4", types: ["17"]},
    {name: "Final Chase M2", types: ["17"]},
    {name: "Complete Final Chase M1 with 100+ Rings", types: ["17"]},
    {name: "2 Chao Boxes in Final Chase and finish", types: ["17"]},
    {name: "5 hidden animals in Final Chase and finish", types: ["17"]},
    {name: "All Dark Story Character's Upgrades", types: ["17"]},
    {name: "Eternal Engine M5", types: ["17"]},
    {name: "Final Rush M3", types: ["17"]}
];
bingoList[18] = [
    {name: "Prison Lane All Missions A-Rank", types: ["18"]},
    {name: "Mission Street M5 A-Rank", types: ["18"]},
    {name: "Crazy Gadget M4 A-Rank", types: ["18"]},
    {name: "Eternal Engine M5 A-Rank", types: ["18"]},
    {name: "Final Rush M3 A-Rank", types: ["18"]},
    {name: "Cosmic Wall M4", types: ["18"]},
    {name: "Final Rush M4", types: ["18"]},
    {name: "Crazy Gadget M5", types: ["18"]},
    {name: "Final Chase M3", types: ["18"]},
    {name: "Hero Story Emblem", types: ["18"]},
    {name: "Dark Story Emblem", types: ["18"]}
];
bingoList[19] = [
    {name: "Mission Street All Missions A-Rank", types: ["19"]},
    {name: "Eternal Engine All Missions A-Rank", types: ["19"]},
    {name: "Cosmic Wall M4 A-Rank", types: ["19"]},
    {name: "Crazy Gadget M5 A-Rank", types: ["19"]},
    {name: "Final Rush M4 A-Rank", types: ["19"]},
    {name: "Route 101 M1 & Route 280 M1", types: ["19"]},
    {name: "Final Rush M5", types: ["19"]},
    {name: "Final Chase M4", types: ["19"]},
    {name: "All Character's Mystic Melody (Team Combined)", types: ["19"]},
    {name: "Defeat both King Boom Boo and Flying Dog", types: ["19"]}
];
bingoList[20] = [
    {name: "Crazy Gadget All Missions A-Rank", types: ["20"]},
    {name: "Final Rush M5 A-Rank", types: ["20"]},
    {name: "Final Chase M4 A-Rank", types: ["20"]},
    {name: "Cosmic Wall M5", types: ["20"]},
    {name: "Final Chase M5", types: ["20"]}
];
bingoList[21] = [
    {name: "Final Rush All Missions A-Rank", types: ["21"]},
    {name: "Cosmic Wall M5 A-Rank", types: ["21"]},
    {name: "8000 Total Rings (Team Combined)", types: ["21"]},
    {name: "Final Chase M5 A-Rank", types: ["21"]}
];
bingoList[22] = [
    {name: "Cosmic Wall All Missions A-Rank", types: ["22"]},
    {name: "Hero Story Boss Rush Emblem", types: ["22"]},
    {name: "Dark Story Boss Rush Emblem", types: ["22"]},
    {name: "Final Chase All Missions A-Rank", types: ["22"]}
];
bingoList[23] = [
    {name: "Knuckles' Alternative Kart", types: ["23"]},
    {name: "Rouge's Alternative Kart", types: ["23"]},
    {name: "Defeat both Knuckles and Rouge", types: ["23"]},
    {name: "Defeat Egg Golem as both Sonic and Dr Eggman", types: ["23"]}
];
bingoList[24] = [
    {name: "Shadow's Alternative Kart", types: ["24"]},
    {name: "Tails' Alternative Kart", types: ["24"]},
    {name: "Defeat both Tails 2 and Dr Eggman 2", types: ["24"]},
    {name: "Sonic's Alternative Kart", types: ["24"]},
    {name: "Eggman's Alternative Kart", types: ["24"]}
];
bingoList[25] = [
    {name: "120 Emblems (Team Combined)", types: ["25"]}
];
