bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList =
[
    "Beat Beta MkII With 0 Rings",
    "Beat Chaos 0 Without Rings",
    "Beat Chaos 2 in Under 2 Minutes",
    "Beat Chaos 4 With 4 Rings",
    "Beat Chaos 6 Without Using Light Speed Attack",
    "Beat Egg Hornet With Exactly 5 Rings",
    "Beat Egg Viper Without Getting Hit",
    "Beat Egg Walker in Under 2:30",
    "Beat Gamma with Sonic and Sonic with Gamma",
    "Beat Knuckles with Sonic and Sonic with Knuckles",
    "Beat Lost World's Mirror Room Without Mirrors",
    "Beat Perfect Chaos",
    "Beat Tails' Sky Deck Without Flying",
    "Beat Tails' Speed Highway Without Flying",
    "Beat Tails' Windy Valley Without Flying",
    "Beat Twinkle Circuit With Car Number 1",
    "Beat Zero With 0 Rings",
    "Beat a Big Stage with 25 Rings",
    "Beat a Gamma Stage Without Destroying Anything",
    "Complete Amy's Twinkle Park Without Using the Hammer",
    "Complete Emerald Coast With 50 Rings",
    "Complete Red Mountain With 0 Rings",
    "Complete Speed Highway in Under 3 Minutes",
    "Destroy the Tails Doll in Sonic's Final Egg",
    "Get 10 Emblems",
    "Get 20 Emblems",
    "Get 25 Lives",
    "Get 30 Emblems",
    "Get 700 Rings in Casinopolis",
    "Get All 4 of Big's Lure Upgrades",
    "Get All Upgrades for Big and Gamma",
    "Get All Upgrades for Sonic and Knuckles",
    "Get All Upgrades for Tails and Amy",
    "Get All of Big's Upgrades",
    "Get All of Sonic's Upgrades",
    "Get Amy's Long Hammer",
    "Get Amy's Warrior Feather",
    "Get Big's Life Belt",
    "Get Big's Power Rod",
    "Get Both of Amy's Upgrades",
    "Get Both of Gamma's Upgrades",
    "Get Both of Knuckles' Upgrades",
    "Get Both of Tails' Upgrades",
    "Get Every Upgrade for Every Character",
    "Get Gamma's Jet Booster",
    "Get Gamma's Laser Blaster",
    "Get Knuckles' Fighting Gloves",
    "Get Knuckles' Shovel Claw",
    "Get Sonic's Ancient Light",
    "Get Sonic's Crystal Ring",
    "Get Sonic's Light Speed Shoes",
    "Get Tails' Jet Anklet",
    "Get Tails' Rhythm Badge",
    "Get a Score of 5000 in Hedgehog Hammer",
    "Jump Off of 3 Ramps in Ice Cap"
];
