bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Radiant Emerald in Balloon Mode with Amy",
    "Radiant Emerald in Balloon Mode with Egg Robo",
    "Radiant Emerald in Balloon Mode with Eggman",
    "Radiant Emerald in Balloon Mode with Knuckles",
    "Radiant Emerald in Balloon Mode with Metal Knuckles",
    "Radiant Emerald in Balloon Mode with Metal Sonic",
    "Radiant Emerald in Balloon Mode with Sonic",
    "Radiant Emerald in Balloon Mode with Super Sonic",
    "Radiant Emerald in Balloon Mode with Tails",
    "Radiant Emerald in Balloon Mode with Tails Doll",
    "Radiant Emerald in Grand Prix with Amy",
    "Radiant Emerald in Grand Prix with Egg Robo",
    "Radiant Emerald in Grand Prix with Eggman",
    "Radiant Emerald in Grand Prix with Knuckles",
    "Radiant Emerald in Grand Prix with Metal Knuckles",
    "Radiant Emerald in Grand Prix with Metal Sonic",
    "Radiant Emerald in Grand Prix with Sonic",
    "Radiant Emerald in Grand Prix with Super Sonic",
    "Radiant Emerald in Grand Prix with Tails",
    "Radiant Emerald in Grand Prix with Tails Doll",
    "Radiant Emerald in Tag Mode with Amy",
    "Radiant Emerald in Tag Mode with Egg Robo",
    "Radiant Emerald in Tag Mode with Eggman",
    "Radiant Emerald in Tag Mode with Knuckles",
    "Radiant Emerald in Tag Mode with Metal Knuckles",
    "Radiant Emerald in Tag Mode with Metal Sonic",
    "Radiant Emerald in Tag Mode with Sonic",
    "Radiant Emerald in Tag Mode with Super Sonic",
    "Radiant Emerald in Tag Mode with Tails",
    "Radiant Emerald in Tag Mode with Tails Doll",
    "Radiant Emerald in Time Trial (Normal) with Amy",
    "Radiant Emerald in Time Trial (Normal) with Egg Robo",
    "Radiant Emerald in Time Trial (Normal) with Eggman",
    "Radiant Emerald in Time Trial (Normal) with Knuckles",
    "Radiant Emerald in Time Trial (Normal) with Metal Knuckles",
    "Radiant Emerald in Time Trial (Normal) with Metal Sonic",
    "Radiant Emerald in Time Trial (Normal) with Sonic",
    "Radiant Emerald in Time Trial (Normal) with Super Sonic",
    "Radiant Emerald in Time Trial (Normal) with Tails",
    "Radiant Emerald in Time Trial (Normal) with Tails Doll",
    "Radiant Emerald in Time Trial (Reverse) with Amy",
    "Radiant Emerald in Time Trial (Reverse) with Egg Robo",
    "Radiant Emerald in Time Trial (Reverse) with Eggman",
    "Radiant Emerald in Time Trial (Reverse) with Knuckles",
    "Radiant Emerald in Time Trial (Reverse) with Metal Knuckles",
    "Radiant Emerald in Time Trial (Reverse) with Metal Sonic",
    "Radiant Emerald in Time Trial (Reverse) with Sonic",
    "Radiant Emerald in Time Trial (Reverse) with Super Sonic",
    "Radiant Emerald in Time Trial (Reverse) with Tails",
    "Radiant Emerald in Time Trial (Reverse) with Tails Doll",
    "Radical City in Balloon Mode with Amy",
    "Radical City in Balloon Mode with Egg Robo",
    "Radical City in Balloon Mode with Eggman",
    "Radical City in Balloon Mode with Knuckles",
    "Radical City in Balloon Mode with Metal Knuckles",
    "Radical City in Balloon Mode with Metal Sonic",
    "Radical City in Balloon Mode with Sonic",
    "Radical City in Balloon Mode with Super Sonic",
    "Radical City in Balloon Mode with Tails",
    "Radical City in Balloon Mode with Tails Doll",
    "Radical City in Grand Prix with Amy",
    "Radical City in Grand Prix with Egg Robo",
    "Radical City in Grand Prix with Eggman",
    "Radical City in Grand Prix with Knuckles",
    "Radical City in Grand Prix with Metal Knuckles",
    "Radical City in Grand Prix with Metal Sonic",
    "Radical City in Grand Prix with Sonic",
    "Radical City in Grand Prix with Super Sonic",
    "Radical City in Grand Prix with Tails",
    "Radical City in Grand Prix with Tails Doll",
    "Radical City in Tag Mode with Amy",
    "Radical City in Tag Mode with Egg Robo",
    "Radical City in Tag Mode with Eggman",
    "Radical City in Tag Mode with Knuckles",
    "Radical City in Tag Mode with Metal Knuckles",
    "Radical City in Tag Mode with Metal Sonic",
    "Radical City in Tag Mode with Sonic",
    "Radical City in Tag Mode with Super Sonic",
    "Radical City in Tag Mode with Tails",
    "Radical City in Tag Mode with Tails Doll",
    "Radical City in Time Trial (Normal) with Amy",
    "Radical City in Time Trial (Normal) with Egg Robo",
    "Radical City in Time Trial (Normal) with Eggman",
    "Radical City in Time Trial (Normal) with Knuckles",
    "Radical City in Time Trial (Normal) with Metal Knuckles",
    "Radical City in Time Trial (Normal) with Metal Sonic",
    "Radical City in Time Trial (Normal) with Sonic",
    "Radical City in Time Trial (Normal) with Super Sonic",
    "Radical City in Time Trial (Normal) with Tails",
    "Radical City in Time Trial (Normal) with Tails Doll",
    "Radical City in Time Trial (Reverse) with Amy",
    "Radical City in Time Trial (Reverse) with Egg Robo",
    "Radical City in Time Trial (Reverse) with Eggman",
    "Radical City in Time Trial (Reverse) with Knuckles",
    "Radical City in Time Trial (Reverse) with Metal Knuckles",
    "Radical City in Time Trial (Reverse) with Metal Sonic",
    "Radical City in Time Trial (Reverse) with Sonic",
    "Radical City in Time Trial (Reverse) with Super Sonic",
    "Radical City in Time Trial (Reverse) with Tails",
    "Radical City in Time Trial (Reverse) with Tails Doll",
    "Reactive Factory in Balloon Mode with Amy",
    "Reactive Factory in Balloon Mode with Egg Robo",
    "Reactive Factory in Balloon Mode with Eggman",
    "Reactive Factory in Balloon Mode with Knuckles",
    "Reactive Factory in Balloon Mode with Metal Knuckles",
    "Reactive Factory in Balloon Mode with Metal Sonic",
    "Reactive Factory in Balloon Mode with Sonic",
    "Reactive Factory in Balloon Mode with Super Sonic",
    "Reactive Factory in Balloon Mode with Tails",
    "Reactive Factory in Balloon Mode with Tails Doll",
    "Reactive Factory in Grand Prix with Amy",
    "Reactive Factory in Grand Prix with Egg Robo",
    "Reactive Factory in Grand Prix with Eggman",
    "Reactive Factory in Grand Prix with Knuckles",
    "Reactive Factory in Grand Prix with Metal Knuckles",
    "Reactive Factory in Grand Prix with Metal Sonic",
    "Reactive Factory in Grand Prix with Sonic",
    "Reactive Factory in Grand Prix with Super Sonic",
    "Reactive Factory in Grand Prix with Tails",
    "Reactive Factory in Grand Prix with Tails Doll",
    "Reactive Factory in Tag Mode with Amy",
    "Reactive Factory in Tag Mode with Egg Robo",
    "Reactive Factory in Tag Mode with Eggman",
    "Reactive Factory in Tag Mode with Knuckles",
    "Reactive Factory in Tag Mode with Metal Knuckles",
    "Reactive Factory in Tag Mode with Metal Sonic",
    "Reactive Factory in Tag Mode with Sonic",
    "Reactive Factory in Tag Mode with Super Sonic",
    "Reactive Factory in Tag Mode with Tails",
    "Reactive Factory in Tag Mode with Tails Doll",
    "Reactive Factory in Time Trial (Normal) with Amy",
    "Reactive Factory in Time Trial (Normal) with Egg Robo",
    "Reactive Factory in Time Trial (Normal) with Eggman",
    "Reactive Factory in Time Trial (Normal) with Knuckles",
    "Reactive Factory in Time Trial (Normal) with Metal Knuckles",
    "Reactive Factory in Time Trial (Normal) with Metal Sonic",
    "Reactive Factory in Time Trial (Normal) with Sonic",
    "Reactive Factory in Time Trial (Normal) with Super Sonic",
    "Reactive Factory in Time Trial (Normal) with Tails",
    "Reactive Factory in Time Trial (Normal) with Tails Doll",
    "Reactive Factory in Time Trial (Reverse) with Amy",
    "Reactive Factory in Time Trial (Reverse) with Egg Robo",
    "Reactive Factory in Time Trial (Reverse) with Eggman",
    "Reactive Factory in Time Trial (Reverse) with Knuckles",
    "Reactive Factory in Time Trial (Reverse) with Metal Knuckles",
    "Reactive Factory in Time Trial (Reverse) with Metal Sonic",
    "Reactive Factory in Time Trial (Reverse) with Sonic",
    "Reactive Factory in Time Trial (Reverse) with Super Sonic",
    "Reactive Factory in Time Trial (Reverse) with Tails",
    "Reactive Factory in Time Trial (Reverse) with Tails Doll",
    "Regal Ruin in Balloon Mode with Amy",
    "Regal Ruin in Balloon Mode with Egg Robo",
    "Regal Ruin in Balloon Mode with Eggman",
    "Regal Ruin in Balloon Mode with Knuckles",
    "Regal Ruin in Balloon Mode with Metal Knuckles",
    "Regal Ruin in Balloon Mode with Metal Sonic",
    "Regal Ruin in Balloon Mode with Sonic",
    "Regal Ruin in Balloon Mode with Super Sonic",
    "Regal Ruin in Balloon Mode with Tails",
    "Regal Ruin in Balloon Mode with Tails Doll",
    "Regal Ruin in Grand Prix with Amy",
    "Regal Ruin in Grand Prix with Egg Robo",
    "Regal Ruin in Grand Prix with Eggman",
    "Regal Ruin in Grand Prix with Knuckles",
    "Regal Ruin in Grand Prix with Metal Knuckles",
    "Regal Ruin in Grand Prix with Metal Sonic",
    "Regal Ruin in Grand Prix with Sonic",
    "Regal Ruin in Grand Prix with Super Sonic",
    "Regal Ruin in Grand Prix with Tails",
    "Regal Ruin in Grand Prix with Tails Doll",
    "Regal Ruin in Tag Mode with Amy",
    "Regal Ruin in Tag Mode with Egg Robo",
    "Regal Ruin in Tag Mode with Eggman",
    "Regal Ruin in Tag Mode with Knuckles",
    "Regal Ruin in Tag Mode with Metal Knuckles",
    "Regal Ruin in Tag Mode with Metal Sonic",
    "Regal Ruin in Tag Mode with Sonic",
    "Regal Ruin in Tag Mode with Super Sonic",
    "Regal Ruin in Tag Mode with Tails",
    "Regal Ruin in Tag Mode with Tails Doll",
    "Regal Ruin in Time Trial (Normal) with Amy",
    "Regal Ruin in Time Trial (Normal) with Egg Robo",
    "Regal Ruin in Time Trial (Normal) with Eggman",
    "Regal Ruin in Time Trial (Normal) with Knuckles",
    "Regal Ruin in Time Trial (Normal) with Metal Knuckles",
    "Regal Ruin in Time Trial (Normal) with Metal Sonic",
    "Regal Ruin in Time Trial (Normal) with Sonic",
    "Regal Ruin in Time Trial (Normal) with Super Sonic",
    "Regal Ruin in Time Trial (Normal) with Tails",
    "Regal Ruin in Time Trial (Normal) with Tails Doll",
    "Regal Ruin in Time Trial (Reverse) with Amy",
    "Regal Ruin in Time Trial (Reverse) with Egg Robo",
    "Regal Ruin in Time Trial (Reverse) with Eggman",
    "Regal Ruin in Time Trial (Reverse) with Knuckles",
    "Regal Ruin in Time Trial (Reverse) with Metal Knuckles",
    "Regal Ruin in Time Trial (Reverse) with Metal Sonic",
    "Regal Ruin in Time Trial (Reverse) with Sonic",
    "Regal Ruin in Time Trial (Reverse) with Super Sonic",
    "Regal Ruin in Time Trial (Reverse) with Tails",
    "Regal Ruin in Time Trial (Reverse) with Tails Doll",
    "Resort Island in Balloon Mode with Amy",
    "Resort Island in Balloon Mode with Egg Robo",
    "Resort Island in Balloon Mode with Eggman",
    "Resort Island in Balloon Mode with Knuckles",
    "Resort Island in Balloon Mode with Metal Knuckles",
    "Resort Island in Balloon Mode with Metal Sonic",
    "Resort Island in Balloon Mode with Sonic",
    "Resort Island in Balloon Mode with Super Sonic",
    "Resort Island in Balloon Mode with Tails",
    "Resort Island in Balloon Mode with Tails Doll",
    "Resort Island in Grand Prix with Amy",
    "Resort Island in Grand Prix with Egg Robo",
    "Resort Island in Grand Prix with Eggman",
    "Resort Island in Grand Prix with Knuckles",
    "Resort Island in Grand Prix with Metal Knuckles",
    "Resort Island in Grand Prix with Metal Sonic",
    "Resort Island in Grand Prix with Sonic",
    "Resort Island in Grand Prix with Super Sonic",
    "Resort Island in Grand Prix with Tails",
    "Resort Island in Grand Prix with Tails Doll",
    "Resort Island in Tag Mode with Amy",
    "Resort Island in Tag Mode with Egg Robo",
    "Resort Island in Tag Mode with Eggman",
    "Resort Island in Tag Mode with Knuckles",
    "Resort Island in Tag Mode with Metal Knuckles",
    "Resort Island in Tag Mode with Metal Sonic",
    "Resort Island in Tag Mode with Sonic",
    "Resort Island in Tag Mode with Super Sonic",
    "Resort Island in Tag Mode with Tails",
    "Resort Island in Tag Mode with Tails Doll",
    "Resort Island in Time Trial (Normal) with Amy",
    "Resort Island in Time Trial (Normal) with Egg Robo",
    "Resort Island in Time Trial (Normal) with Eggman",
    "Resort Island in Time Trial (Normal) with Knuckles",
    "Resort Island in Time Trial (Normal) with Metal Knuckles",
    "Resort Island in Time Trial (Normal) with Metal Sonic",
    "Resort Island in Time Trial (Normal) with Sonic",
    "Resort Island in Time Trial (Normal) with Super Sonic",
    "Resort Island in Time Trial (Normal) with Tails",
    "Resort Island in Time Trial (Normal) with Tails Doll",
    "Resort Island in Time Trial (Reverse) with Amy",
    "Resort Island in Time Trial (Reverse) with Egg Robo",
    "Resort Island in Time Trial (Reverse) with Eggman",
    "Resort Island in Time Trial (Reverse) with Knuckles",
    "Resort Island in Time Trial (Reverse) with Metal Knuckles",
    "Resort Island in Time Trial (Reverse) with Metal Sonic",
    "Resort Island in Time Trial (Reverse) with Sonic",
    "Resort Island in Time Trial (Reverse) with Super Sonic",
    "Resort Island in Time Trial (Reverse) with Tails",
    "Resort Island in Time Trial (Reverse) with Tails Doll"
];
