bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Any boss weapon (non crafted)",
    "Any fusion",
    "Baby dragon Bros",
    "Beat boss rush",
    "Beat game in sub 4 minutes",
    "Beat the game",
    "Buy a bad pistol at the shop",
    "Clear an elite ! Room without getting hit",
    "Collect 2k coins",
    "Desert",
    "Die in a room after killing a boss",
    "Die to map hazard",
    "Find a statue",
    "Get a chest spawn in any room",
    "Get a mercenary to die",
    "Get a red rarity gun from a vending machine",
    "Get an item from a wishing fountain",
    "Golden crystal crab",
    "Halloween",
    "Have a vending machine give any sized purple potion",
    "Have an npc in your starting room",
    "Kill a boss with its own weapon",
    "One punch a boss",
    "Open a cage",
    "Out if bounds",
    "Train your mercenary",
    "Trigun buff",
    "Use a large potion",
    "find a devil's snare seed",
    "grill a fish"
];
