bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
"Get the comic in Hostage Situation",
"Get the comic in Bank Approach",
"Get the comic in Race to the Bugle",
"Get the comic in Scorpion",
"Get the comic in Police Chopper Chase",
"Get the comic in Building Top Chase",
"Get the comic in Scale the Girders",
"Get the comic in Police Evaded",
"Get the comic in Spidey vs Rhino",
"Get the 2 comics in Catch Venom",
"Get the comic in Sewer Entrance",
"Get the comic in Sewer Cavern",
"Get the comic in Sewer Plant",
"Get the comic in Hidden Switches",
"Get the comic in Tunnel Crawl",
"Get the comic in Lizard's Maze",
"Get the comic in Symbiotes Infest Bugle",
"Get the comic in Elevator Descent ",
"Get the comic in Stop the Presses",
"Get the comic in Bugle's Basement",
"Get the comic in Spidey vs Mysterio",
"Get the 2 comics in Waterfront Warehouse",
"Get the comic in Underwater Trench",
"Get the comic in Stopping the Fog",
"Get the comic in Spidey vs Doc Ock",
"Get the comic in Spidey vs Carnage",
"Get the 2 comics in Spidey vs Monster Ock",
"Get the Scarlet Spidey suit",
"Get the Ben Reilly suit",
"Get 7000 points in Zipline Training",
"Get the Peter Parker suit",
"Kill a Symbiote",
"Hug a Lizard",
"Grab a Spidey Armor",
"Talk to the Lizard",
"One cycle Doc Ock",
"One cycle Water Crawl",
"Push all 4 buttons on Elevator Descent",
"Let Jonah die in Spidey vs Scorpion",
"One cycle Scorpion",
"Drown MJ in Spidey vs Venom Again!",
"Complete Hostage Situation with no web",
"Kill Mysterio",
"Kill Rhino",
"Kill Mike",
"Free Black Cat",
"Fully deplete your web cartridges",
"Survival Mode: 1 minute with Lizards",
"Survival Mode: 1 minute with Symbiotes",
"Watch a full FMV cinematic",
"Complete Item Collection Hunt under 1:30 legitimately",
"Complete Speed Training 1",
"Complete Speed Training 2",
"Complete Speed Training 3",
"Complete Stop the Bomb without using webbing",
"Kill 8 enemies in Race to the Bugle",
"Reach the top of the Stark Solutions building in Catch Venom",
"Kill all enemies in Tunnel Crawl",
"Press all the buttons in Venom's Puzzle",
"Kill all 6 enemies in Symbiotes Infest Bugle",
"Take no damage in Symbiotes Infest Bugle",
"Enter the Goblin's lair",
"Die by a press",
"Die by a laser",
"Grab the 6 fire cartridges in Waterfront Warehouse",
"Touch the Pork'n Donuts billboard in Police Chopper Chase",
"Die by fire in Bugle's Basement",
"Stand on top of 2 cranes on the same level",
"Stand on the Carnage billboard on Get To The Bank",
"Kill 10 lizards in Hidden Switches",
"Kill 4 enemies in Get to the Bank",
"Kill 8 lizards in Subway",
"Defeat 15 enemies in Time Attack (60 seconds)",
"Defeat Venom 1 without webs",
"Destroy 8 Lasers",
"Get hit by all 3 rollers in Lizard's Maze",
"Grab the 3 question marks on Get to the Bank",
"Die by drowning",
"Complete Race to the Bugle in Kid Mode",
"Beat Sewer Cavern without touching any pipes",
"Complete Stop the Bomb in Hard Mode",
"Complete Sewer Entrance without pressing x",
"Throw a Symbiote into fire",
"2 Cycle Tunnel Crawl on Hard",
"Perform any Tunnel Crawl Skip",
"Perform the regular Basement Skip",
"Perform either alternate Basement Skip",
"Perform any Stop the Presses Skip",
"Perform any Symbiotes Infest Bugle Skip",
"Perform any Elevator Skip",
"Complete Venom’s Puzzle using ‘Fetti Fall’",
"Defeat Rhino without webs",
"Stop The Presses without webs",
"Complete Waterfront Warehouse without webs",
"Complete Underwater Trench without jumping on Hard",
"Escape Monster Ock without webs",
"Complete Sewage Plant (no skips)",
"Complete Waterfront Warehouse (no skips)",
"Fall off the Subway train"
];
