bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    ".52 Gal",
    ".96 Gal",
    ".96 Gal Deco",
    "Aerospray MG",
    "Aerospray RG",
    "Annaki Splattershot Nova",
    "Ballpoint Splatling",
    "Bamboozler 14 Mk I",
    "Big Swig Roller",
    "Big Swig Roller Express",
    "Blaster",
    "Bloblobber",
    "Carbon Roller",
    "Carbon Roller Deco",
    "Clash Blaster",
    "Clash Blaster Neo",
    "Classic Squiffer",
    "Custom Dualie Squelchers",
    "Custom Jet Squelcher",
    "Custom Splattershot Jr.",
    "Dapple Dualies",
    "Dapple Dualies Nouveau",
    "Dark Tetra Dualies",
    "Dualie Squelchers",
    "Dynamo Roller",
    "E-Liter 4K",
    "E-Liter 4K Scope",
    "Explosher",
    "Flingza Roller",
    "Forge Splattershot Pro",
    "Glooga Dualies",
    "Goo Tuber",
    "H-3 Nozzlenose",
    "H-3 Nozzlenose D",
    "Heavy Splatling",
    "Heavy Splatling Deco",
    "Hero Shot Replica",
    "Hydra Splatling",
    "Inkbrush",
    "Inkbrush Nouveau",
    "Jet Squelcher",
    "Krak-On Roller",
    "L-3 Nozzlenose",
    "L-3 Nozzlenose D",
    "Light Tetra Dualies",
    "Luna Blaster",
    "Luna Blaster Neo",
    "Mini Splatling",
    "N-Zap ‘85",
    "N-Zap ‘89",
    "Nautilus 47",
    "Neo Splash-o-matic",
    "Neo Sploosh-o-matic",
    "Octobrush",
    "Painbrush",
    "REEF-LUX 450",
    "Range Blaster",
    "Rapid Blaster",
    "Rapid Blaster Deco",
    "Rapid Blaster Pro",
    "Rapid Blaster Pro Deco",
    "S Blast ‘92",
    "Slosher",
    "Slosher Deco",
    "Sloshing Machine",
    "Snipewriter 5H",
    "Splash-o-matic",
    "Splat Brella",
    "Splat Charger",
    "Splat Dualies",
    "Splat Roller",
    "Splatana Stamper",
    "Splatana Wiper",
    "Splatana Wiper Deco",
    "Splatterscope",
    "Splattershot",
    "Splattershot Jr.",
    "Splattershot Nova",
    "Splattershot Pro",
    "Sploosh-o-matic",
    "Squeezer",
    "Tenta Brella",
    "Tenta Sorella Brella",
    "Tentatek Splattershot",
    "Tri-Slosher",
    "Tri-Slosher Nouveau",
    "Tri-Stringer",
    "Undercover Brella",
    "Z+F Splat Charger",
    "Z+F Splatterscope",
    "Zink Mini Splatling"
];
