bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    ".52 Gal",
    ".52 Gal Deco",
    ".96 Gal",
    ".96 Gal Deco",
    "Aerospray MG",
    "Aerospray RG",
    "Annaki Splattershot Nova",
    "Ballpoint Splatling",
    "Ballpoint Splatling Nouveau",
    "Bamboozler 14 Mk I",
    "Bamboozler 14 Mk II",
    "Big Swig Roller",
    "Big Swig Roller Express",
    "Blaster",
    "Bloblobber",
    "Bloblobber Deco",
    "Carbon Roller",
    "Carbon Roller Deco",
    "Charcoal Decavitator",
    "Clash Blaster",
    "Clash Blaster Neo",
    "Classic Squiffer",
    "Custom Blaster",
    "Custom Douser Dualies FF",
    "Custom Dualie Squelchers",
    "Custom E-Liter 4K",
    "Custom E-Liter 4K scope",
    "Custom Explosher",
    "Custom Goo Tuber",
    "Custom Hydra Splatling",
    "Custom Jet Squelcher",
    "Custom Range Blaster",
    "Custom Splattershot Jr.",
    "Custom Wellstring V",
    "Dapple Dualies",
    "Dapple Dualies Nouveau",
    "Dark Tetra Dualies",
    "Douser Dualies FF",
    "Dread Wringer",
    "Dread Wringer D",
    "Dualie Squelchers",
    "Dynamo Roller",
    "E-Liter 4K",
    "E-Liter 4K Scope",
    "Enperry Splat Dualies",
    "Explosher",
    "Flingza Roller",
    "Foil Flingza Roller",
    "Foil Squeezer",
    "Forge Splattershot Pro",
    "Glooga Dualies",
    "Glooga Dualies Deco",
    "Gold Dynamo Roller",
    "Goo Tuber",
    "H-3 Nozzlenose",
    "H-3 Nozzlenose D",
    "Heavy Edit Splatling",
    "Heavy Edit Splatling Nouveau",
    "Heavy Splatling",
    "Heavy Splatling Deco",
    "Hero Shot Replica",
    "Hydra Splatling",
    "Inkbrush",
    "Inkbrush Nouveau",
    "Inkline Tri-Stringer",
    "Jet Squelcher",
    "Krak-On Roller",
    "L-3 Nozzlenose",
    "L-3 Nozzlenose D",
    "Light Tetra Dualies",
    "Luna Blaster",
    "Luna Blaster Neo",
    "Mini Splatling",
    "Mint Decavitator",
    "N-Zap ‘85",
    "N-Zap ‘89",
    "Nautilus 47",
    "Nautilus 79",
    "Neo Splash-o-matic",
    "Neo Sploosh-o-matic",
    "New Squiffer",
    "Octobrush",
    "Painbrush",
    "Painbrush Nouveau",
    "REEF-LUX 450",
    "REEF-LUX 450 Deco",
    "Range Blaster",
    "Rapid Blaster",
    "Rapid Blaster Deco",
    "Rapid Blaster Pro",
    "Rapid Blaster Pro Deco",
    "Recycled Brella 24 Mk I",
    "Recycled Brella 24 Mk II",
    "S Blast ‘92",
    "S-BLAST ‘91",
    "Slosher",
    "Slosher Deco",
    "Sloshing Machine",
    "Sloshing Machine Neo",
    "Snipewriter 5B",
    "Snipewriter 5H",
    "Sorella Brella",
    "Splash-o-matic",
    "Splat Brella",
    "Splat Charger",
    "Splat Dualies",
    "Splat Roller",
    "Splatana Stamper",
    "Splatana Stamper Nouveau",
    "Splatana Wiper",
    "Splatana Wiper Deco",
    "Splatterscope",
    "Splattershot",
    "Splattershot Jr.",
    "Splattershot Nova",
    "Splattershot Pro",
    "Sploosh-o-matic",
    "Squeezer",
    "Tenta Brella",
    "Tenta Sorella Brella",
    "Tentatek Splattershot",
    "Tri-Slosher",
    "Tri-Slosher Nouveau",
    "Tri-Stringer",
    "Undercover Brella",
    "Undercover Sorella Brella",
    "Wellstring V",
    "Z+F Splat Charger",
    "Z+F Splatterscope",
    "Zink Mini Splatling"
];
