bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Beat Boss 1 with Brella",
    "Beat Boss 2 with 5 Weapons",
    "Beat Boss 3 with roller",
    "Beat Boss 4 with dualies",
    "Beat level 15 with 5 Weapons",
    "Beat level 17 with 3 Weapons",
    "Beat level 25 with 3 Weapons",
    "Beat level 5 with 3 Weapons",
    "Collect 10 armor upgrades",
    "Collect 10 egg containers",
    "Collect 15 armor upgrades",
    "Collect 5 armor upgrades",
    "Collect 5 egg containers",
    "Collect a ticket",
    "Complete 3 extra levels with the blaster",
    "Complete 3 extra levels with the brella",
    "Complete 3 extra levels with the brush",
    "Complete Level 1 with Brush",
    "Complete Level 11 with roller",
    "Complete Level 15 with splatling",
    "Complete Level 16 with Charger",
    "Complete Level 19 with Brella",
    "Complete Level 24 with blaster",
    "Complete Level 26 with slosher",
    "Complete Level 5 with shot",
    "Complete Level 6 with dualies",
    "Get Collectables in Level 11",
    "Get Collectables in Level 13",
    "Get Collectables in Level 16",
    "Get Collectables in Level 19",
    "Get Collectables in Level 2",
    "Get Collectables in Level 22",
    "Get Collectables in Level 25",
    "Get Collectables in Level 4",
    "Get Collectables in Level 7",
    "Get Collectables in World 3 Overworld",
    "Get Collectables in World 5 Overworld",
    "Unlock auto bombs"
];
