bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "100 % Toasty",
    "100% Gnorc Cove",
    "100% Haunted Towers",
    "100% Lofty Castle",
    "100% Stone Hill",
    "100% Tree Tops",
    "100% Wizard Peak",
    "100% dark hollow sparxless",
    "100% gnorc gnexus",
    "100% sunny flight",
    "all dragons in dry canyon",
    "all eggs in magic crafter",
    "all eggs in peace keepers",
    "break 5 life chests",
    "break 7 yellow spring chests",
    "break a fan chest in 5 different levels",
    "break red spring chest",
    "clear guantan",
    "collect 2000 gems",
    "collect all 10 fodder in dark hollow",
    "collect all 6 lamp gems in ice cavern",
    "defeat 3 bosses",
    "do 5 laps behind cliff town without dying",
    "exit through vortex in 5 levels",
    "exit through vortex in a level from each world",
    "exit through vortex on all artisans levels",
    "flame 5 glowing mushrooms in beast makers",
    "flame hidden stump in lofty castle",
    "flame pink tulip in stone hill",
    "free the two chickens in misty bog",
    "get slapped by 3 big mamas in cliff town",
    "get slapped, electrocuted, and eaten",
    "hit 5 enemies with cannon in dream weavers",
    "jump over shemps rod 8 times without getting hit",
    "key chest in shemp",
    "kill all spiders in high caves",
    "kill both platform druids in high caves with super charge",
    "kissed by all haunted towers faeries",
    "kissed by all high caves faeries",
    "light two bonfires in dark hollow",
    "rescue nestor and defeat gnasty gnorc",
    "shoot 5 gnorcs with cannon in peace keepers",
    "skill point for secret room in dream weavers",
    "stand on shack in misty bog",
    "use all whirlwinds in dream weavers"
];
