//Made By DrMonkeyman
bingoGenerator = require("./generators/generator_bases/simple_generator.js");
var bingoList =
[{"name": "Unlock 5 Locked Chests with Keys"}, 
{"name": "Finish Sunny Flight in under 1:40.00"}, 
{"name": "Collect 6 Eggs"}, 
{"name": "Go through 3 Return Home Portals & Open Toasty"}, 
{"name": "Go through 6 Return Home Portals"}, 
{"name": "Collect all Dragons from the first 5 Homeworlds"}, 
{"name": "Collect 2500 Total Treasure"}, 
{"name": "Collect 5000 Total Treasure"}, 
{"name": "Collect 14 Dragons in all Peacekeepers World Levels combined"}, 
{"name": "Collect 350 Gems in Ice Cavern"}, 
{"name": "Collect 425 Gems in Wizard Peak"}, 
{"name": "Collect all Dragons & 350 Gems in Tree Tops"}, 
{"name": "Catch 3 Green Thiefs"}, 
{"name": "Collect 300 Gems in Cliff Town"}, 
{"name": "Collect 350 Gems in Dry Canyon"}, 
{"name": "Collect 400 Gems in Alpine Ridge"}, 
{"name": "Break 1 Red Spring Chest & 5 Green Spring Chests"}, 
{"name": "Finish Night Flight in under 1:10.00"}, 
{"name": "Finish Crystal Flight in under 1:20.00"}, 
{"name": "Finish Wild Flight in under 1:15.00"}, 
{"name": "Defeat Toasty & Jacques"}, 
{"name": "Defeat Blowhard & Metalhead"}, 
{"name": "Collect all Dragons in all Boss Levels"}, 
{"name": "Collect all Dragons in Wizard Peak & Town Square"}, 
{"name": "Collect 300 Gems in Gnorc Cove"}, 
{"name": "Collect 350 Gems in Twilight Harbor"}, 
{"name": "Collect all Dragons in Stone Hill & Dark Hollow"}, 
{"name": "Go through 10 Return Home Portals"}, 
{"name": "Collect 9 Eggs"}, 
{"name": "Collect 14 Dragons in all Artisans Levels combined"}, 
{"name": "Collect 12 Dragons in all Magic Crafters Levels combined"}, 
{"name": "Collect 10 Dragons in all Beast Makers Levels combined"}, 
{"name": "Collect 14 Dragons in all Dream Weavers Levels combined"}, 
{"name": "Collect 400 Gems in Dark Passage"}, 
{"name": "Collect 6 Shell One-Ups"}, 
{"name": "Defeat Doctor Shemp & Collect 400 Gems in Gnasty Gnorc's Level"}, 
{"name": "Get all Gems in Sunny Flight & Icy Flight"}, 
{"name": "Explode 6 Fireworks Chests"}, 
{"name": "Get all Dragons in Wizard Peak & Lofty Castle"}, 
{"name": "Get all Dragons in Artisans Homeworld & Haunted Towers"}, 
{"name": "Get all Dragons in Terrace Village & Dark Passage"}, 
{"name": "Collect 1500 Total Treasure"}, 
{"name": "Collect 400 Gems in Jacques' Level"}, 
{"name": "Collect 400 Gems in Metalhead's Level"}, 
{"name": "Collect all 100 Gems in Toasty's Level"}, 
{"name": "Get all Gems in Night Flight & Crystal Flight"}, 
{"name": "Collect 400 Gems in Haunted Towers"}, 
{"name": "Collect all 400 Gems in Blowhard's Level"}, 
{"name": "Collect all 300 Gems in Doctor Shemp's Level"}, 
{"name": "Collect 400 Gems in High Caves"}, 
{"name": "Collect all 200 Gems in Town Square"}, 
{"name": "Collect all 200 Gems in Stone Hill"}, 
{"name": "Collect 300 Gems in Terrace Village"}, 
{"name": "Collect 450 Gems in Misty Bog"}, 
{"name": "Collect 300 Gems in Lofty Castle"}, 
{"name": "Complete Icy Flight in under 1:25.00"}, 
{"name": "Collect all 100 Gems in Artisans Homeworld"}, 
{"name": "Collect 175 Gems in Peace Keepers Homeworld"}, 
{"name": "Collect 250 Gems in Magic Crafters Homeworld"}, 
{"name": "Collect 250 Gems in Beast Makers Homeworld"}, 
{"name": "Collect 250 Gems in Dream Weavers Homeworld"}, 
{"name": "Collect all Dragons in Dry Canyon & Gnorc Cove"}, 
{"name": "Collect all Dragons in Cliff Town & Alpine Ridge"}, 
{"name" : "Collect all Dragons in Toasty & Ice Cavern"}, 
{"name": "Collect all Dragons in High Caves & Twilight Harbor"}, 
{"name": "Collect all Eggs in Wizard Peak & All Dragons in Misty Bog"}, 
{"name": "Unlock the Locked Chests in Beast Makers Homeworld Level & Dry Canyon"}]