var bingoGenerator = require("./generators/generator_bases/srl_generator_v5.js");

var bingoList = [[
{ "name": "Kill a Bog Rat, Splox, & Bogdo", "types": ["bogano","combat"] },
{ "name": "Kill a 2 Bogdos", "types": ["bogano","combat"] },
{ "name": "Kill 6 Sploxes", "types": ["bogano","combat"] },
{ "name": "Kill 5 Imperial Enemy Types", "types": ["combat"] },
{ "name": "Kill 5 Scazzes", "types": ["zeffo","combat"] },
{ "name": "Kill a Phillak", "types": ["zeffo","combat"] },
{ "name": "Kill a Nydak", "types": ["dathomir","combat"] },
{ "name": "Kill 3 Bane Back Spiders", "types": ["dathomir","combat"] },
{ "name": "Kill 3 Nightbrother Warriors", "types": ["dathomir","combat"] },
{ "name": "Kill a Wyyyschokk", "types": ["kashyyyk","combat"] },
{ "name": "Kill 3 Flame Beetles", "types": ["kashyyyk","combat"] },
{ "name": "Kill a Flame Trooper", "types": ["kashyyyk","combat"] },
{ "name": "Kill a Slyyyg", "types": ["kashyyyk","combat"] },
{ "name": "Kill a Purge Trooper", "types": ["zeffo","combat"] },
{ "name": "QTE Kill a Nydak", "types": ["dathomir","combat"] },
{ "name": "Kick a Phillak", "types": ["zeffo","combat"] },
{ "name": "Kill a Scazz after it Grabs You", "types": ["zeffo","combat"] },
{ "name": "Destroy 3 Probe Droids on Ilum", "types": ["ilum","combat"] }
],[
{ "name": "Eno Cordova Lightsaber Emitter", "types": ["bogano","collectible"] },
{ "name": "Kalpi Seed", "types": ["bogano","collectible"] },
{ "name": "Valor and Wisdom II Sleeve", "types": ["bogano","collectible"] },
{ "name": "Magus Lightsaber Emitter", "types": ["dathomir","collectible"] },
{ "name": "Racer Mantis Paint Job", "types": ["dathomir","collectible"] },
{ "name": "Blue Leader BD-1 Skin", "types": ["zeffo","collectible"] },
{ "name": "Copper Lightsaber Material", "types": ["zeffo","collectible"] },
{ "name": "Royal Fluzz", "types": ["zeffo","collectible"] },
{ "name": "Sundari Dawn BD-1 Skin", "types": ["kashyyyk","collectible"] },
{ "name": "Rainforest Poncho", "types": ["kashyyyk","collectible"] },
{ "name": "Matte Lightsaber Material", "types": ["kashyyyk","collectible"] },
{ "name": "Bonshyyyr Seed", "types": ["kashyyyk","collectible"] },
{ "name": "Tibanna BD-1 Skin", "types": ["ilum","collectible"] }
],[
{ "name": "100% Binog Mesa", "types": ["bogano","completion"] },
{ "name": "1 Bogano Secret", "types": ["bogano","completion"] },
{ "name": "100% Brother's Bastion", "types": ["dathomir","completion"] },
{ "name": "1 Dathomir Secret", "types": ["bogano","completion"] },
{ "name": "100% Derelict Hangar", "types": ["zeffo","completion"] },
{ "name": "100% Gusty Bluffs", "types": ["zeffo","completion"] },
{ "name": "2 Zeffo Secrets", "types": ["zeffo","completion"] },
{ "name": "1 Tomb of Eilram Secret", "types": ["zeffo","completion"] },
{ "name": "100% Cargo Pad", "types": ["kashyyyk","completion"] },
{ "name": "1 Kashyyyk Secret", "types": ["kashyyyk","completion"] },
{ "name": "100% Jedi Temple", "types": ["ilum","completion"] },
{ "name": "1 Ilum Secret", "types": ["ilum","completion"] }
],[
{ "name": "Evasive Kick", "types": ["skill"] },
{ "name": "Force Attunement", "types": ["skill"] },
{ "name": "Empowered Slow", "types": ["skill"] },
{ "name": "Survival Skills", "types": ["skill"] },
{ "name": "Superior Blocking", "types": ["skill"] },
{ "name": "Sprint Strike", "types": ["skill"] }
],[
{ "name": "Meet Nightsister Merrin", "types": ["dathomir","variety"] },
{ "name": "Meet the Stranger", "types": ["dathomir","skill"] },
{ "name": "Scan the Binog", "types": ["bogano","variety"] },
{ "name": "Scan the Para Fish", "types": ["bogano","variety"] },
{ "name": "Scan the Dead Stormtrooper", "types": ["zeffo","variety"] },
{ "name": "Look Into 3 Scazz Holes", "types": ["zeffo","variety"] },
{ "name": "Create 5 Shortcuts", "types": ["variety"] },
{ "name": "Rest at 7 Meditation Points", "types": ["variety"] },
{ "name": "Scan a Gonk Droid", "types": ["kashyyyk","variety"] },
{ "name": "Observe 2 Tachs", "types": ["kashyyyk","variety"] },
{ "name": "Get Set on Fire", "types": ["kashyyyk","variety"] },
{ "name": "Change Your Lightsaber Color", "types": ["variety"] },
{ "name": "Obtain Slice: Security Droid", "types": ["kashyyyk","variety"] },
{ "name": "Scan a Statue of a Jedi Master", "types": ["ilum","variety"] },
{ "name": "Scan a Geyser", "types": ["ilum","variety"] }
],[
{ "name": "Kill Oggdo Bogdo", "types": ["bogano","combat"] },
{ "name": "Kill Every Bogano Enemy Type", "types": ["bogano","combat"] },
{ "name": "Kill 2 Bog Rats, Sploxes, & Bogdos", "types": ["bogano","combat"] },
{ "name": "Kill 10 Stormtroopers with Deflected Lasers", "types": ["zeffo","combat"] },
{ "name": "Kill 5 Imperial Enemy Types", "types": ["zeffo","combat"] },
{ "name": "Kill 3 Tomb Guardians", "types": ["zeffo","combat"] },
{ "name": "Kill 2 Tomb Guardians Without Using Push/Pull", "types": ["zeffo","combat"] },
{ "name": "Kill 7 Scazzes in the Tomb of Eilram", "types": ["zeffo","combat"] },
{ "name": "Kill an Electrobaton Purge Trooper", "types": ["combat"] },
{ "name": "Kill 6 Imperial Probe Droids", "types": ["combat"] },
{ "name": "Kill an AT-ST", "types": ["combat"] },
{ "name": "Kill Multiple Imperial Troops with 1 Grenade", "types": ["combat"] },
{ "name": "Cause a Scazz to Die from a Skungus", "types": ["zeffo","combat"] },
{ "name": "Kill a Jotaz You've Parried 3 Times", "types": ["zeffo","combat"] },
{ "name": "Kill 2 Types of Purge Trooper", "types": ["combat"] },
{ "name": "Kill Albino Wyyyschokk", "types": ["kashyyyk","combat"] },
{ "name": "Kill a KX Security Droid", "types": ["combat"] },
{ "name": "Kill a Snow Trooper", "types": ["ilum","combat"] }
],[
{ "name": "5 Bogano Chests", "types": ["bogano","collectible"] },
{ "name": "3 Tomb of Eilram Chests", "types": ["zeffo","collectible"] },
{ "name": "Charisma Mantis Paint Job", "types": ["zeffo","collectible"] },
{ "name": "Wayfarer Poncho", "types": ["zeffo","collectible"] },
{ "name": "Cerakote Lightsaber Material", "types": ["zeffo","collectible"] },
{ "name": "Occultation Mantis Paint Job", "types": ["zeffo","collectible"] },
{ "name": "Serape Poncho Material", "types": ["zeffo","collectible"] },
{ "name": "Durite Lightsaber Material", "types": ["zeffo","collectible"] },
{ "name": "Dreamwort", "types": ["zeffo","collectible"] },
{ "name": "Bounty Hunter Mantis Paint Job", "types": ["kashyyyk","collectible"] },
{ "name": "2 Chests on Tree Branches", "types": ["kashyyyk","collectible"] },
{ "name": "Passion and Strength II Lightsaber Sleeve", "types": ["kashyyyk","collectible"] },
{ "name": "Bleeding Gut", "types": ["dathomir","collectible"] },
{ "name": "2 Underwater Ilum Chests", "types": ["ilum","collectible"] },
{ "name": "4 Dathomir Chests", "types": ["dathomir","collectible"] },
{ "name": "10 Zeffo Chests", "types": ["zeffo","collectible"] },
{ "name": "7 Kashyyyk Chests", "types": ["kashyyyk","collectible"] }
],[
{ "name": "100% Ancient Catacombs", "types": ["zeffo","completion"] },
{ "name": "100% Abandoned Village", "types": ["zeffo","completion"] },
{ "name": "100% Weathered Monument", "types": ["zeffo","completion"] },
{ "name": "69% Bogano", "types": ["bogano","completion"] },
{ "name": "Find 3 Force Essences", "types": ["completion"] },
{ "name": "Find 3 Life Essences", "types": ["completion"] },
{ "name": "100% Kyyyalstaad Falls", "types": ["kashyyyk","completion"] },
{ "name": "3 Kashyyyk Secrets", "types": ["kashyyyk","completion"] },
{ "name": "2 Dathomir Secrets", "types": ["dathomir","completion"] },
{ "name": "5 Zeffo Secrets", "types": ["zeffo","completion"] },
{ "name": "3 Bogano Secrets", "types": ["bogano","completion"] },
{ "name": "100% Hermit's Abode", "types": ["bogano","completion"] },
{ "name": "100% Landing Pad", "types": ["bogano","completion"] },
{ "name": "2 Ilum Secrets", "types": ["ilum","completion"] },
{ "name": "100% Shattered Lake", "types": ["ilum","completion"] }
],[
{ "name": "Improved Stims", "types": ["skill"] },
{ "name": "Enhanced Survival Skills", "types": ["skill"] },
{ "name": "Agile Deflection", "types": ["skill"] },
{ "name": "Delay Thrust", "types": ["skill"] },
{ "name": "Delay Combo", "types": ["skill"] },
{ "name": "Repulse", "types": ["skill"] },
{ "name": "Mass Push", "types": ["skill"] },
{ "name": "Enhanced Force Recovery", "types": ["skill"] },
{ "name": "Greater Force Attunement", "types": ["skill"] },
{ "name": "Burst Slow", "types": ["skill"] }
],[
{ "name": "Touch Broken Artifacts in the Tomb of Eilram", "types": ["zeffo","variety"] },
{ "name": "Touch Officer Krane's Remains", "types": ["zeffo","collectible"] },
{ "name": "Enter the Ice Caves via 3 Different Slides", "types": ["zeffo","variety"] },
{ "name": "Touch the Memorial to Fallen Clones", "types": ["zeffo","variety"] },
{ "name": "Use Scomp Link to Open 5 Doors", "types": ["variety"] },
{ "name": "Get the Scan, Chest, and Secret in Albino Wyyyschokk's Room Without Spawning Boss", "types": ["kashyyyk","variety"] },
{ "name": "Hack 2 KX Security Droids", "types": ["kashyyyk","variety"] },
{ "name": "View the Hologram in Broken Wing", "types": ["zeffo","variety"] },
{ "name": "Overcharge 6 Panels", "types": ["zeffo","variety"] },
{ "name": "Discover a Wookiee's Macrobinoculars", "types": ["kashyyyk","variety"] },
{ "name": "Meet Tarrful", "types": ["kashyyyk","variety"] },
{ "name": "Recruit the Bogling Companion", "types": ["bogano","variety"] }
],[
{ "name": "Kill the Rabid Jotaz", "types": ["zeffo","combat"] },
{ "name": "Kick Albino Wyyyschokk on its Sensitive Backside", "types": ["kashyyyk","combat"] },
{ "name": "Defeat Trilla 2", "types": ["zeffo","combat"] },
{ "name": "Drop Attack 3 Slyyygs", "types": ["kashyyyk","combat"] },
{ "name": "Kill 3 Tomb Guardians from Each Tomb", "types": ["zeffo","combat"] },
{ "name": "Push a Purge Trooper Off a Sarcophagus", "types": ["zeffo","combat"] },
{ "name": "Kill 4 Clone Troopers", "types": ["dathomir","combat"] },
{ "name": "Kill a Purge Trooper with Gravity", "types": ["combat"] },
{ "name": "Kill 1 of Each Purge Trooper Type", "types": ["combat"] },
{ "name": "Kill 3 Snow Troopers", "types": ["ilum","combat"] },
{ "name": "Return 10 Rockets to their Origin", "types": ["combat"] }
],[
{ "name": "Greezy Money Mantis Paint Job", "types": ["zeffo","collectible"] },
{ "name": "Zodiac Drifter Mantis Paint Job", "types": ["zeffo","collectible"] },
{ "name": "Doonium Lightsaber Material", "types": ["kashyyyk","collectible"] },
{ "name": "8 Dathomir Chests", "types": ["dathomir","collectible"] },
{ "name": "Savannah Poncho", "types": ["dathomir","collectible"] },
{ "name": "4 Underwater Chests", "types": ["collectible"] },
{ "name": "5 Ilum Chests", "types": ["ilum","collectible"] },
{ "name": "8 Bogano Chests", "types": ["bogano","collectible"] },
{ "name": "8 Dathomir Chests", "types": ["dathomir","collectible"] },
{ "name": "8 Locked Chests", "types": ["collectible"] },
{ "name": "20 Zeffo Chests", "types": ["zeffo","collectible"] },
{ "name": "13 Kashyyyk Chests", "types": ["kashyyyk","collectible"] }
],[
{ "name": "Find 6 Life Essences", "types": ["completion"] },
{ "name": "Find 6 Force Essences", "types": ["completion"] },
{ "name": "6 Bogano Secrets", "types": ["bogano","completion"] },
{ "name": "3 Dathomir Secrets", "types": ["dathomir","completion"] },
{ "name": "100% Tomb of Eilram", "types": ["zeffo","completion"] },
{ "name": "100% Tomb of Miktrull", "types": ["zeffo","completion"] },
{ "name": "6 Zeffo Secrets", "types": ["zeffo","completion"] },
{ "name": "100% Ice Caves", "types": ["zeffo","completion"] },
{ "name": "100% Crash Site", "types": ["zeffo","completion"] },
{ "name": "100% Crystal Caves", "types": ["ilum","completion"] },
{ "name": "100% Origin Lake", "types": ["kashyyyk","completion"] },
{ "name": "3 Ilum Secrets", "types": ["ilum","completion"] },
{ "name": "100% Imperial Refinery", "types": ["kashyyyk","completion"] }
],[
{ "name": "Howling Push", "types": ["zeffo","skill"] },
{ "name": "Grasping Pull", "types": ["zeffo","skill"] },
{ "name": "The Power of Friendship", "types": ["zeffo","skill"] },
{ "name": "Ultimate Force Attunement", "types": ["zeffo","skill"] },
{ "name": "Lightsaber Throw", "types": ["zeffo","skill"] },
{ "name": "Whirlwind Throw", "types": ["zeffo","skill"] },
{ "name": "Switch Attack", "types": ["zeffo","skill"] },
{ "name": "Expert Survival Skills", "types": ["zeffo","skill"] },
{ "name": "Personalized Stims", "types": ["zeffo","skill"] }
],[
{ "name": "Touch Evidence of the Age of Extravagance", "types": ["zeffo","variety"] },
{ "name": "Scan the Votive Candles", "types": ["zeffo","variety"] },
{ "name": "Obtain Slice: Probe Droid", "types": ["zeffo","variety"] },
{ "name": "Get Captured by a Haxion Brood Droid", "types": ["zeffo","variety"] },
{ "name": "Touch the Memorial to Master Mar Ti Kam'Ron", "types": ["ilum","variety"] },
{ "name": "Touch a Jedi's Grave", "types": ["zeffo","variety"] },
{ "name": "Speak to Merrin About Bogano", "types": ["bogano","variety"] }
],[
{ "name": "Kill 4 AT-STs", "types": ["combat"] },
{ "name": "QTE Kill 3 Wyyyschokks in 1 Encounter", "types": ["kashyyyk","combat"] },
{ "name": "Defeat Ninth Sister After Being Hit By Charge and Shockwave", "types": ["kashyyyk","combat"] },
{ "name": "Drown a KX Security Droid", "types": ["zeffo","combat"] },
{ "name": "Kill 3 Nightbrothers w/ Gravity At Once", "types": ["combat"] },
{ "name": "Cut Off a Bogdo's Tongue", "types": ["combat"] },
{ "name": "Awaken Every KX Droid On Ilum At Once and Defeat Them", "types": ["ilum","combat"] }
],[
{ "name": "Orichalc Lightsaber Material", "types": ["zeffo","collectible"] },
{ "name": "Sumi BD-1 Skin", "types": ["zeffo","collectible"] },
{ "name": "Cantonica BD-1 Skin", "types": ["zeffo","collectible"] },
{ "name": "8 Underwater Chests", "types": ["collectible"] },
{ "name": "12 Dathomir Chests", "types": ["dathomir","collectible"] },
{ "name": "12 Bogano Chests", "types": ["bogano","collectible"] },
{ "name": "31 Zeffo Chests", "types": ["zeffo","collectible"] },
{ "name": "20 Kashyyyk Chests", "types": ["kashyyyk","collectible"] },
{ "name": "Collect All Terrarium Seeds", "types": ["collectible"] }
],[
{ "name": "Find 9 Life Essences", "types": ["completion"] },
{ "name": "Find 9 Force Essences", "types": ["completion"] },
{ "name": "100% Bogano", "types": ["bogano","completion"] },
{ "name": "80% Zeffo", "types": ["zeffo","completion"] },
{ "name": "100% Venator Wreckage", "types": ["zeffo","completion"] },
{ "name": "100% Ilum", "types": ["ilum","completion"] },
{ "name": "4 Dathomir Secrets", "types": ["dathomir","completion"] },
{ "name": "5 Kashyyyk Secrets", "types": ["kashyyyk","completion"] },
{ "name": "14 Zeffo Secrets", "types": ["zeffo","completion"] }
],[
{ "name": "Power Throw", "types": ["zeffo","skill"] },
{ "name": "Howling Pull", "types": ["skill"] },
{ "name": "Lightsaber Mastery", "types": ["skill"] },
{ "name": "Precision Evade", "types": ["skill"] }
],[
{ "name": "Use Split Strike 8 Times", "types": ["variety"] },
{ "name": "Escape the Tomb of Miktrull without Pulling a Rope In the Final Puzzle", "types": ["zeffo","variety"] },
{ "name": "Touch a Stormtrooper's Helmet at the Origin Tree", "types": ["kashyyyk","variety"] },
{ "name": "Observe 4 Unique Tachs", "types": ["kashyyyk","variety"] }
],[
{ "name": "Kill Taron Malicos", "types": ["dathomir","combat"] },
{ "name": "Kill All 4 Legendary Beasts", "types": ["combat"] },
{ "name": "Kill 7 Nydaks", "types": ["dathomir","combat"] },
{ "name": "Kill 6 Bogdos", "types": ["bogano","combat"] },
{ "name": "Electrocute a Purge Trooper Commander", "types": ["combat"] },
{ "name": "Parry 4 Mykals", "types": ["kashyyyk","combat"] },
{ "name": "Defeat Every Haxion Brood Enemy Type", "types": ["combat"] },
{ "name": "Kill a Jotaz with Gravity", "types": ["zeffo","combat"] },
{ "name": "Kill 20 Undead Nightsisters", "types": ["dathomir","combat"] },
{ "name": "Kill 6 Purge Troopers on Nur", "types": ["nur","combat"] },
{ "name": "Kill 5 Astromech Droids, You Monster", "types": ["combat"] }
],[
{ "name": "43 Zeffo Chests", "types": ["zeffo","collectible"] },
{ "name": "16 Dathomir Chests", "types": ["kashyyyk","collectible"] },
{ "name": "14 Underwater Chests", "types": ["collectible"] },
{ "name": "16 Bogano Chests", "types": ["bogano","collectible"] },
{ "name": "27 Kashyyyk Chests", "types": ["zeffo","collectible"] }
],[
{ "name": "100% Zeffo", "types": ["zeffo","completion"] },
{ "name": "100% Dathomir", "types": ["dathomir","completion"] },
{ "name": "100% Kashyyyk", "types": ["kashyyyk","completion"] }
],[
{ "name": "Meet a Sith Lord", "types": ["nur","variety"] },
{ "name": "Scan a Detention Cell", "types": ["nur","variety"] },
{ "name": "Complete the Enemy Compendium", "types": ["variety"] },
{ "name": "Witness 12 Conversations Aboard the Mantis", "types": ["variety"] },
{ "name": "Speak to Merrin On Every Planet", "types": ["variety"] },
{ "name": "After Recruiting the Bogling Companion, Observe it 3 Separate Times", "types": ["variety"] },
{ "name": "Watch Cere and Jaro Tapal Walk Down Hallways", "types": ["variety"] }
],[
{ "name": "Find 12 Force Essences", "types": ["hard"] },
{ "name": "Find 12 Life Essences", "types": ["hard"] },
{ "name": "100% 3 Planets", "types": ["hard"] },
{ "name": "100% 4 Planets", "types": ["hard"] },
{ "name": "100% 5 Planets", "types": ["hard"] },
{ "name": "100% a Save File", "types": ["hard"] },
{ "name": "Kill All 4 Legendary Beasts on Jedi Grand Master", "types": ["hard"] },
{ "name": "Kill All 4 Legendary Beasts w/ Only Basic Attacks", "types": ["hard"] },
{ "name": "Kick All 4 Legendary Beasts", "types": ["hard"] },
{ "name": "Kill Taron Malicos Without Taking Damage", "types": ["dathomir","hard"] },
{ "name": "Kill Ninth Sister on Jedi Grand Master", "types": ["kashyyyk","hard"] },
{ "name": "Kill Trilla 4 Without Healing", "types": ["nur","hard"] },
{ "name": "Kill Trilla 4 on Jedi Grand Master", "types": ["nur","hard"] },
{ "name": "Kill 3 of Each Purge Trooper Type", "types": ["hard"] },
{ "name": "Complete the Arena on Ordo Eris on Grand Master", "types": ["hard"] },
{ "name": "Complete the Nur Dojo on Grand Master", "types": ["hard"] },
{ "name": "Buy All Skills", "types": ["hard"] },
{ "name": "100% Ilum Without Using Jedi Flip", "types": ["ilum","hard"] }
]];
