bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    { name: "Good Egg 1" },
    { name: "Good Egg 2" },
    { name: "Good Egg 3" },
    { name: "Good Egg C" },
    { name: "Good Egg P" },
    { name: "Good Egg L" },
    { name: "Honeyhive 1" },
    { name: "Honeyhive 2" },
    { name: "Honeyhive 3" },
    { name: "Honeyhive C" },
    { name: "Honeyhive P" },
    { name: "Honeyhive L" },
    { name: "Loopdeeloop" },
    { name: "Flipswitch" },
    { name: "Bowser Jr.'s Robot Reactor" },
    { name: "Sweet Sweet" },
    { name: "Space Junk 1" },
    { name: "Space Junk 2" },
    { name: "Space Junk 3" },
    { name: "Space Junk C" },
    { name: "Space Junk P" },
    { name: "Space Junk S" },
    { name: "Battlerock 1" },
    { name: "Battlerock 2" },
    { name: "Battlerock 3" },
    { name: "Battlerock C" },
    { name: "Battlerock P" },
    { name: "Battlerock S" },
    { name: "Battlerock L" },
    { name: "Rolling Green" },
    { name: "Hurry-Scurry" },
    { name: "Bowser's Star Reactor" },
    { name: "Sling Pod" },
    { name: "Beach Bowl 1" },
    { name: "Beach Bowl 2" },
    { name: "Beach Bowl 3" },
    { name: "Beach Bowl C" },
    { name: "Beach Bowl P" },
    { name: "Beach Bowl S" },
    { name: "Ghostly 1" },
    { name: "Ghostly 2" },
    { name: "Ghostly 3" },
    { name: "Ghostly Comet" },
    { name: "Ghostly Purples" },
    { name: "Ghostly Hidden" },
    { name: "Bubble Breeze" },
    { name: "Buoy Base 1" },
    { name: "Buoy Base S" },
    { name: "Bowser Jr.'s Airship Armada" },
    { name: "Drip Drop" },
    { name: "Gusty Garden 1" },
    { name: "Gusty Garden 2" },
    { name: "Gusty Garden 3" },
    { name: "Gusty Garden C" },
    { name: "Gusty Garden P" },
    { name: "Gusty Garden S" },
    { name: "Freezeflame 1" },
    { name: "Freezeflame 2" },
    { name: "Freezeflame 3" },
    { name: "Freezeflame C" },
    { name: "Freezeflame P" },
    { name: "Freezeflame S" },
    { name: "Dusty Dune 1" },
    { name: "Dusty Dune 2" },
    { name: "Dusty Dune 3" },
    { name: "Dusty Dune C" },
    { name: "Dusty Dune P" },
    { name: "Dusty Dune S" },
    { name: "Dusty Dune G" },
    { name: "Honeyclimb" },
    { name: "Bowser's Dark Matter Plant" },
    { name: "Bigmouth" },
    { name: "Gold Leaf 1" },
    { name: "Gold Leaf 2" },
    { name: "Gold Leaf 3" },
    { name: "Gold Leaf C" },
    { name: "Gold Leaf P" },
    { name: "Gold Leaf S" },
    { name: "Sea Slide 1" },
    { name: "Sea Slide 2" },
    { name: "Sea Slide 3" },
    { name: "Sea Slide C" },
    { name: "Sea Slide P" },
    { name: "Sea Slide S" },
    { name: "Toy Time 1" },
    { name: "Toy Time 2" },
    { name: "Toy Time 3" },
    { name: "Toy Time C" },
    { name: "Toy Time P" },
    { name: "Toy Time S" },
    { name: "Bonefin" },
    { name: "Bowser Jr.'s Lava Reactor" },
    { name: "Sand Spiral" },
    { name: "Deep Dark 1" },
    { name: "Deep Dark 2" },
    { name: "Deep Dark 3" },
    { name: "Deep Dark C" },
    { name: "Deep Dark P" },
    { name: "Deep Dark S" },
    { name: "Dreadnought 1" },
    { name: "Dreadnought 2" },
    { name: "Dreadnought 3" },
    { name: "Dreadnought C" },
    { name: "Dreadnought P" },
    { name: "Dreadnought S" },
    { name: "Melty Molten 1" },
    { name: "Melty Molten 2" },
    { name: "Melty Molten 3" },
    { name: "Melty Molten C" },
    { name: "Melty Molten P" },
    { name: "Melty Molten S" },
    { name: "Matter Splatter" },
    { name: "Snow Cap" },
    { name: "Gateway 1" },
    { name: "Gateway 2" },
    { name: "Boo's Boneyard" },
    { name: "Bubble Blast" },
    { name: "Rolling Gizmo" },
    { name: "Loopdeeswoop" },
    { name: "Grand Finale" },
    { name: "Any Star from Good Egg" },
    { name: "Any Star from Honeyhive" },
    { name: "Any Star from Space Junk" },
    { name: "Any Star from Battlerock" },
    { name: "Any Star from Beach Bowl" },
    { name: "Any Star from Ghostly" },
    { name: "Any Star from Gusty Garden" },
    { name: "Any Star from Freezeflame" },
    { name: "Any Star from Dusty Dune" },
    { name: "Any Star from Gold Leaf" },
    { name: "Any Star from Sea Slide" },
    { name: "Any Star from Toy Time" },
    { name: "Any Star from Deep Dark" },
    { name: "Any Star from Dreadnought" },
    { name: "Any Star from Melty Molten" },
    { name: "2 Stars from Good Egg" },
    { name: "2 Stars from Honeyhive" },
    { name: "2 Stars from Space Junk" },
    { name: "2 Stars from Battlerock" },
    { name: "2 Stars from Beach Bowl" },
    { name: "2 Stars from Ghostly" },
    { name: "2 Stars from Gusty Garden" },
    { name: "2 Stars from Freezeflame" },
    { name: "2 Stars from Dusty Dune" },
    { name: "2 Stars from Gold Leaf" },
    { name: "2 Stars from Sea Slide" },
    { name: "2 Stars from Toy Time" },
    { name: "2 Stars from Deep Dark" },
    { name: "2 Stars from Dreadnought" },
    { name: "2 Stars from Melty Molten" },
    { name: "3 Stars from Good Egg" },
    { name: "3 Stars from Honeyhive" },
    { name: "3 Stars from Space Junk" },
    { name: "3 Stars from Battlerock" },
    { name: "3 Stars from Beach Bowl" },
    { name: "3 Stars from Ghostly" },
    { name: "3 Stars from Gusty Garden" },
    { name: "3 Stars from Freezeflame" },
    { name: "3 Stars from Dusty Dune" },
    { name: "3 Stars from Gold Leaf" },
    { name: "3 Stars from Sea Slide" },
    { name: "3 Stars from Toy Time" },
    { name: "3 Stars from Deep Dark" },
    { name: "3 Stars from Dreadnought" },
    { name: "3 Stars from Melty Molten" },
    { name: "Get 10 Lives (without using Mailtoad)" },
    { name: "Get 15 Lives (without using Mailtoad)" },
    { name: "Get 20 Lives (without using Mailtoad)" },
    { name: "2 Stars from Trial Galaxies" },
    { name: "3 Stars from Trial Galaxies" },
    { name: "2 Green Stars" },
    { name: "3 Green Stars" },
    { name: "5 Stars (Terrace)" },
    { name: "6 Stars (Terrace)" },
    { name: "7 Stars (Terrace)" },
    { name: "5 Stars (Fountain)" },
    { name: "6 Stars (Fountain)" },
    { name: "7 Stars (Fountain)" },
    { name: "5 Stars (Kitchen)" },
    { name: "6 Stars (Kitchen)" },
    { name: "7 Stars (Kitchen)" },
    { name: "5 Stars (Bedroom)" },
    { name: "6 Stars (Bedroom)" },
    { name: "7 Stars (Bedroom)" },
    { name: "5 Stars (Engine Room)" },
    { name: "6 Stars (Engine Room)" },
    { name: "7 Stars (Engine Room)" },
    { name: "5 Stars (Garden)" },
    { name: "6 Stars (Garden)" },
    { name: "7 Stars (Garden)" },
    { name: "100 Star Bits from any Star" },
    { name: "150 Star Bits from any Star" },
    { name: "200 Star Bits from any Star" },
    { name: "300 Star Bits (Total)" },
    { name: "400 Star Bits (Total)" },
    { name: "500 Star Bits (Total)" }
];
