bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "10+ Energy Tanks",
    "10+ Total Hearts",
    "100+ Missiles",
    "12 Heart Pieces",
    "12+ Total Hearts",
    "2 Crystals",
    "2 Dark World Dungeons",
    "2 Dungeon Blue Rupee Rooms",
    "2 Light World Dungeons",
    "2 Pendants",
    "2+ Reserve Tanks",
    "2+ Reserve Tanks and 2+ Bottles",
    "20 Bombs",
    "20+ Power Bombs and 20+ bombs",
    "25+ Power Bombs",
    "3 A-Items",
    "3 Crystals",
    "3 Dark World Dungeons",
    "3 Light World Dungeons",
    "3 Whirlpool Pairs",
    "3+ Reserve Tanks",
    "30 Bombs",
    "30+ Super Missiles",
    "4 Heart Containers",
    "4 NPC/Object Followers",
    "4+ Energy Tanks and 15+ Power Bombs",
    "40 Arrows",
    "40 Arrows and 20 Bombs",
    "40+ Missiles and 40+ arrows",
    "5+ Energy Tanks",
    "50 Arrows",
    "50+ Missiles",
    "6 Heart Containers",
    "7+ Energy Tanks and 10+ Heart Containers",
    "75+ Missiles",
    "8 Heart Pieces",
    "Activate 4+ Brinstar Save Stations",
    "Activate Both Brinstar Missile Recharge Stations",
    "Activate Both Norfair Energy Recharge Stations",
    "Activate Brinstar, Maridia, and Wrecked Ship Map Stations",
    "Activate Crateria Save Station",
    "Activate Lower Norfair Save Station",
    "Activate Wrecked Ship Map Station",
    "Activate all 3 Brinstar Energy Recharge Stations",
    "Activate all Maridia Save Stations",
    "Activate the Flute",
    "Bomb open a cracked door in any dungeon",
    "Bomb open a cracked floor in any dungeon",
    "Bonk Grave",
    "Bottled Bee",
    "Bottled Faerie",
    "Bottled Potion",
    "Break Bombos Monolith",
    "Break Ether Monolith",
    "Burn a Ball + Chain Trooper",
    "Burn a Floating Stalfos Skull",
    "Buy from 2 Shops in each World",
    "Byrna Cave",
    "Clear 2 Tile Rooms",
    "Collect 11+ Combined Energy Tanks and Reserve Tanks",
    "Collect 50+ Combined Super Missiles and Power Bombs",
    "Collect Charge Beam",
    "Collect Charge Beam, Spazer, Wave Beam, Ice Beam, and Plasma Beam",
    "Collect Grapple Beam",
    "Collect Grapple Beam and Hookshot",
    "Collect Hi-Jump Boots, Speed Booster, and Space Jump",
    "Collect HiJump Boots",
    "Collect Ice Beam",
    "Collect Ice Beam and Ice Rod",
    "Collect Morph Ball Bombs",
    "Collect Plasma Beam",
    "Collect Rod + Cane of opposite colors",
    "Collect Rod + Cane of the same color",
    "Collect Sahasrahla's Prize",
    "Collect Screw Attack",
    "Collect Space Jump",
    "Collect Space Jump and Flute",
    "Collect Spazer Beam",
    "Collect Speed Booster",
    "Collect Speed Booster and Pegasus Boots",
    "Collect Springball",
    "Collect Wave Beam",
    "Collect X-Ray Scope",
    "Collect a Medallion",
    "Collect the Bow",
    "Collect the Hookshot",
    "Collect the Lantern",
    "Complete 1 Line of Y-Items",
    "Darkness Map",
    "Death Mountain Lonely Island",
    "Defeat Agahnim",
    "Defeat Armos",
    "Defeat Arrghus",
    "Defeat Arrghus and Phantoon",
    "Defeat Blind",
    "Defeat Blind and Sporespawn",
    "Defeat Botwoon",
    "Defeat Crocomire",
    "Defeat Crocomire and Draygon",
    "Defeat Crocomire and Ridley",
    "Defeat Draygon",
    "Defeat Golden Torizo",
    "Defeat Golden Torizo and Spore Spawn",
    "Defeat Helmasaur King",
    "Defeat Helmasaur King and Draygon",
    "Defeat Kholdstare",
    "Defeat Kholdstare and Botwoon",
    "Defeat Lanmolas",
    "Defeat Lanmolas and Ridley",
    "Defeat Moldorm",
    "Defeat Mothula",
    "Defeat Mothula and Crocomire",
    "Defeat Ridley",
    "Defeat Spore Spawn",
    "Defeat Spore Spawn and Botwoon",
    "Defeat Trinexx and Kraid",
    "Defeat Vitreous",
    "Defeat Vitreous and Gold Torizo",
    "Defeat a Deadrock",
    "Defeat a Lynel",
    "Defeat a Red Eyegore and Red Mimic",
    "Defeat a snail",
    "Defeat all 6 Freezors",
    "Desert Map",
    "Desert Palace Big Chest",
    "Desert Palace Compass",
    "Destroy at least 1 of the 4 Golden Statues",
    "Destroy at least 2 of the 4 Golden Statues",
    "Die to Trinexx",
    "Finish as a Bunny",
    "Finish at Landing site",
    "Finish in 'Mama Turtle' room",
    "Finish in Grapple Beam room",
    "Finish in Kraid's room",
    "Finish in Metal Pirate room",
    "Finish in Spore Spawn's room",
    "Finish in Springball room",
    "Finish in Wrecked Ship Energy Tank room",
    "Finish in X-Ray Scope room",
    "Finish in a Dark Room",
    "Finish in a Light World Dungeon Fairy Room",
    "Finish in a Prison Cell",
    "Finish in a Room with a Bumper",
    "Finish in a Room with a Firebar",
    "Finish in a Room with a Firesnake",
    "Finish in a Room with an Orange Warp",
    "Finish in a Rupee Floor Room",
    "Finish in a Shinespark or Crystal Flash",
    "Finish in a Trap Room",
    "Finish in an Elevator",
    "Finish near Spazer, Charge Beam, Ice Beam, Wave Beam, or Plasma Beam",
    "Freeze a Bomb Slug",
    "Freeze a Dodongo",
    "Freeze a fireflea",
    "Freeze a space pirate",
    "Freeze a waver",
    "Fully explore the Landing Site",
    "Fully explore the Wrecked Ship",
    "Go bowling",
    "Grapple onto an enemy",
    "Hera Map",
    "Hit Crystal Switch with Frozen Enemy",
    "Ice Map",
    "Ice Palace Big Chest",
    "Ice Palace Compass",
    "Kill Shaktool",
    "Lake Hylia Island",
    "Lantern or Fire Rod",
    "Lumberjack Tree",
    "Master Sword Pedestal",
    "Mimic Cave",
    "Mire Map",
    "Misery Mire Big Chest",
    "Misery Mire Compass",
    "Move or destroy a wall in any dungeon",
    "Norfair Reserve Tank or Wrecked Ship Reserve Tank",
    "Open 4 Small Key Doors (Skull Woods)",
    "Open 5 Small Key Doors (Palace of Darkness)",
    "Open 6 Small Key Doors (Ice Palace)",
    "Open 6 Small Key Doors (Misery Mire)",
    "Open Misery Mire",
    "Open Purple Chest",
    "Open Turtle Rock",
    "Palace of Darkness Big Chest",
    "Palace of Darkness Compass",
    "Pay the Hamburger Helper Hand",
    "Perfect Archery Game",
    "Pull a Tounge Statue",
    "Read 3 Dark World Dungeon Telepathic Tiles",
    "Replace Jeremiah the Blacksmith with Kiki the Monkey",
    "Rescue the Dwarf",
    "Reveal a Hidden Cave under a rock in both Worlds",
    "Skull Map",
    "Skull Woods Big Chest",
    "Skull Woods Compass",
    "Spawn a chest in 2 dungeons",
    "Speak to Fat Faerie",
    "Spend 1000 rupees",
    "Spend 1500 rupees",
    "Stun a Pikit",
    "Stun a Turtle",
    "Swamp Map",
    "Swamp Palace Big Chest",
    "Swamp Palace Compass",
    "TRock Map",
    "Thieves' Map",
    "Thieves' Town Big Chest",
    "Thieves' Town Compass",
    "Tower of Hera Big Chest",
    "Tower of Hera Compass",
    "Turtle Rock Big Chest",
    "Turtle Rock Compass",
    "Upgrade Shield",
    "Upgrade Sword",
    "Visit Crateria-Lake Hylia Portal",
    "Visit Crateria-Maridia Elevator",
    "Visit Grapple Beam Pedestal or Wrecked Ship Energy Tank",
    "Visit Grapple Beam and Speed Booster Pedestal",
    "Visit Lower Norfair Elevator",
    "Visit Lower Norfair-Misery Mire Portal",
    "Visit Maridia-Dark Lake Hylia Portal",
    "Visit Norfair-Death Mountain Portal",
    "Visit Plasma Beam Pedestal or defeat Ridley",
    "Visit Shaktool or defeat Draygon",
    "Visit Spazer and Charge Pedestal",
    "Visit Wave and Ice Pedestal",
    "Visit the Catfish with a Follower",
    "Visit the critters",
    "Visit the front of Gauntlet and Terminator",
    "Visit the front of Gauntlet or X-Ray Pedestal",
    "Visit the left sand pit",
    "Visit the right sand pit"
];
