bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "10 Star Coins",
    "16 Shines",
    "15 Lives",
    "20 Star Coins",
    "24 Shines",
    "3 First Shines in Courses",
    "3 Red Coin Shines",
    "3 Secret Shines in Courses",
    "3 Shines in BM",
    "3 Shines in BoB",
    "3 Shines in BoB Hover Only",
    "3 Shines in HMC",
    "3 Shines in LLL",
    "3 Shines in LLL Hover Only",
    "3 Shines in RR",
    "3 Shines in RR Hover Only",
    "3 Shines in SL",
    "3 Shines in SL Hover Only",
    "3 Shines in SSL",
    "3 Shines in SSL Hover Only",
    "3 Shines in TTC",
    "3 Shines in TTC Hover Only",
    "3 Shines in TTM",
    "3 Shines in WDW",
    "3 Shines in WDW Hover Only",
    "3 Silver Stars Shines",
    "3 Star Coins in BM",
    "3 Star Coins in BoB",
    "3 Star Coins in Bowser Courses",
    "3 Star Coins in Castle Secret Shines",
    "3 Star Coins in HMC",
    "3 Star Coins in LLL",
    "3 Star Coins in RR",
    "3 Star Coins in SL",
    "3 Star Coins in SSL",
    "3 Star Coins in TTC",
    "3 Star Coins in TTM",
    "3 Star Coins in WDW",
    "3 Mini-Boss Shines",
    "8 Shines in Basement",
    "8 Shines in Lobby",
    "8 Shines in Upstairs",
    "All Powerup Stars",
    "Bowser 1 Red Coins",
    "Bowser 2 Red Coins",
    "LLL Secret Fluddless",
    "RR Secret",
    "BM King Boo",
    "Lobby Castle Secret Shines",
    "Basement Castle Secret Shines",
    "Upstairs Castle Secret Shines",
];


    
