(function(j, i, g, m, k, n, o) {
    function q(b) {
        var e, f, a = this,
            c = b.length,
            d = 0,
            h = a.i = a.j = a.m = 0;
        a.S = [];
        a.c = [];
        for (c || (b = [c++]); d < g;) a.S[d] = d++;
        for (d = 0; d < g; d++) e = a.S[d], h = h + e + b[d % c] & g - 1, f = a.S[h], a.S[d] = f, a.S[h] = e;
        a.g = function(b) {
            var c = a.S,
                d = a.i + 1 & g - 1,
                e = c[d],
                f = a.j + e & g - 1,
                h = c[f];
            c[d] = h;
            c[f] = e;
            for (var i = c[e + h & g - 1]; --b;) d = d + 1 & g - 1, e = c[d], f = f + e & g - 1, h = c[f], c[d] = h, c[f] = e, i = i * g + c[e + h & g - 1];
            a.i = d;
            a.j = f;
            return i
        };
        a.g(g)
    }

    function p(b, e, f, a, c) {
        f = [];
        c = typeof b;
        if (e && c == "object")
            for (a in b)
                if (a.indexOf("S") < 5) try {
                    f.push(p(b[a], e - 1))
                } catch (d) {}
                return f.length ? f : b + (c != "string" ? "\0" : "")
    }

    function l(b, e, f, a) {
        b += "";
        for (a = f = 0; a < b.length; a++) {
            var c = e,
                d = a & g - 1,
                h = (f ^= e[a & g - 1] * 19) + b.charCodeAt(a);
            c[d] = h & g - 1
        }
        b = "";
        for (a in e) b += String.fromCharCode(e[a]);
        return b
    }
    i.seedrandom = function(b, e) {
        var f = [],
            a;
        b = l(p(e ? [b, j] : arguments.length ? b : [(new Date).getTime(), j, window], 3), f);
        a = new q(f);
        l(a.S, j);
        i.random = function() {
            for (var c = a.g(m), d = o, b = 0; c < k;) c = (c + b) * g, d *= g, b = a.g(1);
            for (; c >= n;) c /= 2, d /= 2, b >>>= 1;
            return (c + b) / d
        };
        return b
    };
    o = i.pow(g, m);
    k = i.pow(2, k);
    n = k * 2;
    l(i.random(), j)
})([], Math, 256, 6, 52);

bingoGenerator = function(bingoList, opts) {
    var LANG = opts.lang || 'name';
    var MODE = opts.mode || "normal";
    var cardType = "Normal";
    var SEED = opts.seed || Math.ceil(999999 * Math.random()).toString();
    var size = 5;

    // simpler generator that just does a random choice without duplicates
    Math.seedrandom(SEED);
    if (true) {
        var usedGoals = {};
        var bingoBoard = [];

        for (var i = 1; i <= 25; i++) {
            var randIndex = Math.floor(Math.random() * bingoList.length);
            while (usedGoals[randIndex]) {
                randIndex = Math.floor(Math.random() * bingoList.length);
            }
            usedGoals[randIndex] = true;

            var goal = bingoList[randIndex];
            bingoBoard[i] = {"name": goal};
        }

        return bingoBoard;
    }
};

var bingoList = [
    "1 Moon from Picture-Match",
    "1 Multi Moon (Dark Side)",
    "1 Souvenir (Bowser's)",
    "1 Souvenir (Cap)",
    "1 Souvenir (Cascade)",
    "1 Souvenir (Lake)",
    "1 Souvenir (Lost)",
    "1 Souvenir (Luncheon)",
    "1 Souvenir (Metro)",
    "1 Souvenir (Moon)",
    "1 Souvenir (Mushroom)",
    "1 Souvenir (Sand)",
    "1 Souvenir (Seaside)",
    "1 Souvenir (Snow)",
    "1 Souvenir (Wooded)",
    "10 Checkpoints (Bowser's)",
    "10 Moons (Cap)",
    "10 Moons (Dark Side)",
    "10 Moons (Moon)",
    "10 Moons (Mushroom)",
    "10 Moons (Toadette)",
    "10 Moons from 8-bit Sections",
    "10 Moons from Moon Shards",
    "10 Moons from Music Notes",
    "10 Moons from Timer Challenges",
    "10 Moons from sub-areas (Luncheon)",
    "10 Moons from sub-areas (Metro)",
    "10 Moons from sub-areas (Sand)",
    "10 Moons from sub-areas (Wooded)",
    "10 Multi Moons",
    "11 Moons from Moon Shards",
    "11 Moons from Music Note",
    "11 Moons from Nuts",
    "11 Moons from Timer Challenges",
    "11 Multi Moons",
    "12 Moons from Moon Shards",
    "12 Moons from Music Note",
    "12 Moons from Nuts",
    "12 Moons from Timer Challenges",
    "12 Moons from sub-areas (Metro)",
    "13 Moons from Nuts",
    "13 Moons from Timer Challenges",
    "14 Moons from Nuts",
    "14 Moons from sub-areas (Metro)",
    "15 Moons (Cap)",
    "15 Moons (Cascade)",
    "15 Moons (Dark Side)",
    "15 Moons (Lake)",
    "15 Moons (Moon)",
    "15 Moons (Mushroom)",
    "15 Moons (Toadette)",
    "2 Checkpoints (Cap)",
    "2 Moons from Fishing",
    "2 Moons from Golden Turnips",
    "2 Moons from Koopa Trace-Walking",
    "2 Moons from Lochlady Sisters (Lake)",
    "2 Moons from Picture-Match",
    "2 Moons from Slots",
    "2 Moons from sub-areas (Dark Side)",
    "2 Moons from sub-areas (Snow)",
    "2 Multi Moons (Mushroom)",
    "2 Souvenirs (Bowser's)",
    "2 Souvenirs (Cap)",
    "2 Souvenirs (Cascade)",
    "2 Souvenirs (Lake)",
    "2 Souvenirs (Lost)",
    "2 Souvenirs (Luncheon)",
    "2 Souvenirs (Metro)",
    "2 Souvenirs (Moon)",
    "2 Souvenirs (Mushroom)",
    "2 Souvenirs (Sand)",
    "2 Souvenirs (Seaside)",
    "2 Souvenirs (Snow)",
    "2 Souvenirs (Wooded)",
    "20 Moons (Bowser's)",
    "20 Moons (Cap)",
    "20 Moons (Cascade)",
    "20 Moons (Lake)",
    "20 Moons (Lost)",
    "20 Moons (Moon)",
    "20 Moons (Mushroom)",
    "20 Moons (Snow)",
    "20 Moons (Toadette)",
    "20 Moons from sub-areas (Total)",
    "20 Regional Coins (Bowser's)",
    "20 Regional Coins (Cap)",
    "20 Regional Coins (Cascade)",
    "20 Regional Coins (Lake)",
    "20 Regional Coins (Lost)",
    "20 Regional Coins (Luncheon)",
    "20 Regional Coins (Metro)",
    "20 Regional Coins (Moon)",
    "20 Regional Coins (Mushroom)",
    "20 Regional Coins (Sand)",
    "20 Regional Coins (Seaside)",
    "20 Regional Coins (Snow)",
    "20 Regional Coins (Wooded)",
    "200 Total Regional Coins",
    "22 Moons from sub-areas (Total)",
    "24 Moons from sub-areas (Total)",
    "25 Moons (Bowser's)",
    "25 Moons (Cascade)",
    "25 Moons (Lake)",
    "25 Moons (Lost)",
    "25 Moons (Moon)",
    "25 Moons (Mushroom)",
    "25 Moons (Snow)",
    "25 Moons (Toadette)",
    "250 Total Regional Coins",
    "26 Moons from sub-areas (Total)",
    "28 Moons from sub-areas (Total)",
    "3 Checkpoints (Cascade)",
    "3 Checkpoints (Lost)",
    "3 Checkpoints (Moon)",
    "3 Checkpoints (Mushroom)",
    "3 Checkpoints (Snow)",
    "3 Moons (Cloud)",
    "3 Moons from Fishing",
    "3 Moons from Golden Turnips",
    "3 Moons from Koopa Trace-Walking",
    "3 Moons from Lochlady Sisters (Lake)",
    "3 Moons from Slots",
    "3 Multi Moons (Mushroom)",
    "30 Moons (Bowser's)",
    "30 Moons (Cascade)",
    "30 Moons (Lake)",
    "30 Moons (Lost)",
    "30 Moons (Luncheon)",
    "30 Moons (Mushroom)",
    "30 Moons (Sand)",
    "30 Moons (Snow)",
    "30 Moons (Toadette)",
    "30 Moons (Wooded)",
    "30 Moons from sub-areas (Total)",
    "30 Regional Coins (Bowser's)",
    "30 Regional Coins (Cap)",
    "30 Regional Coins (Cascade)",
    "30 Regional Coins (Lake)",
    "30 Regional Coins (Lost)",
    "30 Regional Coins (Luncheon)",
    "30 Regional Coins (Metro)",
    "30 Regional Coins (Moon)",
    "30 Regional Coins (Mushroom)",
    "30 Regional Coins (Sand)",
    "30 Regional Coins (Seaside)",
    "30 Regional Coins (Snow)",
    "30 Regional Coins (Wooded)",
    "300 Total Regional Coins",
    "35 Moons (Bowser's)",
    "35 Moons (Luncheon)",
    "35 Moons (Metro)",
    "35 Moons (Sand)",
    "35 Moons (Snow)",
    "35 Moons (Wooded)",
    "350 Total Regional Coins",
    "4 Barrier-Moons (Snow)",
    "4 Checkpoints (Cascade)",
    "4 Checkpoints (Moon)",
    "4 Fountain-Moons (Seaside)",
    "4 Moons from Fishing",
    "4 Moons from Koopa Freerunning",
    "4 Moons from Koopa Trace-Walking",
    "4 Moons from Musicians (Metro)",
    "4 Moons from Seeds",
    "4 Moons from sub-areas (Bowser's)",
    "4 Moons from sub-areas (Cap)",
    "4 Moons from sub-areas (Cascade)",
    "4 Moons from sub-areas (Dark Side)",
    "4 Moons from sub-areas (Lake)",
    "4 Moons from sub-areas (Seaside)",
    "4 Moons from sub-areas (Snow)",
    "4 Moons from sub-areas (Wooded)",
    "4 Multi Moons (Mushroom)",
    "40 Moons (Bowser's)",
    "40 Moons (Luncheon)",
    "40 Moons (Metro)",
    "40 Moons (Sand)",
    "40 Moons (Seaside)",
    "40 Moons (Snow)",
    "40 Moons (Wooded)",
    "40 Regional Coins (Bowser's)",
    "40 Regional Coins (Cap)",
    "40 Regional Coins (Cascade)",
    "40 Regional Coins (Lake)",
    "40 Regional Coins (Lost)",
    "40 Regional Coins (Luncheon)",
    "40 Regional Coins (Metro)",
    "40 Regional Coins (Moon)",
    "40 Regional Coins (Mushroom)",
    "40 Regional Coins (Sand)",
    "40 Regional Coins (Seaside)",
    "40 Regional Coins (Snow)",
    "40 Regional Coins (Wooded)",
    "400 Total Regional Coins",
    "45 Moons (Bowser's)",
    "45 Moons (Luncheon)",
    "45 Moons (Metro)",
    "45 Moons (Sand)",
    "45 Moons (Seaside)",
    "45 Moons (Snow)",
    "45 Moons (Wooded)",
    "450 Total Regional Coins",
    "5 Checkpoints (Lake)",
    "5 Checkpoints (Luncheon)",
    "5 Moons (Cap)",
    "5 Moons (Cloud)",
    "5 Moons (Dark Side)",
    "5 Moons (Deep Woods)",
    "5 Moons (Ruined)",
    "5 Moons (Toadette)",
    "5 Moons from Hint Art",
    "5 Moons from Koopa Freerunning",
    "5 Moons from Peach",
    "5 Moons from Seeds",
    "5 Stickers",
    "5 Warp-Painting Moons",
    "50 Moons (Bowser's)",
    "50 Moons (Luncheon)",
    "50 Moons (Metro)",
    "50 Moons (Sand)",
    "50 Moons (Seaside)",
    "50 Moons (Wooded)",
    "50 Regional Coins (Bowser's)",
    "50 Regional Coins (Luncheon)",
    "50 Regional Coins (Metro)",
    "50 Regional Coins (Mushroom)",
    "50 Regional Coins (Sand)",
    "50 Regional Coins (Seaside)",
    "50 Regional Coins (Wooded)",
    "500 Total Regional Coins",
    "55 Moons (Luncheon)",
    "55 Moons (Metro)",
    "55 Moons (Sand)",
    "55 Moons (Seaside)",
    "55 Moons (Wooded)",
    "6 Captain Toad Moons",
    "6 Checkpoints (Lake)",
    "6 Checkpoints (Luncheon)",
    "6 Checkpoints (Metro)",
    "6 Checkpoints (Sand)",
    "6 Checkpoints (Seaside)",
    "6 Checkpoints (Wooded)",
    "6 Moons (Deep Woods)",
    "6 Moons (Ruined)",
    "6 Moons from Goombette",
    "6 Moons from Hint Art",
    "6 Moons from Koopa Freerunning",
    "6 Moons from Peach",
    "6 Moons from Seeds",
    "6 Moons from sub-areas (Bowser's)",
    "6 Moons from sub-areas (Cap)",
    "6 Moons from sub-areas (Cascade)",
    "6 Moons from sub-areas (Dark Side)",
    "6 Moons from sub-areas (Luncheon)",
    "6 Moons from sub-areas (Metro)",
    "6 Moons from sub-areas (Sand)",
    "6 Moons from sub-areas (Seaside)",
    "6 Moons from sub-areas (Wooded)",
    "6 Stickers",
    "6 Warp-Painting Moons",
    "60 Moons (Metro)",
    "60 Moons (Sand)",
    "60 Moons (Wooded)",
    "60 Regional Coins (Bowser's)",
    "60 Regional Coins (Luncheon)",
    "60 Regional Coins (Metro)",
    "60 Regional Coins (Mushroom)",
    "60 Regional Coins (Sand)",
    "60 Regional Coins (Seaside)",
    "60 Regional Coins (Wooded)",
    "65 Moons (Metro)",
    "65 Moons (Sand)",
    "65 Moons (Wooded)",
    "7 Captain Toad Moons",
    "7 Checkpoints (Luncheon)",
    "7 Checkpoints (Metro)",
    "7 Checkpoints (Sand)",
    "7 Checkpoints (Seaside)",
    "7 Checkpoints (Wooded)",
    "7 Moons (Cloud)",
    "7 Moons (Deep Woods)",
    "7 Moons (Ruined)",
    "7 Moons from Goombette",
    "7 Moons from Hint Art",
    "7 Moons from Koopa Freerunning",
    "7 Moons from Peach",
    "7 Moons from Seeds",
    "7 Stickers",
    "7 Warp-Painting Moons",
    "70 Moons (Sand)",
    "70 Regional Coins (Bowser's)",
    "70 Regional Coins (Luncheon)",
    "70 Regional Coins (Metro)",
    "70 Regional Coins (Mushroom)",
    "70 Regional Coins (Sand)",
    "70 Regional Coins (Seaside)",
    "70 Regional Coins (Wooded)",
    "8 Captain Toad Moons",
    "8 Checkpoints (Metro)",
    "8 Checkpoints (Sand)",
    "8 Checkpoints (Seaside)",
    "8 Checkpoints (Wooded)",
    "8 Moons (Deep Woods)",
    "8 Moons (Ruined)",
    "8 Moons from 8-bit Sections",
    "8 Moons from Goombette",
    "8 Moons from Hint Art",
    "8 Moons from Moon Shards",
    "8 Moons from Peach",
    "8 Moons from Seeds",
    "8 Moons from sub-areas (Bowser's)",
    "8 Moons from sub-areas (Luncheon)",
    "8 Moons from sub-areas (Metro)",
    "8 Moons from sub-areas (Sand)",
    "8 Moons from sub-areas (Wooded)",
    "8 Stickers",
    "9 Captain Toad Moons",
    "9 Checkpoints (Bowser's)",
    "9 Checkpoints (Metro)",
    "9 Moons from 8-bit Sections",
    "9 Moons from Goombette",
    "9 Moons from Hint Art",
    "9 Moons from Moon Shards",
    "9 Moons from Music Notes",
    "9 Moons from Peach",
    "9 Multi Moons",
    "A Request from the Mayor (Metro)",
    "Answer 10 Sphynx Questions Correctly",
    "Answer 6 Sphynx Questions Correctly",
    "Answer 8 Sphynx Questions Correctly",
    "Beach Volleyball: Champ! (Seaside)",
    "Bonneter Hat-and-Seek (Luncheon)",
    "Bonneter Hat-and-Seek (Metro)",
    "Bonneter Hat-and-Seek (Mushroom)",
    "Bonneter Hat-and-Seek (Sand)",
    "Bonneter Hat-and-Seek (Snow)",
    "Bonneter Scientist (Bowser's)",
    "Bonneter Scientist (Lost)",
    "Bonneter Scientist (Snow)",
    "Bonneter Scientist (Wooded)",
    "Bowser's Kingdom Hint Art",
    "Bowser's Kingdom Sticker",
    "Call Jaxi from 3 Stands",
    "Call Jaxi from 4 Stands",
    "Call Jaxi from 5 Stands",
    "Cap Kingdom Hint Art",
    "Cap Kingdom Sticker",
    "Captain Toad (Bowser's)",
    "Captain Toad (Cap)",
    "Captain Toad (Cascade)",
    "Captain Toad (Dark Side)",
    "Captain Toad (Lake)",
    "Captain Toad (Lost)",
    "Captain Toad (Luncheon)",
    "Captain Toad (Metro)",
    "Captain Toad (Moon)",
    "Captain Toad (Mushroom)",
    "Captain Toad (Sand)",
    "Captain Toad (Seaside)",
    "Captain Toad (Snow)",
    "Captain Toad (Wooded)",
    "Cascade Kingdom Sticker",
    "Catch the Rabbit (Seaside)",
    "Catch the Rabbit! (Cap)",
    "Catch the Rabbit! (Cascade Kingdom)",
    "Catch the Rabbit! (Lost)",
    "Catch the Rabbit! (Luncheon)",
    "Catch the Rabbit! (Moon)",
    "Catch the Rabbit! (Mushroom)",
    "Catch the Rabbit! (Sand)",
    "Catch the Rabbit! (Snow)",
    "Catch! the Rabbit (Bowser's)",
    "Caveman Cave-Fan (Cascade)",
    "Dark Side Hint Art x2",
    "Dark Side Hint Art x3",
    "Dark Side Hint Art x4",
    "Dark Side Hint Art x5",
    "Dark Side Hint Art x6",
    "Flying Sphynx (Bowser's)",
    "Flying Sphynx (Cascade)",
    "Flying Sphynx (Metro)",
    "Flying Taxi (Cap)",
    "Flying Taxi (Lake)",
    "Flying Taxi (Lost)",
    "Have 1000 Coins",
    "Have 1250 Coins",
    "Have 1500 Coins",
    "Have 1750 Coins",
    "Have 2000 Coins",
    "Herding Sheep at Peach's Castle! (Mushroom)",
    "Herding Sheep in the Dunes (Sand)",
    "Iceburn Circuit Class A (Snow)",
    "Iceburn Circuit Class S (Snow)",
    "Jump-Rope Hero (Metro)",
    "Koopa Freerunning (Bowser's)",
    "Koopa Freerunning (Cap)",
    "Koopa Freerunning (Cascade)",
    "Koopa Freerunning (Lake)",
    "Koopa Freerunning (Lost)",
    "Koopa Freerunning (Luncheon)",
    "Koopa Freerunning (Metro)",
    "Koopa Freerunning (Moon)",
    "Koopa Freerunning (Mushroom)",
    "Koopa Freerunning (Sand)",
    "Koopa Freerunning (Seaside)",
    "Koopa Freerunning (Snow)",
    "Koopa Freerunning (Wooded)",
    "Lake Kingdom Hint Art",
    "Lake Kingdom Sticker",
    "Lakitu-Fishing (Bowser's)",
    "Lakitu-Fishing (Lake)",
    "Lakitu-Fishing (Sand)",
    "Lakitu-Fishing (Snow)",
    "Lost Kingdom Sticker",
    "Luncheon Kingdom Hint Art",
    "Luncheon Kingdom Sticker",
    "Metro Kingdom Hint Art",
    "Metro Kingdom Sticker",
    "Moon Kingdom Hint Art",
    "Moon Kingdom Sticker",
    "Mushroom Kingdom Hint Art",
    "Mushroom Kingdom Sticker",
    "Music-Toad (Luncheon)",
    "Music-Toad (Metro)",
    "Music-Toad (Mushroom)",
    "Music-Toad (Sand)",
    "Music-Toad (Wooded)",
    "Outfit-Door (Bowser's)",
    "Outfit-Door (Luncheon Kingdom)",
    "Outfit-Door (Metro)",
    "Outfit-Door (Mushroom)",
    "Outfit-Door (Sand)",
    "Outfit-Door (Seaside)",
    "Outfit-Door (Snow Kingdom)",
    "Outfit-Door (Wooded)",
    "Peach in Bowser's Kingdom",
    "Peach in the Cap Kingdom",
    "Peach in the Cascade Kingdom",
    "Peach in the Cloud Kingdom",
    "Peach in the Lake Kingdom",
    "Peach in the Lost Kingdom",
    "Peach in the Luncheon Kingdom",
    "Peach in the Metro Kingdom",
    "Peach in the Moon Kingdom",
    "Peach in the Mushroom Kingdom",
    "Peach in the Ruined Kingdom",
    "Peach in the Sand Kingdom",
    "Peach in the Seaside Kingdom",
    "Peach in the Snow Kingdom",
    "Peach in the Wooded Kingdom",
    "Plant 7 Seeds",
    "Plant 8 Seeds",
    "Plant 9 Seeds",
    "Power Moon in the City! Good Dog!",
    "Power Moon in the Desert! Good Dog!",
    "Power Moon on the Moon! Good Dog!",
    "Power Moon on the Seaside! Good Dog!",
    "Purchase 10 Full Costume Sets",
    "Purchase 7 Full Costume Sets",
    "Purchase 8 Full Costume Sets",
    "Purchase 9 Full Costume Sets",
    "Purchase a Moon (Bowser's)",
    "Purchase a Moon (Cap)",
    "Purchase a Moon (Cascade)",
    "Purchase a Moon (Lake)",
    "Purchase a Moon (Lost)",
    "Purchase a Moon (Luncheon)",
    "Purchase a Moon (Metro)",
    "Purchase a Moon (Moon)",
    "Purchase a Moon (Mushroom)",
    "Purchase a Moon (Sand)",
    "Purchase a Moon (Seaside)",
    "Purchase a Moon (Snow)",
    "Purchase a Moon (Wooded)",
    "Sand Kingdom Hint Art",
    "Sand Kingdom Sticker",
    "Seaside Kingdom Hint Art",
    "Seaside Kingdom Sticker",
    "Secret Path to Bowser's Castle!",
    "Secret Path to Bubblaine!",
    "Secret Path to Fossil Falls!",
    "Secret Path to Lake Lamode!",
    "Secret Path to Mount Volbono!",
    "Secret Path to New Donk City!",
    "Secret Path to Shiveria!",
    "Secret Path to Tostarena!",
    "Secret Path to the Steam Gardens!",
    "Showdown on the Inverted Pyramid! (Sand)",
    "Snow Kingdom Hint Art",
    "Snow Kingdom Sticker",
    "Snowline Circuit Class S (Snow)",
    "Tostarena-Tourist (Cascade)",
    "Tostarena-Tourist (Luncheon)",
    "Tostarena-Tourist (Metro)",
    "Tostarena-Tourist (Moon)",
    "Tostarena-Tourist (Mushroom)",
    "Tostarena-Tourist (Sand)",
    "Uncork 3 Fountains (Seaside)",
    "Uncork 4 Fountains (Seaside)",
    "Wooded Kingdom Hint Art",
    "Wooded Kingdom Sticker",
    "World Peace Restored! (Luncheon)",
    "World Peace Restored! (Metro)",
    "World Peace Restored! (Sand)",
    "World Peace Restored! (Seaside)",
    "World Peace Restored! (Snow)",
    "World Peace Restored! (Wooded)"
];
