bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "All-Star All Difficulties - Complete with a Character of your choice",
    "All-Star Easy - Complete with a Randomized Character, No Continue",
    "All-Star Easy - Complete with all characters in a horizontal Row (4th Row you must use Random)",
    "All-Star Hard - Complete with a Randomized Character No Continue",
    "All-Star Intense - Complete with a Character of your choice",
    "All-Star Intense - Complete with a Randomized Character",
    "Battleship Halberd Interior - Complete on Intense",
    "Beat Porky - Complete Subspace on any Difficulty up to defeating Porkey (New File)",
    "Beat Raquaza - Complete Subspace on any Difficulty up to defeating Raquaza (New File)",
    "Boss Battle Intense - Complete with a Character of your choice",
    "Boss Battles Easy - Complete with a Randomized Character x3",
    "Boss Battles Easy - Complete with all characters in a horizontal Row (4th Row you must use Random)",
    "Boss Battles Hard - Complete with a Randomized Character x2",
    "Boss Battles Intense - Complete with a Randomized Character",
    "Classic All Difficulties - Complete with a Character of your choice",
    "Classic All Difficulties - Complete with a Randomized Character",
    "Classic Easy - Complete with a Randomized Character, 1 Stock",
    "Classic Easy - Complete with all characters in a horizontal Row (4th Row you must use Random)",
    "Classic Hard - Complete with a Randomized Character, 2 Stock",
    "Classic Intense - Complete with a Character of your choice",
    "Classic Intense - Complete with a Randomized Character",
    "Do Events 1-20",
    "Do Events 11-30",
    "Do Events 21-41",
    "Do any 15 Events on Hard",
    "Do any 20 Events on Normal",
    "Do any 25 Events",
    "Homerun Contest All Characters - Complete (All Characters must have a score greater than 1000ft/305 meters)",
    "Multiman Brawl 10 Man Brawl All Characters - Complete",
    "Multiman Brawl 100 Man Brawl - Complete with Randomized Character x5",
    "Multiman Brawl Cruel Brawl - 10 Kills",
    "Multiman Brawl Endless Brawl - 200 Kills",
    "Subspace - Complete Any 10 Stages on Intense only",
    "Subspace - Complete Any 15 Stages",
    "Subspace - Complete Any 20 Stages",
    "Subspace - Complete Any 20 Stages on Easy only",
    "Subspace - Complete Any 25 Stages",
    "Subspace - Turn 4 Bosses into Trophies",
    "Subspace - Turn Meta Ridley into a Trophy",
    "Subspace - Turn Tabuu into a Trophy",
    "Target Test 1 All Characters - Complete",
    "Target Test 2 All Characters - Complete",
    "Target Test 3 - 18 Characters",
    "Target Test 4 - 15 Characters",
    "Target Test 5 - 18 Characters",
    "Target Test All Difficulties - Random Characters, Complete x5",
    "The Battlefield Fortress - Complete on Intense",
    "The Glacial Peak - Complete on Intense",
    "The Research Facility 2 - Complete on Intense",
    "The Ruins - Complete on Intense, No Wolf Door",
    "The Subspace Bomb Factory 2 - Complete on Intense",
    "The Swamp - Complete on Intense, No Jigglypuff Door",
    "Vs Mode - Random Characters, Level 9, 2 Stock, 10 Stages, Win the Fights, No Items, No Timer",
    "Vs Mode - Random Characters, Level 9, 2 Stock, 15 Stages, Win the Fights, No Items, No Timer"
];
