bingoGenerator = require("./generators/generator_bases/ladx_generator.js");

var bingoList = [
    { "name": "Good Egg 1" },
    { "name": "Good Egg 2" },
    { "name": "Good Egg 3" },
    { "name": "Good Egg C", "group": "Speedy" },
    { "name": "Good Egg P", "group": "Purple" },
    { "name": "Good Egg L", "group": "Luigi" },
    { "name": "Honeyhive 1" },
    { "name": "Honeyhive 2" },
    { "name": "Honeyhive 3" },
    { "name": "Honeyhive C", "group": "Cosmic" },
    { "name": "Honeyhive P", "group": "Purple" },
    { "name": "Honeyhive L", "group": "Luigi" },
    { "name": "Loopdeeloop" },
    { "name": "Flipswitch" },
    { "name": "Bowser Jr.'s Robot Reactor", "group": "GrandStar" },
    { "name": "Sweet Sweet", "group": "LumaGalaxy" },
    { "name": "Space Junk 1" },
    { "name": "Space Junk 2" },
    { "name": "Space Junk 3" },
    { "name": "Space Junk C", "group": "Speedy" },
    { "name": "Space Junk P", "group": "Purple" },
    { "name": "Space Junk S" },
    { "name": "Battlerock 1" },
    { "name": "Battlerock 2" },
    { "name": "Battlerock 3" },
    { "name": "Battlerock C", "group": "Daredevil" },
    { "name": "Battlerock P", "group": "Purple" },
    { "name": "Battlerock S" },
    { "name": "Battlerock L", "group": "Luigi" },
    { "name": "Rolling Green" },
    { "name": "Hurry-Scurry" },
    { "name": "Bowser's Star Reactor", "group": "GrandStar" },
    { "name": "Sling Pod", "group": "LumaGalaxy" },
    { "name": "Beach Bowl 1" },
    { "name": "Beach Bowl 2" },
    { "name": "Beach Bowl 3" },
    { "name": "Beach Bowl C", "group": "FastFoe" },
    { "name": "Beach Bowl P", "group": "Purple" },
    { "name": "Beach Bowl S" },
    { "name": "Ghostly 1", "group": "Luigi" },
    { "name": "Ghostly 2" },
    { "name": "Ghostly 3" },
    { "name": "Ghostly C", "group": "Daredevil" },
    { "name": "Ghostly P", "group": "Purple" },
    { "name": "Ghostly S" },
    { "name": "Bubble Breeze" },
    { "name": "Buoy Base 1" },
    { "name": "Buoy Base S" },
    { "name": "Bowser Jr.'s Airship Armada", "group": "GrandStar" },
    { "name": "Drip Drop", "group": "LumaGalaxy" },
    { "name": "Gusty Garden 1" },
    { "name": "Gusty Garden 2" },
    { "name": "Gusty Garden 3" },
    { "name": "Gusty Garden C", "group": "Daredevil" },
    { "name": "Gusty Garden P", "group": "Purple" },
    { "name": "Gusty Garden S" },
    { "name": "Freezeflame 1" },
    { "name": "Freezeflame 2" },
    { "name": "Freezeflame 3" },
    { "name": "Freezeflame C", "group": "Cosmic" },
    { "name": "Freezeflame P", "group": "Purple" },
    { "name": "Freezeflame S" },
    { "name": "Dusty Dune 1" },
    { "name": "Dusty Dune 2" },
    { "name": "Dusty Dune 3" },
    { "name": "Dusty Dune C", "group": "Speedy" },
    { "name": "Dusty Dune P", "group": "Purple" },
    { "name": "Dusty Dune S" },
    { "name": "Dusty Dune G" },
    { "name": "Honeyclimb" },
    { "name": "Bowser's Dark Matter Plant", "group": "GrandStar" },
    { "name": "Bigmouth", "group": "LumaGalaxy" },
    { "name": "Gold Leaf 1" },
    { "name": "Gold Leaf 2" },
    { "name": "Gold Leaf 3" },
    { "name": "Gold Leaf C", "group": "Cosmic" },
    { "name": "Gold Leaf P", "group": "Purple" },
    { "name": "Gold Leaf S" },
    { "name": "Sea Slide 1" },
    { "name": "Sea Slide 2" },
    { "name": "Sea Slide 3" },
    { "name": "Sea Slide C", "group": "Cosmic" },
    { "name": "Sea Slide P", "group": "Purple" },
    { "name": "Sea Slide S" },
    { "name": "Toy Time 1" },
    { "name": "Toy Time 2" },
    { "name": "Toy Time 3" },
    { "name": "Toy Time C", "group": "FastFoe" },
    { "name": "Toy Time P", "group": "Purple" },
    { "name": "Toy Time S" },
    { "name": "Bonefin" },
    { "name": "Bowser Jr.'s Lava Reactor", "group": "GrandStar" },
    { "name": "Sand Spiral", "group": "LumaGalaxy" },
    { "name": "Deep Dark 1" },
    { "name": "Deep Dark 2" },
    { "name": "Deep Dark 3" },
    { "name": "Deep Dark C", "group": "Daredevil" },
    { "name": "Deep Dark P", "group": "Purple" },
    { "name": "Deep Dark S" },
    { "name": "Dreadnought 1" },
    { "name": "Dreadnought 2" },
    { "name": "Dreadnought 3" },
    { "name": "Dreadnought C", "group": "Speedy" },
    { "name": "Dreadnought P", "group": "Purple" },
    { "name": "Dreadnought S" },
    { "name": "Melty Molten 1" },
    { "name": "Melty Molten 2" },
    { "name": "Melty Molten 3" },
    { "name": "Melty Molten C", "group": "Daredevil" },
    { "name": "Melty Molten P", "group": "Purple" },
    { "name": "Melty Molten S" },
    { "name": "Matter Splatter" },
    { "name": "Snow Cap", "group": "LumaGalaxy" },
    { "name": "Gateway 1", "group": "GrandStar" },
    { "name": "Gateway 2", "group": "Purple" },
    { "name": "Boo's Boneyard", "group": "LumaGalaxy" },
    { "name": "Bubble Blast", "group": "Trial" },
    { "name": "Rolling Gizmo", "group": "Trial" },
    { "name": "Loopdeeswoop", "group": "Trial" },
    { "name": "Grand Finale" },
    { "name": "2 Stars from Good Egg", "group": "GoodEgg" },
    { "name": "2 Stars from Honeyhive", "group": "Honeyhive" },
    { "name": "2 Stars from Space Junk", "group": "SpaceJunk" },
    { "name": "2 Stars from Battlerock", "group": "Battlerock" },
    { "name": "2 Stars from Beach Bowl", "group": "BeachBowl" },
    { "name": "2 Stars from Ghostly", "group": "Ghostly" },
    { "name": "2 Stars from Gusty Garden", "group": "GustyGarden" },
    { "name": "2 Stars from Freezeflame", "group": "Freezeflame" },
    { "name": "2 Stars from Dusty Dune", "group": "DustyDune" },
    { "name": "2 Stars from Gold Leaf", "group": "GoldLeaf" },
    { "name": "2 Stars from Sea Slide", "group": "SeaSlide" },
    { "name": "2 Stars from Toy Time", "group": "ToyTime" },
    { "name": "2 Stars from Deep Dark", "group": "DeepDark" },
    { "name": "2 Stars from Dreadnought", "group": "Dreadnought" },
    { "name": "2 Stars from Melty Molten", "group": "MeltyMolten" },
    { "name": "3 Stars from Good Egg", "group": "GoodEgg" },
    { "name": "3 Stars from Honeyhive", "group": "Honeyhive" },
    { "name": "3 Stars from Space Junk", "group": "SpaceJunk" },
    { "name": "3 Stars from Battlerock", "group": "Battlerock" },
    { "name": "3 Stars from Beach Bowl", "group": "BeachBowl" },
    { "name": "3 Stars from Ghostly", "group": "Ghostly" },
    { "name": "3 Stars from Gusty Garden", "group": "GustyGarden" },
    { "name": "3 Stars from Freezeflame", "group": "Freezeflame" },
    { "name": "3 Stars from Dusty Dune", "group": "DustyDune" },
    { "name": "3 Stars from Gold Leaf", "group": "GoldLeaf" },
    { "name": "3 Stars from Sea Slide", "group": "SeaSlide" },
    { "name": "3 Stars from Toy Time", "group": "ToyTime" },
    { "name": "3 Stars from Deep Dark", "group": "DeepDark" },
    { "name": "2 Stars from Dreadnought", "group": "Dreadnought" },
    { "name": "3 Stars from Melty Molten", "group": "MeltyMolten" },
    { "name": "4 Stars from Good Egg", "group": "GoodEgg" },
    { "name": "4 Stars from Honeyhive", "group": "Honeyhive" },
    { "name": "4 Stars from Space Junk", "group": "SpaceJunk" },
    { "name": "4 Stars from Battlerock", "group": "Battlerock" },
    { "name": "4 Stars from Beach Bowl", "group": "BeachBowl" },
    { "name": "4 Stars from Ghostly", "group": "Ghostly" },
    { "name": "4 Stars from Gusty Garden", "group": "GustyGarden" },
    { "name": "4 Stars from Freezeflame", "group": "Freezeflame" },
    { "name": "4 Stars from Dusty Dune", "group": "DustyDune" },
    { "name": "4 Stars from Gold Leaf", "group": "GoldLeaf" },
    { "name": "4 Stars from Sea Slide", "group": "SeaSlide" },
    { "name": "4 Stars from Toy Time", "group": "ToyTime" },
    { "name": "4 Stars from Deep Dark", "group": "DeepDark" },
    { "name": "4 Stars from Dreadnought", "group": "Dreadnought" },
    { "name": "4 Stars from Melty Molten", "group": "MeltyMolten" },
    { "name": "Get 10 Lives (without using Mailtoad)", "group": "Lives" },
    { "name": "Get 15 Lives (without using Mailtoad)", "group": "Lives" },
    { "name": "Get 20 Lives (without using Mailtoad)", "group": "Lives" },
    { "name": "2 Stars from Trial Galaxies", "group": "Trial" },
    { "name": "3 Stars from Trial Galaxies", "group": "Trial" },
    { "name": "2 Green Stars", "group": "Green" },
    { "name": "3 Green Stars", "group": "Green" },
    { "name": "5 Stars (Terrace)", "group": "Terrace" },
    { "name": "6 Stars (Terrace)", "group": "Terrace" },
    { "name": "7 Stars (Terrace)", "group": "Terrace" },
    { "name": "5 Stars (Fountain)", "group": "Fountain" },
    { "name": "6 Stars (Fountain)", "group": "Fountain" },
    { "name": "7 Stars (Fountain)", "group": "Fountain" },
    { "name": "5 Stars (Kitchen)", "group": "Kitchen" },
    { "name": "6 Stars (Kitchen)", "group": "Kitchen" },
    { "name": "7 Stars (Kitchen)", "group": "Kitchen" },
    { "name": "5 Stars (Bedroom)", "group": "Bedroom" },
    { "name": "6 Stars (Bedroom)", "group": "Bedroom" },
    { "name": "7 Stars (Bedroom)", "group": "Bedroom" },
    { "name": "5 Stars (Engine Room)", "group": "EngineRoom" },
    { "name": "6 Stars (Engine Room)", "group": "EngineRoom" },
    { "name": "7 Stars (Engine Room)", "group": "EngineRoom" },
    { "name": "5 Stars (Garden)", "group": "Garden" },
    { "name": "6 Stars (Garden)", "group": "Garden" },
    { "name": "7 Stars (Garden)", "group": "Garden" },
    { "name": "100 Star Bits from any Star", "group": "StarBits" },
    { "name": "150 Star Bits from any Star", "group": "StarBits" },
    { "name": "200 Star Bits from any Star", "group": "StarBits" },
    { "name": "300 Star Bits (Total)", "group": "StarBitsTotal" },
    { "name": "400 Star Bits (Total)", "group": "StarBitsTotal" },
    { "name": "500 Star Bits (Total)", "group": "StarBitsTotal" },
    { "name": "All Five 1-Ups in the Observatory", "group": "Lives" },
    { "name": "125 Purple Coins in Gusty Garden", "group": "Purple" },
    { "name": "110 Purple Coins in Ghostly", "group": "Purple" },
    { "name": "140 Purple Coins in Toy Time", "group": "Purple" },
    { "name": "At Least 6 Stars from 1 Galaxy", "group": "MultiStar" },
    { "name": "At Least 5 Stars from 2 Galaxies", "group": "MultiStar" },
    { "name": "At Least 4 Stars from 3 Galaxies", "group": "MultiStar" },
    { "name": "At Least 3 Stars from 4 Galaxies", "group": "MultiStar" },
    { "name": "At Least 2 Stars from 5 Galaxies", "group": "MultiStar" },
    { "name": "At Least 1 Star from 6 Galaxies", "group": "MultiStar" },
    { "name": "At Least 1 Star from 8 Galaxies", "group": "MultiStar" },
    { "name": "At Least 1 Star from 10 Galaxies", "group": "MultiStar" },
    { "name": "2 Stars from Speedy Comets", "group": "Speedy" },
    { "name": "3 Stars from Speedy Comets", "group": "Speedy" },
    { "name": "2 Stars from Daredevil Comets", "group": "Daredevil" },
    { "name": "3 Stars from Daredevil Comets", "group": "Daredevil" },
    { "name": "2 Stars from Cosmic Comets", "group": "Cosmic" },
    { "name": "3 Stars from Cosmic Comets", "group": "Cosmic" },
    { "name": "2 Stars from Fast-Foe Comets", "group": "FastFoe" },
    { "name": "3 Stars from Purple Comets", "group": "Purple" },
    { "name": "4 Stars from Purple Comets", "group": "Purple" },
    { "name": "5 Stars from Purple Comets", "group": "Purple" },
    { "name": "2 Grand Stars", "group": "GrandStar" },
    { "name": "3 Grand Stars", "group": "GrandStar" },
    { "name": "2 Stars from Luigi", "group": "Luigi" },
    { "name": "3 Stars from Luigi", "group": "Luigi" },
    { "name": "2 Stars from Hungry Luma Galaxies", "group": "LumaGalaxy" },
    { "name": "3 Stars from Hungry Luma Galaxies", "group": "LumaGalaxy" },
    { "name": "4 Stars from Hungry Luma Galaxies", "group": "LumaGalaxy" }
];
