bingoGenerator = require("./generators/generator_bases/srl_generator_v5.js");

var bingoList = [];
bingoList[1] = [
{ name: "6 Moons (Cap)", types: ["Cap_Moons"] },
{ name: "4 Moons from sub-areas (Cap)", types: ["Cap"] },
{ name: "12 Moons (Cascade)", types: ["Cascade_Moons"] },
{ name: "28 Moons (Sand)", types: ["Sand_Moons"] },
{ name: "16 Moons (Lake)", types: ["Lake_Moons"] },
{ name: "28 Moons (Wooded)", types: ["Wooded_Moons"] },
{ name: "30 Moons (Metro)", types: ["Metro_Moons"] },
{ name: "18 Moons (Snow)", types: ["Snow_Moons"] },
{ name: "20 Moons (Seaside)", types: ["Seaside_Moons"] },
{ name: "26 Moons (Luncheon)", types: ["Luncheon_Moons"] },
{ name: "12 Moons (Bowser's)", types: ["Bowser_Moons"] },
{ name: "4 Moons (Moon)", types: ["Moon_Moons"] }
];
bingoList[2] = [
{ name: "25 Regional Coins (Cap)", types: ["Cap_Regional"] },
{ name: "35 Regional Coins (Cascade)", types: ["Cascade_Regional"] },
{ name: "45 Regional Coins (Sand)", types: ["Sand_Regional"] },
{ name: "30 Regional Coins (Lake)", types: ["Lake_Regional"] },
{ name: "50 Regional Coins (Wooded)", types: ["Wooded_Regional"] },
{ name: "30 Regional Coins (Lost)", types: ["Lost_Regional"] },
{ name: "45 Regional Coins (Metro)", types: ["Metro_Regional"] },
{ name: "30 Regional Coins (Snow)", types: ["Snow_Regional"] },
{ name: "40 Regional Coins (Seaside)", types: ["Seaside_Regional"] },
{ name: "30 Regional Coins (Luncheon)", types: ["Luncheon_Regional"] },
{ name: "25 Regional Coins (Bowser's)", types: ["Bowser_Regional"] },
{ name: "20 Regional Coins (Moon)", types: ["Moon_Regional"] }
];
bingoList[3] = [
{ name: "8 Moons (Cap)", types: ["Cap_Moons"] },
{ name: "6 Moons from sub-areas (Cap)", types: ["Cap"] },
{ name: "14 Moons (Cascade)", types: ["Cascade_Moons"] },
{ name: "30 Moons (Sand)", types: ["Sand_Moons"] },
{ name: "18 Moons (Lake)", types: ["Lake_Moons"] },
{ name: "30 Moons (Wooded)", types: ["Wooded_Moons"] },
{ name: "32 Moons (Metro)", types: ["Metro_Moons"] },
{ name: "20 Moons (Snow)", types: ["Snow_Moons"] },
{ name: "22 Moons (Seaside)", types: ["Seaside_Moons"] },
{ name: "28 Moons (Luncheon)", types: ["Luncheon_Moons"] },
{ name: "14 Moons (Bowser's)", types: ["Bowser_Moons"] },
{ name: "6 Moons (Moon)", types: ["Moon_Moons"] },
];
bingoList[4] = [
{ name: "30 Regional Coins (Cap)", types: ["Cap_Regional" ] },
{ name: "40 Regional Coins (Cascade)", types: ["Cascade_Regional"] },
{ name: "50 Regional Coins (Sand)", types: ["Sand_Regional"] },
{ name: "35 Regional Coins (Lake)", types: ["Lake_Regional"] },
{ name: "55 Regional Coins (Wooded)", types: ["Wooded_Regional"] },
{ name: "35 Regional Coins (Lost)", types: ["Lost_Regional"] },
{ name: "50 Regional Coins (Metro)", types: ["Metro_Regional"] },
{ name: "35 Regional Coins (Snow)", types: ["Snow_Regional"] },
{ name: "45 Regional Coins (Seaside)", types: ["Seaside_Regional"] },
{ name: "35 Regional Coins (Luncheon)", types: ["Luncheon_Regional"] },
{ name: "30 Regional Coins (Bowser's)", types: ["Bowser_Regional"] },
{ name: "25 Regional Coins (Moon)", types: ["Moon_Regional"] }
];
bingoList[5] = [
{ name: "10 Moons (Cap)", types: ["Cap_Moons"] },
{ name: "16 Moons (Cascade)", types: ["Cascade_Moons"] },
{ name: "4 Moons from sub-areas (Cascade)", types: ["Cascade"] },
{ name: "32 Moons (Sand)", types: ["Sand_Moons"] },
{ name: "20 Moons (Lake)", types: ["Lake_Moons"] },
{ name: "32 Moons (Wooded)", types: ["Wooded_Moons"] },
{ name: "34 Moons (Metro)", types: ["Metro_Moons"] },
{ name: "22 Moons (Snow)", types: ["Snow_Moons"] },
{ name: "24 Moons (Seaside)", types: ["Seaside_Moons"] },
{ name: "30 Moons (Luncheon)", types: ["Luncheon_Moons"] },
{ name: "16 Moons (Bowser's)", types: ["Bowser_Moons"] },
{ name: "8 Moons (Moon)", types: ["Moon_Moons"] },
];
bingoList[6] = [
{ name: "35 Regional Coins (Cap)", types: ["Cap_Regional"] },
{ name: "45 Regional Coins (Cascade)", types: ["Cascade_Regional"] },
{ name: "4 Checkpoints (Cascade)", types: ["Cascade"] },
{ name: "55 Regional Coins (Sand)", types: ["Sand_Regional"] },
{ name: "40 Regional Coins (Lake)", types: ["Lake_Regional"] },
{ name: "60 Regional Coins (Wooded)", types: ["Wooded_Regional"] },
{ name: "40 Regional Coins (Lost)", types: ["Lost_Regional"] },
{ name: "55 Regional Coins (Metro)", types: ["Metro_Regional"] },
{ name: "40 Regional Coins (Snow)", types: ["Snow_Regional"] },
{ name: "50 Regional Coins (Seaside)", types: ["Seaside_Regional"] },
{ name: "40 Regional Coins (Luncheon)", types: ["Luncheon_Regional"] },
{ name: "35 Regional Coins (Bowser's)", types: ["Bowser_Regional"] },
];
bingoList[7] = [
{ name: "2 Checkpoints (Cap)", types: ["Cap"] },
{ name: "18 Moons (Cascade)", types: ["Cascade_Moons"] },
{ name: "6 Moons from sub-areas (Cascade)", types: ["Cascade"] },
{ name: "34 Moons (Sand)", types: ["Sand_Moons"] },
{ name: "22 Moons (Lake)", types: ["Lake_Moons"] },
{ name: "34 Moons (Wooded)", types: ["Wooded_Moons"] },
{ name: "36 Moons (Metro)", types: ["Metro_Moons"] },
{ name: "24 Moons (Snow)", types: ["Snow_Moons"] },
{ name: "26 Moons (Seaside)", types: ["Seaside_Moons"] },
{ name: "32 Moons (Luncheon)", types: ["Luncheon_Moons"] },
{ name: "18 Moons (Bowser's)", types: ["Bowser_Moons"] },
{ name: "10 Moons (Moon)", types: ["Moon_Moons"] },
];
bingoList[8] = [
{ name: "40 Regional Coins (Cap)", types: ["Cap_Regional"] },
{ name: "50 Regional Coins (Cascade)", types: ["Cascade_Regional"] },
{ name: "60 Regional Coins (Sand)", types: ["Sand_Regional"] },
{ name: "45 Regional Coins (Lake)", types: ["Lake_Regional"] },
{ name: "65 Regional Coins (Wooded)", types: ["Wooded_Regional"] },
{ name: "45 Regional Coins (Lost)", types: ["Lost_Regional"] },
{ name: "60 Regional Coins (Metro)", types: ["Metro_Regional"] },
{ name: "55 Regional Coins (Seaside)", types: ["Seaside_Regional"] },
{ name: "45 Regional Coins (Luncheon)", types: ["Luncheon_Regional"] },
{ name: "40 Regional Coins (Bowser's)", types: ["Bowser_Regional"] },
{ name: "30 Regional Coins (Moon)", types: ["Moon_Regional"] },
{ name: "145 Moons (Total)", types: ["Total_Moons"] },
];
bingoList[9] = [
{ name: "36 Moons (Sand)", types: ["Sand_Moons"] },
{ name: "4 Moons from sub-areas (Sand)", types: ["Sand"] },
{ name: "Moon Shards in the Sand (Sand)", types: ["Sand"] },
{ name: "24 Moons (Lake)", types: ["Lake_Moons"] },
{ name: "36 Moons (Wooded)", types: ["Wooded_Moons"] },
{ name: "38 Moons (Metro)", types: ["Metro_Moons"] },
{ name: "20 Moons (Bowser's)", types: ["Bowser_Moons"] },
{ name: "Capture both the Cactus and the Tree", types: ["Capture_Both"] },
{ name: "300 Total Regional Coins", types: ["Regional_Coins"] },
{ name: "3 Moons from Goombas", types: ["Goomba"] },
{ name: "1 Moon from Seeds", types: ["Seeds"] },
{ name: "All Regional Coins in 3 Kingdoms", types: ["Regional_Kingdoms"] },
];
bingoList[10] = [
{ name: "65 Regional Coins (Sand)", types: ["Sand_Regional"] },
{ name: "7 Checkpoints (Sand)", types: ["Sand"] },
{ name: "Call Jaxi from 5 Stands", types: ["Jaxi"] },
{ name: "70 Regional Coins (Wooded)", types: ["Wooded_Regional"] },
{ name: "65 Regional Coins (Metro)", types: ["Metro_Regional"] },
{ name: "60 Regional Coins (Seaside)", types: ["Seaside_Regional"] },
{ name: "35 Regional Coins (Moon)", types: ["Moon_Regional"] },
{ name: "2 Moons from Slots", types: ["Slots"] },
{ name: "150 Moons (Total)", types: ["Total_Moons"] },
{ name: "8 Multi Moons", types: ["Multi_Moons"] },
{ name: "2 Moons from Keys", types: ["Keys"] },
{ name: "Outfit-Door (Sand)", types: ["Locked_Door"] },
];
bingoList[11] = [
{ name: "38 Moons (Sand)", types: ["Sand_Moons"] },
{ name: "6 Moons from sub-areas (Sand)", types: ["Sand"] },
{ name: "Koopa Trace-Walking (Sand)", types: ["Sand"] },
{ name: "6 Moons from sub-areas (Wooded)", types: ["Wooded"] },
{ name: "40 Moons (Metro)", types: ["Metro_Moons"] },
{ name: "4 Moons from sub-areas (Luncheon)", types: ["Luncheon"] },
{ name: "325 Total Regional Coins", types: ["Regional_Coins"] },
{ name: "4 Moons from Goombas", types: ["Goomba"] },
{ name: "World Peace Restored! (Wooded)", types: ["World_Peace"] },
{ name: "All Regional Coins in 4 Kingdoms", types: ["Regional_Kingdoms"] },
{ name: "1 Moon (Underground Moon Caves)", types: ["Moon_Caves"] },
{ name: "Seaside Kingdom: Sphynx Quiz Complete!", types: ["Seaside"] },
];
bingoList[12] = [
{ name: "70 Regional Coins (Sand)", types: ["Sand_Regional"] },
{ name: "8 Checkpoints (Sand)", types: ["Sand"] },
{ name: "Call Jaxi from 6 Stands", types: ["Jaxi"] },
{ name: "75 Regional Coins (Wooded)", types: ["Wooded_Regional"] },
{ name: "7 Checkpoints (Metro)", types: ["Metro"] },
{ name: "65 Regional Coins (Seaside)", types: ["Seaside_Regional"] },
{ name: "3 Moons from Slots", types: ["Slots"] },
{ name: "Look at 3 Hint Arts", types: ["Hint_View"] },
{ name: "155 Moons (Total)", types: ["Total_Moons"] },
{ name: "9 Multi Moons", types: ["Multi_Moons"] },
{ name: "3 Moons from Keys", types: ["Keys"] },
{ name: "15 Story Moons (excl. Multi Moons)", types: ["Story"] },
];
bingoList[13] = [
{ name: "40 Moons (Sand)", types: ["Sand_Moons"] },
{ name: "8 Moons from sub-areas (Sand)", types: ["Sand"] },
{ name: "Herding Sheep in the Dunes (Sand)", types: ["Sand"] },
{ name: "8 Moons from sub-areas (Wooded)", types: ["Wooded"] },
{ name: "42 Moons (Metro)", types: ["Metro_Moons"] },
{ name: "8 Moons from sub-areas (Metro)", types: ["Metro"] },
{ name: "6 Moons from sub-areas (Luncheon)", types: ["Luncheon"] },
{ name: "30 Moons from sub-areas (Total)", types: ["Sub_Areas"] },
{ name: "350 Total Regional Coins", types: ["Regional_Coins"] },
{ name: "Outfit-Door (Wooded)", types: ["Locked_Door"] },
{ name: "2 Moons (Underground Moon Caves)", types: ["Moon_Caves"] },
{ name: "Catch the Rabbit! (Bowser's)", types: ["Bowser"] },
];
bingoList[14] = [
{ name: "9 Checkpoints (Sand)", types: ["Sand"] },
{ name: "Call Jaxi from 7 Stands", types: ["Jaxi"] },
{ name: "4 Moons from sub-areas (Lake)", types: ["Lake"] },
{ name: "4 Moons (Deep Woods)", types: ["Deep_Woods"] },
{ name: "8 Checkpoints (Metro)", types: ["Metro"] },
{ name: "70 Regional Coins (Seaside)", types: ["Seaside_Regional"] },
{ name: "2 Moons from sub-areas (Bowser's)", types: ["Bowser"] },
{ name: "Look at 4 Hint Arts", types: ["Hint_View"] },
{ name: "3 Moons from Wooden Crates", types: ["Crates"] },
{ name: "160 Moons (Total)", types: ["Total_Moons"] },
{ name: "Outfit-Door (Seaside)", types: ["Locked_Door"] },
{ name: "Madame Broode Defeated! (Moon)", types: ["Extra_Boss"] },
];
bingoList[15] = [
{ name: "42 Moons (Sand)", types: ["Sand_Moons"] },
{ name: "Ice Cave Treasure-Moon (Sand)", types: ["Sand"] },
{ name: "10 Moons from sub-areas (Wooded)", types: ["Wooded"] },
{ name: "10 Moons from sub-areas (Metro)", types: ["Metro"] },
{ name: "8 Moons from sub-areas (Luncheon)", types: ["Luncheon"] },
{ name: "1 Moon from Lakitu-Fishing", types: ["Fishing"] },
{ name: "32 Moons from sub-areas (Total)", types: ["Sub_Areas"] },
{ name: "6 Stickers", types: ["Stickers"] },
{ name: "375 Total Regional Coins", types: ["Regional_Coins"] },
{ name: "World Peace Restored! (Seaside)", types: ["World_Peace"] },
{ name: "8 Unique Life-Up Hearts (excl. Shops)", types: ["LifeUp"] },
{ name: "Outfit-Door (Snow)", types: ["Locked_Door"] },
];
bingoList[16] = [
{ name: "5 Checkpoints (Lake)", types: ["Lake"] },
{ name: "6 Checkpoints (Wooded)", types: ["Wooded"] },
{ name: "5 Moons (Deep Woods)", types: ["Deep_Woods"] },
{ name: "9 Checkpoints (Metro)", types: ["Metro"] },
{ name: "Uncork 3 Fountains (Seaside)", types: ["Seaside"] },
{ name: "4 Moons from sub-areas (Bowser's)", types: ["Bowser"] },
{ name: "Purchase 8 Hats", types: ["Hats"] },
{ name: "Look at 5 Hint Arts", types: ["Hint_View"] },
{ name: "4 Moons from Wooden Crates", types: ["Crates"] },
{ name: "World Peace in 5 Kingdoms (excl. Cap, Cloud, Lost, Moon)", types: ["World_Peace"] },
{ name: "3 Moons (Underground Moon Caves)", types: ["Moon_Caves"] },
{ name: "Tostarena-Tourist in the Metro Kingdom!", types: ["Tourist"] },
];
bingoList[17] = [
{ name: "9 Moons from Nuts", types: ["Nuts"] },
{ name: "Goomba Picture-Match (Cloud)", types: ["Cloud"] },
{ name: "3 Checkpoints (Lost)", types: ["Lost"] },
{ name: "12 Moons from sub-areas (Metro)", types: ["Metro"] },
{ name: "2 Moons from Lakitu-Fishing", types: ["Fishing"] },
{ name: "34 Moons from sub-areas (Total)", types: ["Sub_Areas"] },
{ name: "7 Stickers", types: ["Stickers"] },
{ name: "Purchase 8 Souvenirs", types: ["Souvenirs"] },
{ name: "7 Timer Challenges", types: ["Timer"] },
{ name: "26 Unique Captures", types: ["Unique_Captures"] },
{ name: "400 Total Regional Coins", types: ["Regional_Coins"] },
{ name: "10 Unique Life-Up Hearts (excl. Shops)", types: ["LifeUp"] },
];
bingoList[18] = [
{ name: "Puzzle Room Solved! (Lake)", types: ["Lake"] },
{ name: "7 Checkpoints (Wooded)", types: ["Wooded"] },
{ name: "6 Moons (Deep Woods)", types: ["Deep_Woods"] },
{ name: "RC Car: Race Complete! (Metro)", types: ["Metro"] },
{ name: "Uncork 4 Fountains (Seaside)", types: ["Seaside"] },
{ name: "Purchase 9 Hats", types: ["Hats"] },
{ name: "Purchase 8 Full Costume Sets", types: ["Outfits"] },
{ name: "9 Treasure Chest Moons", types: ["Treasure_Chest"] },
{ name: "World Peace Restored! (Snow)", types: ["World_Peace"] },
{ name: "World Peace in 6 Kingdoms (excl. Cap, Cloud, Lost, Moon)", types: ["World_Peace"] },
{ name: "17 Story Moons (excl. Multi Moons)", types: ["Story"] },
{ name: "2 Moon from Seeds", types: ["Seeds"] },
];
bingoList[19] = [
{ name: "10 Moons from Nuts", types: ["Nuts"] },
{ name: "16 Moons (Lost)", types: ["Lost_Moons"] },
{ name: "Catch the Rabbit! (Lost)", types: ["Lost"] },
{ name: "2 Checkpoints (Snow)", types: ["Snow"] },
{ name: "5 Checkpoints (Luncheon)", types: ["Luncheon"] },
{ name: "36 Moons from sub-areas (Total)", types: ["Sub_Areas"] },
{ name: "8 Stickers", types: ["Stickers"] },
{ name: "Purchase 10 Souvenirs", types: ["Souvenirs"] },
{ name: "8 Timer Challenges", types: ["Timer"] },
{ name: "7 Moons from 8-bit Sections", types: ["8bit"] },
{ name: "Purchase 8 Moons", types: ["Shop_Moons"] },
{ name: "28 Unique Captures", types: ["Unique_Captures"] },
];
bingoList[20] = [
{ name: "Plant 1 Seed (Lake)", types: ["Seeds"] },
{ name: "8 Checkpoints (Wooded)", types: ["Wooded"] },
{ name: "7 Moons (Deep Woods)", types: ["Deep_Woods"] },
{ name: "Jump-Rope Hero! (Metro)", types: ["Metro"] },
{ name: "7 Checkpoints (Seaside)", types: ["Seaside"] },
{ name: "Purchase 10 Hats", types: ["Hats"] },
{ name: "3 Warp-Painting Moons", types: ["Warp_Painting"] },
{ name: "Purchase 9 Full Costume Sets", types: ["Outfits"] },
{ name: "6 Moons from Music Notes", types: ["Music_Notes"] },
{ name: "11 Treasure Chest Moons", types: ["Treasure_Chest"] },
{ name: "Plant 5 Seeds (Total)", types: ["Seeds"] },
{ name: "World Peace Restored! (Sand)", types: ["World_Peace"] },
];
bingoList[21] = [
{ name: "11 Moons from Nuts", types: ["Nuts"] },
{ name: "18 Moons (Lost)", types: ["Lost_Moons"] },
{ name: "4 Barrier-Moons (Snow)", types: ["Snow"] },
{ name: "4 Moons from sub-areas (Seaside)", types: ["Seaside"] },
{ name: "6 Checkpoints (Luncheon)", types: ["Luncheon"] },
{ name: "38 Moons from sub-areas (Total)", types: ["Sub_Areas"] },
{ name: "9 Stickers", types: ["Stickers"] },
{ name: "Purchase 12 Souvenirs", types: ["Souvenirs"] },
{ name: "9 Timer Challenges", types: ["Timer"] },
{ name: "6 Captain Toad Moons", types: ["Captain_Toad"] },
{ name: "9 Moons from 8-bit Sections", types: ["8bit"] },
{ name: "6 Moons from Moon Shards", types: ["Moon_Shards"] },
];
bingoList[22] = [
{ name: "Catch the Rabbit! (Metro)", types: ["Metro"] },
{ name: "2 Moons from sub-areas (Snow)", types: ["Snow"] },
{ name: "8 Checkpoints (Seaside)", types: ["Seaside"] },
{ name: "2 Moons from Golden Turnips", types: ["Turnips"] },
{ name: "9 Checkpoints (Bowser's)", types: ["Bowser"] },
{ name: "4 Warp-Painting Moons", types: ["Warp_Painting"] },
{ name: "Purchase 10 Full Costume Sets", types: ["Outfits"] },
{ name: "7 Moons from Music Notes", types: ["Music_Notes"] },
{ name: "13 Treasure Chest Moons", types: ["Treasure_Chest"] },
{ name: "2 Moons from Hint Art", types: ["Hint_Moon"] },
{ name: "Plant 6 Seeds (Total)", types: ["Seeds"] },
{ name: "World Peace Restored! (Metro)", types: ["World_Peace"] },
];
bingoList[23] = [
{ name: "20 Moons (Lost)", types: ["Lost_Moons"] },
{ name: "Catch the Rabbit! (Snow)", types: ["Snow"] },
{ name: "6 Moons from sub-areas (Seaside)", types: ["Seaside"] },
{ name: "7 Checkpoints (Luncheon)", types: ["Luncheon"] },
{ name: "40 Moons from sub-areas (Total)", types: ["Sub_Areas"] },
{ name: "10 Timer Challenges", types: ["Timer"] },
{ name: "7 Captain Toad Moons", types: ["Captain_Toad"] },
{ name: "11 Moons from 8-bit Sections", types: ["8bit"] },
{ name: "7 Moons from Moon Shards", types: ["Moon_Shards"] },
{ name: "Purchase 9 Moons", types: ["Shop_Moons"] },
{ name: "30 Unique Captures", types: ["Unique_Captures"] },
{ name: "425 Total Regional Coins", types: ["Regional_Coins"] },
];
bingoList[24] = [
{ name: "Koopa Trace-Walking (Snow)", types: ["Snow"] },
{ name: "9 Checkpoints (Seaside)", types: ["Seaside"] },
{ name: "3 Moons from Golden Turnips", types: ["Turnips"] },
{ name: "10 Checkpoints (Bowser's)", types: ["Bowser"] },
{ name: "5 Warp-Painting Moons", types: ["Warp_Painting"] },
{ name: "Purchase 11 Full Costume Sets", types: ["Outfits"] },
{ name: "8 Moons from Music Notes", types: ["Music_Notes"] },
{ name: "15 Treasure Chest Moons", types: ["Treasure_Chest"] },
{ name: "3 Moons from Hint Art", types: ["Hint_Moon"] },
{ name: "Plant 7 Seeds (Total)", types: ["Seeds"] },
{ name: "12 Unique Life-Up Hearts (excl. Shops)", types: ["LifeUp"] },
{ name: "19 Story Moons (excl. Multi Moons)", types: ["Story"] },
];
bingoList[25] = [
{ name: "2 Moons from sub-areas (Ruined)", types: ["Ruined"] },
{ name: "3 Checkpoints (Moon)", types: ["Moon"] },
{ name: "Wear the Boxer Shorts", types: ["Nipple_Percent"] },
{ name: "11 Timer Challenges", types: ["Timer"] },
{ name: "8 Captain Toad Moons", types: ["Captain_Toad"] },
{ name: "13 Moons from 8-bit Sections", types: ["8bit"] },
{ name: "8 Moons from Moon Shards", types: ["Moon_Shards"] },
{ name: "Purchase 10 Moons", types: ["Shop_Moons"] },
{ name: "32 Unique Captures", types: ["Unique_Captures"] },
{ name: "450 Total Regional Coins", types: ["Regional_Coins"] },
{ name: "World Peace Restored! (Luncheon)", types: ["World_Peace"] },
{ name: "Outfit-Door (Bowser's)", types: ["Locked_Door"] },
];
