(function(j, i, g, m, k, n, o) {
    function q(b) {
        var e, f, a = this,
            c = b.length,
            d = 0,
            h = a.i = a.j = a.m = 0;
        a.S = [];
        a.c = [];
        for (c || (b = [c++]); d < g;) a.S[d] = d++;
        for (d = 0; d < g; d++) e = a.S[d], h = h + e + b[d % c] & g - 1, f = a.S[h], a.S[d] = f, a.S[h] = e;
        a.g = function(b) {
            var c = a.S,
                d = a.i + 1 & g - 1,
                e = c[d],
                f = a.j + e & g - 1,
                h = c[f];
            c[d] = h;
            c[f] = e;
            for (var i = c[e + h & g - 1]; --b;) d = d + 1 & g - 1, e = c[d], f = f + e & g - 1, h = c[f], c[d] = h, c[f] = e, i = i * g + c[e + h & g - 1];
            a.i = d;
            a.j = f;
            return i
        };
        a.g(g)
    }

    function p(b, e, f, a, c) {
        f = [];
        c = typeof b;
        if (e && c == "object")
            for (a in b)
                if (a.indexOf("S") < 5) try {
                    f.push(p(b[a], e - 1))
                } catch (d) {}
                return f.length ? f : b + (c != "string" ? "\0" : "")
    }

    function l(b, e, f, a) {
        b += "";
        for (a = f = 0; a < b.length; a++) {
            var c = e,
                d = a & g - 1,
                h = (f ^= e[a & g - 1] * 19) + b.charCodeAt(a);
            c[d] = h & g - 1
        }
        b = "";
        for (a in e) b += String.fromCharCode(e[a]);
        return b
    }
    i.seedrandom = function(b, e) {
        var f = [],
            a;
        b = l(p(e ? [b, j] : arguments.length ? b : [(new Date).getTime(), j, window], 3), f);
        a = new q(f);
        l(a.S, j);
        i.random = function() {
            for (var c = a.g(m), d = o, b = 0; c < k;) c = (c + b) * g, d *= g, b = a.g(1);
            for (; c >= n;) c /= 2, d /= 2, b >>>= 1;
            return (c + b) / d
        };
        return b
    };
    o = i.pow(g, m);
    k = i.pow(2, k);
    n = k * 2;
    l(i.random(), j)
})([], Math, 256, 6, 52);

bingoGenerator = function(bingoList, opts) {
    var LANG = opts.lang || 'name';
    var MODE = opts.mode || "normal";
    var cardType = "Normal";
    var SEED = opts.seed || Math.ceil(999999 * Math.random()).toString();
    var size = 5;

    // simpler generator that just does a random choice without duplicates
    Math.seedrandom(SEED);
    if (true) {
        var usedGoals = {};
        var bingoBoard = [];

        for (var i = 1; i <= 25; i++) {
            var randIndex = Math.floor(Math.random() * bingoList.length);
            while (usedGoals[randIndex]) {
                randIndex = Math.floor(Math.random() * bingoList.length);
            }
            usedGoals[randIndex] = true;

            var goal = bingoList[randIndex];
            bingoBoard[i] = {"name": goal};
        }

        return bingoBoard;
    }
};

var bingoList = [
    "Defeat each Broodal at least once",
    "Answer 5 Sphynx Questions",
    "15 Total Checkpoints",
    "20 Total Checkpoints",
    "25 Total Checkpoints",
    "30 Total Checkpoints",
    "6 Power Moons from 8-bit Sections",
    "7 Power Moons from 8-bit Sections",
    "8 Power Moons from 8-bit Sections",
    "2 Power Moons from Koopa Trace-Walking",
    "Plant 4 Seeds",
    "Plant 5 Seeds",
    "Plant 6 Seeds",
    "Plant 7 Seeds",
    "2 Power Moons from Seeds",
    "3 Power Moons from Seeds",
    "4 Power Moons from Seeds",
    "Purchase 2 Full Costumes using Regional Coins",
    "Purchase 3 Full Costumes using Regional Coins",
    "Purchase 4 Full Costumes using Regional Coins",
    "4 Power Moons from Goombette",
    "5 Power Moons from Goombette",
    "6 Power Moons from Goombette",
    "6 Power Moons from Moon Shards",
    "7 Power Moons from Moon Shards",
    "8 Power Moons from Moon Shards",
    "Have 1000 Coins at any one point",
    "Have 1500 Coins at any one point",
    "Bring Peace to 5 Kingdoms",
    "Bring Peace to 6 Kingdoms",
    "Bring Peace to 7 Kingdoms",
    "1 Power Moon from Fishing",
    "2 Power Moons from Fishing",
    "200 Total Regional Coins",
    "250 Total Regional Coins",
    "300 Total Regional Coins",
    "350 Total Regional Coins",
    "400 Total Regional Coins",
    "1 Power Moon from Picture Match",
    "8 Multi Moons",
    "9 Multi Moons",
    "15 Power Moons from Every Kingdom (except Cloud and Ruined)",
    "20 Power Moons from Every Kingdom (except Cloud and Ruined)",
    "25 Power Moons from a Single Kingdom",
    "30 Power Moons from a Single Kingdom",
    "Enter 3 Warp-Paintings",
    "Enter 4 Warp-Paintings",
    "Enter 5 Warp-Paintings",
    "2 Power Moons from Peach",
    "3 Power Moons from Peach",
    "4 Power Moons from Peach",
    "5 Power Moons from Peach",
    "4 Power Moons from Captain Toad",
    "5 Power Moons from Captain Toad",
    "6 Power Moons from Captain Toad",
    "1 Power Moon from Slots",
    "2 Power Moons from Slots",
    "3 Power Moons from Slots",
    "50 Regional Coins from a Single Kingdom",
    "75 Regional Coins from a Single Kingdom",
    "2 Power Moons from Hint Art",
    "3 Power Moons from Hint Art",
    "4 Power Moons from Hint Art",
    "5 Power Moons from Hint Art",
    "2 Power Moons from Koopa Freerunning",
    "3 Power Moons from Koopa Freerunning",
    "4 Power Moons from Koopa Freerunning",
    "6 Power Moons from Music Note Challenges",
    "7 Power Moons from Music Note Challenges",
    "8 Power Moons from Music Note Challenges",
    "9 Power Moons from Music Note Challenges",
    "6 Power Moons from Timer Challenges",
    "7 Power Moons from Timer Challenges",
    "8 Power Moons from Timer Challenges",
    "9 Power Moons from Timer Challenges",
    "10 Power Moons from Timer Challenges",
    "8 Total Power Moons from sub-areas",
    "10 Total Power Moons from sub-areas",
    "12 Total Power Moons from sub-areas",
    "14 Total Power Moons from sub-areas",
    "Purchase 3 Kingdom Stickers",
    "Purchase 4 Kingdom Stickers",
    "Purchase 5 Kingdom Stickers",
    "Purchase 6 Kingdom Stickers",
    "5 Power Moons from the Cap Kingdom",
    "10 Power Moons from the Cap Kingdom",
    "20 Regional Coins from the Cap Kingdom",
    "30 Regional Coins from the Cap Kingdom",
    "40 Regional Coins from the Cap Kingdom",
    "Peach in the Cap Kingdom",
    "Power Moon from Cap Kingdom Hint Art",
    "\"Bonneter Blockade\" Power Moon (Cap Kingdom)",
    "Koopa Freerunning (Cap Kingdom) in under 35 Seconds",
    "Purchase the Full Black-Suit Costume (Cap Kingdom)",
    "Purchase a Power Moon in the Cap Kingdom",
    "1 Timer Challenge from the Cap Kingdom",
    "Purchase the Bonneton Sticker (Cap Kingdom)",
    "Captain Toad in the Cap Kingdom",
    "Purchase 1 Souvenir from the Cap Kingdom",
    "2 Checkpoints from the Cap Kingdom",
    "2 Power Moons from sub-areas (Cap Kingdom)",
    "4 Power Moons from sub-areas (Cap Kingdom)",
    "Flying Taxi: At the Central Plaza (Cap Kingdom)",
    "15 Power Moons from the Cascade Kingdom",
    "20 Power Moons from the Cascade Kingdom",
    "20 Regional Coins from the Cascade Kingdom",
    "30 Regional Coins from the Cascade Kingdom",
    "40 Regional Coins from the Cascade Kingdom",
    "Peach in the Cascade Kingdom",
    "Destroy a Rock in the Chain Chomp sub-area (Cascade Kingdom)",
    "Purchase a Power Moon in the Cascade Kingdom",
    "Koopa Freerunning (Cascade Kingdom) in under 40 Seconds",
    "Reach the Cascade Kingdom with a Warp-Painting",
    "Caveman-Fan: Summit of the Falls (Cascade Kingdom)",
    "1 Timer Challenge from the Cascade Kingdom",
    "2 Timer Challenges from the Cascade Kingdom",
    "Purchase the Fossil Falls Sticker (Cascade Kingdom)",
    "Captain Toad in the Cascade Kingdom",
    "Purchase 1 Souvenir from the Cascade Kingdom",
    "2 Power Moons from sub-areas (Cascade Kingdom)",
    "4 Power Moons from sub-areas (Cascade Kingdom)",
    "Flying Sphynx: Over the Waterfall (Cascade Kingdom)",
    "2 Checkpoints from the Cascade Kingdom",
    "3 Checkpoints from the Cascade Kingdom",
    "20 Power Moons from the Sand Kingdom",
    "25 Power Moons from the Sand Kingdom",
    "30 Power Moons from the Sand Kingdom",
    "35 Power Moons from the Sand Kingdom",
    "40 Power Moons from the Sand Kingdom",
    "20 Regional Coins from the Sand Kingdom",
    "30 Regional Coins from the Sand Kingdom",
    "40 Regional Coins from the Sand Kingdom",
    "50 Regional Coins from the Sand Kingdom",
    "Reach the Sand Kingdom with a Warp-Painting",
    "Bonneter Hat-and-Seek: In the Town (Sand Kingdom)",
    "Power Moon atop the Ruins Tower (Sand Kingdom)",
    "Moon Shards in the Moe-Eye Habitat (Sand Kingdom)",
    "Broodals at the Inverted Pyramid! (Sand Kingdom)",
    "Knucklotec Battle in the Icy Caverns (Sand Kingdom)",
    "Collect 5 Power Moons while riding a Jaxi",
    "Tostarena Secret Room: Dancing on Stage! (Sand Kingdom)",
    "Lost Sheep in the Dunes (Sand Kingdom)",
    "1 Timer Challenge from the Sand Kingdom",
    "2 Timer Challenges from the Sand Kingdom",
    "3 Timer Challenges from the Sand Kingdom",
    "Peach in the Sand Kingdom",
    "Power Moon from Sand Kingdom Hint Art",
    "1 Power Moon from Sand Kingdom Seeds",
    "Long Jump from Top of Inverted Pyramid and Land on a Power Moon",
    "Call Jaxi from 3 Different Jaxi-Stands",
    "Call Jaxi from 4 Different Jaxi-Stands",
    "Call Jaxi from 5 Different Jaxi-Stands",
    "Power Moon from the Binding Band (Sand Kingdom)",
    "Score 90 Points on Koopa Trace-Walking (Sand Kingdom)",
    "Sand Kingdom Slots",
    "Koopa Freerunning (Sand Kingdom) in under 45 Seconds",
    "Koopa Freerunning (Sand Kingdom) without using a Jaxi",
    "Lakitu-Fishing Power Moon (Sand Kingdom)",
    "Purchase a Power Moon in the Sand Kingdom",
    "Music-Toad in the Desert Town (Sand Kingdom)",
    "Captain Toad in the Sand Kingdom",
    "Purchase 1 Souvenir from the Sand Kingdom",
    "Purchase the Tostarena Sticker (Sand Kingdom)",
    "Power Moon in the Desert! Good Dog! (Sand Kingdom)",
    "2 Power Moons from sub-areas (Sand Kingdom)",
    "4 Power Moons from sub-areas (Sand Kingdom)",
    "6 Power Moons from sub-areas (Sand Kingdom)",
    "5 Checkpoints from the Sand Kingdom",
    "6 Checkpoints from the Sand Kingdom",
    "7 Checkpoints from the Sand Kingdom",
    "15 Power Moons from the Lake Kingdom",
    "20 Power Moons from the Lake Kingdom",
    "20 Regional Coins from the Lake Kingdom",
    "30 Regional Coins from the Lake Kingdom",
    "40 Regional Coins from the Lake Kingdom",
    "Peach in the Lake Kingdom",
    "Lake Lamode Secret Room: Dress Display Case (Lake Kingdom)",
    "Koopa Freerunning (Lake Kingdom) in under 45 Seconds",
    "Koopa Freerunning (Lake Kingdom) without Triple Jumps",
    "Power Moon from Lake Kingdom Hint Art",
    "Lakitu-Fishing Power Moon (Lake Kingdom)",
    "Power Moon from Lake Kingdom Seed",
    "Cheep Cheep Lover: Over the Water Plaza (Lake Lamode)",
    "1 Power Moon from the Lochlady Sisters (Lake Kingdom)",
    "1 Timer Challenge from the Lake Kingdom",
    "2 Timer Challenges from the Lake Kingdom",
    "Create a Goomba Tower with 10 Goombas (Lake Kingdom)",
    "Reach the Lake Kingdom with a Warp-Painting",
    "Purchase a Power Moon in the Lake Kingdom",
    "Purchase the Lake Lamode Sticker (Lake Kingdom)",
    "Purchase 1 Souvenir from the Lake Kingdom",
    "Captain Toad in the Lake Kingdom",
    "2 Power Moons from sub-areas (Lake Kingdom)",
    "4 Checkpoints from the Lake Kingdom",
    "5 Checkpoints from the Lake Kingdom",
    "6 Checkpoints from the Lake Kingdom",
    "Flying Taxi: Over the Lake! (Lake Kingdom)",
    "20 Power Moons from the Wooded Kingdom",
    "25 Power Moons from the Wooded Kingdom",
    "30 Power Moons from the Wooded Kingdom",
    "35 Power Moons from the Wooded Kingdom",
    "40 Power Moons from the Wooded Kingdom",
    "20 Regional Coins from the Wooded Kingdom",
    "30 Regional Coins from the Wooded Kingdom",
    "40 Regional Coins from the Wooded Kingdom",
    "50 Regional Coins from the Wooded Kingdom",
    "4 Power Moons in the Deep Woods",
    "5 Power Moons in the Deep Woods",
    "6 Power Moons in the Deep Woods",
    "\"A Treasure Made from Coins\" (Wooded Kingdom)",
    "8 Power Moons from Nuts (Wooded Kingdom)",
    "10 Power Moons from Nuts (Wooded Kingdom)",
    "12 Power Moons from Nuts (Wooded Kingdom)",
    "1 Timer Challenge from the Wooded Kingdom",
    "2 Timer Challenges from the Wooded Kingdom",
    "Steam Gardens Secret Room: Explorer in the Deep Woods! (Wooded Kingdom)",
    "Bonneter Scientist: Uproot at Sky Garden! (Wooded Kingdom)",
    "Peach in the Wooded Kingdom",
    "Captain Toad in the Wooded Kingdom",
    "Koopa Freerunning (Wooded Kingdom) in under 35 Seconds",
    "Torkdrift in the Secret Flower Field! (Wooded Kingdom)",
    "Reach the Wooded Kingdom with a Warp-Painting",
    "Power Moon from Wooded Kingdom Hint Art",
    "Music-Toad in the Wooded Kingdom",
    "Purchase the Steam Gardens Sticker (Wooded Kingdom)",
    "Purchase 1 Souvenir from the Wooded Kingdom",
    "5 Checkpoints from the Wooded Kingdom",
    "6 Checkpoints from the Wooded Kingdom",
    "7 Checkpoints from the Wooded Kingdom",
    "2 Power Moons from sub-areas (Wooded Kingdom)",
    "4 Power Moons from sub-areas (Wooded Kingdom)",
    "6 Power Moons from sub-areas (Wooded Kingdom)",
    "Score 85 Points on Picture Match (Cloud Kingdom)",
    "Peach in the Cloud Kingdom",
    "15 Power Moons from the Lost Kingdom",
    "20 Power Moons from the Lost Kingdom",
    "20 Regional Coins from the Lost Kingdom",
    "30 Regional Coins from the Lost Kingdom",
    "40 Regional Coins from the Lost Kingdom",
    "Koopa Freerunning (Lost Kingdom) in under 50 Seconds",
    "Bonneter Scientist: Tropical Wiggler Ahoy! (Lost Kingdom)",
    "Power Moon from the Rabbit (Lost Kingdom)",
    "Purchase the Full Aviator Costume (Lost Kingdom)",
    "Purchase a Power Moon in the Lost Kingdom",
    "Captain Toad in the Lost Kingdom",
    "Peach in the Lost Kingdom",
    "Purchase the Forgotten Isle Sticker (Lost Kingdom)",
    "Purchase 1 Souvenir from the Lost Kingdom",
    "Flying Taxi: In the Forgotten Land (Lost Kingdom)",
    "3 Checkpoints from the Lost Kingdom",
    "30 Power Moons from the Metro Kingdom",
    "35 Power Moons from the Metro Kingdom",
    "40 Power Moons from the Metro Kingdom",
    "20 Regional Coins from the Metro Kingdom",
    "30 Regional Coins from the Metro Kingdom",
    "40 Regional Coins from the Metro Kingdom",
    "50 Regional Coins from the Metro Kingdom",
    "Reach the Metro Kingdom with a Warp-Painting",
    "Bonneter Hat-and-Seek: City Quest (Metro Kingdom)",
    "Bonneter Hat-and-Seek: Among the Crowd (Metro Kingdom)",
    "Music-Toad in the Metro Kingdom",
    "Metro Kingdom Slots",
    "Jump, Man! 100 Points on the Jump-Rope Challenge!",
    "1 Power Moon from Metro Kingdom Seeds",
    "1 Timer Challenge from the Metro Kingdom",
    "2 Timer Challenges from the Metro Kingdom",
    "Purchase a Power Moon in the Metro Kingdom",
    "3 Power Moons from Musicians (Metro Kingdom)",
    "4 Power Moons from Musicians (Metro Kingdom)",
    "New Donk City Festival! (Metro Kingdom)",
    "Pauline's Lost Handbag (Metro Kingdom)",
    "Power Moon from Metro Kingdom Hint Art",
    "Koopa Freerunning (Metro Kingdom) in under 35 Seconds",
    "Use the Letters to Spell Any Word other than \"Mario\" (Metro Kingdom)",
    "New Donk City Secret Room: Construction Mario? (Metro Kingdom)",
    "Peach in the Metro Kingdom",
    "Captain Toad in the Metro Kingdom",
    "Purchase the New Donk City Sticker (Metro Kingdom)",
    "Purchase 1 Souvenir from the Metro Kingdom",
    "2 Power Moons from sub-areas (Metro Kingdom)",
    "4 Power Moons from sub-areas (Metro Kingdom)",
    "6 Power Moons from sub-areas (Metro Kingdom)",
    "8 Power Moons from sub-areas (Metro Kingdom)",
    "4 Checkpoints from the Metro Kingdom",
    "5 Checkpoints from the Metro Kingdom",
    "6 Checkpoints from the Metro Kingdom",
    "Flying Sphynx: Over the Skyscrapers (Metro Kingdom)",
    "15 Power Moons from the Snow Kingdom",
    "20 Power Moons from the Snow Kingdom",
    "25 Power Moons from the Snow Kingdom",
    "30 Power Moons from the Snow Kingdom",
    "20 Regional Coins from the Snow Kingdom",
    "30 Regional Coins from the Snow Kingdom",
    "40 Regional Coins from the Snow Kingdom",
    "Bonneter Hat-and-Seek: In the Snowy Depths (Snow Kingdom)",
    "Reach the Snow Kingdom with a Warp-Painting",
    "The Bound Bowl Grand Prix! (Snow Kingdom)",
    "Purchase a Power Moon from the Snow Kingdom",
    "Power Moon from Snow Kingdom Hint Art",
    "Score 85 Points on Koopa Trace-Walking (Snow Kingdom)",
    "1 Timer Challenge from the Snow Kingdom",
    "2 Timer Challenges from the Snow Kingdom",
    "Shiveria Secret Room: Dressed for the Weather (Snow Kingdom)",
    "Snowline Circuit: Class S (Snow Kingdom)",
    "Peach in the Snow Kingdom",
    "Power Moon from the Rabbit (Snow Kingdom)",
    "Lakitu-Fishing Power Moon (Snow Kingdom)",
    "3 Barrier-Opening Power Moons (Snow Kingdom)",
    "4 Barrier-Opening Power Moons (Snow Kingdom)",
    "Bonneter Scientist: Cheep Cheeps in the Ice (Snow Kingdom)",
    "Boxer Shorts in the Cold?! Here's a Power Moon! (Snow Kingdom)",
    "Koopa Freerunning (Snow Kingdom) in under 25 Seconds",
    "Captain Toad in the Snow Kingdom",
    "Purchase the Shiveria Sticker (Snow Kingdom)",
    "Purchase 1 Souvenir from the Snow Kingdom",
    "2 Checkpoint from the Snow Kingdom",
    "3 Checkpoints from the Snow Kingdom",
    "2 Power Moons from sub-areas (Snow Kingdom)",
    "4 Power Moons from sub-areas (Snow Kingdom)",
    "20 Power Moons from the Seaside Kingdom",
    "25 Power Moons from the Seaside Kingdom",
    "30 Power Moons from the Seaside Kingdom",
    "35 Power Moons from the Seaside Kingdom",
    "20 Regional Coins from the Seaside Kingdom",
    "30 Regional Coins from the Seaside Kingdom",
    "40 Regional Coins from the Seaside Kingdom",
    "50 Regional Coins from the Seaside Kingdom",
    "3 Fountain-Seal Power Moons (Seaside Kingdom)",
    "4 Fountain-Seal Power Moons (Seaside Kingdom)",
    "Uncork 2 Fountains (Seaside Kingdom)",
    "Uncork 3 Fountains (Seaside Kingdom)",
    "Uncork 4 Fountains (Seaside Kingdom)",
    "1 Timer Challenge from the Seaside Kingdom",
    "2 Timer Challenges from the Seaside Kingdom",
    "Power Moon from Seaside Kingdom Hint Art",
    "Reach the Seaside Kingdom with a Warp-Painting",
    "Mollusque-Lanceur's Attack on the Beach! (Seaside Kingdom)",
    "Peach in the Seaside Kingdom",
    "Koopa Freerunning (Seaside Kingdom) in under 50 Seconds",
    "1 Power Moon from Seaside Kingdom Seeds",
    "Purchase a Power Moon from the Seaside Kingdom",
    "Bubblaine Secret Room: A Relaxing Dance (Seaside Kingdom)",
    "Entire \"Underwater Tunnel to the Lighthouse\" without a Cheep Cheep (Seaside Kingdom)",
    "Power Moon on the Beach! Good Dog! (Seaside Kingdom)",
    "Jump, Man! 100 Points on Beach Volleyball! (Seaside Kingdom)",
    "Goombette in the Rolling Canyon (Seaside Kingdom)",
    "Purchase the Bubblaine Sticker (Seaside Kingdom)",
    "Purchase 1 Souvenir from the Seaside Kingdom",
    "Captain Toad in the Seaside Kingdom",
    "2 Power Moons from sub-areas (Seaside Kingdom)",
    "4 Power Moons from sub-areas (Seaside Kingdom)",
    "4 Checkpoints from the Seaside Kingdom",
    "5 Checkpoints from the Seaside Kingdom",
    "6 Checkpoints from the Seaside Kingdom",
    "30 Power Moons from the Luncheon Kingdom",
    "35 Power Moons from the Luncheon Kingdom",
    "40 Power Moons from the Luncheon Kingdom",
    "20 Regional Coins from the Luncheon Kingdom",
    "30 Regional Coins from the Luncheon Kingdom",
    "40 Regional Coins from the Luncheon Kingdom",
    "50 Regional Coins from the Luncheon Kingdom",
    "Mount Volbono Secret Room: Heat Up the First Pot! (Luncheon Kingdom)",
    "Mount Volbono Secret Room: Heat Up the Second Pot! (Luncheon Kingdom)",
    "Bonneter Hat-and-Seek: Plaza Festival! (Luncheon Kingdom)",
    "Cookatiel Confrontation at Mount Volbono (Luncheon Kingdom)",
    "Peach in the Luncheon Kingdom",
    "Captain Toad in the Luncheon Kingdom",
    "Reach the Luncheon Kingdom with a Warp-Painting",
    "Power Moon from Luncheon Kingdom Hint Art",
    "Koopa Freerunning (Luncheon Kingdom) in under 50 Seconds",
    "2 Power Moon from Golden Turnips (Luncheon Kingdom)",
    "3 Power Moons from Golden Turnips (Luncheon Kingdom)",
    "Luncheon Kingdom Slots",
    "Power Moon from the Rabbit (Luncheon Kingdom)",
    "Music-Toad in the Luncheon Kingdom",
    "1 Timer Challenge from the Luncheon Kingdom",
    "2 Timer Challenges from the Luncheon Kingdom",
    "3 Timer Challenges from the Luncheon Kingdom",
    "Mechanic in the Plaza! Fix Up the Steam Gardener! (Luncheon Kingdom)",
    "Goombette over the Lava (Luncheon Kingdom)",
    "Purchase a Power Moon from the Luncheon Kingdom",
    "Peronza Plaza: Heat Up the Pot (Luncheon Kingdom)",
    "On the Remote Island! Fix Up those Cracks! (Luncehon Kingdom)",
    "Purchase the Mount Volbono Sticker (Luncheon Kingdom)",
    "Purchase 1 Souvenir from the Luncheon Kingdom",
    "2 Power Moons from sub-areas (Luncheon Kingdom)",
    "4 Power Moons from sub-areas (Luncheon Kingdom)",
    "6 Power Moons from sub-areas (Luncheon Kingdom)",
    "4 Checkpoints from the Luncheon Kingdom",
    "5 Checkpoints from the Luncheon Kingdom",
    "6 Checkpoints from the Luncheon Kingdom",
    "5 Power Moons from the Ruined Kingdom",
    "Peach in the Ruined Kingdom",
    "Throw Cappy at All the Swords (Ruined Kingdom)",
    "15 Power Moons from Bowser's Kingdom",
    "20 Power Moons from Bowser's Kingdom",
    "25 Power Moons from Bowser's Kingdom",
    "30 Power Moons from Bowser's Kingdom",
    "20 Regional Coins from Bowser's Kingdom",
    "30 Regional Coins from Bowser's Kingdom",
    "40 Regional Coins from Bowser's Kingdom",
    "50 Regional Coins from Bowser's Kingdom",
    "Peach in Bowser's Kingdom",
    "Purchase a Power Moon from Bowser's Kingdom",
    "Reach Bowser's Kingdom with a Warp-Painting",
    "Power Moon from Bowser's Kingdom Hint Art",
    "Power Moon from the Rabbit (Bowser's Kingdom)",
    "1 Timer Challenge from Bowser's Kingdom",
    "Bonneter Scientist: Pokio in the Castle! (Bowser's Kingdom)",
    "Lakitu-Fishing Power Moon (Bowser's Kingdom)",
    "Koopa Freerunning (Bowser's Kingdom) in under 105 Seconds",
    "\"Showdown Arena\" Checkpoint Flag (Bowser's Kingdom)",
    "Open the Front Door to Bowser's Castle (post-game)",
    "Bowser's Castle Secret Room: 8-bit Samurai Action (Bowser's Kingdom)",
    "Captain Toad in Bowser's Kingdom",
    "Purchase 1 Souvenir from Bowser's Kingdom",
    "Purchase the Bowser's Castle Sticker (Bowser's Kingdom)",
    "Flying Sphynx: Over Bowser's Castle (Bowser's Kingdom)",
    "8 Checkpoints from Bowser's Kingdom",
    "9 Checkpoints from Bowser's Kingdom",
    "10 Checkpoints from Bowser's Kingdom",
    "2 Power Moons from sub-areas (Bowser's Kingdom)",
    "4 Power Moons from sub-areas (Bowser's Kingdom)",
    "10 Power Moons from the Moon Kingdom",
    "15 Power Moons from the Moon Kingdom",
    "20 Regional Coins from the Moon Kingdom",
    "30 Regional Coins from the Moon Kingdom",
    "Purchase the Full Space-Suit Costume (Moon Kingdom)",
    "Peach in the Moon Kingdom",
    "Power Moon from the Rabbit (Moon Kingdom)",
    "Koopa Freerunning (Moon Kingdom) in under 60 Seconds",
    "Power Moon from Moon Kingdom Hint Art",
    "Return of Doctor Mario! Heal the Shiverian! (Moon Kingdom)",
    "Power Moon on the Moon! Good Dog! (Moon Kingdom)",
    "1 Power Moon from the Underground Moon Caverns (Moon Kingdom)",
    "1 Timer Challenge from the Moon Kingdom",
    "Purchase a Power Moon from the Moon Kingdom",
    "Purchase 1 Souvenir from the Moon Kingdom",
    "Purchase the Honeylune Ridge Sticker (Moon Kingdom)",
    "Captain Toad in the Moon Kingdom",
    "3 Checkpoints from the Moon Kingdom",
    "Score 85 Points on Koopa Trace-Walking (Moon Kingdom)",
    "10 Power Moons from the Mushroom Kingdom (excluding Toadette)",
    "15 Power Moons from the Mushroom Kingdom (excluding Toadette)",
    "20 Power Moons from the Mushroom Kingdom (excluding Toadette)",
    "20 Regional Coins from the Mushroom Kingdom",
    "30 Regional Coins from the Mushroom Kingdom",
    "40 Regional Coins from the Mushroom Kingdom",
    "Knucklotec's Icy Rematch! (Mushroom Kingdom)",
    "Torkdrift's Flowery Rematch! (Mushroom Kingdom)",
    "Mechwiggler's Mecha-Rematch! (Mushroom Kingdom)",
    "Mollusque-Lanceur's Aerial Rematch! (Mushroom Kingdom)",
    "Cookatiel's Volcanic Rematch! (Mushroom Kingdom)",
    "Ruined Dragon's Electrical Rematch! (Mushroom Kingdom)",
    "2 Boss-Rematch Multi Moons (Mushroom Kingdom)",
    "3 Boss-Rematch Multi Moons (Mushroom Kingdom)",
    "10 Power Moons from Toadette (Mushroom Kingdom)",
    "15 Power Moons from Toadette (Mushroom Kingdom)",
    "Koopa Freerunning (Mushroom Kingdom) in under 20 Seconds",
    "Power Moon from Mushroom Kingdom Hint Art",
    "Eat 10 Berries with Yoshi (Mushroom Kingdom)",
    "1 Power Moon from Mushroom Kingdom Seeds",
    "\"Toad Defender\" Power Moon (Mushroom Kingdom)",
    "Power Moon from the Rabbit (Mushroom Kingdom)",
    "Score 85 Points on Picture Match (Mushroom Kingdom)",
    "Purchase a Power Moon from the Mushroom Kingdom",
    "Peach's Castle Secret Room: Nostaligic Getaway (Mushroom Kingdom)",
    "Goombette Encounter behind Peach's Castle (Mushroom Kingdom)",
    "Captain Toad in the Mushroom Kingdom",
    "Purchase the Peach's Castle Sticker (Mushroom Kingdom)",
    "Purchase the ?-Block Sticker (Mushroom Kingdom)",
    "Purchase the Brick-Block Sticker (Mushroom Kingdom)",
    "Purchase the Coin Sticker (Mushroom Kingdom)",
    "Purchase the Warp Pipe Sticker (Mushroom Kingdom)",
    "Purchase 1 Souvenir from the Mushroom Kingdom",
    "Try to Enter the Wing Cap Stage (Mushroom Kingdom)",
    "Purchase 2 Stickers from the Mushroom Kingdom",
    "Purchase 3 Stickers from the Mushroom Kingdom",
    "2 Checkpoints from the Mushroom Kingdom",
    "3 Checkpoints from the Mushroom Kingdom",
    "Music-Toad in the Mushroom Kingdom",
    "Bonneter Hat-and-Seek: At Peach's Castle (Mushroom Kingdom)",
    "1 Timer Challenge from the Mushroom Kingdom"
];
