bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Defeat a snail",
    "10+ Energy Tanks",
    "10+ Total Hearts",
    "100+ Missiles",
    "11+ Energy Tanks",
    "12 Heart Pieces",
    "12+ Total Hearts",
    "15+ Power Bombs",
    "15+ Super Missiles",
    "2 Crystals",
    "2 Dark World Dungeons",
    "2 Dungeon Blue Rupee Rooms",
    "2 Light World Dungeons",
    "2 Pendants",
    "2+ Reserve Tanks",
    "20 Bombs",
    "20+ Power Bombs",
    "20+ Super Missiles",
    "25+ Power Bombs",
    "25+ Super Missiles",
    "3 A-Items",
    "3 Crystals",
    "3 Dark World Dungeons",
    "3 Light World Dungeons",
    "3 Whirlpool Pairs",
    "3+ Energy Tanks",
    "3+ Reserve Tanks",
    "30 Bombs",
    "30+ Power Bombs",
    "30+ Super Missiles",
    "35+ Super Missiles",
    "4 Heart Containers",
    "4 NPC/Object Followers",
    "4+ Energy Tanks",
    "4+ Energy Tanks and 15+ Power Bombs",
    "4+ Energy Tanks and 35+ Missiles",
    "40 Arrows",
    "40 Arrows and 20 Bombs",
    "40+ Power Bombs",
    "5+ Energy Tanks",
    "50 Arrows",
    "50+ Missiles",
    "6 Heart Containers",
    "6+ Energy Tanks",
    "60+ Missiles and 20+ Super Missiles",
    "7+ Energy Tanks",
    "7+ Energy Tanks and 70+ Missiles",
    "75+ Missiles",
    "8 Heart Pieces",
    "8+ Energy Tanks",
    "9+ Energy Tanks",
    "Activate 4+ Brinstar Save Stations",
    "Activate Both Brinstar Missile Recharge Stations",
    "Activate Both Norfair Energy Recharge Stations",
    "Activate Brinstar, Maridia, and Wrecked Ship Map Stations",
    "Activate Crateria Save Station",
    "Activate Lower Norfair Save Station",
    "Activate Wrecked Ship Map Station",
    "Activate all 3 Brinstar Energy Recharge Stations",
    "Activate all Maridia Save Stations",
    "Activate the Flute",
    "Bomb open a cracked door in any dungeon",
    "Bomb open a cracked floor in any dungeon",
    "Bonk Grave",
    "Bottled Bee",
    "Bottled Faerie",
    "Bottled Potion",
    "Break Bombos Monolith",
    "Break Ether Monolith",
    "Brinstar Reserve Tank (Mockball) Pedestal",
    "Burn a Ball + Chain Trooper",
    "Burn a Floating Stalfos Skull",
    "Buy from 2 Shops in each World",
    "Byrna Cave",
    "Charge Pedestal",
    "Clear 2 Tile Rooms",
    "Collect 11+ Combined Energy Tanks and Reserve Tanks",
    "Collect 50+ Combined Super Missiles and Power Bombs",
    "Collect Charge Beam",
    "Collect Charge Beam, Spazer, Wave Beam, Ice Beam, and Plasma Beam",
    "Collect Grapple Beam",
    "Collect Hi-Jump Boots, Speed Booster, and Space Jump",
    "Collect HiJump Boots",
    "Collect Ice Beam",
    "Collect Morph Ball Bombs",
    "Collect Plasma Beam",
    "Collect Rod + Cane of opposite colors",
    "Collect Rod + Cane of the same color",
    "Collect Sahasrahla's Prize",
    "Collect Screw Attack",
    "Collect Space Jump",
    "Collect Spazer Beam",
    "Collect Speed Booster",
    "Collect Springball",
    "Collect Wave Beam",
    "Collect X-Ray Scope",
    "Collect a Medallion",
    "Collect the Bow",
    "Collect the Hookshot",
    "Collect the Lantern",
    "Complete 1 Line of Y-Items",
    "Crateria Power Bomb Pedestal",
    "Darkness Map",
    "Death Mountain Lonely Island",
    "Defeat Agahnim",
    "Defeat Armos",
    "Defeat Arrghus",
    "Defeat Blind",
    "Defeat Botwoon",
    "Defeat Crocomire",
    "Defeat Crocomire and Draygon",
    "Defeat Crocomire and Ridley",
    "Defeat Draygon",
    "Defeat Golden Torizo",
    "Defeat Golden Torizo and Spore Spawn",
    "Defeat Helmasaur King",
    "Defeat Kholdstare",
    "Defeat Lanmolas",
    "Defeat Moldorm",
    "Defeat Mothula",
    "Defeat Ridley",
    "Defeat Spore Spawn",
    "Defeat Spore Spawn and Botwoon",
    "Defeat Vitreous",
    "Defeat a Deadrock",
    "Defeat a Lynel",
    "Defeat a Mochtroid\"",
    "Defeat a Red Eyegore and Red Mimic",
    "Defeat all 6 Freezors",
    "Desert Map",
    "Desert Palace Big Chest",
    "Desert Palace Compass",
    "Destroy at least 1 of the 4 Golden Statues",
    "Destroy at least 2 of the 4 Golden Statues",
    "Die to Trinexx",
    "Finish as a Bunny",
    "Finish at Landing site",
    "Finish in 'Mama Turtle' room",
    "Finish in Grapple Beam room",
    "Finish in Kraid's room",
    "Finish in Metal Pirate room",
    "Finish in Spore Spawn's room",
    "Finish in Springball room",
    "Finish in Wrecked Ship Energy Tank room",
    "Finish in X-Ray Scope room",
    "Finish in a Dark Room",
    "Finish in a Light World Dungeon Fairy Room",
    "Finish in a Prison Cell",
    "Finish in a Room with a Bumper",
    "Finish in a Room with a Firebar",
    "Finish in a Room with a Firesnake",
    "Finish in a Room with an Orange Warp",
    "Finish in a Rupee Floor Room",
    "Finish in a Shinespark or Crystal Flash",
    "Finish in a Trap Room",
    "Finish in an Elevator",
    "Finish near Spazer, Charge Beam, Ice Beam, Wave Beam, or Plasma Beam",
    "Freeze a Bomb Slug",
    "Freeze a Dodongo",
    "Freeze a fireflea",
    "Freeze a waver",
    "Fully explore the Landing Site",
    "Fully explore the Wrecked Ship",
    "Go bowling",
    "Grapple Beam Pedestal",
    "Grapple onto an enemy",
    "Hera Map",
    "Hit Crystal Switch with Frozen Enemy",
    "Ice Map",
    "Ice Palace Big Chest",
    "Ice Palace Compass",
    "Ice Pedestal",
    "Kill Shaktool",
    "Lake Hylia Island",
    "Lantern or Fire Rod",
    "Lumberjack Tree",
    "Master Sword Pedestal",
    "Mimic Cave",
    "Mire Map",
    "Misery Mire Big Chest",
    "Misery Mire Compass",
    "Move or destroy a wall in any dungeon",
    "Norfair Reserve Tank or Wrecked Ship Reserve Tank",
    "Open 4 Small Key Doors (Skull Woods)",
    "Open 5 Small Key Doors (Palace of Darkness)",
    "Open 6 Small Key Doors (Ice Palace)",
    "Open 6 Small Key Doors (Misery Mire)",
    "Open Misery Mire",
    "Open Purple Chest",
    "Open Turtle Rock",
    "Palace of Darkness Big Chest",
    "Palace of Darkness Compass",
    "Pay the Hamburger Helper Hand",
    "Perfect Archery Game",
    "Plasma Pedestal",
    "Pull a Tounge Statue",
    "Read 3 Dark World Dungeon Telepathic Tiles",
    "Rescue the Dwarf",
    "Reveal a Hidden Cave under a rock in both Worlds",
    "Skull Map",
    "Skull Woods Big Chest",
    "Skull Woods Compass",
    "Spawn a chest in 2 dungeons",
    "Spazer Pedestal",
    "Speak to Fat Faerie",
    "Speed Booster Pedestal",
    "Spend 1000 rupees",
    "Spend 1500 rupees",
    "Stun a Pikit",
    "Stun a Turtle",
    "Swamp Map",
    "Swamp Palace Big Chest",
    "Swamp Palace Compass",
    "TRock Map",
    "Thieves' Map",
    "Thieves' Town Big Chest",
    "Thieves' Town Compass",
    "Tower of Hera Big Chest",
    "Tower of Hera Compass",
    "Turtle Rock Big Chest",
    "Turtle Rock Compass",
    "Upgrade Shield",
    "Upgrade Sword",
    "Visit Crateria Shaft Supers",
    "Visit Crateria-Lake Hylia Portal",
    "Visit Crateria-Maridia Elevator",
    "Visit Grapple Beam Pedestal or Wrecked Ship Energy Tank",
    "Visit Lower Norfair Elevator",
    "Visit Lower Norfair-Misery Mire Portal\"",
    "Visit Maridia-Dark Lake Hylia Portal\"",
    "Visit Norfair-Death Mountain Portal\"",
    "Visit Plasma Beam Pedestal or defeat Ridley",
    "Visit Screw Attack Pedestal",
    "Visit Shaktool",
    "Visit Shaktool or defeat Draygon",
    "Visit the Catfish with a Follower",
    "Visit the critters",
    "Visit the front of Gauntlet and Terminator",
    "Visit the front of Gauntlet or X-Ray Pedestal",
    "Visit the left sand pit",
    "Visit the right sand pit",
    "Wave Pedestal",
    "Wrecked Ship Energy Tank Pedestal",
    "Wrecked Ship Reserve Tank"
];
