bingoGenerator = require("./generators/generator_bases/ladx_generator.js");

var bingoList = [
    { "name": "6 Moons (Cap)", "group": "Cap_Moons" },
    { "name": "8 Moons (Cap)", "group": "Cap_Moons" },
    { "name": "10 Moons (Cap)", "group": "Cap_Moons" },
    { "name": "30 Regional Coins (Cap)", "group": "Cap_Regional" },
    { "name": "35 Regional Coins (Cap)", "group": "Cap_Regional" },
    { "name": "40 Regional Coins (Cap)", "group": "Cap_Regional" },
    { "name": "45 Regional Coins (Cap)", "group": "Cap_Regional" },
    { "name": "4 Moons from sub-areas (Cap)", "group": "Cap" },
    { "name": "6 Moons from sub-areas (Cap)", "group": "Cap" },
    { "name": "2 Checkpoints (Cap)", "group": "Cap" },
    { "name": "14 Moons (Cascade)", "group": "Cascade_Moons" },
    { "name": "16 Moons (Cascade)", "group": "Cascade_Moons" },
    { "name": "18 Moons (Cascade)", "group": "Cascade_Moons" },
    { "name": "20 Moons (Cascade)", "group": "Cascade_Moons" },
    { "name": "35 Regional Coins (Cascade)", "group": "Cascade_Regional" },
    { "name": "40 Regional Coins (Cascade)", "group": "Cascade_Regional" },
    { "name": "45 Regional Coins (Cascade)", "group": "Cascade_Regional" },
    { "name": "50 Regional Coins (Cascade)", "group": "Cascade_Regional" },
    { "name": "4 Moons from sub-areas (Cascade)", "group": "Cascade" },
    { "name": "6 Moons from sub-areas (Cascade)", "group": "Cascade" },
    { "name": "4 Checkpoints (Cascade)", "group": "Cascade" },
    { "name": "36 Moons (Sand)", "group": "Sand_Moons" },
    { "name": "38 Moons (Sand)", "group": "Sand_Moons" },
    { "name": "40 Moons (Sand)", "group": "Sand_Moons" },
    { "name": "42 Moons (Sand)", "group": "Sand_Moons" },
    { "name": "44 Moons (Sand)", "group": "Sand_Moons" },
    { "name": "46 Moons (Sand)", "group": "Sand_Moons" },
    { "name": "48 Moons (Sand)", "group": "Sand_Moons" },
    { "name": "50 Moons (Sand)", "group": "Sand_Moons" },
    { "name": "45 Regional Coins (Sand)", "group": "Sand_Regional" },
    { "name": "50 Regional Coins (Sand)", "group": "Sand_Regional" },
    { "name": "55 Regional Coins (Sand)", "group": "Sand_Regional" },
    { "name": "60 Regional Coins (Sand)", "group": "Sand_Regional" },
    { "name": "65 Regional Coins (Sand)", "group": "Sand_Regional" },
    { "name": "70 Regional Coins (Sand)", "group": "Sand_Regional" },
    { "name": "4 Moons from sub-areas (Sand)", "group": "Sand" },
    { "name": "6 Moons from sub-areas (Sand)", "group": "Sand" },
    { "name": "8 Moons from sub-areas (Sand)", "group": "Sand" },
    { "name": "7 Checkpoints (Sand)", "group": "Sand" },
    { "name": "8 Checkpoints (Sand)", "group": "Sand" },
    { "name": "9 Checkpoints (Sand)", "group": "Sand" },
    { "name": "Moon Shards in the Sand (Sand)", "group": "Sand" },
    { "name": "Koopa Trace-Walking (Sand)", "group": "Sand" },
    { "name": "Ice Cave Treasure-Moon (Sand)", "group": "Sand" },
    { "name": "Herding Sheep in the Dunes (Sand)", "group": "Sand" },
    { "name": "Call Jaxi from 5 Stands", "group": "Jaxi" },
    { "name": "Call Jaxi from 6 Stands", "group": "Jaxi" },
    { "name": "Call Jaxi from 7 Stands", "group": "Jaxi" },
    { "name": "18 Moons (Lake)", "group": "Lake_Moons" },
    { "name": "20 Moons (Lake)", "group": "Lake_Moons" },
    { "name": "22 Moons (Lake)", "group": "Lake_Moons" },
    { "name": "24 Moons (Lake)", "group": "Lake_Moons" },
    { "name": "30 Regional Coins (Lake)", "group": "Lake_Regional" },
    { "name": "35 Regional Coins (Lake)", "group": "Lake_Regional" },
    { "name": "40 Regional Coins (Lake)", "group": "Lake_Regional" },
    { "name": "45 Regional Coins (Lake)", "group": "Lake_Regional" },
    { "name": "4 Moons from sub-areas (Lake)", "group": "Lake" },
    { "name": "5 Checkpoints (Lake)", "group": "Lake" },
    { "name": "Plant 1 Seed (Lake)", "group": "Seeds" },
    { "name": "Puzzle Room Solved! (Lake)", "group": "Lake" },
    { "name": "30 Moons (Wooded)", "group": "Wooded_Moons" },
    { "name": "32 Moons (Wooded)", "group": "Wooded_Moons" },
    { "name": "34 Moons (Wooded)", "group": "Wooded_Moons" },
    { "name": "36 Moons (Wooded)", "group": "Wooded_Moons" },
    { "name": "38 Moons (Wooded)", "group": "Wooded_Moons" },
    { "name": "40 Moons (Wooded)", "group": "Wooded_Moons" },
    { "name": "50 Regional Coins (Wooded)", "group": "Wooded_Regional" },
    { "name": "55 Regional Coins (Wooded)", "group": "Wooded_Regional" },
    { "name": "60 Regional Coins (Wooded)", "group": "Wooded_Regional" },
    { "name": "65 Regional Coins (Wooded)", "group": "Wooded_Regional" },
    { "name": "70 Regional Coins (Wooded)", "group": "Wooded_Regional" },
    { "name": "75 Regional Coins (Wooded)", "group": "Wooded_Regional" },
    { "name": "6 Moons from sub-areas (Wooded)", "group": "Wooded" },
    { "name": "8 Moons from sub-areas (Wooded)", "group": "Wooded" },
    { "name": "10 Moons from sub-areas (Wooded)", "group": "Wooded" },
    { "name": "6 Checkpoints (Wooded)", "group": "Wooded" },
    { "name": "7 Checkpoints (Wooded)", "group": "Wooded" },
    { "name": "8 Checkpoints (Wooded)", "group": "Wooded" },
    { "name": "5 Moons (Deep Woods)", "group": "Deep_Woods" },
    { "name": "6 Moons (Deep Woods)", "group": "Deep_Woods" },
    { "name": "7 Moons (Deep Woods)", "group": "Deep_Woods" },
    { "name": "9 Moons from Nuts", "group": "Nuts" },
    { "name": "10 Moons from Nuts", "group": "Nuts" },
    { "name": "11 Moons from Nuts", "group": "Nuts" },
    { "name": "Goomba Picture-Match (Cloud)", "group": "Cloud" },
    { "name": "18 Moons (Lost)", "group": "Lost_Moons" },
    { "name": "20 Moons (Lost)", "group": "Lost_Moons" },
    { "name": "30 Regional Coins (Lost)", "group": "Lost_Regional" },
    { "name": "35 Regional Coins (Lost)", "group": "Lost_Regional" },
    { "name": "40 Regional Coins (Lost)", "group": "Lost_Regional" },
    { "name": "45 Regional Coins (Lost)", "group": "Lost_Regional" },
    { "name": "3 Checkpoints (Lost)", "group": "Lost" },
    { "name": "Catch the Rabbit! (Lost)", "group": "Lost" },
    { "name": "32 Moons (Metro)", "group": "Metro_Moons" },
    { "name": "34 Moons (Metro)", "group": "Metro_Moons" },
    { "name": "36 Moons (Metro)", "group": "Metro_Moons" },
    { "name": "38 Moons (Metro)", "group": "Metro_Moons" },
    { "name": "40 Moons (Metro)", "group": "Metro_Moons" },
    { "name": "42 Moons (Metro)", "group": "Metro_Moons" },
    { "name": "44 Moons (Metro)", "group": "Metro_Moons" },
    { "name": "45 Regional Coins (Metro)", "group": "Metro_Regional" },
    { "name": "50 Regional Coins (Metro)", "group": "Metro_Regional" },
    { "name": "55 Regional Coins (Metro)", "group": "Metro_Regional" },
    { "name": "60 Regional Coins (Metro)", "group": "Metro_Regional" },
    { "name": "65 Regional Coins (Metro)", "group": "Metro_Regional" },
    { "name": "8 Moons from sub-areas (Metro)", "group": "Metro" },
    { "name": "10 Moons from sub-areas (Metro)", "group": "Metro" },
    { "name": "12 Moons from sub-areas (Metro)", "group": "Metro" },
    { "name": "7 Checkpoints (Metro)", "group": "Metro" },
    { "name": "8 Checkpoints (Metro)", "group": "Metro" },
    { "name": "9 Checkpoints (Metro)", "group": "Metro" },
    { "name": "RC Car: Race Complete! (Metro)", "group": "Metro" },
    { "name": "Jump-Rope Hero! (Metro)", "group": "Metro" },
    { "name": "Catch the Rabbit! (Metro)", "group": "Metro" },
    { "name": "20 Moons (Snow)", "group": "Snow_Moons" },
    { "name": "22 Moons (Snow)", "group": "Snow_Moons" },
    { "name": "24 Moons (Snow)", "group": "Snow_Moons" },
    { "name": "26 Moons (Snow)", "group": "Snow_Moons" },
    { "name": "25 Regional Coins (Snow)", "group": "Snow_Regional" },
    { "name": "30 Regional Coins (Snow)", "group": "Snow_Regional" },
    { "name": "35 Regional Coins (Snow)", "group": "Snow_Regional" },
    { "name": "40 Regional Coins (Snow)", "group": "Snow_Regional" },
    { "name": "2 Checkpoints (Snow)", "group": "Snow" },
    { "name": "3 Barrier-Moons (Snow)", "group": "Snow" },
    { "name": "4 Barrier-Moons (Snow)", "group": "Snow" },
    { "name": "2 Moons from sub-areas (Snow)", "group": "Snow" },
    { "name": "Koopa Trace-Walking (Snow)", "group": "Snow" },
    { "name": "Catch the Rabbit! (Snow)", "group": "Snow" },
    { "name": "22 Moons (Seaside)", "group": "Seaside_Moons" },
    { "name": "24 Moons (Seaside)", "group": "Seaside_Moons" },
    { "name": "26 Moons (Seaside)", "group": "Seaside_Moons" },
    { "name": "28 Moons (Seaside)", "group": "Seaside_Moons" },
    { "name": "30 Moons (Seaside)", "group": "Seaside_Moons" },
    { "name": "32 Moons (Seaside)", "group": "Seaside_Moons" },
    { "name": "34 Moons (Seaside)", "group": "Seaside_Moons" },
    { "name": "45 Regional Coins (Seaside)", "group": "Seaside_Regional" },
    { "name": "50 Regional Coins (Seaside)", "group": "Seaside_Regional" },
    { "name": "55 Regional Coins (Seaside)", "group": "Seaside_Regional" },
    { "name": "60 Regional Coins (Seaside)", "group": "Seaside_Regional" },
    { "name": "65 Regional Coins (Seaside)", "group": "Seaside_Regional" },
    { "name": "70 Regional Coins (Seaside)", "group": "Seaside_Regional" },
    { "name": "4 Moons from sub-areas (Seaside)", "group": "Seaside" },
    { "name": "6 Moons from sub-areas (Seaside)", "group": "Seaside" },
    { "name": "7 Checkpoints (Seaside)", "group": "Seaside" },
    { "name": "8 Checkpoints (Seaside)", "group": "Seaside" },
    { "name": "9 Checkpoints (Seaside)", "group": "Seaside" },
    { "name": "Uncork 3 Fountains (Seaside)", "group": "Uncork" },
    { "name": "Uncork 4 Fountains (Seaside)", "group": "Uncork" },
    { "name": "24 Moons (Luncheon)", "group": "Luncheon_Moons" },
    { "name": "26 Moons (Luncheon)", "group": "Luncheon_Moons" },
    { "name": "28 Moons (Luncheon)", "group": "Luncheon_Moons" },
    { "name": "30 Moons (Luncheon)", "group": "Luncheon_Moons" },
    { "name": "25 Regional Coins (Luncheon)", "group": "Luncheon_Regional" },
    { "name": "30 Regional Coins (Luncheon)", "group": "Luncheon_Regional" },
    { "name": "35 Regional Coins (Luncheon)", "group": "Luncheon_Regional" },
    { "name": "40 Regional Coins (Luncheon)", "group": "Luncheon_Regional" },
    { "name": "45 Regional Coins (Luncheon)", "group": "Luncheon_Regional" },
    { "name": "4 Moons from sub-areas (Luncheon)", "group": "Luncheon" },
    { "name": "6 Moons from sub-areas (Luncheon)", "group": "Luncheon" },
    { "name": "8 Moons from sub-areas (Luncheon)", "group": "Luncheon" },
    { "name": "5 Checkpoints (Luncheon)", "group": "Luncheon" },
    { "name": "6 Checkpoints (Luncheon)", "group": "Luncheon" },
    { "name": "7 Checkpoints (Luncheon)", "group": "Luncheon" },
    { "name": "2 Moons from Golden Turnips", "group": "Turnips" },
    { "name": "3 Moons from Golden Turnips", "group": "Turnips" },
    { "name": "2 Moons from sub-areas (Ruined)", "group": "Ruined" },
    { "name": "12 Moons (Bowser's)", "group": "Bowser_Moons" },
    { "name": "14 Moons (Bowser's)", "group": "Bowser_Moons" },
    { "name": "16 Moons (Bowser's)", "group": "Bowser_Moons" },
    { "name": "18 Moons (Bowser's)", "group": "Bowser_Moons" },
    { "name": "20 Moons (Bowser's)", "group": "Bowser_Moons" },
    { "name": "25 Regional Coins (Bowser's)", "group": "Bowser_Moons" },
    { "name": "30 Regional Coins (Bowser's)", "group": "Bowser_Moons" },
    { "name": "35 Regional Coins (Bowser's)", "group": "Bowser_Moons" },
    { "name": "40 Regional Coins (Bowser's)", "group": "Bowser_Moons" },
    { "name": "2 Moons from sub-areas (Bowser's)", "group": "Bowser" },
    { "name": "4 Moons from sub-areas (Bowser's)", "group": "Bowser" },
    { "name": "9 Checkpoints (Bowser's)", "group": "Bowser" },
    { "name": "10 Checkpoints (Bowser's)", "group": "Bowser" },
    { "name": "4 Moons (Moon)", "group": "Moon_Moons" },
    { "name": "6 Moons (Moon)", "group": "Moon_Moons" },
    { "name": "8 Moons (Moon)", "group": "Moon_Moons" },
    { "name": "20 Regional Coins (Moon)", "group": "Moon_Regional" },
    { "name": "25 Regional Coins (Moon)", "group": "Moon_Regional" },
    { "name": "30 Regional Coins (Moon)", "group": "Moon_Regional" },
    { "name": "35 Regional Coins (Moon)", "group": "Moon_Regional" },
    { "name": "3 Checkpoints (Moon)", "group": "Moon" },
    { "name": "Purchase 8 Hats", "group": "Hats" },
    { "name": "Purchase 9 Hats", "group": "Hats" },
    { "name": "Purchase 10 Hats", "group": "Hats" },
    { "name": "2 Moons from Slots", "group": "Slots" },
    { "name": "3 Moons from Slots", "group": "Slots" },
    { "name": "1 Moon from Lakitu-Fishing", "group": "Fishing" },
    { "name": "18 Moons from sub-areas (Total)", "group": "Sub_Areas" },
    { "name": "20 Moons from sub-areas (Total)", "group": "Sub_Areas" },
    { "name": "22 Moons from sub-areas (Total)", "group": "Sub_Areas" },
    { "name": "24 Moons from sub-areas (Total)", "group": "Sub_Areas" },
    { "name": "26 Moons from sub-areas (Total)", "group": "Sub_Areas" },
    { "name": "28 Moons from sub-areas (Total)", "group": "Sub_Areas" },
    { "name": "30 Moons from sub-areas (Total)", "group": "Sub_Areas" },
    { "name": "Capture both the Cactus and the Tree", "group": "Capture_Both" },
    { "name": "Look at 3 Hint Arts", "group": "Hint_View" },
    { "name": "Look at 4 Hint Arts", "group": "Hint_View" },
    { "name": "Look at 5 Hint Arts", "group": "Hint_View" },
    { "name": "4 Stickers", "group": "Stickers" },
    { "name": "5 Stickers", "group": "Stickers" },
    { "name": "6 Stickers", "group": "Stickers" },
    { "name": "7 Stickers", "group": "Stickers" },
    { "name": "3 Warp-Painting Moons", "group": "Warp_Painting" },
    { "name": "4 Warp-Painting Moons", "group": "Warp_Painting" },
    { "name": "5 Warp-Painting Moons", "group": "Warp_Painting" },
    { "name": "Purchase 6 Souvenirs", "group": "Souvenirs" },
    { "name": "Purchase 8 Souvenirs", "group": "Souvenirs" },
    { "name": "Purchase 10 Souvenirs", "group": "Souvenirs" },
    { "name": "Wear the Boxer Shorts", "group": "Nipple_Percent" },
    { "name": "7 Timer Challenges", "group": "Timer" },
    { "name": "8 Timer Challenges", "group": "Timer" },
    { "name": "9 Timer Challenges", "group": "Timer" },
    { "name": "10 Timer Challenges", "group": "Timer" },
    { "name": "11 Timer Challenges", "group": "Timer" },
    { "name": "Purchase 6 Full Costume Sets", "group": "Outfits" },
    { "name": "Purchase 7 Full Costume Sets", "group": "Outfits" },
    { "name": "Purchase 8 Full Costume Sets", "group": "Outfits" },
    { "name": "Purchase 9 Full Costume Sets", "group": "Outfits" },
    { "name": "5 Captain Toad Moons", "group": "Captain_Toad" },
    { "name": "6 Captain Toad Moons", "group": "Captain_Toad" },
    { "name": "7 Captain Toad Moons", "group": "Captain_Toad" },
    { "name": "7 Moons from 8-bit Sections", "group": "8bit" },
    { "name": "9 Moons from 8-bit Sections", "group": "8bit" },
    { "name": "11 Moons from 8-bit Sections", "group": "8bit" },
    { "name": "5 Moons from Moon Shards", "group": "Moon_Shards" },
    { "name": "6 Moons from Moon Shards", "group": "Moon_Shards" },
    { "name": "7 Moons from Moon Shards", "group": "Moon_Shards" },
    { "name": "8 Moons from Moon Shards", "group": "Moon_Shards" },
    { "name": "9 Moons from Moon Shards", "group": "Moon_Shards" },
    { "name": "5 Moons from Music Notes", "group": "Music_Notes" },
    { "name": "6 Moons from Music Notes", "group": "Music_Notes" },
    { "name": "7 Moons from Music Notes", "group": "Music_Notes" },
    { "name": "3 Moons from Shiny Rocks", "group": "Shiny_Rocks" },
    { "name": "Purchase 6 Moons", "group": "Shop_Moons" },
    { "name": "Purchase 7 Moons", "group": "Shop_Moons" },
    { "name": "Purchase 8 Moons", "group": "Shop_Moons" },
    { "name": "7 Treasure Chest Moons", "group": "Treasure_Chest" },
    { "name": "9 Treasure Chest Moons", "group": "Treasure_Chest" },
    { "name": "11 Treasure Chest Moons", "group": "Treasure_Chest" },
    { "name": "3 Moons from Wooden Crates", "group": "Crates" },
    { "name": "4 Moons from Wooden Crates", "group": "Crates" },
    { "name": "26 Unique Captures", "group": "Unique_Captures" },
    { "name": "28 Unique Captures", "group": "Unique_Captures" },
    { "name": "30 Unique Captures", "group": "Unique_Captures" },
    { "name": "32 Unique Captures", "group": "Unique_Captures" },
    { "name": "34 Unique Captures", "group": "Unique_Captures" },
    { "name": "36 Unique Captures", "group": "Unique_Captures" },
    { "name": "2 Moons from Hint Art", "group": "Hint_Moons" },
    { "name": "3 Moons from Hint Art", "group": "Hint_Moons" },
    { "name": "Plant 6 Seeds (Total)", "group": "Seeds" },
    { "name": "Plant 7 Seeds (Total)", "group": "Seeds" },
    { "name": "Plant 8 Seeds (Total)", "group": "Seeds" },
    { "name": "150 Total Regional Coins", "group": "Regional_Coins" },
    { "name": "175 Total Regional Coins", "group": "Regional_Coins" },
    { "name": "200 Total Regional Coins", "group": "Regional_Coins" },
    { "name": "225 Total Regional Coins", "group": "Regional_Coins" },
    { "name": "250 Total Regional Coins", "group": "Regional_Coins" },
    { "name": "275 Total Regional Coins", "group": "Regional_Coins" },
    { "name": "300 Total Regional Coins", "group": "Regional_Coins" },
    { "name": "145 Moons (Total)", "group": "Total_Moons" },
    { "name": "150 Moons (Total)", "group": "Total_Moons" },
    { "name": "155 Moons (Total)", "group": "Total_Moons" },
    { "name": "160 Moons (Total)", "group": "Total_Moons" },
    { "name": "3 Moons from Goombas", "group": "Goomba" },
    { "name": "4 Moons from Goombas", "group": "Goomba" },
    { "name": "8 Multi Moons", "group": "Multi_Moons" },
    { "name": "9 Multi Moons", "group": "Multi_Moons" },
    { "name": "World Peace Restored! (Sand)", "group": "World_Peace" },
    { "name": "World Peace Restored! (Wooded)", "group": "World_Peace" },
    { "name": "World Peace Restored! (Metro)", "group": "World_Peace" },
    { "name": "World Peace Restored! (Snow)", "group": "World_Peace" },
    { "name": "World Peace Restored! (Seaside)", "group": "World_Peace" },
    { "name": "World Peace Restored! (Luncheon)", "group": "World_Peace" },
    { "name": "World Peace in 5 Kingdoms (excl. Cap, Cloud, Lost, Moon)", "group": "World_Peace" },
    { "name": "World Peace in 6 Kingdoms (excl. Cap, Cloud, Lost, Moon)", "group": "World_Peace" },
    { "name": "2 Moons from Keys", "group": "Keys" },
    { "name": "3 Moons from Keys", "group": "Keys" },
    { "name": "6 Unique Life-Up Hearts (excl. Shops)", "group": "LifeUp" },
    { "name": "8 Unique Life-Up Hearts (excl. Shops)", "group": "LifeUp" },
    { "name": "10 Unique Life-Up Hearts (excl. Shops)", "group": "LifeUp" },
    { "name": "15 Story Moons (excl. Multi Moons)", "group": "Story" },
    { "name": "17 Story Moons (excl. Multi Moons)", "group": "Story" },
    { "name": "19 Story Moons (excl. Multi Moons)", "group": "Story" },
    { "name": "1 Moon from Seeds", "group": "Seeds" },
    { "name": "2 Moons from Seeds", "group": "Seeds" },
    { "name": "All Regional Coins in 3 Kingdoms", "group": "Regional_Kingdoms" },
    { "name": "All Regional Coins in 4 Kingdoms", "group": "Regional_Kingdoms" },
    { "name": "All Regional Coins in 5 Kingdoms", "group": "Regional_Kingdoms" },
    { "name": "Outfit-Door (Sand)", "group": "Locked_Door" },
    { "name": "Outfit-Door (Wooded)", "group": "Locked_Door" },
    { "name": "Outfit-Door (Snow)", "group": "Locked_Door" },
    { "name": "Outfit-Door (Seaside)", "group": "Locked_Door" },
    { "name": "Outfit-Door (Bowser's)", "group": "Locked_Door" }
];
