bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    { name: "Sky Station 1" },
    { name: "Sky Station 2" },
    { name: "Sky Station C" },
    { name: "Sky Station G1" },
    { name: "Sky Station G2" },
    { name: "Sky Station G3" },
    { name: "Yoshi Star 1" },
    { name: "Yoshi Star 2" },
    { name: "Yoshi Star C" },
    { name: "Yoshi Star G1" },
    { name: "Yoshi Star G2" },
    { name: "Yoshi Star G3" },
    { name: "Spin-Dig 1" },
    { name: "Spin-Dig 2" },
    { name: "Spin-Dig C" },
    { name: "Spin-Dig G1" },
    { name: "Spin-Dig G2" },
    { name: "Spin-Dig G3" },
    { name: "Fluffy Bluff 1" },
    { name: "Fluffy Bluff 2" },
    { name: "Fluffy Bluff S" },
    { name: "Fluffy Bluff G1" },
    { name: "Fluffy Bluff G2" },
    { name: "Fluffy Bluff G3" },
    { name: "Flip-Swap 1" },
    { name: "Flip-Swap C" },
    { name: "Flip-Swap G1" },
    { name: "Flip-Swap G2" },
    { name: "Rightside Down 1" },
    { name: "Rightside Down S" },
    { name: "Rightside Down G1" },
    { name: "Rightside Down G2" },
    { name: "Bowser Jr.'s Fiery Flotilla 1" },
    { name: "Bowser Jr.'s Fiery Flotilla C" },
    { name: "Bowser Jr.'s Fiery Flotilla G1" },
    { name: "Bowser Jr.'s Fiery Flotilla G2" },
    { name: "Puzzle Plank 1" },
    { name: "Puzzle Plank C" },
    { name: "Puzzle Plank S" },
    { name: "Puzzle Plank G1" },
    { name: "Puzzle Plank G2" },
    { name: "Puzzle Plank G3" },
    { name: "Hightail Falls 1" },
    { name: "Hightail Falls C" },
    { name: "Hightail Falls S" },
    { name: "Hightail Falls G1" },
    { name: "Hightail Falls G2" },
    { name: "Hightail Falls G3" },
    { name: "Boulder Bowl 1" },
    { name: "Boulder Bowl C" },
    { name: "Boulder Bowl S" },
    { name: "Boulder Bowl G1" },
    { name: "Boulder Bowl G2" },
    { name: "Boulder Bowl G3" },
    { name: "Cosmic Cove 1" },
    { name: "Cosmic Cove 2" },
    { name: "Cosmic Cove S" },
    { name: "Cosmic Cove G1" },
    { name: "Cosmic Cove G2" },
    { name: "Cosmic Cove G3" },
    { name: "Wild Glide 1" },
    { name: "Wild Glide 2" },
    { name: "Wild Glide G1" },
    { name: "Wild Glide G2" },
    { name: "Honeybloom 1" },
    { name: "Honeybloom S" },
    { name: "Honeybloom G1" },
    { name: "Honeybloom G2" },
    { name: "Bowser's Lava Lair 1" },
    { name: "Bowser's Lava Lair C" },
    { name: "Bowser's Lava Lair G1" },
    { name: "Bowser's Lava Lair G2" },
    { name: "Tall Trunk 1" },
    { name: "Tall Trunk 2" },
    { name: "Tall Trunk C" },
    { name: "Tall Trunk G1" },
    { name: "Tall Trunk G2" },
    { name: "Tall Trunk G3" },
    { name: "Cloudy Court 1" },
    { name: "Cloudy Court C" },
    { name: "Cloudy Court S" },
    { name: "Cloudy Court G1" },
    { name: "Cloudy Court G2" },
    { name: "Cloudy Court G3" },
    { name: "Haunty Halls 1" },
    { name: "Haunty Halls 2" },
    { name: "Haunty Halls C" },
    { name: "Haunty Halls G1" },
    { name: "Haunty Halls G2" },
    { name: "Haunty Halls G3" },
    { name: "Freezy Flake 1" },
    { name: "Freezy Flake 2" },
    { name: "Freezy Flake S" },
    { name: "Freezy Flake G1" },
    { name: "Freezy Flake G2" },
    { name: "Freezy Flake G3" },
    { name: "Rolling Masterpiece 1" },
    { name: "Rolling Masterpiece C" },
    { name: "Rolling Masterpiece G1" },
    { name: "Rolling Masterpiece G2" },
    { name: "Beat Block 1" },
    { name: "Beat Block C" },
    { name: "Beat Block G1" },
    { name: "Beat Block G2" },
    { name: "Bowser Jr.'s Fearsome Fleet 1" },
    { name: "Bowser Jr.'s Fearsome Fleet C" },
    { name: "Bowser Jr.'s Fearsome Fleet G1" },
    { name: "Bowser Jr.'s Fearsome Fleet G2" },
    { name: "Supermassive 1" },
    { name: "Supermassive C" },
    { name: "Supermassive S" },
    { name: "Supermassive G1" },
    { name: "Supermassive G2" },
    { name: "Supermassive G3" },
    { name: "Flipsville 1" },
    { name: "Flipsville 2" },
    { name: "Flipsville C" },
    { name: "Flipsville G1" },
    { name: "Flipsville G2" },
    { name: "Flipsville G3" },
    { name: "Starshine Beach 1" },
    { name: "Starshine Beach 2" },
    { name: "Starshine Beach C" },
    { name: "Starshine Beach G1" },
    { name: "Starshine Beach G2" },
    { name: "Starshine Beach G3" },
    { name: "Chompworks 1" },
    { name: "Chompworks 2" },
    { name: "Chompworks C" },
    { name: "Chompworks G1" },
    { name: "Chompworks G2" },
    { name: "Chompworks G3" },
    { name: "Sweet Mystery 1" },
    { name: "Sweet Mystery C" },
    { name: "Sweet Mystery G1" },
    { name: "Sweet Mystery G2" },
    { name: "Honeyhop 1" },
    { name: "Honeyhop 2" },
    { name: "Honeyhop G1" },
    { name: "Honeyhop G2" },
    { name: "Bowser's Gravity Gauntlet 1" },
    { name: "Bowser's Gravity Gauntlet C" },
    { name: "Bowser's Gravity Gauntlet G1" },
    { name: "Bowser's Gravity Gauntlet G2" },
    { name: "Space Storm 1" },
    { name: "Space Storm 2" },
    { name: "Space Storm C" },
    { name: "Space Storm G1" },
    { name: "Space Storm G2" },
    { name: "Space Storm G3" },
    { name: "Slipsand 1" },
    { name: "Slipsand 2" },
    { name: "Slipsand C" },
    { name: "Slipsand G1" },
    { name: "Slipsand G2" },
    { name: "Slipsand G3" },
    { name: "Shiverburn 1" },
    { name: "Shiverburn C" },
    { name: "Shiverburn S" },
    { name: "Shiverburn G1" },
    { name: "Shiverburn G2" },
    { name: "Shiverburn G3" },
    { name: "Boo Moon 1" },
    { name: "Boo Moon 2" },
    { name: "Boo Moon S" },
    { name: "Boo Moon G1" },
    { name: "Boo Moon G2" },
    { name: "Boo Moon G3" },
    { name: "Upside Dizzy 1" },
    { name: "Upside Dizzy S" },
    { name: "Upside Dizzy G1" },
    { name: "Upside Dizzy G2" },
    { name: "Fleet Glide 1" },
    { name: "Fleet Glide 2" },
    { name: "Fleet Glide G1" },
    { name: "Fleet Glide G2" },
    { name: "Bowser Jr.'s Boom Bunker 1" },
    { name: "Bowser Jr.'s Boom Bunker C" },
    { name: "Bowser Jr.'s Boom Bunker G1" },
    { name: "Bowser Jr.'s Boom Bunker G2" },
    { name: "Melty Monster 1" },
    { name: "Melty Monster 2" },
    { name: "Melty Monster S" },
    { name: "Melty Monster G1" },
    { name: "Melty Monster G2" },
    { name: "Melty Monster G3" },
    { name: "Clockwork Ruins 1" },
    { name: "Clockwork Ruins C" },
    { name: "Clockwork Ruins S" },
    { name: "Clockwork Ruins G1" },
    { name: "Clockwork Ruins G2" },
    { name: "Clockwork Ruins G3" },
    { name: "Throwback 1" },
    { name: "Throwback 2" },
    { name: "Throwback C" },
    { name: "Throwback G1" },
    { name: "Throwback G2" },
    { name: "Throwback G3" },
    { name: "Battle Belt 1" },
    { name: "Battle Belt C" },
    { name: "Battle Belt S" },
    { name: "Battle Belt G1" },
    { name: "Battle Belt G2" },
    { name: "Battle Belt G3" },
    { name: "Flash Black 1" },
    { name: "Flash Black C" },
    { name: "Flash Black G1" },
    { name: "Flash Black G2" },
    { name: "Slimy Spring 1" },
    { name: "Slimy Spring 2" },
    { name: "Slimy Spring G1" },
    { name: "Slimy Spring G2" },
    { name: "Bowser's Galaxy Generator C" },
    { name: "Bowser's Galaxy Generator G1" },
    { name: "Bowser's Galaxy Generator G2" },
    { name: "Mario Squared 1" },
    { name: "Mario Squared C" },
    { name: "Mario Squared G1" },
    { name: "Mario Squared G2" },
    { name: "Rolling Coaster 1" },
    { name: "Rolling Coaster C" },
    { name: "Rolling Coaster G1" },
    { name: "Rolling Coaster G2" },
    { name: "Twisty Trials 1" },
    { name: "Twisty Trials C" },
    { name: "Twisty Trials G1" },
    { name: "Twisty Trials G2" },
    { name: "Stone Cyclone 1" },
    { name: "Stone Cyclone C" },
    { name: "Stone Cyclone G1" },
    { name: "Stone Cyclone G2" },
    { name: "Boss Blitz 1" },
    { name: "Boss Blitz C" },
    { name: "Boss Blitz G1" },
    { name: "Boss Blitz G2" },
    { name: "Flip-Out 1" },
    { name: "Flip-Out C" },
    { name: "Flip-Out G1" },
    { name: "Flip-Out G2" },
    { name: "Grandmaster 1" },
    { name: "Grandmaster C" },
    { name: "5 Power Stars (World 1)" },
    { name: "6 Power Stars (World 1)" },
    { name: "7 Power Stars (World 1)" },
    { name: "5 Power Stars (World 2)" },
    { name: "6 Power Stars (World 2)" },
    { name: "7 Power Stars (World 2)" },
    { name: "5 Power Stars (World 3)" },
    { name: "6 Power Stars (World 3)" },
    { name: "7 Power Stars (World 3)" },
    { name: "5 Power Stars (World 4)" },
    { name: "6 Power Stars (World 4)" },
    { name: "7 Power Stars (World 4)" },
    { name: "5 Power Stars (World 5)" },
    { name: "6 Power Stars (World 5)" },
    { name: "7 Power Stars (World 5)" },
    { name: "5 Power Stars (World 6)" },
    { name: "6 Power Stars (World 6)" },
    { name: "7 Power Stars (World 6)" },
    { name: "4 Power Stars (World S)" },
    { name: "5 Power Stars (World S)" },
    { name: "6 Power Stars (World S)" },
    { name: "100 Star Bits from any Star" },
    { name: "150 Star Bits from any Star" },
    { name: "200 Star Bits from any Star" },
    { name: "3 Comet Medals (World 1)" },
    { name: "4 Comet Medals (World 1)" },
    { name: "5 Comet Medals (World 1)" },
    { name: "3 Comet Medals (World 2)" },
    { name: "4 Comet Medals (World 2)" },
    { name: "5 Comet Medals (World 2)" },
    { name: "3 Comet Medals (World 3)" },
    { name: "4 Comet Medals (World 3)" },
    { name: "5 Comet Medals (World 3)" },
    { name: "3 Comet Medals (World 4)" },
    { name: "4 Comet Medals (World 4)" },
    { name: "5 Comet Medals (World 4)" },
    { name: "3 Comet Medals (World 5)" },
    { name: "4 Comet Medals (World 5)" },
    { name: "5 Comet Medals (World 5)" },
    { name: "3 Comet Medals (World 6)" },
    { name: "4 Comet Medals (World 6)" },
    { name: "5 Comet Medals (World 6)" },
    { name: "3 Comet Medals (World S)" },
    { name: "4 Comet Medals (World S)" },
    { name: "5 Comet Medals (World S)" },
    { name: "6 Green Stars (World 1)" },
    { name: "7 Green Stars (World 1)" },
    { name: "8 Green Stars (World 1)" },
    { name: "6 Green Stars (World 2)" },
    { name: "7 Green Stars (World 2)" },
    { name: "8 Green Stars (World 2)" },
    { name: "6 Green Stars (World 3)" },
    { name: "7 Green Stars (World 3)" },
    { name: "8 Green Stars (World 3)" },
    { name: "6 Green Stars (World 4)" },
    { name: "7 Green Stars (World 4)" },
    { name: "8 Green Stars (World 4)" },
    { name: "6 Green Stars (World 5)" },
    { name: "7 Green Stars (World 5)" },
    { name: "8 Green Stars (World 5)" },
    { name: "6 Green Stars (World 6)" },
    { name: "7 Green Stars (World 6)" },
    { name: "8 Green Stars (World 6)" },
    { name: "5 Green Stars (World S)" },
    { name: "6 Green Stars (World S)" },
    { name: "7 Green Stars (World S)" }
];
