bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList =
[
    "10 Man Brawl, 20 Characters",
    "10 Man Brawl, Complete in 20 seconds or less with 10 characters",
    "100 Man Brawl, Complete in under 3:30",
    "100 Man Brawl, Random Character, 3 Times",
    "All-Star, All Difficulties, Any Character",
    "All-Star, All Difficulties, Random Character",
    "All-Star, Easy, All Characters in a vertical Row",
    "All-Star, Easy, Random Character, No Continue",
    "All-Star, Hard, Random Character, No Continue",
    "All-Star, Intense - Complete with a Character of your choice",
    "All-Star, Intense, Random Character",
    "Boss Battles, All Difficulties, Any Character",
    "Boss Battles, Easy, All Characters in a vertical Row",
    "Boss Battles, Easy, Random Character, No Healing",
    "Boss Battles, Easy, Randomized Character, 3 Times",
    "Boss Battles, Easy-Very Hard, Any Character",
    "Boss Battles, Hard, Random Character, No Healing",
    "Boss Battles, Hard, Randomized Character, 2 Times",
    "Boss Battles, Intense, Any Character",
    "Classic, All Difficulties, Any Character",
    "Classic, All Difficulties, Random Character",
    "Classic, Easy, All Characters in a vertical row, 1 Stock",
    "Classic, Easy, Random Character, 1 Stock",
    "Classic, Hard, Random Character, 2 Stock",
    "Classic, Intense, Any Character",
    "Classic, Intense, Random Character",
    "Cruel Brawl, 10 Kills",
    "Do Event 22 on Hard",
    "Do Event 27 on Hard",
    "Do Event 33 in under 25 seconds",
    "Do Events 1-15",
    "Do Events 10,20,29,34,39 on Hard",
    "Do Events 16-30",
    "Do Events 31-41",
    "Do any 10 Events on Hard",
    "Do any 15 Events on Normal",
    "Do any 20 Events",
    "Endless Brawl, 100 Kills",
    "Endless Brawl, 150 Kills",
    "Subspace, Battleship Halberd Interior, Complete on Intense",
    "Subspace, Beat Porky (New File)",
    "Subspace, Beat Rayquaza (New File)",
    "Subspace, Complete Any 10 Stages",
    "Subspace, Complete Any 10 Stages on Intense only",
    "Subspace, Complete Any 15 Stages",
    "Subspace, Entrance to Subspace, Complete on Intense (No Fight Skips)",
    "Subspace, The Battlefield Fortress, Complete on Intense",
    "Subspace, The Glacial Peak, Complete on Intense",
    "Subspace, The Lake - 100% (New File)",
    "Subspace, The Plains - 100% (New File)",
    "Subspace, The Research Facility 2, Complete on Intense",
    "Subspace, The Ruined Zoo, Complete on Intense",
    "Subspace, The Ruins, Complete on Intense, No Wolf Door",
    "Subspace, The Subspace Bomb Factory 1, Complete All The Rooms (Intense)",
    "Subspace, The Subspace Bomb Factory 2, Complete on Intense",
    "Subspace, The Swamp, Complete on Intense, No Jigglypuff Door",
    "Subspace, Trophy All Mario Enemies (7)",
    "Subspace, Trophy All Primids (7)",
    "Subspace, Trophy All R.O.B. Enemies (3)",
    "Subspace, Turn 10 different enemies into a Trophy",
    "Subspace, Turn 10 enemies into a Trophy",
    "Subspace, Turn 15 different enemies into a Trophy",
    "Subspace, Turn 3 Bosses into Trophies",
    "Subspace, Turn 4 Bosses into Trophies",
    "Subspace, Turn Tabuu into a Trophy",
    "Target Test 1, Any 2 Rows",
    "Target Test 1, Complete in 15 seconds or less with 12 characters",
    "Target Test 2, Any 2 Rows",
    "Target Test 2, Complete in 17 seconds or less with 12 characters",
    "Target Test 3, 13 Characters",
    "Target Test 3, Complete in 19 seconds or less with 10 characters",
    "Target Test 4, 10 Characters",
    "Target Test 4, Complete in 30 seconds or less with 7 characters",
    "Target Test 5, 13 Characters",
    "Target Test 5, Complete in 30 seconds or less with 8 characters",
    "VSMode, Win on 10 Stages, Level 9, 2 Stock, Random Characters, 10 Stages, No Items,Timer,Custom Stages",
    "VSMode, Win on 5 Stages, Level 9, 2 Stock, Random Characters, 5 Stages, No Items,Timer,Custom Stages"
];
