bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    {"name": "kill an enemy and pick up their weapon"},
    {"name": "join a group taunt with 2+ other people (don't start it!)"},
    {"name": "kill a taunting enemy"},
    {"name": "taunt in front of enemy spawn door"},
    {"name": "random crit kill (any crit kill if disabled)"},
    {"name": "capture or defend an objective"},
    {"name": "pick up 3 health kits in 1 life"},
    {"name": "make friends with an enemy"},
    {"name": "3 kills in 1 life"},
    {"name": "survive a crit"},
    {"name": "kill the top scoring enemy"},
    {"name": "taunt while getting a kill"},

    {"name": "apply Mad Milk or Jarate to 2 enemies with 1 throw"},
    {"name": "kill with B.A.S.E. Jumper deployed"},
    {"name": "mini crit with Reserve Shooter"},
    {"name": "Mantreads or Thermal Thruster stomp"},
    {"name": "stand on an enemies head as heavy, engi, medic or sniper"},
    {"name": "extinguish yourself or a teammate"},

    {"name": "Back Scatter mini crit kill"},
    {"name": "kill while using Crit-a-Cola"},
    {"name": "Flying Guillotine kill (bleeding also counts)"},
    {"name": "pick up health from Candy Cane"},
    {"name": "Sun-on-a-Stick crit kill"},
    {"name": "Wrap Assassin kill"},
    {"name": "deploy Soda Popper hype"},

    {"name": "Airstrike kill without rocket jumping"},
    {"name": "Righteous Bison kill"},
    {"name": "Cow Mangler charge shot kill (burning also counts)"},
    {"name": "Direct Hit mini crit kill"},
    {"name": "deploy any Soldier banner"},
    {"name": "Market Gardener crit kill"},

    {"name": "Back Burner crit kill"},
    {"name": "Deploy Phlogistinator Mmmph"},
    {"name": "Ignite an enemy covered in gas"},
    {"name": "Axtinguisher mini crit kill"},
    {"name": "Neon Annihilator crit kill"},
    {"name": "flaregun crit kill"},
    {"name": "reflect a soldier rocket"},

    {"name": "Ullapool Caber kill"},
    {"name": "Demo charge crit melee kill"},
    {"name": "double donk"},
    {"name": "kill with a rolling pipe bomb"},
    {"name": "deal shield impact damage as Demo"},

    {"name": "heal >250 health from 1 sandwich"},
    {"name": "Eviction Notice kill"},
    {"name": "heal a Medic with a Heavy food item"},
    {"name": "ignite someone with Huo Long Heater"},
    {"name": "Family Business kill"},
    {"name": "Make someone laugh with Holiday Punch"},
    {"name": "kill while using Buffalo Steak"},

    {"name": "Frontier Justice crit kill"},
    {"name": "Wrangler kill"},
    {"name": "Pomson 6000 kill"},
    {"name": "Gunslinger crit melee kill"},
    {"name": "get a sentry kill while all your buildings are lvl 3"},
    {"name": "remove any Sapper"},
    {"name": "Rescue Ranger kill"},
    {"name": "kill the enemy who just destroyed your dispenser"},

    {"name": "use the Amputator taunt with 3 teammates near"},
    {"name": "use the Solemn Vow to find an enemy with <20 health"},
    {"name": "heal as Medic to assist in 3 kills in 1 life"},
    {"name": "heal >100 health with 1 Crusader's Crossbow arrow"},
    {"name": "deploy stock ubercharge"},
    {"name": "kill with any Needlegun"},

    {"name": "kill while using Hitman's Heatmaker charge"},
    {"name": "Shahanshah kill while at <50% health"},
    {"name": "melee kill an enemy covered in jarate"},
    {"name": "Huntsman headshot"},
    {"name": "no scope kill with any Sniper Rifle"},
    {"name": "kill with any Sniper SMG"},

    {"name": "Diamondback crit kill"},
    {"name": "non-backstab kill with any Spy knife"},
    {"name": "backstab kill"},
    {"name": "destroy a building using the Sapper"},
    {"name": "Ambassador crit kill"},
    {"name": "kill as spy without cloaking or disguising"},
]