var bingoGenerator = require("./generators/generator_bases/srl_generator_v5.js");

var bingoList = 
[];
bingoList[1] = [
{ name: "Have 0 Town NPCs in your world", types: [] },
{ name: "Afflict the same enemy with Frostburn and On Fire!", types: [] },
{ name: "Use the Torch God's Favor", types: [] },
{ name: "Open a Sandstone Chest", types: [] },
{ name: "Craft a Legendary Palm Wood Sword", types: [] },
{ name: "Cook a Marshmallow", types: [] },
]; bingoList[2] = [
{ name: "Walk on water", types: [] },
{ name: "Craft a Target Dummy", types: [] },
{ name: "Craft a Dye", types: [] },
{ name: "Consume a Cooked Fish", types: [] },
{ name: "Research 5 types of Wood Fences", types: [] },
{ name: "Change shoe color at a Dresser", types: [] },
]; bingoList[3] = [
{ name: "Obtain a non-stackable Weapon from an Enemy", types: [] },
{ name: "Catch and contain 3 unique Critters", types: [] },
{ name: "Eat Sauteed Frog Legs", types: [] },
{ name: "Duplicate any Stucco", types: [] },
{ name: "Place a Food Item on a Plate", types: [] },
{ name: "Die to a trap", types: [] },
]; bingoList[4] = [
{ name: "Fire a Boomstick", types: [] },
{ name: "Research Smooth Granite or Smooth Marble", types: [] },
{ name: "Purchase any Pylon", types: [] },
{ name: "Craft a Gold or Platinum Hammer", types: [] },
{ name: "Research regular Mana Potions", types: [] },
{ name: "Buy a Lawnmower", types: [] },
]; bingoList[5] = [
{ name: "Trash a Crispy Honey Block", types: [] },
{ name: "Craft a Featherfall Potion and an Ironskin Potion", types: [] },
{ name: "Wear a Garland", types: [] },
{ name: "Craft a Gills Potion and a Battle Potion", types: [] },
{ name: "Kill an enemy with a Dart", types: [] },
{ name: "Craft a Hunter Potion and a Magic Power Potion", types: [] },
]; bingoList[6] = [
{ name: "Craft a set of Crimson or Shadow Armor", types: [] },
{ name: "Kill a Goblin Summoner", types: [] },
{ name: "Place a Skyware Chandelier", types: [] },
{ name: "Research Sticky or Bouncy Bombs", types: [] },
{ name: "Use a Dirt Rod to throw dirt out of the world", types: [] },
{ name: "Wear a full set of Pumpkin Armor", types: [] },
]; bingoList[7] = [
{ name: "Research Bones", types: [] },
{ name: "Make an Announcement Box say \"BINGO\" in chat", types: [] },
{ name: "Obtain the Cursed Debuff", types: [] },
{ name: "Kill The Bride or The Groom", types: [] },
{ name: "Fish up 3 Junk Items", types: [] },
{ name: "Craft a Piano", types: [] },
]; bingoList[8] = [
{ name: "Defeat the Eye of Cthulhu with only Ranged weapons", types: [] },
{ name: "Touch the Left and Right World Borders", types: [] },
{ name: "Kill a Boss using only a Minecart", types: [] },
{ name: "Finish off a Boss with placeable Explosives", types: [] },
{ name: "Craft any Boss Summon ", types: [] },
{ name: "Craft an Abeemination", types: [] },
]; bingoList[9] = [
{ name: "Craft 4 Shortswords", types: [] },
{ name: "Craft a Gem Robe", types: [] },
{ name: "Obtain 3 Gem Staves", types: [] },
{ name: "Destroy an entire Floating Island (including walls)", types: [] },
{ name: "Directly kill a Truffle Worm", types: [] },
{ name: "Craft an Amber Gemcorn", types: [] },
]; bingoList[10] = [
{ name: "Research 3 Banners", types: [] },
{ name: "Chop a tree with Lucy The Axe", types: [] },
{ name: "Fire the Weather Pain in a Sandstorm", types: [] },
{ name: "Summon Deerclops using a Deer Thing", types: [] },
{ name: "Use a Solar Tablet", types: [] },
{ name: "Cover an Ocean with Obsidian", types: [] },
]; bingoList[11] = [
{ name: "Ride in a Mechanical Minecart", types: [] },
{ name: "Research Waterfall Blocks", types: [] },
{ name: "Duplicate all 3 Liquid Buckets", types: [] },
{ name: "Wear one of the Vanity Contest winner sets", types: [] },
{ name: "Dye your character's hair", types: [] },
{ name: "Record a song with a Music Box", types: [] },
]; bingoList[12] = [
{ name: "Set your spawn in a Slime Bed", types: [] },
{ name: "Touch the very top and very bottom of the world", types: [] },
{ name: "Craft any Timer", types: [] },
{ name: "Kill a Clown", types: [] },
{ name: "Fish and kill a Blood Moon Enemy", types: [] },
{ name: "Fire a Phoenix Blaster", types: [] },
]; bingoList[13] = [
{ name: "Equip a set of Necro Armor", types: [] },
{ name: "Acquire 4 different Mushrooms", types: [] },
{ name: "Kill a Corrupt or Vicious Critter", types: [] },
{ name: "Spawn the Wall of Flesh with a Guide Voodoo Doll", types: [] },
{ name: "Acquire the Exquisitely Stuffed buff", types: ["Food"] },
{ name: "Consume any Flask", types: [] },
]; bingoList[14] = [
{ name: "Throw Holy, Unholy, or Blood Water", types: [] },
{ name: "Place 9 unique Toilets", types: [] },
{ name: "Craft the Terra Toilet", types: ["Terra"] },
{ name: "Craft a Recall Potion", types: [] },
{ name: "Confuse an Enemy", types: [] },
{ name: "Open a Crate", types: [] },
]; bingoList[15] = [
{ name: "Defeat any Biome Mimic", types: [] },
{ name: "Defeat enraged Plantera", types: [] },
{ name: "Summon an Evil Boss without smashing Orbs or Hearts", types: [] },
{ name: "Craft Fairy Wings", types: [] },
{ name: "Defeat Skeletron in the Jungle", types: [] },
{ name: "Wear a Developer Set", types: [] },
]; bingoList[16] = [
{ name: "Research Antlion Eggs", types: [] },
{ name: "Buy a Tragic Umbrella", types: [] },
{ name: "Craft a Greater Healing Potion", types: [] },
{ name: "Craft the Grand Design", types: [] },
{ name: "Fish an item from Lava", types: [] },
{ name: "Use a Jousting Lance while on a Horse or Unicorn", types: [] },
]; bingoList[17] = [
{ name: "Purchase the Quad-Barrel Shotgun", types: [] },
{ name: "Complete 2 Fishing Quests", types: [] },
{ name: "Craft the Star Cannon", types: [] },
{ name: "Equip a set of Jungle Armor", types: [] },
{ name: "Fire a Wet Rocket", types: [] },
{ name: "Research 6 Campfires", types: [] },
]; bingoList[18] = [
{ name: "Kill any Pigron", types: [] },
{ name: "Craft an Adamantite or Titanium Forge", types: [] },
{ name: "Fire a Cobalt or Palladium Repeater", types: [] },
{ name: "Defeat a boss using only Whips", types: [] },
{ name: "Have 5 Minions active", types: [] },
{ name: "Defeat King and Queen Slime", types: [] },
]; bingoList[19] = [
{ name: "Craft an Avenger Emblem", types: [] },
{ name: "Craft 2 Hamaxes", types: [] },
{ name: "Open a Shadow Chest", types: [] },
{ name: "Fish an item from Lava", types: [] },
{ name: "Craft any Spell Tome", types: [] },
{ name: "Obtain the Terraprisma", types: [] },
]; bingoList[20] = [
{ name: "Ride 2 Mounts", types: [] },
{ name: "Summon 2 unique Sentries", types: [] },
{ name: "Mine the Lihzahrd Altar", types: [] },
{ name: "Collect any Celestial Shell ingredient", types: [] },
{ name: "Destroy a Flying Dutchman", types: [] },
{ name: "Obtain the Night's Edge", types: [] },
]; bingoList[21] = [
{ name: "Research Chlorophyte Brick", types: [] },
{ name: "Have 8 unique Food Items in your inventory at once", types: ["Food"] },
{ name: "Have 65 Defense", types: [] },
{ name: "Craft a Magical Harp", types: [] },
{ name: "Craft the Megashark", types: [] },
{ name: "Obtain the Dao of Pow", types: [] },
]; bingoList[22] = [
{ name: "Summon a Pet Parrot", types: ["Pets"] },
{ name: "Craft a Phaseblade and a Phasesaber", types: [] },
{ name: "Have 16 Town NPCs (including pets)", types: [] },
{ name: "Obtain 5 Summon Weapons (excluding Sentries)", types: [] },
{ name: "Research 7 Grappling Hooks", types: [] },
{ name: "Research 4 Fishing Rods", types: [] },
]; bingoList[23] = [
{ name: "Obtain 3 Non-Light Pets", types: ["Pets"] },
{ name: "Obtain 2 Light Pets", types: ["Pets"] },
{ name: "Obtain 4 Yoyos", types: [] },
{ name: "Fly 2 Kites", types: [] },
{ name: "Craft a Naughty Present", types: [] },
{ name: "Craft a Pumpkin Moon Medallion", types: [] },
]; bingoList[24] = [
{ name: "Have 420 Max Health", types: [] },
{ name: "Have 400 Health and 200 Mana", types: [] },
{ name: "Have 4 Pre-Hardmode bosses alive at once", types: [] },
{ name: "Place an Autohammer", types: [] },
{ name: "Fill all 14 Accessory and Vanity Accessory slots", types: [] },
{ name: "Obtain the Terra Blade", types: ["Terra"] },
]; bingoList[25] = [
{ name: "Fail the Old One's Army event", types: [] },
{ name: "Obtain 10 unique Ammo items", types: [] },
{ name: "Activate or destroy a Martian Probe", types: [] },
{ name: "Fight all 3 Mechanical Bosses at the same time", types: [] },
{ name: "Craft a Martian Astro Clock", types: [] },
{ name: "Kill the Lunatic Cultist", types: [] },
];;
