bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Accure 100 platinum coins",
    "Craft Galaxia",
    "Craft a Calamity weapon that uses a vanilla weapon as a component",
    "Craft an accessory using the Obsidian Skull",
    "Craft the Ark of the Elements",
    "Craft the Chalice of the Blood God",
    "Craft the Devil's Devastation",
    "Craft the Eclipse Mirror",
    "Craft the Elemental Disk",
    "Craft the Elemental Gauntlet",
    "Craft the Elemental Quiver",
    "Craft the Ethereal Tailsman",
    "Craft the Nanotech",
    "Craft the Nucleogenesis",
    "Craft the Planetary Annihilation",
    "Craft the Terratomere",
    "Defeat Anahita and the Leviathan",
    "Defeat Crabulon",
    "Defeat Cryogen",
    "Defeat Dragonfolly",
    "Defeat Duke Fishron",
    "Defeat Moon Lord",
    "Defeat Plantera before any mech",
    "Defeat Polterghast",
    "Defeat Providence",
    "Defeat Ravager",
    "Defeat Wall of Flesh without building a bridge",
    "Defeat a Plaguebringer",
    "Defeat a boss using only rogue damage",
    "Defeat a boss using only summon damage",
    "Defeat a boss using only true melee damage",
    "Defeat a boss without leaving a minecart",
    "Defeat a miniboss in the Abyss",
    "Defeat all Pre-hardmode bosses during the Boss Rush",
    "Defeat all three mechs at the same time",
    "Defeat an Earth Elemental",
    "Defeat an enraged boss",
    "Defeat any boss five times, one for each class",
    "Defeat ascended Mothron",
    "Defeat the Acid Rain (any tier)",
    "Defeat the Aquatic Scourge",
    "Defeat the Brimstone Elemental",
    "Defeat the Calamitas Clone",
    "Defeat the Desert Scourge",
    "Defeat the Dungeon Guardian",
    "Defeat the Empress of Light",
    "Defeat the Giant Clam",
    "Defeat the Great Sand Shark",
    "Defeat the Nameless Serpent",
    "Defeat the Plaguebringer Goliath",
    "Defeat the Slime God",
    "Defeat the foreign world evil bosses",
    "Defeat the native world evil bosses",
    "Die to a Blazing Wheel",
    "Fish two different crates exclusive to Calamity",
    "Get a bonus from matching wings with your armor",
    "Get the Bandit to move in",
    "Have a Water Candle, Chaos Candle, Battle Potion, and Zerg Potion active at once",
    "Have five different life regeneration perks active at once",
    "Have ten minions active at once",
    "Have two different fire debuffs active at once (no PvP)",
    "Kill every type of slime, vanilla and Calamity",
    "Kill ten Bloodworms",
    "No-hit a boss",
    "Obtain Bloodflare Armor",
    "Obtain Brimflame Armor",
    "Obtain Fathom Swarmer Armor",
    "Obtain Grand Marquis Bait",
    "Obtain Life Alloy",
    "Obtain Plaguebringer Armor",
    "Obtain Tarragon Armor",
    "Obtain The Community",
    "Obtain a Blossom Pickaxe",
    "Obtain a Core of Calamity",
    "Obtain a developer vanity item without naming your character accordingly",
    "Obtain every schematic",
    "Obtain five different rogue weapons",
    "Obtain five different torches exclusive to Calamity",
    "Obtain one item for each tier of Well Fed",
    "Obtain one of every type of wood, vanilla and Calamity",
    "Obtain one weapon of every class from bosses",
    "Obtain the Cosmolight",
    "Obtain two different dyes exclusive to Calamity",
    "Place three different boss trophies",
    "Reach 100 defense",
    "Reach 20% DR",
    "Reach 400 max mana",
    "Reach 50% Hallow",
    "Reach 700 max HP",
    "Reach the second layer of the Abyss",
    "Reach the third layer of the Abyss",
    "Reach wave 20 of the ascended Frost Moon",
    "Reach wave 20 of the ascended Pumpkin Moon",
    "Summon Polterghast by killing Dungeon enemies",
    "Survive enraged Providence for 15 seconds"
];
