bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Build Couch",
    "Build Log Cabin",
    "Kill Armsy",
    "Kill Bird / Seagull",
    "Kill Cowman",
    "Kill Crocodile",
    "Kill Deer",
    "Kill Mutant Baby",
    "Kill Shark",
    "Kill Turtle / Tortoise",
    "Kill Viginia",
    "Obtain Bomb / Dynamite",
    "Obtain Camcorder",
    "Obtain Cassette",
    "Obtain Cassette Player",
    "Obtain Chainsaw",
    "Obtain Climbing Axe",
    "Obtain Club",
    "Obtain Crafted Axe",
    "Obtain Crafted Bow",
    "Obtain Crossbow",
    "Obtain Energy Mix+",
    "Obtain Flare Gun",
    "Obtain Gun Part",
    "Obtain Herbal Mechicine+",
    "Obtain Katana",
    "Obtain Keycard 1",
    "Obtain Machete",
    "Obtain Map",
    "Obtain Modern Axe",
    "Obtain Modern Bow",
    "Obtain Pedometer",
    "Obtain Rebreather",
    "Obtain Rusty Axe",
    "Obtain Schematic 1",
    "Obtain Schematic 2",
    "Obtain Schematic 3",
    "Obtain Schematic 4",
    "Obtain Slingshot",
    "Obtain Tennis Racket",
    "Obtain Timmy Drawing",
    "Obtain Toy Piece",
    "Obtain Upgraded Spear",
    "Wear Bathrobe",
    "Wear Blacksuit",
    "Wear Old Suit",
    "Wear Pilot Uniform",
    "Wear Stewardess Dress",
    "Wear Tennis Outfit"
];
