bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "[{\"name\": \"Build Log Sled\"},",
    "]",
    "{\"name\": \"Build Couch\"},",
    "{\"name\": \"Build Gazebo\"},",
    "{\"name\": \"Build Glider\"},",
    "{\"name\": \"Build Log Cabin\"}",
    "{\"name\": \"Build a Raft\"},",
    "{\"name\": \"Find Timmy\"},",
    "{\"name\": \"Get a Fish\"},",
    "{\"name\": \"Kill Armsy\"},",
    "{\"name\": \"Kill Bird / Seagull\"},",
    "{\"name\": \"Kill Cowman\"},",
    "{\"name\": \"Kill Crocodile\"},",
    "{\"name\": \"Kill Deer\"},",
    "{\"name\": \"Kill Mutant Baby\"},",
    "{\"name\": \"Kill Shark\"},",
    "{\"name\": \"Kill Turtle / Tortoise\"},",
    "{\"name\": \"Kill Viginia\"},",
    "{\"name\": \"Obtain Bomb / Dynamite\"},",
    "{\"name\": \"Obtain Camcorder\"},",
    "{\"name\": \"Obtain Cassette Player\"},",
    "{\"name\": \"Obtain Cassette\"},",
    "{\"name\": \"Obtain Chainsaw\"},",
    "{\"name\": \"Obtain Climbing Axe\"},",
    "{\"name\": \"Obtain Club\"},",
    "{\"name\": \"Obtain Crafted Axe\"},",
    "{\"name\": \"Obtain Crafted Bow\"},",
    "{\"name\": \"Obtain Crossbow\"},",
    "{\"name\": \"Obtain Energy Mix+\"},",
    "{\"name\": \"Obtain Flare Gun\"},",
    "{\"name\": \"Obtain Gun Part\"},",
    "{\"name\": \"Obtain Hair Spray\"},",
    "{\"name\": \"Obtain Head Bomb\"},",
    "{\"name\": \"Obtain Herbal Mechicine+\"},",
    "{\"name\": \"Obtain Katana\"},",
    "{\"name\": \"Obtain Keycard 1\"},",
    "{\"name\": \"Obtain Machete\"},",
    "{\"name\": \"Obtain Map\"},",
    "{\"name\": \"Obtain Modern Axe\"},",
    "{\"name\": \"Obtain Modern Bow\"},",
    "{\"name\": \"Obtain Pedometer\"},",
    "{\"name\": \"Obtain Rebreather\"},",
    "{\"name\": \"Obtain Rusty Axe\"},",
    "{\"name\": \"Obtain Schematic 1\"},",
    "{\"name\": \"Obtain Schematic 2\"},",
    "{\"name\": \"Obtain Schematic 3\"},",
    "{\"name\": \"Obtain Schematic 4\"},",
    "{\"name\": \"Obtain Slingshot\"},",
    "{\"name\": \"Obtain Snow Shoes},",
    "{\"name\": \"Obtain Tennis Racket\"},",
    "{\"name\": \"Obtain Timmy Drawing\"},",
    "{\"name\": \"Obtain Toy Piece\"},",
    "{\"name\": \"Obtain Upgraded Spear\"},",
    "{\"name\": \"Red Paint\"},",
    "{\"name\": \"Wear Bathrobe\"},",
    "{\"name\": \"Wear Blacksuit\"},",
    "{\"name\": \"Wear Old Suit\"},",
    "{\"name\": \"Wear Tennis Outfit\"},"
];
