bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "10 Cockadoos",
    "10 Imps",
    "10 King Ants",
    "10 Mandolas",
    "10 Saber Tigers",
    "10 Silver Coins",
    "10 Stingers",
    "20 Gudons",
    "25 Gamulians/Puppets",
    "30 Bronze Coins",
    "4 Gold Coins",
    "50 Pollywogs",
    "Beat Cloud Whale/Chimera with white magic/skeleton",
    "Beat Nightmare with Rue/Mint physical attacks",
    "Beat Rod (Black Tornado) to win 1,000g",
    "Beat Rod (Golden Gale) to win 1,000g",
    "Beat Rod (Silver Breeze) to win 1,000g",
    "Beat Skull Beast with red magic/Gudon",
    "Beat Starlight Duke (Mint)/Lose to Starlight Duke (Rue)",
    "Beat both Blood and Smokey",
    "Bronze Belt",
    "Bronze Bracer",
    "Buy a drink at the tavern (no freebies)",
    "Buy a stat increase from Hobbs",
    "Drown in lava 10 times",
    "Drown in water 10 times",
    "Find 10 hidden items",
    "Find all 3 hidden coins at Docks at night",
    "Find both Silver Coins before Carona Forest",
    "Get game over (Die with 0 coins of life)",
    "Go through tunnel in Carona Forest",
    "Gold Belt",
    "Gold Bracer",
    "Jump from black to white to black during rune pool",
    "Jump off the face at B&S area",
    "Kill a Fungie using black magic/Bubba",
    "Kill a Gamulian/Little Bat with yellow magic/Fire Blob",
    "Kill a Gargoyle with red magic/Gudon",
    "Kill a Saber Tiger with blue magic/Pollywog",
    "Legendary Shield",
    "Legendary Sword",
    "Night Stone",
    "Platinum Belt",
    "Platinum Bracer",
    "Platinum Coin",
    "Rare Wine",
    "Return to Town using 3 different frog plants",
    "Return to Town using 5 different frog plants",
    "Ride a falling block all the way down",
    "Score 350+ points in Cockadoo Trumpets",
    "Score 420+ points in Fungie Bash",
    "Score 690+ points in Bouncing Balls",
    "Sell 3 Moon Stones at one time",
    "Silver Belt",
    "Silver Bracer",
    "Sleep at hotel",
    "Sleep at inn",
    "Speak to Rod at night time",
    "Swim with Cloud Whale/Be Pollywog in Ghost Temple acid",
    "Talk to Hobbs before Carona Forest",
    "Use 5 coins of life",
    "Use Heal machine at Underground Ruins Atelier",
    "Use Heal spot at Gargoyles",
    "Use Heal spot behind rolling boulder",
    "Use Heal spot in Lava Room",
    "[Power] magic/Treetops Moon Stone"
];
