bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Change Pants",
    "Change Tomba's Hair",
    "Clear 25 Events",
    "Collect 10 Math Beads",
    "Collect 29 Leaf Butterflies",
    "Collect Funky Parasol twice",
    "Collect all 3 Crystal Balls",
    "Collect all Treasure Keys",
    "Complete Monster Hunt",
    "Complete the Motocross Course",
    "Cry in front of the Phoenix",
    "Defeat an Evil Pig Boss",
    "Discover the Hidden Village",
    "Do 4 laps around V.A.B.",
    "Eat Yan's Lunchbox in front of him",
    "Enter Underground Maze",
    "Enter the Flower Tower",
    "Enter the Seaside Mansion",
    "Find Yan Twice",
    "Find the Mouse",
    "Fix the Pipe at Baccus Lake",
    "Get 10 berries from pump rocks",
    "Get Banana Juice",
    "Get Jewel of Fire",
    "Get Jewel of Water",
    "Get Jewel of Wind",
    "Get in a cage with a monster",
    "Get kicked out of a window",
    "Get to the top of the Watchtower without using the ladder",
    "Go down the Leaf Slider",
    "Go through Lava Caves without Parasol",
    "Help Charles Find Pants",
    "Increase Health to 12",
    "Increase Health to 16",
    "Increase Health to 8",
    "Laugh at the Giant Egg in Hidden Village",
    "Look Through the Telescope on Watchtower",
    "Make a Tiny Pig",
    "Obtain 2 Golden Items",
    "Obtain Baron",
    "Obtain Biting Plant Flower twice",
    "Obtain Fruit of Knowledge",
    "Obtain Grandpa's Bracelet",
    "Open 2 AP boxes",
    "Open a Million Year Old Chest",
    "Open all Treasure Chests in Underground Maze",
    "Pull my finger",
    "Reach 100,000 AP",
    "Return Funga Drum to owner",
    "Ride the raft to Haunted Mansion",
    "Silver Medal in Motocross",
    "Start of Phoenix Mountain to Lava Caves Without Dying",
    "Stop the Storm in Phoenix Mountain",
    "Talk to a Fortune Teller",
    "Talk to the Cute Witch"
];
