bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "99.9 twice in Bullring",
    "99.9 twice in Burnside",
    "99.9 twice in Marseille",
    "99.9 twice in Roswell",
    "99.9 twice in Skatepark",
    "99.9 twice in Skatestreet",
    "All Goals in Downhill Jam",
    "All Goals in Downtown",
    "All Goals in Hangar with 2 Skater",
    "All Goals in Mall with 2 Skater",
    "All Goals in NYC",
    "All Goals in Phili",
    "All Goals in School 2 with 2 Skater",
    "All Goals in School with 2 Skater",
    "All Goals in Streets",
    "All Goals in Venice",
    "All Goals in Warehouse with 2 Skater",
    "Combine 2 Kicker Gaps and 2 Car Ollie Gaps in Dwontown",
    "Combine 2 Light Corner Gaps in Hangar",
    "Combine 2 Pool Hip Gaps and Around the Bend Gap in Skatestreet",
    "Combine 3 Car Plants in NYC",
    "Combine 4 Dumpster Pop Gaps in Marseille",
    "Combine Bridge Gap, Transfer and Rollin' the Hill Gap in Burnside",
    "Combine Channel Gap and Holy Shi... Gap in Warehouse",
    "Combine Havin A Picnic Gap andSurfin U.S.A. Gap in Skatestreet",
    "Combine Huge Water Hazard Gap and Hydrophobic Gap in Dwonhil Jam",
    "Combine Long Stair Gap and Medium Stair Gap in Phili",
    "Combine Nasty in the Pasty Gap and Pool Grind Gap in Roswell",
    "Combine Over a Stair Set Gap and Over a Huge Stair Set Gap in Mall",
    "Combine Roof to Awning Gap and Kicker Gap in School",
    "Combine Threadin The Needle Gap and Nailin da Rail Gap in Bullring",
    "Combine Touchdown!!! Gap and a VB! Transfer Gap in Venice",
    "Combine Up the Spiral Gap and Around the Fountain Gap in Streets",
    "Combine any 2 Roll Call Rail Gaps in School 2",
    "Destroy All Police Cars in Streets with 2 Skater",
    "Get 15 Graffiti Tags in Chopper Drop",
    "Get 20 Graffiti Tags in Warehouse",
    "Get 22 Graffiti Tags in Burnside",
    "Get 30 Graffiti Tags in Roswell",
    "Get 35 Graffiti Tags in Skate Park",
    "Get 40 Graffiti Tags in Bullring",
    "Get 40 Graffiti Tags in Hangar",
    "Get 40 Graffiti Tags in Heaven",
    "Get 40 Graffiti Tags in Marseille",
    "Get 40 Graffiti Tags in Skatestreet",
    "Get 45 Graffiti Tags in Downhill Jam",
    "Get 50 Graffiti Tags in Mall",
    "Get 50 Graffiti Tags in Phili",
    "Get 60 Graffiti Tags in Streets",
    "Get 70 Graffiti Tags in Downtown",
    "Get 70 Graffiti Tags in Nyc",
    "Get 70 Graffiti Tags in School 2",
    "Get 70 Graffiti Tags in Venice",
    "Get 80 Graffiti Tags in School",
    "Get in Marseilles Secret Room",
    "Get into the Vulcano in Skate Heaven",
    "Land All 4 Pool Lip Extension Gaps in School 2",
    "Land All Roof gaps in Downtown with 2 Skater",
    "Land All Skatepark Lips in Phili with 2 Skater",
    "Land All VB-Transfers in Venice with 2 Skater",
    "Land a 1mil Combo",
    "Land a 50multiplier Combo",
    "Ollie All Magic bums in Venice with 2 Skater",
    "Open All Valves in Downhil Jam with 2 Skater",
    "Open Gym in School 2",
    "Open both Secret areas in Skatestreet",
    "Wallride 5 monkeys"
];
