bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "100% the Map",
    "Break All Jewel Towers",
    "Break Amethyst Jewel Tower",
    "Break Aquamarine Jewel Tower",
    "Break Ruby Jewel Tower",
    "Break Topaz Jewel Tower",
    "Dunk All Wastebins in All Stages",
    "Dunk All Wastebins in Stage 1",
    "Dunk All Wastebins in Stage 2",
    "Dunk All Wastebins in Stage 3",
    "Dunk All Wastebins in Stage 4",
    "Dunk All Wastebins in Stage 5",
    "Dunk Wastebin 1 in All Stages",
    "Dunk Wastebin 2 in All Stages",
    "Dunk Wastebin 3 in All Stages",
    "Dunk a Wastebin in All Stages",
    "Get All Abilities",
    "Get All Keys",
    "Get All Skills",
    "Get Auto Aim Skill",
    "Get Blue Key",
    "Get Chainsaw Skill",
    "Get Double Jump Ability",
    "Get Eternal Clock in All Stages",
    "Get Eternal Clock in Stage 1",
    "Get Eternal Clock in Stage 2",
    "Get Eternal Clock in Stage 3",
    "Get Eternal Clock in Stage 4",
    "Get Eternal Clock in Stage 5",
    "Get Green Key",
    "Get Grip Knife Ability",
    "Get HP Upgrade in All Stages",
    "Get HP Upgrade in Stage 1",
    "Get HP Upgrade in Stage 2",
    "Get HP Upgrade in Stage 3",
    "Get HP Upgrade in Stage 4",
    "Get HP Upgrade in Stage 5",
    "Get Knife Upgrade in All Stages",
    "Get Knife Upgrade in Stage 1",
    "Get Knife Upgrade in Stage 2",
    "Get Knife Upgrade in Stage 3",
    "Get Knife Upgrade in Stage 4",
    "Get Knife Upgrade in Stage 5",
    "Get Lost Holy Sword Skill",
    "Get MP Upgrade in All Stages",
    "Get MP Upgrade in Stage 1",
    "Get MP Upgrade in Stage 2",
    "Get MP Upgrade in Stage 3",
    "Get MP Upgrade in Stage 4",
    "Get MP Upgrade in Stage 5",
    "Get Purple Key",
    "Get Red Key",
    "Get Screw Knife Ability",
    "Get Shield Dagger Skill",
    "Get Sliding Knife Ability",
    "Get Stun Knife Skill",
    "Get Thousand Dagger Skill",
    "Get Yellow Key",
    "Reach Level 10",
    "Reach Level 15",
    "Reach Level 20",
    "Reach Level 5"
];
