bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "100% the Map",
    "Beat Flandre without using Skills",
    "Beat Marisa with only Chainsaw",
    "Beat Meiling without using Snail Time",
    "Beat Nitori without reaching Phase 2",
    "Beat Nitori without using Time Stop",
    "Beat Patchouli with only Thousand Dagger",
    "Beat Remilia without using Chainsaw",
    "Break All Jewel Towers",
    "Break the Amethyst Jewel Tower",
    "Break the Aquamarine Jewel Tower",
    "Break the Ruby Jewel Tower",
    "Break the Topaz Jewel Tower",
    "Buy 1 Eternal Clock from Nitori's Shop",
    "Buy 1 HP Recovery from Nitori's Shop",
    "Buy 1 Knife Upgrade from Nitori's Shop",
    "Buy 1 MP Recovery from Nitori's Shop",
    "Buy 1 TP Recovery from Nitori's Shop",
    "Buy 3 HP Recoveries from Nitori's Shop",
    "Buy 3 MP Recoveries from Nitori's Shop",
    "Buy 3 TP Recoveries from Nitori's Shop",
    "Discover the Warp Zone in All Stages",
    "Discover the Warp Zone in Stage 1",
    "Discover the Warp Zone in Stage 2",
    "Discover the Warp Zone in Stage 3",
    "Discover the Warp Zone in Stage 4",
    "Discover the Warp Zone in Stage 5",
    "Dunk All Wastebins in All Stages",
    "Dunk All Wastebins in Stage 1",
    "Dunk All Wastebins in Stage 2",
    "Dunk All Wastebins in Stage 3",
    "Dunk All Wastebins in Stage 4",
    "Dunk All Wastebins in Stage 5",
    "Dunk Wastebin 1 in All Stages",
    "Dunk Wastebin 2 in All Stages",
    "Dunk Wastebin 3 in All Stages",
    "Dunk a Wastebin in All Stages",
    "Finish Off Flandre with Auto Aim",
    "Finish Off Marisa with Stun Knife",
    "Finish Off Meiling with a Slide",
    "Finish Off Patchouli with a Double Jump",
    "Finish Off Remilia with Shield Dagger",
    "Get All Abilities",
    "Get All Keys",
    "Get All Skills",
    "Get the Auto Aim Skill",
    "Get the Blue Key",
    "Get the Chainsaw Skill",
    "Get the Double Jump Ability",
    "Get the Eternal Clock in All Stages",
    "Get the Eternal Clock in Stage 1",
    "Get the Eternal Clock in Stage 2",
    "Get the Eternal Clock in Stage 3",
    "Get the Eternal Clock in Stage 4",
    "Get the Eternal Clock in Stage 5",
    "Get the Green Key",
    "Get the Grip Knife Ability",
    "Get the HP Upgrade in All Stages",
    "Get the HP Upgrade in Stage 1",
    "Get the HP Upgrade in Stage 2",
    "Get the HP Upgrade in Stage 3",
    "Get the HP Upgrade in Stage 4",
    "Get the HP Upgrade in Stage 5",
    "Get the Knife Upgrade in All Stages",
    "Get the Knife Upgrade in Stage 1",
    "Get the Knife Upgrade in Stage 2",
    "Get the Knife Upgrade in Stage 3",
    "Get the Knife Upgrade in Stage 4",
    "Get the Knife Upgrade in Stage 5",
    "Get the Lost Holy Sword Skill",
    "Get the MP Upgrade in All Stages",
    "Get the MP Upgrade in Stage 1",
    "Get the MP Upgrade in Stage 2",
    "Get the MP Upgrade in Stage 3",
    "Get the MP Upgrade in Stage 4",
    "Get the MP Upgrade in Stage 5",
    "Get the Purple Key",
    "Get the Red Key",
    "Get the Screw Knife Ability",
    "Get the Shield Dagger Skill",
    "Get the Sliding Knife Ability",
    "Get the Stun Knife Skill",
    "Get the Thousand Dagger Skill",
    "Get the Yellow Key",
    "Obtain 1 Diamond Jewel",
    "Obtain 10 Emerald Jewels",
    "Obtain 100 Ruby Jewels",
    "Obtain 1000 Amethyst Jewels",
    "Obtain 25 Sapphire Jewels",
    "Obtain 250 Topaz Jewels",
    "Obtain 500 Aquamarine Jewels",
    "Reach 130 TIME Gauge",
    "Reach 27 Time Stop Knives",
    "Reach Level 10",
    "Reach Level 15",
    "Reach Level 20",
    "Reach Level 5",
    "Receive a Shop Ticket from Nitori",
    "Use a Shop Ticket in the Marisa Battle",
    "Use a Shop Ticket in the Meiling Battle",
    "Use a Shop Ticket in the Patchouli Battle",
    "Use a Shop Ticket in the Remilia Battle"
];
