bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "100% the Map",
    "Beat Cirno with only Timestop Attacks",
    "Beat Cirno without taking damage",
    "Beat Flandre without taking damage",
    "Beat Flandre without using Skills",
    "Beat Marisa with only Chainsaw",
    "Beat Marisa without taking damage",
    "Beat Meiling without taking damage",
    "Beat Meiling without using Snail Time",
    "Beat Nitori without reaching Phase 2",
    "Beat Nitori without taking damage",
    "Beat Nitori without using Time Stop",
    "Beat Patchouli with only Thousand Dagger",
    "Beat Patchouli without taking damage",
    "Beat Reimu Air with only Stun Knife",
    "Beat Reimu Air without taking damage",
    "Beat Reimu Ground with only Auto Aim",
    "Beat Reimu Ground without taking damage",
    "Beat Remilia without taking damage",
    "Beat Remilia without using Chainsaw",
    "Break 1 Wooden Box",
    "Break 2 Wooden Boxes",
    "Break 3 Wooden Boxes",
    "Break 4 Wooden Boxes",
    "Break 5 Wooden Boxes",
    "Break 6 Wooden Boxes",
    "Break All Jewel Towers",
    "Break the Amethyst Jewel Tower",
    "Break the Aquamarine Jewel Tower",
    "Break the Diamond Jewel Tower",
    "Break the Emerald Jewel Tower",
    "Break the Ruby Jewel Tower",
    "Break the Sapphire Jewel Tower",
    "Break the Topaz Jewel Tower",
    "Buy 1 Eternal Clock from Nitori's Shop",
    "Buy 1 HP Recovery from Nitori's Shop",
    "Buy 1 Knife Upgrade from Nitori's Shop",
    "Buy 1 MP Recovery from Nitori's Shop",
    "Buy 1 TP Recovery from Nitori's Shop",
    "Buy 3 HP Recoveries from Nitori's Shop",
    "Buy 3 MP Recoveries from Nitori's Shop",
    "Buy 3 TP Recoveries from Nitori's Shop",
    "Carry a Shop Ticket into the Nitori Battle",
    "Carry a Shop Ticket into the Reimu Battle",
    "Complete Boss Rush with B-Rank or better",
    "Complete Boss Rush without Basic Knives",
    "Damage boost through a Fire Barrier in Stage 6",
    "Defeat a Cannon Fairy in Stage 2",
    "Defeat a Floating Clown in Stage 4",
    "Defeat a Jumping Kappa in Stage 1",
    "Defeat a Time Rabbit in Stage 5",
    "Defeat a Toy Drummer in Stage 3",
    "Defeat a Trickster Fox in Stage 6",
    "Defeat a Wisp in Every Stage",
    "Defeat a Wisp in Stage 1",
    "Defeat a Wisp in Stage 2",
    "Defeat a Wisp in Stage 3",
    "Defeat a Wisp in Stage 4",
    "Defeat a Wisp in Stage 5",
    "Defeat a Wisp in Stage 6",
    "Die in All Stages",
    "Die in Stage 1",
    "Die in Stage 2",
    "Die in Stage 3",
    "Die in Stage 4",
    "Die in Stage 5",
    "Die in Stage 6",
    "Discover the Warp Zone in All Stages",
    "Discover the Warp Zone in Stage 1",
    "Discover the Warp Zone in Stage 2",
    "Discover the Warp Zone in Stage 3",
    "Discover the Warp Zone in Stage 4",
    "Discover the Warp Zone in Stage 5",
    "Discover the Warp Zone in Stage 6",
    "Dunk All Wastebins in All Stages",
    "Dunk All Wastebins in Stage 1",
    "Dunk All Wastebins in Stage 2",
    "Dunk All Wastebins in Stage 3",
    "Dunk All Wastebins in Stage 4",
    "Dunk All Wastebins in Stage 5",
    "Dunk Wastebin 1 in All Stages",
    "Dunk Wastebin 2 in All Stages",
    "Dunk Wastebin 3 in All Stages",
    "Dunk a Wastebin in All Stages",
    "Fall through the ground in Stage 3",
    "Finish Off Cirno with a Timestop Stun Knife",
    "Finish Off Flandre with Auto Aim",
    "Finish Off Marisa with Stun Knife",
    "Finish Off Meiling with a Slide",
    "Finish Off Patchouli with a Double Jump",
    "Finish Off Reimu Air with Shield Dagger",
    "Finish Off Reimu Ground with a Slide",
    "Finish Off Remilia with Shield Dagger",
    "Fly up on the Destroyed Bridge in Stage 4",
    "Get All Abilities",
    "Get All Key Items",
    "Get All Skills",
    "Get hit by Cirno's Thousand Icicles",
    "Get hit by Flandre's Wing Snare Trap",
    "Get hit by Marisa's Dash Attack",
    "Get hit by Meiling's Fkying Kick",
    "Get hit by Nitori's Guided Missles",
    "Get hit by Patchouli's Golden Dragons",
    "Get hit by Reimu Air's Exploding Talisman",
    "Get hit by Reimu Ground's Taser Whip",
    "Get hit by Remilia's Bat Swarm",
    "Get hit by a Baby Dragon in Stage 5",
    "Get hit by a Bubble Fairy in Stage 3",
    "Get hit by a Jellyfish in Stage 4",
    "Get hit by a Lightning Shaman in Stage 6",
    "Get hit by a Skeleton in Stage 2",
    "Get hit by a Wind Shaman in Stage 1",
    "Get the Auto Aim Skill",
    "Get the Blue Key",
    "Get the Chainsaw Skill",
    "Get the Dash Spike Ability",
    "Get the Double Jump Ability",
    "Get the Eternal Clock in All Stages",
    "Get the Eternal Clock in Stage 1",
    "Get the Eternal Clock in Stage 2",
    "Get the Eternal Clock in Stage 3",
    "Get the Eternal Clock in Stage 4",
    "Get the Eternal Clock in Stage 5",
    "Get the Green Key",
    "Get the Grip Knife Ability",
    "Get the HP Upgrade in All Stages",
    "Get the HP Upgrade in Stage 1",
    "Get the HP Upgrade in Stage 2",
    "Get the HP Upgrade in Stage 3",
    "Get the HP Upgrade in Stage 4",
    "Get the HP Upgrade in Stage 5",
    "Get the Ice Magatama",
    "Get the Knife Upgrade in All Stages",
    "Get the Knife Upgrade in Stage 1",
    "Get the Knife Upgrade in Stage 2",
    "Get the Knife Upgrade in Stage 3",
    "Get the Knife Upgrade in Stage 4",
    "Get the Knife Upgrade in Stage 5",
    "Get the Lost Holy Sword Skill",
    "Get the MP Upgrade in All Stages",
    "Get the MP Upgrade in Stage 1",
    "Get the MP Upgrade in Stage 2",
    "Get the MP Upgrade in Stage 3",
    "Get the MP Upgrade in Stage 4",
    "Get the MP Upgrade in Stage 5",
    "Get the Purple Key",
    "Get the Red Key",
    "Get the Screw Knife Ability",
    "Get the Shield Dagger Skill",
    "Get the Sliding Knife Ability",
    "Get the Stun Knife Skill",
    "Get the Thousand Dagger Skill",
    "Get the Yellow Key",
    "Hover over the Rotating Gate in Stage 1",
    "Jump around the Blue Door in Stage 2",
    "Negate damage from Spikes in Stage 5",
    "Obtain 1 Diamond Jewel",
    "Obtain 10 Sapphire Jewels",
    "Obtain 100 Aquamarine Jewels",
    "Obtain 25 Ruby Jewels",
    "Obtain 250 Amethyst Jewels",
    "Obtain 5 Emerald Jewels",
    "Obtain 50 Topaz Jewels",
    "Reach 145 TIME Gauge",
    "Reach 27 Time Stop Knives",
    "Reach Level 10",
    "Reach Level 15",
    "Reach Level 5",
    "Receive 1 Shop Ticket from Nitori",
    "Receive 3 Shop Tickets from Nitori",
    "Score 25,000 Points during the Credits Game",
    "Score 50,000 Points during the Credits Game",
    "Stand on a platform with a Green Aura",
    "Stand on a platform with a Purple Aura",
    "Stand on a platform with a Yellow Aura",
    "Use Bound Knife in Stage 4",
    "Use Chainsaw in Stage 6",
    "Use Dash Spike in Stage 5",
    "Use Double Jump in Stage 2",
    "Use Grip Knife in Stage 3",
    "Use Lost Holy Sword in Stage 5",
    "Use Screw Knife in Stage 1",
    "Use Shield Dagger in Stage 3",
    "Use Sliding Knife in Stage 1",
    "Use Stun Knife in Stage 4",
    "Use Thousand Dagger in Stage 2",
    "Use a Shop Ticket in the Marisa Battle",
    "Use a Shop Ticket in the Meiling Battle",
    "Use a Shop Ticket in the Patchouli Battle",
    "Use a Shop Ticket in the Remilia Battle"
];
