bingoGenerator = require("./generators/generator_bases/simple_generator.js");
//Made By TK
var bingoList = [
{"name": "Coin token from AH"},
{"name": "Collectable token from AH"},
{"name": "Coin token from AN"},
{"name": "Collectable token from AN"},
{"name": "Coin token from CY"},
{"name": "Collectable token from CY"},
{"name": "Coin token from A&G"},
{"name": "Collectable token from A&G"},
{"name": "Coin token from ATB"},
{"name": "Collectable token from ATB"},
{"name": "Coin token from ASL"},
{"name": "Collectable token from ASL"},
{"name": "Coin token from EH"},
{"name": "Collectable token from EH"},
{"name": "Coin token from AP"},
{"name": "Collectable token from AP"},
{"name": "Coin token from AI"},
{"name": "Collectable token from AI"},
{"name": "Coin token from TT"},
{"name": "Collectable token from TT"},
{"name": "Race token in AH and Boss token in TT"},
{"name": "Race token in AN and Boss token in ASL"},
{"name": "Race token in CY and Boss token in EH"},
{"name": "Race token in A&G and Boss token in AI"},
{"name": "Race token in ATB and Boss token in AP"},
{"name": "Race token in ASL and Boss token in A&G"},
{"name": "Race token in EH and Boss token in AN"},
{"name": "Race token in AP and Boss token in CY"},
{"name": "Race token in AI and Boss token in AH"},
{"name": "Race token in TT and Boss token in ATB"},
{"name": "Race token in AH and Mystery token in AP"},
{"name": "Race token in AN and Mystery token in A&G"},
{"name": "Race token in CY and Mystery token in ATB"},
{"name": "Race token in A&G and Mystery token in TT"},
{"name": "Race token in ATB and Mystery token in ASL "},
{"name": "Race token in ASL and Mystery token in AI"},
{"name": "Race token in EH and Mystery token in AH"},
{"name": "Race token in AP and Mystery token in EH"},
{"name": "Race token in AI and Mystery token in AN"},
{"name": "Race token in TT and Mystery token in CY"},
{"name": "Boss token in AH and Mystery token in CY"},
{"name": "Boss token in AN and Mystery token in AP "},
{"name": "Boss token in CY and Mystery token in A&G"},
{"name": "Boss token in A&G and Mystery token in AH "},
{"name": "Boss token in ATB and Mystery token in AI"},
{"name": "Boss token in ASL and Mystery token in TT"},
{"name": "Boss token in EH and Mystery token in ATB"},
{"name": "Boss token in AP and Mystery token in ASL"},
{"name": "Boss token in AI and Mystery token in EH"},
{"name": "Boss token in TT and Mystery token in AN"},
{"name": "All tokens from AH"},
{"name": "All tokens from AN"},
{"name": "3 tokens from CY"},
{"name": "3 tokens from A&G"},
{"name": "3 tokens from ATB"},
{"name": "All tokens from ASL"},
{"name": "All tokens from EH"},
{"name": "3 tokens from AP"},
{"name": "All tokens from AI"},
{"name": "3 tokens from TT"},
{"name": "13 Tokens"},
{"name": "21 Tokens"},
{"name": "4 Race tokens"},
{"name": "4 Boss tokens"},
{"name": "4 Mystery tokens"},
{"name": "2 coins tokens "},
{"name": "2 collectable tokens"},
{"name": "Unlock shield powerup"},
{"name": "Unlock disc powerup"},
{"name": "Unlock speed powerup"},
{"name": "Unlock grapplin powerup"},
{"name": "Unlock hover powerup"},
{"name": "Battery from BA, AH and A&G"},
{"name": "Battery from TBE, ATB and TT"},
{"name": "Battery from AN, CY and AP"},
{"name": "Battery from ASL and AI"},
{"name": "Green laser from ST, A&G and AH"},
{"name": "Green laser from AN, CY and ASL"},
{"name": "Green laser from ATB, AP and EH"},
{"name": "Green laser from TT and AI"},
{"name": "Talk to rex in 4+ levels "},
{"name": "Defeat 5 bosses and/or minibosses"},
{"name": "Defeat BA and ST bosses"},
{"name": "Defeat EEZ and TBE bosses"},
{"name": "Defeat Final Showdown bosses"},
{"name": "2 tokens from both AH and ATB"},
{"name": "2 tokens from both AN and CY"},
{"name": "2 tokens from both A&G and AP"},
{"name": "2 tokens from both ASL and AI"},
{"name": "2 tokens from both EH and TT"},
{"name": "8 lives"},
{"name": "2 tokens that require potato powerups "},
{"name": "Talk to 5 NPCs in the same level "},
{"name": "Go inside water in 3 levels"},
{"name": "Use a cable in 3 levels"},
{"name": "1 token from 5+ levels"},
{"name": "Exit a level with more than 65 coins"},
{"name": "1 collectable from 4+ levels"}
];
