bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList =
[
    "10 spine friendly fire kills",
    "Activate 20 OVCs",
    "After bay, don't take any actions in turn before royce unless at the beach(OVC OOB is still allowed)",
    "After bay, don't use jaunt in a primary slot unless at the beach",
    "After first savepoint, don't use spark in a primary slot unless at the beach",
    "Allow 10 cells to respawn into non-bad cells",
    "Allow operators to spawn 15 process",
    "Archive 3 posts at OVCs(fairview)",
    "Be locked out of 4 skills at one time",
    "Be locked out of 5 skills at one time",
    "Change the weather in the bay",
    "Check 6 different bodies",
    "Cold flatbread with your bro",
    "Complete 1 fight with 5 limiters active",
    "Complete 1 tests in 4 categories",
    "Complete 3 Performance Tests",
    "Complete 3 Planning Tests",
    "Complete 3 Speed Tests",
    "Complete 3 Stability Tests",
    "Complete 3 fights only taking actions in turn",
    "Complete 3 fights with 10% bonus experience from limiters",
    "Complete 3 fights with 4 limiters active",
    "Complete 3 fights with only 1 active skill",
    "Complete a fight with a cheerleader being the last non-cell enemy defeated",
    "Complete a fight with a skill costing at least 11 memory",
    "Complete any 6 tests",
    "Complete the function file for Bounce()",
    "Complete the function file for Breach()",
    "Complete the function file for Crash()",
    "Complete the function file for Get()",
    "Complete the function file for Help()",
    "Complete the function file for Jaunt()",
    "Complete the function file for Load()",
    "Complete the function file for Mask()",
    "Complete the function file for Ping()",
    "Complete the function file for Spark()",
    "Complete the function file for Switch()",
    "Damage 5 enemies with a single breach",
    "Defeat 5 snapshots in a single battle",
    "Eliminate all the cells in the lady 3.0 room",
    "Get the Transistor's input on 20 non-OVC things!",
    "Get told you are going the wrong way 3 times",
    "Get told you are mean(Overkill%)",
    "Get your picture taken 10 times",
    "Grab the bike in Recursion",
    "Have 2 two-way conversaitions with the transistor using the OVC terminal",
    "Have the transistor tell you how it really feels(I hate you%)",
    "Hum 10 different songs",
    "Humless hum",
    "Kill 10 cluckers",
    "Kill 10 men",
    "Kill 14 men(Hard)",
    "Kill 15 cheerleaders",
    "Kill 15 cluckers(Hard)",
    "Kill 20 cheerleaders(Hard)",
    "Kill 20 creeps",
    "Kill 20 snapshots",
    "Kill 25 creeps(Hard)",
    "Kill 25 snapshots(Hard)",
    "Kill 3 fetches",
    "Kill 3 young ladys",
    "Kill 5 fetches(Hard)",
    "Kill 5 jerks",
    "Kill 5 operators",
    "Kill 5 young ladys(Hard)",
    "Kill 6 jerks(Hard)",
    "Kill 6 operators(Hard)",
    "Kill Royce",
    "Kill all enemies in the channel",
    "Kill the 3 cluckers in highrise (wooo%)",
    "Listen to all 4 of the proxy's monologues",
    "Listen to the transistor ramble(damn%)",
    "Lose access to 2 skills in a single fight",
    "Lose access to 3 skills in a single fight",
    "Never allocate a skill to the passive slot",
    "Never get locked out of a skill",
    "Obtain a max memory capacity of 20",
    "Order the same flatbread twice from Junction Jan's",
    "Play fetch with some Help",
    "Post to OVC message boards 5 times",
    "Reach user level 7",
    "Reach user level 8",
    "Reach user level 9",
    "Respond to 6 audio OVCs from Asher",
    "Scare off 6 flocks of birds",
    "Take 15 actions in a single turn challenge",
    "Unless at the beach, don't use crash in a secondary slot",
    "Unless at the beach, don't use load in a primary slot",
    "Visit the beach 4 times",
    "Visit the beach all 7 times",
    "Visit the little girls room",
    "Vote 5 times in OVCs",
    "Watch the 4 non-travel cutscenes"
];
