bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "100% the game",
    "Beat the game",
    "Complete all Main Tasks",
    "Complete all Other Tasks",
    "Complete all Tasks",
    "Complete the task Be awarded a flower in Pub",
    "Complete the task Break the broom in High Street",
    "Complete the task Break the dartboard in Pub",
    "Complete the task Cabbage picnic",
    "Complete the task Catch an object as it's thrown over the fence",
    "Complete the task Collect the five flowers",
    "Complete the task Complete the back gardens to-do list before the church bells ring",
    "Complete the task Complete the garden to-do list before the church bells ring",
    "Complete the task Complete the high street to-do list before the church bells ring",
    "Complete the task Complete the pub to-do list before the church bells ring",
    "Complete the task Do the Washing in Back Gardens",
    "Complete the task Get dressed up with a ribbon in Back Gardens",
    "Complete the task Get into the pub in Pub",
    "Complete the task Get on t.v. in High Street",
    "Complete the task Get the Gardener wet in Garden",
    "Complete the task Get the toy boat in Pub",
    "Complete the task Get thrown over the fence",
    "Complete the task Go Shopping in High Street",
    "Complete the task Help the woman dress up the bust in Back Gardens",
    "Complete the task Lock the groundskeeper out of the garden",
    "Complete the task Make someone break the fancy vase in Back Gardens",
    "Complete the task Make someone buy back their own stuff in High Street",
    "Complete the task Make someone from outside the high street buy back their own stuff",
    "Complete the task Make the Gardener wear his sun hat in Garden",
    "Complete the task Make the boy wear the wrong glasses in High Street",
    "Complete the task Make the man go barefoot in Back Gardens",
    "Complete the task Make the old man fall on his bum in Pub",
    "Complete the task Make the shop scales go ding",
    "Complete the task Open an umbrella inside the tv shop",
    "Complete the task Perform at the pub wearing a ribbon",
    "Complete the task Picnic in Garden",
    "Complete the task Put the rake into the lake in Garden",
    "Complete the task Sail the toy boat under a bridge",
    "Complete the task Score a goal",
    "Complete the task Set the Table in Back Gardens",
    "Complete the task Steal a pint glass and drop it in the canal in Pub",
    "Complete the task Steal the keys in Garden",
    "Complete the task Steal the old man's woolen hat",
    "Complete the task Trap the boy in the garage",
    "Complete the task Trap the boy in the phone booth in High Street",
    "Complete the task Trip the boy in the puddle",
    "Complete the task Untitled Goose in Garden",
    "Complete the task make the man spit out his tea in Back Gardens",
    "Complete the tasks in Back Gardens",
    "Complete the tasks in Garden",
    "Complete the tasks in High Street",
    "Complete the tasks in Model Village",
    "Complete the tasks in Pub",
    "Complete the tasks in both to do (as well) and to do (as well) (part 2)",
    "Complete the tasks in to do (as well)",
    "Complete the tasks in to do (as well) (part 2)",
    "Complete the tasks in to do (quickly!!)",
    "Finish the tasks in Back Gardens",
    "Finish the tasks in Garden",
    "Finish the tasks in High Street",
    "Finish the tasks in Model Village",
    "Finish the tasks in Pub",
    "Finish the tasks in both to do (as well) and to do (as well) (part 2)",
    "Finish the tasks in to do (as well)",
    "Finish the tasks in to do (as well) (part 2)",
    "Finish the tasks in to do (quickly!!)",
    "Make all of the Back Gardens characters go into the lake (2)",
    "Make all of the Garden characters go into the lake (1)",
    "Make all of the High Street characters go into the lake (3)",
    "Make all of the Pub characters go into the lake (6)",
    "Make every character go into the lake",
    "Make the Blue Woman go into the lake",
    "Make the Delivery Person go into the lake",
    "Make the Groundskeeper go into the lake",
    "Make the Messy Neighbor go into the lake",
    "Make the Old Man go into the lake",
    "Make the Publician go into the lake",
    "Make the Publician's Husband go into the lake",
    "Make the Shopkeeper go into the lake",
    "Make the TV Shop Owner go into the lake",
    "Make the Tidy Neighbor go into the lake",
    "Make the Wimp go into the lake",
    "Make the Yellow Woman go into the lake",
    "Put all grabbable items from Back Gardens in the lake (33)",
    "Put all grabbable items from Back Gardens in the well (33)",
    "Put all grabbable items from Garden in the lake (39)",
    "Put all grabbable items from Garden in the well (39)",
    "Put all grabbable items from High Street in the lake (37)",
    "Put all grabbable items from High Street in the well (37)",
    "Put all grabbable items from Home in the lake (4)",
    "Put all grabbable items from Home in the well (4)",
    "Put all grabbable items from Model Village in the lake (20)",
    "Put all grabbable items from Model Village in the well (20)",
    "Put all grabbable items from Pub in the lake (24)",
    "Put all grabbable items from Pub in the well (24)",
    "Put all grabbable items in the lake (306)",
    "Put all grabbable items in the well (306)"
];
