bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Alyx (Half-Life)",
    "Apex Legends",
    "Bill (Left 4 Dead)",
    "Bowser",
    "Connect Four board game",
    "Crowbar (Half-Life)",
    "Donkey Kong",
    "Dungeons & Dragons",
    "Fortnite",
    "Francis (Left 4 Dead)",
    "Game of Life",
    "Gordon Freeman (Half-Life)",
    "Gravity gun (Half-Life)",
    "Guess Who? board game",
    "Half-Life",
    "Halo",
    "Kingdom Hearts",
    "Kirby",
    "Left 4 Dead",
    "Legend of Zelda",
    "Link",
    "Luis (Left 4 Dead)",
    "Mario",
    "Minecraft",
    "Monopoly",
    "Nick (Left 4 Dead)",
    "Nintendo",
    "Pikachu",
    "Pikmin",
    "Samus",
    "Scrabble",
    "Sorry! board game",
    "Square Enix",
    "Stardew Valley",
    "Steam",
    "Super Smash Bros",
    "Uno!",
    "Valve",
    "War card game"
];
