bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "100 Pointer (Return Challenge)",
    "200 Point Dive (Skydiving)",
    "200 Pointer (Return Challenge)",
    "3-Stage Master (Cycling)",
    "50 Pointer (Return Challenge)",
    "A for Effort (Frisbee Dog)",
    "Back From the Brink (TT Match)",
    "Bag of Tricks (Wakeboarding)",
    "Balloon Animal (Frisbee Dog)",
    "Beginner Licence (Canoeing)",
    "Bonus Plumber (3-Point Contest)",
    "Bull Stampede (Archery)",
    "Buzzer Beater (Pickup Game)",
    "Camera Shy (Skydiving)",
    "Century Shot (Archery)",
    "Chip It In (Golf)",
    "Cliff-Hanger (Duel)",
    "Double Time (Speed Slice)",
    "Ducks in a Row (Canoeing)",
    "Epic Rally (TT Match)",
    "Expert Licence (Canoeing)",
    "First of Many (Cycling)",
    "Follow That Plane (Island Flyover)",
    "For the Birds (Skydiving)",
    "Friends in High Places (Skydiving)",
    "Gobble Gobble (Bowling)",
    "Good Dog (Frisbee Dog)",
    "Head First (Spin Control)",
    "High Five (Skydiving)",
    "Hole In One (Frisbee Golf)",
    "Hot Streak (3-Point Contest)",
    "Huge Air (Wakeboarding)",
    "In Your Face (TT Match)",
    "Intermediate Licence (Canoeing)",
    "Island Hopper (Island Flyover)",
    "King of Clubs (Golf)",
    "Last Gasp (Cycling)",
    "Leisure Cruiser (Power Cruising)",
    "Lights Out (Pickup Game)",
    "Lucky Skip (Frisbee Golf)",
    "Master Carver (Wakeboarding)",
    "Met Your Match (Duel)",
    "Not a Scratch (Showdown)",
    "Off the Wall (100-Pin Game)",
    "On a Roll (Frisbee Golf)",
    "One for All (Spin Control)",
    "One-Hit Wonder (Duel)",
    "Perfect Target (Frisbee Dog)",
    "Perfectly Matched (TT Match)",
    "Pin Dropper (100-Pin Game)",
    "Pin Dropper (Bowling)",
    "Pop Frenzy (Island Flyover)",
    "Power Cruiser (Power Cruising)",
    "Power Jumper (Power Cruising)",
    "Pro Bowler (Bowling)",
    "Psychic Slice (Speed Slice)",
    "Quick Draw (3-Point Contest)",
    "Rim Rattler (Pickup Game)",
    "Ringmaster (Power Cruising)",
    "Secret Strike (100-Pin Game)",
    "Slice and Dice (Speed Slice)",
    "Slicing Machine (Speed Slice)",
    "Smooth Landing (Wakeboarding)",
    "Split Spare (100-Pin Game)",
    "Split Spare (Bowling)",
    "Split Spare (Spin Control)",
    "Straight to the Point (Duel)",
    "Super Strike (100-Pin Game)",
    "Sure Shot (Archery)",
    "Sword Fighter (Showdown)",
    "Swordmaster (Showdown)",
    "The Long Way Home (Wakeboarding)",
    "Triple Dip (Pickup Game)",
    "Under Par (Frisbee Golf)",
    "Under Par (Golf)"
];
