bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Become a Super Mii and buy a photo.",
    "Buy all 3 cards from a shop.",
    "Collect 4 photos in total.",
    "Collect at least 40 coins from minigames.",
    "Don't use any special cards for 4 turns in a row.",
    "Drive in a taxi.",
    "Fly in a balloon.",
    "Fly in a helicopter.",
    "Fly on a plane.",
    "Get a photo from any African country.",
    "Get a photo from any American country.",
    "Get a photo from any Asian country.",
    "Get a photo from any European country.",
    "Get paid 10 coins for a job.",
    "Get paid less than 5 coins for a job.",
    "Get the first photo of a new tour.",
    "Get the last photo of the game.",
    "Get transported by a UFO.",
    "Have 2 helicopter cards at once.",
    "Have 2 train cards at once.",
    "Have 5 special cards at once.",
    "Have cards that sum up to 20 or more.",
    "Have more coins than your opponents combined.",
    "Have more than 50 coins.",
    "Have the same minimum distance to 2 Hot Spots.",
    "Land on a surprise space.",
    "Land on the same space as an opponent.",
    "Land on the starting space again.",
    "Move in a train.",
    "Move more than 7 spaces in one turn.",
    "Sail on a boat.",
    "Steal/Get coins from an opponent.",
    "Take 2 jobs in consecutive turns.",
    "Travel the same amount of spaces 3 turns in a row.",
    "Win 5 minigames in a row.",
    "Win a 1 vs. 3 minigame."
];
