bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "1-Stage Master (Cycling)",
    "100 Pointer (Return Challenge)",
    "200 Point Dive (Skydiving)",
    "200 Pointer (Return Challenge)",
    "3-Stage Master (Cycling)",
    "50 Pointer (Return Challenge)",
    "5000-Pointer (Power Cruising)",
    "6-Stage Maste (Cycling)",
    "A Cut Above (Speed Slice)",
    "A Secret to Everybody (Archery)",
    "A for Effort (Frisbee Dog)",
    "Ace of Clubs (Golf)",
    "Back From the Brink (TT Match)",
    "Bag of Tricks (Wakeboarding)",
    "Balloon Animal (Frisbee Dog)",
    "Balloonatic (Island Flyover)",
    "Beginner Licence (Canoeing)",
    "Bonus Plumber (3-Point Contest)",
    "Bull Stampede (Archery)",
    "Buzzer Beater (Pickup Game)",
    "Camera Shy (Skydiving)",
    "Century Shot (Archery)",
    "Chip It In (Golf)",
    "Cliff-Hanger (Duel)",
    "Cut the Red Tape (Canoeing)",
    "Double Time (Speed Slice)",
    "Ducks in a Row (Canoeing)",
    "English Major (Spin Control)",
    "Epic Rally (TT Match)",
    "Expert Licence (Canoeing)",
    "First of Many (Cycling)",
    "Follow That Plane (Island Flyover)",
    "For the Birds (Skydiving)",
    "Friends in High Places (Skydiving)",
    "Gobble Gobble (Bowling)",
    "Golden Arm (Frisbee Dog)",
    "Good Dog (Frisbee Dog)",
    "Head First (Spin Control)",
    "High Five (Skydiving)",
    "Hole In One (Frisbee Golf)",
    "Hole-In-One (Golf)",
    "Hoop Hero (Pickup Game)",
    "Hot Hand (3-Point Contest)",
    "Hot Streak (3-Point Contest)",
    "Huge Air (Wakeboarding)",
    "In Your Face (TT Match)",
    "Intermediate Licence (Canoeing)",
    "Island Hopper (Island Flyover)",
    "King of Clubs (Golf)",
    "Last Gasp (Cycling)",
    "Last Mii Standing (Duel)",
    "Leisure Cruiser (Power Cruising)",
    "Lights Out (Pickup Game)",
    "Lucky Skip (Frisbee Golf)",
    "Master Carver (Wakeboarding)",
    "Met Your Match (Duel)",
    "Not a Scratch (Showdown)",
    "Off the Wall (100-Pin Game)",
    "On a Roll (Frisbee Golf)",
    "One for All (Spin Control)",
    "One-Hit Wonder (Duel)",
    "Perfect 10 (Showdown)",
    "Perfect Game (Bowling)",
    "Perfect Target (Frisbee Dog)",
    "Perfectly Matched (TT Match)",
    "Pin Dropper (100-Pin Game)",
    "Pin Dropper (Bowling)",
    "Pin Dropper (Spin Control)",
    "Pop Frenzy (Island Flyover)",
    "Power Cruiser (Power Cruising)",
    "Power Jumper (Power Cruising)",
    "Pro Bowler (Bowling)",
    "Psychic Slice (Speed Slice)",
    "Pure Shooter (3-Point Contest)",
    "Quick Draw (3-Point Contest)",
    "Recycler (Return Challenge)",
    "Rim Rattler (Pickup Game)",
    "Ringmaster (Power Cruising)",
    "Save Face (Return Challenge)",
    "Secret Strike (100-Pin Game)",
    "Sharpshooter (Archery)",
    "Slice and Dice (Speed Slice)",
    "Slicing Machine (Speed Slice)",
    "Smooth Landing (Wakeboarding)",
    "Split Spare (100-Pin Game)",
    "Split Spare (Bowling)",
    "Split Spare (Spin Control)",
    "Straight and Narrow (Frisbee Golf)",
    "Straight to the Point (Duel)",
    "Super Strike (100-Pin Game)",
    "Sure Shot (Archery)",
    "Sword Fighter (Showdown)",
    "Swordmaster (Showdown)",
    "Table Titan (TT Match)",
    "The Long Way Home (Wakeboarding)",
    "Triple Dip (Pickup Game)",
    "Under Par (Frisbee Golf)",
    "Under Par (Golf)",
    "Untouchable (Showdown)",
    "Wuhu Tour Gide (Island Flyover)"
];
