bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList =
[
    "Beat an opponent 6-0 in Table Tennis - Match",
    "Beat an opponent in an 11-Point match in Table Tennis - Match",
    "Beat the opponents by 10 points or more in Basketball - Pickup Game",
    "Clear the first 3 levels in Swordplay Showdown",
    "Collect an i Point on Wedge Island in Island Flyover",
    "Complete 3 stages in Canoeing",
    "Complete Clasic B in Frisbee Golf",
    "Complete Classic A in Frisbee Golf",
    "Complete Classic A in Golf",
    "Complete Classic B in Golf",
    "Complete Classic C in Frisbee Golf",
    "Complete Classic C in Golf",
    "Complete Resort A in Frisbee Golf",
    "Complete Resort A in Golf",
    "Complete Resort B in Frisbee Golf",
    "Complete Resort B in Golf",
    "Complete Resort C in Frisbee Golf",
    "Complete Resort C in Golf",
    "Complete a stage in Canoeing - Expert",
    "Complete a stage of Power Cruising without going out of bounds",
    "Complete any 3 hole course Blind (Holding 2 before selecting course)",
    "Complete any Cycling race without going down to 0 hearts",
    "Complete the \"Across the Bridge\" race in Cycling",
    "Complete the \"Up the Volcano\" race in Cycling",
    "Complete the Power Crusing course \"Lagoon\"",
    "Complete the Power Crusing course \"Shoals\"",
    "Crash 5 times in Island Flyover",
    "Crash into lava in Island Flyover",
    "Fall off a cliff/into a river twice in Cycling",
    "Finish 1st in any Cycling race",
    "Finish any 3 Hole course in Frisbee Golf without touching bunkers or water",
    "Finish any 3 Hole course in Golf without touching bunkers or water",
    "Finish any Frisbee Golf 3 hole course with only the Driver Frisbee",
    "Gain 30 points in Table Tennis - Return Challenge without hitting any can",
    "Get 100 or more points in Archery - Beginner",
    "Get 1000 or more points in Wakeboarding - Intermediate",
    "Get 15 or more points in Basketball - 3 Point Contest",
    "Get 25 points or more in Skydiving",
    "Get 3 mid-air catches in Frisbee Dog",
    "Get 3 spares in any Bowling mode",
    "Get 50 or more points in Archery - Expert",
    "Get 500 or more points in Frisbee Dog",
    "Get 700 or more points in Wakeboarding - Expert",
    "Get a score higher than 5 in 4 gates on Power Cruising",
    "Get a score of 1.0 on 5 gates in Power Cruising",
    "Get a score of 1600 or over in Wakeboarding - Beginner",
    "Get a score of over 1500 in Bowling - 100-Pin Game",
    "Get a score of over 70 points in Archery - Intermediate",
    "Get a time of under 2:05.00 in Cycling - To the Beach",
    "Get a turkey in any bowling mode",
    "Get any stamp in Archery",
    "Get any stamp in Basketball - 3 Point Contest",
    "Get any stamp in Basketball - Pickup Game",
    "Get any stamp in Bowling - 100 Pin Game",
    "Get any stamp in Bowling - Spin Control",
    "Get any stamp in Bowling - Standard Game",
    "Get any stamp in Canoeing",
    "Get any stamp in Cycling",
    "Get any stamp in Frisbee Dog",
    "Get any stamp in Frisbee Golf",
    "Get any stamp in Golf",
    "Get any stamp in Island Flyover",
    "Get any stamp in Power Crusing",
    "Get any stamp in Skydiving",
    "Get any stamp in Swordplay - Duel",
    "Get any stamp in Swordplay - Showdown",
    "Get any stamp in Swordplay - Speed Slice",
    "Get any stamp in Table Tennis - Match",
    "Get any stamp in Table Tennis - Return Challenge",
    "Get any stamp in Wakeboarding",
    "Get over 100 points in Bowling - Spin Control",
    "Get over 100 points in Table Tennis - Return Challenge",
    "Get over 170 points in a Standard Game of Bowling",
    "Get par/under par on any 3 hole course in Golf",
    "Get the \"Miguels's Plane\" i Point in Island Flyover",
    "Get the i Point in the Volcano in Island Flyover",
    "Get the i Point on the Bowling court in Island Flyover",
    "Get two slam dunks in Basketball - Pickup game",
    "Give Up on 5 different holes in Golf",
    "Give up on 2 different holes in Golf with only water hazards",
    "Hit 10 cans in Table Tennis - Return Challenge",
    "Hit any secret target in Archery",
    "Hit the 10 point mark on Archery 3 times in a row",
    "Hit the barriers every throw in Bowling - Spin Control (Minus the 10th frame)",
    "Hit the five point area in Archery",
    "Hit the server's face with a ball 10 times in Table Tennis - Return Challenge",
    "Hit your opponent in the face 3 times with a ball in Table Tennis - Match",
    "Pop a balloon in Frisbee Dog two times",
    "Pop all 5 time balloons in the Power Cruising Free Practice",
    "Ride over 3 different rocks/bananas in Cycling (Doesn't have to be all in 1 race)",
    "Slice 15 items in Swordplay - Speed Slice practice",
    "Slice two candles in Swordplay - Speed Slice",
    "Slice two clocks in Swordplay - Speed Slice",
    "Slice two pieces of bread in Swordplay - Speed Slice",
    "Stun your opponent by blocking 7 times in Swordplay - Duel",
    "Take a picture with Gwen in Skydiving",
    "Win a game of Swordplay - Speed Slice without letting the opponent get any points",
    "Win a match of Swordplay - Duel without getting stuned by an opponent's block"
];
