bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Complete a Wii Fitness training session",
    "Finish 9-Hole Game in Golf",
    "Finish Beginner in Golf",
    "Finish Expert in Golf",
    "Finish Intermediate in Golf",
    "Finish any 3-Hole Golf course without touching bunkers or water",
    "Finish any Golf course Blind(Hold 2)",
    "Finish any course in Golf without using the driver",
    "Finish any game in Baseball",
    "Finish any game in Baseball with a mercy rule",
    "Get 140 or more points without a gutter ball",
    "Get 165 or more points in a Standard Game of Bowling",
    "Get 2 Home Runs in Baseball",
    "Get 3 Spares in Bowling",
    "Get 3 Spares with a different Color Ball then Blue(hold any button on D-Pad besides up)",
    "Get 3 Strikeouts in Baseball",
    "Get 3 Strikes in Bowling(Doesn’t have to be a Turkey)",
    "Get a Bunt Single in Baseball",
    "Get a Gold Medal in any Training Game",
    "Get a Silver Medal in any Training Game",
    "Get a Triple in Baseball",
    "Get a Turkey in Bowling",
    "Get all gutters in Bowling(Except the third throw on the 10th Frame)",
    "Get at least 10 points in Timing your Swing(Tennis Training)",
    "Get at least 12 points in Returning Balls(Tennis Training)",
    "Get at least 15 points in Batting Practice(Baseball Training)",
    "Get at least 15 points in Working the Bag(Boxing Training)",
    "Get at least 200 points in Target Practice(Golf Training)",
    "Get at least 25 points in Swing Control(Baseball Training)",
    "Get at least 30 points in Throwing Punches(Boxing Training)",
    "Get at least 450 points in Power Throws(Bowling Training)",
    "Get at least 5 points in Target Practice(Tennis Training)",
    "Get at least 50 points in Dodging(Boxing Training)",
    "Get past at least 5 stages in Putting(Golf Training)",
    "Get past at least 7 stages in Picking Up Spares(Bowling Training)",
    "Get past at least 7 stages in Spin Control(Bowling Training)",
    "Get within 500 ft. in Hitting the Green(Golf Training)",
    "Give Up on any 3-hole Course in Golf",
    "Have the CPU commit an error in Baseball",
    "Hit at least 5 Home Runs In Hitting Home Runs(Baseball Training)",
    "Win a Best-of-3 Match in Tennis",
    "Win a Best-of-5 Match in Tennis",
    "Win a Match in Boxing",
    "Win a Match in Boxing while only using one hand(doesn’t matter which hand)",
    "Win a Match in Boxing without dodging(No Slow-Mo Punches)",
    "Win a Single Match in Tennis",
    "Win any match in Tennis without losing a single point",
    "Win any match with the blue courts(Hold 2 until courts show up)"
];
