bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "/love 10 critter for the achieve 'To all the squirels I've loved before'",
    "/love 5 critter for the achieve 'To all the squirels I've loved before'",
    "/love 5 critters for the achieve 'To all the squirrels I love despite their scars'",
    "/love 5 critters for the achieve 'To all the squirrels I once caressed'",
    "/love 5 critters for the achieve 'To all the squirrels I set sail to see'",
    "/love 5 critters for the achieve 'To all the squirrels through time and space'",
    "/love 5 critters for the achieve 'To all the squirrels who cared for me'",
    "/love 5 critters for the achieve 'To all the squirrels who've shared my life'",
    "/pet a cat",
    "/pet a dog",
    "/pet a named animal",
    "/pet a rabbit",
    "/wave at Anduin Wrynn",
    "/wave at Brann Bronzebeard",
    "/wave at Bwomsamdi",
    "/wave at Deathwing",
    "/wave at Garrosh Hellscream",
    "/wave at Guldan",
    "/wave at Harrison Jones",
    "/wave at Hemit Nesingwary",
    "/wave at Illidan Stormrage",
    "/wave at Jaina Proudmoore",
    "/wave at Khadgar",
    "/wave at Magni Bronzebeard",
    "/wave at Maiev Shadowsong",
    "/wave at Malfurion Stormrage",
    "/wave at Mankrik's wife",
    "/wave at Sylvanus",
    "/wave at Thrall",
    "/wave at Tirion Fordring",
    "/wave at a Teldrassil banker",
    "/wave at a Warlord of Draenor",
    "/wave at a dragon aspect",
    "/wave at an Undercity banker",
    "/wave at an enemy faction leader",
    "/wave at the Lich King",
    "Buy a green item",
    "Cast a fire spell",
    "Cast a frost spell",
    "Cast a healing spell",
    "Cast a holy spell",
    "Cast a lightning spell",
    "Cast a nature spell",
    "Cast a shadow spell",
    "Cast an arcane spell",
    "Change form",
    "Change your transmog",
    "Click a Broken Isles dungeon waystone",
    "Click a Broken Isles raid waystone",
    "Click a Draenor dungeon waystone",
    "Click a Draenor raid waystone",
    "Click a Kalimdor dungeon waystone",
    "Click a Kalimdor raid waystone",
    "Click a Kul Tiras dungeon waystone",
    "Click a Kul Tiras raid waystone",
    "Click a Northrend dungeon waystone",
    "Click a Northrend raid waystone",
    "Click a Pandaria dungeon waystone",
    "Click a Pandaria raid waystone",
    "Click a Zandalar dungeon waystone",
    "Click a Zandalar raid waystone",
    "Click an Eastern Kingdoms dungeon waystone",
    "Click an Eastern Kingdoms raid waystone",
    "Click an Outland dungeon waystone",
    "Click an Outland raid waystone",
    "Complete 10 quests",
    "Complete 20 quests",
    "Complete 30 quests",
    "Complete Exiles Reach",
    "Complete a daily (blue) quest",
    "Complete a world quest",
    "Complete a zone's quest line",
    "Complete an archeological artifact",
    "Complete the Death Knight starting area",
    "Complete the Demon Hunter starting area",
    "Complete the Draenor introduction scenario",
    "Complete the Legion introduction scenario",
    "Complete the goblin starting area",
    "Complete the worgen starting area",
    "Cook 10 different foods",
    "Cook 3 different foods",
    "Cook 5 different foods",
    "Craft 3 items",
    "Craft 5 items",
    "Craft an item",
    "Die to a dungeon boss",
    "Die to drowning",
    "Die to falling",
    "Die to fatigue",
    "Die to lava/fire",
    "Disenchant 3 items",
    "Disenchant 5 items",
    "Disenchant an item",
    "Dismiss a pet",
    "Drink 10 different drinks",
    "Drink 20 different drinks",
    "Drink 5 different drinks",
    "Drink a potion",
    "Drink water",
    "Eat 10 different foods",
    "Eat 20 different foods",
    "Eat 5 different foods",
    "Eat Bread",
    "Eat Dairy",
    "Eat Fish",
    "Eat Poultry",
    "Eat/drink conjured food/drink",
    "Enchant a weapon",
    "Enter 3 dungeons",
    "Enter 5 dungeons",
    "Enter a dungeon",
    "Enter stealth",
    "Equip 2 rings",
    "Equip a trinket",
    "Explore 1 zones fully",
    "Explore 3 zones fully",
    "Explore 5 zones fully",
    "Find 1 treasure",
    "Find 10 treasures",
    "Find 5 treasures",
    "Fish 3 up different fish",
    "Fish 5 up different fish",
    "Fish up 10 different fish",
    "Gather 10 different herbs",
    "Gather 3 different herbs",
    "Gather 5 different herbs",
    "Generate 100 rage",
    "Get a haircut",
    "Get a profession to level 10",
    "Get a profession to level 25",
    "Get a profession to level 50",
    "Get burnt",
    "Get cursed",
    "Get poisoned",
    "Get stabbed (and bleed)",
    "Have 3 buffs at once",
    "Have 5 buffs at once",
    "Have 7 buffs at once",
    "Have a reputation at honoured",
    "Heal an NPC",
    "Jump off Dalaran",
    "Jump off Mount Hyjal",
    "Jump off Outland",
    "Jump off Teldrassil",
    "Jump off Thunder Bluff and survive",
    "Jump off a cliff",
    "Jump off a tower",
    "Kill 100 creatures",
    "Kill 100 critters",
    "Kill 25 creatures",
    "Kill 25 critters",
    "Kill 50 creatures",
    "Kill 50 critters",
    "Kill a bat",
    "Kill a bear",
    "Kill a beast on each continent (except Shadowlands)",
    "Kill a bird",
    "Kill a clefthoof",
    "Kill a crab",
    "Kill a crocolisk",
    "Kill a demon",
    "Kill a dinosaur",
    "Kill a dragon",
    "Kill a dungeon boss",
    "Kill a dwarf",
    "Kill a ghost",
    "Kill a gnoll",
    "Kill a gnome",
    "Kill a gorilla",
    "Kill a human",
    "Kill a kobald",
    "Kill a mammoth",
    "Kill a murloc",
    "Kill a naga",
    "Kill a named npc",
    "Kill a quillboar",
    "Kill a rare (silver frame)",
    "Kill a robot",
    "Kill a scorpid",
    "Kill a skeleton",
    "Kill a snake",
    "Kill a spider",
    "Kill a troll",
    "Kill a vykrul",
    "Kill a wind serpent",
    "Kill a wolf",
    "Kill a yeti",
    "Kill an elemental",
    "Kill an elf",
    "Kill an elite (dragon frame)",
    "Kill an insect",
    "Kill an orc",
    "Kill an undead",
    "Learn 3 recipes",
    "Learn 5 recipes",
    "Learn a recipe",
    "Loot 10 different cloths",
    "Loot 3 different cloths",
    "Loot 5 different cloths",
    "Loot a blue item and equip it",
    "Loot a green item and equip it",
    "Loot a grey item and equip it",
    "Make a bandage",
    "Mine 10 different ores",
    "Mine 3 different ores",
    "Mine 5 different ores",
    "Obtain 1 gold",
    "Obtain 10 crafting materials",
    "Obtain 15 crafting materials",
    "Obtain 2 tabards",
    "Obtain 20 crafting materials",
    "Obtain 3 tabards",
    "Obtain 5 gold",
    "Obtain 50 silver",
    "Obtain a badge",
    "Obtain a bone",
    "Obtain a claw",
    "Obtain a key",
    "Obtain a letter",
    "Obtain a silly hat",
    "Obtain a skull",
    "Obtain a tooth",
    "Obtain a tusk",
    "Obtain a web",
    "Obtain an artifact weapon",
    "Obtain an elemental item",
    "Obtain an eye",
    "Obtain an item that starts a quest",
    "Obtain an offal",
    "Obtain oil",
    "Obtain resurrection sickness",
    "Obtain sludge/goo",
    "Obtain something black",
    "Obtain something blue",
    "Obtain something brown",
    "Obtain something green",
    "Obtain something grey",
    "Obtain something mechanical",
    "Obtain something orange",
    "Obtain something purple",
    "Obtain something red",
    "Obtain something white",
    "Obtain something wooden",
    "Obtain something yellow",
    "Put out a fire",
    "Reach level 15",
    "Reach level 20",
    "Read a book",
    "Revive yourself after dying",
    "Ride a boat",
    "Ride a train",
    "Ride a zeppelin",
    "Ride an elevator",
    "Ring a gong",
    "Run out of mana",
    "Say a prayer",
    "Sell a green item",
    "Sell an item to a vendor in a dungeon",
    "Set something on fire",
    "Shoot a gun/cannon",
    "Sit on a throne",
    "Skin 10 different leathers",
    "Skin 3 different leathers",
    "Skin 5 different leathers",
    "Slay 10 critters for the achieve 'Pest control'",
    "Slay 5 critters for the achieve 'Pest control'",
    "Summon a demon",
    "Summon a totem",
    "Survey a whole dig site",
    "Take a flight path",
    "Talk to an animal",
    "Tame an animal",
    "Use 15 unique portals",
    "Use 20 unique portals",
    "Use a controllable vehicle",
    "Use a mission table",
    "Use a shield",
    "Use a talented spell",
    "Use a trap",
    "Use your hearthstone",
    "Use your hearthstone 2 times",
    "Use your hearthstone 3 times",
    "Visit 10 flight paths",
    "Visit 10 innkeepers",
    "Visit 15 innkeepers",
    "Visit 20 flight paths",
    "Visit 20 innkeepers",
    "Visit 3 continents",
    "Visit 3 starting subzones",
    "Visit 4 capital cities",
    "Visit 5 continents",
    "Visit 5 flight paths",
    "Visit 5 innkeepers",
    "Visit 6 capital cities",
    "Visit 6 starting subzones",
    "Visit 7 continents",
    "Visit 8 capital cities",
    "Visit Blackrock mountain",
    "Visit Booty Bay",
    "Visit Fizzle & Pozzik's Speedbarge",
    "Visit Gallywix's Pleasure Palace",
    "Visit Icecrown Citadel",
    "Visit Ironforge Airport",
    "Visit Karazahn",
    "Visit Silvermoon City",
    "Visit Strathholme",
    "Visit Wyrmrest Temple",
    "Visit a battleground portal",
    "Visit a class order hall",
    "Visit a dome",
    "Visit a graveyard",
    "Visit a lake",
    "Visit a library",
    "Visit a necropolis/ziggurat",
    "Visit a pyramid",
    "Visit a temple",
    "Visit a worldtree",
    "Visit an arena",
    "Visit an isle",
    "Visit an obelisk",
    "Visit somewhere sandy",
    "Visit somewhere snowy",
    "Visit somewhere underground",
    "Visit somewhere underwater",
    "Visit somewhere windy",
    "Visit the Argent Tournament",
    "Visit the Black Temple",
    "Visit the Blackrock Foundry",
    "Visit the Exodaar",
    "Visit the Gates of Valour",
    "Visit the Gilneas",
    "Visit the Goldshire Inn",
    "Visit the Great Wall of Pandaria",
    "Visit the Loch",
    "Visit the Maelstrom",
    "Visit the big sword in silithus",
    "Visit the bottom of the ocean in Vashjir",
    "Visit the past (other than using the dark portal/chromie time)",
    "Visit the top of Kun Lai summit",
    "Walk through the dark portal",
    "Wield 2 weapons"
];
