bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "/love 10 critter for the achieve 'To all the squirels I've loved before'",
    "/love 5 critter for the achieve 'To all the squirels I've loved before'",
    "/love 5 critters for the achieve 'To all the squirrels I love despite their scars'",
    "/love 5 critters for the achieve 'To all the squirrels I once caressed'",
    "/love 5 critters for the achieve 'To all the squirrels I set sail to see'",
    "/love 5 critters for the achieve 'To all the squirrels through time and space'",
    "/love 5 critters for the achieve 'To all the squirrels who cared for me'",
    "/love 5 critters for the achieve 'To all the squirrels who've shared my life'",
    "/pet a cat",
    "/pet a dog",
    "/pet a named animal",
    "/pet a rabbit",
    "/wave at Anduin Wrynn",
    "/wave at Brann Bronzebeard",
    "/wave at Bwomsamdi",
    "/wave at Deathwing",
    "/wave at Garrosh Hellscream",
    "/wave at Guldan",
    "/wave at Harrison Jones",
    "/wave at Hemit Nesingwary",
    "/wave at Illidan Stormrage",
    "/wave at Jaina Proudmoore",
    "/wave at Khadgar",
    "/wave at Magni Bronzebeard",
    "/wave at Maiev Shadowsong",
    "/wave at Malfurion Stormrage",
    "/wave at Mankrik's wife",
    "/wave at Nat Pagle",
    "/wave at Sylvanus",
    "/wave at Thrall",
    "/wave at Tirion Fordring",
    "/wave at a Teldrassil banker",
    "/wave at a Warlord of Draenor",
    "/wave at a dragon aspect",
    "/wave at an Undercity banker",
    "/wave at an enemy faction leader",
    "/wave at the Lich King",
    "Buy a blue quality item",
    "Buy a green quality item",
    "Buy a purple quality item",
    "Cast 10 unique spells",
    "Cast 20 unique spells",
    "Cast 30 unique spells",
    "Cast a fire spell",
    "Cast a frost spell",
    "Cast a healing spell",
    "Cast a holy spell",
    "Cast a lightning spell",
    "Cast a nature spell",
    "Cast a shadow spell",
    "Cast a teleport",
    "Cast an arcane spell",
    "Change form",
    "Change your transmog",
    "Click a Broken Isles dungeon waystone",
    "Click a Broken Isles raid waystone",
    "Click a Draenor dungeon waystone",
    "Click a Draenor raid waystone",
    "Click a Kalimdor dungeon waystone",
    "Click a Kalimdor raid waystone",
    "Click a Kul Tiras dungeon waystone",
    "Click a Kul Tiras raid waystone",
    "Click a Northrend dungeon waystone",
    "Click a Northrend raid waystone",
    "Click a Pandaria dungeon waystone",
    "Click a Pandaria raid waystone",
    "Click a Zandalar dungeon waystone",
    "Click a Zandalar raid waystone",
    "Click an Eastern Kingdoms dungeon waystone",
    "Click an Eastern Kingdoms raid waystone",
    "Click an Outland dungeon waystone",
    "Click an Outland raid waystone",
    "Climb to the top of a mountain",
    "Close a portal",
    "Complete 10 quests",
    "Complete 20 quests",
    "Complete 30 quests",
    "Complete Exiles Reach",
    "Complete a daily (blue) quest",
    "Complete a quest in 2 different continents",
    "Complete a quest in 3 different continents",
    "Complete a quest in 4 different zones",
    "Complete a quest in 6 different zones",
    "Complete a quest that requires killing 10 or more mobs",
    "Complete a quest that requires killing only 1 mob",
    "Complete a world quest",
    "Complete an achievement worth 20 points or more",
    "Complete an archeological artifact",
    "Complete the Death Knight starting area",
    "Complete the Demon Hunter starting area",
    "Complete the Draenor introduction scenario",
    "Complete the Legion introduction scenario",
    "Complete the goblin starting area",
    "Complete the pandaren starting area",
    "Complete the worgen starting area",
    "Cook 10 different foods",
    "Cook 3 different foods",
    "Cook 5 different foods",
    "Craft 3 items",
    "Craft 5 items",
    "Craft a blue quality item",
    "Craft a green quality item",
    "Craft an item",
    "Die to a dungeon boss",
    "Die to a rare mob",
    "Die to drowning",
    "Die to falling",
    "Die to fatigue",
    "Die to lava/fire",
    "Disenchant 3 items",
    "Disenchant 5 items",
    "Disenchant an item",
    "Dismiss a pet",
    "Drink 10 different drinks",
    "Drink 20 different drinks",
    "Drink 5 different drinks",
    "Drink a potion",
    "Drink water",
    "Eat 10 different foods",
    "Eat 20 different foods",
    "Eat 5 different foods",
    "Eat Bread",
    "Eat Dairy",
    "Eat Fish",
    "Eat Poultry",
    "Eat/drink conjured food/drink",
    "Enchant a neck/ring",
    "Enchant a piece of armour",
    "Enchant a weapon",
    "Enter 3 dungeons",
    "Enter 5 dungeons",
    "Enter a dungeon",
    "Enter stealth",
    "Equip 2 bags",
    "Equip 2 rings",
    "Equip 3 bags",
    "Equip 4 bags",
    "Equip a 12 slot bag",
    "Equip a profession bag",
    "Equip a trinket",
    "Equip an item in every gear slot",
    "Explore 1 zones fully",
    "Explore 3 zones fully",
    "Explore 5 zones fully",
    "Find 1 treasure",
    "Find 10 treasures",
    "Find 5 treasures",
    "Fish 3 up different fish",
    "Fish 5 up different fish",
    "Fish up 10 different fish",
    "Gather 10 different herbs",
    "Gather 3 different herbs",
    "Gather 5 different herbs",
    "Generate 100 rage",
    "Get 2 professions to level 10",
    "Get 2 professions to level 20",
    "Get 2 professions to level 30",
    "Get 3 professions to level 25 at once",
    "Get 4 professions to level 20 at once",
    "Get 5 professions to level 15 at once",
    "Get 6 professions to level 10 at once",
    "Get a haircut",
    "Get a profession to level 10",
    "Get a profession to level 25",
    "Get a profession to level 50",
    "Get a reputation to honoured",
    "Get burnt",
    "Get cursed",
    "Get dazed",
    "Get poisoned",
    "Get stabbed (and bleed)",
    "Have 1000 health",
    "Have 15 items in your inventory",
    "Have 3 buffs at once",
    "Have 30 items in your inventory",
    "Have 5 buffs at once",
    "Have 500 health",
    "Have 7 buffs at once",
    "Heal an NPC",
    "Jump off Dalaran and survive",
    "Jump off Mount Hyjal",
    "Jump off Outland",
    "Jump off Teldrassil",
    "Jump off Thunder Bluff and survive",
    "Jump off a cliff into the ocean",
    "Jump off a tower",
    "Kill 100 creatures",
    "Kill 100 critters",
    "Kill 2 creatures with one spell",
    "Kill 25 creatures",
    "Kill 25 critters",
    "Kill 50 creatures",
    "Kill 50 critters",
    "Kill a bat",
    "Kill a bear",
    "Kill a beast on each continent (except Shadowlands)",
    "Kill a bird",
    "Kill a clefthoof",
    "Kill a crab",
    "Kill a crocolisk",
    "Kill a demon",
    "Kill a dinosaur",
    "Kill a dragon",
    "Kill a dungeon boss",
    "Kill a dwarf",
    "Kill a ghost",
    "Kill a gnoll",
    "Kill a gnome",
    "Kill a gorilla",
    "Kill a harpy",
    "Kill a human",
    "Kill a kobald",
    "Kill a mammoth",
    "Kill a mech",
    "Kill a murloc",
    "Kill a naga",
    "Kill a named npc",
    "Kill a quest boss mob (exclamation frame)",
    "Kill a quillboar",
    "Kill a rare (silver frame)",
    "Kill a robot",
    "Kill a scorpid",
    "Kill a skeleton",
    "Kill a snake",
    "Kill a spawned quest mob",
    "Kill a spider",
    "Kill a spirit beast",
    "Kill a troll",
    "Kill a turtle",
    "Kill a vykrul",
    "Kill a wind serpent",
    "Kill a wolf",
    "Kill a yeti",
    "Kill an elemental",
    "Kill an elf",
    "Kill an elite (dragon frame)",
    "Kill an enemy faction npc",
    "Kill an insect",
    "Kill an ogre",
    "Kill an orc",
    "Kill an undead",
    "Learn 10 recipes",
    "Learn 3 recipe",
    "Learn 5 recipes",
    "Loot 10 different cloths",
    "Loot 3 different cloths",
    "Loot 5 different cloths",
    "Loot a blue item and equip it",
    "Loot a green item and equip it",
    "Loot a grey item and equip it",
    "Loot a white item and equip it",
    "Make 3 different bandages",
    "Make 3 different inks",
    "Make a bandage",
    "Mine 10 different ores",
    "Mine 3 different ores",
    "Mine 5 different ores",
    "Obtain 1 gold",
    "Obtain 10 crafting materials",
    "Obtain 15 crafting materials",
    "Obtain 2 tabards",
    "Obtain 20 crafting materials",
    "Obtain 3 tabards",
    "Obtain 5 gold",
    "Obtain 50 silver",
    "Obtain a badge",
    "Obtain a bone",
    "Obtain a claw",
    "Obtain a key",
    "Obtain a letter",
    "Obtain a silly hat",
    "Obtain a skull",
    "Obtain a tooth",
    "Obtain a toy",
    "Obtain a tusk",
    "Obtain a web",
    "Obtain all the artifact weapons for your class",
    "Obtain an artifact weapon",
    "Obtain an elemental item",
    "Obtain an eye",
    "Obtain an item that starts a quest",
    "Obtain an offal",
    "Obtain oil",
    "Obtain resurrection sickness",
    "Obtain sludge/goo",
    "Obtain something black",
    "Obtain something blue",
    "Obtain something brown",
    "Obtain something green",
    "Obtain something grey",
    "Obtain something mechanical",
    "Obtain something orange",
    "Obtain something purple",
    "Obtain something red",
    "Obtain something white",
    "Obtain something wooden",
    "Obtain something yellow",
    "Obtain the Heart of Azeroth",
    "Put out a fire",
    "Reach level 10",
    "Reach level 15",
    "Reach level 20",
    "Read a book",
    "Revive yourself after dying",
    "Ride a boat",
    "Ride a train",
    "Ride a zeppelin",
    "Ride an elevator",
    "Ring a gong",
    "Run out of mana",
    "Say a prayer",
    "Sell a blue quality item",
    "Sell a green quality item",
    "Sell an item to a vendor in a dungeon",
    "Sell an item to an honour vendor",
    "Set something on fire",
    "Set your hearthsone with a Blood Elf/Draenai",
    "Set your hearthsone with a Troll/Gnome",
    "Set your hearthsone with an Orc/Dwarf",
    "Set your hearthstone with a Goblin/Worgen",
    "Set your hearthstone with a Tauren/Night Elf",
    "Set your hearthstone with an Undead/Human",
    "Shoot a gun/cannon",
    "Sit on a bench",
    "Sit on a throne",
    "Skin 10 different leathers",
    "Skin 3 different leathers",
    "Skin 5 different leathers",
    "Slay 10 critters for the achieve 'Pest control'",
    "Slay 5 critters for the achieve 'Pest control'",
    "Summon a demon",
    "Summon a totem",
    "Survey a whole dig site",
    "Take a flight path",
    "Take a selfie on a beach in Vashjir",
    "Take a selfie while wearing at least 4 distinct colours",
    "Take a selfie with 10 of the same animal",
    "Take a selfie with 6 different animals in it",
    "Take a selfie with Johnny Awesome",
    "Take a selfie with a Dreadlord",
    "Take a selfie with a Loa",
    "Take a selfie with a Titan/Keeper",
    "Take a selfie with a Warden",
    "Take a selfie with a leader of a different class",
    "Take a selfie with a leader of your class",
    "Take a selfie with a raid boss character",
    "Take a selfie with an NPC on a horse",
    "Take a selfie with an Old God (or their raid)",
    "Talk to an animal",
    "Tame an animal",
    "Unlock 3 linked flight paths",
    "Unlock 5 linked flight paths",
    "Unlock all the extra bank slots",
    "Unlock an extra bank slot",
    "Use 10 unique portals",
    "Use 15 unique portals",
    "Use 20 unique portals",
    "Use a controllable vehicle",
    "Use a mission table",
    "Use a shield",
    "Use a talented spell",
    "Use a trap",
    "Use your hearthstone",
    "Use your hearthstone 2 times",
    "Use your hearthstone 3 times",
    "Visit 10 flight paths",
    "Visit 10 innkeepers",
    "Visit 15 innkeepers",
    "Visit 20 flight paths",
    "Visit 20 innkeepers",
    "Visit 3 continents",
    "Visit 3 starting subzones",
    "Visit 4 capital cities",
    "Visit 5 continents",
    "Visit 5 flight paths",
    "Visit 5 innkeepers",
    "Visit 6 capital cities",
    "Visit 6 starting subzones",
    "Visit 7 continents",
    "Visit 8 capital cities",
    "Visit Blackrock mountain",
    "Visit Booty Bay",
    "Visit Fizzle & Pozzik's Speedbarge",
    "Visit Gallywix's Pleasure Palace",
    "Visit Icecrown Citadel",
    "Visit Ironforge Airport",
    "Visit Karazahn",
    "Visit Silvermoon City",
    "Visit Strathholme",
    "Visit Wyrmrest Temple",
    "Visit a battleground portal",
    "Visit a class order hall",
    "Visit a dome",
    "Visit a graveyard",
    "Visit a lake",
    "Visit a library",
    "Visit a necropolis/ziggurat",
    "Visit a pyramid",
    "Visit a temple",
    "Visit a worldtree",
    "Visit an arena",
    "Visit an isle",
    "Visit an obelisk",
    "Visit somewhere sandy",
    "Visit somewhere snowy",
    "Visit somewhere underground",
    "Visit somewhere underwater",
    "Visit somewhere windy",
    "Visit the Argent Tournament",
    "Visit the Black Temple",
    "Visit the Blackrock Foundry",
    "Visit the Exodaar",
    "Visit the Gates of Valour",
    "Visit the Gilneas",
    "Visit the Goldshire Inn",
    "Visit the Great Wall of Pandaria",
    "Visit the Loch",
    "Visit the Maelstrom",
    "Visit the big sword in Silithus",
    "Visit the bottom of the ocean in Vashjir",
    "Visit the past (other than using the dark portal/chromie time)",
    "Visit the top of Kun Lai summit",
    "Walk through the dark portal",
    "Wield 2 weapons",
    "Write a book"
];
