bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList =
[
    "Click the meeting stone of a Burning Crusade Dungeon",
    "Click the meeting stone of a Burning Crusade Raid",
    "Click the meeting stone of a Classic Dungeon",
    "Click the meeting stone of a Classic Raid",
    "Click the meeting stone of a WotLK Dungeon",
    "Click the meeting stone of a WotLK Raid",
    "Click the meeting stone of a MoP Dungeon",
    "Click the meeting stone of a MoP Raid",
    "Click the meeting stone of a WoD Dungeon",
    "Click the meeting stone of a WoD Raid",
    "Click the meeting stone of a Legion Dungeon",
    "Click the meeting stone of a Legion Raid",
    "Click the meeting stone of a BfA Dungeon",
    "Click the meeting stone of a BfA Raid",
    "Die in a capital city of the opposing faction",
    "Die from lava or fire",
    "Visit the past in a way other than going to Draenor / Blasted Lands",
    "Loot and equip a piece of Grey quality gear",
    "Take a boat or zep",
    "Ride the deeprum tram from one side to the other",
    "Visit the Ironforge Airport",
    "Enter a controllable vehicle",
    "Kill a boss with a chance to drop a mount",
    "Get teleported out of another classes Order Hall",
    "Open a dialogue box with Thrall",
    "Get kicked out of flying 2 person mount",
    "Ring a gong",
    "Gather the materials and cook a meat dish",
    "Die to fatigue",
    "Complete a repeatable (blue !) quest",
    "Survive a jump off Thunder Bluff",
    "Lay down on a bed in the Lions Pride Inn",
    "Kill an elite ghost",
    "Kill an elite murloc",
    "Kill an elite dragonkin",
    "Kill an elite spider",
    "Get Drunk",
    "Walk through the Dark Portal",
    "Kneel before your faction's current leader",
    "Obtain Ressurection Sickness",
    "Take a portal to Ancient Dalaran / Dalaran Crater",
    "/wave an undercity banker",
    "/wave a darnassus banker",
    "Sell an item to a vendor within a raid instance",
    "/wave an opposing faction leader",
    "Loot a rare quality item",
    "Defeat Hogger",
    "Get a haircut",
    "Drink 3 different potions",
    "Enter 3 dungeons",
    "Loot meat from 5 different species",
    "Ride an elevator",
    "Talk to 5 innkeepers",
    "Talk to 10 innkeepers",
    "Visit 3 capital cities",
    "Catch a fish",
    "Die by drowning",
    "Read a book",
    "Kill 20 dungeon bosses",
    "Visit all capital cities (Faction specific ones?)",
    "Loot 7 different types of cloth",
    "Kill a beast from each contenient",
    "Speak to Khadgar until he pisses himself",
    "Blow open 2 doors (Zul'Farrak, Blackrock Depths, Deadmines, etc.)",
    "Beat a dungeon in reverse order",
    "Use a flight path",
    "Buy from 3 different dungeon vendors",
    "Speak to Franclorn Forgewright.",
    "\"/love 3 different squirrels\"",
    "Kill an elite skeleton",
    "Jump off the sword in silithus",
    "send a letter",
    "jump off dalaran and die"
];
