bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList =
[
    "Win a pet battle",    
    "Complete a \"kill X mob\" quest",        
    "Complete a quest which just requires you to talk to another npc",        
    "Complete a quest which requires you to go to another continent",        
    "Click the meeting stone of a Burning Crusade Dungeon",        
    "Click the meeting stone of a Burning Crusade Raid",        
    "Click the meeting stone of a Classic Dungeon",        
    "Click the meeting stone of a Classic Raid",        
    "Click the meeting stone of a WotLK Dungeon",        
    "Click the meeting stone of a WotLK Raid",        
    "Click the meeting stone of a MoP Dungeon",        
    "Click the meeting stone of a MoP Raid",        
    "Click the meeting stone of a WoD Dungeon",        
    "Click the meeting stone of a WoD Raid",        
    "Click the meeting stone of a Legion Dungeon",        
    "Click the meeting stone of a Legion Raid",        
    "Click the meeting stone of a BfA Dungeon",        
    "Click the meeting stone of a BfA Raid",        
    "Complete a single boss raid",        
    "Die in a capital city of the opposing faction",        
    "Die from lava or fire",        
    "Visit the past in a way other than going to Draenor / Blasted Lands",        
    "Play through a class trial's intro",        
    "Tip a mage you've never met for a portal (you must take it)",        
    "Loot and equip a piece of Grey quality gear",        
    "Control Razorgore in BWL",        
    "Take a boat or zep",        
    "Ride the deeprum tram from one side to the other",        
    "Visit the Ironforge Airport",        
    "Enter a controllable vehicle",        
    "Kill a boss with a chance to drop a mount",        
    "Kill a player of the opposing faction",        
    "Get teleported out of another classes Order Hall",        
    "Loot and equip a new appearance for your character",        
    "Open a dialogue box with Thrall",        
    "Assist in killing a character with a bounty",        
    "Get kicked out of flying 2 person mount",        
    "Ring a gong",        
    "Gather the materials and cook a meat dish",        
    "Kill a flag carrier in Warsong Gultch",        
    "Capture an objective in Arathi Basin",        
    "Open a non-weekly treasure chest ",        
    "Die to fatigue",        
    "Win a duel",        
    "Accept a summon",        
    "Gain the \"Well Fed\" buff from another player's feast",        
    "Arcane Intellect, Power Word: Fortitude, and Battle Shout active at the same time",        
    "Receive Blessing of Kings from a paladin",        
    "Complete a World Quest",        
    "Complete a repeatable (blue !) quest",        
    "Survive a jump off Thunder Bluff",        
    "Lay down on a bed in the Lions Pride Inn",        
    "Visit the Scholomance Alchemy Lab",        
    "Kill an elite ghost",        
    "Kill an elite murloc",        
    "Kill an elite dragonkin",        
    "Kill an elite spider",        
    "Get Drunk",        
    "Walk through the Dark Portal",        
    "RP a panhandler using only /s until you are given exactly 10 silver",        
    "Kill a current raid boss on any difficulty",        
    "Kneel before your faction's current leader",        
    "Obtain Ressurection Sickness",        
    "Accept a ressurection",        
    "Use a soulstone that was placed on you by another player",        
    "Get Polymorphed into anything other than a sheep",        
    "Take a portal to Ancient Dalaran",        
    "/wave an undercity banker",        
    "/wave a darnassus banker",        
    "Sell an item to a vendor within a raid instance",        
    "Win an Arena Skirmish",        
    "/wave an opposing faction leader",        
    "/hug a druid in cat form",        
    "/pet a hunter's pet"
]