bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Activate 20 Scarabs",
    "Activate 6 Jewel Bumpers",
    "Activate All 4 Temple Storyboards",
    "Activate Ape and Orestation Totem",
    "Activate Crystal Deep Beeline",
    "Activate Dolphin and Sin Totem",
    "Activate Gorilla Woods Beeline",
    "Activate Ivory Peaks Beeline",
    "Activate Marrow Hill Beeline",
    "Activate Spina and Screetch Totem",
    "Activate Village and Ivory Peak Totem",
    "Activate any 3 Beelines",
    "Activate any 3 Totems",
    "Bathe the 6 Sootlings",
    "Blow 2 Horns",
    "Bring back the Glowmoths",
    "Bring back the surviving Egg",
    "Check 5 Telescopes",
    "Close Ore Station Hatches",
    "Complete Statue Puzzle",
    "Complete the Juicer",
    "Defeat Kickback",
    "Deliver the Blue Package",
    "Deliver the Green Package",
    "Deliver the Purple Package",
    "Deliver to 20 Mailboxes",
    "Fall into Thorns 30 Times",
    "Feed Fosfor Juicy Cove Mushroom",
    "Feed Fosfor Poison Toadstool",
    "Fill a Bucket",
    "Forgive Kickback",
    "Free the Info Person",
    "Get 3 Trackers",
    "Get 5 Wallet Upgrades",
    "Get Bling Sprinkles (Yellow)",
    "Get Boon of Plenty!",
    "Get Ceremony Instruments",
    "Get Creepy Sprinkles (Green)",
    "Get Crimson Sprinkles (Red)",
    "Get Crystal Deep Tracker",
    "Get Deadly Sprinkles (Black)",
    "Get Dive Fish",
    "Get Fast Dive Fish",
    "Get Fat Skvader",
    "Get Fleek Heart Fruit",
    "Get Gorilla Woods Tracker",
    "Get Grand Postmaster Badge",
    "Get Ivory Peaks Tracker",
    "Get Kickback",
    "Get Marrow Hill Tracker",
    "Get Noisemaker",
    "Get Ocean Heart Fruit",
    "Get Scarab Tracker",
    "Get Slug Vacuum",
    "Get Slug Vacuum Deluxe",
    "Get Sush back to work (Hideout)",
    "Get Sweet Sprinkles (Violet)",
    "Get Treasure Map",
    "Get a Skvader",
    "Get the Sootling-on-a-Leash",
    "Have 450 Fruits on hand",
    "Open 10 Chests",
    "Open Blue Chest",
    "Open Door to the Underbelly",
    "Open Green Chest",
    "Open Screetch Door",
    "Pay 100 Fruit to Skeeper",
    "Plant 3 Spores",
    "Repair Smashed Statue Pieces",
    "Repair the Bridge",
    "Roll 5 Boulders / Snowballs",
    "Save Chief Boon",
    "Save Chief Sal",
    "Save Chief Spina",
    "Saves 4 Traitors Spirits",
    "Saves the 8 Tadpoles",
    "Scare a Bat",
    "Take Spider Orphan to Tree",
    "Wake up Baldino"
];
