bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Activate 20 Scarabs",
    "Activate 6 Fruit Pinwheels",
    "Activate 6 Jewel Bumpers",
    "Activate Ape and Orestation Totems",
    "Activate Dolphin and Sin Totems",
    "Activate Spina and Screetch Totems",
    "Activate Village and Ivory Peak Totems",
    "Activate all 4 Temple Storyboards",
    "Activate any 3 Beelines",
    "Activate any 3 Totems",
    "Activate the Crystal Deep Beeline",
    "Activate the Gorilla Woods Beeline",
    "Activate the Horned Statue",
    "Activate the Ivory Peaks Beeline",
    "Activate the Marrow Hill Beeline",
    "Bathe 2 Sootlings for Tunguska",
    "Blow 2 Horns",
    "Blow up a Slug in the Tower",
    "Bring 3 Tadpoles to Myrtle",
    "Bring back the Surviving Egg",
    "Close the Orestation Hatches",
    "Collect 25 Fruit in the Waterfall Pit",
    "Collect the Bling Sprinkles (Gold)",
    "Collect the Ceremony Instruments",
    "Collect the Creepy Sprinkles (Green)",
    "Collect the Crimson Sprinkles (Red)",
    "Collect the Deadly Sprinkles (Black)",
    "Collect the Fleek Fruit Heart",
    "Collect the Ocean Fruit Heart",
    "Collect the Sweet Sprinkles (Violet)",
    "Come Across all 4 Map Areas",
    "Complete Umbaba's Puzzle",
    "Complete the Juicery",
    "Defeat Kickback",
    "Defeat the Screech",
    "Deliver Mail to 20 Mailboxes",
    "Deliver Quinbe's Package",
    "Deliver Sin's Package",
    "Deliver Treek's Package",
    "Destroy Crystals in 3 of 4 Map Areas",
    "Destroy Fosfor's Secret Fruit Supply",
    "Destroy the Crystal at Tower's Peak",
    "Destroy the Crystals above The Dolphin",
    "Enter 5 Hidden Tunnels",
    "Equip the Ruby-Ball-Look",
    "Fall into Thorns 30 Times",
    "Fall off 4 Cliffs for 2s Airtime",
    "Fill a Bucket with Water",
    "Find 3 Main Items",
    "Find Piles of Gold in 2 Locations",
    "Forgive Kickback",
    "Free Ojva from the Ice",
    "Get Access to the Underdark Ruins",
    "Get Sush back to Work",
    "Gift Fosfor the Juicy Cove Mushroom",
    "Give Fosfor the Poison Toadstool",
    "Have 350 Fruits on hand once",
    "Help Cleepers with his Sootling Fear",
    "Hit the Owl in the Orestation",
    "Jump across the Lava Pool",
    "Look through 5 Telescopes",
    "Make Friends with Kickback",
    "Make the Glowmoths hatch",
    "Obtain 7 Wallet Upgrades",
    "Obtain any 3 Trackers",
    "Obtain the Boon of Plenty",
    "Obtain the Crystal Deep Tracker",
    "Obtain the Dive Fish",
    "Obtain the Gorilla Woods Tracker",
    "Obtain the Grand Postmaster Badge",
    "Obtain the Ivory Peaks Tracker",
    "Obtain the Mail Bag",
    "Obtain the Marrow Hill Tracker",
    "Obtain the Noisemaker",
    "Obtain the Scarab Tracker",
    "Obtain the Skvader",
    "Obtain the Slug Vacuum",
    "Obtain the Sootling on a Leash",
    "Obtain the Treasure Map",
    "Open 10 Chests",
    "Open 3 Doors/Hatches in Marrow Hill",
    "Open 4 Shortcut Poles",
    "Open 5 Doors/Hatches in Ivory Peaks",
    "Open 6 Doors/Hatches in the Gorilla Woods",
    "Open 8 Doors/Hatches in the Underdark",
    "Open all 4 Doors in the Slug Gardens",
    "Open the Blue Chest",
    "Open the Green Chest",
    "Open the Screech Door",
    "Open the Underbelly Door",
    "Pay Skeeper 100 Fruits",
    "Plant 3 Spores",
    "Reach the East Coast",
    "Read 8 Signs",
    "Release Obtainium in 2 Places",
    "Release Pressure in the Underbelly",
    "Repair Sandro's Bridge",
    "Repair the Smashed Statue Pieces",
    "Ride 15 Metal Rails",
    "Roll 5 Boulders or Snowballs",
    "Save 2 Traitor Spirits",
    "Scare a Bat",
    "Spin Blue Pinwheels in 2 Locations",
    "Start the Rocket of the Space Monks",
    "Take the Spider Orphan to the Tree",
    "Talk to Slug Gardener, Nabinabi, Krimm, Chirp",
    "Talk to Sweepers, Dolphin, Plissken, Kambi",
    "Talk to Zo, Rolypoly, Leeper, Ithaqua",
    "Trade with Liquorice",
    "Trade with Splank",
    "Trade with Sumoe",
    "Upgrade to Fast Dive Fish",
    "Upgrade to Slug Vacuum Deluxe",
    "Upgrade to the Fat Skvader",
    "Use 2 Keys",
    "Wake up Baldino"
];
