bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Activate 20 Scarabs",
    "Activate 6 Jewel Bumpers",
    "Activate Ape and Orestation Totems",
    "Activate Dolphin and Sin Totems",
    "Activate Spina and Screetch Totems",
    "Activate Village and Ivory Peak Totems",
    "Activate all 4 Temple Storyboards",
    "Activate any 3 Beelines",
    "Activate any 3 Totems",
    "Activate the Crystal Deep Beeline",
    "Activate the Gorilla Woods Beeline",
    "Activate the Ivory Peaks Beeline",
    "Activate the Marrow Hill Beeline",
    "Bathe 2 Sootlings for Tunguska",
    "Blow 2 Horns",
    "Bring 3 Tadoles to Myrtle",
    "Bring back the Surviving Egg",
    "Close the Ore Station Hatches",
    "Collect the Bling Sprinkles (Gold)",
    "Collect the Ceremony Instruments",
    "Collect the Creepy Sprinkles (Green)",
    "Collect the Crimson Sprinkles (Red)",
    "Collect the Deadly Sprinkles (Black)",
    "Collect the Sweet Sprinkles (Violet)",
    "Collect the Treasure Map",
    "Collect the entire Fleek Fruit Heart",
    "Collect the entire Ocean Fruit Heart",
    "Complete Umbaba's Puzzle",
    "Complete the Juicer",
    "Defeat Kickback",
    "Defeat the Screech",
    "Deliver Mail to 20 Mailboxes",
    "Deliver Quinbe's Package",
    "Deliver Sin's Package",
    "Deliver Treek's Package",
    "Destroy Fosfor's Secret Fruit Supply",
    "Destroy the Crystal at Tower's Peak",
    "Equip the Ruby-Ball-Look",
    "Fall Off 4 Cliffs for 2s Airtime",
    "Fall into Thorns 30 times",
    "Fill a Bucket with Water",
    "Find Piles of Gold in 2 Locations",
    "Forgive Kickback",
    "Free Ojva from the Ice",
    "Get Access to the Underdark Ruins",
    "Get Sush back to work",
    "Gift Fosfor the Juicy Cove Mushroom",
    "Give Fosfor the Poison Toadstool",
    "Give Skeeper 100 Fruits",
    "Go through 5 Hidden Tunnels",
    "Have 450 Fruits on hand once",
    "Help Cleepers with his Sootling Fear",
    "Hit the Owl in the Ore Station",
    "Jump across the Lava Pool",
    "Look through 5 Telescopes",
    "Make Friends with Kickback",
    "Make the Glowmoths hatch",
    "Obtain 5 Wallet Upgrades",
    "Obtain Boon of Plenty",
    "Obtain any 3 Trackers",
    "Obtain the Crystal Deep Tracker",
    "Obtain the Dive Fish",
    "Obtain the Gorilla Woods Tracker",
    "Obtain the Grand Postmaster Badge",
    "Obtain the Ivory Peaks Tracker",
    "Obtain the Mail Bag",
    "Obtain the Marrow Hill Tracker",
    "Obtain the Noisemaker",
    "Obtain the Scarab Tracker",
    "Obtain the Skvader",
    "Obtain the Slug Vacuum",
    "Obtain the Sootling on a Leash",
    "Open 10 Chests",
    "Open 4 Shortcuts Poles",
    "Open all 4 Doors in the Slug Gardens",
    "Open the Blue Chest",
    "Open the Door ahead of the Screech",
    "Open the Door to the Underbelly",
    "Open the Green Chest",
    "Plant 3 Spores",
    "Release Pressure in the Underbelly",
    "Repair Sandro's Bridge",
    "Repair the Smashed Statue Pieces",
    "Roll 5 Boulders or Snowballs",
    "Save all 4 Traitor Spirits",
    "Scare a Bat",
    "Spin Blue Pinwheels in 2 Locations",
    "Start the Rocket of the Space Monks",
    "Take the Spider Orphan to the Tree",
    "Trade with Liquorice",
    "Trade with Splank",
    "Trade with Sumoe",
    "Upgrade the Skvader to Fat Skvader",
    "Upgrade to Fast Dive Fish",
    "Upgrade to Slug Vacuum Deluxe",
    "Wake up Baldino"
];
