bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Activate 20 Scarabs",
    "Activate 6 Fruit Pinwheels",
    "Activate 6 Jewel Bumpers",
    "Activate Ape and Orestation Totems",
    "Activate Dolphin and Sin Totems",
    "Activate Spina and Screetch Totems",
    "Activate Village and Ivory Peak Totems",
    "Activate all 4 Temple Storyboards",
    "Activate any 3 Beelines",
    "Activate any 3 Totems",
    "Activate the Crystal Deep Beeline",
    "Activate the Gorilla Woods Beeline",
    "Activate the Horned Statue",
    "Activate the Ivory Peaks Beeline",
    "Activate the Marrow Hill Beeline",
    "Bathe the 6 Sootlings for Tunguska",
    "Blow 2 Horns",
    "Blow up a Slug in the Tower",
    "Bring Back the Surviving Egg",
    "Bring the 8 Tadpoles to Myrtle",
    "Close the Orestation Hatches",
    "Collect 25 Fruit in the Waterfall Pit",
    "Collect the Bling Sprinkles (Gold)",
    "Collect the Creepy Sprinkles (Green)",
    "Collect the Crimson Sprinkles (Red)",
    "Collect the Deadly Sprinkles (Black)",
    "Collect the Fleek Fruit Heart",
    "Collect the Ocean Fruit Heart",
    "Collect the Skvader",
    "Collect the Sweet Sprinkles (Violet)",
    "Collect the Treasure Map",
    "Come Across all 4 Map Areas",
    "Complete the Juicery",
    "Defeat Kickback",
    "Defeat the Screech",
    "Deliver Mail to 20 Mailboxes",
    "Deliver Quinbe's Package",
    "Deliver Sin's Package",
    "Deliver Treek's Package",
    "Destroy Crystals in 3 of 4 Map Areas",
    "Destroy the Crystal at Tower's Peak",
    "Destroy the Crystals above The Dolphin",
    "Enter 5 Hidden Tunnels",
    "Equip the Ruby-Ball-Look",
    "Fall into Thorns 30 Times",
    "Fall off 4 Cliffs for 2s Airtime",
    "Fill a Bucket with Water",
    "Find 4 Main Items",
    "Find Piles of Gold in 2 Locations",
    "Forgive Kickback",
    "Free Ojva from the Ice",
    "Get Access to the Underdark Ruins",
    "Get Sush back to Work",
    "Give Fosfor Both Mushrooms",
    "Have 350 Fruits on hand once",
    "Help Cleepers with his Sootling Fear",
    "Hit the Owl in the Orestation",
    "Jump across the Lava Pool",
    "Look through 5 Telescopes",
    "Make the Glowmoths Hatch",
    "Obtain 7 Wallet Upgrades",
    "Obtain Gorilla Woods Tracker",
    "Obtain Ivory Peaks Tracker",
    "Obtain Marrow Hill Tracker",
    "Obtain any 3 Trackers",
    "Obtain the Crystal Deep Tracker",
    "Obtain the Sootling on a Leash",
    "Open 10 Chests",
    "Open 3 Doors/Hatches in Marrow Hill",
    "Open 4 Shortcut Poles",
    "Open 5 Doors/Hatches in Ivory Peaks",
    "Open 6 Doors/Hatches in the Gorilla Woods",
    "Open 8 Doors/Hatches in the Underdark",
    "Open all 4 Doors in the Slug Gardens",
    "Open the Blue Chest",
    "Open the Green Chest",
    "Open the Screech Door",
    "Open the Underbelly Door",
    "Pay Skeeper 100 Fruits",
    "Plant 3 Spores",
    "Reach the East Coast",
    "Read 8 Signs",
    "Release Obtainium in 2 Places",
    "Release Pressure in the Underbelly",
    "Repair Sandro's Bridge",
    "Repair the Smashed Statue Pieces",
    "Ride 15 Metal Rails",
    "Roll 5 Boulders or Snowballs",
    "Save all 4 Traitor Spirits",
    "Scare a Bat",
    "Spin Blue Pinwheels in 2 Locations",
    "Start the Rocket of the Space Monks",
    "Take the Spider Orphan to the Tree",
    "Talk to Slug Gardener, Nabinabi, Krimm, Chirp",
    "Talk to Sweepers, Dolphin, Plissken, Kambi",
    "Talk to Zo, Rolypoly, Leeper, Ithaqua",
    "Upgrade to the Fat Skvader",
    "Use 2 Keys"
];
