bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "10 Chests",
    "15 Metal Rails",
    "2 Blue Pinwh. Loc.",
    "2 Gold Piles",
    "2 Horns",
    "2 Keys",
    "2 Obtanium Releases",
    "2 Sootlings",
    "2 Traitor Spirits",
    "20 Mailboxes",
    "20 Scarabs",
    "25 Fruit at Waterfall",
    "3 Beelines",
    "3 Main Items",
    "3 Marrow Hill D./H.",
    "3 Spores",
    "3 Tadpoles",
    "3 Totems",
    "3 Trackers",
    "30 Deaths",
    "350 Fruits",
    "4 Cliffs (2s)",
    "4 Map Areas",
    "4 Poles",
    "5 Boulders",
    "5 Hidden Tunnels",
    "5 Ivory Peaks D./H.",
    "5 Telescopes",
    "6 Fruit Pinwheels",
    "6 Gorilla Woods D./H.",
    "6 Jewel Bumpers",
    "7 Wallets",
    "8 Signs",
    "8 Underdark D./H.",
    "Ape and Orestation T.",
    "Baldino",
    "Bat",
    "Befriend Kickback",
    "Black",
    "Blue Chest",
    "Boon of Plenty",
    "Bridge",
    "Ceremony Instruments",
    "Cleepers",
    "Cove Mushroom",
    "Crystal Deep BL",
    "Crystal Deep Tr.",
    "Crystals in 3 Areas",
    "Defeat Kickback",
    "Dive Fish",
    "Dolphin Crystals",
    "Dolphin and Sin T.",
    "East Coast",
    "Egg",
    "Fast Dive Fish",
    "Fat Skvader",
    "Fleek Heart",
    "Forgive Kickback",
    "Fosfor's Stash",
    "Glowmoths",
    "Gold",
    "Gorilla Woods BL",
    "Gorilla Woods Tr.",
    "Grand Postmaster Badge",
    "Green",
    "Green Chest",
    "Hook",
    "Horned Statue",
    "Ivory Peaks BL",
    "Ivory Peaks Tr.",
    "Juicery",
    "Lava Pool",
    "Liquorice",
    "Mail Bag",
    "Marrow Hill BL",
    "Marrow Hill Tr.",
    "Noisemaker",
    "Ocean Heart",
    "Ojva",
    "Orest. Hatches",
    "Pay Skeeper",
    "Pressure",
    "Quinbe",
    "Red",
    "Ruby-Ball",
    "Scarab Tracker",
    "Screech",
    "Screech Door",
    "Sin",
    "Skvader",
    "Slug Gard., Nabinabi, Krimm, Chirp",
    "Slug Garden Doors",
    "Slug Vacuum",
    "Slug Vacuum Deluxe",
    "Smashed Pieces",
    "Spider",
    "Spiderling",
    "Spina and Screetch T.",
    "Splank",
    "Squirrowl",
    "Storyboards",
    "Sumoe",
    "Sush",
    "Sweepers, Dolphin, Plissken, Kambi",
    "Toadstool",
    "Tower Crystal",
    "Tower Slug",
    "Treasure Map",
    "Treek",
    "Umbaba's Puzzle",
    "Underbelly Door",
    "Underdark Access",
    "Village and Ivory T.",
    "Violet",
    "Water",
    "Zo, Rolypoly, Leeper, Ithaqua"
];
