bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Activate 20 Scarabs",
    "Activate 3 Beelines",
    "Activate 6 Jewel Bumpers",
    "Activate All 4 Temple Storyboards",
    "Activate Ape and Orestation Totem",
    "Activate Dolphin and Sin Totem",
    "Activate Spina and Screetch Totem",
    "Activate Village and Ivory Peak Totem",
    "Bathe the 6 Sootlings",
    "Blow 2 Horns",
    "Check 5 Telescopes",
    "Close Ore Station Hatches",
    "Complete the Juicer",
    "Defeat Kickback",
    "Deliver the Blue Package",
    "Deliver the Green Package",
    "Deliver the Purple Package",
    "Deliver to 20 Mailboxes",
    "Fall into Thorns 30 Times",
    "Feed Fosfor Both Mushrooms",
    "Forgive Kickback",
    "Free the Info Person",
    "Get 3 Tracker Eyes",
    "Get 5 Wallet Upgrades",
    "Get Fleek Heart Fruit",
    "Get Ocean Heart Fruit",
    "Get Treasure Map",
    "Get a Skvader",
    "Get the Bumble-Bee Ball",
    "Get the Cocoon Ball",
    "Get the Dung Ball",
    "Get the Fairy Egg Ball",
    "Get the Firefly Ball",
    "Get the Gold Scarab Ball",
    "Get the Jeweled Skull Ball",
    "Get the Rose Ball",
    "Get the Ruby Ball",
    "Get the Sootling-on-a-Leash",
    "Get the Strawberry Ball",
    "Have 450 Fruits on hand",
    "Open 10 Chests",
    "Open Blue Chest",
    "Open Green Chest",
    "Open Screetch Door",
    "Plant 3 Spores",
    "Repair Smashed Statue Pieces",
    "Repair the Bridge",
    "Roll 5 Boulders/Snowballs",
    "Save Chief Boon",
    "Save Chief Sal",
    "Save Chief Spina",
    "Saves 4 Traitors Spirits",
    "Saves the Tadpoles",
    "Take Spider Orphan to Tree"
];
