bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "Activate 10 Scarabs",
    "Activate 12 Jewel Bumpers",
    "Activate 2 Beelines",
    "Activate 20 Scarabs",
    "Activate 3 Totems",
    "Activate 4 Beelines",
    "Activate 5 Totems",
    "Activate 8 Totems",
    "Activate All 4 Temple Storyboards",
    "Bathe the 6 Sootlings",
    "Check 5 Telescopes",
    "Close Ore Station Hatches",
    "Complete the Juicer",
    "Defeat Kickback",
    "Deliver the Blue Package",
    "Deliver the Green Package",
    "Deliver the Purple Package",
    "Deliver to 10 Mailboxes",
    "Deliver to 20 Mailboxes",
    "Fall into Thorns 30 Times",
    "Feed Fosfor Both Mushrooms",
    "Forgive Kickback",
    "Free the Info Person",
    "Get 2 Baubles",
    "Get 2 Tracker Eyes",
    "Get 4 Tracker Eyes",
    "Get 4 Wallet Upgrades",
    "Get 5 Baubles",
    "Get 7 Wallet Upgrades",
    "Get Fat Skvader",
    "Get Fleek Heart Fruit",
    "Get Ocean Heart Fruit",
    "Get Skvader",
    "Get Treasure Map",
    "Get the Boon of Plenty",
    "Get the Deluxe Slug-Vac",
    "Get the Dive Fish",
    "Get the Dung Ball",
    "Get the Gold Postmaster Badge",
    "Get the Quick Dive Fish",
    "Get the Slug-Vac",
    "Get the Sootling-on-a-Leash",
    "Open 15 Chests",
    "Open 8 Chests",
    "Repair the Bridge",
    "Roll 4 Boulders/Snowballs",
    "Save Chief Boon",
    "Save Chief Sal",
    "Save Chief Spina",
    "Take Spider Orphan to Tree"
];
