bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "10 Chests",
    "15 Metal Rails",
    "2 Blue Pinwh. Loc.",
    "2 Gold Piles",
    "2 Horns",
    "2 Keys",
    "2 Obtainium Releases",
    "20 Mailboxes",
    "20 Scarabs",
    "25 Fruit at Waterfall",
    "3 Beelines",
    "3 Marrow Hill D./H.",
    "3 Spores",
    "3 Totems",
    "3 Trackers",
    "30 Deaths",
    "350 Fruits",
    "4 Cliffs (2s)",
    "4 Main Items",
    "4 Map Areas",
    "4 Poles",
    "5 Boulders",
    "5 Hidden Tunnels",
    "5 Ivory Peaks D./H.",
    "5 Telescopes",
    "6 Fruit Pinwheels",
    "6 Gorilla Woods D./H.",
    "6 Jewel Bumpers",
    "6 Sootlings",
    "7 Wallets",
    "8 Signs",
    "8 Tadpoles",
    "8 Underdark D./H.",
    "Ape and Orestation T.",
    "Bat",
    "Black",
    "Blue Chest",
    "Bridge",
    "Cleepers",
    "Crystal Deep BL",
    "Crystal Deep Tr.",
    "Crystals in 3 Areas",
    "Defeat Kickback",
    "Dolphin Crystals",
    "Dolphin and Sin T.",
    "East Coast",
    "Egg",
    "Fat Skvader",
    "Fleek Heart",
    "Forgive Kickback",
    "Glowmoths",
    "Gold",
    "Gorilla Woods BL",
    "Gorilla Woods Tr.",
    "Green",
    "Green Chest",
    "Hook",
    "Horned Statue",
    "Ivory Peaks BL",
    "Ivory Peaks Tr.",
    "Juicery",
    "Lava Pool",
    "Marrow Hill BL",
    "Marrow Hill Tr.",
    "Mushrooms",
    "Ocean Heart",
    "Ojva",
    "Orest. Hatches",
    "Pay Skeeper",
    "Pressure",
    "Quinbe",
    "Red",
    "Ruby-Ball",
    "Screech",
    "Screech Door",
    "Sin",
    "Skvader",
    "Slug Gard., Nabinabi, Krimm, Chirp",
    "Slug Garden Doors",
    "Smashed Pieces",
    "Spider",
    "Spiderling",
    "Spina and Screetch T.",
    "Squirrowl",
    "Storyboards",
    "Sush",
    "Sweepers, Dolphin, Plissken, Kambi",
    "Thorns Quest",
    "Tower Crystal",
    "Tower Slug",
    "Treasure Map",
    "Treek",
    "Underbelly Door",
    "Underdark Access",
    "Village and Ivory T.",
    "Violet",
    "Water",
    "Zo, Rolypoly, Leeper, Ithaqua"
];
