bingoGenerator = require("./generators/generator_bases/srl_generator_v5.js");

var bingoList = [[
{"name": "Hookshot"},
{"name": "Destroy a Big Octo Eye with ONLY the Hookshot"},
{"name": "Open all 9 Warp Pots in Diamond Steppe Island"},
{"name": "Defeat the ChuChu at Overlook Island"},
{"name": "Iron Boots and Hookshot"},
{"name": "Defeat a Wizzrobe with the Hookshot"},
{"name": "Defeat Red Wizzrobe with the Hookshot"}
],[
{"name": "Boomerang"},
{"name": "Destroy 4 Mounted Cannons at Six-Eye Reef"},
{"name": "Boomerang a Purple Rupee"},
{"name": "Destroy all 10 Mounted Cannons at Five-Eye Reef"},
{"name": "Defeat a Gyorg"},
{"name": "Hero's Bow"},
{"name": "Befriend Cyclos"},
{"name": "Score 8 Points in Fishman’s Minigame"},
{"name": "Clear all 3 Lookout Platforms at Seven-Star Isles"},
{"name": "Boomerang and Hero’s Bow"}
],[
{"name": "Grappling Hook"},
{"name": "Salvage a Rupee Treasure"},
{"name": "Salvage a Spoils Item"},
{"name": "Salvage a Heart Piece"},
{"name": "Salvage a Treasure at Four-Eye Reef"},
{"name": "Salvage a Treasure in Cyclops Reef Waters"},
{"name": "Salvage an Octorok Vase"},
{"name": "Defeat the ChuChu at Bird’s Peak Rock"},
{"name": "Collect a Vase Joy Pendant in Dragon Roost Cavern"},
{"name": "Defeat Gohma"},
{"name": "Full Clear Pawprint Isle"}
],[
{"name": "Bait Bag"},
{"name": "Feed Fishman at Western Fairy Island"},
{"name": "Feed Fishman near Mother & Child Isles"},
{"name": "Feed a Seagull to a Kargaroc"},
{"name": "Full Bait Bag"},
{"name": "Collect 25 Rupees with a Single Seagull"},
{"name": "Purchase a Blue Potion from a Friendly Salesrat"},
{"name": "Purchase a Red Potion from a Friendly Salesrat"},
{"name": "Purchase a Potion from a Friendly Salesrat"},
{"name": "Unearth Morths from Black Soil"},
{"name": "Full Clear Outset Island"}
],[
{"name": "Deku Leaf"},
{"name": "Enter Makar’s Secret Room in Forest Haven"},
{"name": "Defeat all 6 Boko Babas at Forest Haven"},
{"name": "Win the Flight Control Platform Minigame"},
{"name": "Empty Magic Bar"},
{"name": "Destroy a Leaf Pile"},
{"name": "Collect a Vase Joy Pendant in Forbidden Woods"},
{"name": "Defeat Kalle-Demos"},
{"name": "Crash the Blue Flower in Forbidden Woods"},
{"name": "Deku Leaf and Grappling Hook"}
],[
{"name": "Iron Boots"},
{"name": "Shatter a Wind God's Aria Stone"},
{"name": "Destroy all the Grass at Gale Isle"},
{"name": "Defeat a Curse Bubble"},
{"name": "Shatter the Cyclok Statue at Gale Isle"},
{"name": "Activate the Main Hub Cyclone in the Wind Temple"},
{"name": "Defeat a Floormaster in the Wind Temple"},
{"name": "Plant 6 Seeds in the Wind Temple"},
{"name": "Defeat Molgera"},
{"name": "Power Bracelets and Iron Boots"}
],[
{"name": "Solve the First Cabana Slide Puzzle"},
{"name": "Shatter all 4 Stone Watchers"},
{"name": "Collect all 3 Yellow Rupees on Outset Island"},
{"name": "Stand on a Grappling Post"},
{"name": "Become Poessessed"},
{"name": "Raise the Gate at Bird’s Peak Rock"},
{"name": "STRIKE DOWN all of Mesa's Grass with a Single Hurricane Spin"}
],[
{"name": "Bombs"},
{"name": "Defeat a Kargaroc with Bombs"},
{"name": "Sink Both Warships at Three-Eye Reef"},
{"name": "Sink the Golden Warship"},
{"name": "Sink all 4 Warships at Islet of Steel"},
{"name": "Clear Rock Spire Isle’s Combat Cave"},
{"name": "Sink the Warship at Northern Fairy Island"},
{"name": "Sink all 3 Warships at Two-Eye Reef"},
{"name": "Shatter all 5 Boulders on Star Island"},
{"name": "Fully Shatter Jabun’s Barrier"},
{"name": "Power Bracelets and Bombs"}
],[
{"name": "Hero's Sword"},
{"name": "Master Sword"},
{"name": "Parry a ChuChu"},
{"name": "Score 75 Points in Orca’s Training"},
{"name": "Parry a Moblin"},
{"name": "Defeat a Redead with the Hurricane Spin"},
{"name": "Full Power Master Sword"}
],[
{"name": "Cabana Deed"},
{"name": "Clear the Ghost Ship"},
{"name": "Any Tingle Statue"},
{"name": "Shatter all 4 Vases in the Cabana Cabin"},
{"name": "Deliver a Letter to the Postbox"},
{"name": "Full Clear Private Oasis"},
{"name": "Deliver a Letter to an Already Jumping Postbox"}
],[
{"name": "Skull Hammer"},
{"name": "Flatten a Miniblin"},
{"name": "Defeat 3 Moblins in Forsaken Fortress"},
{"name": "Defeat all 3 Spotlight Bokoblins at Forsaken Fortress"},
{"name": "Defeat a Floormaster in Forsaken Fortress"},
{"name": "Defeat the Octorok in Forsaken Fortress"},
{"name": "Flatten a Wizzrobe"},
{"name": "Flatten a ChuChu"},
{"name": "Flatten a Mothula"},
{"name": "Defeat the Helmaroc King"}
],[
{"name": "Fire and Ice Arrows"},
{"name": "Light Arrows"},
{"name": "Defeat a Fire Keese with Ice Arrows"},
{"name": "Light the Windfall Lighthouse"},
{"name": "Pick up a Frozen Enemy"},
{"name": "Melt all 9 Ice Chunks on Ice Ring Isle"},
{"name": "Fall Flat on Ice"},
{"name": "Collect all 17 Freestanding Rupees at Ice Ring Isle"}
],[
{"name": "Hero's Shield"},
{"name": "Have 4 Hearts"},
{"name": "Have 5 Hearts"},
{"name": "Defend a Moblin Bust’s Laser"},
{"name": "Collect a Piece of Heart"},
{"name": "Full Clear Angular Isles"},
{"name": "Master Sword and Mirror Shield"}
],[
{"name": "Empty Bottle"},
{"name": "Bottled Water"},
{"name": "Forest Firefly"},
{"name": "Red Potion"},
{"name": "Green Potion"},
{"name": "Blue Potion"},
{"name": "Heal Grandma"},
{"name": "Have Forest Water Expire"},
{"name": "Bloom a Withered Sapling"},
{"name": "Bloom a Withered Bomb Flower"},
{"name": "Break and Pay for Sue-Belle’s Vase"},
{"name": "Cook a Blue Potion at Hollo’s Shop"}
],[
{"name": "Power Bracelets"},
{"name": "Shatter an Earth God's Lyric Stone"},
{"name": "Activate Both Sun Masks in Earth Temple"},
{"name": "Open all 4 Transparent Chests in Earth Temple"},
{"name": "Crumble all 8 Pillars in Stone Watcher Island’s Cave"},
{"name": "Defeat a Fire Bubble"},
{"name": "Shatter a Stone Watcher"},
{"name": "Defeat 2 Redeads in Earth Temple"},
{"name": "Enter the Blue Warp Pot in Earth Temple"},
{"name": "Defeat Jalhalla"}
],[
{"name": "Collect 25 Sand Rupees at Headstone Island"},
{"name": "Absorb all the Fairies in Southern Fairy Island"},
{"name": "Collect a Yellow Rupee on Bomb Island"},
{"name": "Collect the Red Rupee on Dragon Roost Island"},
{"name": "Shatter all 10 Boulders on Dragon Roost Island’s Exterior"},
{"name": "Defeat the ChuChu at Thorned Fairy Island"},
{"name": "Defeat all 5 Kargarocs at Bird’s Peak Rock"},
{"name": "Defeat all 5 Kargarocs at Five-Star Isles"},
{"name": "Defeat the ChuChu at Shark Island"},
{"name": "Collect the Red Rupee Above Aryll's Lookout"},
{"name": "Open a Transparent Chest"},
{"name": "Open a Fire Ringed Chest"},
{"name": "Defeat Both Kargarocs at Dragon Roost Island"}
],[
{"name": "1 Triforce Shard"},
{"name": "2 Triforce Shards"},
{"name": "3 Triforce Shards"},
{"name": "3 Charts"},
{"name": "5 Charts"},
{"name": "Decipher a Triforce Chart"},
{"name": "Collect a Corner Triforce Shard"},
{"name": "Triforce of Courage"}
],[
{"name": "Purple Rupee"},
{"name": "Orange Rupee"},
{"name": "Silver Rupee"},
{"name": "Max Rupees for your Wallet"},
{"name": "Have Exactly 69 Rupees for 5 seconds"},
{"name": "Have Exactly 420 Rupees for 5 seconds"},
{"name": "Have Exactly 666 Rupees for 5 seconds"},
{"name": "Purchase Anything from Rock Spire Beedle"}
],[
{"name": "Any Dungeon Map"},
{"name": "Any Compass"},
{"name": "Any Big Key"},
{"name": "Unlock a Big Key Door"},
{"name": "4 Wind Waker Songs"},
{"name": "6 Wind Waker Songs"},
{"name": "Collect a Joy Pendant in the RMR Dungeon"},
{"name": "Defeat the RMR Dungeon Boss"},
{"name": "Open 3 Chests in the RMR Dungeon"},
{"name": "Unlock 2 Key-Locked Doors"},
{"name": "Unlock 4 Key-Locked Doors"},
{"name": "Hear “Mini-Boss” Theme"}
],[
{"name": "Have 3 Boko Baba Seeds"},
{"name": "Have 3 Blue Chu Jelly"},
{"name": "Have 3 Golden Feathers"},
{"name": "Have 3 Joy Pendants"},
{"name": "Collect a Knight's Crest"},
{"name": "Have 3 Skull Necklaces"},
{"name": "Have 6 Different Spoils Items"},
{"name": "Collect a Randomized Spoils Item"},
{"name": "Sell Beedle Spoils Worth 30 Rupees Total"}
],[
{"name": "Zephos & Cyclos Picture"},
{"name": "Phantom Ganon Picture"},
{"name": "Valoo Picture"},
{"name": "Makar Picture"},
{"name": "Medli Picture"},
{"name": "Fishman Picture"},
{"name": "Stalfos Picture"},
{"name": "Seahat Picture"},
{"name": "Rat Picture"},
{"name": "Poe Picture"},
{"name": "Sue-Belle Picture"},
{"name": "Floormaster Picture"},
{"name": "Redead Picture"},
{"name": "Darknut Picture"},
{"name": "Salvage Corp Picture"},
{"name": "Wandering Merchant Picture"}
],[
{"name": "Swing a Darknut Sword"},
{"name": "Swing a Stalfos Club"},
{"name": "Dislodge a Darknut's Helm"},
{"name": "Defeat a Magtail"},
{"name": "Defeat a Wizzrobe"},
{"name": "Clear Horseshoe Island’s Combat Cave"},
{"name": "Clear Boating Course’s Combat Cave"},
{"name": "Clear Dragon Roost Island’s Combat Cave"},
{"name": "Clear Star Island’s Combat Cave"},
{"name": "Clear Stone Watcher Island’s Combat Cave"},
{"name": "Clear Shark Island’s Combat Cave"},
{"name": "Clear Ice Ring Isle’s Combat Cave"},
{"name": "Defeat 4 Different Types of ChuChu"},
{"name": "Defeat a Mothula in Savage Labyrinth"},
{"name": "Defeat 2 Moblins in Savage Labyrinth"},
{"name": "Defeat Both Redeads in the Cabana Labyrinth"},
{"name": "Clear Overlook Island’s Combat Cave"},
{"name": "Clear Pawprint Isle’s Wizzrobe Combat Cave"},
{"name": "Swing a Moblin Spear"},
{"name": "Break 4 Treasure Orbs"},
{"name": "Defeat a Floormaster"}
],[
{"name": "Win the Spectacle Island Minigame"},
{"name": "Score Exactly 26 in Mail Sorting"},
{"name": "Defeat the Size 2 Squid in Sploosh-Kaboom"},
{"name": "Defeat the Size 3 Squid in Sploosh-Kaboom"},
{"name": "Defeat the Size 4 Squid in Sploosh-Kaboom"},
{"name": "Win an Auction at Windfall Island"},
{"name": "Clear the Pirate Ship Rope Course"},
{"name": "Have 4 Different Items in your Delivery Bag"},
{"name": "Place 9 Decorations at Windfall Island"},
{"name": "Score Exactly 99 Rupees at the Boating Course Minigame"},
{"name": "Place a Fountain Idol"}
],[
{"name": "Defeat a ChuChu in the Tower of the Gods"},
{"name": "Din's Pearl"},
{"name": "Nayru's Pearl"},
{"name": "Farore's Pearl"},
{"name": "All Goddess Pearls"},
{"name": "Defeat an Armos Knight"},
{"name": "Shut an Eye Switch"},
{"name": "Defeat a Beamos"},
{"name": "Collect a Vase Joy Pendant in the Tower of the Gods"},
{"name": "Defeat Gohdan"}
],[
{"name": "Defeat 3 Different Kargarocs on Needle Rock Isle"},
{"name": "Defeat Both Octoroks at Forest Haven"},
{"name": "Defeat all 4 Kargarocs at Star Belt Archipelago"},
{"name": "Defeat a Big Octo with ONLY the Boomerang"},
{"name": "Defeat a Big Octo with ONLY Bombs"},
{"name": "Defeat a Blue Wizzrobe"},
{"name": "Defeat a Big Octo with ONLY the Bow"},
{"name": "Defeat the Kargaroc atop Fire Mountain"},
{"name": "Defeat Both Kargarocs at Seven-Star Isles"},
{"name": "Defeat Both Kargarocs at Dragon Roost Island’s Exterior"},
{"name": "Defeat a 12 Eyed Big Octo"},
{"name": "Defeat an 8 Eyed Big Octo"},
{"name": "Defeat all 4 Kargarocs at Islet of Steel"}
]];
