bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "20 Golden Feathers to Hoskit}",
    "20 Joy Pendants to Mrs. Marie",
    "3 chests found on Lookout Platforms",
    "5 Tingle Statues",
    "Angular Isles Chest",
    "At least 1 of Every Spoil (Bag not required)",
    "Bait Bag Get",
    "Big Octo Great Fairy",
    "Brew a Green/Blue Potion",
    "Chest inside Mother Island",
    "Clear Pawprint Island",
    "Collect 10 Charts",
    "Collect Forest Water",
    "Cool down Fire Mountain",
    "Decorate Private Oasis",
    "Defeat a Stalfos",
    "Deku Nut Golf",
    "Diamond Steppe Island Warp Maze Chests",
    "Die by Blue ChuChu",
    "Die from a Gunboat",
    "Drown",
    "Feed 2 Fishy Bois",
    "Fix a Broken Sign with Aria",
    "Flight Control Platform Submarine",
    "Full Power Master Sword",
    "Full Triforce",
    "Get Cursed by Cursed Bubble",
    "Get a Seagull Hurt",
    "Ghost Ship",
    "Give Kalle Demos Water to Drink",
    "Gohdan Defeated",
    "Gohma Defeated",
    "Haul Link the Pig up the Mountain",
    "Have 10 Heart Containers",
    "Have 8 Heart Containers",
    "Heal Grandma",
    "Hear a Rumor From Kids",
    "Helmaroc King Defeated",
    "Hero's Charm",
    "Ice Ring Isle - Inner Cave Chest",
    "Ivan - Catch Killer Bees",
    "Jalhalla Defeated",
    "Kalle Demos Defeated",
    "Kill a Darknut",
    "Molgera Defeated",
    "OHKO a Deku Baba with Boomerang",
    "OHKO a ReDead with a Light Arrow",
    "OHKO a Wizzrobe with a Fire/Ice Arrow",
    "One Slide Puzzle in Cabana",
    "Open Nintendo Gallery",
    "Outset Island Great Fairy",
    "Phantom Ganon (Fortress) Defeated",
    "Savage Labyrinth Floor 30",
    "Score 20 or higher in Mail Sorting",
    "Shoot Down Cyclos",
    "Spook Guy at Milk Bar",
    "Squash an Enemy with Hammer",
    "Stock Exotic Flower in Zunari's Shop",
    "Summon Tower of the Gods",
    "Three-Eye Reef Chest",
    "Throw Medli Into a Wall",
    "Top of Deku Tree",
    "Translate 1 Triforce Chart",
    "Warm up Ice Ring Isle",
    "Win Battleship"
];
