bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
    "1 Bottle",
    "2 Bottles",
    "20 Golden Feathers to Hoskit}",
    "20 Joy Pendants to Mrs. Marie",
    "3 Bottles",
    "3 chests found on Lookout Platforms",
    "4 Bottles",
    "5 Tingle Statues",
    "99 Arrow Quiver",
    "99 Bomb Bag",
    "Angular Isles Chest",
    "At least 1 of Every Spoil (Bag not required)",
    "Bait Bag",
    "Bait Bag Get",
    "Ballad of Gales",
    "Big Octo Great Fairy",
    "Bombs",
    "Boomerang",
    "Bow",
    "Brew a Green/Blue Potion",
    "Chest inside Mother Island",
    "Clear Pawprint Island",
    "Collect 10 Charts",
    "Collect Forest Water",
    "Command Melody",
    "Complete a Long Sidequest",
    "Cool down Fire Mountain",
    "Decorate Private Oasis",
    "Defeat a Stalfos",
    "Deku Leaf",
    "Deku Nut Golf",
    "Delivery Bag",
    "Deluxe Picto Box",
    "Diamond Steppe Island Warp Maze Chests",
    "Die by Blue ChuChu",
    "Die from a Gunboat",
    "Die in Any Way",
    "Double Magic Meter",
    "Drown",
    "Earth God's Lyric",
    "Feed 2 Fishy Bois",
    "Fire/Ice Arrows",
    "Fix a Broken Sign with Aria",
    "Flight Control Platform Submarine",
    "Full Power Master Sword",
    "Full Triforce",
    "Get Cursed by Cursed Bubble",
    "Get a Seagull Hurt",
    "Ghost Ship",
    "Give Kalle Demos Water to Drink",
    "Gohdan Defeated",
    "Gohma Defeated",
    "Grappling Hook",
    "Haul Link the Pig up the Mountain",
    "Have 10 Heart Containers",
    "Have 8 Heart Containers",
    "Heal Grandma",
    "Hear a Rumor From Kids",
    "Helmaroc King Defeated",
    "Hero's Charm",
    "Hookshot",
    "Ice Ring Isle - Inner Cave Chest",
    "Iron Boots",
    "Ivan - Catch Killer Bees",
    "Jalhalla Defeated",
    "Kalle Demos Defeated",
    "Kill 5 Enemies With One Attack",
    "Kill Enemies with 3 Different Alternate Weapons",
    "Kill a Darknut",
    "Magic Armor",
    "Mirror Shield",
    "Molgera Defeated",
    "OHKO a Deku Baba with Boomerang",
    "OHKO a ReDead with a Light Arrow",
    "OHKO a Wizzrobe with a Fire/Ice Arrow",
    "One Slide Puzzle in Cabana",
    "Open Nintendo Gallery",
    "Outset Island Great Fairy",
    "Phantom Ganon (Fortress) Defeated",
    "Picto Box",
    "Power Bracelets",
    "Savage Labyrinth Floor 30",
    "Score 20 or higher in Mail Sorting",
    "Shoot Down Cyclos",
    "Skull Hammer",
    "Spoils Bag",
    "Spook Guy at Milk Bar",
    "Squash an Enemy with Hammer",
    "Stock Exotic Flower in Zunari's Shop",
    "Summon Tower of the Gods",
    "Telescope",
    "Three-Eye Reef Chest",
    "Throw Medli Into a Wall",
    "Tingle Tuner",
    "Top of Deku Tree",
    "Translate 1 Triforce Chart",
    "Warm up Ice Ring Isle",
    "Win Battleship",
    "Wind God's Aria"
];
