var bingoGenerator = require("./generators/generator_bases/srl_generator_v5.js");

var bingoList = [undefined, [
{ "name": "1 Item from Stockwells Shop", "types": [] },
{ "name": "1 Scroll", "types": ["Scroll"] },
{ "name": "DHC Basement Big Chest", "types": ["DHC"] },
{ "name": "Die", "types": [] },
{ "name": "Eastern Hills Beanstalk", "types": ["Eastern Beanstalk"] },
{ "name": "Enter DHC", "types": ["DHC"] },
{ "name": "Put out 1 Fireplace", "types": [] },
{ "name": "Sword", "types": ["Sword"] }
],[
{ "name": "10 Bomb Bag", "types": ["Bombs"] },
{ "name": "1 Bottle", "types": ["Bottle"] },
{ "name": "6 Hearts", "types": ["Hearts"] },
{ "name": "A Book", "types": ["Book"] },
{ "name": "Bow", "types": ["Bow"] },
{ "name": "Digging Mitts", "types": [] },
{ "name": "Flame Lantern", "types": [] },
{ "name": "Green Sword", "types": ["Sword"] },
{ "name": "Roc's Cape", "types": [] },
{ "name": "Spin Attack", "types": ["Scroll"] }
],[
{ "name": "Cane of Pacci", "types": [] },
{ "name": "Flippers", "types": [] },
{ "name": "Graveyard Key", "types": [] },
{ "name": "Grip Ring", "types": [] },
{ "name": "Gust Jar", "types": [] },
{ "name": "Ocarina of Winds", "types": [] },
{ "name": "Pegasus Boots", "types": [] },
{ "name": "Red Sword", "types": ["Sword"] },
{ "name": "Veil Falls Kinstone", "types": [] }
],[
{ "name": "10 Hearts", "types": ["Hearts"] },
{ "name": "2 Books", "types": ["Book"] },
{ "name": "2 Bottles", "types": ["Bottle"] },
{ "name": "300 Wallet", "types": ["Wallet"] },
{ "name": "30 Bomb Bag", "types": ["Bombs"] },
{ "name": "50 Quiver", "types": ["Quiver"] },
{ "name": "Blue Sword", "types": ["Sword"] },
{ "name": "Boomerang", "types": ["Boomerang"] },
{ "name": "One of each type of golden kinstone", "types": [] },
{ "name": "Shield", "types": ["Shield"] }
],[
{ "name": "Item from Simon Simulation", "types": [] },
{ "name": "Kill a Keaton", "types": [] },
{ "name": "Kill a Leever", "types": [] },
{ "name": "Kill an Acrobandit", "types": [] },
{ "name": "Kill an Octorok", "types": [] },
{ "name": "Kill a Peahat", "types": [] },
{ "name": "Kill a Pesto", "types": [] },
{ "name": "Kill a Slug", "types": [] },
{ "name": "Kill a Spiney Beetle", "types": [] },
{ "name": "Kill a Tektite", "types": [] }
],[
{ "name": "1 Item from Swiftblade", "types": ["Swiftblade"] },
{ "name": "1 ToD small key", "types": ["ToD"] },
{ "name": "Enter CoF", "types": ["CoF"] },
{ "name": "Enter DWS", "types": ["DWS"] },
{ "name": "Enter ToD", "types": ["ToD"] },
{ "name": "Item from Lower Crenel Hotspring", "types": [] },
{ "name": "Item from Minish Village Barrel", "types": [] },
{ "name": "Item from Town Fountain", "types": [] },
{ "name": "ToD BK", "types": ["ToD"] }
],[
{ "name": "DWS Madderpillar", "types": ["DWS","Madderpillar"] },
{ "name": "DWS Mulldozer Fight", "types": ["DWS"] },
{ "name": "Item from Castor Darknut", "types": ["Castor","Darknut"] },
{ "name": "Kill a Helmasaur", "types": [] },
{ "name": "Kill a Moblin", "types": [] },
{ "name": "Kill a Moldworm", "types": [] },
{ "name": "Kill a Mulldozer", "types": [] },
{ "name": "Kill CoF Spikey Chus", "types": ["CoF"] },
{ "name": "ToD Mulldozer Fight", "types": ["ToD"] }
],[
{ "name": "1 CoF small key", "types": ["CoF", "Small Key"] },
{ "name": "1 DHC small key", "types": ["DHC","Small Key"] },
{ "name": "1 DWS small key", "types": ["DWS", "Small Key"] },
{ "name": "1 Element", "types": ["Element"] },
{ "name": "2 Items from Swiftblade", "types": [] },
{ "name": "2 ToD small keys", "types": ["ToD","Small Key"] },
{ "name": "CoF BK", "types": ["CoF", "Big Key"] },
{ "name": "Floating item in Castor", "types": ["Floater","Castor"] },
{ "name": "Item from Belari", "types": [] },
{ "name": "Item from Waveblade", "types": ["Hearts"] }
],[
{ "name": "Kill a Cloud Shark", "types": ["Cloud"] },
{ "name": "Kill a Darknut", "types": ["Darknut"] },
{ "name": "Kill a Golden Enemy", "types": ["Golden Tektite", "Golden Octo", "Golden Rope"] },
{ "name": "Kill all 3 Golden Ropes", "types": ["Golden Rope"] },
{ "name": "Kill all 3 Golden Tektites", "types": ["Golden Tektite"] },
{ "name": "Kill a Madderpillar", "types": ["Madderpillar"] },
{ "name": "Kill an Eyegore", "types": ["Castor"] },
{ "name": "Kill a Scissor Beetle", "types": ["Scissor"] }
],[
{ "name": "2 CoF small keys", "types": ["CoF", "Small Key"] },
{ "name": "2 DWS small keys", "types": ["DWS", "Small Key"] },
{ "name": "3 Items from Swiftblade", "types": [] },
{ "name": "3 ToD small keys", "types": ["ToD","Small Key"] },
{ "name": "DWS BK", "types": ["DWS", "Big Key"] },
{ "name": "Get hit by a Cat", "types": [] },
{ "name": "Item from Grimblade", "types": [] },
{ "name": "Item from Syrup (The Witch)", "types": [] },
{ "name": "Save Gregal", "types": [] }
],[
{ "name": "4 Scrolls", "types": ["Scroll"] },
{ "name": "Dash Attack", "types": ["Scroll"] },
{ "name": "Down Strike", "types": ["Scroll"] },
{ "name": "Fast Spin", "types": ["Scroll"] },
{ "name": "Fast Split", "types": ["Scroll"] },
{ "name": "Greatspin", "types": ["Scroll"] },
{ "name": "Long Spin", "types": ["Scroll"] },
{ "name": "Peril Beam", "types": ["Scroll"] },
{ "name": "Rock Breaker", "types": ["Scroll"] },
{ "name": "Roll Attack", "types": ["Scroll"] },
{ "name": "Sword Beam", "types": ["Scroll"] }
],[
{ "name": "2 Items from Stockwells Shop", "types": ["Shop","Wallet"] },
{ "name": "Crenel Beanstalk", "types": ["Crenel Beanstalk"] },
{ "name": "Item from Castor Hiking", "types": [] },
{ "name": "Item from Crenel Mitts Cave", "types": [] },
{ "name": "Item from Crenel Scrub", "types": ["Shop"] },
{ "name": "Item from Dampe", "types": [] },
{ "name": "Item from Trilby Scrub", "types": ["Shop"] },
{ "name": "Item from Veil Falls Waterfall", "types": [] }
],[
{ "name": "3 DWS small keys", "types": ["DWS","Small Key"] },
{ "name": "4 ToD small keys", "types": ["ToD","Small Key"] },
{ "name": "Break 5 Large Trees", "types": [] },
{ "name": "Hylia Beanstalk", "types": ["Hylia Beanstalk"] },
{ "name": "Item from Librari", "types": [] },
{ "name": "Item from Melari", "types": ["CoF","Clear"] },
{ "name": "Item from Percy", "types": [] },
{ "name": "Kill Octo (Boss)", "types": ["ToD", "Clear"] },
{ "name": "Western Woods Beanstalk", "types": ["Western Beanstalk"] }
],[
{ "name": "4 Items from Swiftblade", "types": ["Swiftblade"] },
{ "name": "Item from Crenel Great Fairy", "types": ["Bomb Fairy"] },
{ "name": "Item from Grayblade", "types": ["Grayblade"] },
{ "name": "Item from Greatblade", "types": ["Flippers Dojo","Field"] },
{ "name": "Item from Minish Great Fairy", "types": ["Orphan Fairy"] },
{ "name": "Item from Scarblade", "types": ["Flippers Dojo"] },
{ "name": "Item from Splitblade", "types": ["Flippers Dojo"] },
{ "name": "Item from Valley Great Fairy", "types": ["Arrow Fairy"] }
],[
{ "name": "Bow Butterfly", "types": ["Butterfly"] },
{ "name": "DHC Stone King", "types": ["DHC"] },
{ "name": "Flippers Butterfly", "types": ["Butterfly"] },
{ "name": "Four Sword", "types": ["Sword"] },
{ "name": "Item from a Ghost", "types": ["Ghost"] },
{ "name": "Item from School Garden HP", "types": [] },
{ "name": "Item from Town Underground Pillar", "types": [] },
{ "name": "Light Arrows", "types": ["Bow"] },
{ "name": "Mitts Butterfly", "types": ["Butterfly"] }
],[
{ "name": "Carlov Medal", "types": ["Carlov"] },
{ "name": "Dog Food", "types": ["Fifi"] },
{ "name": "Item from Fifi", "types": ["Fifi"] },
{ "name": "Item from Figurine House", "types": ["Carlov"] },
{ "name": "Item from Rem", "types": ["Rem"] },
{ "name": "Item from Tingle", "types": ["Tingle"] },
{ "name": "Jabber Nut", "types": ["Item"] },
{ "name": "LonLon Ranch Key", "types": [] },
{ "name": "Remote Bombs", "types": [] },
{ "name": "Tingle Trophy", "types": ["Tingle"] },
{ "name": "Wake Up Shroom", "types": ["Rem"] }
],[
{ "name": "1 RC small key", "types": ["RC","Small Key"] },
{ "name": "2 RC small keys", "types": ["RC","Small Key"] },
{ "name": "3 RC small keys", "types": ["RC","Small Key"] },
{ "name": "4 DWS small keys", "types": ["DWS","Small Key"] },
{ "name": "Enter RC", "types": ["RC"] },
{ "name": "Floating item in Valley", "types": ["Floater","RC"] },
{ "name": "Full Clear CoF", "types": ["CoF","Clear"] },
{ "name": "Ice Madderpillar", "types": ["ToD","Madderpillar"] },
{ "name": "Item from Ghost King", "types": ["RC","Clear","Ghost"] },
{ "name": "Kill Blue Chu (Boss)", "types": ["ToD","Clear"] },
{ "name": "Kill Gleerok", "types": ["CoF","Clear"] },
{ "name": "Kill Green Chu (Boss)", "types": ["DWS","Clear"] }
],[
{ "name": "15 Hearts", "types": ["Hearts"] },
{ "name": "All 11 LonLon Ranch + 6 Eastern Hills Locations", "types": ["Clear"] },
{ "name": "All 22 Trilby + 21 Western Woods Locations", "types": ["Western Beanstalk"] },
{ "name": "All 23 Minish Woods Locations", "types": ["Clear"] },
{ "name": "All 25 Veil Falls locations", "types": ["Flippers Dojo", "Falls"] },
{ "name": "All 34 Mt Crenel Locations", "types": ["Crenel Beanstalk", "Grayblade", "CoF", "Clear"] },
{ "name": "All 3 Great Fairy Fountains", "types": ["Orphan Fairy", "Bomb Fairy", "Arrow Fairy"] },
{ "name": "All 8 Royal Valley Locations", "types": ["RC"] },
{ "name": "Full Clear DWS", "types": ["DWS","Clear"] },
{ "name": "Full Clear ToD", "types": ["ToD","Clear"] }
],[
{ "name": "2 DHC small keys", "types": ["DHC","Small Key"] },
{ "name": "70 Quiver", "types": ["Quiver"] },
{ "name": "All 30 Hyrule Field Locations", "types": ["Tingle"] },
{ "name": "Item from Lake Cabin", "types": ["Hylia", "Power Bracelets"] },
{ "name": "Kill 3 unique Darknuts", "types": ["Darknut"] },
{ "name": "Kill 4 unique Madderpillars", "types": ["Madderpillar"] },
{ "name": "Magic Boomerang", "types": ["Boomerang"] },
{ "name": "Mirror Shield", "types": ["Shield"] },
{ "name": "Power Bracelets", "types": ["Power Bracelets"] }
],[
{ "name": "2 Elements", "types": ["Element"] },
{ "name": "3 Bottles", "types": ["Bottle"] },
{ "name": "3 Castor Wilds Kinstones", "types": ["Ruins"] },
{ "name": "3 DHC small keys", "types": ["DHC","Small Key"] },
{ "name": "500 Wallet", "types": ["Wallet"] },
{ "name": "50 Bomb Bag", "types": ["Bombs"] },
{ "name": "7 Scrolls", "types": ["Scroll"] },
{ "name": "Complete all 4 Fetch Quests", "types": ["Tingle", "Carlov", "Rem", "Fifi"] }
],[
{ "name": "2 Element Ped Item", "types": ["Element"] },
{ "name": "3 Books", "types": ["Book"] },
{ "name": "All 18 Castor Wilds Locations", "types": ["Castor"] },
{ "name": "All 21 Lake Hylia Locations", "types": ["Hylia", "Hylia Beanstalk"] },
{ "name": "Enter FoW", "types": ["FoW", "Ruins"] },
{ "name": "Floating item from Ruins", "types": ["Floaters","Ruins"] },
{ "name": "Item from Swiftblade the First (Castor)", "types": ["Castor Dojo","Ghost","Scroll"] },
{ "name": "Kill all 3 Golden Octos", "types": ["Golden Octo"] },
{ "name": "Wind Ruins Beanstalk", "types": ["Ruins Beanstalk","Ruins"] }
],[
{ "name": "1 FoW small key", "types": ["FoW","Small Key"] },
{ "name": "2 FoW small keys", "types": ["FoW","Small Key"] },
{ "name": "4 DHC small keys", "types": ["DHC","Small Key"] },
{ "name": "5 Cloud Tops Kinstones", "types": ["Kinstone"] },
{ "name": "All 11 Dojo Items", "types": ["Castor Dojo", "Swiftblade", "Flippers Dojo", "Grimblade", "Grayblade", "Waveblade"] },
{ "name": "All 3 Floating Items", "types": ["Floaters"] },
{ "name": "All 5 Beanstalks", "types": ["Ruins Beanstalk", "Eastern Beanstalk", "Crenel Beanstalk", "Hylia Beanstalk", "Western Beanstalk"] },
{ "name": "Item from Yellari", "types": ["Book"] },
{ "name": "Kill 9 unique Scissor Beetles", "types": ["Scissor"] }
],[
{ "name": "1 PoW small key", "types": ["PoW","Small Key"] },
{ "name": "2 PoW small keys", "types": ["PoW","Small Key"] },
{ "name": "3 Elements", "types": ["Element"] },
{ "name": "3 FoW small keys", "types": ["FoW","Small Key"] },
{ "name": "3 PoW small keys", "types": ["PoW","Small Key"] },
{ "name": "4 FoW small keys", "types": ["FoW","Small Key"] },
{ "name": "4 PoW small keys", "types": ["PoW","Small Key"] },
{ "name": "5 PoW small keys", "types": ["PoW","Small Key"] },
{ "name": "All 9 Golden Kinstones", "types": ["Kinstone"] },
{ "name": "Enter PoW", "types": ["PoW"] },
{ "name": "FoW BK", "types": ["FoW","Big Key"] },
{ "name": "FoW Skull Fall Chest", "types": ["FoW"] },
{ "name": "Kill FoW Darknut", "types": ["FoW","Darknut"] },
{ "name": "Kill Mazaal", "types": ["FoW","Boss"] },
{ "name": "Kill PoW Darknut", "types": ["PoW","Darknut"] },
{ "name": "PoW BK", "types": ["PoW","Big Key"] }
],[
{ "name": "3 Element Ped Item", "types": ["Element"] },
{ "name": "5 DHC small keys", "types": ["Small Key", "DHC"] },
{ "name": "6 PoW small keys", "types": ["PoW","Small Key"] },
{ "name": "All 4 Items from Minish NPCs", "types": ["NPC"] },
{ "name": "All 9 Cloud Tops + 10 Wind Tribe Locations", "types": ["Cloud"] },
{ "name": "DHC Big Key", "types": ["DHC","Small Key", "Big Key"] },
{ "name": "Full Clear FoW", "types": ["FoW","Clear"] },
{ "name": "Full Clear PoW", "types": ["PoW","Clear"] },
{ "name": "Kill 8 unique Darknuts", "types": ["Darknut"] },
{ "name": "Kill all 9 Golden Enemies", "types": ["Golden Rope", "Golden Octo", "Golden Tektite"] },
{ "name": "Kill Gyorg", "types": ["PoW","Clear"] },
{ "name": "Kill Vaati", "types": ["DHC","Clear"] },
{ "name": "PoW chest after block maze", "types": ["PoW"] },
{ "name": "PoW Fan Loop", "types": ["PoW"] },
{ "name": "PoW Pot Push Puzzle", "types": ["PoW", "Power Bracelets"] }
],[
{ "name": "11 Scrolls", "types": ["Scroll"] },
{ "name": "3 Items from Stockwells Shop", "types": ["Shop", "Wallet"] },
{ "name": "4 Bottles", "types": ["Bottle"] },
{ "name": "4 Element Ped Item", "types": ["Element"] },
{ "name": "4 Elements", "types": ["Element"] },
{ "name": "999 Wallet", "types": ["Wallet"] },
{ "name": "99 Bomb Bag", "types": ["Bombs"] },
{ "name": "99 Quiver", "types": ["Quiver"] },
{ "name": "All 28 Small Keys", "types": ["Small Key", "Clear"] },
{ "name": "All 3 Butterflies", "types": ["Butterfly"] },
{ "name": "All 45 Town Locations", "types": ["Town"] },
{ "name": "All 6 Big Keys", "types": ["Big Key", "Clear"] },
{ "name": "Buy all 6 unique shop items", "types": ["Shop", "Wallet"] },
{ "name": "Kill 14 unique Darknuts", "types": ["Darknut"] }
]];
