var bingoList = [];
bingoList[1] = [
    { name: "ハイリアのフード", types: ["Clothes","Hylian Gear","Rupee"] },
    { name: "ハイリアの服", types: ["Clothes","Hylian Gear","Rupee","Rupee"] },
    { name: "防寒着", types: ["Clothes","Cold Resistance","Hateno"] },
    { name: "始まりの塔エリア コログのミ 3個", types: ["Korok","Plateau"] },
    { name: "ハイリアのズボン", types: ["Clothes","Hylian Gear","Rupee"] },
    { name: "“ボコ”系武器入手", types: ["Equipment"] },
    { name: "双子山の塔エリア コログのミ 3個", types: ["Korok","Dueling Peaks"] },
    { name: "平原の塔エリア コログのミ 3個", types: ["Korok","Central Hyrule"] }
];
bingoList[2] = [
    { name: "コログのミ 5個", types: ["Korok"] },
    { name: "ハテノ塔エリア コログのミ 3個", types: ["Korok","Hateno"] },
    { name: "フィローネの塔エリア コログのミ 3個", types: ["Korok","Faron"] },
    { name: "丘陵の塔エリア コログのミ 3個", types: ["Korok","Ridgeland"] },
    { name: "“錆びた”武器入手", types: ["Equipment"] },
    { name: "がんばり系料理", types: ["Cooking","Stamina"] },
    { name: "テリーにカブトムシをあげる", types: ["Horse"] },
    { name: "馬を登録する", types: ["Horse"] },
    { name: "コッコを怒らせる", types: ["Cucco"] },
    { name: "双子山の塔を起動", types: ["Tower","Dueling Peaks"] },
    { name: "木のオタマ", types: ["Equipment"] },
    { name: "ミニチャレンジ:ココナ's キッチン", types: ["Side Quest","Dueling Peaks"] },
    { name: "ゴーゴー系料理", types: ["Cooking"] },
    { name: "ピリ辛系料理", types: ["Cooking","Cold Resistance"] }
];
bingoList[3] = [
    { name: "始まりの塔エリア コログのミ 5個", types: ["Korok","Plateau"] },
    { name: "双子山の塔エリア コログのミ 6個", types: ["Korok","Dueling Peaks"] },
    { name: "湖の塔エリア コログのミ 3個", types: ["Korok","Lake"] },
    { name: "荒野の塔エリア コログのミ 3個", types: ["Korok","Wasteland"] },
    { name: "森林の塔エリア コログのミ 3個", types: ["Korok","Woodland"] },
    { name: "ラネールの塔エリア コログのミ 3個", types: ["Korok","Lanayru"] },
    { name: "ミニチャレンジ:大事なマラカス", types: ["Side Quest","Dueling Peaks"] },
    { name: "ミニチャレンジ:プリコと遊ぼ！", types: ["Side Quest","Dueling Peaks"] },
    { name: "ミニチャレンジ:野生馬を捕まえて", types: ["Side Quest","Dueling Peaks","Horse"] },
    { name: "ミニチャレンジ:器の操者", types: ["Side Quest","Hateno"] },
    { name: "ほこらチャレンジ:花を踏まないで", types: ["Shrine","Shrine Quest","Dueling Peaks"] },
    { name: "スタミナ系料理", types: ["Cooking","Stamina"] },
    { name: "チカラ系料理", types: ["Cooking"] },
    { name: "しのび系料理", types: ["Cooking"] },
    { name: "微妙な料理", types: ["Cooking"] },
    { name: "ボコ拠点の宝箱を2個開く", types: ["Plateau"] },
    { name: "マモノに襲われている旅人を助ける", types: ["Monster"] },
    { name: "湖の塔を起動", types: ["Tower","Lake"] },
    { name: "タバンタの塔エリア コログのミ 3個", types: ["Korok","Tabantha"] },
    { name: "“○○の骨”入手", types: ["Equipment"] },
    { name: "ミニチャレンジ 3個攻略", types: ["Side Quest"] }
];
bingoList[4] = [
    { name: "コログのミ 10個", types: ["Korok"] },
    { name: "オルディンの塔エリア コログのミ 3個", types: ["Korok","Eldin"] },
    { name: "アッカレの塔エリア コログのミ 3個", types: ["Korok","Akkala"] },
    { name: "大妖精1人解放", types: ["Rupee","Great Fairy"] },
    { name: "ハイリア防具一式", types: ["Clothes","Hylian Gear","Rupee"] },
    { name: "ハイリア兵の兜", types: ["Clothes","Soldier Gear","Rupee","Hateno"] },
    { name: "ハイリア兵の鎧", types: ["Clothes","Soldier Gear","Rupee","Hateno"] },
    { name: "ハイリア兵のすねあて", types: ["Clothes","Soldier Gear","Rupee","Hateno"] },
    { name: "忍びマスク", types: ["Clothes","Stealth Gear","Rupee","Dueling Peaks"] },
    { name: "忍びタイツ", types: ["Clothes","Stealth Gear","Rupee","Dueling Peaks"] },
    { name: "クライムバンダナ", types: ["Clothes","Climbing Gear","Dueling Peaks"] },
    { name: "ミニチャレンジ:消えたコッコちゃん", types: ["Side Quest","Dueling Peaks","Heirloom"] },
    { name: "ミニチャレンジ:ココナ's キッチン２", types: ["Side Quest","Dueling Peaks"] },
    { name: "ミニチャレンジ:燃える矢じりで貫いて！", types: ["Side Quest","Dueling Peaks"] },
    { name: "ミニチャレンジ:新妻は花よりダンゴ", types: ["Side Quest","Tabantha"] },
    { name: "力の試練 序位 ", types: ["Shrine","Guardian"] },
    { name: "畑のクワ", types: ["Equipment"] },
    { name: "マックス系料理", types: ["Cooking"] },
    { name: "カチコチ系料理", types: ["Cooking"] },
    { name: "マックス薬", types: ["Cooking"] },
    { name: "がんばり薬", types: ["Cooking"] },
    { name: "ヒンヤリ薬", types: ["Cooking"] },
    { name: "ゴーゴー薬", types: ["Cooking"] },
    { name: "スタミナ薬", types: ["Cooking"] },
    { name: "チカラ薬", types: ["Cooking"] },
    { name: "カチコチ薬", types: ["Cooking"] },
    { name: "しのび薬", types: ["Cooking"] },
    { name: "硬すぎ料理", types: ["Cooking"] },
    { name: "ウィズローブ討伐", types: ["Wizzrobe"] },
    { name: "イワロック討伐 (どの種でも可)", types: ["Rupee","Gems","Miniboss","Talus"] },
    { name: "イワロック(ノーマル)討伐", types: ["Rupee","Gems","Miniboss","Talus"] },
    { name: "朽ちたガーディアン討伐", types: ["Miniboss","Guardian"] },
    { name: "鹿に乗る", types: ["Horse"] },
    { name: "紫ルピー入手", types: ["Rupee"] },
    { name: "パーヤの日記を読む", types: ["Dueling Peaks"] },
    { name: "プルアの日記を読む", types: ["Hateno"] },
    { name: "ハテノ塔を起動", types: ["Tower","Hateno"] },
    { name: "フィローネの塔を起動", types: ["Tower","Faron"] },
    { name: "荒野の塔を起動", types: ["Tower","Wasteland"] },
    { name: "丘陵の塔を起動", types: ["Tower","Ridgeland"] },
    { name: "ミニチャレンジ 4個攻略", types: ["Side Quest"] },
    { name: "ロッド系武器入手", types: ["Equipment","Wizzrobe"] }
];
bingoList[5] = [
    { name: "ハテノ塔エリア コログのミ 6個", types: ["Korok","Hateno"] },
    { name: "フィローネの塔エリア コログのミ 6個", types: ["Korok","Faron"] },
    { name: "湖の塔エリア コログのミ 6個", types: ["Korok","Lake"] },
    { name: "荒野の塔エリア コログのミ 6個", types: ["Korok","Wasteland"] },
    { name: "ゲルドの塔エリア コログのミ 3個", types: ["Korok","Gerudo"] },
    { name: "丘陵の塔エリア コログのミ 6個", types: ["Korok","Ridgeland"] },
    { name: "ヘブラの塔エリア コログのミ 3個", types: ["Korok","Hebra","Cold Resistance"] },
    { name: "森林の塔エリア コログのミ 6個", types: ["Korok","Woodland"] },
    { name: "ラネールの塔エリア コログのミ 6個", types: ["Korok. Lanayru"] },
    { name: "平原の塔エリア コログのミ 6個", types: ["Korok","Central Hyrule"] },
    { name: "ラバーキャップ", types: ["Clothes","Rubber Gear","Faron"] },
    { name: "ラバースーツ", types: ["Clothes","Rubber Gear","Ridgeland"] },
    { name: "ラバータイツ", types: ["Clothes","Rubber Gear","Faron"] },
    { name: "忍びスーツ", types: ["Clothes","Stealth Gear","Rupee","Dueling Peaks"] },
    { name: "ミニチャレンジ:大盗賊ラムダの秘宝", types: ["Side Quest","Dueling Peaks"] },
    { name: "ミニチャレンジ:海に沈んだ財宝", types: ["Side Quest","Hateno"] },
    { name: "ミニチャレンジ:勇者の蓄え？", types: ["Side Quest","Hateno"] },
    { name: "ミニチャレンジ:雷怖い", types: ["Side Quest","Faron","Rubber Gear"] },
    { name: "ミニチャレンジ:その馬買い取ります！", types: ["Side Quest","Wasteland","Horse"] },
    { name: "ミニチャレンジ:新郎の汚名返上", types: ["Side Quest","Tabantha"] },
    { name: "ミニチャレンジ:大妖精さまのおふせ", types: ["Side Quest","Tabantha","Rupee","Great Fairy"] },
    { name: "ミニチャレンジ:風船よ舞い上がれ！", types: ["Side Quest","Woodland"] },
    { name: "ミニチャレンジ:水底に沈むお宝", types: ["Side Quest","Central Hyrule"] },
    { name: "ほこらチャレンジ:二つの輪", types: ["Shrine","Shrine Quest","Ridgeland"] },
    { name: "ブーメラン系武器入手", types: ["Equipment"] },
    { name: "“リザル”系武器入手", types: ["Equipment"] },
    { name: "船のオール", types: ["Equipment"] },
    { name: "“モリブリン”系武器入手", types: ["Equipment"] },
    { name: "木のモップ", types: ["Equipment"] },
    { name: "ヒンヤリ系料理", types: ["Cooking","Wasteland"] },
    { name: "エレキ系料理", types: ["Cooking"] },
    { name: "ピリ辛薬", types: ["Cooking"] },
    { name: "エレキ薬", types: ["Cooking"] },
    { name: "炎属性ウィズローブ討伐", types: ["Wizzrobe"] },
    { name: "雷属性ウィズローブ討伐", types: ["Wizzrobe"] },
    { name: "ヒノックス討伐 (どの種でも可)", types: ["Miniboss","Hinox"] },
    { name: "ヒノックス(赤)討伐", types: ["Miniboss","Hinox"] },
    { name: "ミニゲーム:鳥人間チャレンジ 500m以上滑空", types: ["Minigame","Ridgeland"] },
    { name: "ラネールの塔を起動", types: ["Tower","Lanayru"] },
    { name: "平原の塔を起動", types: ["Tower","Central Hyrule"] }
];
bingoList[6] = [
    { name: "タバンタの塔エリア コログのミ 6個", types: ["Korok","Tabantha"] },
    { name: "アッカレの塔エリア コログのミ 6個", types: ["Korok","Akkala"] },
    { name: "淑女防具一式", types: ["Clothes","Wasteland","Rupee"] },
    { name: "ハイリアのフード(赤色)", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "ハイリアのフード(黄色)", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "ハイリアのフード(紫色)", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "ハイリアのフード(緑色)", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "ハイリアのフード(薄黄色)", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "ハイリアのフード(灰色)", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "ミニチャレンジ:ココナ's キッチン３", types: ["Side Quest","Dueling Peaks"] },
    { name: "ミニチャレンジ:しのび草の君", types: ["Side Quest","Faron"] },
    { name: "ミニチャレンジ:馬に乗った荒くれ者", types: ["Side Quest","Lake"] },
    { name: "ミニチャレンジ:王家の白馬", types: ["Side Quest","Central Hyrule","Horse","Stamina"] },
    { name: "ほこらチャレンジ:呪われし石像", types: ["Shrine","Shrine Quest","Hateno"] },
    { name: "漁師のモリ", types: ["Equipment"] },
    { name: "同じ武器を3つ入手", types: ["Equipment"] },
    { name: "燃えず薬", types: ["Cooking"] },
    { name: "ゆでタマゴ", types: ["Cooking"] },
    { name: "氷属性ウィズローブ討伐", types: ["Wizzrobe"] },
    { name: "銀ルピー入手", types: ["Rupee"] },
    { name: "タバンタの塔を起動", types: ["Tower","Tabantha"] },
    { name: "森林の塔を起動", types: ["Tower","Woodland"] }
];
bingoList[7] = [
    { name: "コログのミ 15個", types: ["Korok"] },
    { name: "リトの羽毛服", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Tabantha"] },
    { name: "リトの羽毛ズボン", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Tabantha"] },
    { name: "ゾーラの兜", types: ["Clothes","Zora Gear","Lanayru"] },
    { name: "ゾーラの鎧", types: ["Clothes","Zora Gear","Lanayru"] },
    { name: "ハイリアのフード(青色)", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "ハイリアのフード(白色)", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "ハイリアのフード(薄青色)", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "ハイリアのフード(橙色)", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "ハイリアのフード(深紅色)", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "ハイリアのフード(茶色)", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "ミニチャレンジ:ココナ's キッチン４", types: ["Side Quest","Dueling Peaks"] },
    { name: "ミニチャレンジ:にっくきヒツジ泥棒", types: ["Side Quest","Hateno"] },
    { name: "ミニチャレンジ:暑さをしのぐ薬", types: ["Side Quest","Wasteland"] },
    { name: "ミニチャレンジ:飛び込みに目覚めた男", types: ["Side Quest","Lanayru"] },
    { name: "双子山の塔エリア 祠3基", types: ["Shrine","Dueling Peaks"] },
    { name: "ほこらチャレンジ:二本槍の獣", types: ["Shrine","Shrine Quest","Hateno","Horse"] },
    { name: "ほこらチャレンジ:馬宿の風景画", types: ["Shrine","Shrine Quest","Eldin"] },
    { name: "“ゾーラの”武器入手", types: ["Equipment"] },
    { name: "氷属性武器", types: ["Equipment"] },
    { name: "妖精の力水", types: ["Cooking"] },
    { name: "甘露煮肉", types: ["Cooking"] },
    { name: "岩塩焼きガニ", types: ["Cooking"] },
    { name: "がんばりの器 2つ入手", types: ["Shrine","Stamina"] },
    { name: "ロベリーの日記を読む", types: ["Akkala"] },
    { name: "ゲルドの塔を起動", types: ["Tower","Gerudo"] },
    { name: "オルディンの塔を起動", types: ["Tower","Eldin"] }
];
bingoList[8] = [
    { name: "始まりの塔エリア コログのミ 7個", types: ["Korok","Plateau"] },
    { name: "双子山の塔エリア コログのミ 9個", types: ["Korok","Dueling Peaks"] },
    { name: "ハテノ塔エリア コログのミ 9個", types: ["Korok","Hateno"] },
    { name: "湖の塔エリア コログのミ 9個", types: ["Korok","Lake"] },
    { name: "ゲルドの塔エリア コログのミ 6個", types: ["Korok","Gerudo"] },
    { name: "ヘブラの塔エリア コログのミ 6個", types: ["Korok","Hebra","Cold Resistance"] },
    { name: "オルディンの塔エリア コログのミ 6個", types: ["Korok","Eldin"] },
    { name: "平原の塔エリア コログのミ 9個", types: ["Korok","Central Hyrule"] },
    { name: "ハイリアのフード★", types: ["Clothes","Hylian Gear","Rupee","Great Fairy","Bokoblin"] },
    { name: "ハイリアの服★", types: ["Clothes","Hylian Gear","Rupee","Great Fairy","Bokoblin"] },
    { name: "ハイリアのズボン★", types: ["Clothes","Hylian Gear","Rupee","Great Fairy","Bokoblin"] },
    { name: "ハイリア兵防具一式", types: ["Clothes","Soldier Gear","Rupee","Hateno"] },
    { name: "雪よけの羽飾り", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Tabantha"] },
    { name: "耐火の石鎧", types: ["Clothes","Flame Gear","Eldin","Rupee"] },
    { name: "耐火の石靴", types: ["Clothes","Flame Gear","Eldin","Rupee"] },
    { name: "ハイリアのフード(黒色)", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "ハイリアのフード(紺色)", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "ハイリアのフード(桃色)", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "ミニチャレンジ:こおりの杖しれん", types: ["Side Quest","Woodland","Wizzrobe"] },
    { name: "湖の塔エリア 祠3基", types: ["Shrine","Lake"] },
    { name: "平原の塔エリア 祠3基", types: ["Shrine","Central Hyrule"] },
    { name: "ほこらチャレンジ:風を束ねて制する者よ", types: ["Shrine","Shrine Quest","Lanayru"] },
    { name: "“森人の”武器入手", types: ["Equipment"] },
    { name: "炎属性武器", types: ["Equipment"] },
    { name: "雷属性武器", types: ["Equipment"] },
    { name: "ガーディアンランス (+付きも可)", types: ["Equipment","Guardian"] },
    { name: "フルーツケーキ", types: ["Cooking"] },
    { name: "山盛串焼き魚", types: ["Cooking"] },
    { name: "ガーディアン(歩行型)討伐", types: ["Miniboss","Guardian"] },
    { name: "白馬を登録する", types: ["Horse","Central Hyrule","Stamina"] },
    { name: "キルトンに話しかける", types: ["Kilton","Akkala"] },
    { name: "金ルピー入手", types: ["Rupee"] },
    { name: "ハートの器 計5個", types: ["Shrine","Heart"] },
    { name: "ミニゲーム:鹿狩り 鹿を5頭狩る", types: ["Minigame","Hateno"] },
    { name: "ヘブラの塔を起動", types: ["Tower","Hebra","Cold Resistance"] }
];
bingoList[9] = [
    { name: "フィローネの塔エリア コログのミ 9個", types: ["Korok","Faron"] },
    { name: "丘陵の塔エリア コログのミ 9個", types: ["Korok","Ridgeland"] },
    { name: "ラネールの塔エリア コログのミ 9個", types: ["Korok. Lanayru"] },
    { name: "クライムシューズ", types: ["Clothes","Climbing Gear","Hateno"] },
    { name: "ミニチャレンジ:今日の晩御飯", types: ["Side Quest","Faron"] },
    { name: "ミニチャレンジ:秘密クラブの秘密", types: ["Side Quest","Wasteland","Radiant Gear","Desert Gear"] },
    { name: "ミニチャレンジ:ゲルドキャニオン失踪事件", types: ["Side Quest","Wasteland"] },
    { name: "ミニチャレンジ:ヒケシトカゲを捕まえて！", types: ["Side Quest","Eldin","Flame Gear"] },
    { name: "丘陵の塔エリア 祠3基", types: ["Shrine","Ridgeland"] },
    { name: "“双子の記憶”の両祠", types: ["Shrine","Shrine Quest","Dueling Peaks"] },
    { name: "ほこらチャレンジ:稲妻が開く試練", types: ["Shrine","Shrine Quest","Faron"] },
    { name: "ミニチャレンジ:コログ しれん うち1つ攻略", types: ["Shrine","Shrine Quest","Woodland"] },
    { name: "ガーディアンナイフ (+付きも可)", types: ["Equipment","Guardian"] },
    { name: "同じ盾を3つ入手", types: ["Equipment"] },
    { name: "同じ弓を3つ入手", types: ["Equipment"] },
    { name: "アップルパイ", types: ["Cooking","Tabantha"] },
    { name: "カレーピラフ", types: ["Cooking"] },
    { name: "青ヒノックス討伐", types: ["Miniboss","Hinox"] },
    { name: "ミニゲーム:ガンガンゴルフをクリア", types: ["Minigame","Woodland"] },
    { name: "アッカレの塔を起動", types: ["Tower","Akkala"] },
    { name: "フロドラの素材を入手", types: ["Dragon"] }
];
bingoList[10] = [
    { name: "荒野の塔エリア コログのミ 9個", types: ["Korok","Wasteland"] },
    { name: "タバンタの塔エリア コログのミ 9個", types: ["Korok","Tabantha"] },
    { name: "森林の塔エリア コログのミ 9個", types: ["Korok","Woodland"] },
    { name: "アッカレの塔エリア コログのミ 9個", types: ["Korok","Akkala"] },
    { name: "クライムバンダナ★", types: ["Clothes","Climbing Gear","Great Fairy"] },
    { name: "蛮族の服", types: ["Clothes","Barbarian Gear","Wasteland"] },
    { name: "ミニチャレンジ:奪われた漁場", types: ["Side Quest","Faron"] },
    { name: "ミニチャレンジ:巨大馬捕獲大作戦", types: ["Side Quest","Lake","Horse","Stamina"] },
    { name: "フィローネの塔エリア 祠3基", types: ["Shrine","Faron"] },
    { name: "荒野の塔エリア 祠3基", types: ["Shrine","Wasteland"] },
    { name: "力の試練 中位", types: ["Shrine","Guardian"] },
    { name: "ほこらチャレンジ:三本杉の秘密", types: ["Shrine","Shrine Quest","Hateno"] },
    { name: "ほこらチャレンジ:砂漠の試練", types: ["Shrine","Shrine Quest","Wastelands","Barbarian Gear"] },
    { name: "ほこらチャレンジ:消える？砂嵐", types: ["Shrine","Shrine Quest","Wastelands"] },
    { name: "ほこらチャレンジ:渦巻の中心へ", types: ["Shrine","Shrine Quest","Akkala"] },
    { name: "ほこらチャレンジ:ドクロの左目", types: ["Shrine","Shrine Quest","Akkala"] },
    { name: "ガーディアンシールド (+付きも可)", types: ["Equipment","Guardian"] },
    { name: "キノコミルクスープ", types: ["Cooking"] },
    { name: "ミニゲーム:雪玉ボウルで遊ぶ", types: ["Minigame","Hebra","Cold Resistance"] }
];
bingoList[11] = [
    { name: "コログのミ 20個", types: ["Korok"] },
    { name: "大妖精 2人解放", types: ["Rupee","Great Fairy"] },
    { name: "ハイリア兵の鎧★", types: ["Clothes","Soldier Gear","Rupee","Great Fairy"] },
    { name: "熱砂の鉢がね", types: ["Clothes","Desert Gear","Wasteland","Rupee"] },
    { name: "熱砂のズボン", types: ["Clothes","Desert Gear","Wasteland","Rupee"] },
    { name: "ラバーキャップ★", types: ["Clothes","Rubber Gear","Faron","Great Fairy"] },
    { name: "忍びマスク★", types: ["Clothes","Stealth Gear","Rupee","Great Fairy"] },
    { name: "忍びスーツ★", types: ["Clothes","Stealth Gear","Rupee","Great Fairy"] },
    { name: "忍びタイツ★", types: ["Clothes","Stealth Gear","Rupee","Great Fairy"] },
    { name: "忍び防具一式", types: ["Clothes","Stealth Gear","Rupee","Dueling Peaks"] },
    { name: "蛮族の兜", types: ["Clothes","Barbarian Gear","Akkala"] },
    { name: "ミニチャレンジ:愛しの人が望む物", types: ["Side Quest","Hateno"] },
    { name: "ハテノ塔エリア 祠3基", types: ["Shrine","Hateno"] },
    { name: "タバンタの塔エリア 祠3基", types: ["Shrine","Tabantha"] },
    { name: "森林の塔エリア 祠3基", types: ["Shrine","Woodland"] },
    { name: "アッカレの塔エリア 祠3基", types: ["Shrine","Akkala"] },
    { name: "ほこらチャレンジ:口を閉ざした戦士", types: ["Shrine","Shrine Quest","Wastelands"] },
    { name: "ほこらチャレンジ:雪山の日誌", types: ["Shrine","Shrine Quest","Wastelands","Cold Resistance"] },
    { name: "忘れられた神殿の祠", types: ["Shrine","Shrine Quest","Woodland"] },
    { name: "ほこらチャレンジ:暗闇の試練", types: ["Shrine","Shrine Quest","Woodland"] },
    { name: "ほこらチャレンジ:ゴロンのど根性ガケ", types: ["Shrine","Shrine Quest","Eldin"] },
    { name: "ほこらチャレンジ:孤島の試練", types: ["Shrine","Shrine Quest","Akkala","Barbarian Gear"] },
    { name: "“近衛の”武器入手", types: ["Equipment"] },
    { name: "上位ロッド入手", types: ["Equipment","Wizzrobe"] },
    { name: "ガーディアンアクス (+付きも可)", types: ["Equipment","Guardian"] },
    { name: "マモノケーキ", types: ["Cooking","Kilton"] },
    { name: "イチゴクレープ", types: ["Cooking","Tabantha"] },
    { name: "イワロック(希少)討伐", types: ["Rupee","Miniboss","Talus"] },
    { name: "巨馬を登録する", types: ["Horse","Lake","Stamina"] },
    { name: "熊に乗る", types: ["Horse","Stamina"] },
    { name: "スタルホースに乗る", types: ["Horse"] },
    { name: "2,000ルピー集める", types: ["Rupee"] },
    { name: "ハイラル王の手記を読む", types: ["Hyrule Castle"] },
    { name: "ボックリンとツーショット", types: ["Dueling Peaks","Camera"] },
    { name: "シーカーセンサー+", types: ["Camera","Rune Upgrade","Hateno"] }
];
bingoList[12] = [
    { name: "双子山の塔エリア コログのミ 12個", types: ["Korok","Dueling Peaks"] },
    { name: "オルディンの塔エリア コログのミ 9個", types: ["Korok","Eldin"] },
    { name: "平原の塔エリア コログのミ 12個", types: ["Korok","Central Hyrule"] },
    { name: "英傑の服", types: ["Clothes","Champion","Camera"] },
    { name: "ハイリア兵の兜★", types: ["Clothes","Soldier Gear","Rupee","Great Fairy"] },
    { name: "ハイリア兵のすねあて★", types: ["Clothes","Soldier Gear","Rupee","Great Fairy"] },
    { name: "熱砂の肩当て", types: ["Clothes","Desert Gear","Wasteland","Rupee"] },
    { name: "ラバースーツ★", types: ["Clothes","Rubber Gear","Ridgeland","Great Fairy"] },
    { name: "ラバータイツ★", types: ["Clothes","Rubber Gear","Faron","Great Fairy"] },
    { name: "ゾーラのすねあて", types: ["Clothes","Zora Gear","Lanayru","Camera"] },
    { name: "コハクの耳飾り", types: ["Clothes","Gems","Rupee","Wasteland"] },
    { name: "ミニチャレンジ:王家秘伝のレシピ", types: ["Side Quest","Central Hyrule","Cooking"] },
    { name: "ほこらチャレンジ 2つ攻略", types: ["Shrine","Shrine Quest"] },
    { name: "ほこらチャレンジ:七人の英雄", types: ["Shrine","Shrine Quest","Wastelands"] },
    { name: "ほこらチャレンジ:絶壁の文様", types: ["Shrine","Shrine Quest","Gerudo","Cold Resistance"] },
    { name: "ほこらチャレンジ:影が示す先に", types: ["Shrine","Shrine Quest","Gerudo"] },
    { name: "ウツシエの記憶 1つ回収", types: ["Camera"] },
    { name: "ゼルダの日録を読む", types: ["Hyrule Castle"] },
    { name: "カッシーワとツーショット", types: ["Camera"] },
    { name: "ラネールの塔エリア 祠3基", types: ["Shrine","Lanayru"] },
    { name: "ミニチャレンジ:ウツシエとシーカーセンサー", types: ["Side Quest","Hateno","Camera"] },
    { name: "ミニチャレンジ:ホタル ノ ヒカリ", types: ["Side Quest","Dueling Peaks","Heirloom","Camera"] }
];
bingoList[13] = [
    { name: "ハテノ塔エリア コログのミ 12個", types: ["Korok","Hateno"] },
    { name: "湖の塔エリア コログのミ 12個", types: ["Korok","Lake"] },
    { name: "丘陵の塔エリア コログのミ 12個", types: ["Korok","Ridgeland"] },
    { name: "ヘブラの塔エリア コログのミ 9個", types: ["Korok","Hebra","Cold Resistance"] },
    { name: "耐火の石兜", types: ["Clothes","Flame Gear","Eldin","Rupee"] },
    { name: "ゾーラの鎧★", types: ["Clothes","Zora Gear","Great Fairy","Lizalfos"] },
    { name: "蛮族の腰巻き", types: ["Clothes","Barbarian Gear","Hebra"] },
    { name: "ヘブラの塔エリア 祠3基", types: ["Shrine","Hebra","Cold Resistance"] },
    { name: "オルディンの塔エリア 祠3基", types: ["Shrine","Eldin"] },
    { name: "ほこらチャレンジ:大蛇喰らいし龍", types: ["Shrine","Shrine Quest","Lake","Dragon"] },
    { name: "ほこらチャレンジ:ガマンくらべ", types: ["Shrine","Shrine Quest","Gerudo"] },
    { name: "ガチロック討伐", types: ["Rupee","Gems","Miniboss","Talus","Cold Resistance"] },
    { name: "ガーディアン(砲台型)討伐", types: ["Miniboss","Guardian","Hyrule Castle"] },
    { name: "ハイラル図鑑 生き物 5種登録", types: ["Camera","Compendium"] },
    { name: "ハイラル図鑑 魔物 5種登録", types: ["Camera","Compendium"] },
    { name: "ハイラル図鑑 武器 5種登録", types: ["Camera","Compendium"] },
    { name: "シドとツーショット", types: ["Lanayru","Camera"] },
    { name: "オルドラの素材を入手", types: ["Dragon"] },
    { name: "ミニゲーム:盾サーフィン 初級をクリア", types: ["Minigame","Hebra","Cold Resistance"] },
    { name: "スノーブーツ", types: ["Clothes","Boots","Side Quest","Gerudo","Camera"] },
    { name: "マグロック討伐", types: ["Rupee","Gems","Miniboss","Talus","Eldin"] }
];
bingoList[14] = [
    { name: "コログのミ 25個", types: ["Korok"] },
    { name: "フィローネの塔エリア コログのミ 12個", types: ["Korok","Faron"] },
    { name: "ゲルドの塔エリア コログのミ 9個", types: ["Korok","Gerudo"] },
    { name: "タバンタの塔エリア コログのミ 12個", types: ["Korok","Tabantha"] },
    { name: "森林の塔エリア コログのミ 12個", types: ["Korok","Woodland"] },
    { name: "アッカレの塔エリア コログのミ 12個", types: ["Korok","Akkala"] },
    { name: "ラネールの塔エリア コログのミ 12個", types: ["Korok. Lanayru"] },
    { name: "馬神マーロン解放", types: ["Lake","Rupee"] },
    { name: "ミニチャレンジ:宝石はお好き？", types: ["Side Quest","Wasteland","Gems"] },
    { name: "ゾーラの兜★", types: ["Clothes","Zora Gear","Great Fairy","Lizalfos"] },
    { name: "夜光マスク", types: ["Clothes","Radiant Gear","Rupee","Gems","Wasteland"] },
    { name: "夜光スーツ", types: ["Clothes","Radiant Gear","Rupee","Gems","Wasteland"] },
    { name: "夜光タイツ", types: ["Clothes","Radiant Gear","Rupee","Gems","Wasteland"] },
    { name: "トパーズの耳飾り", types: ["Clothes","Gems","Rupee","Wasteland"] },
    { name: "ミニチャレンジ:寒い時にはカレーを！", types: ["Side Quest","Tabantha","Eldin"] },
    { name: "祠 10基攻略", types: ["Shrine"] },
    { name: "ゲルドの塔エリア 祠3基", types: ["Shrine","Gerudo","Cold Resistance"] },
    { name: "ほこらチャレンジ:石碑のかけら探し", types: ["Shrine","Shrine Quest","Faron","Camera"] },
    { name: "ウツシエの記憶 2つ回収", types: ["Camera"] },
    { name: "黒ヒノックス討伐", types: ["Miniboss","Hinox"] },
    { name: "スタルヒノックス討伐", types: ["Miniboss","Hinox"] },
    { name: "ガーディアン(飛行型)討伐", types: ["Miniboss","Guardian"] },
    { name: "がんばりの器 3つ入手", types: ["Shrine","Stamina"] },
    { name: "ネルドラの素材を入手", types: ["Hateno","Cold Resistance","Dragon"] },
    { name: "リモコン爆弾+", types: ["Camera","Rune Upgrade","Hateno"] },
    { name: "シーカータワー 4基起動", types: ["Tower"] },
    { name: "ミニチャレンジ 11個攻略", types: ["Side Quest"] }
];
bingoList[15] = [
    { name: "荒野の塔エリア コログのミ 12個", types: ["Korok","Wasteland"] },
    { name: "リトの羽毛服★", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Great Fairy"] },
    { name: "リトの羽毛ズボン★", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Great Fairy"] },
    { name: "リト防具一式", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Tabantha"] },
    { name: "耐火の石靴★", types: ["Clothes","Flame Gear","Eldin","Rupee","Great Fairy"] },
    { name: "クライムシューズ★", types: ["Clothes","Climbing Gear","Great Fairy"] },
    { name: "サファイアの頭飾り", types: ["Clothes","Gems","Rupee","Wasteland"] },
    { name: "ルビーの頭飾り", types: ["Clothes","Gems","Rupee","Wasteland"] },
    { name: "ボコブリンマスク", types: ["Clothes","Kilton"] },
    { name: "ミニチャレンジ:デスマウンテンの秘宝", types: ["Side Quest","Eldin"] },
    { name: "ミニチャレンジ:ライネル調査", types: ["Side Quest","Lanayru","Camera","Zora Gear"] },
    { name: "ミニチャレンジ:ハイラル城に眠る武器", types: ["Side Quest","Hyrule Castle"] },
    { name: "ほこらチャレンジ:野生の試練", types: ["Shrine","Shrine Quest","Faron"] },
    { name: "ほこらチャレンジ:巨人三兄弟の秘密", types: ["Shrine","Shrine Quest","Faron","Hinox"] },
    { name: "ほこらチャレンジ:おっきなお山のおっきな木", types: ["Shrine","Shrine Quest","Hebra","Cold Resistance"] },
    { name: "ほこらチャレンジ:断崖の試練", types: ["Shrine","Shrine Quest","Hebra","Cold Resistance","Barbarian Gear"] },
    { name: "風斬り刀", types: ["Equipment","Wasteland"] },
    { name: "ライネル討伐", types: ["Miniboss","Lynel"] },
    { name: "モルドラジーク討伐", types: ["Miniboss","Molduga","Wasteland"] },
    { name: "ハート 計6個", types: ["Shrine","Heart"] },
    { name: "ルージュとツーショット", types: ["Wasteland","Camera"] },
    { name: "火の中で自撮り", types: ["Eldin","Camera"] },
    { name: "ビタロック+", types: ["Camera","Rune Upgrade","Hateno"] },
    { name: "ハイラル図鑑 武器 10種登録", types: ["Camera","Compendium"] }
];
bingoList[16] = [
    { name: "双子山の塔エリア コログのミ 15個", types: ["Korok","Dueling Peaks"] },
    { name: "平原の塔エリア コログのミ 15個", types: ["Korok","Central Hyrule"] },
    { name: "英傑の服★", types: ["Clothes","Champion","Camera","Great Fairy"] },
    { name: "雪よけの羽飾り★", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Great Fairy"] },
    { name: "ラバー防具一式", types: ["Clothes","Rubber Gear","Faron","Ridgeland"] },
    { name: "耐火の石鎧★", types: ["Clothes","Flame Gear","Eldin","Rupee","Great Fairy"] },
    { name: "オパールの耳飾り", types: ["Clothes","Gems","Rupee","Wasteland"] },
    { name: "ミニチャレンジ:モルドラジークの肝", types: ["Side Quest","Wasteland","Molduga"] },
    { name: "ミニチャレンジ:免許皆伝への道", types: ["Side Quest","Eldin","Talus"] },
    { name: "ミニチャレンジ:小さな妹の大きな願い", types: ["Side Quest","Akkala"] },
    { name: "ミニチャレンジ:ぴかぴかのルミー しれん", types: ["Side Quest","Wasteland","Camera"] },
    { name: "ミニチャレンジ 12個攻略", types: ["Side Quest"] },
    { name: "ハイラル図鑑 生き物 10種登録", types: ["Camera","Compendium"] },
    { name: "ハイラル図鑑 魔物 10種登録", types: ["Camera","Compendium"] }
];
bingoList[17] = [
    { name: "ハテノ塔エリア コログのミ 15個", types: ["Korok","Hateno"] },
    { name: "湖の塔エリア コログのミ 15個", types: ["Korok","Lake"] },
    { name: "ゲルドの塔エリア コログのミ 12個", types: ["Korok","Gerudo"] },
    { name: "丘陵の塔エリア コログのミ 15個", types: ["Korok","Ridgeland"] },
    { name: "ヘブラの塔エリア コログのミ 12個", types: ["Korok","Hebra","Cold Resistance"] },
    { name: "オルディンの塔エリア コログのミ 12個", types: ["Korok","Eldin"] },
    { name: "熱砂の鉢がね★", types: ["Clothes","Desert Gear","Wasteland","Rupee","Great Fairy"] },
    { name: "熱砂の肩当て★", types: ["Clothes","Desert Gear","Wasteland","Rupee","Great Fairy"] },
    { name: "熱砂のズボン★", types: ["Clothes","Desert Gear","Wasteland","Rupee","Great Fairy"] },
    { name: "サンドブーツ", types: ["Clothes","Boots","Side Quest","Gerudo"] },
    { name: "ミニチャレンジ:八人目の英雄", types: ["Side Quest","Wasteland","Gerudo","Boots","Cold Resistance","Camera"] },
    { name: "祠 11基攻略", types: ["Shrine"] },
    { name: "ほこらチャレンジ 5つ攻略", types: ["Shrine","Shrine Quest"] },
    { name: "ほこらチャレンジ:ガーディアンを見たい！", types: ["Shrine","Shrine Quest","Lake","Camera","Guardian"] },
    { name: "ほこらチャレンジ:力の泉の言い伝え", types: ["Shrine","Shrine Quest","Akkala","Dragon"] },
    { name: "“ライネルの”武器入手", types: ["Equipment","Lynel"] },
    { name: "3属性の武器を1つずつ入手", types: ["Equipment"] },
    { name: "ミニゲーム:飛行訓練 的を20個射抜く", types: ["Minigame","Tabantha","Cold Resistance"] },
    { name: "シーカータワー 5基起動", types: ["Tower"] },
    { name: "ハイラル図鑑 武器 15種登録", types: ["Camera","Compendium"] }
];
bingoList[18] = [
    { name: "ハイラル図鑑 生き物 15種登録", types: ["Camera","Compendium"] },
    { name: "ハイラル図鑑 魔物 15種登録", types: ["Camera","Compendium"] },
    { name: "コログのミ 30個", types: ["Korok"] },
    { name: "フィローネの塔エリア コログのミ 15個", types: ["Korok","Faron"] },
    { name: "アッカレの塔エリア コログのミ 15個", types: ["Korok","Akkala"] },
    { name: "ラネールの塔エリア コログのミ 15個", types: ["Korok. Lanayru"] },
    { name: "熱砂防具一式", types: ["Clothes","Desert Gear","Wasteland","Rupee"] },
    { name: "耐火の石兜★", types: ["Clothes","Flame Gear","Eldin","Rupee","Great Fairy"] },
    { name: "ゾーラのすねあて★", types: ["Clothes","Zora Gear","Great Fairy","Lizalfos","Camera"] },
    { name: "夜光マスク★", types: ["Clothes","Radiant Gear","Rupee","Gems","Great Fairy"] },
    { name: "スノーブーツ★", types: ["Clothes","Boots","Side Quest","Great Fairy","Camera"] },
    { name: "ミニチャレンジ:解放 さらなる力", types: ["Side Quest","Hateno","Camera"] },
    { name: "ミニチャレンジ:求ム！不審者情報", types: ["Side Quest","Akkala","Kilton","Camera"] },
    { name: "祠 12基攻略", types: ["Shrine"] },
    { name: "ほこらチャレンジ:ラネール山のお宝を探れ！", types: ["Shrine","Shrine Quest","Hateno","Cold Resistance","Dragon"] },
    { name: "ウツシエの記憶 3つ回収", types: ["Camera"] },
    { name: "ハイリアの盾", types: ["Miniboss","Hinox","Hyrule Castle"] },
    { name: "山のヌシに乗る", types: ["Horse","Ridgeland","Stamina"] },
    { name: "家を買う", types: ["Hateno","Rupee"] },
    { name: "力の試練 極位", types: ["Shrine","Guardian"] }
];
bingoList[19] = [
    { name: "荒野の塔エリア コログのミ 15個", types: ["Korok","Wasteland"] },
    { name: "タバンタの塔エリア コログのミ 15個", types: ["Korok","Tabantha"] },
    { name: "森林の塔エリア コログのミ 15個", types: ["Korok","Woodland"] },
    { name: "夜光スーツ★", types: ["Clothes","Radiant Gear","Rupee","Gems","Great Fairy"] },
    { name: "夜光タイツ★", types: ["Clothes","Radiant Gear","Rupee","Gems","Great Fairy"] },
    { name: "コハクの耳飾り★", types: ["Clothes","Gems","Rupee","Great Fairy"] },
    { name: "ミニチャレンジ:骨の馬の絵", types: ["Side Quest","Hebra","Camera"] },
    { name: "ほこらチャレンジ:盗まれた宝珠", types: ["Shrine","Shrine Quest","Dueling Peaks","Heirloom","Camera"] },
    { name: "ほこらチャレンジ:弟はいずこ？", types: ["Shrine","Shrine Quest","Eldin"] },
    { name: "神獣系メインチャレンジ 1つ攻略", types: ["Divine Beast"] },
    { name: "メインチャレンジ:風の神獣ヴァ・メドー", types: ["Divine Beast","Tabantha","Cold Resistance"] },
    { name: "リーバルの猛り", types: ["Divine Beast","Tabantha","Cold Resistance"] },
    { name: "闘技場のライネル討伐", types: ["Miniboss","Lynel","Central Hyrule"] },
    { name: "シーカータワー 6基起動", types: ["Tower"] },
    { name: "ミニチャレンジ 13個攻略", types: ["Side Quest"] },
    { name: "クライムグローブ", types: ["Clothes","Climbing Gear","Hateno"] }
];
bingoList[20] = [
    { name: "ゲルドの塔エリア コログのミ 15個", types: ["Korok","Gerudo"] },
    { name: "ヘブラの塔エリア コログのミ 15個", types: ["Korok","Hebra","Cold Resistance"] },
    { name: "オルディンの塔エリア コログのミ 15個", types: ["Korok","Eldin"] },
    { name: "ゾーラ防具一式", types: ["Clothes","Zora Gear","Lanayru","Camera"] },
    { name: "蛮族の兜★", types: ["Clothes","Barbarian Gear","Great Fairy","Lynel"] },
    { name: "蛮族の服★", types: ["Clothes","Barbarian Gear","Great Fairy","Lynel"] },
    { name: "トパーズの耳飾り★", types: ["Clothes","Gems","Rupee","Great Fairy"] },
    { name: "ダイヤの頭飾り", types: ["Clothes","Gems","Rupee","Wasteland"] },
    { name: "ミニチャレンジ:忘れられた剣", types: ["Side Quest","Wasteland","Gerudo","Boots","Cold Resistance","Camera"] },
    { name: "ミニチャレンジ:キールを探して！", types: ["Side Quest","Tabantha"] },
    { name: "ミニチャレンジ:宝石インポーター", types: ["Side Quest","Eldin","Gems"] },
    { name: "ミニチャレンジ:もう一人の研究者", types: ["Side Quest","Akkala","Camera"] },
    { name: "ほこらチャレンジ 6つ攻略", types: ["Shrine","Shrine Quest"] },
    { name: "メインチャレンジ:水の神獣ヴァ・ルッタ", types: ["Divine Beast","Lanayru"] },
    { name: "ミファーの祈り", types: ["Divine Beast","Lanayru"] },
    { name: "ウツシエの記憶 4つ回収", types: ["Camera"] },
    { name: "がんばりの器 4つ入手", types: ["Shrine","Stamina"] },
    { name: "ハイラル図鑑 武器 20種登録", types: ["Camera","Compendium"] }
];
bingoList[21] = [
    { name: "ハイラル図鑑 生き物 20種登録", types: ["Camera","Compendium"] },
    { name: "ハイラル図鑑 魔物 20種登録", types: ["Camera","Compendium"] },
    { name: "コログのミ 35個", types: ["Korok"] },
    { name: "大妖精 3人解放", types: ["Rupee","Great Fairy"] },
    { name: "耐火防具一式", types: ["Clothes","Flame Gear","Eldin","Rupee"] },
    { name: "蛮族の腰巻き★", types: ["Clothes","Barbarian Gear","Great Fairy","Lynel"] },
    { name: "夜光防具一式", types: ["Clothes","Radiant Gear","Rupee","Gems","Wasteland"] },
    { name: "オパールの耳飾り★", types: ["Clothes","Gems","Rupee","Great Fairy"] },
    { name: "サファイアの頭飾り★", types: ["Clothes","Gems","Rupee","Great Fairy"] },
    { name: "ルビーの頭飾り★", types: ["Clothes","Gems","Rupee","Great Fairy"] },
    { name: "祠 13基攻略", types: ["Shrine"] },
    { name: "ほこらチャレンジ 7つ攻略", types: ["Shrine","Shrine Quest"] },
    { name: "ほこらチャレンジ:うるわしの美酒を求めて…", types: ["Shrine","Shrine Quest","Wastelands"] },
    { name: "ほこらチャレンジ:リトの兄弟岩", types: ["Shrine","Shrine Quest","Tabantha"] },
    { name: "ほこらチャレンジ:リトの詩の謎", types: ["Shrine","Shrine Quest","Tabantha"] },
    { name: "ウツシエの記憶 5つ回収", types: ["Camera"] },
    { name: "ボヨーンハンマー", types: ["Equipment","Kilton"] },
    { name: "ハート 計7個", types: ["Shrine","Heart"] },
    { name: "シーカーストーン 全アイテム強化", types: ["Camera","Rune Upgrade","Hateno"] },
    { name: "ほこらチャレンジ:英傑祭の詩", types: ["Shrine","Shrine Quest","Lanayru"] }
];
bingoList[22] = [
    { name: "ミニチャレンジ:ハイラルのなぞなぞしれん", types: ["Side Quest","Woodland","Lynel"] },
    { name: "ミニチャレンジ:雨ときどきカエル", types: ["Side Quest","Lanayru"] },
    { name: "ミニチャレンジ:夜光石採集", types: ["Side Quest","Lanayru","Gems"] },
    { name: "ミニチャレンジ:流された嫁", types: ["Side Quest","Lanayru"] },
    { name: "祠 14基攻略", types: ["Shrine"] },
    { name: "ほこらチャレンジ 8つ攻略", types: ["Shrine","Shrine Quest"] },
    { name: "シーカータワー 7基起動", types: ["Tower"] },
    { name: "ミニチャレンジ 14個攻略", types: ["Side Quest"] }
];
bingoList[23] = [
    { name: "コログのミ 40個", types: ["Korok"] },
    { name: "ミニチャレンジ:ブリザー谷のガチロック", types: ["Side Quest","Tabantha","Hebra","Cold Resistance"] },
    { name: "ミニチャレンジ:ラルス池の巨人討伐", types: ["Side Quest","Lanayru","Hinox"] },
    { name: "祠 15基攻略", types: ["Shrine"] },
    { name: "メインチャレンジ:炎の神獣ヴァ・ルーダニア", types: ["Divine Beast","Eldin"] },
    { name: "ダルケルの護り", types: ["Divine Beast","Eldin"] },
    { name: "ウツシエの記憶 6つ回収", types: ["Camera"] },
    { name: "英傑武器を作り直す", types: ["Equipment","Divine Beast","Gems"] },
    { name: "クライムグローブ★", types: ["Clothes","Climbing Gear","Great Fairy"] },
    { name: "シーカータワー 8基起動", types: ["Tower"] }
];
bingoList[24] = [
    { name: "コログのミ 45個", types: ["Korok"] },
    { name: "ミニチャレンジ:巨大クジラの化石", types: ["Side Quest","Camera"] },
    { name: "祠 16基攻略", types: ["Shrine"] },
    { name: "メインチャレンジ:雷の神獣ヴァ・ナボリス", types: ["Divine Beast","Wasteland"] },
    { name: "ウルボザの怒り", types: ["Divine Beast","Wasteland"] },
    { name: "ガノン討伐", types: ["Hyrule Castle"] },
    { name: "シーカータワー 9基起動", types: ["Tower"] },
    { name: "クライム防具一式", types: ["Clothes","Climbing Gear"] }
];
bingoList[25] = [
    { name: "コログのミ 50個", types: ["Korok"] },
    { name: "ミニチャレンジ:ゾーラの石碑を探して", types: ["Side Quest","Lanayru"] },
    { name: "神獣系メインチャレンジ 2つ攻略", types: ["Divine Beast"] },
    { name: "ミニチャレンジ:バレッタを探して", types: ["Side Quest","Wasteland"] },
    { name: "ミニチャレンジ:犯人はだれだ！", types: ["Side Quest","Wasteland"] },
    { name: "ほこらチャレンジ:無敗の女王", types: ["Shrine","Shrine Quest","Wastelands"] },
    { name: "シーカータワー 10基起動", types: ["Tower"] },
    { name: "ミニチャレンジ 15個攻略", types: ["Side Quest"] },
    { name: "蛮族防具一式", types: ["Clothes","Barbarian Gear"] }
];
module.exports = bingoList;

// This board was translated by Phanty.
// https://twitter.com/i/notifications
// https://twitter.com/evolchronicle
