var bingoList = [];
bingoList[1] = [
    { name: "Capuche Hylienne", types: ["Clothes","Hylian Gear","Rupee"] },
    { name: "Tunique Hylienne", types: ["Clothes","Hylian Gear","Rupee","Rupee"] },
    { name: "Doublet", types: ["Clothes","Cold Resistance","Hateno"] },
    { name: "3 Noix Korogu du Plateau du Prélude", types: ["Korok","Plateau"] },
    { name: "Pantalon Hylien", types: ["Clothes","Hylian Gear","Rupee"] },
    { name: "N'importe quel équipement 'boko'", types: ["Equipment"] },
    { name: "3 Noix Korogu des Monts Géminés", types: ["Korok","Dueling Peaks"] },
    { name: "3 Noix Korogu de la Tour de la plaine", types: ["Korok","Central Hyrule"] }
];
bingoList[2] = [
    { name: "5 Noix Korogu", types: ["Korok"] },
    { name: "3 Noix Korogu d'Elimith", types: ["Korok","Hateno"] },
    { name: "3 Noix Korogu de Firone", types: ["Korok","Faron"] },
    { name: "3 Noix Korogu des Collines d'Hyrule", types: ["Korok","Ridgeland"] },
    { name: "N'importe quel équipement 'rouillé'", types: ["Equipment"] },
    { name: "N'importe quel plat Enduro", types: ["Cooking","Stamina"] },
    { name: "Donner un scarabée à Terry", types: ["Horse"] },
    { name: "Enregistrer un cheval", types: ["Horse"] },
    { name: "Énerver une cocotte", types: ["Cucco"] },
    { name: "Activer la tour des Monts Géminés", types: ["Tower","Dueling Peaks"] },
    { name: "Une Louche", types: ["Equipment"] },
    { name: "1 quête 'Les Recettes de Coconoa'", types: ["Side Quest","Dueling Peaks"] },
    { name: "N'importe quel plat Tempo", types: ["Cooking"] },
    { name: "N'importe quel plat Picpic", types: ["Cooking","Cold Resistance"] }
];
bingoList[3] = [
    { name: "5 Noix Korogu du Plateau du Prélude", types: ["Korok","Plateau"] },
    { name: "6 Noix Korogu des Monts Géminés", types: ["Korok","Dueling Peaks"] },
    { name: "3 Noix Korogu de la Tour du Lac", types: ["Korok","Lake"] },
    { name: "3 Noix Korogu des Landes Sauvages", types: ["Korok","Wasteland"] },
    { name: "3 Noix Korogu de la Tour Sylvestre", types: ["Korok","Woodland"] },
    { name: "3 Noix Korogu de Lanelle", types: ["Korok","Lanayru"] },
    { name: "Quête secondaire 'De Précieux Maracas'", types: ["Side Quest","Dueling Peaks"] },
    { name: "Quête secondaire 'Un camarade pour Pricota'", types: ["Side Quest","Dueling Peaks"] },
    { name: "Quête secondaire 'Chevaux Sauvages'", types: ["Side Quest","Dueling Peaks","Horse"] },
    { name: "Quête secondaire 'La Statue Maléfique'", types: ["Side Quest","Hateno"] },
    { name: "Quête de sanctuaire 'Pas sur les fleurs!'", types: ["Shrine","Shrine Quest","Dueling Peaks"] },
    { name: "N'importe quel plat vitalis", types: ["Cooking","Stamina"] },
    { name: "N'importe quel plat lame", types: ["Cooking"] },
    { name: "N'importe quel plat silencio", types: ["Cooking"] },
    { name: "Plat douteux", types: ["Cooking"] },
    { name: "Ouvrir 2 coffres de camp bokoblin", types: ["Plateau"] },
    { name: "Sauver un voyageur en péril", types: ["Monster"] },
    { name: "Activer la tour du lac", types: ["Tower","Lake"] },
    { name: "3 Noix Korogus de Tabanta", types: ["Korok","Tabantha"] },
    { name: "N'importe quel bras de stalfos", types: ["Equipment"] },
    { name: "3 quêtes secondaires", types: ["Side Quest"] }
];
bingoList[4] = [
    { name: "10 Noix Korogu", types: ["Korok"] },
    { name: "3 Noix Korogu d'Ordinn", types: ["Korok","Eldin"] },
    { name: "3 Noix Korogu d'Akkala", types: ["Korok","Akkala"] },
    { name: "Payer 1 grande fée", types: ["Rupee","Great Fairy"] },
    { name: "Armure Hylienne au complet", types: ["Clothes","Hylian Gear","Rupee"] },
    { name: "Casque de soldat", types: ["Clothes","Soldier Gear","Rupee","Hateno"] },
    { name: "Armure de soldat", types: ["Clothes","Soldier Gear","Rupee","Hateno"] },
    { name: "Jambières de soldat", types: ["Clothes","Soldier Gear","Rupee","Hateno"] },
    { name: "Masque furtif", types: ["Clothes","Stealth Gear","Rupee","Dueling Peaks"] },
    { name: "Chausses furtives", types: ["Clothes","Stealth Gear","Rupee","Dueling Peaks"] },
    { name: "Bandana d'escalade", types: ["Clothes","Climbing Gear","Dueling Peaks"] },
    { name: "Quête secondaire 'Les cocottes perdues'", types: ["Side Quest","Dueling Peaks","Heirloom"] },
    { name: "2 quêtes 'Les recettes de Coconoa'", types: ["Side Quest","Dueling Peaks"] },
    { name: "Quête secondaire 'Les flèches de feu'", types: ["Side Quest","Dueling Peaks"] },
    { name: "Quête secondaire 'La mariée déprimée'", types: ["Side Quest","Tabantha"] },
    { name: "1 sanctuaire 'Épreuve basique de force'", types: ["Shrine","Guardian"] },
    { name: "Houe", types: ["Equipment"] },
    { name: "N'importe quel plat max", types: ["Cooking"] },
    { name: "N'importe quel plat armo", types: ["Cooking"] },
    { name: "Remède Max", types: ["Cooking"] },
    { name: "Remède enduro", types: ["Cooking"] },
    { name: "Remède glagla", types: ["Cooking"] },
    { name: "Remède tempo", types: ["Cooking"] },
    { name: "Remède vitalis", types: ["Cooking"] },
    { name: "Remède lame", types: ["Cooking"] },
    { name: "Remède armo", types: ["Cooking"] },
    { name: "Remède silencio", types: ["Cooking"] },
    { name: "Plat brise-dent", types: ["Cooking"] },
    { name: "Tuer 1 Sorcier de n'importe quel type", types: ["Wizzrobe"] },
    { name: "Tuer 1 Lithorok de n'importe quel type", types: ["Rupee","Gems","Miniboss","Talus"] },
    { name: "Tuer 1 Lithorok normal", types: ["Rupee","Gems","Miniboss","Talus"] },
    { name: "Tuer 1 Gardien détérioré", types: ["Miniboss","Guardian"] },
    { name: "Monter un cerf", types: ["Horse"] },
    { name: "Obtenir un rubis violet", types: ["Rupee"] },
    { name: "Lire le journal de Pahya", types: ["Dueling Peaks"] },
    { name: "Lire le journal de Pru'Ha", types: ["Hateno"] },
    { name: "Activer la Tour d'Elimith", types: ["Tower","Hateno"] },
    { name: "Activer la Tour de Firone", types: ["Tower","Faron"] },
    { name: "Activer la Tour des Landes Sauvages", types: ["Tower","Wasteland"] },
    { name: "Activer la Tour des Collines", types: ["Tower","Ridgeland"] },
    { name: "4 Quêtes Secondaires", types: ["Side Quest"] },
    { name: "N'importe quelle Baguette de Sorcier", types: ["Equipment","Wizzrobe"] }
];
bingoList[5] = [
    { name: "6 Noix Korogu d'Elimith", types: ["Korok","Hateno"] },
    { name: "6 Noix Korogu de Firone", types: ["Korok","Faron"] },
    { name: "6 Noix Korogu de la Tour du Lac", types: ["Korok","Lake"] },
    { name: "6 Noix Korogu des Landes Sauvages", types: ["Korok","Wasteland"] },
    { name: "3 Noix Korogu Gerudo", types: ["Korok","Gerudo"] },
    { name: "6 Noix Korogu des Collines", types: ["Korok","Ridgeland"] },
    { name: "3 Noix Korogu d'Hebra", types: ["Korok","Hebra","Cold Resistance"] },
    { name: "6 Noix Korogu Sylvestres", types: ["Korok","Woodland"] },
    { name: "6 Noix Korogu de Lanelle", types: ["Korok. Lanayru"] },
    { name: "6 Noix Korogu de la Tour de la Plaine", types: ["Korok","Central Hyrule"] },
    { name: "Casque Isolant", types: ["Clothes","Rubber Gear","Faron"] },
    { name: "Combinaison Isolante", types: ["Clothes","Rubber Gear","Ridgeland"] },
    { name: "Pantalon Isolant", types: ["Clothes","Rubber Gear","Faron"] },
    { name: "Combinaison furtive (torse)", types: ["Clothes","Stealth Gear","Rupee","Dueling Peaks"] },
    { name: "Quête secondaire 'Le tréso de Lambda'", types: ["Side Quest","Dueling Peaks"] },
    { name: "Quête secondaire 'Tréso Englouti'", types: ["Side Quest","Hateno"] },
    { name: "Quête secondaire 'La cachette du Héros'", types: ["Side Quest","Hateno"] },
    { name: "Quête secondaire 'Peur panique de la foudre'", types: ["Side Quest","Faron","Rubber Gear"] },
    { name: "Quête secondaire 'Le Cheval Géant'", types: ["Side Quest","Wasteland","Horse"] },
    { name: "Quête secondaire 'Lune de miel en péril'", types: ["Side Quest","Tabantha"] },
    { name: "Quête secondaire 'L'offrance à la grande fée'", types: ["Side Quest","Tabantha","Rupee","Great Fairy"] },
    { name: "Quête secondaire 'Volent, volent les Ballons!'", types: ["Side Quest","Woodland"] },
    { name: "Quête secondaire 'Un tréso au fond du lit'", types: ["Side Quest","Central Hyrule"] },
    { name: "Quête de sanctuaire 'Les deux roues'", types: ["Shrine","Shrine Quest","Ridgeland"] },
    { name: "N'importe quel boomerang", types: ["Equipment"] },
    { name: "N'importe quel équipement 'lézal'", types: ["Equipment"] },
    { name: "Rame", types: ["Equipment"] },
    { name: "N'importe quel équipement 'moblin'", types: ["Equipment"] },
    { name: "Balai-brosse", types: ["Equipment"] },
    { name: "N'importe quel plat glagla", types: ["Cooking","Wasteland"] },
    { name: "N'importe quel plat volt", types: ["Cooking"] },
    { name: "Remède picpic", types: ["Cooking"] },
    { name: "Remède volt", types: ["Cooking"] },
    { name: "Tuer un Sorcier de feu", types: ["Wizzrobe"] },
    { name: "Tuer un Sorcier électrique", types: ["Wizzrobe"] },
    { name: "Tuer un Hinox de n'importe quel type", types: ["Miniboss","Hinox"] },
    { name: "Tuer un Hinox rouge", types: ["Miniboss","Hinox"] },
    { name: "500m au mini-jeu de planeur", types: ["Minigame","Ridgeland"] },
    { name: "Activer la Tour de Lanelle", types: ["Tower","Lanayru"] },
    { name: "Activer la Tour de la Plaine", types: ["Tower","Central Hyrule"] }
];
bingoList[6] = [
    { name: "6 Noix Korogu de Tabanta", types: ["Korok","Tabantha"] },
    { name: "6 Noix Korogu d'Akkala", types: ["Korok","Akkala"] },
    { name: "Ensemble Damoiselle Gerudo", types: ["Clothes","Wasteland","Rupee"] },
    { name: "Capuche Hylienne teinte en rouge", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "Capuche Hylienne teinte en jaune", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "Capuche Hylienne teinte en violet", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "Capuche Hylienne teinte en vert", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "Capuche Hylienne teinte en jaune clair", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "Capuche Hylienne teinte en gris", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "3 quêtes 'Les recettes de Coconoa'", types: ["Side Quest","Dueling Peaks"] },
    { name: "Quête secondaire 'Le fleuriste du coeur'", types: ["Side Quest","Faron"] },
    { name: "Quête secondaire 'Les bandits de la plaine'", types: ["Side Quest","Lake"] },
    { name: "Quête secondaire 'Le cheval blanc'", types: ["Side Quest","Central Hyrule","Horse","Stamina"] },
    { name: "Quête de sanctuaire 'La statue maudite'", types: ["Shrine","Shrine Quest","Hateno"] },
    { name: "Harpon de pêcheur", types: ["Equipment"] },
    { name: "3 Armes identiques", types: ["Equipment"] },
    { name: "Remède Ignifus", types: ["Cooking"] },
    { name: "Oeuf dur", types: ["Cooking"] },
    { name: "Tuer un Sorcier de glace", types: ["Wizzrobe"] },
    { name: "Obtenir un Rubis Argenté", types: ["Rupee"] },
    { name: "Activer la Tour de Tabanta", types: ["Tower","Tabantha"] },
    { name: "Activer la Tour Sylvestre", types: ["Tower","Woodland"] }
];
bingoList[7] = [
    { name: "15 Noix Korogus", types: ["Korok"] },
    { name: "Tunique duveteuse piaf", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Tabantha"] },
    { name: "Pantalon duveteux piaf", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Tabantha"] },
    { name: "Casque Zora", types: ["Clothes","Zora Gear","Lanayru"] },
    { name: "Armure Zora", types: ["Clothes","Zora Gear","Lanayru"] },
    { name: "Capuche Hylienne teinte en bleu", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "Capuche Hylienne teinte en blanc", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "Capuche Hylienne teinte en bleu clair", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "Capuche Hylienne teinte en orange", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "Capuche Hylienne teinte en rouge foncé", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "Capuche Hylienne teinte en marron", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "4 quêtes 'Les recettes de Coconoa'", types: ["Side Quest","Dueling Peaks"] },
    { name: "Quête secondaire 'Les voleurs de bétail'", types: ["Side Quest","Hateno"] },
    { name: "Quête secondaire 'Un grand bol de fraîcheur'", types: ["Side Quest","Wasteland"] },
    { name: "Quête secondaire 'L'esthétique du plongeon'", types: ["Side Quest","Lanayru"] },
    { name: "3 sanctuaires des Monts Géminés", types: ["Shrine","Dueling Peaks"] },
    { name: "Quête de sanctuaire 'La bête à deux lances'", types: ["Shrine","Shrine Quest","Hateno","Horse"] },
    { name: "Quête de sanctuaire 'Mystère au relais'", types: ["Shrine","Shrine Quest","Eldin"] },
    { name: "N'importe quel équipement objet Zora", types: ["Equipment"] },
    { name: "N'importe quel équipement objet de glace", types: ["Equipment"] },
    { name: "N'importe quel Elixir Féérique", types: ["Cooking"] },
    { name: "Viande marinée enduro", types: ["Cooking"] },
    { name: "Crabe salé", types: ["Cooking"] },
    { name: "2 Réceptables d'Endurance", types: ["Shrine","Stamina"] },
    { name: "Lire le journal de Farras", types: ["Akkala"] },
    { name: "Activer la Tour Gerudo", types: ["Tower","Gerudo"] },
    { name: "Activer la Tour d'Ordinn", types: ["Tower","Eldin"] }
];
bingoList[8] = [
    { name: "7 Noix Korogu du Plateau du Prélude", types: ["Korok","Plateau"] },
    { name: "9 Noix Korogu des Monts Géminés", types: ["Korok","Dueling Peaks"] },
    { name: "9 Noix Korogu d'Elimith", types: ["Korok","Hateno"] },
    { name: "9 Noix Korogu de la Tour du Lac", types: ["Korok","Lake"] },
    { name: "6 Noix Korogu Gerudo", types: ["Korok","Gerudo"] },
    { name: "6 Noix Korogu d'Hebra", types: ["Korok","Hebra","Cold Resistance"] },
    { name: "6 Noix Korogu d'Ordinn", types: ["Korok","Eldin"] },
    { name: "9 Noix Korogu de la Plaine d'Hyrule", types: ["Korok","Central Hyrule"] },
    { name: "Capuche Hylienne ★", types: ["Clothes","Hylian Gear","Rupee","Great Fairy","Bokoblin"] },
    { name: "Tunique Hylienne ★", types: ["Clothes","Hylian Gear","Rupee","Great Fairy","Bokoblin"] },
    { name: "Pantalon Hylien ★", types: ["Clothes","Hylian Gear","Rupee","Great Fairy","Bokoblin"] },
    { name: "Ensemble armure de Soldat", types: ["Clothes","Soldier Gear","Rupee","Hateno"] },
    { name: "Bijou à plumes", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Tabantha"] },
    { name: "Armure de pierre", types: ["Clothes","Flame Gear","Eldin","Rupee"] },
    { name: "Bottes de pierre", types: ["Clothes","Flame Gear","Eldin","Rupee"] },
    { name: "Tunique Hylienne teinte en noir", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "Tunique Hylienne teinte en bleu marine", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "Tunique Hylienne teinte en rose", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "Quête secondaire 'La baguette surgelée'", types: ["Side Quest","Woodland","Wizzrobe"] },
    { name: "3 Sanctuaires du Lac", types: ["Shrine","Lake"] },
    { name: "3 Sanctuaires de la Tour de la Plaine", types: ["Shrine","Central Hyrule"] },
    { name: "Quête de sanctuaire 'Dompteur de vent'", types: ["Shrine","Shrine Quest","Lanayru"] },
    { name: "N'importe quel équipement sylvestre", types: ["Equipment"] },
    { name: "N'importe quel équipement objet de feu", types: ["Equipment"] },
    { name: "N'importe quel équipement objet électrique", types: ["Equipment"] },
    { name: "N'importe quel lance de gardien", types: ["Equipment","Guardian"] },
    { name: "Gâteau au fruit", types: ["Cooking"] },
    { name: "Brochette de poisson", types: ["Cooking"] },
    { name: "Tuer un gardien à pied", types: ["Miniboss","Guardian"] },
    { name: "Enregistrer le cheval royal", types: ["Horse","Central Hyrule","Stamina"] },
    { name: "Parler à Kilton", types: ["Kilton","Akkala"] },
    { name: "Obtenir un rubis doré", types: ["Rupee"] },
    { name: "5 Réceptacles de Coeur", types: ["Shrine","Heart"] },
    { name: "5 cerf dans le mini-jeu de chasse", types: ["Minigame","Hateno"] },
    { name: "Activer la tour d'Hebra", types: ["Tower","Hebra","Cold Resistance"] }
];
bingoList[9] = [
    { name: "9 Noix Korogu de Firone", types: ["Korok","Faron"] },
    { name: "9 Noix Korogu des Collines d'Hyrule", types: ["Korok","Ridgeland"] },
    { name: "9 Noix Korogu de Lanelle", types: ["Korok. Lanayru"] },
    { name: "Souliers d'escalade", types: ["Clothes","Climbing Gear","Hateno"] },
    { name: "Quête secondaire 'Le repas du soir'", types: ["Side Quest","Faron"] },
    { name: "Quête secondaire 'Le secret du club secret'", types: ["Side Quest","Wasteland","Radiant Gear","Desert Gear"] },
    { name: "Quête secondaire 'Portés disparus'", types: ["Side Quest","Wasteland"] },
    { name: "Quête secondaire 'Sus au lézards ignigus'", types: ["Side Quest","Eldin","Flame Gear"] },
    { name: "3 Sanctuaires des Collines d'Hyrule", types: ["Shrine","Ridgeland"] },
    { name: "Sanctuaires 'Esprits jumelés'", types: ["Shrine","Shrine Quest","Dueling Peaks"] },
    { name: "Quête de sanctuaire 'L'épreuve de la foudre'", types: ["Shrine","Shrine Quest","Faron"] },
    { name: "1 Épreuve Korogu", types: ["Shrine","Shrine Quest","Woodland"] },
    { name: "N'importe quel épée de gardien", types: ["Equipment","Guardian"] },
    { name: "3 boucliers identiques", types: ["Equipment"] },
    { name: "3 arcs identiques", types: ["Equipment"] },
    { name: "Tarte aux pommes", types: ["Cooking","Tabantha"] },
    { name: "Riz au curry", types: ["Cooking"] },
    { name: "Tuer un Hynox bleu", types: ["Miniboss","Hinox"] },
    { name: "Finir le mini-jeu de golf", types: ["Minigame","Woodland"] },
    { name: "Activer la tour d'Akkala", types: ["Tower","Akkala"] },
    { name: "Obtenir un matériau de Rordrac", types: ["Dragon"] }
];
bingoList[10] = [
    { name: "9 Noix Korogus des Landes Sauvages", types: ["Korok","Wasteland"] },
    { name: "9 Noix Korogu de Tabanta", types: ["Korok","Tabantha"] },
    { name: "9 Noix Korogu Sylvestre", types: ["Korok","Woodland"] },
    { name: "9 Noix Korogu d'Akkala", types: ["Korok","Akkala"] },
    { name: "Bandana d'escalade ★", types: ["Clothes","Climbing Gear","Great Fairy"] },
    { name: "Gilet barbare", types: ["Clothes","Barbarian Gear","Wasteland"] },
    { name: "Quête secondaire 'Nettoyage de plage'", types: ["Side Quest","Faron"] },
    { name: "Quête secondaire 'Le Cheval Géant'", types: ["Side Quest","Lake","Horse","Stamina"] },
    { name: "3 Sanctuaires de Firone", types: ["Shrine","Faron"] },
    { name: "3 Sanctuaires des Landes Sauvages", types: ["Shrine","Wasteland"] },
    { name: "Un sanctuaire 'Épreuve moyenne de force'", types: ["Shrine","Guardian"] },
    { name: "Quêtes de sanctuaire 'Le secret des trois cèdres'", types: ["Shrine","Shrine Quest","Hateno"] },
    { name: "Quête de sanctuaire 'L'épreuve du désert'", types: ["Shrine","Shrine Quest","Wastelands","Barbarian Gear"] },
    { name: "Quête de sanctuaire 'La tempête inconstante'", types: ["Shrine","Shrine Quest","Wastelands"] },
    { name: "Quête de sanctuaire 'L'oeil du cyclone'", types: ["Shrine","Shrine Quest","Akkala"] },
    { name: "Quête de sanctuaire 'Dans l'oeil du crâne'", types: ["Shrine","Shrine Quest","Akkala"] },
    { name: "N'importe quel bouclier de gardien", types: ["Equipment","Guardian"] },
    { name: "Velouté de champignon à la crème", types: ["Cooking"] },
    { name: "Jouer au mini-jeu de bowling", types: ["Minigame","Hebra","Cold Resistance"] }
];
bingoList[11] = [
    { name: "20 Noix Korogu", types: ["Korok"] },
    { name: "Payer 2 Grandes Fées", types: ["Rupee","Great Fairy"] },
    { name: "Armure de soldat ★", types: ["Clothes","Soldier Gear","Rupee","Great Fairy"] },
    { name: "Parure des sablons", types: ["Clothes","Desert Gear","Wasteland","Rupee"] },
    { name: "Pantalon des sablons", types: ["Clothes","Desert Gear","Wasteland","Rupee"] },
    { name: "Casque isolant ★", types: ["Clothes","Rubber Gear","Faron","Great Fairy"] },
    { name: "Masque furtif ★", types: ["Clothes","Stealth Gear","Rupee","Great Fairy"] },
    { name: "Combinaison furtive (torse) ★", types: ["Clothes","Stealth Gear","Rupee","Great Fairy"] },
    { name: "Chausses furtives ★", types: ["Clothes","Stealth Gear","Rupee","Great Fairy"] },
    { name: "Ensemble furtif", types: ["Clothes","Stealth Gear","Rupee","Dueling Peaks"] },
    { name: "Casque barbare", types: ["Clothes","Barbarian Gear","Akkala"] },
    { name: "Quête secondaire 'Ce que femme veut'", types: ["Side Quest","Hateno"] },
    { name: "3 Sanctuaires d'Elimith", types: ["Shrine","Hateno"] },
    { name: "3 Sanctuaires de Tabanta", types: ["Shrine","Tabantha"] },
    { name: "3 Sanctuaires Sylvestre", types: ["Shrine","Woodland"] },
    { name: "3 Sanctuaires d'Akkala", types: ["Shrine","Akkala"] },
    { name: "Quête de sanctuaire 'Les épéistes taciturnes'", types: ["Shrine","Shrine Quest","Wastelands"] },
    { name: "Quête de sanctuaire 'Le journal des neiges'", types: ["Shrine","Shrine Quest","Wastelands","Cold Resistance"] },
    { name: "Sanctuaire du Temple Oublié", types: ["Shrine","Shrine Quest","Woodland"] },
    { name: "Quête de sanctuaire 'L'épreuve de l'ombre'", types: ["Shrine","Shrine Quest","Woodland"] },
    { name: "Quête de sanctuaire 'La paroi de fer'", types: ["Shrine","Shrine Quest","Eldin"] },
    { name: "Quête de sanctuaire 'L'épreuve de l'île perdue'", types: ["Shrine","Shrine Quest","Akkala","Barbarian Gear"] },
    { name: "N'importe quel équipement objet de la Garde Royale", types: ["Equipment"] },
    { name: "N'importe quel baguette de deuxième niveau", types: ["Equipment","Wizzrobe"] },
    { name: "N'importe quelle Hache de Gardien", types: ["Equipment","Guardian"] },
    { name: "Gateau de monstre", types: ["Cooking","Kilton"] },
    { name: "Crêpe aux baies", types: ["Cooking","Tabantha"] },
    { name: "Tuer un lithorok rare", types: ["Rupee","Miniboss","Talus"] },
    { name: "Enregistrer le cheval géant", types: ["Horse","Lake","Stamina"] },
    { name: "Monter un ours", types: ["Horse","Stamina"] },
    { name: "Monter un staldestrier", types: ["Horse"] },
    { name: "2000 rubis", types: ["Rupee"] },
    { name: "Lire le journal du Roi", types: ["Hyrule Castle"] },
    { name: "Prenez un selfie avec Noïa", types: ["Dueling Peaks","Camera"] },
    { name: "Détecteur Sheikah +", types: ["Camera","Rune Upgrade","Hateno"] }
];
bingoList[12] = [
    { name: "12 Noix Korogu des Monts Géminés", types: ["Korok","Dueling Peaks"] },
    { name: "9 Noix Korogu d'Ordinn", types: ["Korok","Eldin"] },
    { name: "12 Noix Korogu de la Tour de la Plaine d'Hyrule", types: ["Korok","Central Hyrule"] },
    { name: "Tunique du Prodige", types: ["Clothes","Champion","Camera"] },
    { name: "Casque de soldat ★", types: ["Clothes","Soldier Gear","Rupee","Great Fairy"] },
    { name: "Jambières de soldat ★", types: ["Clothes","Soldier Gear","Rupee","Great Fairy"] },
    { name: "Épaulières des sablons", types: ["Clothes","Desert Gear","Wasteland","Rupee"] },
    { name: "Combinaison Isolante ★", types: ["Clothes","Rubber Gear","Ridgeland","Great Fairy"] },
    { name: "Pantalon Isolant ★", types: ["Clothes","Rubber Gear","Faron","Great Fairy"] },
    { name: "Jambières Zora", types: ["Clothes","Zora Gear","Lanayru","Camera"] },
    { name: "Boucles d'ambre", types: ["Clothes","Gems","Rupee","Wasteland"] },
    { name: "Quête secondaire 'Les recettes royales'", types: ["Side Quest","Central Hyrule","Cooking"] },
    { name: "2 Quête de Sanctuaires", types: ["Shrine","Shrine Quest"] },
    { name: "Quête de sanctuaire 'Les Sept Héroïnes'", types: ["Shrine","Shrine Quest","Wastelands"] },
    { name: "Quête de sanctuaire 'Le dessin sur la falaise'", types: ["Shrine","Shrine Quest","Gerudo","Cold Resistance"] },
    { name: "Quête de sanctuaire 'Le signe de l'ombre'", types: ["Shrine","Shrine Quest","Gerudo"] },
    { name: "Collecter 1 souvenir", types: ["Camera"] },
    { name: "Lire le journal de Zelda", types: ["Hyrule Castle"] },
    { name: "Prenez un selfie avec Asarim", types: ["Camera"] },
    { name: "3 Sanctuaires de Lanelle", types: ["Shrine","Lanayru"] },
    { name: "Quête secondaire 'Photo et détecteur'", types: ["Side Quest","Hateno","Camera"] },
    { name: "Quête secondaire 'A la lumière des lucioles'", types: ["Side Quest","Dueling Peaks","Heirloom","Camera"] }
];
bingoList[13] = [
    { name: "12 Noix Korogu d'Elimith", types: ["Korok","Hateno"] },
    { name: "12 Noix Korogu de la tour du Lac", types: ["Korok","Lake"] },
    { name: "12 Noix Korogu des Collines d'Hyrule", types: ["Korok","Ridgeland"] },
    { name: "9 Noix Korogu d'Hebra", types: ["Korok","Hebra","Cold Resistance"] },
    { name: "Casque de pierre", types: ["Clothes","Flame Gear","Eldin","Rupee"] },
    { name: "Armure Zora ★", types: ["Clothes","Zora Gear","Great Fairy","Lizalfos"] },
    { name: "Culotte Barbare", types: ["Clothes","Barbarian Gear","Hebra"] },
    { name: "3 Sanctuaires d'Hebra", types: ["Shrine","Hebra","Cold Resistance"] },
    { name: "3 Sanctuaires d'Ordinn", types: ["Shrine","Eldin"] },
    { name: "Quête de sanctuaire 'Le mangeur de serpents'", types: ["Shrine","Shrine Quest","Lake","Dragon"] },
    { name: "Quête de sanctuaire 'L'épreuve d'endurance'", types: ["Shrine","Shrine Quest","Gerudo"] },
    { name: "Tuer un cryorok", types: ["Rupee","Gems","Miniboss","Talus","Cold Resistance"] },
    { name: "Tuer un gardien tourelle", types: ["Miniboss","Guardian","Hyrule Castle"] },
    { name: "5 Créatures dans l'Encyclopédie", types: ["Camera","Compendium"] },
    { name: "5 Monstres dans l'Encyclopédie", types: ["Camera","Compendium"] },
    { name: "5 Armes dans l'Encyclopédie", types: ["Camera","Compendium"] },
    { name: "Prenez un selfie avec Sidon", types: ["Lanayru","Camera"] },
    { name: "Obtenez un matériaux d'Ordrac", types: ["Dragon"] },
    { name: "Finir le mini-jeu basique de Ski sur bouclier", types: ["Minigame","Hebra","Cold Resistance"] },
    { name: "Bottes de neige", types: ["Clothes","Boots","Side Quest","Gerudo","Camera"] },
    { name: "Tuer un Magrok", types: ["Rupee","Gems","Miniboss","Talus","Eldin"] }
];
bingoList[14] = [
    { name: "25 Noix Korogus", types: ["Korok"] },
    { name: "12 Noix Korogu de Firone", types: ["Korok","Faron"] },
    { name: "9 Noix Korogu Gerudo", types: ["Korok","Gerudo"] },
    { name: "12 Noix Korogu de Tabanta", types: ["Korok","Tabantha"] },
    { name: "12 Noix Korogu Sylvestre", types: ["Korok","Woodland"] },
    { name: "12 Noix Korogu d'Akkala", types: ["Korok","Akkala"] },
    { name: "12 Noix Korogu de Lanelle", types: ["Korok. Lanayru"] },
    { name: "Payer la Divinité Équine Marlon", types: ["Lake","Rupee"] },
    { name: "Quête secondaire 'Une pierre si précieuse'", types: ["Side Quest","Wasteland","Gems"] },
    { name: "Casque Zora ★", types: ["Clothes","Zora Gear","Great Fairy","Lizalfos"] },
    { name: "Masque Nox", types: ["Clothes","Radiant Gear","Rupee","Gems","Wasteland"] },
    { name: "Combinaison Nox (torse)", types: ["Clothes","Radiant Gear","Rupee","Gems","Wasteland"] },
    { name: "Chausses Nox", types: ["Clothes","Radiant Gear","Rupee","Gems","Wasteland"] },
    { name: "Boucles de Topaze", types: ["Clothes","Gems","Rupee","Wasteland"] },
    { name: "Quête secondaire 'Curry Anti-froid'", types: ["Side Quest","Tabantha","Eldin"] },
    { name: "10 Sanctuaires", types: ["Shrine"] },
    { name: "3 Sanctuaires Gerudo²é9", types: ["Shrine","Gerudo","Cold Resistance"] },
    { name: "Quête secondaire 'Travaux de restauration'", types: ["Shrine","Shrine Quest","Faron","Camera"] },
    { name: "Collectez 2 souvenirs", types: ["Camera"] },
    { name: "Tuer un Hinox noir", types: ["Miniboss","Hinox"] },
    { name: "Tuer un Stalhinox", types: ["Miniboss","Hinox"] },
    { name: "Tuer un gardien volant", types: ["Miniboss","Guardian"] },
    { name: "3 Réceptacles d'Endurance", types: ["Shrine","Stamina"] },
    { name: "Obtenir un matériau de Nedrac", types: ["Hateno","Cold Resistance","Dragon"] },
    { name: "Bombes à distance +", types: ["Camera","Rune Upgrade","Hateno"] },
    { name: "Activer 4 Tours", types: ["Tower"] },
    { name: "11 Quêtes Secondaires", types: ["Side Quest"] }
];
bingoList[15] = [
    { name: "12 Noix Korogu des Landes Sauvages", types: ["Korok","Wasteland"] },
    { name: "Tunique duveteuse piaf ★", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Great Fairy"] },
    { name: "Pantalon duveteux piaf ★", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Great Fairy"] },
    { name: "Ensemble duveteux piaf complet", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Tabantha"] },
    { name: "Bottes de pierre ★", types: ["Clothes","Flame Gear","Eldin","Rupee","Great Fairy"] },
    { name: "Souliers d'escalade ★", types: ["Clothes","Climbing Gear","Great Fairy"] },
    { name: "Diadème Saphir", types: ["Clothes","Gems","Rupee","Wasteland"] },
    { name: "Diadème rubis", types: ["Clothes","Gems","Rupee","Wasteland"] },
    { name: "Masque Bokoblin", types: ["Clothes","Kilton"] },
    { name: "Quête de sanctuaire 'Le secret de la montagne'", types: ["Side Quest","Eldin"] },
    { name: "Quête secondaire 'Reportage animalier'", types: ["Side Quest","Lanayru","Camera","Zora Gear"] },
    { name: "Quête secondaire 'Les armes du château'", types: ["Side Quest","Hyrule Castle"] },
    { name: "Quête de sanctuaire 'Épreuve en terre sauvage'", types: ["Shrine","Shrine Quest","Faron"] },
    { name: "Quête de sanctuaire 'Le secret des trois géants", types: ["Shrine","Shrine Quest","Faron","Hinox"] },
    { name: "Quête de sanctuaire 'L'arbre solitaire'", types: ["Shrine","Shrine Quest","Hebra","Cold Resistance"] },
    { name: "Quête de sanctuaire 'L'épreuve de la falaise'", types: ["Shrine","Shrine Quest","Hebra","Cold Resistance","Barbarian Gear"] },
    { name: "Sabre tranche-vent", types: ["Equipment","Wasteland"] },
    { name: "Tuer un Lynel", types: ["Miniboss","Lynel"] },
    { name: "Tuer un Molarquor", types: ["Miniboss","Molduga","Wasteland"] },
    { name: "6 Réceptacles de Coeur", types: ["Shrine","Heart"] },
    { name: "Prenez un selfie avec Riju", types: ["Wasteland","Camera"] },
    { name: "Prenez un selfie en étant en feu", types: ["Eldin","Camera"] },
    { name: "Cinetis +", types: ["Camera","Rune Upgrade","Hateno"] },
    { name: "10 Armes dans l'Encyclopédie", types: ["Camera","Compendium"] }
];
bingoList[16] = [
    { name: "15 Noix Korogus des Monts Géminés", types: ["Korok","Dueling Peaks"] },
    { name: "15 Noix Korogu de la Tour de la Plaine d'Hyrule", types: ["Korok","Central Hyrule"] },
    { name: "Tunique de Prodige ★", types: ["Clothes","Champion","Camera","Great Fairy"] },
    { name: "Bijou à plumes ★", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Great Fairy"] },
    { name: "Ensemble Isolant complet", types: ["Clothes","Rubber Gear","Faron","Ridgeland"] },
    { name: "Armure en pierre ★", types: ["Clothes","Flame Gear","Eldin","Rupee","Great Fairy"] },
    { name: "Boucle d'Opale", types: ["Clothes","Gems","Rupee","Wasteland"] },
    { name: "Quête secondaire 'Le viscère de Moldarquor'", types: ["Side Quest","Wasteland","Molduga"] },
    { name: "Quête secondaire 'Prouver sa valeur'", types: ["Side Quest","Eldin","Talus"] },
    { name: "Quête secondaire 'Entomologie'", types: ["Side Quest","Akkala"] },
    { name: "Quête secondaire 'L'épreuve des Rumys'", types: ["Side Quest","Wasteland","Camera"] },
    { name: "12 Quêtes secondaires", types: ["Side Quest"] },
    { name: "10 Créature dans l'Encyclopédie", types: ["Camera","Compendium"] },
    { name: "10 Monstres dans l'Encyclopédie", types: ["Camera","Compendium"] }
];
bingoList[17] = [
    { name: "15 Noix Korogu d'Elimith", types: ["Korok","Hateno"] },
    { name: "15 Noix Korogu de la Tour du Lac", types: ["Korok","Lake"] },
    { name: "12 Noix Korogu Gerudo", types: ["Korok","Gerudo"] },
    { name: "15 Noix Korogu des Collines d'Hyrule", types: ["Korok","Ridgeland"] },
    { name: "12 Noix Korogu d'Hebra", types: ["Korok","Hebra","Cold Resistance"] },
    { name: "12 Noix Korogu d'Ordinn", types: ["Korok","Eldin"] },
    { name: "Parure des Sablons ★", types: ["Clothes","Desert Gear","Wasteland","Rupee","Great Fairy"] },
    { name: "Épaulière des Sablons ★", types: ["Clothes","Desert Gear","Wasteland","Rupee","Great Fairy"] },
    { name: "Pantalon des Sablons ★", types: ["Clothes","Desert Gear","Wasteland","Rupee","Great Fairy"] },
    { name: "Bottes des sables", types: ["Clothes","Boots","Side Quest","Gerudo"] },
    { name: "Quête secondaire 'La Huitième Héroïne'", types: ["Side Quest","Wasteland","Gerudo","Boots","Cold Resistance","Camera"] },
    { name: "11 Sancturaires", types: ["Shrine"] },
    { name: "5 Quêtes de Sanctuaire", types: ["Shrine","Shrine Quest"] },
    { name: "Quête de sanctuaire 'L'amatrice de Gardiens'", types: ["Shrine","Shrine Quest","Lake","Camera","Guardian"] },
    { name: "Quête de sanctuaire 'A la source de la Force'", types: ["Shrine","Shrine Quest","Akkala","Dragon"] },
    { name: "N'importe quel équipement 'Lynel'", types: ["Equipment","Lynel"] },
    { name: "1 arme de feu, 1 arme de glace, et 1 arme électrique", types: ["Equipment"] },
    { name: "20 cibles au mini-jeu de la Zone d'exercice au vol", types: ["Minigame","Tabantha","Cold Resistance"] },
    { name: "Activer 5 Tours", types: ["Tower"] },
    { name: "15 Armes dans l'Encyclopédie", types: ["Camera","Compendium"] }
];
bingoList[18] = [
    { name: "15 Créatures dans l'Encyclopédie", types: ["Camera","Compendium"] },
    { name: "15 Monstres dans l'Encyclopédie", types: ["Camera","Compendium"] },
    { name: "30 Noix Korogu", types: ["Korok"] },
    { name: "15 Noix Korogu de Firone", types: ["Korok","Faron"] },
    { name: "15 Noix Korogu d'Akkala", types: ["Korok","Akkala"] },
    { name: "15 Noix Korogu de Lanelle", types: ["Korok. Lanayru"] },
    { name: "Ensemble des Sablons entier", types: ["Clothes","Desert Gear","Wasteland","Rupee"] },
    { name: "Casque de pierre ★", types: ["Clothes","Flame Gear","Eldin","Rupee","Great Fairy"] },
    { name: "Jambières Zora ★", types: ["Clothes","Zora Gear","Great Fairy","Lizalfos","Camera"] },
    { name: "Masque nox ★", types: ["Clothes","Radiant Gear","Rupee","Gems","Great Fairy"] },
    { name: "Bottes de neige ★", types: ["Clothes","Boots","Side Quest","Great Fairy","Camera"] },
    { name: "Quête secondaire 'Déployer des pouvoirs'", types: ["Side Quest","Hateno","Camera"] },
    { name: "Quête secondaire 'Un individu suspect", types: ["Side Quest","Akkala","Kilton","Camera"] },
    { name: "12 Sanctuaires", types: ["Shrine"] },
    { name: "Quête de sanctuaire 'Le trésor de Lanelle'", types: ["Shrine","Shrine Quest","Hateno","Cold Resistance","Dragon"] },
    { name: "Collectez 3 souvenirs", types: ["Camera"] },
    { name: "Bouclier d'Hylia", types: ["Miniboss","Hinox","Hyrule Castle"] },
    { name: "Monter un Alpha", types: ["Horse","Ridgeland","Stamina"] },
    { name: "Acheter une maison", types: ["Hateno","Rupee"] },
    { name: "Un Sanctuaire 'Épreuve extrême de force'", types: ["Shrine","Guardian"] }
];
bingoList[19] = [
    { name: "15 Noix Korogu des Landes Sauvages", types: ["Korok","Wasteland"] },
    { name: "15 Noix Korogu de Tabanta", types: ["Korok","Tabantha"] },
    { name: "15 Noix Korogu Sylvestre", types: ["Korok","Woodland"] },
    { name: "Combinaison Nox (torse) ★", types: ["Clothes","Radiant Gear","Rupee","Gems","Great Fairy"] },
    { name: "Chausses Nox ★", types: ["Clothes","Radiant Gear","Rupee","Gems","Great Fairy"] },
    { name: "Boucle d'Ambre ★", types: ["Clothes","Gems","Rupee","Great Fairy"] },
    { name: "Quête secondaire 'Un cheval tout en os'", types: ["Side Quest","Hebra","Camera"] },
    { name: "Quête de sanctuaire 'Le joyau disparu'", types: ["Shrine","Shrine Quest","Dueling Peaks","Heirloom","Camera"] },
    { name: "Quête de sanctuaire 'Le frère disparu'", types: ["Shrine","Shrine Quest","Eldin"] },
    { name: "1 quête principale de Créature Divine", types: ["Divine Beast"] },
    { name: "Quete principale 'Vah'Medoh'", types: ["Divine Beast","Tabantha","Cold Resistance"] },
    { name: "La Rage de Revali", types: ["Divine Beast","Tabantha","Cold Resistance"] },
    { name: "Tuer le Lynel de l'Amphithéâtre", types: ["Miniboss","Lynel","Central Hyrule"] },
    { name: "Activer 6 Tours", types: ["Tower"] },
    { name: "13 quêtes secondaires", types: ["Side Quest"] },
    { name: "Une pièce de la tenue d'escalade", types: ["Clothes","Climbing Gear","Hateno"] }
];
bingoList[20] = [
    { name: "15 Noix Korogu Gerudo", types: ["Korok","Gerudo"] },
    { name: "15 Noix Korogu d'Hébra", types: ["Korok","Hebra","Cold Resistance"] },
    { name: "15 Noix Korogu d'Ordinn", types: ["Korok","Eldin"] },
    { name: "Ensemble Zora complet", types: ["Clothes","Zora Gear","Lanayru","Camera"] },
    { name: "Casque Barbare ★", types: ["Clothes","Barbarian Gear","Great Fairy","Lynel"] },
    { name: "Gilet Barbare ★", types: ["Clothes","Barbarian Gear","Great Fairy","Lynel"] },
    { name: "Boucles de Topaze ★", types: ["Clothes","Gems","Rupee","Great Fairy"] },
    { name: "Diadème Diamant", types: ["Clothes","Gems","Rupee","Wasteland"] },
    { name: "Quête secondaire 'L'épée oubliée'", types: ["Side Quest","Wasteland","Gerudo","Boots","Cold Resistance","Camera"] },
    { name: "Quête secondaire 'A la recherche de Quill'", types: ["Side Quest","Tabantha"] },
    { name: "Quête secondaire 'Commerce de pierres'", types: ["Side Quest","Eldin","Gems"] },
    { name: "Quête secondaire 'L'autre scientifique'", types: ["Side Quest","Akkala","Camera"] },
    { name: "6 Quêtes de Sanctuaires", types: ["Shrine","Shrine Quest"] },
    { name: "Quête principale 'Vah'Ruta'", types: ["Divine Beast","Lanayru"] },
    { name: "La prière de Mipha", types: ["Divine Beast","Lanayru"] },
    { name: "Collectez 4 souvenirs", types: ["Camera"] },
    { name: "4 Réceptacles d'Endurance", types: ["Shrine","Stamina"] },
    { name: "20 Armes dans l'Encyclopédie", types: ["Camera","Compendium"] }
];
bingoList[21] = [
    { name: "20 Créatures dans l'Encyclopédie", types: ["Camera","Compendium"] },
    { name: "20 Monstres dans l'Encyclopédie", types: ["Camera","Compendium"] },
    { name: "35 Noix Korogus", types: ["Korok"] },
    { name: "Payer 3 Grandes Fées", types: ["Rupee","Great Fairy"] },
    { name: "Ensemble Armure de Pierre complet", types: ["Clothes","Flame Gear","Eldin","Rupee"] },
    { name: "Culotte Barbare ★", types: ["Clothes","Barbarian Gear","Great Fairy","Lynel"] },
    { name: "Ensemble Armure Nox complet", types: ["Clothes","Radiant Gear","Rupee","Gems","Wasteland"] },
    { name: "Boucles d'Opale ★", types: ["Clothes","Gems","Rupee","Great Fairy"] },
    { name: "Diadème Saphir ★", types: ["Clothes","Gems","Rupee","Great Fairy"] },
    { name: "Diadème Rubis ★", types: ["Clothes","Gems","Rupee","Great Fairy"] },
    { name: "13 Sanctuaires", types: ["Shrine"] },
    { name: "7 Quêtes de Sanctuaires", types: ["Shrine","Shrine Quest"] },
    { name: "Quête de sanctuaire 'Une boisson fraîche, une!'", types: ["Shrine","Shrine Quest","Wastelands"] },
    { name: "Quête de sanctuaire 'Les Soeurs de pierre'", types: ["Shrine","Shrine Quest","Tabantha"] },
    { name: "Quête de sanctuaire 'La chanson des piafs'", types: ["Shrine","Shrine Quest","Tabantha"] },
    { name: "Collectez 5 souvenirs", types: ["Camera"] },
    { name: "Maillet ressort", types: ["Equipment","Kilton"] },
    { name: "7 Réceptacles de Coeur", types: ["Shrine","Heart"] },
    { name: "Améliorez tous les modules", types: ["Camera","Rune Upgrade","Hateno"] },
    { name: "Quête de sanctuaire 'La chanson de la fête'", types: ["Shrine","Shrine Quest","Lanayru"] }
];
bingoList[22] = [
    { name: "Quête secondaire 'Les énigmes d'Hyrule'", types: ["Side Quest","Woodland","Lynel"] },
    { name: "Quête secondaire 'Pluie de grenouilles'", types: ["Side Quest","Lanayru"] },
    { name: "Quête secondaire 'Collecte de gemmes nox'", types: ["Side Quest","Lanayru","Gems"] },
    { name: "'Quête secondaire 'Coeur à la dérive'", types: ["Side Quest","Lanayru"] },
    { name: "14 Sanctuaires", types: ["Shrine"] },
    { name: "8 Quêtes de Sanctuaires", types: ["Shrine","Shrine Quest"] },
    { name: "Activer 7 Tours", types: ["Tower"] },
    { name: "14 Quêtes Secondaires", types: ["Side Quest"] }
];
bingoList[23] = [
    { name: "40 Noix Korogu", types: ["Korok"] },
    { name: "Quête secondaire 'Sus au Cryorok'", types: ["Side Quest","Tabantha","Hebra","Cold Resistance"] },
    { name: "Quête secondaire 'Chasse au géant'", types: ["Side Quest","Lanayru","Hinox"] },
    { name: "15 Sanctuaires", types: ["Shrine"] },
    { name: "Quête principale 'Vah'Rudania'", types: ["Divine Beast","Eldin"] },
    { name: "Bouclier de Daruk", types: ["Divine Beast","Eldin"] },
    { name: "Collectez 6 Souvenirs", types: ["Camera"] },
    { name: "Refaire fabriquer une arme ou un bouclier de Prodige", types: ["Equipment","Divine Beast","Gems"] },
    { name: "Une pièce de la tenue d'escalade ★", types: ["Clothes","Climbing Gear","Great Fairy"] },
    { name: "Activer 8 Tours", types: ["Tower"] }
];
bingoList[24] = [
    { name: "45 Noix Korogus", types: ["Korok"] },
    { name: "Quête secondaire 'Fossiles de baleines'", types: ["Side Quest","Camera"] },
    { name: "16 Sanctuaires", types: ["Shrine"] },
    { name: "Quête principale 'Vah'Naboris'", types: ["Divine Beast","Wasteland"] },
    { name: "La Colère d'Urbosa", types: ["Divine Beast","Wasteland"] },
    { name: "Abattre Ganon", types: ["Hyrule Castle"] },
    { name: "Activer 9 Tours", types: ["Tower"] },
    { name: "Ensemble d'escalade complet", types: ["Clothes","Climbing Gear"] }
];
bingoList[25] = [
    { name: "50 noix korogus", types: ["Korok"] },
    { name: "Quête secondaire 'Les pierres de mémoire'", types: ["Side Quest","Lanayru"] },
    { name: "2 Quêtes principales de Créatures Divines", types: ["Divine Beast"] },
    { name: "Quête secondaire 'Il faut retrouver Brihk'", types: ["Side Quest","Wasteland"] },
    { name: "Quête secondaire 'Chasse au pollueur'", types: ["Side Quest","Wasteland"] },
    { name: "Quête de sanctuaire 'La reine de la piste'", types: ["Shrine","Shrine Quest","Wastelands"] },
    { name: "Activer 10 Tours", types: ["Tower"] },
    { name: "15 Quêtes secondaires", types: ["Side Quest"] },
    { name: "Ensemble barbare complet", types: ["Clothes","Barbarian Gear"] }
];
module.exports = bingoList;
