var bingoList = [];

bingoList[1] = [
  { name: "Hylia-Kapuze", types: ["Clothes","Hylian Gear","Rupee",] },
  { name: "Hylia-Gewand", types: ["Clothes","Hylian Gear","Rupee","Rupee",] },
  { name: "Winterwams", types: ["Clothes","Cold Resistance","Hateno",] },
  { name: "3 ‘Turm des Plateaus’-Gebiet Korgs", types: ["Korok","Plateau",] },
  { name: "Hylia-Hose", types: ["Clothes","Hylian Gear","Rupee",] },
  { name: "Beliebiges Bok-Equipment", types: ["Equipment",] },
  { name: "3 ‘Turm der Zwillingsberge’ Gebiet Krogs", types: ["Korok","Dueling Peaks",] },
  { name: "3 ‘Turm der Hügel’ Gebiet Krogs", types: ["Korok","Ridgeland",] },
];
bingoList[2] = [
  { name: "5 Krogs", types: ["Korok",] },
  { name: "3 Hateno-Turm Gebiet Krogs", types: ["Korok","Hateno",] },
  { name: "3 Phirone-Turm Gebiet Krogs", types: ["Korok","Faron",] },
  { name: "3 ‘Turm der Ebene’ Gebiet Krogs", types: ["Korok","Central Hyrule",] },
  { name: "Rostige Waffe", types: ["Equipment",] },
  { name: "Ausdauer-Gericht", types: ["Cooking","Stamina",] },
  { name: "Gib Terri einen Käfer", types: ["Horse",] },
  { name: "Registriere ein Pferd", types: ["Horse",] },
  { name: "Mache ein Huhn wütend", types: ["Cucco",] },
  { name: "Aktiviere den Turm der Zwillingsberge", types: ["Tower","Dueling Peaks",] },
  { name: "Holzkelle", types: ["Equipment",] },
  { name: "’Kokos Küche’ Nebenaufgabe", types: ["Side Quest","Dueling Peaks",] },
  { name: "Spurt-Gericht", types: ["Cooking",] },
  { name: "Scharfes Gericht", types: ["Cooking","Cold Resistance",] },
];
bingoList[3] = [
  { name: "5 ‘Turm der Ebene’ Gebiet-Krogs", types: ["Korok","Plateau",] },
  { name: "6 ‘Turm der Zwillingsberge’ Gebiet Krogs", types: ["Korok","Dueling Peaks",] },
  { name: "3 ‘Turm des Sees’ Gebiet Krogs", types: ["Korok","Lake",] },
  { name: "3 ‘Turm der Wüste’ Gebiet Krogs", types: ["Korok","Wasteland",] },
  { name: "3 ‘Turm der Wälder’ Gebiet Krogs", types: ["Korok","Woodland",] },
  { name: "3 Ranelle-Turm Gebiet Krogs", types: ["Korok”,”Lanayru",] },
  { name: "'Die einzig wahren Rasseln' Nebenaufgabe", types: ["Side Quest","Dueling Peaks",] },
  { name: "'Ein Spielkamerad für Priko' Nebenaufgabe", types: ["Side Quest","Dueling Peaks",] },
  { name: "'Der Wildfang' Nebenaufgabe", types: ["Side Quest","Dueling Peaks","Horse",] },
  { name: "'Dunkle Geschäfte' Nebenaufgabe", types: ["Side Quest","Hateno",] },
  { name: "'Bitte nicht betreten!' Schreinaufgabe", types: ["Shrine","Shrine Quest","Dueling Peaks",] },
  { name: "Fit-Gericht", types: ["Cooking","Stamina",] },
  { name: "Kraft-Gerichtl", types: ["Cooking",] },
  { name: "Schleich-Gericht", types: ["Cooking",] },
  { name: "Dubiose Matsche", types: ["Cooking",] },
  { name: "Öffne 2 Bokblin Lager Truhen", types: ["Plateau",] },
  { name: "Rette einen Reisenden in Gefahr", types: ["Monster",] },
  { name: "Aktiviere den Turm des Sees", types: ["Tower","Lake",] },
  { name: "3 Tabanta-Turm Gebiet Krogs", types: ["Korok","Tabantha",] },
  { name: "Beliebige Knochen-Arm Waffe", types: ["Equipment",] },
  { name: "3 Nebenaufgaben", types: ["Side Quest",] },
];
bingoList[4] = [
  { name: "10 Krogs", types: ["Korok",] },
  { name: "3 Eldin-Turm Gebiet Krogs", types: ["Korok","Eldin",] },
  { name: "3 Akkala-Turm Gebiet Krogs", types: ["Korok","Akkala",] },
  { name: "Bezahle eine große Fee", types: ["Rupee","Great Fairy",] },
  { name: "Hylia-Set (nicht Rüstung)", types: ["Clothes","Hylian Gear","Rupee",] },
  { name: "Hylia-Helm", types: ["Clothes","Soldier Gear","Rupee","Hateno",] },
  { name: "Hylia-Rüstung", types: ["Clothes","Soldier Gear","Rupee","Hateno",] },
  { name: "Hylia-Beinschutz", types: ["Clothes","Soldier Gear","Rupee","Hateno",] },
  { name: "Ninja-Maske", types: ["Clothes","Stealth Gear","Rupee","Dueling Peaks",] },
  { name: "Ninja-Hose", types: ["Clothes","Stealth Gear","Rupee","Dueling Peaks",] },
  { name: "Kletterkopftuch", types: ["Clothes","Climbing Gear","Dueling Peaks",] },
  { name: "'Entwischte Hühner' Nebenaufgabe", types: ["Side Quest","Dueling Peaks","Heirloom",] },
  { name: "’Kokos Küche 2’ Nebenaufgabe", types: ["Side Quest","Dueling Peaks",] },
  { name: "'Der brennende Pfeil' Nebenaufgabe", types: ["Side Quest","Dueling Peaks",] },
  { name: "'Liebe durch den Magen' Nebenaufgabe", types: ["Side Quest","Tabantha",] },
  { name: "‘Kraftprobe (Leicht)’ Schrein", types: ["Shrine","Guardian",] },
  { name: "Hacke", types: ["Equipment",] },
  { name: "Maxi-Gericht", types: ["Cooking",] },
  { name: "Abwehr-Gericht", types: ["Cooking",] },
  { name: "Maxi-Medizin", types: ["Cooking",] },
  { name: "Elektro-Medizin", types: ["Cooking",] },
  { name: "Kühlungs-Medizin", types: ["Cooking",] },
  { name: "Spurt-Medizin", types: ["Cooking",] },
  { name: "Fitness-Medizin", types: ["Cooking",] },
  { name: "Kraft-Medizin", types: ["Cooking",] },
  { name: "Abwehr-Medizin", types: ["Cooking",] },
  { name: "Schlech-Medizin", types: ["Cooking",] },
  { name: "Harter Brocken", types: ["Cooking",] },
  { name: "Töte einen beliebigen Pyromagus", types: ["Wizzrobe",] },
  { name: "Töte einen beliebigen Iwarok", types: ["Rupee","Gems","Miniboss","Talus",] },
  { name: "Töte einen normalen Iwarok", types: ["Rupee","Gems","Miniboss","Talus",] },
  { name: "Töte ein Wächter-Wrack", types: ["Miniboss","Guardian",] },
  { name: "Steige auf ein Reh", types: ["Horse",] },
  { name: "Lilaner Rubin", types: ["Rupee",] },
  { name: "Lies Payas Tagebuch", types: ["Dueling Peaks",] },
  { name: "Lies Purahs Tagebuch", types: ["Hateno",] },
  { name: "Aktiviere den Hateno-Turm", types: ["Tower","Hateno",] },
  { name: "Aktiviere den Phirone-Turm", types: ["Tower","Faron",] },
  { name: "Aktiviere den Turm der Wüste", types: ["Tower","Wasteland",] },
  { name: "Aktiviere den Turm der Hügel", types: ["Tower","Ridgeland",] },
  { name: "4 Nebenaufgaben", types: ["Side Quest",] },
  { name: "Beliebiger Stab (Pyromagus)", types: ["Equipment","Wizzrobe",] },
];
bingoList[5] = [
  { name: "6 Hateno-Turm Gebiet Krogs", types: ["Korok","Hateno",] },
  { name: "6 Phirone-Turm Gebiet Krogs", types: ["Korok","Faron",] },
  { name: "6 ‘Turm des Sees’ Gebiet Krogs", types: ["Korok","Lake",] },
  { name: "6 ‘Turm der Wüste’ Gebiet Krogs", types: ["Korok","Wasteland",] },
  { name: "3 Gerudo-Turm Gebiet Krogs", types: ["Korok","Gerudo",] },
  { name: "6 ‘Turm der Hügel’ Gebiet Krogs", types: ["Korok","Ridgeland",] },
  { name: "3 Hebra-Turm Gebiet Krogs", types: ["Korok","Hebra","Cold Resistance",] },
  { name: "6 ‘Turm der Wälder’ Gebiet Krogs", types: ["Korok","Woodland",] },
  { name: "6 Ranelle-Turm Gebiet Krogs", types: ["Korok”,“Lanayru",] },
  { name: "6 ‘Turm der Ebene’ Gebiet Krogs", types: ["Korok","Central Hyrule",] },
  { name: "Isolierhelm", types: ["Clothes","Rubber Gear","Faron",] },
  { name: "Isolierrüstung", types: ["Clothes","Rubber Gear","Ridgeland",] },
  { name: "Isolierhose", types: ["Clothes","Rubber Gear","Faron",] },
  { name: "Ninja-Anzug", types: ["Clothes","Stealth Gear","Rupee","Dueling Peaks",] },
  { name: "'Der große Räuberkönig' Nebenaufgabe", types: ["Side Quest","Dueling Peaks",] },
  { name: "'Versunkener Schatz' Nebenaufgabe", types: ["Side Quest","Hateno",] },
  { name: "'Der Schatz des Helden' Nebenaufgabe", types: ["Side Quest","Hateno",] },
  { name: "'Blitzableiter' Nebenaufgabe", types: ["Side Quest","Faron","Rubber Gear",] },
  { name: "'Pferdehandel' Nebenaufgabe", types: ["Side Quest","Wasteland","Horse",] },
  { name: "'Flitterwochen in Gefahr' Nebenaufgabe", types: ["Side Quest","Tabantha",] },
  { name: "'Folge dem Schatten' Nebenaufgabe", types: ["Side Quest","Tabantha","Rupee","Great Fairy",] },
  { name: "'Fliegt, kleine Ballons!' Nebenaufgabe", types: ["Side Quest","Woodland",] },
  { name: "'Versunkene Schätze' Nebenaufgabe", types: ["Side Quest","Central Hyrule",] },
  { name: "'Zwei in Eins' Schreinaufgabe", types: ["Shrine","Shrine Quest","Ridgeland",] },
  { name: "Beliebiger Bumerang", types: ["Equipment",] },
  { name: "Beliebiges Echsal-Equipment", types: ["Equipment",] },
  { name: "Ruder", types: ["Equipment",] },
  { name: "Beliebiges Moblin-Equipment", types: ["Equipment",] },
  { name: "Wischmopp", types: ["Equipment",] },
  { name: "Kühlendes Gericht", types: ["Cooking","Wasteland",] },
  { name: "Elektro-Gericht", types: ["Cooking",] },
  { name: "Scharfe-Medizin", types: ["Cooking",] },
  { name: "Elektro-Medizin", types: ["Cooking",] },
  { name: "Töte einen Feuer-/Meteor- Pyromagus", types: ["Wizzrobe",] },
  { name: "Töte einen Elektro-/Blitz- Pyromagus", types: ["Wizzrobe",] },
  { name: "Töte einen Hinox", types: ["Miniboss","Hinox",] },
  { name: "Töte einen roten Hinox", types: ["Miniboss","Hinox",] },
  { name: "Erreiche >500m in der Vogelvolk-Herausforderung", types: ["Minigame","Ridgeland",] },
  { name: "Aktiviere den Ranelle-Turm", types: ["Tower","Lanayru",] },
  { name: "Aktiviere den Turm der Ebene", types: ["Tower","Central Hyrule",] },
  { name: "5 Nebenaufgaben", types: ["Side Quest",] },
];
bingoList[6] = [
  { name: "6 Tabanta-Turm Gebiet Krogs", types: ["Korok","Tabantha",] },
  { name: "6 Akkala-Turm Gebiet Krogs", types: ["Korok","Akkala",] },
  { name: "Damen-Set", types: ["Clothes","Wasteland","Rupee",] },
  { name: "Rot gefärbte Hylia-Kapuze", types: ["Clothes","Hylian Gear","Hateno",] },
  { name: "Gelb gefärbte Hylia-Kapuze", types: ["Clothes","Hylian Gear","Hateno",] },
  { name: "Lila gefärbte Hylia-Kapuze", types: ["Clothes","Hylian Gear","Hateno",] },
  { name: "Grün gefärbte Hylia-Kapuze", types: ["Clothes","Hylian Gear","Hateno",] },
  { name: "Hellgelb gefärbte Hylia-Kapuze", types: ["Clothes","Hylian Gear","Hateno",] },
  { name: "Grau gefärbte Hylia-Kapuze", types: ["Clothes","Hylian Gear","Hateno",] },
  { name: "’Kokos Küche 3’ Nebenaufgabe", types: ["Side Quest","Dueling Peaks",] },
  { name: "'Schleichende Liebe' Nebenaufgabe", types: ["Side Quest","Faron",] },
  { name: "'Die Banditen der Prärie' Nebenaufgabe", types: ["Side Quest","Lake",] },
  { name: "'Das Pferd der Könige' Nebenaufgabe", types: ["Side Quest","Central Hyrule","Horse","Stamina",] },
  { name: "'Die verfluchte Statue' Schreinaufgabe", types: ["Shrine","Shrine Quest","Hateno",] },
  { name: "Fischerharpune", types: ["Equipment",] },
  { name: "3 identische Waffen", types: ["Equipment",] },
  { name: "Brandschutz-Medizin", types: ["Cooking",] },
  { name: "Gekochtes Ei", types: ["Cooking",] },
  { name: "Töte einen Eis-/Polar- Pyromagus", types: ["Wizzrobe",] },
  { name: "Silberner Rubin", types: ["Rupee",] },
  { name: "Aktiviere den Tabanta-Turm", types: ["Tower","Tabantha",] },
  { name: "Aktiviere den Turm der Wälder", types: ["Tower","Woodland",] },
  { name: "6 Nebenaufgaben", types: ["Side Quest",] },
];
bingoList[7] = [
  { name: "15 Krogs", types: ["Korok",] },
  { name: "Orni-Gewand", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Tabantha",] },
  { name: "Orni-Hose", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Tabantha",] },
  { name: "Zora-Helm", types: ["Clothes","Zora Gear","Lanayru",] },
  { name: "Zora-Rüstung", types: ["Clothes","Zora Gear","Lanayru",] },
  { name: "Blau gefärbte Hylia-Kapuze", types: ["Clothes","Hylian Gear","Hateno",] },
  { name: "Weiß gefärbte Hylia-Kapuze", types: ["Clothes","Hylian Gear","Hateno",] },
  { name: "Hellblau gefärbte Hylia-Kapuze", types: ["Clothes","Hylian Gear","Hateno",] },
  { name: "Orange gefärbte Hylia-Kapuze", types: ["Clothes","Hylian Gear","Hateno",] },
  { name: "Karmesinrot gefärbte Hylia-Kapuze", types: ["Clothes","Hylian Gear","Hateno",] },
  { name: "Braun gefärbte Hylia-Kapuze", types: ["Clothes","Hylian Gear","Hateno",] },
  { name: "’Kokos Küche 4’ Nebenaufgabe", types: ["Side Quest","Dueling Peaks",] },
  { name: "'Schabernack mit Schafen' Nebenaufgabe", types: ["Side Quest","Hateno",] },
  { name: "'Ein Mittel gegen die Hitze Side' Nebenaufgabe", types: ["Side Quest","Wasteland",] },
  { name: "'Der Kopfsprung' Nebenaufgabe", types: ["Side Quest","Lanayru",] },
  { name: "3 ‘Turm der Zwillingsberge’ Gebiet Schreine", types: ["Shrine","Dueling Peaks",] },
  { name: "'Das gekrönte Tier' Schreinaufgabe", types: ["Shrine","Shrine Quest","Hateno","Horse",] },
  { name: "'Das Gemälde des Stalls' Schreinaufgabe", types: ["Shrine","Shrine Quest","Eldin",] },
  { name: "Beliebiges Zora-Equipment (keine Rüstung)", types: ["Equipment",] },
  { name: "Beliebige Eis-Waffe", types: ["Equipment",] },
  { name: "Feenwasser", types: ["Cooking",] },
  { name: "Ausdauer-Festtagsgulasch", types: ["Cooking",] },
  { name: "Beliebige Schmorkrabbe", types: ["Cooking",] },
  { name: "2 Ausdauercontainer", types: ["Shrine","Stamina",] },
  { name: "Lies Robelos Tagebuch", types: ["Akkala",] },
  { name: "Aktiviere den Gerudo-Turm", types: ["Tower","Gerudo",] },
  { name: "Aktiviere den Eldin-Turm", types: ["Tower","Eldin",] },
  { name: "7 Nebenaufgaben", types: ["Side Quest",] },
];
bingoList[8] = [
  { name: "7 ‘Turm der Ebene’ Gebiet Krogs", types: ["Korok","Plateau",] },
  { name: "9 ‘Turm der Zwillingsberge’ Gebiet Krogs", types: ["Korok","Dueling Peaks",] },
  { name: "9 Hateno-Turm Gebiet Krogs", types: ["Korok","Hateno",] },
  { name: "9 ‘Turm des Sees’ Gebiet Krogs", types: ["Korok","Lake",] },
  { name: "6 Gerudo-Turm Gebiet Krogs", types: ["Korok","Gerudo",] },
  { name: "6 Hebra-Turm Gebiet Krogs", types: ["Korok","Hebra","Cold Resistance",] },
  { name: "6 Eldin-Turm Gebiet Krogs", types: ["Korok","Eldin",] },
  { name: "9 ‘Turm der Ebene’ Gebiet Krogs", types: ["Korok","Central Hyrule",] },
  { name: "Hylia-Kapuze ★", types: ["Clothes","Hylian Gear","Rupee","Great Fairy","Bokoblin",] },
  { name: "Hylia-Gewand ★", types: ["Clothes","Hylian Gear","Rupee","Great Fairy","Bokoblin",] },
  { name: "Hylia-Hose ★", types: ["Clothes","Hylian Gear","Rupee","Great Fairy","Bokoblin",] },
  { name: "Hylia-Set (Soldat)", types: ["Clothes","Soldier Gear","Rupee","Hateno",] },
  { name: "Anti-Schnee-Federn", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Tabantha",] },
  { name: "Anti-Feuer-Rüstung", types: ["Clothes","Flame Gear","Eldin","Rupee",] },
  { name: "Anti-Feuer-Hose", types: ["Clothes","Flame Gear","Eldin","Rupee",] },
  { name: "Schwarz gefärbte Hylia-Kapuze", types: ["Clothes","Hylian Gear","Hateno",] },
  { name: "Dunkelblau gefärbte Hylia-Kapuze", types: ["Clothes","Hylian Gear","Hateno",] },
  { name: "Rosa gefärbte Hylia-Kapuze", types: ["Clothes","Hylian Gear","Hateno",] },
  { name: "'Die Magie des Eises' Nebenaufgabe", types: ["Side Quest","Woodland","Wizzrobe",] },
  { name: "'Der Fleischfresser' Nebenaufgabe", types: ["Side Quest","Central Hyrule",] },
  { name: "3 ‘Turm des Sees’ Gebiet Schreine", types: ["Shrine","Lake",] },
  { name: "3 ‘Turm der Ebene’ Gebiet Schreine", types: ["Shrine","Central Hyrule",] },
  { name: "'Zähmer des Windes' Schreinaufgabe", types: ["Shrine","Shrine Quest","Lanayru",] },
  { name: "Beliebiges Wald-Equipment", types: ["Equipment",] },
  { name: "Beliebige Feuer-Waffe", types: ["Equipment",] },
  { name: "Beliebige Elektro-Waffe", types: ["Equipment",] },
  { name: "Beliebige Wächter-Lanze ", types: ["Equipment","Guardian",] },
  { name: "Obsttorte", types: ["Cooking",] },
  { name: "Riesenfischspieße", types: ["Cooking",] },
  { name: "Töte einen Iwarok (leuchtend)", types: ["Rupee","Gems","Miniboss","Talus",] },
  { name: "Töte einen Wächter (Läufer)", types: ["Miniboss","Guardian",] },
  { name: "Registriere das königliche Pferd", types: ["Horse","Central Hyrule","Stamina",] },
  { name: "Sprich mit Kilton", types: ["Kilton","Akkala",] },
  { name: "Golder Rubin", types: ["Rupee",] },
  { name: "5 Herzcontainer", types: ["Shrine","Heart",] },
  { name: "Erlege 5 Hirsche beim Hirschjagd-Minispiel", types: ["Minigame","Hateno",] },
  { name: "Aktiviere den Hebra-Turm", types: ["Tower","Hebra","Cold Resistance",] },
  { name: "8 Nebenaufgaben", types: ["Side Quest",] },
];
bingoList[9] = [
  { name: "9 Phirone-Turm Gebiet Krogs", types: ["Korok","Faron",] },
  { name: "9 ‘Turm der Hügel’ Gebiet Krogs", types: ["Korok","Ridgeland",] },
  { name: "9 Ranelle-Turm Gebiet Krogs", types: ["Korok”,“Lanayru",] },
  { name: "Kletterstiefel", types: ["Clothes","Climbing Gear","Hateno",] },
  { name: "'Das Leibgericht' Nebenaufgabe", types: ["Side Quest","Faron",] },
  { name: "'Geheimniskrämerei' Nebenaufgabe", types: ["Side Quest","Wasteland","Radiant Gear","Desert Gear",] },
  { name: "'Edle Steine' Nebenaufgabe", types: ["Side Quest","Wasteland","Gems",] },
  { name: "'Verschwunden im Tal' Nebenaufgabe", types: ["Side Quest","Wasteland",] },
  { name: "'Löschechsenjagd' Nebenaufgabe", types: ["Side Quest","Eldin","Flame Gear",] },
  { name: "8 Schreine", types: ["Shrine",] },
  { name: "3 ‘Turm der Hügel’ Gebiet Schreine ", types: ["Shrine","Ridgeland",] },
  { name: "'Doppelte Erinnerung' Schreine", types: ["Shrine","Shrine Quest","Dueling Peaks",] },
  { name: "'Die Donnerprüfung' Schreinaufgabe", types: ["Shrine","Shrine Quest","Faron",] },
  { name: "1 Schrein aus ‘Die Prüfungen der Krogs’", types: ["Shrine","Shrine Quest","Woodland",] },
  { name: "Beliebiges Wächter-Schwert", types: ["Equipment","Guardian",] },
  { name: "3 identische Schilde", types: ["Equipment",] },
  { name: "3 identische Bögen", types: ["Equipment",] },
  { name: "Apfelkuchen", types: ["Cooking","Tabantha",] },
  { name: "Curry-Pilaw", types: ["Cooking",] },
  { name: "Töte einen blauen Hinox", types: ["Miniboss","Hinox",] },
  { name: "Schaffe Rumpelgolf", types: ["Minigame","Woodland",] },
  { name: "Aktiviere den Akkala-Turm", types: ["Tower","Akkala",] },
];
bingoList[10] = [
  { name: "9 ‘Turm der Wüste’ Gebiet Krogs", types: ["Korok","Wasteland",] },
  { name: "9 Tabanta-Turm Gebiet Krogs", types: ["Korok","Tabantha",] },
  { name: "9 ‘Turm der Wälder’ Gebiet Krogs", types: ["Korok","Woodland",] },
  { name: "9 Akkala-Turm Gebiet Krogs", types: ["Korok","Akkala",] },
  { name: "Kletterkopftuch ★", types: ["Clothes","Climbing Gear","Great Fairy",] },
  { name: "Barbarenkleider", types: ["Clothes","Barbarian Gear","Wasteland",] },
  { name: "'Fischgründe' Nebenaufgaben", types: ["Side Quest","Faron",] },
  { name: "'Riesiger Reisegefährte' Nebenaufgabe", types: ["Side Quest","Lake","Horse","Stamina",] },
  { name: "3 Phirone-Turm Gebiet Schreine", types: ["Shrine","Faron",] },
  { name: "3 ‘Turm der Wüste’ Gebiet Schreine", types: ["Shrine","Wasteland",] },
  { name: "'Kraftprobe (Mittel)' Schrein", types: ["Shrine","Guardian",] },
  { name: "'Geheimnis der drei Zedern’ Schreinaufgabe", types: ["Shrine","Shrine Quest","Hateno",] },
  { name: "'Prüfung der Wüste' Schreinaufgabe", types: ["Shrine","Shrine Quest","Wastelands","Barbarian Gear",] },
  { name: "'Verschwinde, Sandsturm!' Schreinaufgabe", types: ["Shrine","Shrine Quest","Wastelands",] },
  { name: "'Das Auge des Strudels' Schreinaufgabe", types: ["Shrine","Shrine Quest","Akkala",] },
  { name: "'Linkes Auge des Schädels' Schreinaufgabe", types: ["Shrine","Shrine Quest","Akkala",] },
  { name: "Beliebiges Wächter-Schild", types: ["Equipment","Guardian",] },
  { name: "Pilzcremesuppe", types: ["Cooking",] },
  { name: "Strike im Schneeball-Kegeln", types: ["Minigame","Hebra","Cold Resistance",] },
  { name: "9 Nebenaufgaben", types: ["Side Quest",] },
];
bingoList[11] = [
  { name: "20 Krogs", types: ["Korok",] },
  { name: "Bezahle 2 große Feen", types: ["Rupee","Great Fairy",] },
  { name: "Hylia-Rüstung ★", types: ["Clothes","Soldier Gear","Rupee","Great Fairy",] },
  { name: "Wüsten-Stirnschutz", types: ["Clothes","Desert Gear","Wasteland","Rupee",] },
  { name: "Wüsten-Beinschutz", types: ["Clothes","Desert Gear","Wasteland","Rupee",] },
  { name: "Isolierhelm ★", types: ["Clothes","Rubber Gear","Faron","Great Fairy",] },
  { name: "Ninja-Maske ★", types: ["Clothes","Stealth Gear","Rupee","Great Fairy",] },
  { name: "Ninja-Anzug ★", types: ["Clothes","Stealth Gear","Rupee","Great Fairy",] },
  { name: "Ninja-Hose ★", types: ["Clothes","Stealth Gear","Rupee","Great Fairy",] },
  { name: "Ninja-Set", types: ["Clothes","Stealth Gear","Rupee","Dueling Peaks",] },
  { name: "Barbarenmaske", types: ["Clothes","Barbarian Gear","Akkala",] },
  { name: "'Ein ausdauernder Verehrer' Nebenaufgabe", types: ["Side Quest","Hateno",] },
  { name: "3 Hateno-Turm Gebiet Schreine", types: ["Shrine","Hateno",] },
  { name: "3 Tabanta-Turm Gebiet Schreine", types: ["Shrine","Tabantha",] },
  { name: "3 ‘Turm der Wälder’ Gebiet Schreine", types: ["Shrine","Woodland",] },
  { name: "3 Akkala-Turm Gebiet Schreine", types: ["Shrine","Akkala",] },
  { name: "'Schweigende Statuen' Schreinaufgabe", types: ["Shrine","Shrine Quest","Wastelands",] },
  { name: "'Das alte Tagebuch' Schreinaufgabe", types: ["Shrine","Shrine Quest","Wastelands","Cold Resistance",] },
  { name: "Schrein im vergessenen Tempel", types: ["Shrine","Shrine Quest","Woodland",] },
  { name: "'Prüfung in der Finsternis' Schreinaufgabe", types: ["Shrine","Shrine Quest","Woodland",] },
  { name: "'Die Schneidklippen' Schreinaufgabe", types: ["Shrine","Shrine Quest","Eldin",] },
  { name: "’Prüfung auf einsamer Insel’ Schrein Quest", types: ["Shrine","Shrine Quest","Akkala","Barbarian Gear",] },
  { name: "Beliebiges Garde-Equipment", types: ["Equipment",] },
  { name: "Meteor-, Blitz- oder Polar-Stab", types: ["Equipment","Wizzrobe",] },
  { name: "Beliebige Wächter-Axt", types: ["Equipment","Guardian",] },
  { name: "Monsterkuchen", types: ["Cooking","Kilton",] },
  { name: "Wildbeeren Crêpe", types: ["Cooking","Tabantha",] },
  { name: "Töte einen Iwarok (selten)", types: ["Rupee","Miniboss","Talus",] },
  { name: "Registriere das Riesenpferd", types: ["Horse","Lake","Stamina",] },
  { name: "Steige auf ein Bär", types: ["Horse","Stamina",] },
  { name: "Steige auf ein Stalpferd", types: ["Horse",] },
  { name: "2000 Rubine", types: ["Rupee",] },
  { name: "Lies das Tagebuch des Königs", types: ["Hyrule Castle",] },
  { name: "Mache ein Selfie mit Maronus", types: ["Dueling Peaks","Camera",] },
  { name: "Shiekah-Sensor +", types: ["Camera","Rune Upgrade","Hateno",] },
];
bingoList[12] = [
  { name: "12 ‘Turm der Zwillingsberge’ Gebiet Krogs", types: ["Korok","Dueling Peaks",] },
  { name: "9 Eldin-Turm Gebiet Krogs", types: ["Korok","Eldin",] },
  { name: "12 ‘Turm der Ebene’", types: ["Korok","Central Hyrule",] },
  { name: "Reckengewand", types: ["Clothes","Champion","Camera",] },
  { name: "Hylia-Helm ★", types: ["Clothes","Soldier Gear","Rupee","Great Fairy",] },
  { name: "Hylia-Beinschutz ★", types: ["Clothes","Soldier Gear","Rupee","Great Fairy",] },
  { name: "Wüsten-Schulterschutz", types: ["Clothes","Desert Gear","Wasteland","Rupee",] },
  { name: "Isolierrüstung ★", types: ["Clothes","Rubber Gear","Ridgeland","Great Fairy",] },
  { name: "Isolierhose ★", types: ["Clothes","Rubber Gear","Faron","Great Fairy",] },
  { name: "Zora-Beinschutz", types: ["Clothes","Zora Gear","Lanayru","Camera",] },
  { name: "Bernstein-Ohrringe", types: ["Clothes","Gems","Rupee","Wasteland",] },
  { name: "'Königliche Küche' Nebenaufgabe", types: ["Side Quest","Central Hyrule","Cooking",] },
  { name: "9 Schreine", types: ["Shrine",] },
  { name: "4 Schreinaufgaben", types: ["Shrine","Shrine Quest",] },
  { name: "'Die sieben Kriegerinnen' Schreinaufgabe", types: ["Shrine","Shrine Quest","Wastelands",] },
  { name: "'Wandgemälde' Schreinaufgabe", types: ["Shrine","Shrine Quest","Gerudo","Cold Resistance",] },
  { name: "'Worauf der Schatten weist' Schreinaufgabe", types: ["Shrine","Shrine Quest","Gerudo",] },
  { name: "Sammle eine Erinnerung", types: ["Camera",] },
  { name: "Töte ein Magmarok", types: ["Rupee","Gems","Miniboss","Talus","Eldin",] },
  { name: "Lies Zeldas Tagebuch", types: ["Hyrule Castle",] },
  { name: "Mache ein Selfie mit Kashiwa", types: ["Camera",] },
  { name: "Beliebiges Faroda-Item", types: ["Dragon",] },
  { name: "3 Ranelle-Turm Gebiet Schreine", types: ["Shrine","Lanayru",] },
  { name: "10 Nebenaufgaben", types: ["Side Quest",] },
  { name: "'Fotografisches Gedächtnis' Nebenaufgabe", types: ["Side Quest","Hateno","Camera",] },
  { name: "Schneestiefel", types: ["Clothes","Boots","Side Quest","Gerudo","Camera",] },
];
bingoList[13] = [
  { name: "12 Hateno-Turm Gebiet Krogs", types: ["Korok","Hateno",] },
  { name: "12 ‘Turm des Sees’ Gebiet Krogs", types: ["Korok","Lake",] },
  { name: "12 ‘Turm der Hügel’ Gebiet Krogs", types: ["Korok","Ridgeland",] },
  { name: "9 Hebra-Turm Gebiet Krogs", types: ["Korok","Hebra","Cold Resistance",] },
  { name: "Anti-Feuer-Helm", types: ["Clothes","Flame Gear","Eldin","Rupee",] },
  { name: "Zora-Rüstung ★", types: ["Clothes","Zora Gear","Great Fairy","Lizalfos",] },
  { name: "Barbarenhose", types: ["Clothes","Barbarian Gear","Hebra",] },
  { name: "3 Hebra-Turm Gebiet Schreine", types: ["Shrine","Hebra","Cold Resistance",] },
  { name: "3 Eldin-Turm Gebiet Schreine", types: ["Shrine","Eldin",] },
  { name: "'Im Rachen des Drachen' Schreinaufgabe", types: ["Shrine","Shrine Quest","Lake","Dragon",] },
  { name: "'Ausdauer-Härtetest' Schreinaufgabe", types: ["Shrine","Shrine Quest","Gerudo",] },
  { name: "Töte einen Glacirok", types: ["Rupee","Gems","Miniboss","Talus","Cold Resistance",] },
  { name: "Töte einen Wächter (Geschütz)", types: ["Miniboss","Guardian","Hyrule Castle",] },
  { name: "5 Tiere im Hyrule-Handbuch", types: ["Camera","Compendium",] },
  { name: "5 Monster im Hyrule-Handbuch", types: ["Camera","Compendium",] },
  { name: "5 Waffen im Hyrule-Handbuch", types: ["Camera","Compendium",] },
  { name: "Mache ein Selfie mit Sidon", types: ["Lanayru","Camera",] },
  { name: "Beliebiges Eldra-Item", types: ["Dragon",] },
  { name: "Schaffe “Anfänger” im Schldschlitter-Minispiel", types: ["Minigame","Hebra","Cold Resistance",] },
  { name: "'Tanzende Lichter' Nebenaufgabe", types: ["Side Quest","Dueling Peaks","Heirloom","Camera",] },
];
bingoList[14] = [
  { name: "25 Krogs", types: ["Korok",] },
  { name: "12 Phirone-Turm Gebiet Krogs", types: ["Korok","Faron",] },
  { name: "9 Gerudo-Turm Gebiet Krogs", types: ["Korok","Gerudo",] },
  { name: "12 Tabanta-Turm Gebiet Krogs", types: ["Korok","Tabantha",] },
  { name: "12 ‘Turm der Wälder’ Gebiet Krogs", types: ["Korok","Woodland",] },
  { name: "12 Akkala-Turm Krogs", types: ["Korok","Akkala",] },
  { name: "12 Ranelle-Turm Gebiet Krogs", types: ["Korok”,”Lanayru",] },
  { name: "Bezahle den Gott der Pferde", types: ["Lake","Rupee",] },
  { name: "Zora-Helm ★", types: ["Clothes","Zora Gear","Great Fairy","Lizalfos",] },
  { name: "Leuchtmaske", types: ["Clothes","Radiant Gear","Rupee","Gems","Wasteland",] },
  { name: "Leuchtanzug", types: ["Clothes","Radiant Gear","Rupee","Gems","Wasteland",] },
  { name: "Leuchthose", types: ["Clothes","Radiant Gear","Rupee","Gems","Wasteland",] },
  { name: "Topas-Ohrringe", types: ["Clothes","Gems","Rupee","Wasteland",] },
  { name: "'Curry gegen die Kälte' Nebenaufgabe", types: ["Side Quest","Tabantha","Eldin",] },
  { name: "10 Schreine", types: ["Shrine",] },
  { name: "3 Gerudo-Turm Gebiet Schreine", types: ["Shrine","Gerudo","Cold Resistance",] },
  { name: "'Die Summe der Teile' Schreinaufgabe", types: ["Shrine","Shrine Quest","Faron","Camera",] },
  { name: "Sammle 2 Erinnerungen", types: ["Camera",] },
  { name: "Töte einen schwarzen Hinox", types: ["Miniboss","Hinox",] },
  { name: "Töte einen Stalhinox", types: ["Miniboss","Hinox",] },
  { name: "Töte einen Wächter (Flieger)", types: ["Miniboss","Guardian",] },
  { name: "3 Ausdauercontainer", types: ["Shrine","Stamina",] },
  { name: "Beliebiges Naydra-Item", types: ["Hateno","Cold Resistance","Dragon",] },
  { name: "Bombenmodul +", types: ["Camera","Rune Upgrade","Hateno",] },
  { name: "Aktiviere 4 Türme", types: ["Tower",] },
  { name: "11 Nebenaufgaben", types: ["Side Quest",] },
];
bingoList[15] = [
  { name: "12 ‘Turm der Wüste’ Gebiet Krogs", types: ["Korok","Wasteland",] },
  { name: "Orni-Gewand ★", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Great Fairy",] },
  { name: "Orni-Hose ★", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Great Fairy",] },
  { name: "Orni-Set", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Tabantha",] },
  { name: "Anti-Feuer-Hose ★", types: ["Clothes","Flame Gear","Eldin","Rupee","Great Fairy",] },
  { name: "Kletterstiefel ★", types: ["Clothes","Climbing Gear","Great Fairy",] },
  { name: "Saphir-Stirnband", types: ["Clothes","Gems","Rupee","Wasteland",] },
  { name: "Rhodonit-Stirnband", types: ["Clothes","Gems","Rupee","Wasteland",] },
  { name: "Bokblin-Maske", types: ["Clothes","Kilton",] },
  { name: "'Geheimnis des Todesbergs' Nebenaufgabe", types: ["Side Quest","Eldin",] },
  { name: "'Suche nach dem Leunen' Nebenaufgabe", types: ["Side Quest","Lanayru","Camera","Zora Gear",] },
  { name: "'Die schwarze Serie' Nebenaufgabe", types: ["Side Quest","Hyrule Castle",] },
  { name: "'Prüfung in der Wildnis' Schreinaufgabe", types: ["Shrine","Shrine Quest","Faron",] },
  { name: "'Geheimnis der drei Riesen' Schreinaufgabe", types: ["Shrine","Shrine Quest","Faron","Hinox",] },
  { name: "'Der einsame Baum' Schreinaufgabe", types: ["Shrine","Shrine Quest","Hebra","Cold Resistance",] },
  { name: "'Prüfung auf der Klippe' Schreinaufgabe", types: ["Shrine","Shrine Quest","Hebra","Cold Resistance","Barbarian Gear",] },
  { name: "Windklinge", types: ["Equipment","Wasteland",] },
  { name: "Töte einen Leunen", types: ["Miniboss","Lynel",] },
  { name: "Töte ein Moldora", types: ["Miniboss","Molduga","Wasteland",] },
  { name: "6 Herzcontainer", types: ["Shrine","Heart",] },
  { name: "Mache ein Selfie mit Riju", types: ["Wasteland","Camera",] },
  { name: "Mache brennend ein Selfie", types: ["Eldin","Camera",] },
  { name: "Stasismodul +", types: ["Camera","Rune Upgrade","Hateno",] },
  { name: "10 Waffen im Hyrule-Handbuch", types: ["Camera","Compendium",] },
];
bingoList[16] = [
  { name: "15 ‘Turm der Zwillingsberge’ Gebiet Krogs", types: ["Korok","Dueling Peaks",] },
  { name: "15 ‘Turm der Ebene’ Gebiet Krogs", types: ["Korok","Central Hyrule",] },
  { name: "Reckengewand ★", types: ["Clothes","Champion","Camera","Great Fairy",] },
  { name: "Anti-Schnee-Feedern ★", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Great Fairy",] },
  { name: "Isolier-Set", types: ["Clothes","Rubber Gear","Faron","Ridgeland",] },
  { name: "Anti-Feuer-Rüstung ★", types: ["Clothes","Flame Gear","Eldin","Rupee","Great Fairy",] },
  { name: "Opal-Ohrringe", types: ["Clothes","Gems","Rupee","Wasteland",] },
  { name: "'Das Moldora-Herz' Nebenaufgabe", types: ["Side Quest","Wasteland","Molduga",] },
  { name: "'Lehrgeld' Nebenaufgabe", types: ["Side Quest","Eldin","Talus",] },
  { name: "'Kleine, große Wünsche' Nebenaufgabe", types: ["Side Quest","Akkala",] },
  { name: "'Der geheimnisvolle Rumi' Nebenaufgabe", types: ["Side Quest","Wasteland","Camera",] },
  { name: "12 Nebenaufgaben", types: ["Side Quest",] },
  { name: "10 Tiere im Hyrule-Handbuch", types: ["Camera","Compendium",] },
  { name: "10 Monster im Hyrule-Handbuch", types: ["Camera","Compendium",] },
];
bingoList[17] = [
  { name: "15 Hateno-Turm Gebiet Krogs", types: ["Korok","Hateno",] },
  { name: "15 ‘Turm des Sees’ Gebiet Krogs", types: ["Korok","Lake",] },
  { name: "12 Gerudo-Turm Gebiet Krogs", types: ["Korok","Gerudo",] },
  { name: "15 ‘Turm der Hügel’ Gebiet Krogs", types: ["Korok","Ridgeland",] },
  { name: "12 Hebra-Turm Gebiet Krogs", types: ["Korok","Hebra","Cold Resistance",] },
  { name: "12 Eldin-Turm Gebiet Krogs", types: ["Korok","Eldin",] },
  { name: "Wüsten-Stirnschutz ★", types: ["Clothes","Desert Gear","Wasteland","Rupee","Great Fairy",] },
  { name: "Wüsten-Schulterschutz ★", types: ["Clothes","Desert Gear","Wasteland","Rupee","Great Fairy",] },
  { name: "Wüsten-Beinschutz ★", types: ["Clothes","Desert Gear","Wasteland","Rupee","Great Fairy",] },
  { name: "Sandstiefel", types: ["Clothes","Boots","Side Quest","Gerudo",] },
  { name: "'Die achte Kriegerin' Nebenaufgabe", types: ["Side Quest","Wasteland","Gerudo","Boots","Cold Resistance","Camera",] },
  { name: "11 Schreine", types: ["Shrine",] },
  { name: "5 Schreinaufgaben", types: ["Shrine","Shrine Quest",] },
  { name: "'Im Anblick des Wächters' Schreinaufgabe", types: ["Shrine","Shrine Quest","Lake","Camera","Guardian",] },
  { name: "'Die Quelle der Kraft' Schreinaufgabe", types: ["Shrine","Shrine Quest","Akkala","Dragon",] },
  { name: "Beliebiges Equipment eines Leunen", types: ["Equipment","Lynel",] },
  { name: "Feuer-, Eis- und Elektro-Waffe", types: ["Equipment",] },
  { name: "Triff 20 Ziele bei der Flugplatz-Prüfung", types: ["Minigame","Tabantha","Cold Resistance",] },
  { name: "Aktiviere 5  Türme", types: ["Tower",] },
  { name: "15 Waffen im Hyrule-Handbuch", types: ["Camera","Compendium",] },
];
bingoList[18] = [
  { name: "15 Tiere im Hyrule-Handbuch", types: ["Camera","Compendium",] },
  { name: "15 Monster im Hyrule-Handbuch", types: ["Camera","Compendium",] },
  { name: "30 Krogs", types: ["Korok",] },
  { name: "15 Phirone-Turm Gebiet Krogs", types: ["Korok","Faron",] },
  { name: "15 Akkala-Turm Gebiet Krogs", types: ["Korok","Akkala",] },
  { name: "15 Ranelle-Turm Gebiet Krogs", types: ["Korok”,”Lanayru",] },
  { name: "Wüsten-Set", types: ["Clothes","Desert Gear","Wasteland","Rupee",] },
  { name: "Anti-Feuer-Helm ★", types: ["Clothes","Flame Gear","Eldin","Rupee","Great Fairy",] },
  { name: "Zora-Beinschutz ★", types: ["Clothes","Zora Gear","Great Fairy","Lizalfos","Camera",] },
  { name: "Leuchtmaske ★", types: ["Clothes","Radiant Gear","Rupee","Gems","Great Fairy",] },
  { name: "Schneestiefel ★", types: ["Clothes","Boots","Side Quest","Great Fairy","Camera",] },
  { name: "'Verborgene Kräfte' Nebenaufgabe", types: ["Side Quest","Hateno","Camera",] },
  { name: "'Verdächtiger Verkäufer' Nebenaufgabe", types: ["Side Quest","Akkala","Kilton","Camera",] },
  { name: "12 Schreine", types: ["Shrine",] },
  { name: "'Schatz der Ranelle-Spitze' Schreinaufgabe", types: ["Shrine","Shrine Quest","Hateno","Cold Resistance","Dragon",] },
  { name: "Sammle 3 Erinnerungen", types: ["Camera",] },
  { name: "Hylia-Schild", types: ["Miniboss","Hinox","Hyrule Castle",] },
  { name: "Steige auf den Herrn der Wildnis", types: ["Horse","Ridgeland","Stamina",] },
  { name: "Kaufe ein Haus", types: ["Hateno","Rupee",] },
  { name: "Kraftprobe (Schwer) Schrein", types: ["Shrine","Guardian",] },
];
bingoList[19] = [
  { name: "15 ‘Turm der Wüste’ Gebiet Krogs", types: ["Korok","Wasteland",] },
  { name: "15 Tabanta-Turm Gebiet Krogs", types: ["Korok","Tabantha",] },
  { name: "15 ‘Turm der Wälder’ Gebiet Krogs", types: ["Korok","Woodland",] },
  { name: "Leuchtanzug ★", types: ["Clothes","Radiant Gear","Rupee","Gems","Great Fairy",] },
  { name: "Leuchthose ★", types: ["Clothes","Radiant Gear","Rupee","Gems","Great Fairy",] },
  { name: "Bernstein-Ohrringe ★", types: ["Clothes","Gems","Rupee","Great Fairy",] },
  { name: "'Ein Bild vom Knochenpferd!' Nebenaufgabe", types: ["Side Quest","Hebra","Camera",] },
  { name: "'Das gestohlene Juwel' Schreinaufgabe", types: ["Shrine","Shrine Quest","Dueling Peaks","Heirloom","Camera",] },
  { name: "'Der verlorene Bruder' Schreinaufgabe", types: ["Shrine","Shrine Quest","Eldin",] },
  { name: "Ein Titan-Hauptziel", types: ["Divine Beast",] },
  { name: "'Windtitan Vah Medoh' Hauptziel", types: ["Divine Beast","Tabantha","Cold Resistance",] },
  { name: "Revalis Sturm", types: ["Divine Beast","Tabantha","Cold Resistance",] },
  { name: "Töte den Leunen in der Arena-Ruine", types: ["Miniboss","Lynel","Central Hyrule",] },
  { name: "Aktiviere 6 Türme", types: ["Tower",] },
  { name: "13 Nebenaufgaben", types: ["Side Quest",] },
  { name: "Kletterhandschuhe", types: ["Clothes","Climbing Gear","Hateno",] },
];
bingoList[20] = [
  { name: "15 Gerudo-Turm Gebiet Krogs", types: ["Korok","Gerudo",] },
  { name: "15 Hebra-Turm Gebiet Krogs", types: ["Korok","Hebra","Cold Resistance",] },
  { name: "15 Eldin-Turm Gebiet Krogs", types: ["Korok","Eldin",] },
  { name: "Zora-Set", types: ["Clothes","Zora Gear","Lanayru","Camera",] },
  { name: "Barbarenmaske ★", types: ["Clothes","Barbarian Gear","Great Fairy","Lynel",] },
  { name: "Barbarenkleider ★", types: ["Clothes","Barbarian Gear","Great Fairy","Lynel",] },
  { name: "Topas-Ohrringe ★", types: ["Clothes","Gems","Rupee","Great Fairy",] },
  { name: "Diamant-Stirnband", types: ["Clothes","Gems","Rupee","Wasteland",] },
  { name: "'Das vergessene Schwert' Nebenaufgabe", types: ["Side Quest","Wasteland","Gerudo","Boots","Cold Resistance","Camera",] },
  { name: "'Finde Kihl!' Nebenaufgabe", types: ["Side Quest","Tabantha",] },
  { name: "'Edelstein-Import' Nebenaufgabe", types: ["Side Quest","Eldin","Gems",] },
  { name: "'Der andere Forscher' Nebenaufgabe", types: ["Side Quest","Akkala","Camera",] },
  { name: "6 Schreinaufgaben", types: ["Shrine","Shrine Quest",] },
  { name: "'Donnertitan Vah Naboris' Hauptziel", types: ["Divine Beast","Lanayru",] },
  { name: "Miphas Gebet", types: ["Divine Beast","Lanayru",] },
  { name: "Sammle 4 Erinnerungen", types: ["Camera",] },
  { name: "4 Ausdauercontainer", types: ["Shrine","Stamina",] },
  { name: "20 Waffen im Hyrule-Handbuch", types: ["Camera","Compendium",] },
];
bingoList[21] = [
  { name: "20 Tiere im Hyrule-Handbuch", types: ["Camera","Compendium",] },
  { name: "20 Monster im Hyrule-Handbuch", types: ["Camera","Compendium",] },
  { name: "35 Krogs", types: ["Korok",] },
  { name: "Bezahle 3 große Feen", types: ["Rupee","Great Fairy",] },
  { name: "Anti-Feuer-Set", types: ["Clothes","Flame Gear","Eldin","Rupee",] },
  { name: "Barbarenhose ★", types: ["Clothes","Barbarian Gear","Great Fairy","Lynel",] },
  { name: "Leucht-Set", types: ["Clothes","Radiant Gear","Rupee","Gems","Wasteland",] },
  { name: "Opal-Ohrringe ★", types: ["Clothes","Gems","Rupee","Great Fairy",] },
  { name: "Saphir-Stirnband ★", types: ["Clothes","Gems","Rupee","Great Fairy",] },
  { name: "Rhodonit-Stirnband ★", types: ["Clothes","Gems","Rupee","Great Fairy",] },
  { name: "13 Schreine", types: ["Shrine",] },
  { name: "7 Schreinaufgaben", types: ["Shrine","Shrine Quest",] },
  { name: "'Ein Trank für müde Geister' Schreinaufgabe", types: ["Shrine","Shrine Quest","Wastelands",] },
  { name: "'Die Brüder-Felsen' Schreinaufgabe", types: ["Shrine","Shrine Quest","Tabantha",] },
  { name: "'Das Rätsel des Orni-Lieds' Schreinaufgabe", types: ["Shrine","Shrine Quest","Tabantha",] },
  { name: "Sammle 5 Erinnerungen", types: ["Camera",] },
  { name: "Scherzhammer", types: ["Equipment","Kilton",] },
  { name: "7 Herzcontainer", types: ["Shrine","Heart",] },
  { name: "Verbessere alle Module", types: ["Camera","Rune Upgrade","Hateno",] },
  { name: "'Das Lied des Reckenfestes' Schreinaufgabe", types: ["Shrine","Shrine Quest","Lanayru",] },
];
bingoList[22] = [
  { name: "'Rätselhaftes Hyrule' Nebenaufgabe", types: ["Side Quest","Woodland","Lynel",] },
  { name: "'Frischer Froschregen' Nebenaufgabe", types: ["Side Quest","Lanayru",] },
  { name: "'Der Leuchtsteinbruch' Nebenaufgabe", types: ["Side Quest","Lanayru","Gems",] },
  { name: "'Davongetrieben' Nebenaufgabe", types: ["Side Quest","Lanayru",] },
  { name: "14 Schreine", types: ["Shrine",] },
  { name: "8 Schreinaufgaben", types: ["Shrine","Shrine Quest",] },
  { name: "Aktiviere 7 Türme", types: ["Tower",] },
  { name: "14 Nebenaufgaben", types: ["Side Quest",] },
];
bingoList[23] = [
  { name: "40 Krogs", types: ["Korok",] },
  { name: "'Der Glacirok im Blizzar-Tal' Nebenaufgabe", types: ["Side Quest","Tabantha","Hebra","Cold Resistance",] },
  { name: "'Ein kleines Riesenproblem' Nebenaufgabe", types: ["Side Quest","Lanayru","Hinox",] },
  { name: "15 Schreine", types: ["Shrine",] },
  { name: "'Feuertitan Vah Rudania' Hauptziel", types: ["Divine Beast","Eldin",] },
  { name: "Daruks Schirm", types: ["Divine Beast","Eldin",] },
  { name: "Sammle 6 Erinnerungen", types: ["Camera",] },
  { name: "Lasse eine neue Reckenwaffe anfertigen", types: ["Equipment","Divine Beast","Gems",] },
  { name: "Kletterhandschuhe ★", types: ["Clothes","Climbing Gear","Great Fairy",] },
  { name: "Aktiviere 8 Türme", types: ["Tower",] },
];
bingoList[24] = [
  { name: "45 Krogs", types: ["Korok",] },
  { name: "'Kolossale Knochen' Nebenaufgabe", types: ["Side Quest","Camera",] },
  { name: "16 Schreine", types: ["Shrine",] },
  { name: "'Donnertitan Vah Naboris' Hauptziel", types: ["Divine Beast","Wasteland",] },
  { name: "Urbosas Zorn", types: ["Divine Beast","Wasteland",] },
  { name: "Besiege Ganon", types: ["Hyrule Castle",] },
  { name: "Aktiviere 9 Türme", types: ["Tower",] },
  { name: "Kletter-Set", types: ["Clothes","Climbing Gear",] },
];
bingoList[25] = [
  { name: "50 Krogs", types: ["Korok",] },
  { name: "'Gedenksteine' Nebenaufgabe", types: ["Side Quest","Lanayru",] },
  { name: "2 Titanen-Hauptziele", types: ["Divine Beast",] },
  { name: "'Die Suche nach Baretta' Nebenaufgabe", types: ["Side Quest","Wasteland",] },
  { name: "'Der Umweltsünder' Nebenaufgabe", types: ["Side Quest","Wasteland",] },
  { name: "'Der Champion' Schreinaufgabe", types: ["Shrine","Shrine Quest","Wastelands",] },
  { name: "Aktiviere 10 Türme", types: ["Tower",] },
  { name: "15 Nebenaufgaben", types: ["Side Quest",] },
  { name: "Barbaren-Set", types: ["Clothes","Barbarian Gear",] },
];

module.exports = bingoList;
