# Generated by Django 4.1.5 on 2023-01-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0032_alter_game_game_type_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='size',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
