# Generated by Django 4.1.5 on 2023-01-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0033_game_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='square',
            name='slot',
            field=models.IntegerField(),
        ),
    ]
