# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-06-06 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0033_auto_20240605_2204'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['uuid'], name='bingosync_p_uuid_88027c_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['uuid'], name='bingosync_r_uuid_70620b_idx'),
        ),
    ]
