# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-06-06 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0034_auto_20240605_2204'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['room', 'created_date'], name='bingosync_g_room_id_18733a_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['active'], name='bingosync_r_active_43cfb1_idx'),
        ),
    ]
