# Generated by Django 4.1.5 on 2023-01-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bingosync", "0034_alter_square_slot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="seed",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="newcardevent",
            name="seed",
            field=models.BigIntegerField(default=0),
        ),
    ]
