# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-06-07 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0035_auto_20240605_2228'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['created_date'], name='bingosync_r_created_833796_idx'),
        ),
    ]
