# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-06-11 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0036_auto_20240606_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_type', models.IntegerField(choices=[(1, 'Notice'), (2, 'Announcement'), (3, 'Warning'), (4, 'Error')])),
                ('visible_to_users', models.BooleanField(default=False)),
                ('visible_to_admins', models.BooleanField(default=False)),
                ('header', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
            ],
        ),
    ]
