# Generated by Django 5.0.6 on 2024-06-19 17:01

import bingosync.models.game_type
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0037_sitenotice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type_value',
            field=models.IntegerField(choices=bingosync.models.game_type.GameType.choices, verbose_name='Game Type'),
        ),
        migrations.AlterField(
            model_name='newcardevent',
            name='game_type_value',
            field=models.IntegerField(choices=bingosync.models.game_type.GameType.choices),
        ),
    ]
