# Generated by Django 5.0.6 on 2025-11-30 16:52

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0038_alter_game_game_type_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='player_count',
            field=models.SmallIntegerField(default=0),
        ),
    ]
