# Generated by Django 5.0.6 on 2025-11-30 17:53

from django.db import migrations

def set_player_count(apps, schema_editor):
    Room = apps.get_model('bingosync', 'Room')
    for room in Room.objects.all():
        room.player_count = len(room.player_set.all())
        room.save()

class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0039_room_player_count'),
    ]

    operations = [
        migrations.RunPython(set_player_count),
    ]
