# Generated by Django 5.0.6 on 2025-11-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0040_backfill_player_count'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['player_count'], name='bingosync_r_player__1ec0cd_idx'),
        ),
    ]
