# Generated by Django 5.0.6 on 2025-11-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0041_room_bingosync_r_player__1ec0cd_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='room',
            name='bingosync_r_created_833796_idx',
        ),
        migrations.RemoveIndex(
            model_name='room',
            name='bingosync_r_player__1ec0cd_idx',
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['created_date', 'player_count'], name='bingosync_r_created_7d3923_idx'),
        ),
    ]
